(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.back = function() {
	this.initialize(img.back);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1094,117);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,92);


(lib.molecule = function() {
	this.initialize(img.molecule);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,122,122);


(lib.oim = function() {
	this.initialize(img.oim);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,174,174);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.molecule();
	this.instance.parent = this;
	this.instance.setTransform(568,100.7,0.418,0.418,180);

	this.instance_1 = new lib.molecule();
	this.instance_1.parent = this;
	this.instance_1.setTransform(335,37.1,0.598,0.598,69);

	this.instance_2 = new lib.molecule();
	this.instance_2.parent = this;
	this.instance_2.setTransform(365.9,44.2,0.418,0.418,150);

	this.instance_3 = new lib.molecule();
	this.instance_3.parent = this;
	this.instance_3.setTransform(273,58.7,0.418,0.418,180);

	this.instance_4 = new lib.molecule();
	this.instance_4.parent = this;
	this.instance_4.setTransform(475.1,42.5,0.598,0.598,114);

	this.instance_5 = new lib.molecule();
	this.instance_5.parent = this;
	this.instance_5.setTransform(124,23.7,0.598,0.598);

	this.instance_6 = new lib.molecule();
	this.instance_6.parent = this;
	this.instance_6.setTransform(115,48.7,0.418,0.418,90);

	this.instance_7 = new lib.molecule();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,27.7,0.598,0.598);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(0,0,568,131.3), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTBOQgGAAgFgCIgJgEQgQgLAAgSIAAhUQAAgfAdgEIAGgBIBMAAIAAAXIhKAAQgMAAgCALIgBACIAAAUIA0AAQAQAAALAJQAFAFACAGQADAFAAAIIAAAfQAAAIgDAHQgEAHgGAFQgFAEgFACQgFACgFAAgAgUABQgNABAAALIAAAcQAAAFAGAFQAFAEAGAAIAlAAIAFgBQAGgCABgIIABAAIAAgeQAAgHgDgDQgDgCgHgBIgBgBIgnAAIgBABg");
	this.shape.setTransform(480.8,50.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AABBOIAAiEIgYAAIAAgXIAtAAIACAAIAACbg");
	this.shape_1.setTransform(465.6,50.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHBOQgPAAgLgGQgLgFgGgLIgDgKQgCgGAAgGIAAhDQAAgKADgIQADgIAFgGQAHgHAKgDQAGgCAOAAIAQAAQANAAAGACQAKADAHAHQAGAGACAIQADAIAAAKIAABDQAAAVgLALQgHAIgKACQgGACgNAAgAgSg2QgJACgDAFQgCAEgBAJIAABFQABAJACAFQADAFAJABIAHAAIAXAAIAIAAQAIgBADgFQACgFAAgJIAAhFQAAgLgDgEQgEgEgLgBIgDAAIgXAAg");
	this.shape_2.setTransform(452.9,50.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgxBOIAAgwQAAgKADgIQADgHAGgFQALgHALAAIAfAAQADAAAEgDQACgBABgEIABgEIAAgYQgBgJgIgCIgCAAIhBAAIAAgXIA/AAQAUAAAKAOQAFAJABAJIAAAbQAAAJgEAGQgDAGgIAFIgJAFIgKABIgcAAQgIAAgCAEQgEADAAAHIAAAbIBMAAIAAAXg");
	this.shape_3.setTransform(438.9,50.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAeA6IgegrIgdArIgXAAIApg7Igng4IAYAAIAaAnIAbgnIAYAAIgnA4IApA7g");
	this.shape_4.setTransform(420.3,52.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPA6QgHAAgHgCQgFgCgFgEQgJgJABgNIAAg0QgBghAkAAIAcAAQAIAAAFACQAGACAEAEQAEAEACAFQACAGAAAGIAAAOIhLAjIAAAFQABAHADADQACADAIAAIA/AAIAAATgAgYgiQgEAEAAAHIAAAXIA3gaIAAgCQAAgKgLAAIgfAAQgGAAgDAEg");
	this.shape_5.setTransform(409,52.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSBOQgFAAgHgDQgRgIAAgUIAAg3QAAgPAIgHQAFgEAFgCQAGgCAHAAIAtAAIAAgnIATAAIAAB6QAAAMgIALQgJAKgMAAgAgZgPQgDADAAAHIAAAzIABABQAAAGADADQACACAFAAIAhAAQAEAAADgCQAGgEAAgIIAAgyQAAgMgLAAIghAAQgGAAgEADg");
	this.shape_6.setTransform(396.6,50.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAdA6IAAhYQgCgHgMAAIgdAAQgIAAgDACQgDADAAAHIAABTIgTAAIAAhVQAAgeAhAAIAdAAQARAAAIAHQAIAIAAAPIAABVg");
	this.shape_7.setTransform(384.3,52.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKBOIAAibIAVAAIAACbg");
	this.shape_8.setTransform(375.7,50.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAdBOIAAhTIAAgCQgBgFgCgDQgCgCgEgBIgiAAQgHAAgDADQgEADAAAHIAABTIgTAAIAAibIATAAIAAAnIAwAAQAQAAAIANQAEAHAAAIIAABYg");
	this.shape_9.setTransform(360.8,50.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgFA6QgJAAgIgEQgHgEgEgHQgFgGAAgIIAAg5QABgHACgGQACgFAEgEQAJgHAPAAIAsAAIAAATIgsAAQgNAAAAANIAAAxQAAAGAEAFQADAEAHAAIArAAIAAATg");
	this.shape_10.setTransform(350,52.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQA6QgHAAgFgCQgGgCgEgEQgKgJABgNIAAg0QgBghAlAAIAbAAQAHAAAGACQAGACAEAEQAEAEACAFQACAGAAAGIAAAOIhLAjIAAAFQACAHABADQADADAHAAIBAAAIAAATgAgZgiQgDAEAAAHIAAAXIA3gaIAAgCQAAgKgLAAIgfAAQgGAAgEAEg");
	this.shape_11.setTransform(339,52.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgKBOIAAiEIgiAAIAAgXIBZAAIAAAXIgiAAIAACEg");
	this.shape_12.setTransform(328.2,50.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBNIAAgTIBCAAQAFgBACgDQADgDAAgGIAAgGIgwAAQgMAAgIgIQgEgEgCgFQgCgFAAgGIAAhXIATAAIAABSQAAAHAEADQADAEAHAAIAdAAQAHAAADgDQAEgDAAgGIAAhUIATAAIAAB4QAAAIgCAGQgCAGgDAEQgJAJgPAAg");
	this.shape_13.setTransform(311.2,54.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaA6IAAhWIABgHQAFgWAZAAIAWAAIAAATIgYAAQgEABgDAEQgCAEAAAFIAABSg");
	this.shape_14.setTransform(301.9,52.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAcA6IAAguIg4AAIAAAuIgTAAIAAhzIATAAIAAAyIA4AAIAAgyIAUAAIAABzg");
	this.shape_15.setTransform(291.7,52.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgOA6QghAAAAgeIAAhVIATAAIAABYQACAIALAAIAhAAQAFgBADgDQADgEAAgFIAAhTIATAAIAABzg");
	this.shape_16.setTransform(279.4,52.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAwA6IAAhUQAAgLgMAAIgRAAQgEAAgCAEQgCADAAAFIAABTIgSAAIAAhUIgBgCQgCgJgKAAIgPAAIgCAAQgFAAgCACQgCACAAAFIAABWIgUAAIAAhWQAAgOAHgIQAHgHANAAIASAAIAFAAQAGABAEADQAFACABAEQADgEAEgCQAEgDAHgBIAEAAIASAAQANAAAHAHQAHAIAAAOIAABWg");
	this.shape_17.setTransform(265.2,52.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgOBMQghAAAAgeIAAhWIATAAIAABZQACAHALABIAhAAQAFgBADgEQADgDAAgGIAAhTIATAAIAAB0gAgKgyQgFgCgEgEQgKgGAAgNIAPAAQACAOANAAQANAAABgOIAQAAQAAAGgCAFQgDAFgFADQgJAIgLgBQgGABgFgCg");
	this.shape_18.setTransform(251.1,50.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPA6QgHAAgHgCQgFgCgFgEQgIgJgBgNIAAg0QABghAjAAIAcAAQAIAAAFACQAGACAEAEQAEAEACAFQACAGAAAGIAAAOIhLAjIAAAFQACAHACADQACADAIAAIA+AAIAAATgAgYgiQgEAEAAAHIAAAXIA4gaIAAgCQAAgKgMAAIgfAAQgGAAgDAEg");
	this.shape_19.setTransform(239.1,52.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag2BOIAAibIBCAAQArAAAAAlIAAAXQABAJgDAHQgDAHgFAFQgGAFgIACQgHADgKAAIguAAIAAA5gAgggBIAuAAQAJAAAFgDQAEgDABgIIAAgXIAAgDQgBgHgEgDQgDgCgHgBIgCAAIgwAAg");
	this.shape_20.setTransform(226.8,50.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSA6QgIAAgGgCQgGgCgDgEQgHgHAAgNIAAg8QAAgMAHgHQAGgGANgCIACAAIAmAAIAFAAQAaAEAAAXIAAA8QAAAQgQAJQgGADgJAAgAgdgYIAAAvQABAQAOAAIAeAAQAHAAADgEQAEgEAAgHIAAgwQAAgHgEgDQgDgEgHAAIgeAAQgOAAgBAOg");
	this.shape_21.setTransform(207.4,52.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAcA6IAAguIg4AAIAAAuIgTAAIAAhzIATAAIAAAyIA4AAIAAgyIAUAAIAABzg");
	this.shape_22.setTransform(195,52.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgFA6QgJAAgIgEQgHgEgFgHQgDgGAAgIIAAg5QgBgHADgGQACgFAFgEQAIgHAOAAIAsAAIAAATIgsAAQgMAAAAANIAAAxQAAAGADAFQAFAEAGAAIAqAAIAAATg");
	this.shape_23.setTransform(184.2,52.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRA6QgJAAgJgGQgHgGgDgIQgCgFAAgGIAAgOQAAgPAGgJQAFgGAFgDQAFgCAIAAIAvAAIAAgIQAAgDgCgCQgCgDgDAAIhFAAIAAgTIBDAAQAMAAAHAFQAHAGACAKIAAAGIAAA7QAAAHgDAHQgFAIgGAEQgGADgIAAgAgZAAQgDADAAAGIAAASQAAAIAFACQAEACAHAAIAZAAQAQAAAAgMIAAgSQAAgGgDgDQgEgCgGgBIgeAAQgHABgEACg");
	this.shape_24.setTransform(172.9,52.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAdA6IAAhYQgCgHgLAAIgRAAQgHAAgEACQgDADAAAHIAAA1QABAegiAAIAAgTQAIAAADgDQADgDAAgHIAAg1QAAgeAhAAIARAAQAQAAAIAHQAIAIAAAPIAABVg");
	this.shape_25.setTransform(160.5,52.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgaA6IAAhWIABgHQAGgWAXAAIAXAAIAAATIgZAAQgDABgDAEQgCAEgBAFIAABSg");
	this.shape_26.setTransform(151.2,52.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgSA6QgIAAgGgCQgGgCgDgEQgHgHAAgNIAAg8QAAgMAHgHQAGgGANgCIACAAIAmAAIAEAAQAbAEAAAXIAAA8QAAAQgQAJQgGADgJAAgAgdgYIAAAvQABAQAOAAIAeAAQAHAAADgEQADgEABgHIAAgwQgBgHgDgDQgDgEgHAAIgeAAQgOAAgBAOg");
	this.shape_27.setTransform(140.9,52.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgFA6QgKAAgHgEQgIgEgEgHQgDgGAAgIIAAg5QAAgHACgGQACgFAFgEQAIgHAOAAIAsAAIAAATIgsAAQgMAAAAANIAAAxQAAAGADAFQAFAEAFAAIArAAIAAATg");
	this.shape_28.setTransform(130,52.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgIAjIAIgiIgZAZIgIgRIAhgJIgigIIAJgRIAZAZIgIgiIASAAIgIAiIAYgZIAJARIghAIIAhAKIgJAQIgagZIAKAig");
	this.shape_29.setTransform(120.6,46.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(114.5,39.7,375.3,25.9), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAmIAJgkIgbAaIgJgSIAkgKIgkgJIAJgSIAbAbIgJglIAUAAIgJAlIAagaIAJASIgjAIIAjAKIgJATIgbgcIAJAlg");
	this.shape.setTransform(193.4,-127.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACBbIAAiaIgdAAIAAgbIA1AAIACAAIAAC1g");
	this.shape_1.setTransform(182.6,-117.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaBKIg3iBIAACRIgaAAIAAibQAAgbAWAAIAIABQAKADAHAOIA2CFIAAiVIAaAAIAACeQAAAKgGAHQgFAHgJABIgDAAQgPAAgIgTgAAkAPIAAgRIBIAAIAAARgABHgMQgWAAgJgRQgEgIAAgJIAAgKQAAgIACgGQACgHAEgEQAGgGAHgCQAGgBAIAAIACAAQAIAAAFABQAIACAFAGQAJAJAAAQIAAAKQAAARgJAIQgFAGgIACIgNABgAA3hDQgBADAAAHIAAAMQAAAHABAEQADADAGABIAFABIAGAAIAFgBQAGgBACgDQACgEAAgHIAAgMQgBgIgCgEQgDgDgGAAIgDAAIgGAAIgFAAQgGABgDAEg");
	this.shape_2.setTransform(164.3,-117.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgKgHQgJgHgEgKQgCgFAAgHIAAgRQAAgRAIgLQAFgHAGgDQAHgDAJAAIA3AAIAAgJQAAgEgDgDQgCgCgEAAIhRAAIAAgXIBQAAQANAAAIAGQAIAGADANIABAGIAABGQAAAJgFAIQgGAIgHAEQgHAFgJAAgAgdAAQgEADAAAHIAAAWQAAAJAGACQAEACAJAAIAdAAQATAAAAgNIAAgWQAAgHgEgDQgEgDgIAAIgjAAQgIAAgEADg");
	this.shape_3.setTransform(137.5,-115);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBAQgEgEgDgKIgihcIAABtIgXAAIAAhtQgBgTAPgGQALgDAIAFQAHAFAFAMIAgBaIAhhaQAFgMAHgFQAIgFALADQAIADADAGQAEAGgBAKIAABtIgXAAIAAhtIgiBcQgDAKgEAEQgFAFgJAAQgHAAgGgFg");
	this.shape_4.setTransform(120.7,-115);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag4BaIAAiRQAAgIACgHQADgGAFgEQAIgJASAAIApAAQAHAAAGABQAGACAEACQAGAFADAHQAEAHAAAJIAABAQAAAIgDAGQgCAGgEAFQgLANgPAAIg4AAIAAAsgAgdg/QgFADAAAHIAAA8IABADQABAHADACQAFAEADAAIAqAAIACAAQAJgCACgJIAAgCIAAhCQgBgFgBgCQgDgCgFgBIgpAAQgJAAgDADg");
	this.shape_5.setTransform(104,-112.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgGgDQgHgBgFgFQgHgJAAgQIAAhFQAAgOAHgIQAIgIAPgCIADAAIArAAIAGABQAfAEAAAbIAABFQAAATgTALQgHAEgLAAgAgigcIAAA3QAAATARgBIAkAAQAHABAEgFQAFgFAAgIIAAg4QAAgIgFgEQgEgEgHAAIgkAAQgRAAAAAQg");
	this.shape_6.setTransform(89.4,-115);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJBzIAAhHQgGANgGAFQgHAFgJAAQgiAAAAhHQAAhDAjAAQASAAAJAUIAAg/IATAAIAAA/QAJgUASAAQAjAAAABDQAABHgiAAQgJAAgHgFQgHgFgFgNIAABHgAARgsQgHAKAAADIAAA2QAHAQAFAFQAFAFAGAAQAJAAAEgLQAFgLAAgeQAAgVgCgKQgDgKgEgFQgEgFgHAAQgHAAgHAKgAgtgrQgFAKAAAeQAAAVACALQACAKAEAFQAEAFAGAAQAFAAAFgDQAEgEAFgJIAEgKIAAg2QgEgLgGgGQgFgGgGAAQgKAAgFALg");
	this.shape_7.setTransform(74.4,-114.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AA3BEIAAhiQAAgNgNgBIgUAAQgFABgCAEQgCADAAAHIAABhIgWAAIAAhjIAAgCQgDgLgMAAIgRAAIgDAAQgGABgCACQgCACAAAGIAABlIgXAAIAAhlQAAgRAHgIQAJgJAPAAIAUAAIAHABQAGABAFACQAGADACAFQADgFAEgDQAGgCAHgBIAGgBIAUAAQAQAAAIAJQAIAIAAARIAABlg");
	this.shape_8.setTransform(57.3,-115);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgKgHQgJgHgEgKQgCgFAAgHIAAgRQAAgRAIgLQAFgHAGgDQAHgDAJAAIA3AAIAAgJQAAgEgDgDQgCgCgEAAIhRAAIAAgXIBQAAQANAAAIAGQAIAGADANIABAGIAABGQAAAJgFAIQgGAIgHAEQgHAFgJAAgAgdAAQgEADAAAHIAAAWQAAAJAGACQAEACAJAAIAdAAQATAAAAgNIAAgWQAAgHgEgDQgEgDgIAAIgjAAQgIAAgEADg");
	this.shape_9.setTransform(40.7,-115);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAiBEIAAhoQgCgIgOAAIgUAAQgIAAgEADQgDADAAAJIAAA+QAAAjgnAAIAAgXQAJAAAEgDQADgDAAgJIAAg+QAAgjAmAAIAUAAQATAAAKAJQAKAIAAASIAABkg");
	this.shape_10.setTransform(26.2,-115);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAhBEIAAhoQgCgIgNAAIgjAAQgJAAgDADQgEADAAAJIAABhIgWAAIAAhkQAAgjAmAAIAjAAQATAAAJAJQAKAIAAASIAABkg");
	this.shape_11.setTransform(11.9,-115);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAbBEIg3g7QgGgFAAgFQAAgHAGgFIA0g2IAgAAIhABBIBCBGgAg5BEIAAiHIAWAAIAACHg");
	this.shape_12.setTransform(180.5,-147.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRBEQgmAAAAgjIAAhkIAWAAIAABoQACAIAOAAIAmAAQAGgBADgEQADgDAAgHIAAhhIAXAAIAACHg");
	this.shape_13.setTransform(165.9,-147.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AA4BEIAAhjQAAgMgPAAIgTAAQgFAAgCADQgDAFABAFIAABiIgWAAIAAhjIAAgBQgCgMgMAAIgSAAIgDABQgFAAgCACQgCADgCAFIAABlIgWAAIAAhkQAAgSAIgIQAHgJAQAAIAVAAIAFAAQAHABAGADQAFADACAFQACgFAFgDQAGgDAIgBIAFAAIAVAAQAPAAAIAJQAIAIAAASIAABkg");
	this.shape_14.setTransform(149.4,-147.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgKgHQgJgHgEgKQgCgFAAgIIAAgQQAAgRAIgLQAFgGAGgEQAHgDAJAAIA3AAIAAgJQAAgEgDgCQgCgDgEAAIhRAAIAAgXIBQAAQANAAAIAGQAIAHADAMIABAGIAABFQAAAKgFAHQgGAJgHAFQgHAEgJAAgAgdAAQgEAEAAAGIAAAWQAAAIAGADQAEACAJABIAdAAQATAAAAgOIAAgWQAAgGgEgEQgEgCgIgCIgjAAQgIACgEACg");
	this.shape_15.setTransform(132.8,-147.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNBAQgEgEgDgKIgihcIAABtIgXAAIAAhtQgBgTAPgGQALgDAIAFQAHAFAFAMIAgBaIAhhaQAFgMAHgFQAIgFALADQAIADADAGQAEAGgBAKIAABtIgXAAIAAhtIgiBcQgDAKgEAEQgFAFgJAAQgHAAgGgFg");
	this.shape_16.setTransform(116,-147.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgNBAQgEgEgDgKIgihcIAABtIgXAAIAAhtQgBgTAPgGQALgDAIAFQAHAFAFAMIAgBaIAhhaQAFgMAHgFQAIgFALADQAIADADAGQAEAGgBAKIAABtIgXAAIAAhtIgiBcQgDAKgEAEQgFAFgJAAQgHAAgGgFg");
	this.shape_17.setTransform(97,-147.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgKgHQgJgHgEgKQgCgFAAgIIAAgQQAAgRAIgLQAFgGAGgEQAHgDAJAAIA3AAIAAgJQAAgEgDgCQgCgDgEAAIhRAAIAAgXIBQAAQANAAAIAGQAIAHADAMIABAGIAABFQAAAKgFAHQgGAJgHAFQgHAEgJAAgAgdAAQgEAEAAAGIAAAWQAAAIAGADQAEACAJABIAdAAQATAAAAgOIAAgWQAAgGgEgEQgEgCgIgCIgjAAQgIACgEACg");
	this.shape_18.setTransform(80.3,-147.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag4BaIAAiRQAAgIACgHQACgGAFgEQAKgJAQAAIAqAAQAHAAAGABQAFACAEACQAHAFAEAHQADAHAAAJIAABAQAAAIgCAGQgCAGgFAFQgLANgPAAIg3AAIAAAsgAgeg/QgDADAAAHIAAA8IAAADQABAHADACQAEAEAEAAIAqAAIACAAQAJgCACgJIAAgCIAAhCQgBgFgCgCQgCgCgFgBIgpAAQgIAAgFADg");
	this.shape_19.setTransform(65.8,-144.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgeBEIAAhkIABgIQAGgbAcAAIAbAAIAAAXIgdAAQgFACgDADQgDAEAAAHIAABgg");
	this.shape_20.setTransform(54.8,-147.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgVBEQgKAAgGgCQgIgCgDgFQgIgJAAgQIAAhFQAAgOAIgIQAHgIAPgCIADAAIArAAIAGAAQAfAFAAAbIAABFQAAATgTALQgHAEgLAAgAgigcIAAA4QAAASARAAIAjAAQAJAAADgFQAFgFAAgIIAAg4QAAgIgFgEQgDgEgJAAIgjAAQgRAAAAAQg");
	this.shape_21.setTransform(42.8,-147.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag4BaIAAiRQAAgIACgHQADgGAFgEQAIgJASAAIApAAQAHAAAGABQAFACAFACQAGAFAEAHQADAHAAAJIAABAQAAAIgDAGQgCAGgEAFQgLANgPAAIg4AAIAAAsgAgdg/QgFADAAAHIAAA8IABADQABAHADACQAEAEAEAAIAqAAIACAAQAJgCACgJIAAgCIAAhCQAAgFgDgCQgBgCgGgBIgpAAQgJAAgDADg");
	this.shape_22.setTransform(28.3,-144.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAnBbIAAiaIhOAAIAACaIgaAAIAAi1ICDAAIAAC1g");
	this.shape_23.setTransform(12.9,-149.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ37, new cjs.Rectangle(2.6,-161.9,197.6,62.4), null);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao9D9QhpABhLhLQhKhKAAhpQAAhoBKhLQBLhJBpgBIR7AAQBqABBJBJQBLBLAABoQAABphLBKQhJBLhqgBg");
	this.shape.setTransform(95.1,29.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ35, new cjs.Rectangle(12.4,4.1,165.6,50.7), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBSQhSBSh0AAIx9AAQh0AAhShSQhShSAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ34, new cjs.Rectangle(-1,-1,173,58), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AicBdQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAaiGQABgEAEAAIAJAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBAEQAHgFAHgCQAJgDAIAAQAKAAAJAEQAIADAFAHQAFAHACAKQABAOgCAIQgFAQgDAHQgGAJgIAIQgIAHgJADQgKAEgKAAQgIAAgIgDQgGgCgFgFIgIArQAAADgFAAgAhqggQgIADgGAGIgLA1QAEAGAHADQAGADAIAAQAHAAAHgCQAGgDAGgFQAFgFAEgHQAEgIACgJQACgJgBgHQgBgIgEgFQgDgEgGgDQgFgCgHAAQgJAAgHADgAi7BLQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIADgQIhIAAIgEAQQgBAEgDAAIgJAAQgEAAABgEIAFgbQABgEADAAIAGAAQAJgKAGgKIANgUIAKgWIAIgWQABgEADAAIAtAAQABAAAAAAQABABAAAAQABABAAAAQAAABgBABIgQBUIAMAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgFAbQgBAEgEAAgAjdAEQgOAYgKAMIAtAAIAPhJIgVAAQgJAZgGAMgAHAA4IgKgDQgIgEgGgHQgFgHgBgKQgCgKACgMQADgMAFgKQAGgKAIgHQAIgHALgDQAKgEAMAAQAJAAAHACQAHACAFAEQAFAEACAGQACAFgBAHQgBAHgEAFQgFAGgHADQgHAEgLACQgMADgPAAIgVAAQgBAIACAGQACAGAEAEQADAEAGACQAGACAHAAQAIAAAHgBQAHgCAGgDQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAIABACIgBAJQAAADgEACQgGADgIABQgIACgJAAgAHQgiQgGACgFAEQgGAEgDAGQgEAGgDAIIARAAIAUgBQAIgBAGgCQAFgCADgDQADgDABgEQAAgEgBgDQgBgDgDgCQgGgDgMAAQgHAAgGABgAFUA4IgKgDQgJgEgFgHQgFgHgCgKQgBgKACgMQACgMAGgKQAFgKAJgHQAIgHAKgDQALgEALAAQAJAAAIACQAHACAFAEQAFAEACAGQACAFgCAHQgBAHgEAFQgEAGgHADQgIAEgLACQgLADgPAAIgVAAQgBAIACAGQABAGAEAEQAEAEAGACQAFACAHAAQAIAAAHgBQAIgCAGgDQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAAAIABACIAAAJQgBADgDACQgHADgIABQgIACgJAAgAFjgiQgGACgFAEQgFAEgEAGQgEAGgCAIIARAAIAUgBQAIgBAFgCQAGgCADgDQADgDAAgEQABgEgBgDQgCgDgDgCQgGgDgLAAQgHAAgHABgABvA4QgGgBgEgDQgEgCgDgDIgGgIQgDgGgCgPQAAgJADgSIAEgSQADgJAEgHQADgHAFgGQAFgHAGgFQAGgFAHgEQAIgEAJgDIAUgFIAXgDQAEgBAAAEIgBAIQgBADgDABQgRABgNADQgNAEgJAFQgKAFgGAIQgHAIgEALQAHgGAJgDQAIgCAJAAQAKAAAHADQAIADAEAHQAFAGABAKQACAJgDALQgCAMgFAKQgFAJgIAHQgHAGgJAEQgIADgKAAQgGAAgFgBgAB5gZQgKAEgIAIIgBAEQgCANAAAKQABAKADAGQADAHAFADQAGACAHAAQAGAAAGgCQAFgDAFgEQAEgFADgHQAEgGABgJQACgHgBgHQAAgGgDgFQgDgFgEgCQgFgDgGAAQgKAAgIAEgAgDA4IgJgDQgJgEgFgHQgFgIgBgJQgCgKACgMQADgLAFgKQAGgKAHgHQAIgHAJgEQAHgDAPgBQAIAAAMAEQAIAEAFAHQAGAHABAKQACAKgDALQgCAMgFAKQgGAJgIAIQgIAHgKAEQgKAEgLAAgAALghQgHADgEAFQgGAFgDAIQgEAHgCAIQgBAJABAHQABAIADAFQADAFAFADQAFACAIAAQAHAAAHgCQAHgDAFgFQAFgGAEgHQAEgHABgJQACgIgBgHQgBgIgDgFQgDgFgGgDQgFgCgIAAQgIAAgGACgAlbA4IgJgDQgJgEgFgHQgFgIgBgJQgCgKACgMQADgLAFgKQAGgKAHgHQAIgHAKgEQAHgDAPgBQAIAAAMAEQAIAEAFAHQAGAHABAKQACAKgDALQgCAMgFAKQgGAJgIAIQgIAHgKAEQgKAEgLAAgAlMghQgHADgFAFQgGAFgDAIQgEAHgCAIQgBAJABAHQABAIADAFQADAFAFADQAGACAIAAQAHAAAHgCQAHgDAFgFQAFgGAEgHQAEgHABgJQACgIgBgHQgBgIgDgFQgDgFgGgDQgFgCgIAAQgIAAgGACgAEJA3QgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAIgtIg3AAIgJAtQAAAEgEAAIgJAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAShfQABgEAEAAIAJAAQABAAABAAQABABAAAAQAAABAAAAQABABgBABIgHAkIA3AAIAHgkQABgEAEAAIAJAAQAEAAgBAEIgTBfQAAAEgEAAgAmoA3QAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAYh4IhJAAIgXB4IgCACIgDACIgKAAQAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAaiDQAAgEAFAAIBkAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgaCDIgCACIgDACg");
	this.shape.setTransform(51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(0,0,103.5,18.7), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao/D/QhqgBhKhKQhLhLAAhpQAAhpBLhKQBKhLBqAAIR/AAQBqAABKBLQBKBKABBpQgBBphKBLQhKBKhqABg");
	this.shape.setTransform(83.5,27.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0.5,1.8,166.1,50.9), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBSQhSBSh0AAIx9AAQh0AAhShSQhShSAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(-1,-1,173,58), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah8DVQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAQhSQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgBADQAEgDAEgCQAGgCAFAAQAGAAAFADQAFACADAEQADAEABAGQABAJgBAFIgFAOQgEAGgFAEQgEAFgGACQgGACgGAAQgFAAgFgCQgEgBgCgDIgGAaQAAAAAAAAQAAABAAAAQgBAAAAAAQgBABAAAAgAheCIQgFACgDAEIgHAgQADAEAEACQAEACAFAAQAEAAAEgCQAEgBADgDIAGgHIADgLIABgKQgBgFgCgDIgFgEQgEgCgEAAQgFAAgFACgAGVC/IgGgCQgFgDgDgEQgDgFgBgGQgBgGACgHQABgHADgGQAEgGAEgEQAFgFAGgCIANgDQAFAAAHADQAGACADAFQADAEABAGQABAGgCAHQgBAHgDAGQgEAGgEAFQgFAEgGADQgGACgHAAgAGeCIIgHAFQgEADgCAEIgDAKIAAAKQAAAFACADQACADADABQAEACAEAAQAFAAAEgCQAEgBADgDQAEgEACgEQACgFABgFIABgKIgDgHQgCgDgDgCQgEgCgEAAQgFAAgEACgACtC/QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIACgEQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAEAAIAGgBQADAAACgCQACgCABgDIACgIIAHglQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAlAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgGAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAKgzIgVAAIgGAhQgBAFgDAFQgCAEgDADQgDACgFACQgEABgFAAgAAoC+IgGgCIgEgDIgEgFIgDgNIACgRIADgLIAEgJIAEgIIAHgHIAIgGIAKgEIAMgDIAPgCQAAgBABAAQAAABAAAAQABAAAAAAQAAABAAABIgBAFQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgSADIgOAFQgGADgDAFQgEAFgDAGQAEgDAGgCIAKgBQAGAAAFABQAEACADAEQADAEAAAGQABAGgBAHQgBAHgEAGQgDAGgEAEQgFAEgFACQgFACgGAAIgHgBgAAuCMQgGADgEAFIgBACQgCAJABAGQAAAGACAEQACAEADABQADACAFAAQAEAAADgCIAGgEQADgDABgEQADgEABgFIAAgJQAAgEgCgDQgCgDgCgBQgDgCgEAAQgGAAgFACgAkaC9QgFgCgDgFQgDgEgBgGQgCgGACgIQABgFAEgJQADgGAFgEQAFgEAGgCQAFgDAHAAQAFAAAEACQAEACADADIAAgDQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIABgCQgEADgFABQgFACgFAAQgGAAgFgCgAkLCIQgEABgEADIgFAIIgEAKQgBAGABAEQABAFACADQACADADABQADACAEAAQAGAAAFgCQAEgCAEgEIAGggQgCgEgEgCQgEgCgFAAIgIACgAl1C/QAAAAgBgBQAAAAAAAAQgBAAAAgBQABAAAAgBIABgEQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAEAAIAGgBIAEgCIADgFIACgIIAIglQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAgBABIgLA6QAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAKgzIgVAAIgHAhQgBAFgCAFIgGAHQgDACgEACQgEABgGAAgAn6C+IgFgCIgFgDIgDgFQgCgEgBgJQgBgFACgMIADgLIAEgJIAFgIIAGgHIAJgGIAKgEIAMgDIAOgCQABgBAAAAQABABAAAAQAAAAAAAAQAAABAAABIAAAFQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgSADQgIACgFADQgGADgEAFQgEAFgDAGQAFgDAFgCIAKgBQAGAAAFABQAEACADAEQADAEABAGQABAGgCAHQgBAHgDAGQgDAGgFAEQgEAEgGACQgFACgGAAIgHgBgAnzCMQgGADgFAFIgBACQgBAJAAAGQAAAGACAEQACAEADABQAEACAEAAQAEAAADgCIAGgEQADgDACgEIADgJIAAgJQAAgEgCgDQgBgDgDgBQgDgCgEAAQgFAAgFACgAH4C+QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAJguIgrAvQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIgHAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABIgJAvIArgwIADgBIAHAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA6QAAABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAFoC+QAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAGgbIgiAAIgFAbQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIALg6QAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgEAWIAhAAIAFgWQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAgAD7C+QAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAMg6QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgEAUIAMAAQAIAAAFABQAGABADADQADACACAEQABAEgBAFQgBAGgDADQgCAEgFADQgEACgGABQgGACgIAAgAEFC1IAMAAIAKgBIAHgCIAEgEQABgBABgEIAAgFQAAgBgBAAQAAgBAAAAQgBgBAAAAQgBgBAAAAIgGgCIgJAAIgMAAgACaC+QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIALg6QAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA6QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAgABaC+QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgEAUIALAAQAIAAAGABQAFABAEADQADACABAEQACAEgBAFQgBAGgDADQgDAEgEADQgFACgGABQgGACgHAAgABkC1IAMAAIAKgBIAGgCIAEgEQACgBAAgEIAAgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAgBgBAAIgFgCIgJAAIgNAAgAgDC+QAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAIguIgpAvIgDACIgIAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAMg6QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgJAvIApgwIADgBIAIAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgLA6QAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAgAiSC+QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAKgzIgfAAIgKAzQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIALg6QAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAvAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAgAmIC+QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAgAnIC+QAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAMg6QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgEAUIAMAAQAHAAAGABQAGABADADQADACACAEQABAEgBAFQgBAGgDADQgDAEgEADQgEACgGABQgGACgIAAgAm+C1IAMAAIAKgBIAGgCQADgBABgDIADgFIAAgFIgDgEIgGgCIgJAAIgNAAgAHqB0QgDAAgCgDIgDgEQgBgDAAgEQAAgBAAgBQABAAAAAAQAAgBABAAQAAAAABAAIAEAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAAEADACQACADAEAAQAEAAADgDQAEgCABgEQABgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAEAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABQgBAEgDADIgFAEQgDADgDAAQgEACgEAAIgHgCgAhVA5QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAQhRQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAADQAEgDAEgCQAFgCAGAAQAGAAAFADQAFACADAEQADAEABAGQABAJgCAEIgEAOQgEAGgFAEQgFAFgFACQgGACgGAAQgFAAgFgCQgEgBgDgDIgFAaQAAAAAAAAQAAABAAAAQgBAAAAAAQgBABAAAAgAg3gTQgFACgDAEIgHAfQADAEAEACQAEACAEAAQAFAAAEgCQAEgBADgDQADgDACgEIAEgLIABgJQgBgFgCgDQgCgDgEgBQgDgCgEAAQgFAAgFACgAFjAhQgEgCgDgFQgEgEgBgGQgBgGACgIQAAgEAEgJQAEgGAFgEQAEgEAGgCQAGgDAGAAQAGAAAEACQAEACACADIABgDQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABIgLA5QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgCQgDADgFABQgFACgGAAQgGAAgFgCgAFygTQgEABgDADQgDADgCAFIgEAJQgBAGABAEQAAAFACADQACADADABQAEACAEAAQAFAAAFgCQAFgCADgEIAHgfQgCgEgEgCQgEgCgGAAIgIACgADIAhQgFgCgDgFQgDgEgBgGQgBgGABgIQABgEAEgJQAEgGAFgEQAEgEAGgCQAGgDAGAAQAFAAAFACQAEACACADIABgDQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA5QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgCQgEADgEABQgFACgGAAQgGAAgFgCgADXgTQgEABgDADIgGAIIgDAJQgBAGABAEQAAAFACADQACADADABQAEACAEAAQAFAAAFgCQAFgCADgEIAHgfQgDgEgEgCQgDgCgGAAIgIACgABuAjQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIACgEQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAEAAIAGgBIAFgCIADgFIACgIIAHgkQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAlAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgMA5QAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgGAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAKgyIgVAAIgHAgQAAAFgDAFIgFAHQgDACgFACQgEABgFAAgAAIAjIgGgCQgFgDgDgEQgDgEgBgGQgBgGABgIQACgHADgGQAEgGAEgEQAFgEAGgCQAGgDAHAAIAKABQAFACADACQADADABADQABAEgBADQAAAFgDADIgHAFQgEADgHABQgHABgJAAIgMAAQgBAFABAEQABAEACACQACADAEABQADABAEAAIAKgBIAIgDIACgBIAAACIAAAFQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgJADQgFABgFAAgAARgUQgEABgDADQgDACgCAEIgEAIIAKAAIAMAAIAJgCIAFgDQAAgBABAAQAAgBAAgBQABAAAAgBQAAAAAAgBIAAgDIgDgEQgEgCgHAAIgIABgAivAhQgFgCgDgFQgDgEgBgGQgBgGABgIIAFgNQADgGAFgEQAFgEAGgCQAGgDAGAAQAFAAAEACQAFACACADIABgDQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgMA5QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIABgCQgEADgFABQgFACgFAAQgGAAgFgCgAiggTQgEABgDADQgEADgCAFIgEAJIAAAKQABAFACADQACADADABQADACAFAAQAFAAAFgCQAEgCAEgEIAGgfQgCgEgEgCQgEgCgFAAQgEAAgEACgAlLAhQgFgCgDgFQgDgEgBgGQgBgGABgIIAFgNQADgGAFgEQAFgEAGgCQAGgDAGAAQAFAAAEACQAFACACADIABgDQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgMA5QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIABgCQgEADgFABQgFACgFAAQgGAAgFgCgAk8gTQgEABgDADQgEADgCAFIgEAJIAAAKQABAFACADQACADADABQADACAFAAQAFAAAFgCQAEgCAEgEIAGgfQgCgEgEgCQgEgCgFAAQgEAAgEACgAE8AiQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAJgsIgZAZIgCABIgEAAIgCgBIgOgZIgJAsQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIALg5QAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAIACABIARAdIAdgdIACgBIAHAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgMA5QAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAgABfAiQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAIgXgdIgGAcQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg5QAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgFAaIAegaQADgCACAAIAIAAIABAAIgBACIghAbIAYAeIABACIgCABgAkRAiQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAMg5QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIAGAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIgKAzIATAAIAKgzQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgKAzIATAAIAKgzQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA5QAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAgAmWAiQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAgBIAMg5QAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIARAAIALABIAIACIAFAGQABADgBAEQAAAEgDADQgEAEgGABIAGADIADADIACAFQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAABQgBAEgDADQgCAEgEACIgKADQgGACgHAAgAmNAZIAKAAIAJgBIAHgCIAEgDIACgEIgBgEIgDgDIgFgCIgKgBIgJAAgAmHgCIAQgBIAGgBIAEgDIABgEQABgBAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAIgGgBIgQAAgAgLhpIAAgCIAAgBQADgCACgEIADgGQgDAAgBgCQAAgBgBAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQABgEACgCQACgBADAAQAEAAABACQABACgBAFIgCAGIgDAFIgEAGIgFAEIAAAAIgCgBgAithtQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIACgKIgsAAIgCAKQAAAAgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgFAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAAAIADgRQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIADAAQAGgGADgGIAIgNIAGgNIAFgOQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAbAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAABIgKA0IAIAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgEARQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAgAjCiYQgIAPgGAHIAbAAIAJgtIgMAAQgGAPgEAIgAESh5IgGgCIgEgDIgEgFIgDgNIACgRIADgLIAEgJIAEgIIAHgHIAIgGIAKgEIAMgDIAPgCQAAgBABAAQAAABAAAAQABAAAAAAQAAABAAABIgBAFQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgSADIgOAFQgGADgDAFQgEAEgDAHQAEgDAGgCQAFgCAFAAQAGAAAFACQAEACADAEQADAEAAAGQABAGgBAHQgBAHgEAGQgDAGgEAEQgFAEgFACQgFACgGAAIgHgBgAEYirQgGADgEAFIgBACQgCAJABAGIACAKQACAEADABQADACAFAAQAEAAADgCIAGgEQADgDABgEQADgEABgFIAAgJIgCgHIgEgEQgDgCgEAAQgGAAgFACgADMh4IgFgCQgFgDgDgEQgDgFgBgGQgBgGABgHQABgHAEgGQADgGAFgEQAFgFAGgCIANgDQAFAAAHADQAFACADAFQADAEABAGQABAGgBAHQgCAHgDAGQgDAGgFAFQgFAEgGADQgGACgHAAgADVivIgHAFQgDADgCAEIgEAKQgBAFABAFIACAIQACADAEABQADACAFAAQAEAAAFgCQAEgBADgDIAFgIIADgKIABgKIgCgHIgGgFQgDgCgFAAQgFAAgEACgAiJh6QgFgCgDgFQgEgEgBgGQgBgGACgIQABgFAEgJQADgGAFgEQAFgEAFgCQAGgDAHAAQAFAAAEACQAEACADADIAAgDQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgMA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBABgBAAIgFAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgCQgDADgFABQgFACgFAAQgHAAgEgCgAh7ivIgHAEQgDADgCAFQgDAEgBAGIAAAKQAAAFADADQABADAEABQADACAEAAQAFAAAFgCQAFgCADgEIAHggQgCgEgEgCQgEgCgFAAQgFAAgEACgAkYh6QgBgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAIABgFQABgBAAAAQAAgBAAAAQABAAAAAAQAAAAABAAQAFACALABIAJgBIAGgBIAEgDIACgEQAAgDgBgCIgEgEIgHgCIgLgBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIABgFQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIALgBIAIgBQAEgCABgCQADgCAAgCQABgEgEgCIgEgBIgIgBQgMABgFABQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAgGQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAFgBANgBIALABIAIADQADACABAEQABADAAAEQgBADgCACIgEAFIgGADIgHACIAHACQADACACACIACAFIAAAFQgBAFgDADQgCADgFADIgKADQgFABgGAAQgNAAgFgCgAlIh4IgGgCQgFgDgDgEQgDgFgBgGQgBgGABgHQACgHADgGQAEgGAEgEQAFgFAGgCIANgDQAFAAAHADQAFACADAFQAEAEABAGQABAGgCAHQgBAHgDAGQgEAGgFAFQgFAEgGADQgGACgHAAgAk/ivIgHAFQgEADgCAEQgCAFgBAFQgBAFAAAFIADAIQACADADABQADACAFAAQAFAAAEgCQAEgBADgDIAFgIIAEgKIAAgKQAAgEgCgDQgCgDgEgCQgDgCgEAAQgFAAgEACgAmIh6QgGgDgDgEQgEgEgBgGIAAgOQABgFAEgIQAEgGAFgFQAFgEAGgCQAHgDAHAAIAJABIAHACQAAAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgCAFQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgHgCIgHgBQgFAAgFACQgEABgEADQgEADgCAFIgEAKQgBAGABAEQABAFACADQADADAEABQAEACAFAAIAIgBIAHgCQABgBAAAAQABAAAAAAQAAAAAAABQAAAAAAABIAAAFQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAIgIACIgJABIgNgCgAGEh5QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA6QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAgAFEh5QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgEAUIALAAQAIAAAGABQAFABAEADQADACABAEQACAEgBAFQgBAGgDADQgDAEgEADQgFACgGABQgGACgHAAgAFOiCIAMAAIAKgBIAGgCIAEgEQACgBAAgEIAAgFQAAgCgDgCIgFgCIgJAAIgNAAgACQh5QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAKgzIgVAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIABgEQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIA0AAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgBAEQAAABgBAAQAAABAAAAQAAAAgBAAQAAABgBAAIgVAAIgKAzQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAgABlh5QAAAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAFgYQgEADgFABIgJABQgFAAgFgCQgDgCgDgDQgCgEgBgFIABgNIACgKQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgCALIgBAIIACAGIAEAEIAGABIAJgCQAFgBADgDIAEgYQABgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAFAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIgLA6QAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAgAgjh5QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAFgbIghAAIgGAbQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgGAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIALg6QAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgFAWIAiAAIAEgWQAAgBAAAAQABgBAAAAQAAAAABAAQAAAAABAAIAFAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgLA6QAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape.setTransform(-169.1,262.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(-221.4,240.9,104.7,42.5), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHoBJQgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgLIAEgNIAGgKIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAHQgBAHgFAGQgFAHgIAEQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAH5gDQgFADgDAIIADAAQAOAAAGgCQAFgCABgEQABgDgCgCQgDgCgFAAQgHAAgFAEgAA5BGQgHgDgFgHQgEgHgCgKQgBgLACgMQADgNAFgJQAGgKAHgHQAHgHAJgEQAIgDAJAAQAJAAAGADQAHADACAFIABgFQABgEAEAAIArAAQAEAAgBAEIgTBfQgBAEgDAAIgrAAQgEAAABgEIAAgFQgEAFgHADQgIADgJAAQgJAAgHgEgABiAAQgEAGgDAOQgCAOABAGQACAFAGAAQAEAAADgCIAJgtQgCgCgEAAQgGAAgEAEgAkUBGIgJgEIgIgHQgEgDgCgEQgCgFgBgFIgBgKIABgMQABgIAIgOQAEgGALgLQAHgEAPgGQAIgDASgBQAJAAAPAEQAGABAEADIAIAGIAFAIIAEAJIABAKIgBAMIgEAMIgFAKQgKANgGAEQgNAJgIACQgRAEgJAAQgSgBgHgDgAj0AAQgEAGgDAOQgDANACAHQACAFAEAAQAFAAAEgFQAEgHACgNQADgOgCgGQgBgEgFAAQgFAAgDAEgAmYBGIgKgEIgIgHQgDgDgCgEQgDgFgBgFIgBgKIABgMQACgIAHgOQAEgGAMgLQAGgEAPgGQAIgDASgBQAKAAAPAEQAFABAEADIAIAGIAGAIIADAJIABAKIgBAMIgDAMIgGAKQgJANgGAEQgOAJgIACQgRAEgJAAQgRgBgHgDgAl5AAQgEAGgDAOQgCANACAHQABAFAFAAQAFAAADgFQAEgHADgNQADgOgCgGQgCgEgEAAQgFAAgEAEgAF+BIQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgJgtIgJAsQAAAEgEAAIgrAAQgEAAABgEIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgOBMIAVgiQADgDACAAIAvAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIggAoIAQAzQAAABABAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAgADzBIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAThfQAAgEAEAAIAsAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgTBfQAAAEgEAAgACtBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgbCKQAAAEgEAAgAhnBIQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgJgtIgJAsQAAAEgEAAIgrAAQgEAAABgEIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgOBMIAVgiQADgDACAAIAvAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIggAoIAQAzQAAABABAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAgAo1BIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAaiDQAAgEAFAAIAuAAQAAAAABAAQABAAAAABQAAAAABABQAAABAAABIgUBjIA7AAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIgGAdQAAAEgEAAgAgeAVQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAFgYQABgEADAAIA1AAQAEAAgBAEIgFAYQAAADgEAAgAETgoQgFgBgDgCQgDgCgBgDQgBgDABgFIADgIQACgDAEgCIAJgDIAMgBIAMABQAFABADACQADACABADQABADgBAFQgBAFgCADQgCADgEACQgEACgFABIgMABg");
	this.shape.setTransform(56.9,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,113.8,14.9), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgGCzIAygzQgTgUAAgdQAAgfAWgWQAWgWAfAAQAfAAAWAWQAWAWAAAfQAAAfgWAWQgWAWgfAAQgdAAgUgTIgzAzgAA2AhQgTATAAAbQAAAbATATQATATAbAAQAbAAATgTQATgTAAgbQAAgbgTgTQgTgTgbAAQgbAAgTATgAhVCDIAVhIIAAgZIgGAAQgnABgbAbQgcAcAAAnIAAAPIgKAAIAAgPQAAgrAfgfQAegeArgBIgLgPQgXgbAAglIAAhGIAKAAIAABGQAAAhAVAaIARAUIAiAAIARgUQAUgaAAghIAAg8QgbgBgdgGQgZgFgPgJIgFgBIAFgJIAEABQAPAJAaAFQAcAGAcAAIAFAAIAABGQAAAlgXAbIgKAPQAPAAATAHIAEABIgDAKIgFgCQgPgGgPAAIgGAAIAAAZIAUBIIgtAtgAhJB/IAiAjIAigjIgSg/IggAAgAg2A2IAeAAIAAgUIgeAAgAAuBaIgBgLQAAgWAQgQQAQgRAXAAIAFAAIAAAKIgFAAQgTAAgNANQgNANAAATIACAOIgKACgAAjgtIAAgKIAFAAQAGAAAFgFQAEgEAAgGQAAgGgEgFQgFgEgGAAIgFAAIAAgoQAAgPgJgNQgJgLgPgFQgYgGgRAAQgRAAgZAGQgPAFgJALQgJANAAAPIAAAoIgFAAQgGAAgFAEQgEAFAAAGQAAAGAEAEQAFAFAGAAIAFAAIAAAKIgFAAQgLAAgGgHQgIgHAAgLQAAgJAFgHQAHgGAIgCIAAgfQAAgSALgQQAMgOARgFQAZgHAUAAQAUAAAYAHQARAFAMAOQALAQAAASIAAAfQAIACAHAGQAFAHAAAJQAAALgHAHQgIAHgKAAgAgdhBIAAgKIAdAAIAAAKgAhPhBIAAgKIAeAAIAAAKg");
	this.shape.setTransform(17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(0,0,35,37.2), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixBZQgEAAABgDIAaiGQABgEAEAAIArAAQAEAAgBAEIgBAFQAGgGAIgDQAHgCAIAAQAIAAAIADQAHAEAEAHQAFAHABAKQACAKgDANQgCALgGALQgFAKgHAHQgHAHgJADQgJAEgJAAQgHAAgGgCQgHgDgEgGIgIAsQgBADgEAAgAhsgXIgJAtQACACAFAAQAGAAAEgFQADgGADgNQADgOgCgGQgBgFgGAAQgFAAgDACgABtA0QgHgBgGgCIgKgFQgFgDgDgEQgDgDgCgFIgDgJQgCgKACgKIAEgNIAFgLIAIgJIAJgIQAGgEAQgGQAMgDAOAAQAMAAAJACQAJADAGAEQAGAFACAGQACAGgBAIQgCAHgEAGQgFAHgIADQgJAFgLACQgNADgQAAIgHAAQAAAEABADQACADADABQAFADAMAAIANgBIANgDQAFgCgBAFIgBASQgBADgDABQgIADgKABQgKABgKAAIgPgBgAB9gYQgEAEgDAIIADAAQANAAAHgCQAFgCABgFQAAgDgCgCQgCgCgFAAQgIAAgFAEgAkcAxQgHgDgFgHQgEgHgCgKQgBgLACgLQADgNAFgKQAGgKAHgHQAHgHAJgEQAIgDAJAAQAJAAAGADQAHADACAFIABgFQABgEAEAAIArAAQAEAAgBAEIgTBfQgBAEgDAAIgrAAQgEAAABgEIAAgFQgEAFgHADQgIADgJAAQgJAAgHgEgAjzgUQgEAGgDAOQgCANABAGQACAFAGAAQAEAAADgCIAJgtQgCgCgEAAQgGAAgEAFgAntA0QgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgKIAEgNIAGgLIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAIQgBAHgFAGQgFAHgIADQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAncgYQgFAEgDAIIADAAQAOAAAGgCQAFgCABgFQABgDgCgCQgDgCgFAAQgHAAgFAEgAI4AzQgEAAABgEIAThfQAAgEAEAAIBXAAQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIgFAVQAAAEgEAAIgnAAIgOBGQAAAEgEAAgAH0AzQgEAAABgEIAGgjIgRAAIgHAjQAAAEgEAAIgrAAQgEAAABgEIAShfQABgEAEAAIArAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgGAhIARAAIAGghQABgEAEAAIArAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgTBfQAAAEgEAAgAFxAzQgDAAAAgEIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThfQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBfQAAAEgEAAgADTAzQgDAAAAgEIAOhGIgXAAQgBAAgBgBQgBAAAAAAQAAgBAAAAQgBgBABgBIAEgVQAAgEAEAAIBhAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgEAVQAAAEgEAAIgXAAIgOBGQgBAEgEAAgAgjAzQgEAAABgEIAShfQABgEAEAAIBVAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgEAVQgBAEgEAAIgnAAIgOBGQAAAEgEAAgAmHAzQgDAAAAgEIAOhGIgXAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgVQABgEAEAAIBhAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgEAVQgBAEgEAAIgXAAIgOBGQAAAEgEAAgAqhAzQgEAAABgEIAZiDQABgEAEAAIA5AAQAPAAAMADIAKADIAIAGQAEADACADQADAEABAFQACAFAAAFIgCANIgDAMQgCAFgEAFQgDAFgEADIgJAHQgNAGgJACQgMADgPAAIgKAAIgHAlQAAAEgEAAgApjgWIALAAQAHAAAFgDQAFgFABgIQACgJgDgFQgDgDgIAAIgLAAg");
	this.shape.setTransform(67.7,8.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,135.5,17.9), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AiOCPQgsgsgBg+QABg+AsgsQAngnA5gFQA3gEAtAiIADADIgFAIIgFgDQgpgfgzADQg1AEglAlQgpApAAA6QAAA6ApApQApAqA7AAQA5AAApgqQAlglADg0QAFg0gggpIgCgEIAIgGIACAEQAiAsgFA4QgEA4gnAnQgtAtg8AAQg/AAgsgtgAh2B4QgjgkAAgvQAAgwAjgiQAegeAqgEQAqgEAiAYIAEADIgGAIIgEgDQgfgWgmAEQgnADgcAcQgeAfAAAsQAAAsAeAfQAgAgAtAAQArAAAfggQAcgbADgnQADgmgVgfIgDgEIAIgGIADAEQAYAigDAqQgFArgeAeQgjAiguAAQgyAAghgigAhfBgQgYgZAAgiQAAgjAYgXQAUgUAdgEQAcgEAXAOIAFADIgGAIIgEgCQgUgNgZAEQgZADgSASQgVAUAAAfQAAAeAVAWQAWAVAfAAQAeAAAVgVQARgSAEgZQACgYgMgWIgCgDIAJgFIACAEQAOAYgEAcQgDAcgVAUQgXAYgiAAQgkAAgYgYgAhHBIQgPgOAAgVQAAgVAPgPQAKgJANgDQAOgDANAEIAGACIgDAIIgGAAQgXgHgRAPQgMANAAAQQAAAQAMAMQAMALARAAQAQAAAMgLQAHgIACgLQADgLgEgKIgBgFIAKgDIABAFQAEANgDANQgEAOgIAKQgPAPgUAAQgVAAgPgPgAgrAlICIiIIgIgnIAwgxIAJAuIAuAJIgxAwIgngHIiHCHgABfiHIAHAiIAiAGIAfgfIghgHIgHghg");
	this.shape.setTransform(18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(0,0,37.5,37.6), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0DbQgFAAADgFIAQghIgWhjQgBgFAGAAIAqAAQADAAABADIADA4IAWg4QABgDADAAIArAAQAFAAgDAFIhFCGQgCADgDAAgAk9CzQgIgDgEgHQgFgHgBgKQgCgLADgMQACgNAGgKQAFgKAHgHQAIgHAIgEQAJgDAJAAQAJAAAGADQAGADADAFIABgFQABgEADAAIAsAAQAEAAgBAEIgTBgQgBAEgDAAIgsAAQgEAAABgEIABgFQgFAFgHADQgIADgIAAQgJAAgHgEgAkUBtQgEAGgDAOQgDAOACAGQABAFAHAAQAEAAADgCIAJguQgCgCgFAAQgGAAgDAFgAmzC2QgLgCgJgDQgBAAgBAAQAAgBAAAAQgBgBAAgBQAAAAABgBIAGgUQACgEAEABQAHAEAIABIARABIAJgBQAEgBAAgDQABgFgHgCQgHgCgTAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgTQABgEAEAAQASAAAIgCQAHgCABgEQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgBgHAAQgVABgMADIgDgBIgBgDIACgSQABgEADAAQANgEAdgBQAPAAALACQAKACAGAFQAGAEACAGQACAGgBAHQgBAHgFAFQgGAGgHACQAIAEADAHQACAFgBAHQgCAIgFAGQgEAGgIAEQgIAFgMACQgLACgOAAQgMAAgLgBgAGTC1QgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThgQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgAELC1QgDAAgBgDIgJgqIgIApQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAWglQACgDADAAIAuAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABIggAsIARAwQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgACCC1QgBAAgBgBQgBAAAAAAQAAgBAAgBQgBAAABgBIAOhHIgSAAIgOBHQAAAEgEAAIgrAAQgEAAABgEIAShgQABgEAEAAIBvAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAgAiGC1QgBAAgBAAQAAgBgBAAQAAAAgBgBQAAgBAAAAIgJgqIgIApQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAWglQACgDADAAIAuAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABIggAsIARAwQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgABsgoQgEAAACgDIAaiHQABgEADAAIAsAAQAEAAgBAEIgBAFQAGgGAHgDQAHgCAIAAQAJAAAHADQAHAEAFAHQAFAHABAKQABAKgCANQgDAMgFALQgFAKgIAHQgHAHgIADQgJAEgJAAQgHAAgGgCQgHgDgEgGIgJAsQAAADgEAAgACyiZIgJAuQACACAEAAQAGAAAEgFQAEgGADgOQACgOgBgGQgCgFgGAAQgEAAgDACgAn4goQgFAAADgFIAQghIgVhjQgBgFAFAAIAqAAQAEAAAAADIADA4IAXg4QACgDADAAIArAAQAFAAgDAFIhHCGQgBADgEAAgAk+g6QgEAAABgEIADgQIgiAAIgDAQQgBAEgDAAIgqAAQgEAAABgEIAIgpQABgEAEAAIAIAAQAGgMAKgXQAGgRAFgTQABgEADAAIBXAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgOBHIAJAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgIApQgBAEgEAAgAlEiEQgFANgGAMIAOAAIAKgyIgFAAQgDAMgFANgAJhhNQgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgLIAEgNIAGgLIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAIQgBAHgFAGQgFAHgIAEQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAJyiaQgFAEgDAIIADAAQAOAAAGgCQAFgCABgFQABgDgCgCQgDgCgFAAQgHAAgFAEgAANhQIgKgEIgHgHQgDgDgCgEQgDgFgBgFIgBgKIABgMQACgIAHgPQAEgGALgLQAGgEAPgGQAIgDASgBQAKAAAPAEQAFABAEADIAIAGIAGAIIADAJIABALIgBAMIgDAMIgGAKQgJANgGAEQgOAJgIACQgRAEgJAAQgRgBgHgDgAAsiWQgEAGgDAOQgCANACAHQABAFAFAAQAFAAADgFQAEgHADgNQADgOgCgGQgCgFgEAAQgFAAgEAFgAHzhOQgEAAABgEIAThgQABgEADAAIArAAQAFAAgCAEIgSBgQgBAEgEAAgAGDhOQgEAAABgEIAShgQABgEAEAAIAnAAQAEAAgBAEIgFAbIAKAAQALAAAJACQAIACAGAFQAGAEACAHQACAHgCAJQgCAJgFAHQgEAHgIAFQgHAEgJADQgKACgLAAgAGzhpIAFAAQAFAAACgDQADgCABgEQABgFgCgDQgCgCgFAAIgEAAgAE+hOQgDAAAAgEIAHgjIgRAAIgHAjQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAhIASAAIAGghQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgAhnhOQgDAAAAgEIAOhHIgXAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgVQABgEAEAAIBhAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgEAVQgBAEgEAAIgXAAIgOBHQAAAEgEAAgAi4hOQgDAAAAgEIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThgQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgApKhOQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIgBgUIgiAAIgJAUQgBAEgEAAIgvAAQgFAAACgFIBAiEQABgDAEAAIBFAAQABAAAAAAQABAAAAAAQABABAAAAQAAABABABIAMCEQAAAFgEAAgApOiKIgBgvIgTAvIAUAAg");
	this.shape.setTransform(68.9,21.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(0,0,137.9,43.9), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgtCXIAVhbIAAgaIgFAAQgoABgbAbQgcAcAAAnIAAAPIgKAAIAAgPQAAgrAfgfQAegeAsgBIgMgOQgXgdAAgkIAAhGIAKAAIAABGQAAAhAVAaIARAUIAiAAIAQgUQAVgZAAgiIAAg8QgcAAgcgHQgYgFgQgIIgFgCIAFgJIAEACQAPAIAZAFQAdAGAcAAIAFAAIAABGQAAAlgXAcIgLAOQArABAeAeQAfAfAAArIAAAPIgKAAIAAgPQAAgngcgcQgbgbgngBIgGAAIAAAYIAVBdIguAjgAghCTIAhAaIAigaIgShTIgeAAgAgOA2IAdAAIAAgUIgdAAgABLgtIAAgKIAFAAQAGAAAFgEQAEgEAAgHQAAgGgEgEQgFgFgGAAIgFAAIAAgoQAAgPgJgMQgJgMgPgEQgYgHgSAAQgQAAgZAHQgPAEgJAMQgJAMAAAPIAAAoIgFAAQgGAAgFAFQgEAEAAAGQAAAHAEAEQAFAEAGAAIAFAAIAAAKIgFAAQgKAAgHgHQgIgHAAgLQAAgJAGgHQAFgGAJgCIAAgfQAAgSALgPQAMgPARgFQAZgHATAAQAUAAAaAHQARAFALAPQALAPAAASIAAAfQAIACAHAGQAFAHAAAJQAAALgHAHQgIAHgKAAgAAKhBIAAgKIAeAAIAAAKgAgnhBIAAgKIAeAAIAAAKg");
	this.shape.setTransform(13.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(0,0,27,37.2), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("ABlC3IAAhOQAAgXgRgQQgHgHgJgFIAAA9IgvgWIgVAkIgUgkIgwAWIAAg9QgIAFgHAHQgRAQAAAXIAABOIgKAAIAAhOQAAgbAUgTQATgTAbAAIATAAIAAgOIgFgDQgSgOgKgTQgKgUAAgWIAAgoIAKAAIAAAoQAAAUAJASQAJAQAQANIAJAGIAAAdIgSAAIAhA6IAig6IgSAAIAAgdIAJgGQAQgNAIgQQAJgSAAgUIAAgYQgmgBgXgJQgZgKgbgYIAGgHQAcAXAWAJQAXAIAoABIAEAAIAAAiQAAAWgKAUQgKATgRAOIgFADIAAAOIATAAQAbAAAUATQATATAAAbIAABOgAAaBUIAgAPIAAgwQgGgCgHABgAg6AzIAAAwIAhgPIgTgiQgHgBgHACgABqAyQAQAAASgQQgXgQgOgWQgNgWAAgXIAAg1QAAgdgUgUQgUgVgdAAIg+AAIAAgKIA+AAQAhAAAXAYQAXAXAAAhIAAA1QAAAXAQAYQAOASAVAOIAFADIgEAEQgXAXgXAAgAiXAlIgEgEIAFgDQAXgPAOgWQAOgVAAgVIAAhCQAAgWARgPQARgOAWADIANACIgCAKIgMgCQgSgCgOALQgNAMAAARIAABCQAAAXgNAWQgOAWgXAQQASAQAQAAIAAAKQgXAAgXgXgAAQg4IAAgJIAVAAIAAAJgAgkg4IAAgJIAVAAIAAAJg");
	this.shape.setTransform(15.6,18.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(0,0,31.3,36.5), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApQBxQgEAAAAgEIAKg1QgFAGgJADQgKAEgKAAQgLAAgJgFQgJgEgGgJQgFgIgCgNQgCgNADgPQADgOAHgMQAHgNAIgIQAKgJAKgFQAKgEALAAQALAAAIAEQAIADADAGIALg6QABgEAFAAIA1AAQAFAAgBAEIgLA6QAFgGAJgDQAJgEALAAQALAAAJAEQAJAFAFAJQAGAIACANQABAMgDAOQgDAPgGANQgHANgJAIQgJAJgKAEQgLAFgLAAQgKAAgIgEQgIgDgDgGIgLA1QAAAEgFAAgAn7gYIgLA2QACADAGAAQAHAAAEgGQAFgHAEgSQADgRgCgGQgCgHgHAAQgGAAgDAEgApOgVQgFAHgDAQQgDASACAHQABAGAIAAQAFAAAEgDIALg2QgCgEgGAAQgHAAgFAHgAtGBxQgEAAABgEIAKg1QgGAGgJADQgJAEgLAAQgLAAgIgFQgKgEgFgJQgGgIgCgNQgBgNADgPQADgOAHgMQAGgNAJgIQAJgJAKgFQALgEALAAQALAAAHAEQAIADADAGIALg6QACgEAFAAIA0AAQAFAAgBAEIgLA6QAGgGAJgDQAJgEAKAAQALAAAKAEQAIAFAGAJQAGAIABANQACAMgDAOQgDAPgHANQgGANgJAIQgJAJgLAEQgKAFgLAAQgLAAgIgEQgHgDgEgGIgKA1QgBAEgFAAgArxgYIgLA2QADADAFAAQAHAAAFgGQAFgHADgSQADgRgBgGQgCgHgIAAQgGAAgDAEgAtDgVQgFAHgEAQQgDASACAHQACAGAIAAQAFAAADgDIAMg2QgDgEgFAAQgIAAgEAHgALYBBIgNgGIgLgHQgFgEgDgGIgEgLQgCgHAAgHQAAgHACgIIAEgOIAHgNQAEgGAFgFIALgKQAIgFAUgIQALgDAZgBIASABQAKABAHADQADACgBAEIgHAYQgCAFgFgBQgIgEgMAAQgHAAgGACQgGACgEAEIgHAKQgEAGgBAGQgCAHACAHQAAAFADAEQADAEAFADQAFABAHAAQAMAAALgDQAGgCgBAFIgCAYQgBAFgEABQgIADgLACQgJABgJAAQgZgCgJgCgAIyBAIgMgFIgKgIQgEgFgCgFQgDgFgCgGIgBgNIABgPQACgJAJgRQAFgIAOgNQAIgGATgHQAKgDAWgCQALAAATAFQAHACAEADQAGADAEAFQAEAEADAFIAEAMQACAGAAAHIgCANIgEAPIgHANQgLAPgIAGQgQAKgKADQgVAFgLAAQgVgCgJgDgAJZgVQgFAIgEAPQgDARACAIQACAGAGAAQAGAAAEgGQAFgIADgRQAEgPgDgIQgBgHgGAAQgGAAgEAHgAlvBEQgJgBgHgDQgHgDgGgEQgFgDgEgFQgEgEgDgFQgCgFgBgGQgDgNADgOQABgHAEgIQACgHAEgGIAKgLIALgKQAIgFATgHQAPgEARAAQAOAAAMADQAKADAIAGQAHAFACAHQAEAIgCAKQgCAJgGAHQgGAHgKAGQgKAFgOADQgPADgVAAIgIAAQAAAFACAEQABAEAEABQAHAEAPAAIAPgBIAQgEQAGgDgBAGIgCAWQAAAFgEABQgKADgMABQgMACgNAAQgKAAgIgBgAlbgaQgGAFgDAKIADAAQARAAAIgDQAGgDABgFQABgEgDgDQgDgCgGAAQgJAAgGAFgAwkBDQgPgDgJgFQgDgBABgEIAKghQAAgEACgBQABAAAAAAQABAAABAAQAAAAAAAAQABAAAAABQAHAEAIABQAJACAIAAQAIAAAHgBQAHgBAGgDQAFgDAFgEQAFgEAEgGIhEAAQgFAAABgDIAHgkQABgEAEAAIBFAAQgCgGgDgEQgDgEgEgDQgFgDgGgBQgHgBgHAAQgJAAgJACQgJACgIADQAAAAgBABQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAIAEgjQABgDADgBQAMgEAPgDQAOgDAOAAQAMAAAJACQALABAIADQAIADAIAFQAGAEAGAFQAFAGAEAHQADAHABAIQACAJAAAJQAAAKgCAKQgCAKgEAJQgDAJgFAIIgLAQQgGAHgIAFQgIAGgIAFIgTAHQgKADgKABQgLACgLAAQgOAAgOgCgAO4BCQgFAAACgFIAWh1QABgEAFAAIAwAAQAFAAgBAEIgHAhIANAAQAOAAAKADQAKADAHAFQAIAGACAIQACAIgBALQgDALgGAJQgFAIgKAGQgJAFgLAEQgMACgNAAgAPzAhIAGAAQAGAAAEgDQADgDABgFQABgGgCgDQgCgEgGAAIgGAAgANNBCQgEAAAAgFIARhWIgcAAQgEAAAAgFIAFgaQABgEAFAAIB3AAQAEAAAAAEIgFAaQgBAFgFAAIgcAAIgRBWQgBAFgFAAgAG6BCQgEAAABgFIAIgqIgVAAIgJAqQAAAFgFAAIg1AAQgFAAABgFIAXh1QAAgEAFAAIA2AAQAEAAgBAEIgIApIAWAAIAHgpQABgEAFAAIA1AAQAEAAAAAEIgXB1QAAAFgFAAgADABCQgEAAABgFIAWh1QABgEAFAAIBEAAQARAAANACQAMACAIAFQAJAEADAIQAEAHgCAJQgBAGgEAGQgFAGgHAEQAIAEAEAHQADAGgCAJQgCAKgGAIQgGAIgLAFQgKAEgPAEQgOACgSAAgAD+AhIALAAQAHAAADgBQADgDACgEQAAgEgCgCQgDgDgGAAIgLAAgAEHgNIAKAAQAHAAADgCQADgCACgDQAAgEgDgCQgCgCgGAAIgLAAgAB0BCQgFAAABgFIAJgsIgtAvIgEACIgrAAQgFAAABgFIAXh1QAAgEAFAAIAuAAQAEAAAAAEIgJAsIAtguIAEgCIArAAQAFAAgBAEIgXB1QAAAFgFAAgAhOBCQgDAAAAgFIARhWIgdAAQgEAAABgFIAFgaQAAgEAFAAIB2AAQAFAAgBAEIgFAaQgBAFgEAAIgcAAIgRBWQAAAFgFAAgAi0BCQgFAAAAgEIgMgzIgKAyQAAAFgFAAIg1AAQgFAAABgFIAXh1QABgEAFAAIA1AAQAEAAAAAEIgJAtIAcguQACgDADAAIA5AAQABAAAAAAQABAAABAAQAAAAAAABQABAAAAABQABACgCADIgoA1IAVA7QABADgCACQgCACgDAAg");
	this.shape.setTransform(88.6,9.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(-20.1,-2,217.5,22.7), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AkwFYIAAgSIB/AAIAAl7Ih/AAIAAgSICqAAQAlgPAVgTQAWgSAYgjIABgDQApgbAigoQAWgZAlg2IAMgRQAIgMAOgFQAOgEANAEQAQAGAIAOQAJAPgEAQIgtDbIBuAAQAVAAAMAPQAOAQgDAVIgrEgQgDARgNALQgMALgRAAIl3AAIAAAkgAifEiIF3AAQAKAAAIgGQAIgIABgKIAHgwIhCAAIAAgTIBFAAIALhIIhAAAIAAgSIBCAAIALhIIhCAAIAAgTIBFAAIAGgoQACgNgIgJQgGgJgOAAIiDAAIAxjxQAEgVgVgJQgSgGgLAQIgLARQgnA3gVAZQgkArgqAcQgZAlgYAUQgWATgoAQIgEABIgbAAgAknEiIAAgSIA3AAIAAASg");
	this.shape.setTransform(30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(0,0,61,68.9), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.oim();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(0,0,174,174), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-23,20);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(-23,20,150,92), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(-284,65.6,1,1,0,0,0,284,65.6);

	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(284,65.6,1,1,0,0,0,284,65.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(-568,0,1136,131.3), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(1));

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(85.6,28,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5));

	// Слой 1
	this.instance_1 = new lib.Символ34();
	this.instance_1.parent = this;
	this.instance_1.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.13,scaleY:1.13},4,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.instance_2 = new lib.Символ35();
	this.instance_2.parent = this;
	this.instance_2.setTransform(85.6,27.6,1,1,0,0,0,95.2,29.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,172,57);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(81.3,28.5,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ31();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(84.5,27.5,1,1,0,0,0,86.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(-4.5,-0.5,172,57), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.5,-0.5,172,57);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(70.5,65,2.04,2.04,0,0,0,17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ24();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(73.6,58.6,1.97,1.97,0,0,0,18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ20();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(40.2,64.3,1.748,1.748,0,0,0,13.5,18.6);

	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(89.1,63,1.748,1.748,0,0,0,15.6,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ18();
	this.instance_2.parent = this;
	this.instance_2.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(64.6,63,1.05,1.05,0,0,0,30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_349 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_384 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(349).call(this.frame_349).wait(35).call(this.frame_384).wait(36));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAoQgGAAgFgEQgGgEgCgGIgBgIIAAgJQAAgKAEgHQADgDAEgCQAEgCAFAAIAgAAIAAgFIgCgEQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgvAAIAAgNIAuAAQAIAAAEAEQAFADACAIIAAAEIAAAnQAAAGgDAFQgDAFgEACQgEADgFAAgAgRAAQgCACAAAEIAAANQAAAFADACQADABAFAAIARAAQALAAAAgIIAAgNQAAgEgDgCQgCgBgFAAIgUAAQgEAAgDABg");
	this.shape.setTransform(138.9,-219.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAlQgCgCgCgGIgUg1IAAA/IgOAAIAAg/QAAgMAJgDQAGgCAFADQAEADADAHIASA1IATg1QADgHAFgDQAEgDAGACQAFACACADQACAEAAAGIAAA/IgNAAIAAg/IgUA1QgCAGgDACQgDADgFAAQgEAAgDgDg");
	this.shape_1.setTransform(129.1,-219.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMAoQgGAAgFgEQgGgEgCgGIgBgIIAAgJQAAgKAEgHQADgDAEgCQAEgCAFAAIAgAAIAAgFIgCgEQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgvAAIAAgNIAuAAQAIAAAEAEQAFADACAIIAAAEIAAAnQAAAGgDAFQgDAFgEACQgEADgFAAgAgRAAQgCACAAAEIAAANQAAAFADACQADABAFAAIARAAQALAAAAgIIAAgNQAAgEgDgCQgCgBgFAAIgUAAQgEAAgDABg");
	this.shape_2.setTransform(119.3,-219.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAUAoIAAg8QgBgFgIgBIgLAAQgFAAgDACQgBACAAAFIAAAkQAAAVgXAAIAAgOQAFAAACgBQACgCAAgFIAAgkQAAgVAXAAIAKAAQAMAAAFAFQAGAGAAAKIAAA6g");
	this.shape_3.setTransform(110.8,-219.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQAoIgggiQgEgEAAgCQAAgFAEgDIAegfIASAAIglAnIAnAogAghAoIAAhPIANAAIAABPg");
	this.shape_4.setTransform(102.9,-219.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLAoQgEAAgEgCQgEgBgDgDQgGgGAAgJIAAgjQAAgXAZAAIATAAQAEAAAEACQAEABADACQACADACAEQACAEgBAFIAAAJIgzAYIAAADQABAFACACQACACAEAAIArAAIAAANgAgQgXQgDADAAAEIAAAQIAmgSIAAAAQAAgIgIAAIgVAAQgEABgCACg");
	this.shape_5.setTransform(94.6,-219.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggA1IAAhUIABgJQABgEADgDQAGgFAJAAIAYAAIAIABIAGACQADADACAFQACADAAAGIAAAlIgBAIQgBAEgDADQgGAHgJAAIggAAIAAAagAgRglQgCACAAAEIAAAjIAAACQAAAEACACQADACACAAIAZAAIAAgBQAGAAABgGIAAgBIAAgmIgBgFQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBAAgBgBIgYAAQgEAAgDACg");
	this.shape_6.setTransform(86.1,-218.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(420));

	// Слой 3
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(-31.7,860.7,0.654,0.654,0,0,0,231.2,14.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(280).to({_off:false},0).to({y:718.1,alpha:1},9,cjs.Ease.get(1)).to({y:722},5,cjs.Ease.get(1)).wait(45).to({y:718.1},5).to({y:918,alpha:0},5).wait(1).to({y:860.7},0).to({y:718.1,alpha:1},9,cjs.Ease.get(1)).to({y:722},5,cjs.Ease.get(1)).wait(45).to({y:718.1},5).to({y:918,alpha:0},5).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ37();
	this.instance_1.parent = this;
	this.instance_1.setTransform(71.1,323.3,1,1,0,0,0,154.3,16.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:148.4,alpha:1},5,cjs.Ease.get(1)).to({scaleX:0.92,scaleY:0.92,x:65.5,y:138.9},4,cjs.Ease.get(1)).wait(271).to({regX:154.2,x:63.3,y:256.2,alpha:0},0).to({y:115.3,alpha:1},9,cjs.Ease.get(1)).to({y:118.9},5,cjs.Ease.get(1)).wait(45).to({y:115.3},5).to({y:279.1,alpha:0},5).wait(1).to({y:256.2},0).to({y:115.3,alpha:1},9,cjs.Ease.get(1)).to({y:118.9},5,cjs.Ease.get(1)).wait(45).to({y:115.3},5).to({y:279.1,alpha:0},5).wait(1));

	// logo
	this.instance_2 = new lib.Символ5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(45.2,-333.5,1.278,1.278,0,0,0,75,46);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-125.2,alpha:1},5,cjs.Ease.get(1)).to({y:-135.2},4,cjs.Ease.get(1)).wait(271).to({x:44.8,y:-316.2},0).to({x:41.8,y:-151.8},9,cjs.Ease.get(1)).to({y:-156.8},5,cjs.Ease.get(1)).wait(45).to({y:-151.8},5).to({y:-355.1,alpha:0},5).wait(1).to({x:44.8,y:-316.2,alpha:1},0).to({x:41.8,y:-151.8},9,cjs.Ease.get(1)).to({y:-156.8},5,cjs.Ease.get(1)).wait(45).to({y:-151.8},5).to({y:-355.1,alpha:0},5).wait(1));

	// text_5
	this.instance_3 = new lib.Символ27();
	this.instance_3.parent = this;
	this.instance_3.setTransform(508.5,145.3,1.932,1.932,0,0,0,86.2,35.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(280).to({_off:false},0).to({regY:34.9,y:-144.7,alpha:1},9,cjs.Ease.get(1)).to({y:-125.3},5,cjs.Ease.get(1)).wait(42).to({y:-144.7},5,cjs.Ease.get(1)).to({regY:35,y:-28.6,alpha:0},5,cjs.Ease.get(1)).wait(4).to({regY:35.1,y:145.3},0).to({regY:34.9,y:-144.7,alpha:1},9,cjs.Ease.get(1)).to({y:-125.3},5,cjs.Ease.get(1)).wait(42).to({y:-144.7},5,cjs.Ease.get(1)).to({regY:35,y:-28.6,alpha:0},5,cjs.Ease.get(1)).wait(4));

	// btn
	this.instance_4 = new lib.Символ28();
	this.instance_4.parent = this;
	this.instance_4.setTransform(20.3,787.1,1.087,1.087,0,0,0,85.5,28.2);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.Символ28(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(280).to({_off:false},0).to({regY:28.1,y:624,alpha:1},9,cjs.Ease.get(1)).to({regY:28.2,y:635},5,cjs.Ease.get(1)).wait(40).to({regY:28.1,y:624},5,cjs.Ease.get(1)).to({y:689.2,alpha:0},5,cjs.Ease.get(1)).wait(6).to({y:787},0).to({y:624,alpha:1},9,cjs.Ease.get(1)).to({regY:28.2,y:635},5,cjs.Ease.get(1)).wait(40).to({regY:28.1,y:624},5,cjs.Ease.get(1)).to({y:689.2,alpha:0},5,cjs.Ease.get(1)).wait(6));

	// text_4
	this.instance_5 = new lib.Символ26();
	this.instance_5.parent = this;
	this.instance_5.setTransform(16.2,685.3,1.556,1.556,0,0,0,56.8,7.4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(214).to({_off:false},0).to({y:529.8,alpha:1},10,cjs.Ease.get(1)).to({y:545.3},5,cjs.Ease.get(1)).wait(40).to({y:529.8},5,cjs.Ease.get(1)).to({y:965.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// pic_4
	this.instance_6 = new lib.Символ23();
	this.instance_6.parent = this;
	this.instance_6.setTransform(16.9,366.1,0.822,0.822,0,0,0,65.5,65.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(214).to({_off:false},0).to({regY:65.5,rotation:360,y:357.8},10,cjs.Ease.get(1)).to({regY:65.6,y:366.1},5,cjs.Ease.get(1)).wait(10).to({regY:65.5,scaleX:0.73,scaleY:0.73},5,cjs.Ease.get(1)).to({regY:65.6,scaleX:0.82,scaleY:0.82},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:357.8},5,cjs.Ease.get(1)).to({regY:65.6,y:588.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// text_3
	this.instance_7 = new lib.Символ22();
	this.instance_7.parent = this;
	this.instance_7.setTransform(17.1,677.3,1.278,1.278,0,0,0,67.7,9);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(144).to({_off:false},0).to({regY:8.9,y:536.7,alpha:1},10,cjs.Ease.get(1)).to({regY:9,y:549.6},5,cjs.Ease.get(1)).wait(40).to({regY:8.9,y:536.7},5,cjs.Ease.get(1)).to({regY:9,y:894.7,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// pic_3
	this.instance_8 = new lib.Символ19();
	this.instance_8.parent = this;
	this.instance_8.setTransform(16.9,399.1,0.822,0.822,0,0,0,65.5,65.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(144).to({_off:false},0).to({regY:65.5,rotation:360,y:357.8,alpha:1},10,cjs.Ease.get(1)).to({regY:65.6,y:366.1},5,cjs.Ease.get(1)).wait(11).to({regX:65.4,scaleX:0.74,scaleY:0.74,x:16.8},4,cjs.Ease.get(1)).to({regX:65.5,scaleX:0.82,scaleY:0.82,x:16.9},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:357.8},5,cjs.Ease.get(1)).to({regY:65.6,y:588.1,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// text_2
	this.instance_9 = new lib.Символ16();
	this.instance_9.parent = this;
	this.instance_9.setTransform(16.2,771.5,1.306,1.306,0,0,0,69,22);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(74).to({_off:false},0).to({y:536.4,alpha:1},10,cjs.Ease.get(1)).to({regY:22.1,y:549.6},5,cjs.Ease.get(1)).wait(40).to({regY:22,y:536.4},5,cjs.Ease.get(1)).to({regY:21.9,y:914.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// pic_2
	this.instance_10 = new lib.Символ17();
	this.instance_10.parent = this;
	this.instance_10.setTransform(16.9,390.8,0.822,0.822,0,0,0,65.5,65.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(74).to({_off:false},0).to({rotation:360,y:357.8,alpha:1},10,cjs.Ease.get(1)).to({regY:65.6,y:366.1},5,cjs.Ease.get(1)).wait(10).to({regX:65.3,regY:65.5,scaleX:0.72,scaleY:0.72,x:16.8},5,cjs.Ease.get(1)).to({regX:65.5,regY:65.6,scaleX:0.82,scaleY:0.82,x:16.9},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:357.8},5,cjs.Ease.get(1)).to({y:596.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// text_1
	this.instance_11 = new lib.Символ12();
	this.instance_11.parent = this;
	this.instance_11.setTransform(16.3,640.8,1.054,1.054,0,0,0,88.6,9.2);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(5).to({_off:false},0).to({y:535.4,alpha:1},9,cjs.Ease.get(1)).to({y:545.9},5,cjs.Ease.get(1)).wait(40).to({y:535.4},5,cjs.Ease.get(1)).to({y:851.7,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pic_1
	this.instance_12 = new lib.Символ9();
	this.instance_12.parent = this;
	this.instance_12.setTransform(16.9,382.6,0.822,0.822,0,0,0,65.5,65.6);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(5).to({_off:false},0).to({regY:65.5,rotation:360,y:357.8,alpha:1},9,cjs.Ease.get(1)).to({regY:65.6,y:366.1},5,cjs.Ease.get(1)).wait(10).to({regX:65.4,regY:65.5,scaleX:0.72,scaleY:0.72,x:16.8},5,cjs.Ease.get(1)).to({regX:65.5,regY:65.6,scaleX:0.82,scaleY:0.82,x:16.9},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:357.8},5,cjs.Ease.get(1)).to({regY:65.6,y:604.6,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pricel
	this.instance_13 = new lib.Символ8();
	this.instance_13.parent = this;
	this.instance_13.setTransform(16.9,382.7,0.866,0.866,0,0,0,87,87);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({rotation:360,y:356.7,alpha:1},9,cjs.Ease.get(1)).to({regY:87.1,y:365.5},5,cjs.Ease.get(1)).wait(15).to({regY:87,scaleX:0.92,scaleY:0.92,x:16.8,y:365.4},5,cjs.Ease.get(1)).to({regY:87.1,scaleX:0.87,scaleY:0.87,x:16.9,y:365.5},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:356.7},5,cjs.Ease.get(1)).to({y:616.4,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:382.7},0).to({rotation:720,y:356.7,alpha:1},9,cjs.Ease.get(1)).to({regY:87.1,y:365.5},5,cjs.Ease.get(1)).wait(15).to({regY:87,scaleX:0.92,scaleY:0.92,x:16.8,y:365.4},5,cjs.Ease.get(1)).to({regY:87.1,scaleX:0.87,scaleY:0.87,x:16.9,y:365.5},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:356.7},5,cjs.Ease.get(1)).to({y:616.4,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:382.7},0).to({rotation:1080,y:356.7,alpha:1},9,cjs.Ease.get(1)).to({regY:87.1,y:365.5},5,cjs.Ease.get(1)).wait(15).to({regY:87,scaleX:0.92,scaleY:0.92,x:16.8,y:365.4},5,cjs.Ease.get(1)).to({regY:87.1,scaleX:0.87,scaleY:0.87,x:16.9,y:365.5},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:356.7},5,cjs.Ease.get(1)).to({y:616.4,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:382.7},0).to({rotation:1440,y:356.7,alpha:1},9,cjs.Ease.get(1)).to({regY:87.1,y:365.5},5,cjs.Ease.get(1)).wait(15).to({regY:87,scaleX:0.92,scaleY:0.92,x:16.8,y:365.4},5,cjs.Ease.get(1)).to({regY:87.1,scaleX:0.87,scaleY:0.87,x:16.9,y:365.5},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:356.7},5,cjs.Ease.get(1)).to({y:616.4,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.6,-366.8,224.4,824.8);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции - копия
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(458.9,84,0.529,0.529,0,0,0,284.1,65.7);
	this.instance.alpha = 0.309;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:284.2,regY:65.8,x:449.9},47).to({regX:284.1,regY:65.7,x:458.9},52).wait(1));

	// Режим изоляции
	this.instance_1 = new lib.Символ40();
	this.instance_1.parent = this;
	this.instance_1.setTransform(291,85.9,1,1,0,0,0,284,65.6);
	this.instance_1.alpha = 0.172;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:859.3},99).wait(1));

	// Слой 2
	this.instance_2 = new lib.back();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-15,51,0.601,0.601);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-561,20.3,1203.4,131.3);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.bg = new lib.Символ1();
	this.bg.parent = this;
	this.bg.setTransform(1321.7,348.5,1.94,1.94,0,0,0,120.2,199.9);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,2334.8,254.7), null);


// stage content:
(lib._215x800 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		
		
		
		stage.canvas.addEventListener("mouseover", fl_MouseOverHandler_5);
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(350);
		}
		
		
		stage.canvas.addEventListener("mouseout", fl_MouseOutHandler_23);
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(404);
		}
		
		setTimeout(function() {
		         _this.an.gotoAndStop(364);
				 _this.bg.bg.gotoAndStop(0);
				 stage.canvas.removeEventListener("mouseover", fl_MouseOverHandler_5);
				 stage.canvas.removeEventListener("mouseout", fl_MouseOutHandler_23);
		   }, 27000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// an
	this.an = new lib.Символ7();
	this.an.parent = this;
	this.an.setTransform(162.9,255.5,0.8,0.8,0,0,0,87,87);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// bg
	this.bg = new lib.Символ41();
	this.bg.parent = this;
	this.bg.setTransform(30.7,-1,1.699,1.699,90,0,0,1167.3,174.1);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.3,-1584.6,432.8,3967.6);
// library properties:
lib.properties = {
	width: 215,
	height: 800,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/back.jpg?1490623260223", id:"back"},
		{src:"images/logo.png?1490623260223", id:"logo"},
		{src:"images/molecule.png?1490623260223", id:"molecule"},
		{src:"images/oim.png?1490623260223", id:"oim"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;