(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.icon2 = function() {
	this.initialize(img.icon2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,177,178);


(lib.mouse = function() {
	this.initialize(img.mouse);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,93,115);


(lib.pizza1 = function() {
	this.initialize(img.pizza1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,88,88);


(lib.pizzatext = function() {
	this.initialize(img.pizzatext);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.radar = function() {
	this.initialize(img.radar);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,288,287);


(lib.radarback = function() {
	this.initialize(img.radarback);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,312,300);


(lib.setka = function() {
	this.initialize(img.setka);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC00").s().p("AsEBrQgvAAgHgCIgEgCIgDgmQgBgGAIAAIALACIAKgBIgBgLIADhKQAAgXgBAAIgdgCIADgZIACgCIAZgGQAPgCANgBIACgBIA8gFQAVgBARgBIATgEQAFAAAAAPIAAAGIADgMQASgCAPAAIA0ABQADACABAOIACAXIgZAGIAAAHIAEAQQADAMABAAIAFgBIAkgDIACABIAFAAIAMgCIAHgCIADgdIgHgCIgSABIAAgBIgBgCIAEgNIABgNQAAgEAUgCIA2gCIAMgBQABAAABAAQAAAAABAAQAAABAAAAQAAABABAAIAEAYIgBACIgBAAQgJABgRAFIAABVIARABQACAGABANIACAXQgCABgEAAIgGABQgPACgYACIgnABIACglQACgCAHgCIAJgDQgFgXgDgBIg2AHIABAXIAUgBIAGAEIAAALQAAAKgBAJQgEACgXAAIg+AGIgIgCQgHgBgBgBIAAgEIABgEIgDAFQgGAKgMAEIgXAHIgbAEQgPACgQAAgAr+AeIgCAoIAfAAQAJAAAHgGQAHgGABgIQAAgHgDgDQgKgIgDgBIghgHIgDAAIgBAGgArOgzIgbADIgFAfIAAACIAkAGQAKADANAFIAXAKIAOALQAHAGACAJIAEANIgBAKIAVgIIAAgSIgGhTQgDgBgRAAIgFgCIgCAZQgHgBgWAEIgCgDIAAgZIghADgAk/BIIARgJQgGgSgDAAIgqAFQgGACgEADIAAANQAWADAAAFIgDATQgCAFgDADQgZgDgMAAQgcAAgSgGIAAgFIAFgMQADgLADAAIATgDQACgBAIgcIAUhGQAHgYAEgWQACgGAEAAIA2ADQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAIAeBhQAIAaALASQAGgBALACQADABAAAIIABAZQgIACgNABIgXABIgpAJQgEgOgCgUgAkuAQQgFgPgIgPIgPgdQgGAhgBASQAFADAeAFIAAAAgAAbBnQgLAAgMgIQgFgEgEgFQgEgFgCgFIgBgJQAAgPAKgLQAEgEAGgDQAHgDAHABQAIAAAEAHQAEAGAAAMIgBAJIALgFQAJgFAFgHQAFgIABgLIABgNQgSAEgVAAQgHgBgNgEQgegGAAgnIACgkIgMgFQgDAAgCgCIACghIAnAEIAEAAIAZADQAEABAAAFIAAARIgBADIABAVQgLAAgFACIAAAFIABAXQACAUAjgNQAHgDACgJIADgdQABgBAAgBQAAAAgBgBQAAAAAAAAQAAAAgBAAIgIgEIgCAAIAAgBIgBABIAAgbIBFACQAFAAAAALQgBAAgCAKIAFgFQAJgIAGgEIAVgNIAWAFQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAAAIgDAJQgGAIgDAAIARAIQAVALAVANIANAIIgBgWIgagGIAAggIAsgGQAHAAARgDQAQgEAJAAQAIAAAEAOIAFAQIgeAKQABAPAFASIAVgPIAygcQgEAAgFgIIgDgIQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAVgFIAWANIAPAMIAGAHIABgJIAOgEICRgMIAJABQABACABAFIgBAIIABAhQAAASgDAFIgbAAQgEgNgDgRQgBgGgGAAIgPAAIgGABQgKAAgVAEIAAAtIADABIATgFIACgVIAFAAIAWADIABAEIABAmQAAAPgDAOIgRACQgDAAgBgLIgDgMIgBAAQgCAAgMAHQAAAHAGAMIAHARIAigGIAOgFIAAgQQAAgOAGAAIATADIADAAQAAABAAAAQAAAAAAABQABAAAAABQAAAAABABIADA6IgPACIiKAEQgFAAgHgBQgJgDAAgEQAAgRACgEQABgEAOgFIAHgBIgDgVIgChPQgBgDgLAAIgCAAIgCABQgEAAgGgCIAAgBIgGAFQgBAAgFgEIgIgIIgyAnIAYAXIAEAFQAGAJANAQQAHAAAJAEQABACAAAEIgBAZIgCAMQgEABgIAAIhBgBIgCABIgCABQgEAAAAgIIgCgSQAAgGAFgEIALgHIgvglIAAABIgCAZIABAJIACAAIAIgCIAIgCIAEAEIAAAfQAAABAAAAQAAAAgBABQAAAAgBAAQgBAAAAABIhPADQgGAAgCgEQgDgDABgOQAAgHALgEIAIgEIAAgZIgBgFIgUAOQgVAPgFAFIALAHQAFADgCAMIAAANQgTADgoADIgOABQgIABgEgDIgCgLIgCgZQAAgEACgCQAJgEAGABQAOgRAFgJIAcgcIgxgoIgIAIIgHAGIgGgHIAAADQgHADgDgFQACAUgFAxQgHAlgaAXQgHAGgJAHIgUAFQgMACgHAAIgDAAgAN4BVQgNgIgKgLQgJgLgHgOQgOgaAAgdQAAgTADgPQAEgPAGgLQAIgPAUgHIAWgHQALgDAHAAQAJAAAdAGIAeAHQAcAKALAsQAFAUABASQgBALgFAUQgHASgGALQgHALgQAKQgIAGgIADQgGADgHABIgIACIgVABQgKAAgfgLgAOMhIIgDAFIgFAKQgDAUAAAZQAAAbAIAPQAEAKAMAHQALAIAKAAQAJAAAHgEQAGgEAFgGQADgHACgHQACgIAAgKQAAgXgGgVQgEgLgNgNIgLgKQgLgGgKAAQgFABgIACgAvOBVQgNgIgKgLQgKgLgHgOQgOgaAAgdQABgTADgPQADgPAGgLQAJgPATgHIAXgHQAKgDAIAAQAIAAAdAGIAeAHQAcAKAMAsQAFAUAAASQAAALgGAUQgGASgHALQgHALgPAKQgJAGgHADQgHADgGABIgJACIgVABQgJAAgfgLgAu6hIIgDAFIgFAKQgDAUAAAZQAAAbAHAPQAEAKAMAHQALAIALAAQAJAAAGgEQAHgEAEgGQAEgHABgHQADgIAAgKQgBgXgGgVQgDgLgOgNIgLgKQgKgGgLAAQgFABgHACgAjgBDQAAgHAbgKIAAgWQgDgXgBggIAAgZIgJgCIgLADQgIgBABgFIADglIAFgEQAfgCAtAAQAQAAAPACQAOACANAEIAWAGQANAFAFAIQAEAFADALQACALAAAGIgDAMQgCAKgHAGIgPAKIgWAKQgNAFgLADIgjAIIAAALQAAALACADIAGAAIAWgCQAEAAADACQgBAGAAALIAAAQQgSAAglAEIg6ADgAijgeIABAIIACAFIADAAIACgBIADAAIAFgBQALABAMgFIAMgJQADgDAAgHQAAgJgHgGQgIgFgHgBIggAAIAAAhgAJ1BVQgHgBAAgBIAAgEIACgUIAZgJIAAgSIgGhTQgEgBgQAAIgHgCQABgWAEgNQASgCAPAAIA0ABQADACACAOIACAXIgZAGIAAAHIADAQQADAMACAAIAEgBIAlgDIACABIAEAAIAMgCIAHgCIADgdIgGgCIgSABIAAgBIgBgCIAEgNIAAgNQABgEATgCIA3gCIAMgBQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAEAYIAAACIgBAAQgJABgRAFIAABVIAQABQACAGACANIABAXQgBABgFAAIgGABQgPACgYACIgnABIADglQABgCAHgCIAJgDQgEgXgDgBIg2AHIABAXIAUgBIAGAEIAAALQAAAKgCAJQgDACgXAAIg/AGgALSAtIAAAAIAAAAgAokAtIAAAAIAAAAg");
	this.shape.setTransform(102.9,10.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol65, new cjs.Rectangle(0,0,205.7,21.4), null);


(lib.Symbol64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AgCByIgJgBQgFAAgYgJIgUgIQgGgEgLgMQgKgLgFgJQgGgLgDgNQgDgNAAgOQAAgnAOgcQAIgSANgLQANgLARgGIAbgGIAYgDIANACIAOABQAiALAQAaQAQAZAAApQAAAZgDANQgEAPgJAOQgJAOgOANQgdAbgeABgAgfgdQgKAjAAAOQAAAnAnAAQAEgBAMgMQALgKADgGQAJgSAEgPIABgTQAAgogqgIIgGgDQgOAOgLAeg");
	this.shape.setTransform(61.3,20.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AgCByIgJgBQgFAAgYgJIgUgIQgGgEgLgMQgLgLgEgJQgGgLgDgNQgDgNAAgOQAAgnAOgcQAIgSANgLQANgLARgGIAagGIAZgDIANACIAOABQAiALAQAaQAQAZAAApQAAAZgDANQgFAPgIAOQgJAOgOANQgdAbgeABgAgfgdQgKAjAAAOQAAAnAnAAQAEgBAMgMQALgKADgGQAJgSADgPIACgTQAAgogqgIIgGgDQgOAOgLAeg");
	this.shape_1.setTransform(37.8,20.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AgOB/IgWgQQgsgcAAgFIA/hKIAqg0QASgXABgEIgsAHIg7AFIgLAyIgDAAIgQgGIgQgJIAKg9QAEgYAGgOQAEgIANgBIAMAAIAGABQAFAAAEAIIAGANQAqgHA8gDQAdAAACAFQAHASABAQIgEAFIgCAFIgjBKIgbAyIgjBYg");
	this.shape_2.setTransform(14.8,21.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol64, new cjs.Rectangle(0,0,72,42.8), null);


(lib.Symbol59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC00").s().p("AgYCKIgMgDIAFgVQgbgGgXgDQgPgCgPAFIgVABQgLACgMAEQADgBgMggIACAAIAPgJIgBgOQgCgbgGgtIgDgHQgJACgBACIgEgFQAAgGgCgEIgEgVIBNgJIAJABIABAGQABARgDAIIgHAFIgKACIACAZQgCgHACAOIAEAjQABANADAFIALgBQAKgCAYAFIABgbIABgTIACgnIgJgHIgBgeQADgCADAAIAggDQAXgDARABIgBAiIAAgBIAAABQgCADgKAAQgGAAgCABIgMBdIAmALQgCAZgGASQAAAOgDALQgIAAgagIgAjzCKIgLgDIAFgVQgcgGgXgDQgOgCgPAFIgWABQgKACgMAEQADgBgMggIACAAIAPgJIgCgOQgCgbgFgtIgEgHQgIACgCACIgDgFQgBgGgCgEIgEgVIBOgJIAJABIABAGQAAARgCAIIgHAFIgKACIACAZQgDgHACAOIAEAjQACANADAFIALgBQAJgCAZAFIAAgbIACgTIABgnIgJgHIgBgeQADgCAEAAIAfgDQAXgDATABIgBAiIAAgBIAAABQgDADgJAAQgIAAgCABIgMBdIAoALQgCAZgGASQAAAOgEALQgHAAgcgIgAAnBxQgKgDABgDQgBgRACgFQABgEAOgFIAHgBIgCgUIgDhPQgBgDgKAAIgDAAIgCABQgDAAgGgDIABgcIAOgDICRgMIAKABQABABAAAFIgBAIIACAhQAAATgDAFIgcgBQgEgMgDgSQAAgGgHABIgOAAIgHABQgJgBgVAEIAAAsIADABIATgEIABgVIAFAAIAWAEIABADIABAnQAAAOgDAPIgRACQgDAAgBgLIgCgNIgBAAQgCAAgNAHQAAAHAHAMIAGARIAjgGIAOgEIgBgRQABgOAFAAIAUAEIADAAQAAAAAAAAQAAABAAAAQAAABABAAQAAABABAAIADA7IgPABIiLAEIgCABIgJgCgADTBWQAAgGAbgLIAAgVQgDgXgCggIAAgaIgJgBIgLACQgHAAAAgFIAEgmIAEgDQAfgCAuAAQAQAAAOACQAOACANADIAXAGQAMAFAGAJQADAEADALQADAMAAAFIgEANQgBAIgIAGIgOALIgXALQgNAFgKADIgjAHIAAAMQAAAKACADIAFAAIAXgCQAEAAADACQgCAHABAKIAAARQgSAAgmADIg6AEgAEPgLIACAIIACAFIACAAIADgBIADAAIAEgBQALAAANgEIALgJQAEgDAAgHQgBgIgGgGQgIgFgIgBIggAAIAAAggAJYBnIgCAEIhCgCQgKgBgCgCIACgjQAKgDAHABIAAAAIACAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAIgFgkQAAgNgCgDQgJAQgNAgIgVAtIg1AEIgxgFIgCgZQAEgCAFgBIANAAQACAAAAAAQABAAABAAQAAAAAAAAQABgBAAAAIAChiIgKgDQgHgCgDgDQgCgBAAgFIgCgfQgBgLAEgEIBNAHQAFAagBANQAAAEgFAAIgEgBIgLgBIgBBBQAOgKAJgNIArhBIABgHIAGgJIAYAGQAWAFAJAFQgFAlAAALIgCA6IABANQAEADASAAQAGAAAAADIgBAJIANAAQABAAABAAQAAAAABAAQAAAAABAAQAAgBAAAAQACgYABhKIgLgDQgGgCgDgDQgCgBAAgFIgCgfQgBgLADgEIBNAHQAGAagBANQgBAEgFAAIgDgBIgLgBIgBBBQANgKAKgNIArhBIABgHIAGgJIAiAIQANAEAIAEQgGAlAAALIgCA6IACANQAEADARAAQAHAAgBADIgBAKQgBANgCAIQgCAIgDACIhCgCQgKgBgCgCIADgjQAKgDAGABIABAAIABAAQAAAAABAAQAAAAABgBQAAAAAAAAQAAgBABAAIgGgkQAAgNgCgDQgJAQgNAgIgUAtQgGABgdAAIgSADgAptBoIgfAAIgnABQgCAAgEgCIABgNQAAgIABAAIAJgIIgCgvIgBgTIgCgaQgNACgMABIgagBIgFABQgBAEgBAMIACBHIAJABQAHACgBABQAEAIABAPIABAFIgIABIhIACIAAgGIABgXIADgEQABABAHAAIACgGQABgzgCgYIAAgHQgCgDgEAAIADgBIgSgDIAAgIIAHgcIABgCQAdACAZAAQAZgBAWgCQArgEAUABIAKAkIgCAAIgRAFIAGBCQAAgCAAAAQABgBAAABQAAAAAAACQABABAAACIABAOQACACAIAAQALgBACACIAAAKIACAAIANAAQABAAABAAQABAAABAAQAAAAAAAAQABgBAAAAIAChiIgKgDQgHgCgDgDQgCgBAAgFIgCgfQgBgLAEgEIBNAHQAFAagBANQAAAEgFAAIgEgBIgKgBIgCBBQAOgKAJgNIArhBIABgHIAHgJIAWAGQAWAFAKAFQgFAlgBALIgBA6IABANQAFADARAAQAGAAAAADIgBAKQgBANgCAIQgDAIgDACIhBgCQgKgBgCgCIACgjQALgDAGABIABAAIABAAQAAAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAIgFgkQAAgNgCgDQgJAQgNAgIgVAtIg0AEgAKlhnIgXgFIAOglIAMAHIANAGQAHABAHAAIAQAAIAegIIAIAfIgkAHIgVACg");
	this.shape.setTransform(81.5,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol59, new cjs.Rectangle(0,0,162.9,29.2), null);


(lib.Symbol54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#00B138","rgba(0,33,5,0)"],[0,1],-33.9,11.1,36.1,-12).s().p("ApdH9IKOygIItTgIgCABQj3BmkiAAQl0AAksing");
	this.shape.setTransform(60.6,67.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol54, new cjs.Rectangle(0,0,121.2,135.2), null);


(lib.Symbol53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.pizza1();
	this.instance.parent = this;
	this.instance.setTransform(-3,-2,0.168,0.168);

	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#00FF00","rgba(0,178,58,0.996)","rgba(0,176,58,0.929)","rgba(3,146,45,0)"],[0,0.106,0.263,1],0,0,0,0,0,5.4).s().p("AgiAjQgPgOAAgVQAAgUAPgOQAOgPAUAAQAVAAAOAPQAOAOAAAUQAAAVgOAOQgOAOgVAAQgUAAgOgOg");
	this.shape.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol53, new cjs.Rectangle(-3,-2,14.8,14.8), null);


(lib.Symbol51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.mouse();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol51, new cjs.Rectangle(0,0,93,115), null);


(lib.Symbol49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC00").s().p("AgHEVIgXgCQgLAAg6gWIgwgTQgRgJgZgdQgagdgLgUQgOgbgIgfQgHgfAAgjQAAhhAihGQAUgqAfgbQAfgdAqgNIBAgPIA+gIIAgAGIAjAEQBQAZAoA+QAoA+AABlQAAA+gIAfQgKAlgWAjQgWAighAfQhHBDhKAAgAhNhIQgZBVAAAkQAABeBeAAQAMAAAdgdQAbgaAIgQQAWgrAIgmIADguQAAhihlgRIgPgIQgkAigaBIg");
	this.shape.setTransform(13,56.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CC00").s().p("AiYEbIgEgcIgHg8QAIgHAdgHIApgMIAcgMIAEgqIgBgTIgBgvIgDiHIgngDIgqADIgFAAIgXgLIgMhHIAfgLQApgDAigeQAfgbAOgpIAQgHIBKgLQAAgEAFAAIAeAAIAGAbQAAgBAAgBQAAAAAAAAQABABAAABQAAACAAACIgBgEIgFA5IgHBhIgFDxIBOAJIAIAQIAFAwIADAaIAAADQgIAZjUAmIhgARQgLABgFgUgAg0B0IAAgEIAAgBIAAABIAAAEIgBAAIAAAAIAAgBIAAABIAAAAIABAAg");
	this.shape_1.setTransform(-35.1,51);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol49, new cjs.Rectangle(-68.5,6.6,107.6,104.3), null);


(lib.Symbol47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAgBDQgHAAgVgHQgIgFgGgHQgGgHgFgKQgGgKgBgKIgFAAIgEABIgDAAIgCABIgCAUQABABAFABIAHACIABAFIABAHIABACIAAADQAAABAAABQAAAAAAABQgBAAAAAAQAAAAAAAAIgRABIgPABIgEACIgGABIgBgBIgBAAIgIACQgEACgDAAQgDAAgCgMIgCgNQAAgBAIgBQAJgBAAgBIABgMIgBgDIAAgEIACgeIAAgFIAAgEIAAgCIAAgCQAAgHgBAAIgNgBIgBAAIAAABIAAgBIgBAAIgBAAIgBABIgDgBIADgRIABgBIARgEIATgCIABgBIASgCIAFAAQADAAABAGQAAAHgDANIgFACIgFAYIALAAIABAAQAAgLACgJQACgJAFgHQAFgKANgFIAOgFIAMgBQAGAAATAEIAUAEQASAGAIAeQADANABAMQAAAIgEAMQgFANgEAHQgFAHgKAHIgKAGIgJACIgGABIgGABgAARgsIgBADIgEAHQgCANAAARQAAARAFALQADAGAHAFQAIAFAHAAQAGAAAFgCQAEgDADgEIADgJIABgMQAAgQgDgNQgCgHgKgJIgHgHQgHgDgIAAIgIABgAgaAKIgCAAg");
	this.shape.setTransform(114.9,9.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF0000").s().p("AgeBAQgEgDgCgDIgEgHIgBgGQABgJAGgHQAEgEADgBQAEgCAFAAQAGAAADAEQADAFgBAIIgBAGIAIgDQAFgEADgFQADgFABgHIAAgJQgLADgOgBQgEAAgIgCQgVgEAAgaIABgYIgIgDQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIAAgBIABgVIASACIADAAIACABIAEAAIADAAIAQADQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIgBAJIAAACIAAACIABAOIgLABIAAAEIABAPQABANAWgIQAFgCACgGIACgTQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAAAIgFgDIgBAAIgBAAIgBAAIABgSIAXAAIAWABQADAAABAHQgCABgBAVQgEACgDgDQACANgEAgQgEAZgSAPIgKAIIgNAEIgOACQgHgBgJgFg");
	this.shape_1.setTransform(99.6,9.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF0000").s().p("AhAA7QgBgBgBAAQgBAAgBAAQAAgBAAAAQgBAAAAAAIAAgDIABgNIARgGIAAgMIgEg3IgNAAIgFgCQABgOADgJIAVgBIASAAIARAAQACACABAJIABAPIgQAFIAAAEIACALIADAIIAAAAIAAAAIADgBIAKgBIANgBIACAAIADAAIADAAIAFgBIAFgBIACgTIgFgBIgMAAIAAgBIgBgBIACgEIABgFIAAgIQABgDANgBIAPgBIAVAAIAEgBIAEgBQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIADAQIAAABIgBABIgRADIAAA5IALABQABADABAJIABAPIgEABIgEABIgaACIgaABIABgPIABgKQABgBAEgBIAGgCQgCgQgDAAIgNACIgVACIAAAPIAIAAIAGAAIADACIAAAIIgBANQgCABgPAAIgGAAIgbADIgEAAIgFAAgAgCAgIAAAAIAAAAg");
	this.shape_2.setTransform(86,9.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FF0000").s().p("AAIA9IgVgCIgBAAIgBAAIgBABIgFAAIgFAAIgDAAIgCAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAIABgJQgBgFACgBIASgEIAAgFIAAgfIgBgeIAAgHIgBgHIgSABIABALIAAAIQAAAFgBAEIgTgBIgDAAIgDABQgCAAAAgKIABgOIABgXIADgBIATAAIAdgBIAcAAIASAAIAKABIAKABIADAWIADAPIAAAKIgBAAIgGAAIgKgBIgNgDQgCgUgCAAIgOADIACARIAAALIAAATIABAJIAAAJQABACAHgBQAIABABACIAAABIAAAHIAAAQg");
	this.shape_3.setTransform(72.7,8.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF0000").s().p("AAIArIAKgGQgDgNgCAAIgNACIgOACIgHADIAAAJQAPACAAADIgBAGIgBAGIgDAGIgZgCQgTAAgMgEIAAgDIAEgJQACgGACgBIANgCQABAAAFgTIAGgZIAHgVIAIgeQABgFACAAIAjACQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIANAlIAIAaQAFASAHAMIALABQACAAAAAGIAAAHIAAAJQgEACgJAAIgPABIgcAGQgCgJgBgNgAASAFQgCgJgGgLIgKgTQgDAWgBAMQAEACASADIAAAAg");
	this.shape_4.setTransform(59.8,9.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FF0000").s().p("Ag8A6QgIgFgCgGIgBgGQAAgJAHgGQADgDADgCQADgCAFAAQALAAAAAPIgBAGIAGgDQAFgDACgFIADgLIgBgLIABgFIgDgVIgBgNQAAAAAAgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIgNAAIgBAAIgBAAIgBAAIAAgTQAHgDAKgBIASgBIANAAQApgEAKAAIAHAWIgBAAIgLADIACAQIABAYIABAUQABgBAAAAQAAAAAAAAQAAAAABABQAAABAAABIAAAIQACACAEgBQAIAAABACIAAABIAAAHIAAAPIgVABIgYAAIgDgBIAAgIQAAgFABAAIAFgFIAAgEIgCgjIAAgGIAAAAIgBgEIAAgRIgBgKIgUADQgCAFACAIIABARIAAADIAAALQgBAWgPAPIgKAIIgNAEIgMACQgHAAgIgFg");
	this.shape_5.setTransform(45.2,9.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF0000").s().p("AgvA5IgMgBIgBgDIABgJIAAgHIACgCQABABAFAAIABgEQABgigBgQIgBgFQAAAAAAgBQgBAAAAAAQgBAAgBgBQAAAAgBAAIADgBIgMgBIAAgGIAEgTIAAgBIAlABQARAAANgBQAdgDANABIAHAXIgCAAIgLAEIACARIABAGIABAUQAAgBAAAAQAAAAAAAAQABAAAAABQAAABAAACIABAIQABACAFAAQAIgBABACIAAABIAAAIIABAQIgXABIgaAAIgEgBIABgJQgBgFACAAIAGgGIAAgEIgCgbIgBgLIAAgIIgBgKIgQACIgRgBIgDABQgBADAAAIIAAATIABAMIAAAPIAGABQABAAABAAQABABAAAAQABAAAAABQAAAAAAAAQACAFABAKIAAAEIgFABIgUABg");
	this.shape_6.setTransform(31.8,9.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FF0000").s().p("AgcA/QgKgFgJgJQgOgSAAgcIAEgQQAPg2AoAAIAEABIADAAQAGAAAHAEQAIAEAJAIIABgGQAHgDAPgBQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIACAlIABAFIAAAEQAAACgKAEIgLADIgIgRQgIgNgDgDIgIgDIgJgBQgEAAgEAEIgHAHQgDAGgCAIIgEAPIgCAIQAAAMAHAIQADAEAFACQAEACAFAAIADAAQADAAAJgFQAGgDAFgIIADgHQAFgBAJAAQADAAAAAGQAAAIgCAGQgCAHgEAGQgJAMgOAFIgDACQgJAEgJAAQgOAAgLgFg");
	this.shape_7.setTransform(18.4,9.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FF0000").s().p("AgxA9QgGgCAAgBQAAgNABgCQABgDAJgDIAFgBIgBgNIgCglIgBgQQAAgBgHAAIgBAAIgCAAIgGgBIABgTIAJgDIBIgFIAOgBIAJgBIAHAAQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAIgBAGIABANIAAAJQAAANgCADIgSgBIgFgUQAAgEgEAAIgJAAIgBAAIgCAAIgDABQgFgBgNAEIAAAeIABAAIAMgDIABgPIADAAIAPADIABACIABAaQAAAJgDAKIgLACQgCAAgBgIIgBgIIgBAAIgJAFQABAEADAIIAEALIAXgEIAJgDIAAgLQAAgKAEAAIAGABIAFABIACABIACAAQAAAAAAABQAAAAAAAAQAAABABAAQAAAAAAABIACAnIgKAAIhbADIgIgBg");
	this.shape_8.setTransform(6.4,9.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FF0000").s().p("AgWBEQgfAAgFgBIgDgCIgCgZQAAgEAFAAIAEABIADAAIAGAAIAAgIIAAgOIACgTIAAgPQABgQgBAAIgFAAIgPgBIACgRIACgBIAQgEIATgCIABgBIATgCIAUgBQAOAAALgCIANgBQADAAAAAJIAAAGIgCAeQgEgBgPADIgCgCIABgRIgWACIgRACIgCALIgBAKIAAABIAWAFQAHABAJAEIAPAGIAJAHQAFAEABAGIACAEIABAFIgCALQgCAIgCACQgEAGgIADIgPAFIgSADQgKABgKAAgAgSARIgCAbIAVAAQAFgBAFgDQAFgEAAgGQAAgFgCgBIgIgHIgSgDIgCAAIgCgBIgBAAIgBAEg");
	this.shape_9.setTransform(-5.5,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol47, new cjs.Rectangle(-12.9,1.5,137.3,20.1), null);


(lib.Symbol43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#00B23A").ss(2,1,1).p("AEgoAIo/QB");
	this.shape.setTransform(28.8,51.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol43, new cjs.Rectangle(-1,-1,59.5,104.6), null);


(lib.Symbol42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(0,0,0,0)","#000000"],[0,1],-155.8,0,155.8,0).s().p("A4VYUMAAAgwnMAwrAAAMAAAAwng");
	this.shape.setTransform(466.5,150.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.instance = new lib.setka();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol42, new cjs.Rectangle(0,-5,622.4,311.2), null);


(lib.Symbol37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("At8DeQhcABhChCQhBhBAAhcQAAhbBBhCQBChBBcAAIb5AAQBcAABBBBQBCBCAABbQAABchCBBQhBBChcgBg");
	this.shape.setTransform(111.6,22.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol37, new cjs.Rectangle(0,0,223.2,44.5), null);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().rs(["rgba(51,255,0,0.188)","#006600","rgba(0,255,0,0.2)"],[0,0.518,1],0,0,0,0,0,14.6).ss(9,1,1).p("ABkAAQAAAqgdAdQgdAdgqAAQgpAAgdgdQgdgdAAgqQAAgpAdgdQAdgdApAAQAqAAAdAdQAdAdAAApg");
	this.shape.setTransform(10,10);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol16, new cjs.Rectangle(-4.5,-4.5,29,29), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.radarback();
	this.instance.parent = this;
	this.instance.setTransform(-3,-4,0.968,1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AusOtQmGmFAAooQAAonGGmFQGGmGImAAQIoAAGFGGQGGGFAAInQAAIomGGFQmFGGooAAQomAAmGmGg");
	mask.setTransform(143.6,142.8);

	// Layer 1
	this.instance_1 = new lib.radar();
	this.instance_1.parent = this;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-3,-4,302,300), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.pizzatext();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,600,300), null);


(lib.Symbol63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol64();
	this.instance.parent = this;
	this.instance.setTransform(36,21.4,1,1,0,0,0,36,21.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.07,scaleY:1.07,y:21.6},7,cjs.Ease.get(-1)).to({regX:35.9,regY:21.3,scaleX:1.3,scaleY:1.3,y:22},7,cjs.Ease.get(1)).to({regY:21.2,scaleX:1.21,scaleY:1.21,y:21.8},8,cjs.Ease.get(-1)).to({regX:36,regY:21.4,scaleX:1,scaleY:1,y:21.4},7,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,72,42.8);


(lib.Symbol62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA40").s().p("AhfBuIgBgdIAAgEIABgDIAcgPIAAgCIgFggIgEgZIgDgXIgGglQgBgCgEAAIgFAAIgEAAQgIAAgGgEIAAgnQAKgEAHAAIAdgBIAEABIADABIAJgCIAKgCIAQgBQARABARAEIAdAJQAMAGAIAGQAJAFAFAHQAHALAAALIABACIABACQAAAWgLAQIACACQAKAEAJAFQAIAHAFAIQAGALADAOIABAPQAAAPgMANQgLAOgQAFQgTAGgMgBIgCACQgzAFghgBgAgLAOIgEABIgIACIAAADIAFAbIAGAaIAFAAQAIAAAbgJQAJgDAEgGQAFgHAAgJQgBgOgUgGQgPgGgRAAgAgRhGIgBAfIAAANQABAEAJAAIADAAQAHAAAMgGQARgJAAgKQAAgGgEgEQgEgFgHgFQgNgHgJAAQgLAAAAAEg");
	this.shape.setTransform(232.1,160.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCA40").s().p("AgDB9QgMAAgmgOQgQgJgMgNQgMgOgKgRQgPggAAglQAAgXADgTQAEgSAIgOQAKgSAYgJIAcgJQANgDAKAAQALAAAiAHIAlAIQAiAMAPA4QAGAYAAAWQAAAPgHAXQgIAYgHAMQgKAPgTAMQgKAHgJAEQgJADgIABIgLACIgLACgAgchTIgEAGIgGANQgEAZAAAfQAAAhAIATQAGAMAOAJQAOAKAMAAQAMAAAHgFQAJgEAGgJQADgIADgJQACgKAAgLQAAgegIgZQgDgOgRgQIgPgNQgLgGgNAAQgHAAgIACg");
	this.shape_1.setTransform(209.1,159.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCA40").s().p("AhwBsQgPgJgDgMIgCgKQAAgRALgMQAFgGAGgDQAHgDAJAAQAUAAAAAcIgBAKIALgGQAIgEAFgLIAFgUIgBgVIABgIIgFgoIgBgYQAAgBgBgBQAAAAAAAAQAAgBgBAAQAAAAgBAAIgWAAIgCgBIgCgBIgBACIAAglQALgGAUgBIAhgCIAZgBQBLgGAVAAIALApIgCAAIgUAGIAEAdIAEAuIABAkQABgGACALIABAPQACACAJAAQAMgBADADIAAADIAAANIACAcIgoABIgsABQgEAAgEgCIABgQQAAgJACgBIALgIIAAgIIgFhAIAAgEIgBgQIgBggIgBgSIgmAGQgDAIADAQIABAfIAAAGIAAAUQgCArgdAbIgSAPQgHAEgPADQgQAEgIAAQgMAAgPgJg");
	this.shape_2.setTransform(182.7,161.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCA40").s().p("AAOBPIAVgLQgHgXgEAAIgZACIgaAEQgHACgGAEIAAAQQAcAEAAAGIgDALIgCAMQgBAHgDADQghgEgOABQgiAAgXgHIAAgHIAGgPQAEgMAEgBIAXgEQADgBAKgjIAMguIAMgoQAJgeAGgbQACgHAFAAIBBADQABAAAAABQABAAAAAAQABABAAAAQAAABABAAIAXBFIAPAyQAJAgANAXQAHgBAPADQADABgBAKIABANIABARQgJADgQABIgcACIgzAKQgGgRgCgYgAAiAJQgEgRgLgVIgSgjQgHApgCAXQAIADAiAGIAAAAg");
	this.shape_3.setTransform(157.2,161.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCA40").s().p("AgqB/Qg5gBgJgCIgFgDIgFguQAAgIAJAAIAHABIAHACIAMgCIgBgNIABgbIACgjIABgeQABgcgCgBIgJAAIgbgBIADggIAEgDIAegGQATgEAQAAIACgCIAjgFIAmgBQAaAAAVgDIAYgDQAGAAAAASIgBALIgDA3QgJgCgaAGIgEgDIACgfQgKAAgfADIghAEIgDATIgEATIAAACIAsAJQANADAQAHIAcAMIARANQAJAIACALIACAIIADAHQAAAIgEAOQgDANgEAGQgIALgPAGIgcAIQgPAEgSACQgSACgTAAgAgjAfIgCAzIAmAAQALgBAIgHQAJgHAAgKQAAgKgDgDQgLgKgEgCIgigGIgDgBIgEAAIgDAAIgCAGg");
	this.shape_4.setTransform(134.2,161.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCA40").s().p("Ag8CUQg9AAgXhKQgIgZAAgmIACgMIACgMIAAgnIADgUIgjgKIAEgUQADgNAHgFIAmgFIAVAAIAXABIATgBIANgCQAHAAACAFIAAAnIgBAaIgBAaIgBAUQAAArAKAVQALAXAVAAQAEAAANgQIAHgKQAHgQACgQIAGgnQAAgkgHgYIgMAFIgLAFIgFgCQgHggAAgNIAAgGQAsgRA5AAIADABIACAAIAmgHQAMAvABgBIgBACIAAACIgdAEIgDASIAOCdIAFACIAPgEIAPgDQAIAAACASIACAUIACADIABAFQAAAJgEAAQhEAFgtAKQgDgGgDgTQgDgUgDgGQgJAQghASQggASgUAAg");
	this.shape_5.setTransform(222.8,109.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCA40").s().p("AAgCBQAAgKgDgHIADg3IgIAEQgeALgTAAIgSAAQgvgVgUgfIgMg+QABgjgIgNIghgHIAEgOQADgIAGgEIAmgCIATAAIAWAAIASgBIAMgBQAHAAACADIAAAaIgBAXIgCAZQAAA5AnAAIAXgIIAGgdIABgnQAAgBgSAAQgEgfAFgSIAAgGQAkgPAvgBIABABIADAAIAngEQADAjADAQIgBACIAAACIgaADIgDARIAACMIAFABQAGAAAIgDIANgDQAJAAAAASIABAlIABAEIAAAFQAAAIgFgBQhIABg0AHQgDgGABgKg");
	this.shape_6.setTransform(188.8,108.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFCA40").s().p("AhaCyQgPgEgPgKQgRgLgIgNQgJgNAAgRQAAgLAFgLQAFgLAJgKQAUgTAXAAQARAAAOAKQAOAKAAAQQAAAOgGAKIgQAUIAJADQAGAAAJgIIAMgNQAOgXAAgHIgSghIhDikQgCgCgDAAIgMABIgYABQgCAAgBgFIAAgMIABgIIAAgDIACghIA/gEIBBABQAJABAGAYIADASIgeAWQAMAKARAZQARAZALAKIAdhDQgIgDgfAAQgGAAAAgHIAFgUIADgYQAEgEAEAAIAcABIAdACQBAACAGAIIAAAvIgCAHQgcAJgGAIIgIAVQgNAxgaAxIg5BoQgKAUgVANQgWAOgVAAQgQAAgPgFg");
	this.shape_7.setTransform(156.4,117.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCA40").s().p("ACICMIgigDIhAgEIANg5IAXAEIgBgaIACghIABgoIgBgeQgHgJgGgCQgGgDgOAAQgXAEgGAgIgBA6QADAegGAdQgOAcgbAMQgcAMgfAAQgaAAgdgNQgigPgEgWQgHgTADgXQACgLAGgIQAGgIAKgFQAVgKANAAQARAAANAQQAMAPAAASIgBAKIAAAEQAKgGACgPIACgUIgCgkIgBgYQACgaAOgWQAOgWAcgSIAWgMQAjgOApADIAeAFIAoAJIApALIAAAlIAAACQABAjgDAGIgXgFIAAgEIgBAEIgBAAIABADIgFAdIADA6IgCAhQAEADAMAFIAPAHIgCAtIgDgCIgCADgACjgmIAAAAIAAgDIABAAIgBAEIAAgBgACjgmIgBgDIABAAIABgEIAAAEIgBAAIAAADIAAAAgACjgmIAAAAgACkgpg");
	this.shape_8.setTransform(122.4,109.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFCA40").s().p("AhQCEQgdgTgUgdQgEgGgFgWIgEgeQAAg/AXgpQAWgpAugRQAggQAdAAQAbAAAVAKQARAJAYAUQAaAXAEAOIAOBBIAAAJIAAAYQgIA+gtAjQgWARgbAJQgaAIgeAAQggAAghgVgAgihKQgEAIgHAcQgKAkAAAXQAAAWALASQAGALAIAFQAIAFALAAQAbAAASgvQANgiAAgeQAAgZgOgTQgQgVgWAAQgSAAgLAUg");
	this.shape_9.setTransform(86.9,109.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFCA40").s().p("AAUCRQgEgTAAgTIAAgJIABgIQAWgDAFgNIAAgmIgDgxIgGgjQgIgNgYAAIgUABIgUACQgMACAHAiIADAlIACAlIgCATIgBAQIAXgCIAKA6IhBABIgxAAIgsAAIgCgDIgDACIAAgsQAEgEAPgDQAPgDAEgDIgEhGIADgSIABgEIAAgDIgogEQgDgHgCgiQACAZAAgUIgBgaIABgqQACgCAngEIA2gMQAugJAigBQAvgDAfAKQAXAGAOALQANALAHAOQAIAQgBAWQAAAhgEAWQgBAQADAMQACAPAGAGQAHAHALgBIAJAAIABAHIACAIIgDAfQgCATACANIgBAFIgBAEIgrABIgHACIgIABIgfACIgHABIgiABQgUAAgDgCg");
	this.shape_10.setTransform(55,109);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 4
	this.instance = new lib.icon2();
	this.instance.parent = this;
	this.instance.setTransform(186,10,0.307,0.307);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 700
	this.instance_1 = new lib.Symbol63();
	this.instance_1.parent = this;
	this.instance_1.setTransform(70.9,161.9,1,1,0,0,0,36,21.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 1
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFCA40").s().p("AgtA6QgGgCAAgCIAAgOQABgCAJgDIAFgBIgCgMIgCgjIAAgPQAAgBgHAAIgBAAIgCAAIgGgBIACgRIAIgDIBDgGIAOAAIAJgBIAFAAQABAAAAABQAAAAAAABQAAAAAAABQAAABAAAAIAAAFIAAAMIABAIQAAAMgCAEIgSgBIgDgTQgBgDgEgBIgIAAIgBABIgCAAIgCAAQgFAAgNADIAAAcIACABIAKgEIABgNIAEAAIANACIABACIABAYQAAAJgCAJIgLABQgCAAAAgGIgBgIIgCAAIgIAEQABAEADAIIAEALIAVgFIAJgCIAAgKQAAgJADAAIAGABIAFABIABAAIACAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIACAlIgKABIhVADIgHgBg");
	this.shape_11.setTransform(163.1,53.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFCA40").s().p("AgqA7IgKAAIgNgCIgCgQIAFgBIAJAAQAAAAABAAQABAAAAgBQAAAAABAAQAAAAAAAAIABgWIAAgSIAAgVIgGgCQgFgBgBgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgEIAAgKIgBgGQAAgHACgCIAXACIAZACQADAQAAAJQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgCgBIgHAAIAAAVIAAATQAIgGAGgIIAJgNIAHgNIAKgPIAAgEIAEgFIAPADQANADAGADQgDAXAAAIIAAASIgBAJIgBAIIABAJQADABALAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAIgBADIAAADIgCANQgBAFgCABIgZAAIgQAAQgGgBgBgCIABgVIAKgCIABAAIABAAIABgBIAAAAIAAAAIgDgXQAAgHgBgCQgGAKgIAUIgMAcIgLABIgLAAIgDAAIgDAAIgCAAIgDABg");
	this.shape_12.setTransform(151,52.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFCA40").s().p("Ag8A3QgBAAgBAAQgBgBAAAAQgBAAAAAAQAAgBAAAAIAAgCIABgMIAPgGIAAgLIgEgzQgCgBgKAAIgEgBQAAgOADgJIAUgBIARABIAQAAQACACABAIIABAOIgQAEIAAAEIADAKIACAJIADgBIAJgCIANAAIABAAIADAAIADAAIAFgCIAEgBIACgSIgEgBIgMABIAAgBIAAgBIABgEIABgEIAAgJQABgCAMAAIAPgCIATAAIAEAAIAEgBQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIACAOIAAABIAAABIgRADIAAA1IAKABQACADAAAIIABAPQAAAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAIgEABIgYACIgZABIABgNIABgKIAFgCIAGgDQgDgOgCAAIgNACIgTABIAAAQIAIgBIAFAAIADACIAAAHQAAAHgBAFQgCABgOAAIgFAAIgaADIgEAAIgEABg");
	this.shape_13.setTransform(137.4,53);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFCA40").s().p("AguA6QgFgCAAgCIABgOQABgCAIgDIAEgBIgBgMIgCgjIAAgPQAAgBgHAAIgBAAIgBAAIgHgBIABgRIAJgDIBEgGIAMAAIAJgBIAHAAQAAAAAAABQAAAAAAABQAAAAAAABQAAABAAAAIAAAFIAAAMIABAIQAAAMgCAEIgRgBIgEgTQgBgDgEgBIgIAAIgBABIgCAAIgCAAQgFAAgNADIAAAcIACABIALgEIAAgNIADAAIAOACIABACIABAYQAAAJgCAJIgLABQgBAAgCgGIgBgIIgBAAIgIAEQABAEADAIIAEALIAVgFIAJgCIgBgKQABgJADAAIAFABIAGABIABAAIACAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABAAIACAlIgKABIhVADIgIgBg");
	this.shape_14.setTransform(125.1,53.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFCA40").s().p("AhZA7IgBgHIAAgIIgBgHQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAKgDIALgPIADgEIAPgNIgMgKIgTgPIgFAFIgEADIgFgEIgEgFQACgEAHgGIAJgHIANgIIANADQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAIgDAGQgDAEgCAAIALAGIAaAOIAIAFIgBgNIgQgEIAAgUIAbgDIAOgDIAQgCQAFAAACAJIADAKIgSAGQAAAJAEAMIANgKIASgLIANgGQgCAAgEgFIgCgFIABgCIAOgDIANAIIAJAHIAJAKIgEAFIgFAEIgFgDIgEgFIgSAOIgNALIAPANIADAEQADAFAIALQAEAAAGACIABAEIgBAIIAAAHIgBAHQgDACgFgBIgIAAIgIgBIgJABIgHAAIgIAAIgBAAIgCABQgCAAAAgFIgBgFIAAgGQAAgEADgCIAHgEIgSgPIgMgJIAAABIgBAIIAAAHIAAAGIACAAIAFgBIAEgBIADABIAAAVQAAAAAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgbABIgMABIgJAAQgDAAgCgDQgBgCAAgIQAAgFAHgCIAFgDIAAgPIAAgDIgOAJIgQAMIAHAEQADADAAAHIgBAIQgMACgZABIgIABIgDAAIgFgBg");
	this.shape_15.setTransform(109.9,52.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFCA40").s().p("AgBA/QgGAAgTgHQgJgFgGgGQgGgHgEgJQgIgQAAgSQAAgMACgJQACgJAEgHQAFgJAMgFIAOgFIALgBQAGAAARAEIASAEQASAGAHAcQADAMAAAKQAAAIgEAMQgDAMgEAGQgFAHgKAHQgFADgEACIgJACIgFABIgGABgAgOgpIgCADIgDAGQgCANAAAQQAAAQAFAJQACAGAIAFQAGAFAGAAQAGAAAEgDQAEgCADgEQACgEABgFIABgKQAAgPgDgNQgCgHgJgIIgHgGQgGgDgGAAIgIABg");
	this.shape_16.setTransform(94.4,52.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFCA40").s().p("Ag4A3QgHgFgCgGIgBgFQAAgIAFgHIAGgEQADgCAFAAQAKAAAAAOIAAAFIAFgCQAEgDACgFIADgKIAAgLIAAgEIgDgTIAAgNQAAAAAAgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgMAAIgBgBIAAAAIgBABIAAgSQAFgDAKgBIARgBIANAAIAwgEIAGAVIgCAAIgKADIACAPIACAWIABATQAAgBAAAAQAAgBAAABQABAAAAABQAAAAAAACIABAIQABABAFgBQAFAAABACIAAABIABAHIABAOIgVAAIgVABIgEgBIABgIQgBgFABAAIAFgFIAAgEIgCggIAAgGIAAgDIgBgQIAAgJIgTACQgCAFACAIIAAAPIAAADIAAAKQgBAVgOAOIgJAIIgLADIgNACQgGAAgHgEg");
	this.shape_17.setTransform(81.2,53.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFCA40").s().p("AgqA7IgKAAIgNgCIgCgQIAFgBIAJAAQABAAAAAAQABAAAAgBQAAAAABAAQAAAAAAAAIABgWIAAgSIAAgVIgGgCQgFgBgBgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgEIAAgKIgBgGQAAgHACgCIAXACIAZACQADAQAAAJQAAAAAAABQgBAAAAABQgBAAAAAAQgBAAgBAAIgCgBIgHAAIAAAVIAAATQAIgGAGgIIAJgNIAHgNIAKgPIAAgEIAEgFIAPADQANADAGADQgDAXAAAIIAAASIgBAJIgBAIIABAJQADABALAAQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAIgBADIAAADIgCANQgBAFgCABIgZAAIgQAAQgGgBgBgCIABgVIAKgCIABAAIABAAIABgBIAAAAIAAAAIgDgXQAAgHgBgCQgGAKgIAUIgMAcIgLABIgLAAIgDAAIgDAAIgCAAIgDABg");
	this.shape_18.setTransform(68,52.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFCA40").s().p("Ag3A1IgBgEIAAgEQAAgEARgHIAAAAIAAgNIgDgiIAAgJIABgHIgGAAIgEAAIgDABQgFAAAAgDIACgYIADgCQAUgBAcAAIASABIARADIAOAEQAIADADAGQACACACAHIACALIgBAEIgCAEQgBAFgEAEIgJAGIgOAGIgPAGIgVAEIAAAIQAAAGACACIADAAIADAAIAEAAIADgBIADAAQABAAAAAAQABAAABAAQAAAAABABQAAAAABAAIgBALIAAAJIgiADIgkACgAgSgPIABAFIABADIACAAIABAAIACAAIABAAIACgBQAHAAAGgDQACAAAGgFQACgCAAgEQAAgGgFgDQgEgEgFAAIgTAAIAAAUg");
	this.shape_19.setTransform(55.8,52.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFCA40").s().p("AgsA1IgLAAIgBgEIABgIIAAgGIACgCQABABAEAAIACgEIgBgvIAAgEIgEgCIACgBIgLgCIAAgFIAEgRIAAgCIAiACQAQAAANgCQAagCANAAIAGAWIgBAAIgLAEIACAPIABAGIABATQAAgBAAAAQAAAAAAAAQABAAAAABQAAABAAACIABAIQABABAFAAQAHgBABACIAAACIAAAHIABAPIgWAAIgYABIgDgBIAAgJQAAgFABAAIAGgFIAAgEIgCgZIgBgLIAAgHIgBgKIgPACIgQAAIgDAAQgBADABAIIAAASIAAALIABAOIAFABQABAAABAAQABABAAAAQABAAAAAAQAAABAAAAQACAEABAKIAAADIgFABIgTABg");
	this.shape_20.setTransform(43.8,53.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFCA40").s().p("Ag+CJIgLAAIgSgCIgYgCIgCgcQAEgCAFAAIAPAAQAFAAAAgCQADgaAAhQIgMgDQgIgCgDgDQgCgCABgFIAAgHIgBgRIgBgKQgCgMAEgDIBUAHQAGAbgBAPQgBAEgFAAIgEgBIgLgBIgCBGQAOgKAKgPIAQgXIAegvIABgHIAHgKIAlAIQAPAEAIAEQgHApAAALIAAAjIgBAOIgBAOIABAQQAFACAUAAQAGAAAAAEIgBAGIgBAFQgBAOgBAIQgDAJgEACIgqAAIgdgCQgKgBgCgDIACglQAMgDAGAAIABAAIABAAQABAAAAAAQAAAAABAAQAAgBAAAAQAAAAABgBIAAAAIAAAAIgGgnQAAgNgBgEQgLASgOAiIgUAxQgIABgeAAIgGABIgGABIgEAAgAgRhYIgNgCIgNgDIgMgEIAPgnIANAIIAPAFQAHADAHAAIARgCIAQgDIARgEIAIAhIgSAFIgUADIgXABg");
	this.shape_21.setTransform(156.9,22.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFCA40").s().p("AAMBGIASgKQgFgVgEABIgWACIgXADQgFACgGAEIAAANQAYAEAAAEIgCAKIgCALQgBAGgDADQgcgDgMAAQgfAAgTgGIAAgFIAFgPQADgKAEgBIAUgCQADgCAIgfIALgoIAKgjQAIgbAFgXQACgGAEgBIA5AEQABAAAAAAQABAAAAABQABAAAAAAQAAABABAAIAVA9IAMAsQAIAcAMATIATACQADABgBAJIAAALIABAPQgHACgPACIgYACIgtAJQgFgPgCgVgAAeAIQgEgPgKgSIgQgeQgFAjgCAUQAHADAeAFIAAAAg");
	this.shape_22.setTransform(134.8,27.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFCA40").s().p("AgGBpIgIgCIAAgFQgEgPALgZQAAgBAGgCIAWgEQgBgLABgJIAAgEIggAAQgJAAgTgEQgggMgFgfQgFgfACgNQgDgBgLgBIgIgCIgBgEIAAgeIBWgEQAFAAABAHQgDARABAMIgCAQIgLgBQgJAYAMATQAIADALABQALABAOgDQACglACgBQABgOgCgFQgUgCAAgEIADgMIADgRQAUgDARABIAKACIAJABIAMABIAQAGQADAAAFAdIAAAJIgTACQAJAAgJABQgFABgDACIAAAHQgEAlgBA+IACAGIATAAIADAEIAAAUIAAAOIAAAGQgNgBgQAAIgWABIgGAAIgRABIgbgCg");
	this.shape_23.setTransform(114.4,27.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFCA40").s().p("AAMBGIASgKQgFgVgEABIgWACIgXADQgFACgGAEIAAANQAYAEAAAEIgCAKIgCALQgBAGgDADQgcgDgMAAQgfAAgTgGIAAgFIAFgPQADgKAEgBIAUgCQADgCAIgfIALgoIAKgjQAIgbAFgXQACgGAEgBIA5AEQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAIAVA9IAMAsQAIAcAMATIATACQADABgBAJIAAALIABAPQgHACgPACIgYACIgtAJQgFgPgCgVgAAeAIQgEgPgKgSIgQgeQgFAjgCAUQAHADAeAFIAAAAg");
	this.shape_24.setTransform(91.8,27.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFCA40").s().p("AAIBgIgBgKIgBgKQAAgHAFgEIAMgHQgKgKgogfIgBABIgBAPIAAAMIAAAKIADAAIAIgCIAJgCIAFADIAAAjQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBAAIgwACIgVABIgQABQgNABgEgEQgCgEAAgOQAAgJAMgDQAPgFACgCIAAgaIgFhLIgcgBIgCgJIAAgEIABgKIAAgSIAxgGQAIAAASgEQASgEAJAAQAIAAAFAQIAEAQIgfAMQABAPAGAUQAigcAqgTQgEAAgGgIIgEgJQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABgBIAXgFIAWAOQAIAFAKAIQALALADAGIgHAJIgIAHQgCAAgGgFIgIgIIg2AqIAaAZIAFAGQAGAJAOASQAIAAAJAEQACACAAAFIgBANIgBAOIgCAMQgEACgJgBIgPAAIgOgBIgPABIgMAAIgOAAIgCAAIgCABQgFAAAAgHg");
	this.shape_25.setTransform(69.2,26);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFCA40").s().p("AguBmQgRgHgNgQQgYgcAAgvIAHgbQAXhWBDgBIAGABIAGACQAJgBAMAHQAMAGAQANIACgKQAKgFAYgBQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIADA8IABAJIAAAGQAAADgPAFIgTAHIgOgdQgMgUgGgFQgFgEgHgBQgHgCgJAAQgFAAgHAHQgHAFgEAGQgGAJgEAOIgGAYIgCAOQAAAUAKAMQAGAGAHAEQAHACAJAAIAFAAQAGABANgIQAKgEAIgPQABgEAEgGQAHgCAQAAQAFAAAAALQAAAMgDAKQgEALgGALQgOATgXAIIgEADQgQAGgQABQgWAAgSgJg");
	this.shape_26.setTransform(47.1,26.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol62, new cjs.Rectangle(34.9,10,207.8,173.3), null);


(lib.Symbol55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol49();
	this.instance.parent = this;
	this.instance.setTransform(98.3,45.5,1,1,0,0,0,29.8,52.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol55, new cjs.Rectangle(0,0,107.6,104.3), null);


(lib.Symbol50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol51();
	this.instance.parent = this;
	this.instance.setTransform(42.5,53,1,1,-10.2,0,0,-0.1,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol50, new cjs.Rectangle(42.5,36,111.9,129.7), null);


(lib.Symbol48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol55();
	this.instance.parent = this;
	this.instance.setTransform(-14.7,58.7,1,1,0,0,0,53.8,52.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:52.2,scaleY:1.13,y:58.9},4).to({regY:52.1,scaleY:1,y:58.7},5).to({scaleX:1.12,x:-14.6},5).to({scaleX:1,x:-14.7},5).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.5,6.6,107.6,104.3);


(lib.Symbol46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol47();
	this.instance.parent = this;
	this.instance.setTransform(56.7,8.2,1,1,0,0,0,56.7,8.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:56.6,regY:8.1,scaleX:1.8,scaleY:1.8,x:56.6,y:8.1},4).to({regX:56.7,regY:8.2,scaleX:1,scaleY:1,x:56.7,y:8.2},5).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.9,1.5,137.3,20.1);


(lib.Symbol36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("At8DeQhcABhChCQhBhBAAhcQAAhbBBhCQBChBBcAAIb5AAQBcAABBBBQBCBCAABbQAABchCBBQhBBChcgBg");
	mask.setTransform(111.6,22.3);

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.31)").s().p("AsFB3Qk/gyAAhFQAAhEE/gyQFBgwHEgBQHFABFAAwQFAAyABBEQgBBFlAAyQlAAwnFAAQnEAAlBgwg");
	this.shape.setTransform(110.9,7.8);

	var maskedShapeInstanceList = [this.shape];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.instance = new lib.Symbol37();
	this.instance.parent = this;
	this.instance.setTransform(111.5,22.2,1,1,0,0,0,111.5,22.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol36, new cjs.Rectangle(0,0,223.2,44.5), null);


(lib.Symbol35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol36();
	this.instance.parent = this;
	this.instance.setTransform(111.5,22.2,1,1,0,0,0,111.5,22.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F24841").ss(2,1,1).p("At8jeIb5AAQBcAABBBBQBCBCAABbQAABchCBBQhBBChcAAI75AAQhcAAhChCQhBhBAAhcQAAhbBBhCQBChBBcAAg");
	this.shape.setTransform(111.6,22.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol35, new cjs.Rectangle(-1,-9,225.2,54.5), null);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol16();
	this.instance.parent = this;
	this.instance.setTransform(10.1,10.1,0.4,0.4,0,0,0,10,10);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:9.6,regY:9.6,scaleX:8.65,scaleY:8.65,x:6.6,y:6.6,alpha:0.199},29).to({alpha:0},8).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.3,4.3,11.6,11.6);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol 43
	this.instance = new lib.Symbol43();
	this.instance.parent = this;
	this.instance.setTransform(28.1,52.4,1,1,-0.9,0,0,28.8,51.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.instance_1 = new lib.Symbol54();
	this.instance_1.parent = this;
	this.instance_1.setTransform(60.3,53.7,1,1,0,0,0,60.6,67.5);
	this.instance_1.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(-2.5,-13.8,123.5,135.2), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00CC00").s().p("AhpDEIgDgTIgFgpQAGgFAUgGIAcgHIATgJIAEgdIAAgDIAAADIgBgNIgBghIgChdIgbgCIgdACIgEAAIgQgIIgIgxIAWgIQAcgBAYgVQAVgTAKgcIALgGIAzgGQAAgBAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAVAAIAEAUIgDAnIgFBDIgECnIA2AFIAGAMIADAhIACARIABAEQgGARiTAaIhCAMQgIgBgDgNg");
	this.shape.setTransform(58,0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00CC00").s().p("Ai9CgQADgZAJgVIAkg7QAQgZAXgNQAOgIAdgIQAdgGANgHIAcgRQALgJAAgQQgBgYgTgRQgUgSgZAAQgkAAgMAMIAEAEQAQAAAMAUQAMASAAARQABANgJAKQgHAKgQAHQgaALgVAAQgdAAgTgPQgSgQgBgcQAAgUALgkQAEgLALgMQAWgXAkgPQAkgPA0gHIAEgBIAFgBQA6AAAzAgQA6AmAAA4QAAAWgKAUQgJATgSAOIgSAUIgkAVQgTAGg7AGIgpANIABACQAKgDAtAJIAVAGIAeADQArAAAggkIAMgLIAtAHIAGAAIABADIABAEIgDAJIgDALIgMA6QgHAQgXAQQgXAQgRAAIgIAAIgHABIgJABIgJAAIgWAAQgSAAgvgSQgwgTgVAAQggAAgQApgACMAuIAAAAIAAAAg");
	this.shape_1.setTransform(59.3,1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00CC00").s().p("AgeDnIgmgLIgygVQgXgLgOgNQgTgQgLgVQgJgWAAgaQAAhHBgAAQAQAAAQAKQAXAQAAAkQAAAQgGALIgRAUIAbANIAfAAIADACIAFABIADgBIAFgCQAzgGAAg3QgBgggVgVQgMgLgNgFQgMgGgQABIgCABIgDAAQgMAAAAgJIAAgJIABgIIAAghIAHgEQAggCAQgLQATgNABgeQgBgNgPgNQgPgMgdgLIgOAAQglAAgWAPIAOADQAKAHAJAJIAJAXIAFAaIAAAEIgBAEQAAAHgIAKIgPANQgeAOgSAAQgNAAgPgJQgOgKgGgNQgOgWAAglQABg5AwgeQAUgNAagHQAZgFAegBQAyABAiAFQAjAGASAMQAdAUAPAVQAPAVAAAXQAAAZgOAhQgOAhgSAPQAmAOAQASQASAVAAAmQAAAXgLAXQgLAWgUAXQgaAbgZAOIgrAMQgqAKAGABg");
	this.shape_2.setTransform(60.8,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00CC00").s().p("AB8DhIgdgBIhmgIIgFgDQgEgWgDhAIgCgCIiqgLIgFg3QAAgUAog+IApg8QAIgPAWgfIApg3IAKgSIASgOQAFgDAVAAIAKAAIAIAAIACAAIgCAAQgJAAAdgDIAigDQAXAAAFALIABAiIADBVQABAzAHAeIA7gHQALAAABAHQAFAogBAUIAAALIgBAIIAAAJIg9AOQAGAVAGAvQAGAvAHAXgAg2gXQgeAkgLAVIBiATIAAgsQAAgbgKhAg");
	this.shape_3.setTransform(60.2,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00CC00").s().p("AgaDXQgpAAgwgWQghgOgQgTQgQgSAAgXQAAgbAOgcQAPggAXgFQAUgEAbAAQAbAAAOANQANANAAAbQAAAQgLANQgLAOgVAJQAMAKAfAAIAIAAIAPABIALgBQAfgMAOgNQARgRABgeQAAgRgHgQQgGgRgOgQQgZgfgggCIgDgBIgEgCQgfAAgVAMQgKAGgOAQQgJALgIAAQgIAAgvgfIAMhsIAOhOQAYgGBDAAICPAGIANAIIAABBQgRAFgUgBQhLABhIAGIgDAIIADARQACALgEAEIAIAAQAvgSA+AAQAQAAATAFIAoAQQAYAMAOAMQAOAMAFANQAOAoAAAZQAAAVgGAWQgGAVgMAWQgZAvgjAUQgFAGgcANQgiAKgiAAg");
	this.shape_4.setTransform(59.2,5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00CC00").s().p("AgfDdIgigLQgggJgZgTQgYgUgQgeQgOgZgHgfQgHgfAAgkIABgFIACgFQAAggAVgrIAlhFQAQgZAigVQAegTAhgIIAWgFIAngBQAUAAARAGQASAGAQANQAkAbAAAmQAABEhcAAQgKAAgTgIQgUgIgDgIIgEgSIADgPIADgQQgYAKgTAYQgUAZgOAoQAEADAZgKQAmgHAfAAIAKACIAKACIAZAAQAOAAAZAMQBMAkAABGQAAAugXAiQgYAigvAUQgoASgeABIgKACIgKACgAgiAWQgFAIAAAWQAAAzATAZQATAaAlAAQBAAAAAhFQAAgxhEgZIgNgEQgrAAgKAPg");
	this.shape_5.setTransform(59.9,1.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00CC00").s().p("AgXDXIgmgbQhLgxAAgJIBqh7IBHhYQAfgnADgGIhKAMIhkAGIgUBWIgFAAIgagLIgbgQIAQhlQAIgqAKgYQAFgNAXgBIAUAAIAKABQAIAAAJAOIAJAWQBGgLBngGQAwAAADAIQANAfAAAbIgEAJIgGAJIg5B7IgtBVIg9CVg");
	this.shape_6.setTransform(59.9,6.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00CC00").s().p("AgqDtQgyABg1gaQgVgLgXgyQgHgPAAgQQAAhKAugmQgQgJgNgdQgOgcAAgUQAAgtAWghQAWggAtgVQAfgPAlgHQAlgIAqAAQAPAAASAHQAQAGAUANQAWAPALAQQALARAAASQAAAXgRAnQgRAmgRASIAlAYQAYAOAIARQAXAwAAAXQAAA2hPAwQhBAmgxACIgnABgAg/B0QAAAWAHAKQAIAMAXAAIAPABIAOABQALAAAZgMQAcgOAAgOQAAgMgRgLQgRgMghgLIg1gUQgLAPAAAtgAg6iDQgOAOAAALQAAATAyAWIA6AXIAbgtQAJgSAAgJQAAgQgUgMQgVgNgRAAQgvAAgZAYg");
	this.shape_7.setTransform(60.5,0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00CC00").s().p("Ah5DYQgfgOgXgbQgMgOAAgRQgBgRAHgOQAFgOALgMQAXgXAhAAQAWAAASAQQATARAAAVQAAAGgLAUIAkABQAWAAAXgVQAXgXAAgVQAAgRgKgZIgxASQgOAEglAAQggAAgYgFQgYgHgQgMQgSgOgIgWQgJgVAAggQAAgqAOggQAOghAcgYQAzgrBWAAIAbAEIAdAHQAaAEAZASQAZARAYAdQAwA7AABKQAAAjgJAhQgLAhgSAfQgVAfgZAWQgaAWggAPQgXALgbAFQgaAGgfgBQgnAAgggMgAg9iOQgUASgEAcIgGAWQAAALARASQARASAMAEQAUAJAWgBQAcABATgSQASgRAAgcQAAglgSgVQgUgZgjAAQgcAAgWASg");
	this.shape_8.setTransform(61.5,1.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#00CC00").s().p("AgEDAIgRgBQgHAAgogQIgigNQgLgGgSgUQgSgUgHgOQgLgTgEgVQgFgWAAgYQAAhDAXgwQAOgdAWgUQAVgTAdgJIAtgKIAqgGIAWAEIAYADQA4ARAbArQAcArAABGQAAArgFAVQgIAagOAYQgQAXgXAWQgxAugzAAgAg1gxQgSA6AAAZQAABBBCAAQAIAAAUgUQASgSAGgLQAPgeAGgaIACggQAAhEhGgLIgKgGQgZAYgSAyg");
	this.shape_9.setTransform(72.5,4.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape,p:{x:58}}]},4).to({state:[{t:this.shape_1}]},7).to({state:[{t:this.shape_2}]},8).to({state:[{t:this.shape_3}]},15).to({state:[{t:this.shape_4}]},14).to({state:[{t:this.shape_5}]},9).to({state:[{t:this.shape_6}]},7).to({state:[{t:this.shape_7}]},5).to({state:[{t:this.shape_8}]},7).to({state:[{t:this.shape,p:{x:39.2}},{t:this.shape_9}]},12).wait(12));

	// Layer 1 copy 9
	this.instance = new lib.Symbol53();
	this.instance.parent = this;
	this.instance.setTransform(77,93.4,1.374,1.374,0,0,0,5,5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(88).to({_off:false},0).to({scaleX:1.82,scaleY:1.82,x:77.1,y:93.5},4).to({scaleX:1.37,scaleY:1.37,x:77,y:93.4,alpha:0},7).wait(1));

	// Layer 1 copy 8
	this.instance_1 = new lib.Symbol53();
	this.instance_1.parent = this;
	this.instance_1.setTransform(117,37,1.565,1.565,0,0,0,5,5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(76).to({_off:false},0).to({scaleX:2.07,scaleY:2.07,x:117.1,y:37.1},4).to({scaleX:1.57,scaleY:1.57,x:117,y:37,alpha:0},16).to({_off:true},1).wait(3));

	// Layer 1 copy 7
	this.instance_2 = new lib.Symbol53();
	this.instance_2.parent = this;
	this.instance_2.setTransform(153,14.3,1.496,1.496,0,0,0,5,5);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).to({scaleX:1.98,scaleY:1.98,x:153.1},4).to({scaleX:1.5,scaleY:1.5,x:153,alpha:0},20).to({_off:true},1).wait(6));

	// Layer 1 copy 6
	this.instance_3 = new lib.Symbol53();
	this.instance_3.parent = this;
	this.instance_3.setTransform(101,-7,1.443,1.443,0,0,0,5,5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(64).to({_off:false},0).to({regY:4.9,scaleX:1.91,scaleY:1.91,x:101.1,y:-7.1},4).to({regY:5,scaleX:1.44,scaleY:1.44,x:101,y:-7,alpha:0},22).to({_off:true},1).wait(9));

	// Layer 1 copy 5
	this.instance_4 = new lib.Symbol53();
	this.instance_4.parent = this;
	this.instance_4.setTransform(133.1,-51.1,1.496,1.496,0,0,0,5,4.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(57).to({_off:false},0).to({regY:5,scaleX:1.98,scaleY:1.98,y:-50.9},4).to({regY:4.9,scaleX:1.5,scaleY:1.5,y:-51.1,alpha:0},26).to({_off:true},1).wait(12));

	// Layer 1 copy 4
	this.instance_5 = new lib.Symbol53();
	this.instance_5.parent = this;
	this.instance_5.setTransform(85,-75.1,1.496,1.496,0,0,0,5,4.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(48).to({_off:false},0).to({regY:5,scaleX:1.98,scaleY:1.98,x:85.1,y:-74.9},4).to({regY:4.9,scaleX:1.5,scaleY:1.5,x:85,y:-75.1,alpha:0},32).to({_off:true},1).wait(15));

	// Layer 1 copy 3
	this.instance_6 = new lib.Symbol53();
	this.instance_6.parent = this;
	this.instance_6.setTransform(17.1,-75.1,1.496,1.496,0,0,0,5,4.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(34).to({_off:false},0).to({regY:5,scaleX:1.98,scaleY:1.98,y:-74.9},4).to({regY:4.9,scaleX:1.5,scaleY:1.5,y:-75.1,alpha:0},43).to({_off:true},1).wait(18));

	// Layer 1 copy 2
	this.instance_7 = new lib.Symbol53();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-23.2,-7,1.626,1.626,0,0,0,4.9,5);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).to({regX:5,scaleX:2.15,scaleY:2.15,x:-22.9,y:-6.9},4).to({regX:4.9,scaleX:1.63,scaleY:1.63,x:-23.2,y:-7,alpha:0},55).to({_off:true},1).wait(21));

	// Layer 1 copy
	this.instance_8 = new lib.Symbol53();
	this.instance_8.parent = this;
	this.instance_8.setTransform(17,17,1.687,1.687,0,0,0,5,5);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(11).to({_off:false},0).to({scaleX:2.23,scaleY:2.23,x:17.1,y:17.1},4).to({scaleX:1.69,scaleY:1.69,x:17,y:17,alpha:0},60).to({_off:true},1).wait(24));

	// Layer 1
	this.instance_9 = new lib.Symbol53();
	this.instance_9.parent = this;
	this.instance_9.setTransform(-3.2,65,1.748,1.748,0,0,0,4.9,5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(4).to({_off:false},0).to({regX:5,scaleX:2.31,scaleY:2.31,x:-2.9,y:65.1},4).to({regX:4.9,scaleX:1.75,scaleY:1.75,x:-3.2,y:65,alpha:0},64).to({_off:true},1).wait(27));

	// Layer 1
	this.instance_10 = new lib.Symbol7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(58,0.3,1,1,0,0,0,58,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({rotation:360},99).wait(1));

	// Layer 4
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(0,0,0,0.498)").s().p("AuSOTQl7l7AAoYQAAoXF7l7QF7l7IXAAQIYAAF7F7QF7F7AAIXQAAIYl7F7Ql7F7oYAAQoXAAl7l7g");
	this.shape_10.setTransform(58.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.3,-129.5,258.8,258.8);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(139,203.2,1,1,0,0,0,53,60.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 1
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(144,143.5,1,1,0,0,0,144,143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 4
	this.instance_2 = new lib.Symbol15();
	this.instance_2.parent = this;
	this.instance_2.setTransform(144.1,143.1,1,1,0,0,0,10,10);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-3,-4,302,300), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,600,300), null);


(lib.Symbol56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol48();
	this.instance.parent = this;
	this.instance.setTransform(78.8,40.5,1,1,0,0,0,29.8,52.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol56, new cjs.Rectangle(-19.5,-5,107.6,104.3), null);


(lib.Symbol45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol65();
	this.instance.parent = this;
	this.instance.setTransform(104.7,138.6,1,1,0,0,0,102.9,10.7);

	this.instance_1 = new lib.Symbol59();
	this.instance_1.parent = this;
	this.instance_1.setTransform(133.2,171.4,0.905,0.905,0,0,0,81.5,14.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Symbol 48
	this.instance_2 = new lib.Symbol56();
	this.instance_2.parent = this;
	this.instance_2.setTransform(32.8,178.4,0.463,0.463,0,0,0,54,52.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Symbol 46
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCA40").s().p("AgoC+QgUAAgWgPQgMgIgHgJQgHgIgDgKQgCgFAAgMQABgaASgTQAJgJALgFQALgEANAAQAQABAIALQAHAMgBAWIgCARIATgJQAQgJAKgOQAJgOACgUIABgXQggAHgngCQgLAAgYgIQg3gLgBhHIADhBQgDgDgTgHQgFAAgDgEIAAgFIADg3IAxAFIAHABIAHABIAJAAIAJABIAtAGQAGABAAAKIAAAWIgBAHIAAAHIABAlQgUABgIACIgBAMIACAoQADAjA/gWQAOgFAEgQIAGg2QAAgGgDAAIgNgGIgEgBIgCAAIgBABIABgxIA/gBIA+ADQAHAAABAUQgEADgDA5QgMAEgGgHQAFAigKBaQgMBEgyAqQgLALgRAMQgNAFgXAFQgXAFgNAAIgDgBg");
	this.shape.setTransform(183.2,85.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCA40").s().p("ABjCzIgVgHIAIgmQgygLgogFQgagDgcAIQgTgBgUADQgUAEgVAHQAFgCgVg6IAEAAIAagSIgDgYQgDgxgLhTIgGgMQgPACgCADIgHgHQgBgMgEgHIgFgaIgBgMIAngFIAqgGIA8gFIAQABIABAKQACAggFAQIgMAJIgTADIAEAvQgFgPAEAbIAIA/QACAZAEAIIAWgCQAQgDAsAJIABgcIABgUIADgjIACg6IAAgNIgRgPIAAgdIgBgZQAFgEAGABIA5gHQArgFAiACIgCAlIgBAVIAAAEIAAABQgEAFgSgBQgOgBgDAEIgOBtIgCAQIgGAuIBIASQgDAugLAiQAAAYgHAVQgNAAgygOgACsiBIABgBIgBACgACsiBg");
	this.shape_1.setTransform(148.2,89.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFCA40").s().p("ABjCzIgVgHIAIgmQgygLgogFQgagDgcAIQgTgBgUADQgUAEgVAHQAFgCgVg6IAEAAIAagSIgDgYQgDgxgLhTIgGgMQgPACgCADIgHgHQgBgMgEgHIgFgaIgBgMIAngFIAqgGIA8gFIAQABIABAKQACAggFAQIgMAJIgTADIAEAvQgFgPAEAbIAIA/QACAZAEAIIAWgCQAQgDAsAJIABgcIABgUIADgjIACg6IAAgNIgRgPIAAgdIgBgZQAFgEAGABIA5gHQArgFAiACIgCAlIgBAVIAAAEIAAABQgEAFgSgBQgOgBgDAEIgOBtIgCAQIgGAuIBIASQgDAugLAiQAAAYgHAVQgNAAgygOgACsiBIABgBIgBACgACsiBg");
	this.shape_2.setTransform(108.4,89.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCA40").s().p("Ah8CtIgcgCIgpgDIgEgvQAHgFAIAAIAZAAQAIABAAgDIAEg/IABg3IAAg9IgUgGQgMgEgGgFQgDgCAAgJIAAgLIgBgeIgCgPQgCgVAGgFIBFAFIBIAGQAKAvgCAYQAAAHgKAAIgHgCIgTgBIgBA9IgBA6QAYgTARgXIAagmIAYgnIAcgrIABgLIANgRIApAJQAoAKASAJQgLBDAAAVIAAA6IgCAYIgCAXIADAaQAJAEAgAAQAKAAAAAHIgBAJIgBAJQgCAYgEAOQgDANgGAEIhIAAIgwgCQgRgCgEgFIAEg/QATgFALAAIACABIACAAQADAAABgDIAAgCIAAACQgBADgIhGQAAgVgDgHQgRAegZA6IgjBSIgiACIgeAAIgJABIgJABIgIABIgHABg");
	this.shape_3.setTransform(68.3,83.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFCA40").s().p("AiDCaIghAAIAAgKIABgZIACgSIAFgGQACADANAAIAEgLQAAhfgCgtIgBgMQgDgEgJgBIAHgCIgggFIAAgPIALgzIACgEQA1AEAuAAQAugBAngEQBOgIAkACQAAgDAUBEIgEAAIggAJIAFAvIADARIADA5QABgJACAQIADAYQAEADAOAAQATgBADAFIAAAEIABAVIACAsQghACgeAAIhGABQgFAAgGgDIACgZQgCgOAFgBIARgPIAAgMIgGhJIgCghIgCgVIgBgdQgXAFgWABQgYABgYgDIgJACQgCAIABAXIAAA3IABAgIABApIARACQALAEAAADQAGANACAcIABAJIgOADIg4ADg");
	this.shape_4.setTransform(32.1,85.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCA40").s().p("Ah5CUIgHgEIgFg2QAAgIALgBIAHACIAIABIAOgBIgBgQIAAgVQACguAEghIAAgeIgLABIggAKIgEgnIgBgNQAAgNgFgOQAygIAPAAQAPAAA9gKQAJAXACAmQgXAKgBgCIAAgBIAAABIAAAkIgBARIAzAKIAiAMIAhAOIAUAPQAKAJADAMIADAJIACAKQAAAIgEARQgEAQgEAGQgIANgSAHIghAJQgkAKgtAAQhCAAgtgCgAgYAkIgCAMIAAAwIAvAAQANgBAKgIQAKgJAAgNQAAgLgEgEQgOgLgEgCQgTgHgPAAIgEgBIgDAAIgEgBIgEAAIgEAAIgDAIg");
	this.shape_5.setTransform(186,10.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFCA40").s().p("ACXCGIhWgNQgUgCgcgBIg/ACIh4AOIgLgCIgDgJIgHgTIgBgFIACgCIAIgDIARgFIgGg4IgCgOIgCgwQgBAHgCgNIgCgUQgCgDgLAAQgPABgDgEIAAgFIAAgYIAGgfQASgBAbAFIA8ABQADAAAFADIgBAUQgBAVgDABQgSAFAFAGIAAALIAHAwIAEAcIAAASIABAXQASgHARgCQARgDAAgCIAAgHQAEgnABg+IgEgJQgKAAgBACIgEgGIgBgPIgBgUIAAgJIAaAAIAgAAIArACIAJADIAAAGQgBAYgFAMQAAADgIADIgNABQAEAVgDAaIACAqQAAASACAIIAHABQAegCAkAIIAAgYIABgSIACgcQADgfgBgSIAAgMIgNgMIAAgYIgDgRQAFgEAEAAIAtgFQAYgFAmgBIgCAgIgBARIAAADIAAABQgDADgPAAQgKAAgDADIgKBbIgCANIgEAoIATAGQAFACACAEIgBAJIgMArIgHABIgGABIgHgBg");
	this.shape_6.setTransform(149.9,10.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFCA40").s().p("AhvCKQgNgEAAgFQAAgbACgGQABgGAVgGIALgDIgDgeIgEhTIgBgkQgBgFgQAAIgDABIgDABQgGgBgIgDIACgpIAUgGICkgOIAfgCIAVgCIAOABQADADAAAHIgBANIABAeIABATQAAAcgFAHIgpgBQgGgTgEgaQgBgIgJAAIgUAAIgDAAIgEABIgGAAQgNAAgeAGIAABDIADABIAcgGIADghIAHAAIAgAHIACADIACA8QAAAWgFAVIgZADQgFAAgCgRIgCgSIgCgBQgEAAgRALQAAAKAJASIAKAaIAzgKIAVgGIgBgZQABgVAIAAIANACIANADIAEAAIAEAAQAAAEADACIAEBYIgWACIjOAGQgHAAgLgCg");
	this.shape_7.setTransform(115.2,10);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFCA40").s().p("AgKCSIgLgEIABgHQgGgVAPgiQABgCAIgCIAggGQgCgOACgNIAAgFIguAAQgMAAgbgHQgrgQgHgqQgIgsADgRQgEgCgPgBIgKgDIgBgGIgBgpIB2gGQAIABAAAJQgEAXACARIgEAXIgOgDQgNAjARAaQALAEAQABQAOABAVgDQACg0ADgCQABgTgDgGQgcgDABgGIAEgRIADgXQAcgFAYACIAOACIANACIARACIAWAIQAEAAAGAoIgBAMIgaADQANABgNABQgGABgEADIgBAKQgEAygDBWIAEAJIAaAAIADAFIAAAcIABAUIgBAIQgRgCgWABIgfABIgJAAIgTABQgXAAgTgCg");
	this.shape_8.setTransform(88.3,11.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFCA40").s().p("AgDCYQgQAAgugRQgTgLgPgQQgPgQgKgVQgUgoAAgsQAAgcAFgXQAFgWAJgRQAMgWAdgLIAjgLQAPgEAMAAQANAAAqAKIAsAJQAqAPASBDQAIAeAAAaQAAASgJAdQgJAcgKAPQgMASgWAPQgMAIgLAFQgLAEgKABIgNADIgNACgAgihkIgFAHIgHAPQgFAfAAAmQAAAoALAXQAGAOASALQAQAMAPAAQAOAAAJgGQAKgFAHgLQAFgJADgLQADgMAAgOQAAgkgJgfQgFgQgVgUIgRgQQgOgHgQAAQgIAAgKADg");
	this.shape_9.setTransform(57.6,8.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFCA40").s().p("AADByQAAgMAEgEQADgDANgGIgtgvQgSAeAAANQAAAEAEAAIAHgBIAHAAQAKAAgBAIIgCAkQAAAFgFAAIg0gGQgVAAgkgEIgQgFQgBgEAGgbQADgNAEgCIAggDQADgBATgfQAWgkAAgDIgGgJIgHgJIgSgkIgKgXQgFgJgFgGQgFgEgHAAIgHAAIgHABQgFAAAAgHIABgOQAAgZAEgDQAFABAjABIAJgBIAIgBIAOABIAOABIAjACQAHACAAAEIACAfIgBAEIgBADIgNADIgIADQAAADATAUIAZAZQANgSASghQgFgCgYAAQgFAAAAgEQAAgKAKgdQACgFAEABIBqADQAIABABANIAAAUIgoAJQgJAKgLAYIgSAhIgKAQIAPAVIAQAVIAUAnIAJASQAMgDAMAAIACAAIAEAGIAAAUIAAAOIgBAJIgGABIgGABIhMABIgcADIgSADQgIAAAAgdg");
	this.shape_10.setTransform(28.4,9);

	this.instance_3 = new lib.Symbol46();
	this.instance_3.parent = this;
	this.instance_3.setTransform(105.3,46.4,1,1,0,0,0,56.7,8.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol45, new cjs.Rectangle(-1.2,-7.8,208.7,208), null);


(lib.Symbol40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol3();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol40, new cjs.Rectangle(0,0,600,300), null);


(lib.Symbol38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// СКАЧАТЬ copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhGBWIgEgCIgDgfQAAgGAGAAIAFABIAEABIAIgBIAAgJIAAgMQABgbACgTIAAgRIgGAAIgTAGIgCgXIgBgHQAAgIgDgIQAegFAIABQAJAAAjgHQAFANABAXQgNAGgBgBIAAgBIAAABIAAAVIAAAKIAeAGIAUAGIASAIIAMAJQAGAFACAIIABAEIACAGQAAAFgDAKQgCAJgCADQgFAIgLAEIgSAGQgWAGgZAAIhBgCgAgNAVIgCAHIABAcIAbAAQAHAAAFgGQAHgFAAgHQAAgHgDgCIgLgIQgKgDgJAAIgCgBIgCAAIgDAAIgCAAIgCgBIgBAFg");
	this.shape.setTransform(166.3,22.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAKBQIgcgCIgBgBIAAAAIAAAAIgBABIgCABIgGgBIgIAAIgDABIgCAAQgDAAgDgCIABgMQAAgGADgBIAXgGIAAgGIgBgpIgBgnIAAgKQAAgGgBgEIgXADIAAAPIABAJQABAIgCAEIgagBIgEAAIgCAAQgEAAAAgMIABgTIACgdIAEgCIAZAAIAmgBIAkgBIAYABIANAAIAOADIAEAdIAEASIAAANIgDABIgHgBIgNgBQgMgCgFgCQgDgagCAAIgSAEIACAWIAAAPIAAAaIABAMIAAALQACACAIAAQANAAAAAEIAAABIAAAKIAAAVg");
	this.shape_1.setTransform(149.4,21.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAKA4IAOgIQgEgQgDAAIgSABIgSADIgJAEIAAAMQATACAAAEIgCAIIAAAJQgCAFgCACQgXgDgJABQgZAAgQgFIAAgFIAEgLQADgIADgBIAQgCQACgBAHgZIAIggIAJgdQAGgVAEgSQACgGAEAAIAtADQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIAQAwIAKAjQAHAXAJAQIAQABQADABgBAHIAAAJIAAAMQgFACgMABIgUACIgkAHQgEgMgBgRgAAYAGQgDgLgIgPIgNgZQgFAdAAAQQAFACAYAEIAAAAg");
	this.shape_2.setTransform(132.6,22.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFBVIgGgCIAAgEQgEgNAJgTQABgCAFgBIASgDQgBgJABgHIAAgDIgbAAQgGAAgRgEQgYgJgFgZQgFgZADgKQgDgBgIgBIgHgCIAAgDIgBgYIBGgDQAEAAAAAFQgDAOACAKIgCANIgJgBQgHAUAJAPQAHACAKABQAHAAAMgCQACgdABgCQABgLgCgEQgQgBABgEIACgJIABgOQARgDAOABIAHACIAIABIAKABIANAEQACABAEAXIgBAHIgPACQAIAAgHABQgFAAgBACIgBAGQgDAdgBAyIACAFIAPAAIADADIAAAQIAAAMIAAAFQgLgCgNABIgSABIgFAAIgJAAIgagBg");
	this.shape_3.setTransform(116.2,22.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAKA4IAOgIQgEgQgDAAIgSABIgSADIgJAEIAAAMQATACAAAEIgCAIIgBAJQgBAFgCACQgXgDgJABQgZAAgPgFIAAgFIADgLQADgIADgBIAQgCQADgBAGgZIAIggIAJgdQAGgVAEgSQACgGADAAIAuADQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIAQAwIAKAjQAIAXAIAQIAQABQADABgCAHIABAJIAAAMQgFACgMABIgUACIgkAHQgEgMgBgRgAAYAGQgEgLgHgPIgNgZQgFAdAAAQQAFACAYAEIAAAAg");
	this.shape_4.setTransform(98,22.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAGBNIAAgIIgBgIIAAAAQAAgGAEgDIAKgFQgIgJgggZIgBABIAAANIgBAJIAAAIIACAAIAHgCIAHgBIAEACIAAAdQAAAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAABIgnABIgRABIgNAAQgLACgCgEQgCgDAAgMQAAgGAKgEQAMgDABgBIAAgWIgDg8IgXAAIgCgIIAAgDIABgJIAAgOIAngFQAGAAAPgDQAPgDAHAAQAGAAAEANIAEANIgZAJQAAAMAGAQQAbgVAhgQQgEAAgDgHIgEgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAgBIASgEIASALQAHAEAHAHQAKAJACAFIgGAHIgGAFIgHgEIgGgHIgrAjIAUATIAEAFQAFAIALAOQAHAAAHAEQABABABADIgBALIgBAMIgBAJQgEACgHAAIgMgBIgLgBIgNABIgJAAIgMAAIgBABIgCAAQgEAAAAgGg");
	this.shape_5.setTransform(79.8,21.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AglBTQgOgHgKgMQgTgXAAgmIAFgVQAThGA2AAIAEABIAFABQAHgBAKAGQAKAFANAKIABgIQAIgEATgBQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAIACAxIABAHIAAAFQAAACgMAFIgPAFIgMgXQgJgRgFgEQgEgCgGgBQgFgCgHAAQgFAAgFAFIgJAKQgEAHgEALIgFAUIgCALQAAAPAJALQAEAEAGADQAGACAHABIAEAAQAFAAALgHQAHgDAHgLQABgEADgEQAGgDANAAQADAAAAAIQAAALgCAIQgDAJgFAIQgLAQgTAGIgDACQgNAGgNAAQgSAAgOgGg");
	this.shape_6.setTransform(62,21.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// СКАЧАТЬ
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#996600").s().p("AhGBXIgEgDIgDgfQAAgFAGgBIAFABIAEABIAIgBIAAgJIAAgMQABgbACgTIAAgRIgGAAIgTAGIgCgXIgBgHQAAgIgDgIQAegFAIAAQAJABAjgHQAFANABAXQgNAGgBgBIAAgBIAAABIAAAUIAAALIAeAGIAUAHIASAHIAMAJQAGAGACAGIABAGIACAFQAAAFgDAKQgCAJgCADQgFAIgLAFIgSAFQgWAFgZABIhBgBgAgNAVIgCAGIABAdIAbAAQAHAAAFgFQAHgGAAgHQAAgHgDgCIgLgIQgKgEgJAAIgCAAIgCAAIgDAAIgCAAIgCgBIgBAFg");
	this.shape_7.setTransform(166.3,24.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#996600").s().p("AAKBQIgcgCIgBgBIAAAAIAAAAIgBABIgCABIgGgBIgIAAIgDABIgCAAQgDAAgDgCIABgMQAAgGADgBIAXgGIAAgGIgBgpIgBgnIAAgKQAAgGgBgEIgXADIAAAPIABAJQABAIgCAEIgagBIgEAAIgCAAQgEAAAAgMIABgTIACgdIAEgCIAZAAIAmgBIAkgBIAYABIANAAIAOADIAEAdIAEASIAAANIgDABIgHgBIgNgBQgMgCgFgCQgDgagCAAIgSAEIACAWIAAAPIAAAaIABAMIAAALQACACAIAAQANAAAAAEIAAABIAAAKIAAAVg");
	this.shape_8.setTransform(149.4,23.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#996600").s().p("AAKA4IAOgIQgEgQgDAAIgSABIgSADIgJAEIAAAMQATACAAAEIgCAIIAAAJQgCAFgCACQgXgDgJABQgZAAgQgFIAAgFIAEgLQADgIADgBIAQgCQACgBAHgZIAIggIAJgdQAGgVAEgSQACgGAEAAIAtADQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIAQAwIAKAjQAHAXAJAQIAQABQADABgBAHIAAAJIAAAMQgFACgMABIgUACIgkAHQgEgMgBgRgAAYAGQgDgLgIgPIgNgZQgFAdAAAQQAFACAYAEIAAAAg");
	this.shape_9.setTransform(132.6,25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#996600").s().p("AgFBVIgGgCIAAgEQgEgNAJgTQABgCAFgBIASgDQgBgJABgHIAAgDIgbAAQgGAAgRgEQgYgJgFgZQgFgZADgKQgDgBgIgBIgHgCIAAgDIgBgYIBGgDQAEAAAAAFQgDAOACAKIgCANIgJgBQgHAUAJAPQAHACAKABQAHAAAMgCQACgdABgCQABgLgCgEQgQgBABgEIACgJIABgOQARgDAOABIAHACIAIABIAKABIANAEQACABAEAXIgBAHIgPACQAIAAgHABQgFAAgBACIgBAGQgDAdgBAyIACAFIAPAAIADADIAAAQIAAAMIAAAFQgLgCgNABIgSABIgFAAIgJAAIgagBg");
	this.shape_10.setTransform(116.2,25.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#996600").s().p("AAKA4IAOgIQgEgQgDAAIgSABIgSADIgJAEIAAAMQATACAAAEIgCAIIgBAJQgBAFgCACQgXgDgJABQgZAAgPgFIAAgFIADgLQADgIADgBIAQgCQADgBAGgZIAIggIAJgdQAGgVAEgSQACgGADAAIAuADQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIAQAwIAKAjQAIAXAIAQIAQABQADABgCAHIABAJIAAAMQgFACgMABIgUACIgkAHQgEgMgBgRgAAYAGQgEgLgHgPIgNgZQgFAdAAAQQAFACAYAEIAAAAg");
	this.shape_11.setTransform(98,25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#996600").s().p("AAGBNIAAgIIgBgIIAAAAQAAgGAEgDIAKgFQgIgJgggZIgBABIAAANIgBAJIAAAIIACAAIAHgBIAHgCIAEADIAAAcQAAAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAIgnACIgRABIgNAAQgLABgCgDQgCgDAAgMQAAgGAKgEQAMgDABgBIAAgWIgDg8IgXAAIgCgIIAAgDIABgJIAAgOIAngFQAGABAPgEQAPgDAHAAQAGAAAEAMIAEAPIgZAJQAAALAGARQAbgXAhgPQgEAAgDgHIgEgHQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIASgFIASALQAHAEAHAHQAKAJACAEIgGAIIgGAGIgHgFIgGgHIgrAjIAUATIAEAFQAFAIALAOQAHABAHADQABABABADIgBAMIgBALIgBAJQgEACgHAAIgMgBIgLgBIgNABIgJAAIgMAAIgBABIgCAAQgEAAAAgGg");
	this.shape_12.setTransform(79.8,23.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#996600").s().p("AglBSQgOgGgKgMQgTgXAAgmIAFgVQAThGA2AAIAEAAIAFABQAHAAAKAGQAKAFANALIABgJQAIgEATgBQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAIACAxIABAHIAAAFQAAACgMAFIgPAFIgMgXQgJgQgFgEQgEgDgGgCQgFgBgHAAQgFAAgFAGIgJAJQgEAHgEALIgFAUIgCALQAAAPAJAKQAEAFAGADQAGADAHgBIAEAAQAFABALgHQAHgDAHgLQABgEADgEQAGgDANAAQADAAAAAJQAAAJgCAKQgDAIgFAIQgLAQgTAGIgDACQgNAGgNAAQgSAAgOgHg");
	this.shape_13.setTransform(62,24.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7}]}).wait(1));

	// Symbol 35
	this.instance = new lib.Symbol35();
	this.instance.parent = this;
	this.instance.setTransform(111.5,22.2,1,1,0,0,0,111.5,22.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol38, new cjs.Rectangle(-1,-9,225.2,54.5), null);


(lib.Symbol61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Symbol62();
	this.instance.parent = this;
	this.instance.setTransform(115.2,-57.3,1,1,0,0,0,136.2,12);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(102).to({_off:false},0).to({y:12.7},5).wait(98).to({y:-57.3},5).to({_off:true},1).wait(3));

	// Layer 1
	this.instance_1 = new lib.Symbol45();
	this.instance_1.parent = this;
	this.instance_1.setTransform(116.3,88.5,1,1,0,0,0,103.2,89.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({x:416.3},5).to({_off:true},1).wait(103).to({_off:false},0).to({x:116.3},5).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(11.8,-9,208.8,208);


(lib.Symbol60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol38();
	this.instance.parent = this;
	this.instance.setTransform(111.5,18.2,1,1,0,0,0,111.5,18.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({y:17},0).wait(1).to({y:19.4},0).wait(1).to({y:17},0).wait(1).to({y:19.4},0).wait(1).to({y:17},0).wait(1).to({y:19.4},0).wait(1).to({y:17},0).wait(1).to({y:19.4},0).wait(1).to({y:18.2},0).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-9,225.2,54.5);


(lib.Symbol44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol60();
	this.instance.parent = this;
	this.instance.setTransform(111.5,18.2,1,1,0,0,0,111.5,18.2);

	this.instance_1 = new lib.Symbol38();
	this.instance_1.parent = this;
	this.instance_1.setTransform(111.6,18.2,1.067,1.067,0,0,0,111.5,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-9,225.2,54.5);


(lib.Symbol41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol40();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol41, new cjs.Rectangle(0,0,600,300), null);


(lib.Symbol39copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol41();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);
	this.instance.alpha = 0.148;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol39copy, new cjs.Rectangle(0,0,600,300), null);


(lib.Symbol39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol41();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);
	this.instance.alpha = 0.059;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.18},9).to({alpha:0.059},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
		
		 this.pizza.x = - stage.mouseX / 15;
		 this.pizza.y = - stage.mouseY / 15;
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer 1
	this.instance = new lib.Symbol39();
	this.instance.parent = this;
	this.instance.setTransform(300,150,1,1,0,0,0,300,150);

	this.pizza = new lib.Symbol39copy();
	this.pizza.parent = this;
	this.pizza.setTransform(-5.7,-0.1,1,1,0,0,0,-5.7,-0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.pizza}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


// stage content:
(lib.index4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		/* Custom Mouse Cursor
		Replaces the default mouse cursor with the specified symbol instance.
		*/
		stage.canvas.style.cursor = "none";
		this.kurs.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.kurs.x = stage.mouseX/window.devicePixelRatio;
			this.kurs.y = stage.mouseY/window.devicePixelRatio;
		}
		//To restore the default mouse pointer, uncomment the following lines:
		//this.removeEventListener("tick", fl_CustomMouseCursor.bind(this));
		//stage.removeChild(kurs);
		//stage.canvas.style.cursor = "default";
		
		
		var _this = this;
		
		_this.kurs.visible=false;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		function fl_MouseOverHandler_5()
		    {
			    _this.pica.gotoAndPlay(0);
				_this.kurs.visible=true;
		
		    }
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		
		      function fl_MouseOutHandler_2()
		    {
			    _this.pica.gotoAndPlay(1);
				_this.kurs.visible=false;
		
		    }
		
			
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer 6
	this.kurs = new lib.Symbol50();
	this.kurs.parent = this;
	this.kurs.setTransform(-120.4,144.6,0.564,0.564,0,0,0,46.5,57.6);

	this.timeline.addTween(cjs.Tween.get(this.kurs).wait(1));

	// Layer 5
	this.instance = new lib.Symbol61();
	this.instance.parent = this;
	this.instance.setTransform(439.8,116.5,1,1,0,0,0,110.2,89);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 4
	this.instance_1 = new lib.Symbol44();
	this.instance_1.parent = this;
	this.instance_1.setTransform(447.7,248.9,1,1,0,0,0,111.5,18.2);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 3
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(156,150.5,1,1,0,0,0,144,143.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// back
	this.pica = new lib.Symbol2();
	this.pica.parent = this;
	this.pica.setTransform(306,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.pica).wait(1));

	// Layer 2
	this.instance_3 = new lib.Symbol42();
	this.instance_3.parent = this;
	this.instance_3.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(177.3,145,745.1,311.2);
// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#000000",
	opacity: 1.00,
	manifest: [
		{src:"images/icon2.png?1486046892140", id:"icon2"},
		{src:"images/mouse.png?1486046892140", id:"mouse"},
		{src:"images/pizza1.png?1486046892140", id:"pizza1"},
		{src:"images/pizzatext.png?1486046892140", id:"pizzatext"},
		{src:"images/radar.png?1486046892140", id:"radar"},
		{src:"images/radarback.png?1486046892140", id:"radarback"},
		{src:"images/setka.png?1486046892140", id:"setka"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;