(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 320,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	manifest: [
		{src:"images/avatar.png?1477553153095", id:"avatar"},
		{src:"images/dol.png?1477553153095", id:"dol"},
		{src:"images/envelope.png?1477553153095", id:"envelope"},
		{src:"images/logo.png?1477553153095", id:"logo"},
		{src:"images/mob.png?1477553153095", id:"mob"},
		{src:"images/padlock.png?1477553153095", id:"padlock"},
		{src:"images/reg.png?1477553153095", id:"reg"},
		{src:"images/ten.png?1477553153095", id:"ten"}
	]
};



// symbols:



(lib.avatar = function() {
	this.initialize(img.avatar);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,25,29);


(lib.dol = function() {
	this.initialize(img.dol);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,562,248);


(lib.envelope = function() {
	this.initialize(img.envelope);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,29,22);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,193,57);


(lib.mob = function() {
	this.initialize(img.mob);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,548);


(lib.padlock = function() {
	this.initialize(img.padlock);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,21,29);


(lib.reg = function() {
	this.initialize(img.reg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,426,90);


(lib.ten = function() {
	this.initialize(img.ten);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,520,110);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AznK+IAA17MA0HAAAIAAV7g");
	mask.setTransform(208,59.2);

	// Слой 1
	this.instance = new lib.ten();
	this.instance.setTransform(-10.8,0);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(82.4,0,333.7,110);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ten();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,520,110);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dol();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,562,248);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-174.55,-30,349.1,60,19.9);
	this.shape.setTransform(64.1,31.6,0.963,1.054);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104,0,336.1,63.3);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-174.55,-30,349.1,60,19.9);
	this.shape.setTransform(64.1,31.6,0.963,1.054);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104,0,336.1,63.3);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-174.55,-30,349.1,60,19.9);
	this.shape.setTransform(168.1,31.6,0.963,1.054);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336.1,63.3);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("Ai+ChIACgLIACAAIACAAQAFAAACgDQADgEABgFIADgIIgZhPIAQAAIAPA6IAQg6IAQAAIgcBcQgDAIgFAFQgEAHgJAAgAK1B+QgGgGAAgLQAAgLAIgHQAIgGAOgBIAMAAIAAgIQAAgHgDgEQgDgEgGAAQgGAAgDAEQgDADAAAGIgOAAIAAgBQgBgJAIgHQAHgHANAAQAMAAAHAGQAHAIAAAMIABAuIACAIIgQAAIgCgLQgDAFgFAEQgFAEgHAAQgKAAgGgGgALCBiQgEAEAAAHQAAAFADAEQACACAFAAQAGAAAFgDQAFgEABgFIAAgPIgMAAQgHABgEAEgAIoB+QgJgHAAgLIABAAIAOAAQAAAFAEAEQAEAEAHAAQAGAAAEgDQAEgFAAgFQAAgGgEgDQgDgEgHAAIgMAAIAAgKIAMAAQAGAAAEgDQADgDAAgGQAAgFgDgDQgEgEgHAAQgFAAgEAEQgEADAAAGIgOAAIAAgBQgBgKAIgHQAIgGAMAAQANAAAIAGQAIAGAAALQAAAFgDAFQgEAEgFADQAGACAEAFQADAEAAAIQAAALgIAGQgJAGgNAAQgMAAgIgGgAHjB5QgJgLAAgRIAAgDQAAgSAJgLQAIgLAOAAQANAAAHAJQAHAKAAAQIAAAIIgrAAQAAAMAFAIQAEAIAJAAQAGAAAFgCQAEgCAEgEIAFAJQgEAFgGACQgHADgIAAQgPAAgIgLgAHuBDQgDAGgBAKIAcAAIAAgBQAAgKgEgFQgDgGgGAAQgHAAgEAGgAFRB5QgJgLAAgSIAAgCQAAgRAJgMQAIgLAPAAQAOAAAJALQAIAMAAARIAAACQAAASgIALQgJALgOAAQgPAAgIgLgAFbBFQgEAIAAANIAAACQAAANAEAHQAEAJAJAAQAIAAAEgJQAEgHAAgNIAAgCQAAgNgEgIQgEgIgIAAQgJAAgEAIgAhUB5QgIgLAAgSIAAgDIAAgBIAAgSQAAgXAIgKQAIgKAPgBQAJgBAEgCQAFgCAAgEIALAAIAAAAQABAMgHAEQgHAEgOABQgKAAgGAGQgFAFAAALIAAAAQAEgEAFgDQAGgDAGAAQAOAAAIALQAHAMAAARIAAACQAAASgIALQgIALgPAAQgOAAgJgLgAhJBFQgEAIAAANIAAACQAAANAEAHQAEAJAIAAQAIAAAEgJQAFgHAAgNIAAgCQAAgNgFgIQgEgIgIAAQgIAAgEAIgAk2B5QgJgLAAgSIAAgCQAAgRAJgMQAIgLAPAAQAOAAAJALQAIAMAAARIAAACQAAASgIALQgJALgOAAQgPAAgIgLgAksBFQgEAIAAANIAAACQAAANAEAHQAEAJAJAAQAIAAAEgJQAEgHAAgNIAAgCQAAgNgEgIQgEgIgIAAQgJAAgEAIgArIB5QgIgLAAgRIAAgDQAAgSAIgLQAJgLANAAQAOAAAHAJQAHAKAAAQIAAAIIgrAAQAAAMAEAIQAEAIAJAAQAHAAAEgCQAFgCAEgEIAFAJQgEAFgHACQgGADgJAAQgOAAgJgLgAq8BDQgEAGgBAKIAcAAIAAgBQAAgKgDgFQgDgGgHAAQgGAAgEAGgAMGCCIAAgOIAPAAIAAAOgAKTCCIAAgiIgbAAIAAAiIgPAAIAAhPIAPAAIAAAiIAbAAIAAgiIAPAAIAABPgAG/CCIAAhDIgVAAIAAAWQAAAYgFAKQgGAMgOgBIgDAAIAAgLIACAAQAHAAACgIQADgGAAgUIAAgiIAyAAIAABPgAEsCCIAAhDIgbAAIAABDIgPAAIAAhPIA5AAIAABPgACbCCIAAhPIAPAAIAAAeIAPAAQANAAAHAGQAHAIAAAKQAAAMgHAGQgHAIgNgBgACqB3IAPAAQAGAAADgDQADgFAAgGQAAgFgDgEQgDgEgGAAIgPAAgABoCCIAAhDIgWAAIAAgMIA7AAIAAAMIgWAAIAABDgAA+CCIAAhPIAOAAIAABPgAgOCCIAAhPIAOAAIAAAeIAOAAQANAAAHAGQAHAIAAAKQAAAMgHAGQgHAIgNgBgAAAB3IAOAAQAGAAADgDQADgFAAgGQAAgFgDgEQgDgEgGAAIgOAAgAjyCCIAAhPIAtAAIAAAMIgeAAIAABDgAldCCIAAg0IAAAAIgTA0IgKAAIgTg0IAAAAIAAA0IgPAAIAAhPIASAAIAVA9IAAAAIAUg9IATAAIAABPgAneCCIAAgdIgOAAIgQAdIgPAAIARggQgHgDgEgFQgDgHAAgHQAAgLAHgHQAIgHAMAAIAdAAIAABPgAn2BCQgDAEAAAGQAAAFADAEQADAFAFAAIAQAAIAAgbIgPAAQgGAAgDADgApJCCIAAg0IAAAAIgTA0IgKAAIgTg0IAAAAIAAA0IgPAAIAAhPIASAAIAVA9IAAAAIAUg9IATAAIAABPgAruCCIAAgtQgFACgGABIgLABQgQAAgJgIQgIgIAAgRIAAggIAPAAIAAAgQAAAMAEAFQAFAFAJAAIALgBIALgDIAAgyIAPAAIAABqgAMGBlQAAgKACgFQACgDAHgIQAGgGACgFQADgGAAgHQAAgIgDgFQgEgEgGAAQgFAAgEAEQgEAFAAAGIgOAAQAAgMAHgIQAIgHAMAAQANAAAIAIQAHAHAAAOQAAAKgEAHQgFAIgHAIQgEAEgBADIgBAKgAjWgTIACgLIACAAIACAAQAEABADgEQADgEABgFIADgIIgZhPIAQAAIAPA6IAQg6IAQAAIgcBcQgDAIgFAGQgFAFgJABgAp+gTIAAhuIAMAAIACAKQADgFAFgEQAEgCAHAAQAMAAAHALQAHAMAAATIAAACQAAARgHALQgHAKgMAAQgGAAgFgCQgEgDgDgEIAAAmgApqh0QgDADgCAEIAAApQACAEADADQAEACAFAAQAIAAADgIQAEgHAAgMIAAgCQAAgOgEgIQgDgJgIAAQgFAAgEADgAqagXIAAgbIgtAAIAAAbIgPAAIAAgmIAHAAQAEAAADgJQACgJABgTIABgfIAwAAIAABEIAIAAIAAAmgAq2hiIgDAWQgBAJgDAGIAaAAIAAg3IgSAAgAAAg7QgIgKAAgSIAAgEQAAgRAIgLQAHgLANAAQAOAAAHAJQAHAKAAAQIAAAJIgrAAQAAAMAEAHQAEAIAJAAQAHAAAEgCQAFgCAEgEIAFAJQgEAEgHAEQgGACgJAAQgOAAgHgLgAAKhxQgEAGgBAKIAcAAIAAgBQAAgJgDgGQgDgGgHAAQgGAAgEAGgAmgg7QgIgLAAgRIAAgEQAAgQAIgMQAIgLAPAAQAMAAAHAIQAIAIgBAMIAAABIgNAAQAAgIgEgFQgDgFgGAAQgIAAgEAIQgEAJAAALIAAAEQAAAMAEAIQADAIAJAAQAFAAAEgFQAEgEAAgHIANAAIAAAAQABAMgIAHQgIAIgLAAQgPAAgIgLgAoyg3QgGgGAAgKQAAgLAIgHQAIgGAOAAIAMAAIAAgJQAAgHgDgEQgDgEgGAAQgGAAgDAEQgDADAAAGIgOAAIAAgBQgBgJAIgHQAHgHANAAQAMAAAHAHQAHAGAAANIABAuIACAIIgQAAIgCgLQgDAFgFAEQgFAEgHAAQgKAAgGgHgAolhSQgEAEAAAHQAAAFADAEQACADAFAAQAGgBAFgDQAFgEABgGIAAgNIgMAAQgHAAgEAEgAsgg4QgKgIAAgOIAAgBIAPAAQAAAIAFAGQAGAGAJAAQAKAAAGgGQAGgFAAgJQAAgKgGgFQgFgEgKAAIgMAAIAAgMIAMAAQAKABAFgFQAEgFAAgJQAAgIgFgFQgFgFgKgBQgIABgGAFQgFAFAAAIIgOAAIgBgBQAAgNAKgHQAKgJAOAAQAQABAKAHQAJAIAAAOQAAAIgEAHQgFAFgHAEQAIADAFAGQAFAHAAAJQAAAOgKAJQgLAIgQAAQgPAAgKgIgAA+gyIAAgPIAPAAIAAAPgAg3gyIAAhEIgWAAIAAgLIA7AAIAAALIgWAAIAABEgAhogyIAAg2IgBAAIgaA2IgPAAIAAhPIAPAAIAAA2IAbg2IAPAAIAABPgAkdgyIAAhPIAbAAQAOAAAHAGQAIAFAAALQAAAGgDAEQgEAFgGACQAIACAEAEQAEAGAAAGQAAALgHAGQgHAFgNAAgAkOg8IARAAQAGAAADgEQADgCAAgHQAAgFgDgDQgDgDgGgBIgRAAgAkOhfIANAAQAHAAADgCQADgEAAgFQAAgGgEgCQgDgDgHgBIgMAAgAlQgyIAAhEIgWAAIAAgLIA8AAIAAALIgXAAIAABEgAnugyIAAhPIAcAAQANAAAIAGQAHAFAAALQAAAGgDAEQgDAFgGACQAHACAEAEQAEAGAAAGQAAALgHAGQgHAFgNAAgAnfg8IARAAQAGAAADgEQADgCAAgHQAAgFgDgDQgDgDgGgBIgRAAgAnfhfIAOAAQAGAAADgCQADgEAAgFQAAgGgDgCQgDgDgHgBIgNAAgAA+hVIAAhHIAPAAIAABHgAiFiTQgGgGAAgIIABAAIALAAQAAAEACADQACAEAFAAQAFAAACgEQACgDAAgEIAMAAIAAAAQAAAIgFAGQgGAFgKABQgKgBgFgFg");
	this.shape.setTransform(85,8.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(3.9,-7.6,162.3,32.6);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AkqChIAAhuIANAAIABAKQAEgGAFgDQAEgCAGAAQANAAAHALQAHAMAAATIAAACQAAARgHALQgHAKgNAAQgFAAgFgCQgFgCgDgFIAAAmgAkVBAQgEADgCAEIAAApQACAEAEACQADADAGAAQAHAAAEgHQAEgIAAgMIAAgCQAAgOgEgIQgEgJgHAAQgGABgDACgAq+ChIAAhuIANAAIABAKQAEgGAEgDQAFgCAGAAQANAAAGALQAIAMgBATIAAACQABARgIALQgGAKgNAAQgGAAgFgCQgEgCgDgFIAAAmgAqpBAQgEADgCAEIAAApQACAEAEACQADADAFAAQAIAAADgHQAEgIAAgMIAAgCQAAgOgEgIQgDgJgIAAQgFABgDACgAggCdIAAgaIgzAAIAAhQIAPAAIAABEIAbAAIAAhEIAPAAIAABEIAJAAIAAAmgABuB6QgJgJAAgRIgSAAIAAAjIgQAAIAAhQIAQAAIAAAiIASAAQABgQAIgJQAJgKANAAQAPAAAIALQAIALAAASIAAACQAAARgIAMQgIALgPAAQgNAAgJgKgAB3BFQgDAJAAAMIAAACQAAAMADAJQAEAIAJAAQAIAAAFgIQADgJAAgMIAAgCQABgMgFgJQgEgIgIAAQgJAAgEAIgAiXB9QgFgFgBgMQAAgKAIgHQAIgHAOABIANAAIAAgIQgBgIgDgEQgDgEgGAAQgGAAgDADQgDAEAAAFIgOAAIAAAAQgBgJAIgHQAHgHANAAQAMAAAHAHQAIAGgBAOIABAtIACAJIgQAAIgBgNQgDAHgFADQgGAEgGAAQgLAAgGgHgAiKBiQgDAFAAAFQgBAGADADQADAEAFAAQAFAAAFgEQAFgEACgGIAAgNIgNAAQgHgBgEAFgAjdB9QgGgFAAgMQAAgKAIgHQAHgHAPABIAMAAIAAgIQAAgIgDgEQgEgEgFAAQgGAAgDADQgDAEgBAFIgNAAIAAAAQgBgJAHgHQAIgHANAAQALAAAIAHQAHAGAAAOIABAtIACAJIgQAAIgCgNQgDAHgFADQgFAEgHAAQgLAAgFgHgAjQBiQgEAFAAAFQAAAGACADQADAEAFAAQAGAAAFgEQAEgEACgGIAAgNIgMAAQgIgBgDAFgAmrB5QgJgMAAgQIAAgEQAAgRAJgLQAIgLAOAAQAMAAAIAIQAHAIgBAMIAAABIgNAAQAAgIgDgFQgEgFgGAAQgIAAgEAIQgEAJABALIAAAEQgBAMAEAIQADAIAJAAQAFAAAFgFQADgDAAgIIANAAIAAABQABALgIAHQgIAIgLAAQgOAAgIgLgApvB5QgJgLAAgRIAAgEQAAgRAJgLQAIgLAOAAQANAAAHAKQAIAJAAAQIAAAJIgsAAQABAMAEAHQAEAIAJAAQAGAAAFgCQAFgCADgEIAGAKQgFADgGAEQgGACgJAAQgPAAgIgLgApjBDQgEAGgBAKIAcAAIAAgCQAAgIgDgGQgDgGgHAAQgGAAgEAGgAsjB9QgFgFAAgMQAAgKAIgHQAHgHAPABIAMAAIAAgIQAAgIgEgEQgDgEgGAAQgFAAgDADQgEAEABAFIgPAAIAAAAQAAgJAIgHQAHgHAMAAQANAAAGAHQAIAGAAAOIAAAtIACAJIgPAAIgCgNQgDAHgFADQgFAEgHAAQgKAAgHgHgAsVBiQgEAFAAAFQAAAGADADQACAEAFAAQAGAAAFgEQAFgEABgGIAAgNIgNAAQgGgBgEAFgAtmB9QgIgFAAgMIAAgBIAOAAQAAAGAEAEQAEAEAHAAQAGAAAEgEQAFgEAAgFQAAgHgFgDQgDgCgHAAIgMAAIAAgLIAMAAQAHAAADgEQADgDAAgFQAAgFgDgEQgDgDgIAAQgFAAgEADQgEAEAAAFIgOAAIAAAAQgBgLAJgFQAHgHAMAAQAOAAAHAGQAIAGAAAKQAAAGgDAEQgDAFgGADQAGACAEAFQADAFAAAGQABAMgJAFQgJAHgNAAQgMAAgIgHgAC5CDIAAgPIAPAAIAAAPgAAjCDIAAg2IAAAAIgbA2IgNAAIAAhQIANAAIAAA3IAbg3IAPAAIAABQgAlbCDIAAhFIgXAAIAAgLIA8AAIAAALIgWAAIAABFgAnQCDIAAg2IAAAAIgbA2IgPAAIAAhQIAPAAIAAA3IAbg3IAPAAIAABQgAoxCDIAAhQIAtAAIAAAMIgdAAIAABEgAC5BkQAAgJADgEQABgEAIgHQAFgHACgGQAEgEAAgIQgBgIgDgEQgDgFgHAAQgFAAgEAFQgDADAAAIIgPAAQAAgOAHgGQAIgIAMABQAOAAAHAHQAIAIgBANQABAJgFAJQgEAHgIAIQgDADgCADIgBAKgAgngGIACgLIADAAIACAAQAEABADgEQACgEABgFIADgIIgYhPIAPAAIAPA6IAPg6IAQAAIgaBcQgEAIgEAGQgFAFgJABgAqBgGIACgLIACAAIACAAQAFABACgEQADgEABgFIADgIIgZhPIAQAAIAPA6IAQg6IAQAAIgcBcQgDAIgFAGQgEAFgKABgANNgVIAAgPQgFAAgGgCIgIgHQgHgHAAgPIAAgBIAOAAQAAAMAFAEQAFAGAGAAQAIAAAEgGQADgEABgIQgBgGgDgFQgDgEgJgEQgNgGgHgHQgHgHAAgNQAAgMAHgIQAGgHALgCIAAgPIAKAAIAAAPQALACAGAJQAGAIAAAOIgOAAQAAgKgFgFQgDgGgHAAQgGAAgEAFQgDAFAAAHQAAAHADAEQAEAFAJAEQAOAFAGAIQAHAGgBANQABAMgHAIQgHAHgLABIAAAPgALuguQgJgKAAgSIAAgfQAAgTAJgKQAJgLAOAAQAOAAAIALQAJAKAAATIAAAfQAAASgJAKQgIALgOAAQgOAAgJgLgAL4h/QgDAIAAALIAAAjQAAANADAGQAFAIAIAAQAHAAAFgHQAEgHAAgNIAAgjQAAgLgEgIQgEgHgIAAQgIAAgFAHgAHrguQgIgLAAgSIAAgCQAAgRAIgMQAJgLAPAAQAOAAAIALQAIAMAAARIAAACQAAASgIALQgIALgOAAQgPAAgJgLgAH2hiQgEAJAAAMIAAACQAAAMAEAIQAEAJAJAAQAHAAAEgJQAFgIAAgMIAAgCQAAgMgFgJQgEgIgHAAQgJAAgEAIgAFeguQgIgLAAgRIAAgEQAAgQAIgMQAIgLAOAAQAMAAAIAIQAHAIAAAMIAAABIgNAAQAAgIgEgFQgEgFgGAAQgHAAgEAIQgEAJAAALIAAAEQAAAMAEAIQADAIAIAAQAGAAAEgFQAEgEAAgHIANAAIAAAAQABAMgJAHQgHAIgMAAQgOAAgIgLgAixguQgIgLAAgSIAAgCQAAgRAIgMQAJgLAOAAQAPAAAIALQAIAMAAARIAAACQAAASgIALQgIALgPAAQgOAAgJgLgAinhiQgDAJAAAMIAAACQAAAMADAIQAEAJAJAAQAIAAAEgJQAEgIAAgMIAAgCQAAgMgEgJQgEgIgIAAQgJAAgEAIgAr5guQgJgLAAgSIAAgCQAAgRAJgMQAIgLAOAAQAPAAAIALQAJAMAAARIAAACQAAASgJALQgIALgPAAQgOAAgIgLgArvhiQgEAJAAAMIAAACQAAAMAEAIQAEAJAIAAQAIAAAFgJQADgIAAgMIAAgCQAAgMgDgJQgFgIgIAAQgIAAgEAIgAK0glIAAhdIgWABIAAgMIAkgEIAABsgAJaglIAAg2IgBAAIgaA2IgPAAIAAhPIAPAAIAAA2IAbg2IAOAAIAABPgAGdglIAAhPIAcAAQANAAAIAGQAHAFAAALQAAAGgDAEQgDAFgHACQAIACAEAEQAEAGAAAGQAAALgHAGQgHAFgNAAgAGsgvIARAAQAGAAADgEQADgCAAgHQAAgFgDgDQgDgDgGgBIgRAAgAGshSIAOAAQAGAAADgCQADgEAAgFQAAgGgDgCQgDgDgHgBIgNAAgADyglIAAhPIAPAAIAAAdIAPAAQANABAHAGQAHAHAAALQAAAMgHAGQgHAIgNgBgAEBgwIAPAAQAHAAACgEQADgDAAgHQAAgFgDgEQgCgEgHAAIgPAAgAC/glIAAhEIgWAAIAAgLIA7AAIAAALIgWAAIAABEgACOglIAAg2IgBAAIgaA2IgPAAIAAhPIAPAAIAAA2IAbg2IAPAAIAABPgABEglIAAgcIgGABIgGAAQgOABgHgIQgIgHAAgPIAAgXIAPAAIAAAXQAAAKADAEQADAEAIABIAGgBIAGgCIAAgnIAQAAIAABPgAhDglIAAhDIgUAAIAAAXQgBAXgFALQgGALgOgBIgCAAIAAgLIACAAQAGgBADgGQACgIAAgSIAAgjIAyAAIAABPgAjWglIAAhDIgbAAIAABDIgPAAIAAhPIA5AAIAABPgAlBglIAAgdIgOAAIgPAdIgPAAIAQggQgHgDgDgGQgEgFAAgIQAAgLAHgHQAIgGAMgBIAdAAIAABPgAlZhkQgDADAAAGQAAAGADAEQADADAFAAIAQAAIAAgbIgPAAQgFABgEAEgAmqglIAAg2IgBAAIgaA2IgPAAIAAhPIAPAAIAAA2IAbg2IAPAAIAABPgAnzglIAAhDIgUAAIAAAXQAAAXgGALQgFALgOgBIgDAAIAAgLIACAAQAHgBACgGQADgIgBgSIAAgjIAzAAIAABPgAq2glIAAhPIAtAAIAAAMIgeAAIAABDgAsfglIAAhNIgBAAIgYBNIgKAAIgahOIAAAAIAABOIgPAAIAAhqIATAAIAaBXIAAAAIAahXIATAAIAABqg");
	this.shape.setTransform(92.9,9.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.9,-6.5,176,32.3);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AloChIACgLIACABIACAAQAEgBADgDQADgEABgFIADgIIgZhOIAQAAIAPA4IAQg4IAQAAIgcBbQgDAIgFAFQgFAHgJgBgAGBChIAAhtIAMAAIACAJQADgFAFgDQAEgDAHAAQAMAAAHAMQAHALAAATIAAABQAAASgHALQgHAKgMAAQgGAAgFgCQgEgCgDgFIAAAmgAGVBAQgDADgCAEIAAAoQACAFADACQAEADAFAAQAIAAADgHQAEgIAAgNIAAgBQAAgNgEgJQgDgIgIAAQgFgBgEADgAgSChIAAhtIANAAIABAJQAEgFACgDQAFgDAGAAQANAAAHAMQAHALAAATIAAABQAAASgHALQgHAKgNAAQgGAAgEgCQgDgCgDgFIAAAmgAABBAQgCADgCAEIAAAoQACAFACACQADADAFAAQAIAAAEgHQAEgIAAgNIAAgBQAAgNgEgJQgEgIgIAAQgFgBgDADgAJECcIAAgZIgzAAIAAhPIAPAAIAABDIAbAAIAAhDIAPAAIAABDIAIAAIAAAlgALUB6QgJgKAAgQIgTAAIAAAjIgPAAIAAhPIAPAAIAAAhIATAAQABgQAIgJQAIgKAOAAQAOAAAJALQAIALAAASIAAACQAAARgIAMQgJALgOAAQgOAAgIgKgALdBGQgEAHAAANIAAACQAAANAEAIQAEAIAJAAQAIAAAEgIQAEgIAAgNIAAgCQAAgNgEgHQgEgJgIAAQgJAAgEAJgAHNB9QgGgFAAgMQAAgLAIgGQAIgHAOAAIAMAAIAAgHQAAgIgDgEQgDgEgGAAQgGAAgDADQgDAEAAAFIgOAAIAAAAQgBgJAIgHQAHgHANAAQAMAAAHAGQAHAIAAANIABAtIACAJIgQAAIgCgNQgDAHgFADQgFAEgHAAQgKAAgGgHgAHaBiQgEAFAAAFQAAAGADADQACADAFAAQAGAAAFgDQAFgEABgGIAAgOIgMAAQgHAAgEAFgAD/B5QgIgLAAgSIAAgCQAAgRAIgMQAIgLAOAAQAMAAAIAIQAHAIAAANIAAAAIgOAAQAAgIgDgFQgEgFgGAAQgIAAgEAJQgDAHAAANIAAACQAAANADAIQAEAIAIAAQAGAAAEgFQADgDAAgIIAOAAIAAABQAAALgIAIQgIAHgLAAQgOAAgIgLgAA7B5QgIgLAAgRIAAgDQAAgSAIgLQAJgLANAAQAOAAAHAKQAHAJAAAQIAAAIIgrAAQAAANAEAHQAEAIAJAAQAHAAAEgCQAFgCAEgEIAFAKQgEADgHADQgGADgJAAQgOAAgJgLgABHBDQgEAGgBAKIAcAAIAAgCQAAgJgDgFQgDgGgHAAQgGAAgEAGgAh2B9QgGgFAAgMQAAgLAIgGQAIgHAOAAIAMAAIAAgHQAAgIgDgEQgDgEgGAAQgGAAgDADQgDAEAAAFIgOAAIAAAAQgBgJAIgHQAHgHANAAQAMAAAHAGQAHAIAAANIABAtIACAJIgQAAIgCgNQgDAHgFADQgFAEgHAAQgKAAgGgHgAhpBiQgEAFAAAFQAAAGADADQACADAFAAQAGAAAFgDQAFgEABgGIAAgOIgMAAQgHAAgEAFgAi6B9QgIgGAAgLIAAgBIAOAAQAAAGAEAEQAEAEAHAAQAHAAAEgEQAEgDAAgGQAAgHgEgCQgEgDgHAAIgMAAIAAgLIAMAAQAHAAADgEQADgDAAgFQAAgFgDgEQgDgDgHAAQgGAAgEADQgEAEAAAFIgOAAIAAAAQAAgKAIgHQAIgGAMAAQANAAAIAGQAHAGAAAKQAAAGgDAEQgDAFgGADQAHACADAFQAEAFAAAGQAAAMgJAFQgIAHgNAAQgMAAgJgHgAkfB5QgIgLAAgSIAAgCQAAgRAIgMQAIgLAOAAQAMAAAIAIQAHAIAAANIAAAAIgOAAQAAgIgDgFQgEgFgGAAQgIAAgEAJQgDAHAAANIAAACQAAANADAIQAEAIAIAAQAGAAAEgFQADgDAAgIIAOAAIAAABQAAALgIAIQgIAHgLAAQgOAAgIgLgAn0B5QgIgMAAgRIAAgCQAAgSAIgLQAJgLAOAAQAPAAAIALQAIALAAASIAAACQAAARgIAMQgIALgPAAQgOAAgJgLgAnpBGQgEAHAAANIAAACQAAANAEAIQAEAIAIAAQAIAAAEgIQAEgIAAgNIAAgCQAAgNgEgHQgEgJgIAAQgIAAgEAJgAo8B5QgJgMAAgRIAAgDIAAgBIAAgSQAAgXAIgKQAIgLAQAAQAIgBAFgBQAEgCAAgFIAMAAIAAAAQAAAMgHAEQgHAFgOAAQgKAAgFAGQgGAFABALIAAABQADgGAGgCQAFgDAGAAQAOAAAIALQAIALAAASIAAACQAAARgIAMQgJALgOAAQgPAAgIgLgAoyBGQgEAHAAANIAAACQAAANAEAIQAEAIAJAAQAIAAAEgIQAEgIAAgNIAAgCQAAgNgEgHQgEgJgIAAQgJAAgEAJgAsQB9QgFgFAAgMQAAgLAIgGQAHgHAPAAIAMAAIAAgHQAAgIgEgEQgDgEgGAAQgFAAgDADQgEAEAAAFIgOAAIAAAAQAAgJAHgHQAIgHAMAAQAMAAAHAGQAIAIAAANIAAAtIACAJIgPAAIgCgNQgDAHgFADQgGAEgGAAQgLAAgGgHgAsCBiQgEAFAAAFQAAAGACADQADADAFAAQAGAAAFgDQAEgEACgGIAAgOIgNAAQgHAAgDAFgAMTCDIAAgPIAPAAIAAAPgAKJCDIAAg2IgBAAIgaA2IgPAAIAAhPIAPAAIAAA2IAbg2IAPAAIAABPgAFPCDIAAhFIgWAAIAAgKIA7AAIAAAKIgWAAIAABFgADaCDIAAg2IAAAAIgbA2IgPAAIAAhPIAPAAIAAA2IAbg2IAPAAIAABPgAB6CDIAAhPIAtAAIAAALIgeAAIAABEgAmGCDIAAgiIgbAAIAAAiIgPAAIAAhPIAPAAIAAAiIAbAAIAAgiIAPAAIAABPgArMCDIAAhPIAPAAIAABDIAWAAIAAhDIAPAAIAABDIAWAAIAAhDIAPAAIAABPgAtbCDIAAhPIAbAAQAOAAAHAEQAIAGAAALQAAAFgDAFQgEAEgGADQAIABAEAGQAEAEAAAHQAAALgHAGQgHAGgNAAgAtMB3IARAAQAGAAADgDQADgDAAgGQAAgFgDgDQgDgEgGABIgRAAgAtMBVIANAAQAHAAADgDQADgDAAgFQAAgGgEgDQgDgDgHAAIgMAAgAMTBfIAAhHIAPAAIAABHgAK8gTIACgLIACABIACAAQAFAAACgEQADgEABgFIADgIIgZhOIAQAAIAPA5IAQg5IAQAAIgcBbQgDAIgFAFQgEAHgJAAgAJ1gTIAAhtIAMAAIACAJQADgFAFgDQAEgDAHAAQAMAAAHAMQAHALAAATIAAABQAAASgHAKQgHALgMAAQgGAAgFgCQgEgDgDgEIAAAmgAKJh0QgDADgCAFIAAAnQACAFADADQAEACAFAAQAIAAADgIQAEgHAAgNIAAgBQAAgNgEgJQgDgJgIABQgFAAgEACgAMsg6QgJgKAAgQIgTAAIAAAiIgPAAIAAhOIAPAAIAAAhIATAAQABgQAIgKQAIgJAOAAQAOAAAJALQAIAMAAARIAAACQAAARgIAMQgJALgOAAQgOAAgIgKgAM1huQgEAHAAANIAAACQAAAMAEAIQAEAJAJAAQAIAAAEgJQAEgIAAgMIAAgCQAAgNgEgHQgEgJgIAAQgJAAgEAJgADIg2QgFgHAAgKQAAgLAIgHQAHgGAPgBIAMAAIAAgIQAAgHgEgEQgDgEgGAAQgFAAgDAEQgEADAAAFIgOAAIAAAAQAAgJAHgHQAIgHAMAAQAMAAAHAGQAIAIAAAMIAAAuIACAIIgPAAIgCgLQgDAFgFAEQgGAEgGAAQgLAAgGgGgADWhSQgEAFAAAGQAAAFACAEQADACAFAAQAGABAFgEQAEgEACgFIAAgPIgNAAQgHABgDAEgABng7QgIgMAAgRIAAgCQAAgRAIgMQAIgLAOAAQAMAAAIAIQAHAIAAANIAAAAIgOAAQAAgIgDgFQgEgFgGAAQgIAAgEAJQgDAHAAANIAAACQAAANADAIQAEAIAIAAQAGAAAEgEQADgFAAgHIAOAAIAAABQAAAKgIAJQgIAHgLAAQgOAAgIgLgAAeg2QgGgHAAgKQAAgLAIgHQAIgGAOgBIAMAAIAAgIQAAgHgDgEQgDgEgGAAQgGAAgDAEQgDADAAAFIgOAAIAAAAQgBgJAIgHQAHgHANAAQAMAAAHAGQAHAIAAAMIABAuIACAIIgQAAIgCgLQgDAFgFAEQgFAEgHAAQgKAAgGgGgAArhSQgEAFAAAGQAAAFADAEQACACAFAAQAGABAFgEQAFgEABgFIAAgPIgMAAQgHABgEAEgAizg7QgJgLAAgRIAAgDQAAgSAJgLQAIgLAOAAQANAAAHAJQAHAKAAAQIAAAIIgrAAQAAAMAFAIQAEAIAJAAQAGAAAFgCQAEgCAEgEIAFAJQgEAFgGACQgHADgIAAQgPAAgIgLgAiohxQgDAGgBAKIAcAAIAAgBQAAgKgEgFQgDgGgGAAQgHAAgEAGgAkDg7QgJgKAAgTIAAgdQAAgUAJgKQAKgLAQAAQAQAAAKAJQAJAIgBARIAAAAIgOAAQAAgMgFgFQgFgGgKABQgKgBgFAIQgFAHAAAOIAAAeQAAAOAFAHQAGAIAKAAQAJAAAFgFQAFgGAAgLIAOAAIAAAAQABAPgJAKQgKAIgPAAQgRAAgKgLgAmgg8QgJgLAAgSIAAgBQAAgSAJgLQAIgMAPAAQAOAAAJAMQAIALAAASIAAABQAAASgIALQgJALgOAAQgPAAgIgLgAmWhvQgEAIAAANIAAABQAAANAEAIQAEAIAJAAQAIAAAEgIQAEgIAAgNIAAgBQAAgNgEgIQgEgJgIABQgJgBgEAJgAp2g8QgJgKAAgSIAAgDQAAgSAJgKQAIgMAOAAQANAAAHAKQAHAKAAAPIAAAJIgrAAQAAAMAFAHQAEAJAJgBQAGAAAFgBQAEgCAEgFIAFAKQgEAEgGADQgHACgIAAQgPAAgIgLgAprhyQgDAHgBAJIAcAAIAAgBQAAgJgEgGQgDgFgGAAQgHAAgEAFgAsJg8QgJgLAAgSIAAgBQAAgSAJgLQAIgMAPAAQAOAAAJAMQAIALAAASIAAABQAAASgIALQgJALgOAAQgPAAgIgLgAr/hvQgEAIAAANIAAABQAAANAEAIQAEAIAJAAQAIAAAEgIQAEgIAAgNIAAgBQAAgNgEgIQgEgJgIABQgJgBgEAJgAJVgyIAAg2IAAAAIgbA2IgPAAIAAhOIAPAAIAAA2IAbg2IAPAAIAABOgAHigyIAAhOIAcAAQANAAAIAEQAHAGAAALQAAAFgDAFQgDAEgGADQAHABAEAGQAEAFAAAGQAAALgHAGQgHAGgNgBgAHxg9IARAAQAGAAADgCQADgDAAgGQAAgGgDgDQgDgEgGAAIgRAAgAHxhfIAOAAQAGAAADgDQADgCAAgGQAAgGgDgDQgDgCgHAAIgNAAgAHCgyIAAg2IAAAAIgbA2IgPAAIAAhOIAPAAIAAA2IAbg2IAPAAIAABOgAFmgyIAAhDIgWAAIAAgLIA8AAIAAALIgXAAIAABDgAE3gyIgUghIgHAAIAAAhIgPAAIAAhOIAPAAIAAAgIAGAAIAUggIATAAIgaAlIAcApgAgCgyIAAgcIgHABIgGAAQgOAAgHgGQgIgIAAgQIAAgVIAPAAIAAAVQAAALADAEQAEAEAHAAIAGAAIAHgCIAAgmIANAAIAABOgAhLgyIAAg2IAAAAIgbA2IgPAAIAAhOIAPAAIAAA2IAbg2IAPAAIAABOgAlbgyIAAgPIAPAAIAAAPgAnFgyIAAgiIgbAAIAAAiIgPAAIAAhPIAPAAIAAAiIAbAAIAAgiIAPAAIAABPgAoPgyIAAgdIgGACIgGAAQgOAAgIgHQgHgHAAgQIAAgWIAPAAIAAAWQAAAKADAFQADAEAIAAIAGgBIAGgBIAAgnIAPAAIAABPgAqbgyIAAgiIgbAAIAAAiIgPAAIAAhPIAPAAIAAAiIAbAAIAAgiIAPAAIAABPgAsrgyIgegwIgIAAIAAAwIgPAAIAAhrIAPAAIAAAvIAHAAIAdgvIASAAIgjAyIAmA5gAlbhWIAAhHIAPAAIAABHgAhoiTQgFgFAAgJIAAAAIALAAQAAAFACADQADACAFAAQAEAAADgCQACgDAAgFIALAAIAAAAQABAJgGAFQgGAFgJAAQgKAAgGgFg");
	this.shape.setTransform(88.1,17.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1.6,0.8,173,32.6);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("ABJA1IAAhNIAPAAIAABNgAgDA1IAAhNIANAAIAAAbIAPAAQANAAAHAHQAIAHAAALQAAALgIAHQgHAHgNAAgAAKApIAPAAQAGAAAEgDQACgEAAgGQAAgGgCgEQgEgEgGAAIgPAAgAhXA1IAAhpIAeAAQAQAAAIAHQAJAHAAAPQgBAHgDAGQgEAGgHADQAKABAFAFQAFAIAAAKQAAAOgIAIQgJAIgPAAgAhHApIAUAAQAIAAAEgEQAFgFAAgJQAAgJgFgFQgDgGgJAAIgUAAgAhHgGIARAAQAGAAAFgEQAEgFAAgIQAAgJgEgEQgFgEgJAAIgOAAg");
	this.shape.setTransform(8.8,5.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,17.6,10.7);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("Am+BEIAAhrIANAAIABAJQAEgFAEgDQAFgDAGAAQANAAAHAMQAHALAAASIAAAAQAAASgHAKQgHALgNAAQgGAAgEgCQgFgDgDgEIAAAmgAmpgbQgEADgCAFIAAAlQACAFAEACQADADAFAAQAIAAAEgIQAEgHAAgNIAAAAQAAgMgEgJQgEgJgIABQgFAAgDACgAI7AhQgFgHAAgKQAAgLAIgFQAHgGAPgBIAMAAIAAgIQAAgHgEgEQgDgEgGAAQgFAAgDADQgEAEAAAFIgOAAIAAAAQAAgJAHgHQAIgHAMAAQAMAAAHAGQAIAIAAAMIAAAsIACAIIgPAAIgCgMQgDAGgFAEQgGAEgGAAQgLAAgGgGgAJJAFQgEAFAAAGQAAAFACAEQADACAFAAQAGABAFgEQAEgEACgFIAAgPIgNAAQgHABgDAEgAGrAcQgIgMAAgQIAAgBQAAgRAIgMQAJgLAOAAQAPAAAIALQAIAMAAARIAAABQAAAQgIAMQgIALgPAAQgOAAgJgLgAG2gVQgEAHAAANIAAABQAAALAEAIQAEAJAIAAQAIAAAEgJQAEgIAAgLIAAgBQAAgNgEgHQgEgJgIAAQgIAAgEAJgABCAcQgIgLAAgRIAAgBQAAgSAIgLQAJgLANAAQAOAAAHAJQAHAKAAAQIAAAGIgrAAQAAAMAEAIQAEAIAJAAQAHAAAEgCQAFgCAEgEIAFAJQgEAFgHACQgGADgJAAQgOAAgJgLgABOgYQgEAGgBAKIAcAAIAAgBQAAgKgDgFQgDgGgHAAQgGAAgEAGgAhpAcQgIgMAAgQIAAgBQAAgRAIgMQAJgLAOAAQAPAAAIALQAIAMAAARIAAABQAAAQgIAMQgIALgPAAQgOAAgJgLgAhegVQgEAHAAANIAAABQAAALAEAIQAEAJAIAAQAIAAAEgJQAEgIAAgLIAAgBQAAgNgEgHQgEgJgIAAQgIAAgEAJgAoCAhQgFgHAAgKQAAgLAIgFQAHgGAPgBIAMAAIAAgIQAAgHgEgEQgDgEgGAAQgFAAgDADQgEAEAAAFIgOAAIAAAAQAAgJAHgHQAIgHAMAAQAMAAAHAGQAIAIAAAMIAAAsIACAIIgPAAIgCgMQgDAGgFAEQgGAEgGAAQgLAAgGgGgAn0AFQgEAFAAAGQAAAFACAEQADACAFAAQAGABAFgEQAEgEACgFIAAgPIgNAAQgHABgDAEgAHwAlIAAhMIAbAAQAOAAAHAEQAIAGAAALQAAAFgDAFQgEAEgGADQAIABAEAEQAEAFAAAGQAAALgHAGQgHAGgNgBgAH/AaIARAAQAGAAADgCQADgDAAgGQAAgGgDgDQgDgEgGAAIgRAAgAH/gGIANAAQAHAAADgDQADgCAAgGQAAgGgEgDQgDgCgHAAIgMAAgAGIAlIgUghIgHAAIAAAhIgPAAIAAhMIAPAAIAAAgIAGAAIAUggIATAAIgaAlIAcAngAE+AlIAAg0IgBAAIgaA0IgPAAIAAhMIAPAAIAAA0IAbg0IAPAAIAABMgAD0AlIAAghIgbAAIAAAhIgPAAIAAhMIAPAAIAAAhIAbAAIAAghIAPAAIAABMgACBAlIAAhMIAcAAQANAAAIAEQAHAGAAALQAAAFgDAFQgDAEgGADQAHABAEAEQAEAFAAAGQAAALgHAGQgHAGgNgBgACQAaIARAAQAGAAADgCQADgDAAgGQAAgGgDgDQgDgEgGAAIgRAAgACQgGIAOAAQAGAAADgDQADgCAAgGQAAgGgDgDQgDgCgHAAIgNAAgAAgAlIgSghIgEAAIAAAhIgNAAIAAghIgEAAIgRAhIgTAAIAYgoIgXgkIATAAIAQAgIAEAAIAAggIANAAIAAAgIAEAAIARggIASAAIgXAkIAZAogAiKAlIgfguIgHAAIAAAuIgPAAIAAhoIAPAAIAAAvIAGAAIAegvIASAAIgjAyIAmA2gAkCAlIAAgdIgOAAIgPAdIgPAAIAQggQgHgDgDgDQgEgHAAgHQAAgLAIgHQAHgHANABIAdAAIAABMgAkagZQgDAFAAAFQAAAFADAEQADAFAGAAIAPAAIAAgbIgOAAQgGAAgEADgAlKAlIAAg0IgBAAIgaA0IgPAAIAAhMIAPAAIAAA0IAbg0IAPAAIAABMgAolAlIAAhKIAAAAIgZBKIgKAAIgZhLIAAAAIAABLIgPAAIAAhoIATAAIAaBVIAAAAIAahVIATAAIAABog");
	this.shape.setTransform(62.6,6.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,125.2,13.7);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66CC00").s().p("AgfAfQgNgNAAgSQAAgRANgOQAOgNARAAQASAAANANQAOAOAAARQAAASgOANQgNAOgSAAQgRAAgOgOg");
	this.shape.setTransform(4.5,4.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,9,9);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Am8BeIACgOIADAAIADAAQAGAAAEgFQADgFACgGIAEgLIgihnIAWAAIATBJIABAAIAVhJIAVAAIglB3QgEALgGAIQgHAIgMgBgAEkBdIAAiPIARAAIACAMQAEgHAGgEQAHgEAIABQARAAAJAOQAJAQAAAYIAAABQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAE/ghQgEADgDAHIAAAzQADAFAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgBQAAgQgGgMQgFgLgKAAQgHAAgFAEgAGNAoQgLgOAAgYIAAgCQAAgXALgPQALgOAUAAQATAAAMAOQALAPAAAXIAAACQAAAYgLAOQgMAPgTAAQgUAAgLgPgAGcgaQgGAKAAAQIAAACQAAAQAGALQAFALALAAQALAAAFgLQAGgLAAgQIAAgCQAAgQgGgKQgFgMgLAAQgLAAgFAMgAIhA1IgbgsIgJAAIAAAsIgUAAIAAhnIAUAAIAAAsIAIAAIAbgsIAZAAIgjAxIAlA2gADbA1IAAhnIA8AAIAAAPIgoAAIAABYgACyA1IAAhGIgBAAIgkBGIgUAAIAAhnIAUAAIAABGIABAAIAkhGIATAAIAABngAAkA1IAAhGIgBAAIgjBGIgSAAIAAhnIASAAIAABGIAAAAIAkhGIAUAAIAABngAg8A1IAAhGIgBAAIgjBGIgUAAIAAhnIAUAAIAABGIAAAAIAkhGIAUAAIAABngAkBA1IAAhnIAUAAIAABYIAdAAIAAhYIAUAAIAABYIAdAAIAAhYIAUAAIAABngAkrA1IAAgnIgIADIgJABQgSgBgKgJQgKgIAAgVIAAgdIAUAAIAAAdQAAAOAEAFQAFAEAJAAIAJAAIAIgCIAAgyIAUAAIAABngAnmA1IAAh9IgoAAIAAAyQAAAngKASQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgOQAFgNAAghIAAhBIBQAAIAACMgAgBhLQgHgHAAgMIABgBIAMAAQAAAHADAEQADAFAHAAQAGAAADgFQADgEAAgHIAPAAIABABQAAAMgIAHQgHAHgNAAQgNAAgGgHg");
	this.shape.setTransform(57.2,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,114.4,19.2);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak2BKQgTgZACgqQABgnAVgaQAUgZAiAAQAiAAASAYQARAYgBAnQgBAVgKAPQgKAQgUAAQgGAAgFgFQgFgEgCgIQgFAIgGAFQgFAEgJAAQgLAAgHgMQgGgMACgTQABgXALgPQAKgPAPAAQAJAAAGADQAGACAHAFIgBABIABAAIgEA2QgBALADAFQABAEAFAAQAKAAAHgMQAGgLABgSQACgjgOgUQgOgVgeAAQgbAAgQAWQgQAXgCAiQgBAkAOAWQAPAVAbAAQAIAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgJAAQgiAAgSgYgAkJgRQgHALgBATQgBAOADAIQADAIAGAAQAGAAAEgEQAFgDADgIIABgBIAAgCIAEgyIgKgDQgLAAgFALgAmfBfIACgPIADAAIADABQAGAAAEgFQACgFACgHIAFgLIgihnIAWAAIATBKIABAAIAUhKIAWAAIgmB4QgDALgHAIQgGAHgNAAgAijBeIAAiQIASAAIABANQAFgHAFgEQAHgEAJAAQAQAAAKAPQAIAQABAXIAAACQgBAYgIAOQgKAOgQAAQgJAAgGgDQgFgDgFgGIAAAygAiIghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQALAAAEgKQAGgKAAgRIAAgCQAAgQgGgLQgEgLgLAAQgHAAgFADgAqJBeIAAiQIARAAIABANQAFgHAFgEQAHgEAJAAQAQAAAKAPQAIAQABAXIAAACQgBAYgIAOQgKAOgQAAQgIAAgHgDQgGgDgEgGIAAAygApughQgFAEgDAGIAAAzQADAGAFAEQAEADAHAAQAKAAAGgKQAFgKAAgRIAAgCQAAgQgFgLQgGgLgKAAQgHAAgEADgAMAApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAALAPQAMAPAAAWIAAACQAAAYgMAPQgLAPgTAAQgUAAgLgPgAMOgaQgFALAAAPIAAACQAAARAFALQAGALALAAQAKAAAGgLQAGgLgBgRIAAgCQABgPgGgLQgFgLgMAAQgKAAgGALgAKlApQgLgPAAgXIAAgDQAAgWALgPQALgPATAAQAQAAAKALQAKALAAARIAAAAIgSAAQAAgKgGgHQgEgHgIAAQgLAAgFALQgFALAAAPIAAADQAAAQAFALQAFALALAAQAIAAAEgGQAGgGAAgJIARAAIABAAQAAAPgKALQgLAKgPAAQgTAAgLgPgAF8ApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAALAPQAMAPAAAWIAAACQAAAYgMAPQgLAPgTAAQgUAAgLgPgAGKgaQgFALAAAPIAAACQAAARAFALQAGALALAAQALAAAFgLQAGgLgBgRIAAgCQABgPgGgLQgFgLgLAAQgMAAgFALgAEYAqQgJgOAAgYIAAgCQAAgXAJgQQAKgPAQAAQAIAAAGAEQAGADAEAGIAAg6IAUAAIAACXIgRAAIgCgNQgDAHgHAEQgGAEgJAAQgQAAgKgOgAEogZQgFALAAAQIAAACQAAARAFAKQAFAJALAAQAGAAAFgDQAFgEACgGIAAgxQgDgHgFgEQgEgDgGAAQgLAAgFALgACCApQgMgOAAgXIAAgEQAAgWAMgPQALgPASAAQASAAAJANQAKANgBAVIAAAJIg4AAQgBARAGAKQAGAKAMAAQAIAAAHgDQAFgCAGgFIAGAMQgFAFgJAEQgIAEgMAAQgTAAgLgPgACRgdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgAg5ApQgMgPAAgYIAAgCQAAgWAMgPQAKgPAUAAQATAAAKAPQALAPAAAWIAAACQAAAYgLAPQgJAPgUAAQgUAAgKgPgAgrgaQgGALABAPIAAACQgBARAGALQAFALALAAQALAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAn3AvQgIgIAAgPQAAgOALgJQALgHASAAIARAAIAAgLQAAgJgFgGQgFgFgHAAQgHAAgFAFQgEAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAPAAALAJQAJAKAAARIAAAvIABAMIACALIgTAAIgDgQQgFAIgHAFQgHAFgIAAQgPAAgHgJgAnmAKQgFAGAAAIQAAAIAEAEQAEAFAFAAQAJAAAGgFQAGgFADgIIAAgSIgRAAQgJAAgGAFgAq5AwQgGgHAAgQIAAg9IgPAAIAAgOIAPAAIAAgaIATAAIAAAaIARAAIAAAOIgRAAIAAA9QABAIACAEQADADADAAIAHgBIACAOIgGACIgHABQgMAAgGgIgAsYAuQgKgKAAgNIAAgBIATAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgJgHAAgLQABgNAJgIQALgJAPAAQAQAAAKAKQALAJgBANIgBABIgSAAQgBgIgEgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAIAHQAJAHgBAMQABANgLAJQgKAIgQAAQgSAAgKgKgAtxApQgLgOAAgXIAAgEQAAgWALgPQAMgPARAAQATAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAFAKANAAQAIAAAGgDQAGgCAGgFIAFAMQgEAFgJAEQgJAEgLAAQgTAAgMgPgAthgdQgFAIgCANIAlAAIAAgCQAAgMgDgHQgFgIgJAAQgIAAgFAIgAu9A0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgHgEgAu+ggQgGAEgCAGIAAAwQACAHAGAEQAEADAHAAQAKAAAGgJQAEgKAAgRIAAgCQAAgQgEgLQgGgLgKAAQgHAAgEAEgAPHA2IAAg9QAAgQgEgHQgEgGgIAAQgHAAgEAFQgFAFgCAIIAAAEIAABEIgUAAIAAg9QAAgQgEgHQgFgGgHAAQgGAAgFADQgEAEgDAGIAABNIgUAAIAAhoIASAAIABAOQAFgHAGgFQAHgEAJAAQAJAAAHAFQAGAFADAKQAEgKAIgFQAGgFAKAAQAOAAAHALQAIALAAAXIAAA9gAJwA2IAAgUIAUAAIAAAUgAJDA2IAAg9QAAgQgEgHQgEgGgIAAQgHAAgEAFQgFAFgCAIIAAAEIAABEIgUAAIAAg9QAAgQgEgHQgFgGgHAAQgHAAgEADQgEAEgDAGIAABNIgUAAIAAhoIASAAIABAOQAFgHAGgFQAHgEAJAAQAJAAAGAFQAHAFADAKQAEgKAIgFQAGgFAKAAQANAAAIALQAIALAAAXIAAA9gADWA2IAAhoIARAAIACAQQADgJAGgEQAFgFAIAAIAGABIgCASIgJgBQgGAAgEAEQgFAEgCAGIAABKgABXA2IgcgxIgIAAIAAAxIgTAAIAAiXIATAAIAABZIAIAAIAZgqIAXAAIggAwIAkA4gAomA2IAAiXIATAAIAACXg");
	this.shape.setTransform(98.8,9.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,197.5,19.7);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("ADAALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIgABzALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIgAAmALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIgAglALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIgAhyALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIgAi/ALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgbIAOAAIAAAbIAVgJIAEAOIgVAFIANAWIgLAIg");
	this.shape.setTransform(22.5,3.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,45,6.8);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.reg();
	this.instance.setTransform(4.5,-6.4,0.774,0.774);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.5,-6.4,329.6,69.7);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.avatar();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,25,29);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.envelope();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,29,22);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.padlock();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,21,29);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ38();
	this.instance.setTransform(260,55,1,1,0,0,0,260,55);
	this.instance.alpha = 0.488;
	this.instance.compositeOperation = "lighter";
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(260,55,1,1,0,0,0,260,55);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,520,110);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A5+LCIAA2DMAz9AAAIAAWDg");
	mask.setTransform(249.8,61.5);

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.setTransform(249.4,55,1,1,0,0,0,260,55);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(83.5,0,332.7,110);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.setTransform(78.7,6.9,1,1,0,0,0,62.6,6.9);

	this.instance_1 = new lib.Символ25();
	this.instance_1.setTransform(4.5,5.8,1,1,0,0,0,4.5,4.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,141.2,13.7);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.setTransform(78.7,6.9,1,1,0,0,0,62.6,6.9);

	this.instance_1 = new lib.Символ25();
	this.instance_1.setTransform(4.5,5.8,1,1,0,0,0,4.5,4.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,141.2,13.7);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 36
	this.instance = new lib.Символ43();
	this.instance.setTransform(1337.5,366.1,0.84,0.84,0,0,0,259.9,55);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(76).to({_off:false},0).to({regX:260,scaleX:0.83,scaleY:0.83,x:1337.6,alpha:0.078},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5,alpha:0.27},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2,alpha:0.148},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1,alpha:0},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.83,scaleY:0.83,x:1337.6,alpha:0.078},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5,alpha:0.27},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2,alpha:0.148},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1,alpha:0},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.83,scaleY:0.83,x:1337.6,alpha:0.078},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5,alpha:0.27},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2,alpha:0.148},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1,alpha:0},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.83,scaleY:0.83,x:1337.6,alpha:0.078},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5,alpha:0.27},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2,alpha:0.148},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1,alpha:0},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.83,scaleY:0.83,x:1337.6,alpha:0.078},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5,alpha:0.27},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2,alpha:0.148},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:498.4,alpha:0},9,cjs.Ease.get(-1)).wait(1));

	// Символ 36
	this.instance_1 = new lib.Символ36();
	this.instance_1.setTransform(1337.5,530.2,0.84,0.84,0,0,0,259.9,55);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(24).to({y:366.1},14,cjs.Ease.get(1)).wait(38).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:366.1},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6},7,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.79,scaleY:0.79,x:1337.5},6,cjs.Ease.get(1)).to({regX:260,scaleX:0.81,scaleY:0.81,x:1337.6,y:366.2},5,cjs.Ease.get(-1)).to({regX:259.9,scaleX:0.84,scaleY:0.84,x:1337.5,y:498.4,alpha:0},9,cjs.Ease.get(-1)).wait(1));

	// Символ 37
	this.instance_2 = new lib.Символ37();
	this.instance_2.setTransform(1310.7,-243.7,0.764,0.764,83.3,0,0,281,124);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:1362.5,y:196.6},38,cjs.Ease.get(1)).to({rotation:83.4,y:177.7},11,cjs.Ease.get(-1)).to({rotation:83.3,y:169.8},10,cjs.Ease.get(1)).to({regX:281.1,rotation:83.4,x:1362.4,y:183.3},11,cjs.Ease.get(-1)).to({regX:281,rotation:83.3,x:1362.5,y:196.6},11,cjs.Ease.get(1)).to({rotation:83.4,y:177.7},11,cjs.Ease.get(-1)).to({rotation:83.3,y:169.8},10,cjs.Ease.get(1)).to({regX:281.1,rotation:83.4,x:1362.4,y:183.3},11,cjs.Ease.get(-1)).to({regX:281,rotation:83.3,x:1362.5,y:196.6},11,cjs.Ease.get(1)).to({rotation:83.4,y:177.7},11,cjs.Ease.get(-1)).to({rotation:83.3,y:169.8},10,cjs.Ease.get(1)).to({regX:281.1,rotation:83.4,x:1362.4,y:183.3},11,cjs.Ease.get(-1)).to({regX:281,rotation:83.3,x:1362.5,y:196.6},11,cjs.Ease.get(1)).to({x:1358.5,y:162.8},17,cjs.Ease.get(-1)).to({x:1374.6,y:666.1,alpha:0},15,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(1110.4,-468.1,436.7,1063.1);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 32
	this.instance = new lib.Символ32();
	this.instance.setTransform(313.9,439.7,1.311,1.311,0,0,0,70.5,6.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(82).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(58));

	// Символ 31
	this.instance_1 = new lib.Символ31();
	this.instance_1.setTransform(311.6,143.4,1.311,1.311,0,0,0,70.5,6.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(8).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(132));

	// Символ 30
	this.instance_2 = new lib.Символ30();
	this.instance_2.setTransform(406.4,197.5,1.311,1.311,0,0,0,128,7.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(126));

	// Символ 29
	this.instance_3 = new lib.Символ29();
	this.instance_3.setTransform(476.3,341.2,1.311,1.311,0,0,0,145.3,7.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(49).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(91));

	// Символ 28
	this.instance_4 = new lib.Символ28();
	this.instance_4.setTransform(428.4,494.1,1.311,1.311,0,0,0,142,16.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(90).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(50));

	// Символ 27
	this.instance_5 = new lib.Символ27();
	this.instance_5.setTransform(531.3,283.8,1.311,1.311,0,0,0,8.8,5.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(42).to({_off:false},0).to({alpha:1},10,cjs.Ease.get(1)).wait(98));

	// Символ 34
	this.instance_6 = new lib.Символ34();
	this.instance_6.setTransform(636.2,198.5,1.311,1.311,0,0,0,168.1,31.6);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:426.4,alpha:1},10,cjs.Ease.get(1)).wait(140));

	// Символ 33
	this.instance_7 = new lib.Символ33();
	this.instance_7.setTransform(681.7,342.6,1.311,1.311,0,0,0,168.1,31.6);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(35).to({_off:false},0).to({x:472,alpha:1},10,cjs.Ease.get(1)).wait(105));

	// Символ 35
	this.instance_8 = new lib.Символ35();
	this.instance_8.setTransform(638.4,494.8,1.311,1.311,0,0,0,168.1,31.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(79).to({_off:false},0).to({x:428.7,alpha:1},10,cjs.Ease.get(1)).wait(61));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(279.5,157.1,440.6,82.9);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ11();
	this.instance.setTransform(213,45,1,1,0,0,0,213,45);
	this.instance.alpha = 0.469;
	this.instance.compositeOperation = "lighter";
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ11();
	this.instance_1.setTransform(213,45,1,1,0,0,0,213,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.5,-6.4,329.6,69.7);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(33.5,34.1,1,1,0,0,0,10.5,14.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-183.5,-40,367,80,11.5);
	this.shape.setTransform(160,34.9,0.872,0.872);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,69.8);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();
	this.instance.setTransform(37.4,35.8,1,1,0,0,0,14,11);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-183.45,-40,366.9,80,11.5);
	this.shape.setTransform(160,34.9,0.872,0.872);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,69.8);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.setTransform(35.5,35.5,1,1,0,0,0,12.5,14.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().rr(-183.5,-40,367,80,11.5);
	this.shape.setTransform(160,34.9,0.872,0.872);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,69.8);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.setTransform(213,45,1,1,0,0,0,213,45);
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(4.5,-6.4,329.6,69.7);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("AAAALIgMAWIgLgIIANgWIgVgFIAFgNIAVAJIAAgaIAMAAIAAAaIAUgJIAFAOIgWAFIANAWIgLAIg");
	this.shape.setTransform(1041.7,516.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AAmALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAglALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIg");
	this.shape_1.setTransform(1045.6,516.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("ABMALIgNAWIgLgIIANgWIgVgFIAFgNIAVAJIAAgaIAOAAIAAAaIAUgJIAFAOIgWAFIANAWIgLAIgAAAALIgMAWIgLgIIANgWIgVgFIAFgNIAVAJIAAgaIAMAAIAAAaIAUgJIAFAOIgWAFIANAWIgLAIgAhMALIgNAWIgLgIIANgWIgVgFIAFgNIAVAJIAAgaIAOAAIAAAaIAUgJIAFAOIgWAFIANAWIgLAIg");
	this.shape_2.setTransform(1049.4,516.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#666666").s().p("ABzALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAAmALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAglALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAhyALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIg");
	this.shape_3.setTransform(1053.3,516.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#666666").s().p("ACaALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIADALIAAAEIgUAEIANAWIgLAIgABNALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAAAALIgLAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAMAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAhLALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIgAiYALIgNAWIgMgIIAOgWIgVgFIAEgNIAWAJIgBgaIAOAAIAAAaIAVgJIAEAOIgVAFIANAWIgLAIg");
	this.shape_4.setTransform(1057.1,516.4);

	this.instance = new lib.Символ19();
	this.instance.setTransform(1060.9,516.4,1,1,0,0,0,22.4,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},111).to({state:[{t:this.shape_1}]},3).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},2).to({state:[{t:this.instance}]},2).wait(29));

	// Слой 7
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#666666").s().p("AgJBJQgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAGAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgHAAgGgEgAgLgLQgFAEgCAGIAAAwQACAHAFAEQAFADAGAAQAJAAAFgJQAFgKAAgRIAAgCQAAgSgFgJQgFgLgJAAQgGAAgFAEg");
	this.shape_5.setTransform(1041.5,395.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#666666").s().p("AATA+QgLgOAAgXIAAgFQAAgVALgPQAMgPARAAQATAAAJANQAJANAAATIAAALIg5AAQAAARAFAKQAHAKAMAAQAIAAAGgDQAGgCAFgFIAGAMQgEAFgJAEQgJAEgLAAQgUAAgLgPgAAjgIQgFAIgCALIAlAAIAAgCQAAgKgDgHQgFgIgJAAQgJAAgEAIgAg3BJQgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgAg5gLQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQALAAAEgJQAGgKAAgRIAAgCQAAgSgGgJQgEgLgLAAQgHAAgFAEg");
	this.shape_6.setTransform(1046.1,395.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("ABABDQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgHQgIgHAAgJQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBAMIAAAAIgTAAQAAgGgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAEAEADQADAEANAFQAQAGAJAIQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAgWA+QgMgOAAgXIAAgFQAAgVALgPQAMgPAQAAQASAAAJANQAJANAAATIAAALIg3AAQAAARAGAKQAGAKAKAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgRAAgLgPgAgHgIQgFAIgCALIAkAAIAAgCQAAgKgEgHQgFgIgIAAQgHAAgFAIgAhjBJQgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAhkgLQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgSgFgJQgFgLgLAAQgHAAgEAEg");
	this.shape_7.setTransform(1050.4,395.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#666666").s().p("ACBBFQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIADAEQACADAEAAIAGgBIACAOIgFACIgIABQgMAAgFgIgAAhBDQgJgKgBgNIABgBIASAAQABAKAGAFQAEAEAIAAQAJAAAEgEQAFgEgBgGQAAgGgDgEQgEgEgNgGQgPgGgJgHQgIgHAAgJQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBAMIAAAAIgTAAQAAgGgEgFQgFgFgIAAQgHAAgFAEQgDAEAAAGQgBAEAEADQAEAEAMAFQARAGAIAIQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAg1A+QgMgOAAgXIAAgFQABgVAKgPQAMgPASAAQASAAAIANQAIANABATIAAALIg4AAQAAARAGAKQAGAKAMAAQAIAAAHgDQAFgCAEgFIAGAMQgFAFgHAEQgJAEgKAAQgUAAgLgPgAgmgIQgFAIgCALIAmAAIAAgCQAAgKgEgHQgFgIgIAAQgJAAgFAIgAiBBJQgHgEgEgHIgCANIgQAAIAAiXIATAAIAAA7QAEgHAGgDQAHgEAIAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgJAAgGgEgAiDgLQgFAEgDAGIAAAwQADAHAFAEQAFADAGAAQALAAAFgJQAFgKAAgRIAAgCQAAgSgFgJQgFgLgLAAQgGAAgFAEg");
	this.shape_8.setTransform(1053.5,395.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#666666").s().p("ACABgIAAiQIARAAIACAMQAEgGAGgFQAHgDAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJANQgJAOgRAAQgIAAgGgCQgGgEgEgFIAAAygACbgfQgEAEgDAGIAAAzQADAGAEADQAFADAHAAQAKAAAFgKQAGgKAAgQIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgABRAyQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgbIAUAAIAAAbIARAAIAAAOIgRAAIAAA9QAAAIADAEQACADAEAAIAHgBIACAOIgGACIgIAAQgLAAgGgHgAgMAwQgKgLAAgNIAAAAIATAAQAAAKAEAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgOgGgIgFQgJgIAAgLQAAgMAKgIQAKgJAOAAQAQAAAKAKQAKAJAAANIgBAAIgTAAQAAgHgEgFQgFgGgHAAQgIABgEAEQgCAEAAAGQAAAFABAEQAEADAMAGQARAEAIAIQAIAHAAAMQAAANgKAIQgKAJgQgBQgQABgKgKgAhlArQgLgOAAgYIAAgEQAAgWALgOQALgPASAAQASAAAKAMQAJANAAAWIAAAJIg5AAQAAAQAFAKQAGAKAMAAQAJAAAGgCQAGgDAFgFIAGANQgFAFgIAEQgJADgLAAQgUAAgLgOgAhWgbQgFAIgBANIAlAAIAAgCQAAgMgEgIQgEgHgJAAQgJAAgFAIgAixA2QgHgEgEgIIgCAOIgQAAIAAiXIAUAAIAAA6QAEgGAGgEQAGgDAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJANQgJAOgRAAQgJAAgGgDgAizgfQgFAEgCAHIAAAwQACAHAFAEQAFADAHAAQAKAAAFgKQAFgJAAgRIAAgCQAAgRgFgKQgFgLgKAAQgHAAgFADg");
	this.shape_9.setTransform(1058.3,397.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#666666").s().p("ABsBgIAAiQIARAAIACAMQAEgGAGgFQAHgDAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJANQgJAOgRAAQgIAAgGgCQgGgEgEgFIAAAygACHgfQgEAEgDAGIAAAzQADAGAEADQAFADAHAAQAKAAAFgKQAGgKAAgQIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgAA9AyQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgbIAUAAIAAAbIARAAIAAAOIgRAAIAAA9QAAAIADAEQACADAEAAIAHgBIACAOIgGACIgIAAQgLAAgGgHgAggAwQgKgLAAgNIAAAAIATAAQAAAKAGAFQAFAEAIAAQAGAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgKgGQgQgGgIgFQgJgIAAgLQAAgMAKgIQAKgJAQAAQAOAAAKAKQAKAJAAANIgBAAIgTAAQAAgHgEgFQgFgGgFAAQgIABgEAEQgEAEAAAGQAAAFADAEQAEADAMAGQAPAEAIAIQAIAHAAAMQAAANgKAIQgKAJgOgBQgSABgKgKgAh5ArQgLgOAAgYIAAgEQAAgWALgOQALgPASAAQASAAAKAMQAJANAAAWIAAAJIg5AAQAAAQAFAKQAGAKAMAAQAJAAAGgCQAGgDAFgFIAGANQgFAFgIAEQgJADgLAAQgUAAgLgOgAhqgbQgFAIgBANIAlAAIAAgCQAAgMgEgIQgEgHgJAAQgJAAgFAIgAjFA2QgHgEgEgIIgCAOIgQAAIAAiXIAUAAIAAA6QAEgGAGgEQAGgDAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJANQgJAOgRAAQgJAAgGgDgAjHgfQgFAEgCAHIAAAwQACAHAFAEQAFADAHAAQAKAAAFgKQAFgJAAgRIAAgCQAAgRgFgKQgFgLgKAAQgHAAgFADgADPA4IAAiXIAUAAIAACXg");
	this.shape_10.setTransform(1060.3,397.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#666666").s().p("AA7BgIAAiQIARAAIABAMQAFgGAGgFQAGgDAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJANQgKAOgQAAQgIAAgGgCQgGgEgEgFIAAAygABWgfQgFAEgCAGIAAAzQACAGAFADQAFADAGAAQALAAAFgKQAFgKAAgQIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgADNAxQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgGgIAAQgHABgEAEQgFAFAAAHIgTAAIAAAAQgBgMALgJQAKgKAQAAQAQAAAKAJQAJAJAAASIAAAuIABANIADALIgUAAIgDgRQgFAJgGAEQgHAGgJgBQgOAAgIgIgADfAMQgGAGAAAIQAAAIAEAEQAEAFAGgBQAIAAAGgEQAHgGACgHIAAgTIgRAAQgJAAgFAGgAALAyQgGgHAAgQIAAg9IgMAAIAAgOIAMAAIAAgbIAUAAIAAAbIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHAAQgMAAgGgHgAhSAwQgKgLAAgNIABAAIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgIAAgLQAAgMAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAAAIgTAAQAAgHgFgFQgEgGgIAAQgHABgFAEQgEAEAAAGQAAAFAEAEQADADANAGQAQAEAJAIQAIAHAAAMQAAANgKAIQgKAJgRgBQgSABgKgKgAiqArQgMgOAAgYIAAgEQAAgWALgOQAMgPASAAQASAAAJAMQAJANAAAWIAAAJIg5AAQAAAQAGAKQAGAKAMAAQAIAAAGgCQAGgDAGgFIAGANQgFAFgJAEQgJADgLAAQgTAAgLgOgAibgbQgFAIgCANIAmAAIAAgCQAAgMgEgIQgFgHgIAAQgJAAgFAIgAj3A2QgGgEgEgIIgDAOIgQAAIAAiXIAUAAIAAA6QAEgGAGgEQAGgDAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKANQgJAOgRAAQgIAAgHgDgAj4gfQgFAEgDAHIAAAwQADAHAFAEQAEADAHAAQALAAAFgKQAFgJAAgRIAAgCQAAgRgFgKQgFgLgLAAQgHAAgEADgACeA4IAAiXIAUAAIAACXg");
	this.shape_11.setTransform(1065.2,397.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#666666").s().p("AD2BfIACgOIAEAAIACABQAGAAAEgGQADgEACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAWAAIgmB4QgEAKgGAJQgGAHgNAAgAAMBfIAAiQIARAAIABAMQAFgGAGgFQAGgDAJAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJANQgJAOgRAAQgIAAgGgCQgGgEgEgFIAAAygAAnggQgFAEgCAGIAAAzQACAGAFADQAFADAGAAQALAAAFgKQAGgKAAgQIAAgCQAAgQgGgLQgFgLgLAAQgGAAgFADgACeAwQgHgIAAgPQAAgOALgJQAKgHASAAIARAAIAAgLQAAgJgFgGQgEgGgIAAQgHABgEAEQgFAFAAAHIgTAAIAAAAQgBgMALgJQAKgKAQAAQAQAAAKAJQAKAJgBASIAAAuIABANIADALIgUAAIgDgRQgEAJgHAEQgHAGgJgBQgOAAgIgIgACwALQgGAGABAIQAAAIADAEQAEAFAGgBQAIAAAHgEQAGgGACgHIAAgTIgRAAQgJAAgFAGgAghAxQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgbIAUAAIAAAbIAQAAIAAAOIgQAAIAAA9QAAAIADAEQACADAEAAIAGgBIACAOIgFACIgIAAQgMAAgFgHgAiBAvQgJgLgBgNIABAAIASAAQABAKAGAFQAEAEAIAAQAJAAAEgEQAFgEgBgGQAAgGgDgEQgEgEgNgGQgPgGgJgFQgIgIAAgLQAAgMAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAAAIgTAAQAAgHgEgFQgFgGgIAAQgHABgFAEQgDAEAAAGQgBAFAEAEQAEADAMAGQARAEAIAIQAIAHAAAMQAAANgKAIQgKAJgRgBQgSABgKgKgAjZAqQgMgOAAgYIAAgEQABgWAKgOQAMgPASAAQASAAAKAMQAIANABAWIAAAJIg6AAQAAAQAGAKQAGAKAMAAQAIAAAHgCQAFgDAGgFIAGANQgFAFgJAEQgJADgKAAQgUAAgLgOgAjKgcQgFAIgCANIAmAAIAAgCQAAgMgEgIQgFgHgIAAQgJAAgFAIgAklA1QgHgEgEgIIgCAOIgQAAIAAiXIATAAIAAA6QAEgGAGgEQAHgDAIAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJANQgKAOgQAAQgJAAgGgDgAknggQgFAEgDAHIAAAwQADAHAFAEQAFADAGAAQALAAAFgKQAFgJAAgRIAAgCQAAgRgFgKQgFgLgLAAQgGAAgFADgABvA3IAAiXIAUAAIAACXg");
	this.shape_12.setTransform(1069.9,397.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#666666").s().p("AERBKQgSgZABgqQACgnAVgaQAUgZAiAAQAiAAARAYQASAYgBAnQgBAVgKAPQgKAQgUAAQgHAAgFgFQgFgEgBgIQgFAIgGAFQgGAEgIAAQgMAAgGgMQgGgMABgTQACgXALgPQAKgPAPAAQAJAAAGADQAGACAHAFIgBABIABAAIgFA2QAAALACAFQACAEAEAAQALAAAHgMQAGgLABgSQABgjgOgUQgNgVgeAAQgbAAgQAWQgRAXgBAiQgCAkAPAWQAPAVAbAAQAIAAAIgCQAIgCAFgDIAEAKQgGAEgJADQgJACgJAAQgiAAgTgYgAE+gRQgGALgBATQgBAOADAIQADAIAGAAQAGAAAEgEQAFgDADgIIABgBIAAgCIAEgyIgKgDQgLAAgGALgACpBfIACgPIADAAIADABQAGAAADgFQADgFACgHIAEgLIghhnIAVAAIAUBKIAAAAIAVhKIAWAAIgmB4QgEALgGAIQgGAHgNAAgAhABeIAAiQIARAAIACANQAEgHAGgEQAHgEAIAAQARAAAHAPQAJAQAAAXIAAACQAAAYgJAOQgHAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAglghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgABRAvQgIgIAAgPQAAgOALgJQAKgHATAAIAQAAIAAgLQAAgJgEgGQgFgFgIAAQgHAAgEAFQgEAEAAAIIgTAAIAAgBQgBgMAKgJQAKgKARAAQAPAAAKAJQAKAKAAARIAAAvIABAMIACALIgUAAIgDgQQgEAIgHAFQgHAFgJAAQgOAAgHgJgABiAKQgFAGAAAIQAAAIAEAEQADAFAGAAQAJAAAGgFQAGgFACgIIAAgSIgQAAQgKAAgFAFgAhvAwQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIARAAIAAAOIgRAAIAAA9QAAAIADAEQACADAEAAIAHgBIACAOIgGACIgIABQgLAAgGgIgAjOAuQgKgKAAgNIAAgBIATAAQAAAKAGAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgJgHAAgLQAAgNAKgIQAKgJAQAAQAQAAAKAKQAKAJAAANIgBABIgTAAQAAgIgEgFQgFgFgHAAQgIAAgEAEQgEAEAAAGQAAAGADADQAEAEAMAFQARAFAIAHQAIAHAAAMQAAANgKAJQgKAIgQAAQgSAAgKgKgAknApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgAkYgdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgAlzA0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgAl1ggQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQAKAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgKAAQgHAAgFAEgAAhA2IAAiXIAUAAIAACXg");
	this.shape_13.setTransform(1077.7,397.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#666666").s().p("ADgBKQgTgZACgqQACgnAUgaQAVgZAhAAQAiAAASAYQASAYgCAnQgBAVgKAPQgKAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgHgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAGgMQAHgLAAgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgQAXgCAiQgBAkAOAWQAPAVAcAAQAHAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgIAAQgjAAgSgYgAENgRQgGALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgGALgAB3BfIACgPIADAAIADABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEALgGAIQgHAHgMAAgAF0BeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAGPghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAhxBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAhWghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAAfAvQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAJAKAAARIAAAvIABAMIADALIgUAAIgDgQQgFAIgGAFQgHAFgJAAQgOAAgIgJgAAxAKQgGAGAAAIQAAAIAEAEQAEAFAGAAQAIAAAGgFQAHgFACgIIAAgSIgRAAQgJAAgFAFgAihAwQgGgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHABQgMAAgGgIgAkAAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAJAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAlYApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgAlJgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAmlA0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAmmggQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgHAAgEAEgAgOA2IAAiXIASAAIAACXg");
	this.shape_14.setTransform(1082.6,397.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#666666").s().p("ACuBKQgSgZABgqQACgnAVgaQAVgZAhAAQAiAAASAYQARAYgBAnQgBAVgKAPQgKAQgTAAQgIAAgEgFQgFgEgCgIQgFAIgFAFQgHAEgIAAQgLAAgHgMQgGgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgFA2QAAALADAFQACAEADAAQALAAAHgMQAGgLABgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgRAXgBAiQgCAkAPAWQAPAVAbAAQAIAAAIgCQAIgCAFgDIAEAKQgGAEgJADQgJACgJAAQgiAAgTgYgADbgRQgFALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgHALgABGBfIACgPIADAAIADABQAGAAAEgFQACgFACgHIAFgLIgihnIAVAAIAUBKIABAAIAVhKIAVAAIgmB4QgEALgGAIQgGAHgMAAgAFDBeIAAiQIARAAIABANQAEgHAHgEQAGgEAJAAQAQAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgQAAQgIAAgHgDQgFgDgFgGIAAAygAFeghQgFAEgDAGIAAAzQADAGAFAEQAEADAHAAQAKAAAGgKQAFgKAAgRIAAgCQAAgQgFgLQgGgLgKAAQgHAAgEADgAiiBeIAAiQIAQAAIACANQAFgHAGgEQAGgEAJAAQAQAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgQAAQgJAAgFgDQgGgDgEgGIAAAygAiHghQgFAEgCAGIAAAzQACAGAFAEQAEADAHAAQAKAAAGgKQAFgKAAgRIAAgCQAAgQgFgLQgGgLgKAAQgHAAgEADgAGrApQgKgPgBgYIAAgCQABgWAKgPQAMgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgMAPgSAAQgVAAgLgPgAG6gaQgGALAAAPIAAACQAAARAGALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAgQAvQgHgIgBgPQAAgOALgJQALgHAQAAIAQAAIAAgLQABgJgFgGQgEgFgJAAQgGAAgFAFQgCAEAAAIIgTAAIAAgBQgBgMALgJQAJgKAPAAQAQAAAJAJQAKAKAAARIAAAvIABAMIADALIgUAAIgEgQQgEAIgHAFQgGAFgKAAQgMAAgHgJgAAAAKQgEAGAAAIQAAAIAEAEQABAFAHAAQAIAAAGgFQAGgFACgIIAAgSIgQAAQgKAAgEAFgAjSAwQgHgHABgQIAAg9IgPAAIAAgOIAPAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QgBAIADAEQADADAEAAIAGgBIACAOIgGACIgIABQgLAAgGgIgAkxAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQgBgNAKgIQAKgJAQAAQARAAAKAKQAJAJAAANIAAABIgTAAQgBgIgEgFQgFgFgHAAQgIAAgEAEQgEAEAAAGQAAAGADADQAEAEAMAFQARAFAIAHQAJAHgBAMQABANgKAJQgKAIgRAAQgSAAgKgKgAmKApQgLgOAAgXIAAgEQAAgWALgPQAMgPARAAQATAAAJANQAJANAAAVIAAAJIg5AAQAAARAFAKQAHAKAMAAQAIAAAGgDQAGgCAFgFIAGAMQgEAFgJAEQgJAEgLAAQgUAAgLgPgAl6gdQgFAIgCANIAlAAIAAgCQAAgMgDgHQgFgIgJAAQgJAAgEAIgAnWA0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgAnYggQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQALAAAEgJQAGgKAAgRIAAgCQAAgQgGgLQgEgLgLAAQgHAAgFAEgAg/A2IAAiXIAUAAIAACXg");
	this.shape_15.setTransform(1087.6,397.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#666666").s().p("AB+BKQgTgZACgqQACgnAUgaQAVgZAhAAQAiAAASAYQASAYgCAnQgBAVgKAPQgKAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgHgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAGgMQAHgLAAgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgQAXgCAiQgBAkAOAWQAPAVAcAAQAHAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgIAAQgjAAgSgYgACrgRQgGALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgGALgAAVBfIACgPIADAAIADABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEALgGAIQgHAHgMAAgAESBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAEtghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAjTBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAi4ghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAF7ApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgLAPgTAAQgUAAgLgPgAGJgaQgFALAAAPIAAACQAAARAFALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAhBAvQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAHAKAAARIAAAvIABAMIADALIgSAAIgDgQQgFAIgGAFQgHAFgJAAQgOAAgIgJgAgvAKQgGAGAAAIQAAAIAEAEQAEAFAGAAQAIAAAGgFQAHgFACgIIAAgSIgRAAQgJAAgFAFgAkDAwQgGgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHABQgMAAgGgIgAliAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAJAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAm6ApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgAmrgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAoHA0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAoIggQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgHAAgEAEgAIOA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAhwA2IAAiXIAUAAIAACXg");
	this.shape_16.setTransform(1092.4,397.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#666666").s().p("ABTBKQgSgZABgqQACgnAVgaQAUgZAiAAQAiAAARAYQASAYgBAnQgBAVgKAPQgKAQgUAAQgHAAgFgFQgFgEgBgIQgFAIgGAFQgGAEgIAAQgMAAgGgMQgGgMABgTQACgXALgPQAKgPAPAAQAJAAAGADQAGACAHAFIgBABIABAAIgFA2QAAALACAFQACAEAEAAQALAAAHgMQAGgLABgSQABgjgOgUQgNgVgeAAQgbAAgQAWQgRAXgBAiQgCAkAPAWQAPAVAbAAQAIAAAIgCQAIgCAFgDIAEAKQgGAEgJADQgJACgJAAQgiAAgTgYgACAgRQgGALgBATQgBAOADAIQADAIAGAAQAGAAAEgEQAFgDADgIIABgBIAAgCIAEgyIgKgDQgLAAgGALgAgTBfIACgPIADAAIADABQAGAAADgFQACgFABgHIAEgLIgfhnIAVAAIASBKIAAAAIAVhKIAWAAIgmB4QgEALgGAIQgGAHgLAAgADnBeIAAiQIARAAIACANQAEgHAGgEQAHgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAECghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgAj+BeIAAiQIARAAIACANQAEgHAGgEQAHgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAjjghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgAIOApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgAIdgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAFQApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgAFfgaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgAhrAvQgIgIAAgPQAAgOALgJQAKgHATAAIAQAAIAAgLQAAgJgEgGQgFgFgIAAQgHAAgEAFQgEAEAAAIIgTAAIAAgBQgBgMAKgJQAKgKARAAQAPAAAKAJQAKAKAAARIAAAvIABAMIACALIgUAAIgDgQQgEAIgHAFQgHAFgJAAQgOAAgHgJgAhaAKQgFAGAAAIQAAAIAEAEQADAFAGAAQAJAAAGgFQAGgFACgIIAAgSIgQAAQgKAAgFAFgAktAwQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIARAAIAAAOIgRAAIAAA9QAAAIADAEQACADAEAAIAHgBIACAOIgGACIgIABQgLAAgGgIgAmMAuQgKgKAAgNIAAgBIATAAQAAAKAGAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgJgHAAgLQAAgNAKgIQAKgJAQAAQAQAAAKAKQAKAJAAANIgBABIgTAAQAAgIgEgFQgFgFgHAAQgIAAgEAEQgEAEAAAGQAAAGADADQAEAEAMAFQARAFAIAHQAIAHAAAMQAAANgKAJQgKAIgQAAQgSAAgKgKgAnlApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgAnWgdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgAoxA0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgAozggQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQAKAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgKAAQgHAAgFAEgAHjA2IgcgxIgIAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAYAAIghAwIAkA4gAibA2IAAiXIAUAAIAACXg");
	this.shape_17.setTransform(1096.7,397.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#666666").s().p("AAtBKQgSgZABgqQACgnAVgaQAUgZAiAAQAiAAARAYQASAYgBAnQgBAVgKAPQgKAQgUAAQgHAAgFgFQgFgEgBgIQgFAIgGAFQgGAEgIAAQgMAAgGgMQgGgMABgTQACgXALgPQAKgPAPAAQAJAAAGADQAGACAHAFIgBABIABAAIgFA2QAAALACAFQACAEAEAAQALAAAHgMQAGgLABgSQABgjgOgUQgNgVgeAAQgbAAgQAWQgRAXgBAiQgCAkAPAWQAPAVAbAAQAIAAAIgCQAIgCAFgDIAEAKQgGAEgJADQgJACgJAAQgiAAgTgYgABagRQgGALgBATQgBAOADAIQADAIAGAAQAGAAAEgEQAFgDADgIIABgBIAAgCIAEgyIgKgDQgLAAgGALgAg5BfIACgPIADAAIADABQAGAAADgFQADgFACgHIAEgLIghhnIAVAAIAUBKIAAAAIAVhKIAUAAIgkB4QgEALgGAIQgGAHgNAAgADBBeIAAiQIARAAIACANQAEgHAGgEQAHgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygADcghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgAkkBeIAAiQIARAAIACANQAEgHAGgEQAHgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAkJghQgEAEgDAGIAAAzQADAGAEAEQAFADAHAAQAKAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgKAAQgHAAgFADgAHoApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgAH3gdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAEqApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgAE5gaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgAiRAvQgIgIAAgPQAAgOALgJQAKgHATAAIAQAAIAAgLQAAgJgEgGQgFgFgIAAQgHAAgEAFQgEAEAAAIIgTAAIAAgBQgBgMAKgJQAKgKARAAQAPAAAKAJQAKAKAAARIAAAvIABAMIACALIgUAAIgDgQQgEAIgHAFQgHAFgJAAQgOAAgHgJgAiAAKQgFAGAAAIQAAAIAEAEQADAFAGAAQAJAAAGgFQAGgFACgIIAAgSIgQAAQgKAAgFAFgAlTAwQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIARAAIAAAOIgRAAIAAA9QAAAIADAEQACADAEAAIAHgBIACAOIgGACIgIABQgLAAgGgIgAmyAuQgKgKAAgNIAAgBIATAAQAAAKAGAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgJgHAAgLQAAgNAKgIQAKgJAQAAQAQAAAKAKQAKAJAAANIgBABIgTAAQAAgIgEgFQgFgFgHAAQgIAAgEAEQgEAEAAAGQAAAGADADQAEAEAMAFQARAFAIAHQAIAHAAAMQAAANgKAJQgKAIgQAAQgSAAgKgKgAoLApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgAn8gdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgApXA0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgApZggQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQAKAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgKAAQgHAAgFAEgAI7A2IAAhoIASAAIACAQQADgJAGgEQAFgFAHAAIAHABIgDASIgIgBQgGAAgEAEQgFAEgCAGIAABKgAG9A2IgcgxIgIAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAYAAIghAwIAkA4gAjBA2IAAiXIAUAAIAACXgAJ1AEIAAgCIAAgJIAAAWIAAgLg");
	this.shape_18.setTransform(1100.5,397.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#666666").s().p("AAGBKQgRgZACgqQACgnASgaQAVgZAhAAQAiAAASAYQASAYgCAnQAAAVgKAPQgLAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgGgMABgTQACgXALgPQAJgPAPAAQAKAAAGADQAFACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAHgMQAGgLABgSQABgjgOgUQgNgVgeAAQgbAAgRAWQgQAXgBAiQgCAkAOAWQAPAVAcAAQAIAAAHgCQAJgCAFgDIADAKQgGAEgIADQgJACgJAAQgiAAgTgYgAAzgRQgGALgCATQAAAOACAIQADAIAGAAQAHAAAEgEQAFgDADgIIAAgBIAAgCIAFgyIgKgDQgLAAgGALgAhhBfIACgPIAEAAIACABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAWAAIgmB4QgEALgGAIQgGAHgNAAgACaBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAC1ghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKABgRIAAgCQgBgQgFgLQgFgLgLAAQgGAAgFADgAlLBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAkwghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgLAAQgGAAgFADgAJXAqQgKgOABgYIAAgCQgBgXAKgQQAKgPAQAAQAIAAAFAEQAGADAFAGIAAg6IATAAIAACXIgQAAIgCgNQgEAHgHAEQgGAEgIAAQgRAAgJgOgAJmgZQgEALAAAQIAAACQAAARAEAKQAGAJAKAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgEgDgHAAQgKAAgGALgAHAApQgLgOAAgXIAAgEQAAgWALgPQAMgPARAAQATAAAJANQAJANAAAVIAAAJIg5AAQAAARAFAKQAHAKAMAAQAIAAAGgDQAGgCAFgFIAGAMQgEAFgJAEQgJAEgLAAQgUAAgLgPgAHQgdQgFAIgCANIAlAAIAAgCQAAgMgDgHQgFgIgJAAQgJAAgEAIgAEDApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAAMAPQAKAPAAAWIAAACQAAAYgKAPQgMAPgTAAQgUAAgLgPgAESgaQgGALAAAPIAAACQAAARAGALQAEALAMAAQAKAAAGgLQAGgLAAgRIAAgCQAAgPgGgLQgGgLgLAAQgLAAgEALgAi5AvQgHgIAAgPQAAgOALgJQAKgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAKAKgBARIAAAvIABAMIADALIgUAAIgDgQQgEAIgHAFQgHAFgJAAQgOAAgIgJgAinAKQgGAGABAIQAAAIADAEQAEAFAGAAQAIAAAHgFQAGgFACgIIAAgSIgRAAQgJAAgFAFgAl6AwQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIADAEQACADAEAAIAGgBIACAOIgFACIgIABQgMAAgFgIgAnaAuQgJgKgBgNIABgBIASAAQABAKAGAFQAEAEAIAAQAJAAAEgEQAFgEgBgGQAAgGgDgEQgEgEgNgGQgPgGgJgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgEgFQgFgFgIAAQgHAAgFAEQgDAEAAAGQgBAGAEADQAEAEAMAFQARAFAIAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAoyApQgMgOAAgXIAAgEQABgWAKgPQAMgPASAAQASAAAKANQAIANABAVIAAAJIg6AAQAAARAGAKQAGAKAMAAQAIAAAHgDQAFgCAGgFIAGAMQgFAFgJAEQgJAEgKAAQgUAAgLgPgAojgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAp+A0QgHgEgEgHIgCANIgQAAIAAiXIATAAIAAA7QAEgHAGgDQAHgEAIAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgJAAgGgEgAqAggQgFAEgDAGIAAAwQADAHAFAEQAFADAGAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFAEgAIUA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAHAAIAHABIgDASIgJgBQgGAAgEAEQgEAEgCAGIAABKgAGWA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAjoA2IAAiXIAUAAIAACXg");
	this.shape_19.setTransform(1104.4,397.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#666666").s().p("AgrBKQgTgZACgqQACgnAUgaQAVgZAfAAQAiAAASAYQASAYgCAnQgBAVgKAPQgKAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgHAAQgLAAgGgMQgHgMACgTQACgXAKgPQAKgPANAAQAKAAAFADQAGACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAGgMQAHgLAAgSQACgjgOgUQgOgVgdAAQgZAAgRAWQgQAXgCAiQgBAkAOAWQAPAVAaAAQAHAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgIAAQghAAgSgYgAAAgRQgEALgCATQgBAOADAIQADAIAEAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgGALgAiUBfIACgPIADAAIADABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEALgGAIQgHAHgMAAgABnBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygACCghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAl+BeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAljghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAKHApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgAKWgaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgAIkAqQgKgOAAgYIAAgCQAAgXAKgQQAJgPARAAQAHAAAGAEQAGADAFAGIAAg6IATAAIAACXIgQAAIgCgNQgEAHgHAEQgGAEgIAAQgRAAgJgOgAIzgZQgFALAAAQIAAACQAAARAFAKQAFAJALAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgFgDgGAAQgLAAgFALgAGNApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgAGcgdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgADQApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgLAPgTAAQgUAAgLgPgADegaQgFALAAAPIAAACQAAARAFALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAjsAvQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAJAKAAARIAAAvIABAMIADALIgUAAIgDgQQgFAIgGAFQgHAFgJAAQgOAAgIgJgAjaAKQgGAGAAAIQAAAIAEAEQAEAFAGAAQAIAAAGgFQAHgFACgIIAAgSIgRAAQgJAAgFAFgAmuAwQgGgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHABQgMAAgGgIgAoNAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAJAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAplApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgApWgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAqyA0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAqzggQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgHAAgEAEgAHhA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAHAAIAGABIgCASIgJgBQgGAAgEAEQgEAEgCAGIAABKgAFjA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAkbA2IAAiXIAUAAIAACXg");
	this.shape_20.setTransform(1109.5,397.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#666666").s().p("Ah1BKQgSgZABgqQACgnAVgaQAVgZAhAAQAiAAASAYQAPAYgBAnQgBAVgIAPQgKAQgTAAQgIAAgEgFQgFgEgCgIQgFAIgFAFQgHAEgIAAQgLAAgHgMQgGgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgFA2QAAALADAFQACAEADAAQALAAAHgMQAGgLABgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgRAXgBAiQgCAkAPAWQAPAVAbAAQAIAAAIgCQAIgCAFgDIAEAKQgGAEgJADQgJACgJAAQgiAAgTgYgAhIgRQgFALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgHALgAjdBfIACgPIADAAIADABQAGAAAEgFQACgFACgHIAFgLIgihnIAVAAIAUBKIABAAIAVhKIAVAAIgmB4QgEALgGAIQgGAHgMAAgAAeBeIAAiQIARAAIABANQAEgHAHgEQAGgEAJAAQAQAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgQAAQgIAAgHgDQgFgDgFgGIAAAygAA5ghQgFAEgDAGIAAAzQADAGAFAEQAEADAHAAQAKAAAGgKQAFgKAAgRIAAgCQAAgQgFgLQgGgLgKAAQgHAAgEADgAnHBeIAAiQIAQAAIACANQAFgHAGgEQAGgEAJAAQAQAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgQAAQgJAAgFgDQgGgDgEgGIAAAygAmsghQgFAEgCAGIAAAzQACAGAFAEQAEADAHAAQAKAAAGgKQAFgKAAgRIAAgCQAAgQgFgLQgGgLgKAAQgHAAgEADgAI+ApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAALAPQALAPAAAWIAAACQAAAYgLAPQgLAPgTAAQgUAAgLgPgAJNgaQgGALAAAPIAAACQAAARAGALQAEALAMAAQALAAAFgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgKAAQgMAAgEALgAHaAqQgJgOAAgYIAAgCQAAgXAJgQQAKgPAQAAQAIAAAGAEQAGADAFAGIAAg6IATAAIAACXIgRAAIgBgNQgEAHgHAEQgGAEgJAAQgQAAgKgOgAHqgZQgFALAAAQIAAACQAAARAFAKQAFAJALAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgFgDgGAAQgLAAgFALgAFEApQgMgOAAgXIAAgEQABgWAKgPQAMgPASAAQASAAAKANQAIANABAVIAAAJIg6AAQAAARAGAKQAGAKAMAAQAIAAAHgDQAFgCAGgFIAGAMQgFAFgJAEQgJAEgKAAQgUAAgLgPgAFTgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgACGApQgKgPgBgYIAAgCQABgWAKgPQAMgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgMAPgSAAQgVAAgLgPgACVgaQgGALAAAPIAAACQAAARAGALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAk1AvQgHgIgBgPQAAgOALgJQALgHASAAIAQAAIAAgLQABgJgFgGQgEgFgJAAQgGAAgFAFQgEAEAAAIIgTAAIAAgBQgBgMALgJQAJgKARAAQAQAAAJAJQAKAKAAARIAAAvIABAMIADALIgUAAIgEgQQgEAIgHAFQgGAFgKAAQgOAAgHgJgAkjAKQgGAGAAAIQAAAIAEAEQADAFAHAAQAIAAAGgFQAGgFACgIIAAgSIgQAAQgKAAgEAFgAn3AwQgHgHABgQIAAg9IgPAAIAAgOIAPAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QgBAIADAEQADADAEAAIAGgBIACAOIgGACIgIABQgLAAgGgIgApWAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAEgEQAFgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQgBgNAKgIQAKgJAQAAQARAAAKAKQAJAJAAANIAAABIgTAAQgBgIgEgFQgFgFgHAAQgIAAgEAEQgEAEAAAGQAAAGADADQAEAEAMAFQARAFAIAHQAJAHgBAMQABANgKAJQgKAIgRAAQgSAAgKgKgAqvApQgLgOAAgXIAAgEQAAgWALgPQAMgPARAAQATAAAJANQAJANAAAVIAAAJIg5AAQAAARAFAKQAHAKAMAAQAIAAAGgDQAGgCAFgFIAGAMQgEAFgJAEQgJAEgLAAQgUAAgLgPgAqfgdQgFAIgCANIAlAAIAAgCQAAgMgDgHQgFgIgJAAQgJAAgEAIgAr7A0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgJAAgGgEgAr9ggQgFAEgCAGIAAAwQACAHAFAEQAFADAHAAQALAAAEgJQAGgKAAgRIAAgCQAAgQgGgLQgEgLgLAAQgHAAgFAEgAMFA2IAAg9QAAgQgEgHQgEgGgIAAQgHAAgFAFQgEAFgCAIIAAAEIAABEIgUAAIAAg9QAAgQgEgHQgFgGgHAAQgHAAgEADQgEAEgDAGIAABNIgUAAIAAhoIASAAIABAOQAEgHAIgFQAGgEAJAAQAJAAAGAFQAHAFADAKQAEgKAIgFQAGgFAJAAQAOAAAJALQAHALAAAXIAAA9gAGYA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAGAAIAHABIgCASIgJgBQgGAAgEAEQgEAEgCAGIAABKgAEaA2IgdgxIgHAAIAAAxIgVAAIAAiXIAVAAIAABZIAHAAIAYgqIAYAAIghAwIAkA4gAlkA2IAAiXIAUAAIAACXg");
	this.shape_21.setTransform(1116.9,397.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#666666").s().p("AiLBKQgTgZACgqQACgnAUgaQAVgZAhAAQAiAAASAYQASAYgCAnQAAAVgKAPQgLAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgGgMABgTQACgXALgPQAJgPAPAAQAKAAAGADQAFACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAHgMQAGgLABgSQABgjgOgUQgNgVgeAAQgbAAgRAWQgQAXgBAiQgCAkAOAWQAPAVAcAAQAIAAAHgCQAJgCAFgDIADAKQgGAEgIADQgJACgJAAQgiAAgTgYgAhegRQgGALgCATQAAAOACAIQADAIAGAAQAHAAAEgEQAFgDADgIIAAgBIAAgCIAFgyIgKgDQgLAAgGALgAj0BfIACgPIAEAAIACABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIAUBKIAAAAIAVhKIAWAAIgmB4QgEALgGAIQgGAHgNAAgAAHBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAAighQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKABgRIAAgCQgBgQgFgLQgFgLgLAAQgGAAgFADgAneBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQARAAAJAPQAJAQAAAXIAAACQAAAYgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAygAnDghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAGgKAAgRIAAgCQAAgQgGgLQgFgLgLAAQgGAAgFADgAIoApQgMgPAAgYIAAgCQAAgWAMgPQALgPATAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgLAPgUAAQgTAAgLgPgAI2gaQgGALABAPIAAACQgBARAGALQAFALALAAQALAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAHEAqQgKgOABgYIAAgCQgBgXAKgQQAKgPAQAAQAIAAAFAEQAGADAFAGIAAg6IATAAIAACXIgQAAIgCgNQgEAHgHAEQgGAEgIAAQgRAAgJgOgAHTgZQgEALAAAQIAAACQAAARAEAKQAGAJAKAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgEgDgHAAQgKAAgGALgAEtApQgLgOAAgXIAAgEQAAgWALgPQAMgPARAAQATAAAJANQAJANAAAVIAAAJIg5AAQAAARAFAKQAHAKAMAAQAIAAAGgDQAGgCAFgFIAGAMQgEAFgJAEQgJAEgLAAQgUAAgLgPgAE9gdQgFAIgCANIAlAAIAAgCQAAgMgDgHQgFgIgJAAQgJAAgEAIgABwApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAAMAPQAKAPAAAWIAAACQAAAYgKAPQgMAPgTAAQgUAAgLgPgAB/gaQgGALAAAPIAAACQAAARAGALQAEALAMAAQAKAAAGgLQAGgLAAgRIAAgCQAAgPgGgLQgGgLgLAAQgLAAgEALgAlMAvQgHgIAAgPQAAgOALgJQAKgHATAAIAQAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAKAKgBARIAAAvIABAMIADALIgUAAIgDgQQgEAIgHAFQgHAFgJAAQgOAAgIgJgAk6AKQgGAGABAIQAAAIADAEQAEAFAGAAQAIAAAHgFQAGgFACgIIAAgSIgQAAQgKAAgFAFgAoNAwQgHgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIADAEQACADAEAAIAGgBIACAOIgFACIgIABQgMAAgFgIgAptAuQgJgKgBgNIABgBIASAAQABAKAGAFQAEAEAIAAQAJAAAEgEQAFgEgBgGQAAgGgDgEQgEgEgNgGQgPgGgJgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgEgFQgFgFgIAAQgHAAgFAEQgDAEAAAGQgBAGAEADQAEAEAMAFQARAFAIAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgArFApQgMgOAAgXIAAgEQABgWAKgPQAMgPASAAQASAAAKANQAIANABAVIAAAJIg6AAQAAARAGAKQAGAKAMAAQAIAAAHgDQAFgCAGgFIAGAMQgFAFgJAEQgJAEgKAAQgUAAgLgPgAq2gdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAsRA0QgHgEgEgHIgCANIgQAAIAAiXIAUAAIAAA7QADgHAGgDQAHgEAIAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgJAAgGgEgAsTggQgFAEgCAGIAAAwQACAHAFAEQAFADAGAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFAEgAMcA2IAAgUIATAAIAAAUgALvA2IAAg9QAAgQgFgHQgDgGgJAAQgGAAgFAFQgEAFgDAIIAAAEIAABEIgTAAIAAg9QAAgQgFgHQgEgGgIAAQgGAAgEADQgFAEgDAGIAABNIgTAAIAAhoIASAAIAAAOQAFgHAHgFQAGgEAKAAQAJAAAGAFQAHAFADAKQADgKAIgFQAHgFAJAAQAOAAAIALQAHALAAAXIAAA9gAGBA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAHAAIAHABIgDASIgJgBQgGAAgEAEQgEAEgCAGIAABKgAEDA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAl7A2IAAiXIAUAAIAACXg");
	this.shape_22.setTransform(1119.1,397.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#666666").s().p("Ai8BKQgTgZACgqQACgnAUgaQAVgZAhAAQAiAAASAYQASAYgCAnQgBAVgKAPQgKAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgHgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAGgMQAHgLAAgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgQAXgCAiQgBAkAOAWQAPAVAcAAQAHAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgIAAQgjAAgSgYgAiPgRQgGALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgGALgAklBfIACgPIADAAIADABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEALgGAIQgHAHgMAAgAgoBeIAAiQIARAAIABANQAFgHAGgEQAGgEAHAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgGAAgGgDQgGgDgEgGIAAAygAgNghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQAJAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgJAAQgGAAgFADgAoPBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAn0ghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgAMfApQgKgPAAgXIAAgDQAAgWAKgPQALgPATAAQAQAAAKALQAKALAAARIAAAAIgSAAQAAgKgFgHQgFgHgIAAQgLAAgFALQgFALAAAPIAAADQAAAQAFALQAFALALAAQAIAAAFgGQAFgGAAgJIARAAIABAAQAAAPgKALQgLAKgPAAQgTAAgLgPgAH2ApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgAIFgaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgAGTAqQgKgOAAgYIAAgCQAAgXAKgQQAJgPARAAQAHAAAGAEQAGADAFAGIAAg6IATAAIAACXIgQAAIgCgNQgEAHgHAEQgGAEgIAAQgRAAgJgOgAGigZQgFALAAAQIAAACQAAARAFAKQAFAJALAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgFgDgGAAQgLAAgFALgAD8ApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgAELgdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgAA/ApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgLAPgTAAQgUAAgLgPgABNgaQgFALAAAPIAAACQAAARAFALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAl9AvQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAJAKAAARIAAAvIABAMIADALIgUAAIgDgQQgFAIgGAFQgHAFgJAAQgOAAgIgJgAlrAKQgGAGAAAIQAAAIAEAEQAEAFAGAAQAIAAAGgFQAHgFACgIIAAgSIgRAAQgJAAgFAFgAo/AwQgGgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHABQgMAAgGgIgAqeAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAJAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAr2ApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgArngdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAtDA0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAtEggQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgHAAgEAEgALqA2IAAgUIAUAAIAAAUgAK9A2IAAg9QAAgQgEgHQgEgGgIAAQgHAAgEAFQgFAFgCAIIAAAEIAABEIgUAAIAAg9QAAgQgEgHQgEgGgIAAQgGAAgFADQgEAEgDAGIAABNIgUAAIAAhoIASAAIABAOQAFgHAHgFQAGgEAJAAQAJAAAHAFQAGAFADAKQAEgKAIgFQAGgFAKAAQAOAAAIALQAHALAAAXIAAA9gAFQA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAHAAIAGABIgCASIgJgBQgGAAgEAEQgEAEgCAGIAABKgADSA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAmsA2IAAiXIAUAAIAACXg");
	this.shape_23.setTransform(1124,397.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#666666").s().p("AjtBKQgTgZACgqQACgnAUgaQAVgZAhAAQAiAAASAYQASAYgCAnQgBAVgKAPQgKAQgTAAQgHAAgFgFQgFgEgCgIQgEAIgGAFQgGAEgIAAQgMAAgGgMQgHgMACgTQACgXAKgPQAKgPAPAAQAKAAAFADQAGACAHAFIAAABIAAAAIgEA2QgBALADAFQACAEAEAAQALAAAGgMQAHgLAAgSQACgjgOgUQgOgVgdAAQgbAAgRAWQgQAXgCAiQgBAkAOAWQAPAVAcAAQAHAAAIgCQAIgCAGgDIADAKQgGAEgJADQgJACgIAAQgjAAgSgYgAjAgRQgGALgCATQgBAOADAIQADAIAGAAQAGAAAFgEQAEgDAEgIIAAgBIAAgCIAEgyIgKgDQgKAAgGALgAlWBfIACgPIADAAIADABQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEALgGAIQgHAHgMAAgAhZBeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAg+ghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgApABeIAAiQIARAAIABANQAFgHAGgEQAGgEAJAAQAQAAAKAPQAJAQAAAXIAAACQAAAYgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAygAolghQgFAEgCAGIAAAzQACAGAFAEQAFADAGAAQALAAAFgKQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgGAAgFADgANJApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgANYgaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgALuApQgKgPAAgXIAAgDQAAgWAKgPQALgPATAAQAQAAAKALQAKALAAARIAAAAIgSAAQAAgKgFgHQgFgHgIAAQgLAAgFALQgFALAAAPIAAADQAAAQAFALQAFALALAAQAIAAAFgGQAFgGAAgJIARAAIABAAQAAAPgKALQgLAKgPAAQgTAAgLgPgAHFApQgLgPAAgYIAAgCQAAgWALgPQALgPAUAAQATAAAMAPQALAPAAAWIAAACQAAAYgLAPQgMAPgTAAQgUAAgLgPgAHUgaQgGALAAAPIAAACQAAARAGALQAFALALAAQALAAAFgLQAGgLAAgRIAAgCQAAgPgGgLQgFgLgLAAQgLAAgFALgAFiAqQgKgOAAgYIAAgCQAAgXAKgQQAJgPARAAQAHAAAGAEQAGADAFAGIAAg6IATAAIAACXIgQAAIgCgNQgEAHgHAEQgGAEgIAAQgRAAgJgOgAFxgZQgFALAAAQIAAACQAAARAFAKQAFAJALAAQAGAAAFgDQAFgEADgGIAAgxQgDgHgFgEQgFgDgGAAQgLAAgFALgADLApQgLgOAAgXIAAgEQAAgWALgPQALgPASAAQASAAAKANQAJANAAAVIAAAJIg5AAQAAARAFAKQAGAKAMAAQAJAAAGgDQAGgCAFgFIAGAMQgFAFgIAEQgJAEgLAAQgUAAgLgPgADagdQgFAIgBANIAlAAIAAgCQAAgMgEgHQgEgIgJAAQgJAAgFAIgAAOApQgLgPAAgYIAAgCQAAgWALgPQALgPATAAQAUAAALAPQALAPAAAWIAAACQAAAYgLAPQgLAPgTAAQgUAAgLgPgAAcgaQgFALAAAPIAAACQAAARAFALQAFALAMAAQAKAAAGgLQAFgLAAgRIAAgCQAAgPgFgLQgGgLgLAAQgLAAgFALgAmuAvQgHgIAAgPQAAgOAKgJQALgHASAAIARAAIAAgLQAAgJgFgGQgEgFgIAAQgHAAgEAFQgFAEAAAIIgTAAIAAgBQgBgMALgJQAKgKAQAAQAQAAAKAJQAJAKAAARIAAAvIABAMIADALIgUAAIgDgQQgFAIgGAFQgHAFgJAAQgOAAgIgJgAmcAKQgGAGAAAIQAAAIAEAEQAEAFAGAAQAIAAAGgFQAHgFACgIIAAgSIgRAAQgJAAgFAFgApwAwQgGgHAAgQIAAg9IgOAAIAAgOIAOAAIAAgaIAUAAIAAAaIAQAAIAAAOIgQAAIAAA9QAAAIACAEQADADAEAAIAGgBIACAOIgGACIgHABQgMAAgGgIgArPAuQgKgKAAgNIABgBIASAAQABAKAFAFQAFAEAIAAQAIAAAFgEQAEgEAAgGQAAgGgEgEQgEgEgMgGQgQgGgIgFQgIgHAAgLQAAgNAKgIQAKgJAPAAQARAAAKAKQAKAJgBANIAAABIgTAAQAAgIgFgFQgEgFgIAAQgHAAgFAEQgEAEAAAGQAAAGAEADQADAEANAFQAQAFAJAHQAIAHAAAMQAAANgKAJQgKAIgRAAQgSAAgKgKgAsnApQgMgOAAgXIAAgEQAAgWALgPQAMgPASAAQASAAAJANQAJANAAAVIAAAJIg5AAQAAARAGAKQAGAKAMAAQAIAAAGgDQAGgCAGgFIAGAMQgFAFgJAEQgJAEgLAAQgTAAgLgPgAsYgdQgFAIgCANIAmAAIAAgCQAAgMgEgHQgFgIgIAAQgJAAgFAIgAt0A0QgGgEgEgHIgDANIgQAAIAAiXIAUAAIAAA7QAEgHAGgDQAGgEAIAAQARAAAJAPQAKAQAAAXIAAACQAAAYgKAOQgJAOgRAAQgIAAgHgEgAt1ggQgFAEgDAGIAAAwQADAHAFAEQAEADAHAAQALAAAFgJQAFgKAAgRIAAgCQAAgQgFgLQgFgLgLAAQgHAAgEAEgAK5A2IAAgUIAUAAIAAAUgAKMA2IAAg9QAAgQgEgHQgEgGgIAAQgHAAgEAFQgFAFgCAIIAAAEIAABEIgUAAIAAg9QAAgQgEgHQgEgGgIAAQgGAAgFADQgEAEgDAGIAABNIgUAAIAAhoIASAAIABAOQAFgHAHgFQAGgEAJAAQAJAAAHAFQAGAFADAKQAEgKAIgFQAGgFAKAAQAOAAAIALQAHALAAAXIAAA9gAEfA2IAAhoIASAAIABAQQAEgJAFgEQAGgFAHAAIAGABIgCASIgJgBQgGAAgEAEQgEAEgCAGIAABKgAChA2IgdgxIgHAAIAAAxIgUAAIAAiXIAUAAIAABZIAHAAIAZgqIAXAAIggAwIAkA4gAndA2IAAiXIAUAAIAACXg");
	this.shape_24.setTransform(1128.9,397.6);

	this.instance_1 = new lib.Символ20();
	this.instance_1.setTransform(1136.3,397.6,1,1,0,0,0,98.8,9.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},70).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},2).to({state:[{t:this.shape_8}]},2).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},2).to({state:[{t:this.shape_11}]},2).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},2).to({state:[{t:this.shape_15}]},2).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},2).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},2).to({state:[{t:this.shape_21}]},2).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},3).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.instance_1}]},2).wait(48));

	// Слой 6
	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#666666").s().p("AAgBHIAAh+IgnAAIAAAyQAAAngJATQgKASgVAAIgEAAIAAgPIADAAQAMAAAFgOQAEgNAAgiIABhAIBOAAIAACMg");
	this.shape_25.setTransform(1041.7,277.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#666666").s().p("AAYBaIACgOIADAAIADAAQAGAAAEgFQADgFACgGIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEAKgGAIQgHAIgMAAgAgQAxIAAh9IgoAAIAAAyQAAAngKASQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgNQAFgOAAghIAAhBIBOAAIAACMg");
	this.shape_26.setTransform(1046.7,279.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#666666").s().p("AgSBaIACgOIAEAAIACAAQAGAAAEgFQABgFACgGIAEgLIgghnIAWAAIARBKIABAAIAVhKIAWAAIgmB4QgEAKgGAIQgHAIgKAAgAB9AxIAAgmIgIACIgJABQgSAAgKgKQgKgIAAgVIAAgdIAUAAIAAAdQAAAOAFAGQAEAFAJAAIAJAAIAIgCIAAg0IAUAAIAABngAg8AxIAAh9IgoAAIAAAyQAAAngKASQgKASgUAAIgEAAIAAgPIADAAQAMAAAEgNQAFgOAAghIABhBIBQAAIAACMg");
	this.shape_27.setTransform(1051.1,279.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#666666").s().p("AhYBaIACgOIADAAIADAAQAGAAAEgFQADgFACgGIAEgLIgihnIAWAAIATBKIABAAIAVhKIAVAAIglB4QgEAKgGAIQgHAIgMAAgABhAxIAAhnIAUAAIAABYIAdAAIAAhYIAUAAIAABYIAdAAIAAhYIAUAAIAABngAA3AxIAAgmIgIACIgJABQgSAAgKgKQgKgIAAgVIAAgdIAUAAIAAAdQAAAOAEAGQAFAFAJAAIAJAAIAIgCIAAg0IAUAAIAABngAiCAxIAAh9IgoAAIAAAyQAAAngKASQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgNQAFgOAAghIAAhBIBQAAIAACMg");
	this.shape_28.setTransform(1058.1,279.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#666666").s().p("AiJBaIACgOIADAAIADAAQAGAAAEgFQADgFABgGIAFgLIgihnIAVAAIAUBKIAAAAIAWhKIAVAAIgmB4QgEAKgGAIQgGAIgMAAgAD1AxIAAhGIgBAAIgkBGIgUAAIAAhnIAUAAIAABGIABAAIAkhGIAUAAIAABngAAvAxIAAhnIAVAAIAABYIAdAAIAAhYIAUAAIAABYIAdAAIAAhYIAUAAIAABngAAGAxIAAgmIgGACIgJABQgTAAgJgKQgLgIABgVIAAgdIAUAAIAAAdQAAAOAEAGQAFAFAJAAIAJAAIAGgCIAAg0IATAAIAABngAizAxIAAh9IgoAAIAAAyQAAAngKASQgKASgVAAIgDAAIAAgPIACAAQANAAAEgNQAFgOgBghIABhBIBQAAIAACMg");
	this.shape_29.setTransform(1063,279.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#666666").s().p("Ai6BeIACgOIADAAIADAAQAGAAAEgFQADgFABgHIAFgLIgihnIAVAAIAUBLIAAAAIAWhLIAVAAIgmB5QgEAKgGAIQgGAIgMAAgAEmA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogADEA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIAUAAIAABogAAAA1IAAhoIATAAIAABZIAdAAIAAhZIAUAAIAABZIAdAAIAAhZIAUAAIAABogAgpA1IAAgmIgIABIgJABQgTABgJgLQgLgHABgVIAAgeIAUAAIAAAeQAAAOAEAGQAFADAJAAIAJgBIAIgBIAAgzIATAAIAABogAjkA1IAAh9IgoAAIAAAyQAAAmgKATQgKASgVAAIgDAAIAAgPIACAAQANAAAEgNQAFgOgBghIABhBIBQAAIAACMgAD/hLQgHgHAAgLIAAgCIAPAAQAAAHADAFQADADAGAAQAHAAADgEQADgEAAgHIAPAAIAAACQABALgIAHQgIAHgNAAQgNAAgHgHg");
	this.shape_30.setTransform(1067.9,279.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#666666").s().p("AkBBeIACgOIADAAIADAAQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBLIABAAIAVhLIAVAAIglB5QgEAKgGAIQgHAIgMAAgAFtA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogADfA1IAAhGIgBAAIgjBGIgUAAIAAhoIAUAAIAABGIAAAAIAkhGIAUAAIAABogAB9A1IAAhGIgBAAIgjBGIgUAAIAAhoIAUAAIAABGIAAAAIAkhGIAUAAIAABogAhGA1IAAhoIAUAAIAABZIAdAAIAAhZIAUAAIAABZIAbAAIAAhZIAUAAIAABogAhwA1IAAgmIgIABIgJABQgSABgKgLQgKgHAAgVIAAgeIAUAAIAAAeQAAAOAEAGQAFADAJAAIAJgBIAIgBIAAgzIAUAAIAABogAkrA1IAAh9IgoAAIAAAyQAAAmgKATQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgNQAFgOAAghIAAhBIBQAAIAACMgAC4hLQgHgHAAgLIABgCIAOAAQAAAHADAFQADADAHAAQAGAAADgEQADgEAAgHIAPAAIABACQAAALgIAHQgHAHgNAAQgNAAgIgHg");
	this.shape_31.setTransform(1075,279.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#666666").s().p("AkqBeIACgOIADAAIADAAQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBLIABAAIAVhLIAVAAIglB5QgEAKgGAIQgHAIgMAAgAFtA1IAAhoIA8AAIAAAPIgoAAIAABZgAFEA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogAC2A1IAAhGIgBAAIgjBGIgUAAIAAhoIAUAAIAABGIAAAAIAkhGIAUAAIAABogABUA1IAAhGIgBAAIgjBGIgUAAIAAhoIAUAAIAABGIAAAAIAkhGIAUAAIAABogAhvA1IAAhoIAUAAIAABZIAdAAIAAhZIAUAAIAABZIAdAAIAAhZIASAAIAABogAiZA1IAAgmIgIABIgJABQgSABgKgLQgKgHAAgVIAAgeIAUAAIAAAeQAAAOAEAGQAFADAJAAIAJgBIAIgBIAAgzIAUAAIAABogAlUA1IAAh9IgoAAIAAAyQAAAmgKATQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgNQAFgOAAghIAAhBIBQAAIAACMgACPhLQgHgHAAgLIABgCIAOAAQAAAHADAFQADADAHAAQAGAAADgEQADgEAAgHIAPAAIABACQAAALgIAHQgHAHgNAAQgNAAgIgHg");
	this.shape_32.setTransform(1079.1,279.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#666666").s().p("AlYBeIACgOIADAAIADAAQAGAAAEgFQADgFACgHIAEgLIgihnIAWAAIATBLIABAAIAVhLIAVAAIglB5QgEAKgGAIQgHAIgMAAgAGIBeIAAiRIARAAIACANQAEgHAGgEQAHgDAIgBQARABAJAPQAJAPAAAXIAAADQAAAXgJAOQgJAOgRAAQgIAAgGgDQgGgDgEgGIAAAzgAGjgiQgEAEgDAGIAAAzQADAHAEADQAFADAHAAQAKAAAFgKQAGgKAAgQIAAgDQAAgQgGgLQgFgLgKAAQgHAAgFADgAE/A1IAAhoIA8AAIAAAPIgoAAIAABZgAEWA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogACIA1IAAhGIgBAAIgjBGIgUAAIAAhoIAUAAIAABGIAAAAIAkhGIAUAAIAABogAAmA1IAAhGIgBAAIgjBGIgSAAIAAhoIASAAIAABGIAAAAIAkhGIAUAAIAABogAidA1IAAhoIAUAAIAABZIAdAAIAAhZIAUAAIAABZIAdAAIAAhZIAUAAIAABogAjHA1IAAgmIgIABIgJABQgSABgKgLQgKgHAAgVIAAgeIAUAAIAAAeQAAAOAEAGQAFADAJAAIAJgBIAIgBIAAgzIAUAAIAABogAmCA1IAAh9IgoAAIAAAyQAAAmgKATQgKASgVAAIgDAAIAAgPIADAAQAMAAAEgNQAFgOAAghIAAhBIBQAAIAACMgABhhLQgHgHAAgLIABgCIAOAAQAAAHADAFQADADAHAAQAGAAADgEQADgEAAgHIAPAAIABACQAAALgIAHQgHAHgNAAQgNAAgIgHg");
	this.shape_33.setTransform(1083.7,279.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#666666").s().p("AmJBeIACgOIADAAIADAAQAGAAAEgFQADgFABgHIAFgLIgihnIAVAAIAUBLIAAAAIAWhLIAVAAIgmB5QgEAKgGAIQgGAIgMAAgAFXBeIAAiRIARAAIACANQAEgHAGgEQAGgDAJgBQAQABAKAPQAJAPAAAXIAAADQAAAXgJAOQgKAOgQAAQgIAAgGgDQgGgDgEgGIAAAzgAFygiQgEAEgDAGIAAAzQADAHAEADQAFADAGAAQALAAAFgKQAGgKgBgQIAAgDQABgQgGgLQgFgLgLAAQgGAAgFADgAHAAoQgLgPAAgYIAAgBQAAgWALgPQALgPAUgBQATABALAPQALAPAAAWIAAABQAAAYgLAPQgLAPgTAAQgUAAgLgPgAHPgbQgGALAAAQIAAABQAAASAGAKQAEALAMAAQALAAAFgLQAGgKgBgSIAAgBQABgQgGgLQgGgLgKABQgMgBgEALgAEOA1IAAhoIA8AAIAAAPIgoAAIAABZgADlA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogABXA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIATAAIAABogAgJA1IAAhGIgBAAIgkBGIgUAAIAAhoIAUAAIAABGIABAAIAkhGIASAAIAABogAjPA1IAAhoIAVAAIAABZIAdAAIAAhZIAUAAIAABZIAdAAIAAhZIAUAAIAABogAj4A1IAAgmIgIABIgJABQgTABgJgLQgLgHABgVIAAgeIAUAAIAAAeQAAAOAEAGQAFADAJAAIAJgBIAIgBIAAgzIATAAIAABogAmzA1IAAh9IgoAAIAAAyQAAAmgKATQgKASgVAAIgDAAIAAgPIACAAQANAAAEgNQAFgOgBghIABhBIBQAAIAACMgAAwhLQgHgHAAgLIAAgCIAPAAQAAAHADAFQADADAGAAQAHAAADgEQADgEAAgHIAPAAIAAACQABALgIAHQgIAHgNAAQgNAAgHgHg");
	this.shape_34.setTransform(1088.6,279.1);

	this.instance_2 = new lib.Символ21();
	this.instance_2.setTransform(1093.6,279.1,1,1,0,0,0,57.1,9.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_25}]},49).to({state:[{t:this.shape_26}]},2).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},2).to({state:[{t:this.shape_29}]},2).to({state:[{t:this.shape_30}]},2).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},2).to({state:[{t:this.shape_32}]},2).to({state:[{t:this.shape_33}]},2).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.instance_2}]},2).wait(82));

	// Символ 6
	this.instance_3 = new lib.Символ6();
	this.instance_3.setTransform(1165.8,667.8,1,1,0,0,0,213,45);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(18).to({_off:false},0).to({y:636.8,alpha:1},9,cjs.Ease.get(1)).wait(123));

	// Символ 10
	this.instance_4 = new lib.Символ10();
	this.instance_4.setTransform(1023.8,517.4,1,1,0,0,0,205,34.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({x:1165.8,alpha:1},9,cjs.Ease.get(1)).wait(132));

	// Символ 9
	this.instance_5 = new lib.Символ9();
	this.instance_5.setTransform(1023.8,396.9,1,1,0,0,0,205,34.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(4).to({_off:false},0).to({x:1165.8,alpha:1},9,cjs.Ease.get(1)).wait(137));

	// Символ 8
	this.instance_6 = new lib.Символ8();
	this.instance_6.setTransform(1023.8,278.4,1,1,0,0,0,205,34.9);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({x:1165.8,alpha:1},9,cjs.Ease.get(1)).wait(141));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(818.7,243.5,320,69.8);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgbSgtmMA2kgADMgADBbTMg2hAAAg");
	mask.setTransform(338.7,224.9);

	// 3
	this.instance = new lib.Символ24();
	this.instance.setTransform(-685.8,229.6,1,1,0,0,0,303,139);
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(300).to({_off:false},0).wait(200));

	// 2
	this.instance_1 = new lib.Символ22();
	this.instance_1.setTransform(969.5,219.5,1,1,0,0,0,218.5,281.5);
	this.instance_1._off = true;

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(150).to({_off:false},0).to({x:164.5,y:220},9,cjs.Ease.get(1)).to({x:180},5,cjs.Ease.get(1)).wait(125).to({x:-726.7,y:219.5},10,cjs.Ease.get(-1)).to({_off:true},1).wait(200));

	// 1
	this.instance_2 = new lib.Символ7();
	this.instance_2.setTransform(-569.7,-44.6,1,1,0,0,0,213,121);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(139).to({x:-1448.1},10,cjs.Ease.get(-1)).to({_off:true},1).wait(350));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(164,77.9,192,69.8);


// stage content:



(lib.mobile_animation = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.logo();
	this.instance.setTransform(59.5,113);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ40();
	this.instance_1.setTransform(74.9,312,0.674,0.674,0,0,0,219.4,242);

	this.instance_2 = new lib.mob();
	this.instance_2.setTransform(1,34);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(111.2,334,369.8,548);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;