(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1480587114252", id:"bg"},
		{src:"images/iconsgame.jpg?1480587114252", id:"iconsgame"},
		{src:"images/logo.png?1480587114252", id:"logo"},
		{src:"images/machine.jpg?1480587114252", id:"machine"},
		{src:"images/man.png?1480587114252", id:"man"},
		{src:"images/ВамвыпалоlinesИзображение.png?1480587114252", id:"ВамвыпалоlinesИзображение"},
		{src:"images/СпиновRectangle5Изображение.png?1480587114252", id:"СпиновRectangle5Изображение"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,800,300);


(lib.iconsgame = function() {
	this.initialize(img.iconsgame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,84,420);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,136,98);


(lib.machine = function() {
	this.initialize(img.machine);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,396,523);


(lib.man = function() {
	this.initialize(img.man);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,432,188);


(lib.ВамвыпалоlinesИзображение = function() {
	this.initialize(img.ВамвыпалоlinesИзображение);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,289,33);


(lib.СпиновRectangle5Изображение = function() {
	this.initialize(img.СпиновRectangle5Изображение);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,176,34);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,800,300);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.man();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,432,188);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EhB0AbbMAAAg21MCDpAAAMAAAA21g");
	this.shape.setTransform(421.3,175.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,842.7,351);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(3,1,1).p("Al3mKILvAAIAAMVIrvAAg");
	this.shape.setTransform(37.7,39.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,78.4,82);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(3,1,1).p("Al3mKILvAAIAAMVIrvAAg");
	this.shape.setTransform(37.7,39.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,78.4,82);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(3,1,1).p("Al3mKILvAAIAAMVIrvAAg");
	this.shape.setTransform(37.7,39.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,78.4,82);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFF00").ss(3,1,1).p("Al3mKILvAAIAAMVIrvAAg");
	this.shape.setTransform(37.7,39.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.5,-1.5,78.4,82);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.iconsgame();
	this.instance.parent = this;
	this.instance.setTransform(0,-383,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.iconsgame();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-383,76.9,767.2);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.iconsgame();
	this.instance.parent = this;
	this.instance.setTransform(-1,-382,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.iconsgame();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-1,0,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-382,76.9,766.2);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.iconsgame();
	this.instance.parent = this;
	this.instance.setTransform(-1,-382,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.iconsgame();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-1,0,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-382,76.9,766.2);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.iconsgame();
	this.instance.parent = this;
	this.instance.setTransform(0,-382,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.iconsgame();
	this.instance_1.parent = this;
	this.instance_1.setTransform(1,0,0.915,0.915);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-382,77.9,766.2);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.machine();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.825,0.825);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,326.7,431.5);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiDBRIAAgWIAKAAQALAAAFgKIAGgNIg3hzIAeAAIAmBSIAghSIAfAAIg9CNQgLAUgYAAgAmwBIQgPgKgIgRQgIgSAAgXIAAgHQAAgXAIgSQAIgSAPgKQAPgJAUAAQAUAAAPAJQAPAKAIARQAIASAAAXIAAAHQABAYgJASQgIARgPAKQgPAKgUAAQgUAAgPgKgAmpgsQgLAOAAAaIAAAHQAAAbALAOQAKAPASAAQASAAAKgPQAKgOAAgbIAAgGQAAgagKgPQgKgOgSAAQgSAAgKAOgAJQBNQgDgEAAgGQgBgGAFgFQAEgEAGAAQAIAAAEAEQAEAFAAAGQAAAGgEAEQgEAEgIAAQgGAAgFgEgAG/BPIAAieIAcAAIAAA+IAhAAQARAAANAGQANAGAHAIQAHAMAAAOQAAAXgPANQgPAOgaAAgAHbA5IAhAAQAOAAAHgIQAJgHgBgNQABgMgJgHQgHgHgNAAIgiAAgAFdBPIAAiIIgxAAIAAgWIB/AAIAAAWIgyAAIAACIgAD6BPIAAhwIhHBwIgcAAIAAieIAcAAIAABwIBHhwIAbAAIAACegABaBPIAAg/QgRAFgUAAQgdAAgOgNQgMgKAAgaIAAgzIAZAAIAAAzQAAAPAHAHQAHAGAQAAQAUAAARgEIAAhLIAdAAIAACegAjNBPIAAiIIgxAAIgCA8QgCAdgGARQgFAQgLAHQgKAHgSAAIgHAAIAAgWIAFgBQAKAAAEgGQAGgGADgMQADgMABgVIAChOIBoAAIAACegAoIBPIAAiIIhGAAIAACIIgcAAIAAieIB/AAIAACegAJQAgIgChvIAcAAIgDBvg");
	this.shape.setTransform(62,8.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,123.9,16.5);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("Av2i5IftAAQAYAAAPAKQAVAOAAAkIAAD7QAAA8g8AAI/tAAQgXAAgOgJQgXgOAAglIAAj7QAAg8A8AAg");
	this.shape.setTransform(107.5,18.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#E11E4C","#F42686"],[0.4,0.443],0,19.2,0,-19.1).s().p("Av2C6QgYAAgPgKQgVgOAAgkIAAj7QAAg8A8AAIftAAQAXAAAPAJQAUAOAAAkIAAD7QAAA8g8AAI/sAAQgYAAgOgJQAOAJAYAAIfsAAQA8AAAAg8IAAj7QAAgkgUgOQAWAOAAAlIAAD7QAAA8g8AAgAQdiwIAAAAg");
	this.shape_1.setTransform(107.7,18.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,217.1,39.4);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,136,98);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AKCCQQgbgVAAgkQAAgoAbgTQAWgPAfAAQAYgBATAHQASAHAJALIAAgXQABgNgLgHQgMgHgVgBQgQABgQAFQgSAHgOAIIgcgzQAWgRAfgKQAbgHAcgBQB0ABgCBeIAACNIhXAAIAAgXQgKANgSAHQgUAJgWgBQgeABgXgTgAK+BWQAAATAeAAQAZAAAJgMIAAgOQgJgMgZAAQgeAAAAATgAxGCQQgbgVAAgkQAAgoAbgTQAWgPAfAAQAXgBAUAHQASAHAKALIAAgXQAAgNgLgHQgMgHgUgBQgQABgRAFQgSAHgOAIIgcgzQAVgRAggKQAbgHAcgBQBzABAABeIAACNIhXAAIAAgXQgKANgTAHQgTAJgXgBQgdABgYgTgAwJBWQAAATAeAAQAZAAAJgMIAAgOQgJgMgZAAQgeAAAAATgAS6B9QgigiAAgyQAAgxAigiQAkglA8AAQA8ABAlAjQAiAiAAAxQAAAzgiAiQgmAlg7AAQg8AAgkglgAT8AIQgLANAAAUQAAATALANQALANATABQATgBAMgNQAKgNABgTQAAgUgLgNQgMgKgTAAQgTAAgLAKgAN1BbQANAAAIgLQAIgNAEggIAShsIDPAAIAADmIhVAAIAAidIgwAAIgIAvQgHA4gaAcQgdAfg3AAgAg8CdIAAjmIBVAAIAABGIBJAAQAqgBAYAWQAWAXABAkQgBAigXAWQgZAYgoAAgAAZBZIA4AAQAIAAAGgDQAFgFAAgEQAAgHgFgEQgFgEgJAAIg4AAgAHyCdIAAidIhHAAIAACdIhWAAIAAjmIDzAAIAADmgADOCdIAAjmIBXAAIAADmgAllCdIAAjmICoAAQAlAAAUATQATARAAAXQAAATgMANQgKANgSAGQAUAEAMAPQANAQAAAWQAAAZgTASQgVATglABgAkNBdIA+AAQAFAAAEgDQADgEAAgEQAAgLgMAAIg+AAgAkNAIIA6AAQAFAAADgDQAEgDAAgCQAAgEgEgDQgDgDgFAAIg6AAgApkCdIAAh+IgtB+IgvAAIgth/IAAB/IhWAAIAAjmIByAAIAnBtIAqhtIBxAAIAADmgA2cCdIAAk/IDDAAQAtABAbAaQAXAYAAAfQAAAcgQAVQgPATgYAFQAZAFASATQASAWAAAfQAAAkgXAYQgbAbgtAAgA07BNIBOAAQAKAAAGgGQAGgGABgJQAAgIgGgGQgGgHgLAAIhOAAgA07gsIBLAAQAIAAAGgEQAFgHAAgIQAAgIgFgFQgHgFgHAAIhMAAg");
	mask.setTransform(144.5,16.8);

	// Слой 3
	this.instance = new lib.ВамвыпалоlinesИзображение();
	this.instance.parent = this;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.7,0.5,287.5,32.6);


(lib._1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A0yFFQgRgPgDgFIgGgHIgEgDIgegeIgBAAIgxAKIgeAoIgegUIgKgoIgogoIgKhQQgBivABiPQABhZBUgiQArgSAqABQBJACBXgCQA7gCA8AjQAwAcAhAnQAkgOALgCQAagGARAMQAZAQATACQAcADAmgVQAkgUA0AIQAdAFA1ARQAigXBUAOQBNAMAtAbQANgWBNgcQBYggBHAWQAnAMAqAcQAYgTAJgCQAdgKA4ALQA7ALAQAHQALAFAYARQAVgRAfgMQAngQAdAFQAWAEAWALQARAFAdgUQAggWBTADQBLADAeAQQAbAOAeABQAhABAegQQAcgPArAHQAeAFAdANQAgAPAKABQAcAEAogUQAqgVBsAHQBhAHArARQAOgCAegKQAcgIAIAAQBXAJA9AkQBjA6ANB1QARCRhWBFQgcAXgpAPIg0AQQhXAghVgHQhKgPgOAAQg1gBg5gTQgUAJglAGIgrAFQgHABgIgFQgLgGgEAAQgRAKgUABIghgBQgLAAgMgHQgLgGgGADQgWAJgmABQgSAAgQgHIgagNQgMAIgjAHIghAFIhuAAQgXAAgigGQgkgGgRgIQgQAPgvAEQgdACgcgBQgHAAgPgHQgMgGgGADQgLAGgPABQgZADg7AAQhegBhUgTQgjAQhOACQhCABgzgJQgmgHgRgMQgLgIgOgXIgNAPQgMAMgZANQgqAXhYgDIg2gEQgkgDgUAHQgWAHgngFQgkgFgNgHQgHgHgCAAIgVAHQgVAHhYAAQgIALgDACQgdAWgfAIQgMADgcgXIgUgKIgeAKIgFAIIgMAOQghgOAAACIgigJQgCgDgEgIIgbgJIgEAAIgnAnIgeAUg");
	this.shape.setTransform(156.2,32.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,312.4,65);


(lib.ClipGroup_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("As1B3QgzgvAAhIQAAhIAzguQAxguBMAAQA5AAAnAeQAgAXARAoIhVAnQgFgUgRgNQgTgOgVAAQgiAAgVAXQgWAXAAAhQAAAiAVAXQAWAXAiAAQAVAAATgOQARgNAFgUIBVAmQgQAnggAYQgoAfg5AAQhMAAgxgugAFwCAQgjgiAAgzQAAgwAjgjQAkgkA7AAQA8AAAkAkQAjAiAAAxQAAAzgjAiQgkAlg8AAQg7AAgkglgAGxALQgLAMAAAUQAAAUALANQALANATAAQAUAAALgNQALgNAAgUQAAgUgLgMQgLgLgUAAQgTAAgLALgADXCfIAAhUIhHAAIAABUIhWAAIAAjmIBWAAIAABHIBHAAIAAhHIBWAAIAADmgAhKCfIAAhuIhKBuIhTAAIAAjmIBWAAIAABlIBFhlIBWAAIAADmgAJyCfIAAjmICmAAQAmAAAVATQASARAAAYQAAASgMAOQgKANgTAFQAVAEAMAQQAMAPAAAWQAAAagSARQgWAUgjAAgALJBfIA+AAQAFAAADgDQAEgDAAgFQAAgLgMAAIg+AAgALJAKIA7AAQAFAAADgDQADgDAAgEQAAgCgDgDQgDgDgFAAIg7AAgAluCfIAAidIhHAAIAACdIhWAAIAAjmIDzAAIAADmg");
	mask_1.setTransform(87.8,17.5);

	// Слой 3
	this.instance_1 = new lib.СпиновRectangle5Изображение();
	this.instance_1.parent = this;

	this.instance_1.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.4,1,174.8,33.1);


(lib._4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AL8EZIAAgeIgUAUIgyAAIgKgeIgUA8IAAAoIgegyQgtgjgFgFQgDgDgEgTIgDgSIhGAeIAAAeIgUgoIgKgoQgXgFgHAFQgEADgXAJIgXAIIgOgjIgQAFQggAOgpgBQgmgBgdgMQgXgKgjAIQgYAFgmARQgbANgygCQgngCgggJQg5gQg1AaQgpAVhZgVIg2gQQgogMgQAIQgNAIgggBQgrAAgWADQgfAFgigKQgggNgNgCQg9AehNgOQg7gKhJgkQhOg+gXh0QgXhxApheQA2h9CzgcQA+gJA0ARQAtAOArAkQAYATAiAhQAmgJA6AAQA7AAAjAJQAiAKAggFQAegFAsgUQAsgTAQgBQATgCAzAMQAhAJAyAQQAlAKASgFIA7gNQArgGAmAJIA8AQQAQACAOgIQAZgOAUgFQAhgJAgAIQAZAHARAMQAUAFBOgYQBfgcBZAUQBbAWA3BCQA5BEADBmQADBkg1BOIgOARIgGANIgoAyIgeAUIgKAoIAAAUIgKAyIgeAyg");
	this.shape.setTransform(99.4,39.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0.1,198.9,78.3);


(lib.Бесплатных_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6600").s().p("AABCQQgZgVAAglQAAgnAZgTQAVgQAgAAQAXAAATAHQATAHAJALIAAgYQAAgNgLgGQgMgIgUAAQgQAAgRAGQgSAGgNAJIgbgzQAUgRAfgKQAbgIAdAAQAyAAAdAUQAjAYgBAzIAACMIhWAAIAAgWQgKAMgTAIQgUAIgVAAQgeAAgXgSgAA9BWQAAATAeAAQAZAAAJgMIAAgOQgEgGgKgDQgJgDgLAAQgeAAAAATgAk6BbQANAAAIgLQAJgNAEggIARhsIDQAAIAADlIhWAAIAAicIgwAAIgHAvQgIA4gaAcQgdAfg3AAgAspCBQglgjAAg2QAAg0AlgiQAlghA4AAQAjAAAcAOQAXAMAMASIg4AyQgOgSgZAAQgTAAgNAJQgOAMAAAVQAAAVAOANQANAMATAAQAbAAAMgUIA4A1QgMASgWALQgcAPgkAAQg4AAglghgAwtCCQgmgiAAg4QAAgxAjgiQAkgkA3AAQA0AAAiAjQAiAjAAA6IAAASIidAAQAEAMANAIQANAJAUAAQALAAAQgEQASgFAIgHIAkA1QgQAOgdAIQgaAHgcAAQg3AAgkgggAuvAMQgGgaggAAQgeAAgIAaIBMAAIAAAAgAMHCdIAAjmIBWAAIAABFIBJAAQArAAAXAWQAWAWABAkQAAAigXAXQgaAYgoAAgANcBZIA5AAQAIAAAFgEQAFgEAAgFQAAgOgSAAIg5AAgAKACdIAAhUIhHAAIAABUIhWAAIAAjmIBWAAIAABJIBHAAIAAhJIBWAAIAADmgA1/CdIAAk+IELAAIAABUIiqAAIAAAZIBOAAQA0AAAfAfQAcAbAAAtQAAAugcAdQgeAfg0AAgA0eBIIBCAAQAYAAABgUQAAgKgHgGQgGgFgLAAIhDAAgAUhCcIgkg9IglA9IheAAIBMh3IhHhvIBfAAIAfA2IAfg2IBfAAIhHBvIBMB3gAQSCcIAAjlIBWAAIAADlgAEwCcIAAicIg+AAIAAhKIDRAAIAABKIg9AAIAACcgAmxCcIAAicIhHAAIAACcIhWAAIAAjlIDzAAIAADlg");
	this.shape.setTransform(140.9,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281.8,32.6);


(lib.Бесплатных_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AABCQQgZgVAAglQAAgnAZgTQAVgQAgAAQAXAAATAHQATAHAJALIAAgYQAAgNgLgGQgMgIgUAAQgQAAgRAGQgSAGgNAJIgbgzQAUgRAfgKQAbgIAdAAQAyAAAdAUQAjAYgBAzIAACMIhWAAIAAgWQgKAMgTAIQgUAIgVAAQgeAAgXgSgAA9BWQAAATAeAAQAZAAAJgMIAAgOQgEgGgKgDQgJgDgLAAQgeAAAAATgAk6BbQANAAAIgLQAJgNAEggIARhsIDQAAIAADlIhWAAIAAicIgwAAIgHAvQgIA4gaAcQgdAfg3AAgAspCBQglgjAAg2QAAg0AlgiQAlghA4AAQAjAAAcAOQAXAMAMASIg4AyQgOgSgZAAQgTAAgNAJQgOAMAAAVQAAAVAOANQANAMATAAQAbAAAMgUIA4A1QgMASgWALQgcAPgkAAQg4AAglghgAwtCCQgmgiAAg4QAAgxAjgiQAkgkA3AAQA0AAAiAjQAiAjAAA6IAAASIidAAQAEAMANAIQANAJAUAAQALAAAQgEQASgFAIgHIAkA1QgQAOgdAIQgaAHgcAAQg3AAgkgggAuvAMQgGgaggAAQgeAAgIAaIBMAAIAAAAgAMHCdIAAjmIBWAAIAABFIBJAAQArAAAXAWQAWAWABAkQAAAigXAXQgaAYgoAAgANcBZIA5AAQAIAAAFgEQAFgEAAgFQAAgOgSAAIg5AAgAKACdIAAhUIhHAAIAABUIhWAAIAAjmIBWAAIAABJIBHAAIAAhJIBWAAIAADmgA1/CdIAAk+IELAAIAABUIiqAAIAAAZIBOAAQA0AAAfAfQAcAbAAAtQAAAugcAdQgeAfg0AAgA0eBIIBCAAQAYAAABgUQAAgKgHgGQgGgFgLAAIhDAAgAUhCcIgkg9IglA9IheAAIBMh3IhHhvIBfAAIAfA2IAfg2IBfAAIhHBvIBMB3gAQSCcIAAjlIBWAAIAADlgAEwCcIAAicIg+AAIAAhKIDRAAIAABKIg9AAIAACcgAmxCcIAAicIhHAAIAACcIhWAAIAAjlIDzAAIAADlg");
	this.shape.setTransform(140.9,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281.8,32.6);


(lib.Бесплатных_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFC000").s().p("AABCQQgZgVAAglQAAgoAZgSQAVgQAgAAQAXAAATAHQATAGAJAMIAAgYQAAgNgLgGQgMgIgUAAQgQAAgRAGQgSAGgNAIIgbgyQAUgRAfgKQAbgIAdAAQAyAAAdAUQAjAYgBAzIAACMIhWAAIAAgWQgKAMgTAIQgUAIgVAAQgeAAgXgSgAA9BVQAAAUAegBQAZABAJgMIAAgPQgEgFgKgEQgJgDgLAAQgeABAAASgAk6BbQANAAAIgMQAJgNAEggIARhsIDQAAIAADmIhWAAIAAicIgwAAIgHAvQgIA4gaAbQgdAfg3ABgAspCBQglgjAAg2QAAg0AlgjQAlggA4AAQAjAAAcAOQAXAMAMARIg4AyQgOgRgZgBQgTAAgNAJQgOAMAAAWQAAAVAOANQANAMATAAQAbgBAMgTIA4A1QgMASgWALQgcAPgkAAQg4gBglgggAwtCCQgmgjAAg3QAAgxAjgiQAkgkA3AAQA0AAAiAiQAiAkAAA5IAAASIidAAQAEANANAHQANAKAUgBQALAAAQgDQASgGAIgHIAkA1QgQAOgdAJQgaAGgcABQg3gBgkgfgAuvAMQgGgaggAAQgeAAgIAaIBMAAIAAAAgAMHCdIAAjnIBWAAIAABGIBJAAQArAAAXAWQAWAWABAkQAAAigXAWQgaAZgoAAgANcBZIA5AAQAIAAAFgEQAFgEAAgFQAAgPgSAAIg5AAgAKACdIAAhUIhHAAIAABUIhWAAIAAjnIBWAAIAABJIBHAAIAAhJIBWAAIAADngA1/CdIAAk+IELAAIAABUIiqAAIAAAZIBOAAQA0AAAfAfQAcAbAAAtQAAAtgcAeQgeAfg0AAgA0eBIIBCAAQAYAAABgVQAAgJgHgGQgGgFgLAAIhDAAgAUhCcIgkg9IglA9IheAAIBMh3IhHhvIBfAAIAfA2IAfg2IBfAAIhHBvIBMB3gAQSCcIAAjmIBWAAIAADmgAEwCcIAAicIg+AAIAAhKIDRAAIAABKIg9AAIAACcgAmxCcIAAicIhHAAIAACcIhWAAIAAjmIDzAAIAADmg");
	this.shape.setTransform(140.9,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281.8,32.5);


(lib.Бесплатных = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF1800").s().p("AABCQQgZgVAAglQAAgoAZgSQAVgQAgAAQAXAAATAHQATAGAJAMIAAgYQAAgNgLgGQgMgIgUAAQgQAAgRAGQgSAGgNAIIgbgyQAUgRAfgKQAbgIAdAAQAyAAAdAUQAjAYgBAzIAACMIhWAAIAAgWQgKAMgTAIQgUAIgVAAQgeAAgXgSgAA9BVQAAAUAegBQAZABAJgMIAAgPQgEgFgKgEQgJgDgLAAQgeABAAASgAwtCCQgmgjAAg3QAAgxAjgiQAkgkA3AAQA0AAAiAiQAiAkAAA6IAAARIidAAQAEANANAIQAOAJATAAQALAAAQgEQASgFAIgHIAkA1QgQAOgdAIQgaAHgcAAQg3AAgkgggAuvAMQgGgaggAAQgeAAgIAaIBMAAIAAAAgAk6BbQANAAAIgMQAJgNAEggIARhsIDQAAIAADmIhWAAIAAicIgwAAIgHAvQgIA4gaAbQgdAfg3ABgAspCBQglgjAAg2QAAg0AlgjQAlggA4AAQAjAAAcAOQAXAMAMARIg4AyQgOgRgZgBQgTAAgNAJQgOAMAAAWQAAAVAOANQANAMATAAQAbgBAMgTIA4A1QgMASgWALQgcAPgkAAQg4gBglgggAMHCdIAAjnIBWAAIAABGIBJAAQArAAAXAWQAWAWABAkQAAAigXAWQgaAZgoAAgANcBZIA5AAQAIAAAFgEQAFgEAAgFQAAgPgSAAIg5AAgAKACdIAAhUIhHAAIAABUIhWAAIAAjnIBWAAIAABJIBHAAIAAhJIBWAAIAADngA1/CdIAAk+IELAAIAABUIiqAAIAAAZIBOAAQA0AAAfAfQAcAbAAAtQAAAtgcAeQgeAfg0AAgA0eBIIBCAAQAYAAABgVQAAgJgHgGQgGgFgLAAIhDAAgAUhCcIgkg9IglA9IheAAIBMh3IhHhvIBfAAIAfA2IAfg2IBfAAIhHBvIBMB3gAQSCcIAAjmIBWAAIAADmgAEwCcIAAicIg+AAIAAhKIDRAAIAABKIg9AAIAACcgAmxCcIAAicIhHAAIAACcIhWAAIAAjmIDzAAIAADmg");
	this.shape.setTransform(140.9,16.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,281.8,32.5);


(lib._3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A0fFFQgDgFgHg3IgegeIgyAKIgeAoIgegUIgKgoIgogoIgEgmQgUgdgFgnIgBgiQADgrgDjDQgCiABNgpQAngVBWAAIBhgBQA6ABA3AKQA3AJAVAdQAMARAMAjQAEAAATgFQAZgDAqAIQAiAGAaARQAQAMAOgFQAOgFAqgTQApgQAXAAIAsAGQAYAEAggKQApgNAagCQAdgDA2AIQAlAFBJASQBBAPAZACQAaABAogVQAugaAcgEQAjgGAnASQA1AZANADQAmAIAsgFQAwgFAcgSQAbgRAcAAQAGgBBPAIQAkADAwANQAgAIAYgEIBGgNQAqgFAmAIQA2ALAgADQAsAEAegIQAXgGAggMQAegGAtAOQAXAHAkAdQAOALAbgbQAegeA4AJQAeAFAsAQQAUAEAzgJICLgZQBXgOA6A5QA2AzgTAuQgTAtgCAoQgCAxAXAiQAXAlgNApQgKAjgoAvQgfAlg6AIQguAGgZgLQgngSgpASQgVAJhWgFQhRgGgWgIQgTgIgIABQgJABgsAQQgoAOhNgCQg+gCgpgKQgegHgOABQgLACgtAOQgnANgegBQgUgBgzgLQgegHgQgJQgJgGgPACQgPACgWAHQgZAIgSADQgWAEgjgJIg/gPQhDAXg1AHQgZADgggSQgfgVgMgEQgVAQhNAEQgsACgdgGQgTgEgcgMQgcAKgPAEQgZAGgWAAIgugGQgegDgiAJQglAKg3gDQgegBgwgGQgWgDgbAEQgwAHgXACQgoADgigOQglgSgXgJIhMAmIgKAKQgKANAAAHQAAARgUANQgKAHg8gbIgegKIgeAKIgFAIQgGAIgGAGQghgPAAADIgigJIgGgLIgegKIgOAKQgOAMgCAIQgCANgIARIgeAoIgUAyg");
	this.shape.setTransform(154.3,38.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0,308.5,77.1);


(lib._100_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF6600").s().p("ACkByQgjgtAAhFQAAhFAjgtQAmgyBEAAQBFAAAnAyQAjAugBBEQAABFgjAtQgmAzhFAAQhDAAgngzgADhAAQAAApALATQALAUAXAAQAYAAALgUQAKgTAAgpQAAgogLgTQgKgTgYAAQgtAAAABOgAiHBzQgkguAAhFQAAhEAjguQAngyBEAAQBCAAAnAyQAkAugBBEQAABFgjAtQgmAzhDAAQhEAAgmgygAhKAAQAABQAtAAQAYAAAIgUQALgTAAgpQAAgogLgTQgIgTgYAAQgtAAAABOgAkvCfIAAjDIg2A0Ig2g3IB5h4IBUAAIAAE+g");
	this.shape.setTransform(41.3,16.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,82.6,33.1);


(lib._100_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFA200").s().p("ACkByQgjgtAAhFQAAhFAjgtQAmgyBEAAQBFAAAnAyQAjAugBBEQAABFgjAtQgmAzhFAAQhDAAgngzgADhAAQAAApALATQALAUAXAAQAYAAALgUQAKgTAAgpQAAgogLgTQgKgTgYAAQgtAAAABOgAiHBzQgkguAAhFQAAhEAjguQAngyBEAAQBCAAAnAyQAkAugBBEQAABFgjAtQgmAzhDAAQhEAAgmgygAhKAAQAABQAtAAQAYAAAIgUQALgTAAgpQAAgogLgTQgIgTgYAAQgtAAAABOgAkvCfIAAjDIg2A0Ig2g3IB5h4IBUAAIAAE+g");
	this.shape.setTransform(41.3,16.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,82.6,33.1);


(lib._100_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACkBzQgjguAAhFQAAhEAjguQAmgyBEAAQBFAAAnAyQAjAugBBEQAABFgjAuQgmAyhFAAQhDAAgngygADhAAQAAApALAUQALATAXAAQAYAAALgTQAKgUAAgpQAAgngLgUQgKgTgYAAQgtAAAABOgAiHBzQgkguAAhFQAAhEAjguQAngyBEAAQBCAAAnAyQAkAugBBEQAABFgjAuQgmAyhDAAQhEAAgmgygAhKAAQAABQAtAAQAYAAAIgTQALgTAAgqQAAgngLgUQgIgTgYAAQgtAAAABOgAkvCgIAAjDIg2A0Ig2g4IB5h4IBUAAIAAE/g");
	this.shape.setTransform(41.3,16.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,82.6,33.1);


(lib._100 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF1800").s().p("ACkBzQgjguAAhFQAAhEAjguQAmgyBEAAQBFAAAnAyQAjAugBBEQAABFgjAuQgmAyhFAAQhDAAgngygADhAAQAAApALAUQALATAXAAQAYAAALgTQAKgUAAgpQAAgngLgUQgKgTgYAAQgtAAAABOgAiHBzQgkguAAhFQAAhEAjguQAngyBEAAQBCAAAnAyQAkAugBBEQAABFgjAuQgmAyhDAAQhEAAgmgygAhKAAQAABQAtAAQAYAAAIgTQALgTAAgqQAAgngLgUQgIgTgYAAQgtAAAABOgAkvCgIAAjDIg2A0Ig2g4IB5h4IBUAAIAAE/g");
	this.shape.setTransform(41.3,16.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,82.6,33.1);


(lib._2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADWEuQgWgFhPgjQgtAagyAJQg5ALg4gQQgxgNgMADQgHAIgMACQiRAhg/gtQgegWgWhCQgFgPADgXIAGgkQAFgpgngPQhUgnAQhLQAIgmAog4QAXggAvgwQAlg8BDgPQA1gMAhARQAgASALABQAZADA0gWQAygUA2ASQAgALBcApQCmhPB8BQQAzAhAhA4QAeA0AGA6QAMBygnBUQgoBZhdApQg3AZg2AAQgZAAgZgFg");
	this.shape.setTransform(53.7,30.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0.1,107.3,61.6);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.parent = this;
	this.instance.setTransform(421.3,175.5,1,1,0,0,0,421.3,175.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},9).wait(381).to({alpha:1},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,842.7,351);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AT7YoQgPgCgJgLIgFgHQgIgEgGgFQgOgLgFgTQgPgDgJgLIgEgGMgldAAAQgEAQgLASQgKATgNAKQgMAJgPACQgQABgMgHQgNgIgFgPIgBgBQgHgHgGgKIgPgbIgMAAIACgMQgLgFgNgKIg0gnQgRgNgMgBQgGgBgQAFQgPAEgIgDQgNgEgJgYQgUg1gJg6QgDgWgEgKQgDgFgHgIIgKgNQgdgnALhEQADgSAKglIAEgSQgKgEgEgKQgDgIAAgMIAAgVQgBgJgIgQQgJgRgCgIIgFgTIgIgPQgCgGABgKIABgQIgBgOQAAgIABgFIAHgSQAFgMgBgXIgBiOIAAgJIgBgFIAA+pIgBAAIAAj8MAzNAAAIAAD8IgDAAMAAAAj+QABAQgEAUIgIAYQACAIgBAJQAAAMgGAPIgKAbIgIATIgDAIIAAAKIgCAJIgGAGQgGBLgXA7QgJAZgMAOIADAFQAIASgIARQgKAUgmARIgjAOIgBAAQgeAhgoAQQgHALgCAKIgBABIgOAAIgRAUIgNAUQgIALgIAGQgGAEgIADQgEAFgEADQgKAHgMAAIgGAAgAR/Q/IAkAHQAUADAogGQAogFAUACIAVADIAWADIAngDIAigCQAVgBANgCQAMgCAKgEIABAAIAEgBIACgBIADgBIACgCIADgBIABgCIAAgBQALgIAHgLQAIgNAEgdIAGguQABgOgCgIIAAgCIACgBIADgCIABgCIACgBIABgCIABgCIABgCIAAgCIAAgBIAAgCIABgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAAAIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgBIAAgEIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgGIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIABAAIAAmqIhTAAIAAABMgt5AAAIAAgBIhKAAIAAFnIAAAAIAAAFIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAHIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAHIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAFIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIgBACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAABIAAABIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIABACIAAACIAAACIAAACIABABIABACIAAABQgBAGACASIACAgIACAUIAEAJIAAACIABABIAAACIAAACQgEAHAAAOIACBYQABAWADAIIAIARIAKAZQAFAPAHAHQAQATAhACIAcAAIARgBIADAAIAHAAQAVABAJgBIeZAAIADAAIADABIGnAAIAGABIAVABQANABAIACIARAGQAKAEAIgBQALAAAUgIQAGgCAIAAQAJAAANADgAN5QRIBUgBIgBABIhTAAgAqkQRIAAAAICYAAIAAAAIiYAAgArvOVIAAgCIAaACg");
	var mask_graphics_394 = new cjs.Graphics().p("AT7YoQgPgCgJgLIgFgHQgIgEgGgFQgOgLgFgTQgPgDgJgLIgEgGMgldAAAQgEAQgLASQgKATgNAKQgMAJgPACQgQABgMgHQgNgIgFgPIgBgBQgHgHgGgKIgPgbIgMAAIACgMQgLgFgNgKIg0gnQgRgNgMgBQgGgBgQAFQgPAEgIgDQgNgEgJgYQgUg1gJg6QgDgWgEgKQgDgFgHgIIgKgNQgdgnALhEQADgSAKglIAEgSQgKgEgEgKQgDgIAAgMIAAgVQgBgJgIgQQgJgRgCgIIgFgTIgIgPQgCgGABgKIABgQIgBgOQAAgIABgFIAHgSQAFgMgBgXIgBiOIAAgJIgBgFIAA+pIgBAAIAAj8MAzNAAAIAAD8IgDAAMAAAAj+QABAQgEAUIgIAYQACAIgBAJQAAAMgGAPIgKAbIgIATIgDAIIAAAKIgCAJIgGAGQgGBLgXA7QgJAZgMAOIADAFQAIASgIARQgKAUgmARIgjAOIgBAAQgeAhgoAQQgHALgCAKIgBABIgOAAIgRAUIgNAUQgIALgIAGQgGAEgIADQgEAFgEADQgKAHgMAAIgGAAgAR/Q/IAkAHQAUADAogGQAogFAUACIAVADIAWADIAngDIAigCQAVgBANgCQAMgCAKgEIABAAIAEgBIACgBIADgBIACgCIADgBIABgCIAAgBQALgIAHgLQAIgNAEgdIAGguQABgOgCgIIAAgCIACgBIADgCIABgCIACgBIABgCIABgCIABgCIAAgCIAAgBIAAgCIABgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAAAIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgBIAAgEIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgGIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIABAAIAAmqIhTAAIAAABMgt5AAAIAAgBIhKAAIAAFnIAAAAIAAAFIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAHIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAHIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAFIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIgBACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAABIAAABIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIABACIAAACIAAACIAAACIABABIABACIAAABQgBAGACASIACAgIACAUIAEAJIAAACIABABIAAACIAAACQgEAHAAAOIACBYQABAWADAIIAIARIAKAZQAFAPAHAHQAQATAhACIAcAAIARgBIADAAIAHAAQAVABAJgBIeZAAIADAAIADABIGnAAIAGABIAVABQANABAIACIARAGQAKAEAIgBQALAAAUgIQAGgCAIAAQAJAAANADgAN5QRIBUgBIgBABIhTAAgAqkQRIAAAAICYAAIAAAAIiYAAgArvOVIAAgCIAaACg");
	var mask_graphics_399 = new cjs.Graphics().p("AT7YoQgPgCgJgLIgFgHQgIgEgGgFQgOgLgFgTQgPgDgJgLIgEgGMgldAAAQgEAQgLASQgKATgNAKQgMAJgPACQgQABgMgHQgNgIgFgPIgBgBQgHgHgGgKIgPgbIgMAAIACgMQgLgFgNgKIg0gnQgRgNgMgBQgGgBgQAFQgPAEgIgDQgNgEgJgYQgUg1gJg6QgDgWgEgKQgDgFgHgIIgKgNQgdgnALhEQADgSAKglIAEgSQgKgEgEgKQgDgIAAgMIAAgVQgBgJgIgQQgJgRgCgIIgFgTIgIgPQgCgGABgKIABgQIgBgOQAAgIABgFIAHgSQAFgMgBgXIgBiOIAAgJIgBgFIAA+pIgBAAIAAj8MAzNAAAIAAD8IgDAAMAAAAj+QABAQgEAUIgIAYQACAIgBAJQAAAMgGAPIgKAbIgIATIgDAIIAAAKIgCAJIgGAGQgGBLgXA7QgJAZgMAOIADAFQAIASgIARQgKAUgmARIgjAOIgBAAQgeAhgoAQQgHALgCAKIgBABIgOAAIgRAUIgNAUQgIALgIAGQgGAEgIADQgEAFgEADQgKAHgMAAIgGAAgAR/Q/IAkAHQAUADAogGQAogFAUACIAVADIAWADIAngDIAigCQAVgBANgCQAMgCAKgEIABAAIAEgBIACgBIADgBIACgCIADgBIABgCIAAgBQALgIAHgLQAIgNAEgdIAGguQABgOgCgIIAAgCIACgBIADgCIABgCIACgBIABgCIABgCIABgCIAAgCIAAgBIAAgCIABgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAAAIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgBIAAgCIAAgCIAAgCIAAgCIAAgBIAAgCIAAgBIAAgEIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgGIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgGIAAgFIAAgHIAAgFIAAgHIAAgFIAAgHIAAgHIAAgFIAAgGIAAgFIAAgHIAAgHIAAgFIAAgHIAAgFIAAgHIAAgFIAAgGIAAgHIABAAIAAmqIhTAAIAAABMgt5AAAIAAgBIhKAAIAAFnIAAAAIAAAFIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAHIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAHIAAADIAAAJIAAADIAAAIIAAAEIAAAIIAAAEIAAAIIAAADIAAAHIAAAEIAAAIIAAADIAAAJIAAADIAAAJIAAADIAAAIIAAAEIAAAGIAAAEIAAAIIAAAEIAAAIIAAADIAAAJIAAADIAAAFIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAADIAAABIAAACIAAABIAAACIgBACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAABIAAABIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIAAACIAAACIAAACIAAACIAAABIABACIAAACIAAACIAAACIABABIABACIAAABQgBAGACASIACAgIACAUIAEAJIAAACIABABIAAACIAAACQgEAHAAAOIACBYQABAWADAIIAIARIAKAZQAFAPAHAHQAQATAhACIAcAAIARgBIADAAIAHAAQAVABAJgBIeZAAIADAAIADABIGnAAIAGABIAVABQANABAIACIARAGQAKAEAIgBQALAAAUgIQAGgCAIAAQAJAAANADgAN5QRIBUgBIgBABIhTAAgAqkQRIAAAAICYAAIAAAAIiYAAgArvOVIAAgCIAaACg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:141,y:163.7}).wait(394).to({graphics:mask_graphics_394,x:141,y:163.7}).wait(5).to({graphics:mask_graphics_399,x:141,y:163.7}).wait(1));

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.parent = this;
	this.instance.setTransform(140.3,197.8,1,1,0,0,0,163.3,215.8);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(394).to({alpha:0},5).wait(1));

	// Слой 10
	this.instance_1 = new lib.Символ25();
	this.instance_1.parent = this;
	this.instance_1.setTransform(257.6,158.1,1,1,0,0,0,37.6,39.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(364).to({_off:false},0).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).wait(5).to({alpha:0},5).wait(1));

	// Слой 9
	this.instance_2 = new lib.Символ24();
	this.instance_2.parent = this;
	this.instance_2.setTransform(180.1,158.1,1,1,0,0,0,37.6,39.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(359).to({_off:false},0).to({alpha:1},5).to({alpha:0},10).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).wait(5).to({alpha:0},5).wait(1));

	// Слой 8
	this.instance_3 = new lib.Символ23();
	this.instance_3.parent = this;
	this.instance_3.setTransform(101.4,158.1,1,1,0,0,0,37.6,39.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(354).to({_off:false},0).to({alpha:1},5).to({alpha:0},15).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).wait(5).to({alpha:0},5).wait(1));

	// Слой 7
	this.instance_4 = new lib.Символ22();
	this.instance_4.parent = this;
	this.instance_4.setTransform(23.4,158,1,1,0,0,0,37.6,39.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(349).to({_off:false},0).to({alpha:1},5).to({alpha:0},20).to({alpha:1},5).to({alpha:0},5).to({alpha:1},5).wait(5).to({alpha:0},5).wait(1));

	// Слой 12 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A1OWAIgCgJQgFgQgLgOQgWgYgkgGQgYgFgsADIgKg4QgFgggNgUQgPgXgHgMQgHgOgFgdQgIg+gGgeIgKgiIgJgiQgDgNgCgWIgDgkQgFgdgNgTMAAAgjnMAyvAAAMAAAAmtIgHATIgJAzQgLBHgcBFQgMAbgOAJQgKAIgQADIgeAEQg7AIgvAoQgQAOgMAPg");
	mask_1.setTransform(139.9,172.2);

	// Слой 6
	this.instance_5 = new lib.Символ21();
	this.instance_5.parent = this;
	this.instance_5.setTransform(256.4,-165.1,1,1,0,0,0,38.4,192.1);
	this.instance_5._off = true;

	this.instance_5.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(302).to({_off:false},0).to({y:-170.9},13).wait(24).to({y:541.4},12,cjs.Ease.get(1)).wait(43).to({alpha:0},5).wait(1));

	// Слой 5
	this.instance_6 = new lib.Символ20();
	this.instance_6.parent = this;
	this.instance_6.setTransform(180.4,-166.1,1,1,0,0,0,38.4,192.1);
	this.instance_6._off = true;

	this.instance_6.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(302).to({_off:false},0).to({y:-171.9},13).wait(12).to({y:540.4},12,cjs.Ease.get(1)).wait(55).to({alpha:0},5).wait(1));

	// Слой 4
	this.instance_7 = new lib.Символ19();
	this.instance_7.parent = this;
	this.instance_7.setTransform(102.4,-166.1,1,1,0,0,0,38.4,192.1);
	this.instance_7._off = true;

	this.instance_7.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(302).to({_off:false},0).to({y:-171.9},13).to({y:540.4},12,cjs.Ease.get(0.97)).wait(67).to({alpha:0},5).wait(1));

	// Слой 2
	this.instance_8 = new lib.Символ18();
	this.instance_8.parent = this;
	this.instance_8.setTransform(24.4,-166.1,1,1,0,0,0,38.4,192.1);
	this.instance_8._off = true;

	this.instance_8.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(302).to({_off:false},0).to({y:539.7},13,cjs.Ease.get(1)).wait(79).to({alpha:0},5).wait(1));

	// Слой 11
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A4pTYMAAAgmvMAxTAAAMAAAAmvg");
	this.shape.setTransform(143.5,155.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(400));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23,6.1,326.7,315.3);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ16();
	this.instance.parent = this;
	this.instance.setTransform(178,235.1,1,1,0,0,0,178,235.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(295).to({y:277.4},0).to({x:215.5,y:307.4,alpha:1},5).to({x:216.1},1).to({x:215.5},1).wait(88).to({alpha:0},5).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23.4,-18,328.8,431.5);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(107.1,17.9,1.187,1.187,0,0,0,62,8.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:8.3,scaleX:1.25,scaleY:1.25,x:107.2,y:19.1},9).to({regY:8.2,scaleX:1.19,scaleY:1.19,x:107.1,y:17.9},10).to({regY:8.3,scaleX:1.25,scaleY:1.25,x:107.2,y:19.1},10).to({regY:8.2,scaleX:1.19,scaleY:1.19,x:107.1,y:17.9},10).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ12();
	this.instance_1.parent = this;
	this.instance_1.setTransform(106.6,18.2,1.187,1.187,0,0,0,107.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:18.7,scaleX:1.25,scaleY:1.25,x:106.8,y:19.4},9).to({regY:18.6,scaleX:1.19,scaleY:1.19,x:106.6,y:18.2},10).to({regY:18.7,scaleX:1.25,scaleY:1.25,x:106.8,y:19.4},10).to({regY:18.6,scaleX:1.19,scaleY:1.19,x:106.6,y:18.2},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22.2,-5.1,257.7,46.7);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib._100();
	this.instance.parent = this;
	this.instance.setTransform(53.1,30.6,1,1,0,0,0,41.2,16.6);

	this.instance_1 = new lib._100_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(53.1,31.6,1,1,0,0,0,41.2,16.6);

	this.instance_2 = new lib._100_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(54.1,32.5,1,1,0,0,0,41.2,16.5);

	this.instance_3 = new lib._100_3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(54.1,33.5,1,1,0,0,0,41.2,16.5);

	this.instance_4 = new lib._2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(53.7,30.8,1,1,0,0,0,53.7,30.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,107.3,61.6);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.parent = this;
	this.instance.setTransform(216,94,1,1,0,0,0,216,94);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:98.4},9,cjs.Ease.get(-1)).to({y:103.2},10,cjs.Ease.get(1)).to({y:98.6},10,cjs.Ease.get(-1)).to({y:94},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,432,188);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(216,94,1,1,0,0,0,216,94);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(49).to({_off:false},0).to({x:-514},15,cjs.Ease.get(1)).to({x:-486,y:95.5},7,cjs.Ease.get(-1)).to({x:-454,y:97.3},8,cjs.Ease.get(1)).to({x:-483,y:98.6},15,cjs.Ease.get(-1)).to({x:-514,y:100},16,cjs.Ease.get(1)).to({x:-484,y:101},15,cjs.Ease.get(-1)).to({x:-454,y:102},15,cjs.Ease.get(1)).to({x:-954},10,cjs.Ease.get(-1)).wait(149).to({skewY:180,y:57},0).to({x:-609,y:109.5},10,cjs.Ease.get(1)).wait(80).to({x:1071},10,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.parent = this;
	this.instance.setTransform(68.5,47.5,0.213,0.213,0,0,0,68,49);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,x:68,y:49,alpha:1},24,cjs.Ease.get(1)).wait(55).to({alpha:0},20).wait(302));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(54,37.1,29,20.9);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// bg
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(400,150,1,1,0,0,0,400,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(24).to({x:354},25).to({x:471.3},101).wait(251));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,800,300);


(lib.Вамвыпалоlines = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(144.5,16.5,1,1,0,0,0,144.5,16.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,289,33.1);


(lib.СпиновRectangle5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ClipGroup_1();
	this.instance.parent = this;
	this.instance.setTransform(88,17.1,1,1,0,0,0,88,17.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,176,34.1);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.text = new cjs.Text("btn", "30px 'Roboto Medium'");
	this.text.lineHeight = 37;
	this.text.lineWidth = 100;
	this.text.parent = this;
	this.text.setTransform(-347.6,69.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,1).p("AkrlgIJXAAQA8AAAAA8IAAJJQAAA8g8AAIpXAAQg8AAAAg8IAApJQAAg8A8AAg");
	this.shape.setTransform(-326.2,88.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkrFhQg8AAAAg9IAApHQAAg8A8gBIJXAAQA8ABAAA8IAAJHQAAA9g8AAg");
	this.shape_1.setTransform(-326.2,88.3);

	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(106.9,71.3,1,1,0,0,0,107.5,18.7);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape},{t:this.text}]}).to({state:[{t:this.instance}]},185).to({state:[{t:this.instance}]},5).to({state:[{t:this.instance}]},200).to({state:[{t:this.instance}]},5).to({state:[{t:this.instance}]},5).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(185).to({_off:false},0).to({y:-79.9},5).wait(200).to({y:-78.8,alpha:0},5).wait(6));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-363.2,52,117.6,72.6);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(355,33,0.928,0.928,0,0,0,53.7,30.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Вамвыпалоlines();
	this.instance_1.parent = this;
	this.instance_1.setTransform(158.6,29.5,1,1,0,0,0,144.5,16.5);

	this.instance_2 = new lib._1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(156.3,32.5,1,1,0,0,0,156.2,32.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,404.8,65);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.СпиновRectangle5();
	this.instance.parent = this;
	this.instance.setTransform(-0.4,-8,0.836,0.836,0,0,0,88,17.1);

	this.instance_1 = new lib._4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.1,0,0.836,0.836,0,0,0,99.5,39.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.1,-32.7,166.2,65.4);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Анимация2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(397.5,41.6,1.158,1.158);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Бесплатных();
	this.instance_1.parent = this;
	this.instance_1.setTransform(155.1,29.8,1,1,0,0,0,140.8,16.2);

	this.instance_2 = new lib.Бесплатных_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(155.1,30.8,1,1,0,0,0,140.8,16.2);

	this.instance_3 = new lib.Бесплатных_2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(156.1,31.8,1,1,0,0,0,140.8,16.2);

	this.instance_4 = new lib.Бесплатных_3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(156.1,32.8,1,1,0,0,0,140.8,16.2);

	this.instance_5 = new lib._3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(154.2,38.5,1,1,0,0,0,154.2,38.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,493.7,79.5);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Besplatnih.svg
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.setTransform(449.2,221.3,0.249,0.249,180,0,0,154.1,38.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(150).to({_off:false},0).to({regX:154.2,scaleX:0.84,scaleY:0.84,rotation:0,x:219.7,y:145.2,alpha:1},24,cjs.Ease.get(-1)).to({regX:154.3,scaleX:0.85,scaleY:0.85,x:218.7,y:144.7},5).to({regX:154.2,scaleX:0.84,scaleY:0.84,x:219.7,y:145.2},5).wait(100).to({alpha:0},15).wait(102));

	// Слой 1
	this.instance_1 = new lib.Символ8();
	this.instance_1.parent = this;
	this.instance_1.setTransform(438.9,240.2,0.249,0.249,180,0,0,156.3,32.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(150).to({_off:false},0).to({scaleX:0.84,scaleY:0.84,rotation:0,x:254.2,y:81.6,alpha:1},24,cjs.Ease.get(-1)).to({regY:32.6,scaleX:0.85,scaleY:0.85,x:253.7,y:80.2},5).to({regY:32.5,scaleX:0.84,scaleY:0.84,x:254.2,y:81.6},5).wait(100).to({alpha:0},15).wait(102));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:



(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// blick
	this.instance = new lib.Символ26();
	this.instance.parent = this;
	this.instance.setTransform(321.9,148.1,1,1,0,0,0,421.3,175.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// btn
	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(299.4,347.2,1,1,0,0,0,107.5,18.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Vam-vipalo.svg
	this.instance_2 = new lib.Символ7();
	this.instance_2.parent = this;
	this.instance_2.setTransform(1.9,19);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// santa
	this.instance_3 = new lib.Символ5();
	this.instance_3.parent = this;
	this.instance_3.setTransform(657,116);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// slot
	this.instance_4 = new lib.Символ15();
	this.instance_4.parent = this;
	this.instance_4.setTransform(299,139.1,1,1,0,0,0,178,235.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// logo
	this.instance_5 = new lib.Символ3();
	this.instance_5.parent = this;
	this.instance_5.setTransform(299,152,1,1,0,0,0,68,49);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

	// bg
	this.instance_6 = new lib.Символ1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(319,150,1,1,0,0,0,400,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(128.7,36,914.5,567);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;