(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.back = function() {
	this.initialize(img.back);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1094,117);


(lib.molecule = function() {
	this.initialize(img.molecule);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,122,122);


(lib.oim = function() {
	this.initialize(img.oim);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,174,174);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.molecule();
	this.instance.parent = this;
	this.instance.setTransform(568,100.7,0.418,0.418,180);

	this.instance_1 = new lib.molecule();
	this.instance_1.parent = this;
	this.instance_1.setTransform(335,37.1,0.598,0.598,69);

	this.instance_2 = new lib.molecule();
	this.instance_2.parent = this;
	this.instance_2.setTransform(365.9,44.2,0.418,0.418,150);

	this.instance_3 = new lib.molecule();
	this.instance_3.parent = this;
	this.instance_3.setTransform(273,58.7,0.418,0.418,180);

	this.instance_4 = new lib.molecule();
	this.instance_4.parent = this;
	this.instance_4.setTransform(475.1,42.5,0.598,0.598,114);

	this.instance_5 = new lib.molecule();
	this.instance_5.parent = this;
	this.instance_5.setTransform(124,23.7,0.598,0.598);

	this.instance_6 = new lib.molecule();
	this.instance_6.parent = this;
	this.instance_6.setTransform(115,48.7,0.418,0.418,90);

	this.instance_7 = new lib.molecule();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,27.7,0.598,0.598);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(0,0,568,131.3), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYBgQgHAAgGgCQgGgCgGgDQgTgOgBgWIAAhoQAAgnAlgEIAHgBIBfAAIAAAcIhdAAQgPAAgCANIgBADIAAAYIBAAAQAVAAAMAMQAHAFADAIQADAHAAAJIAAAnQAAAKgEAIQgEAJgIAGQgGAFgGACQgHADgGAAgAgpAQIAAAiQABAHAGAGQAHAFAGAAIAvAAIAGgBQAHgDACgJIAAgBIAAglQAAgJgDgDQgDgDgIgCIgCAAIgxAAIgBAAQgPACgBAOg");
	this.shape.setTransform(449,14.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACBgIAAijIgfAAIAAgcIA4AAIAAAAIADAAIAAC/g");
	this.shape_1.setTransform(430.2,14.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgJBgQgTAAgNgHQgNgHgHgNIgFgNIgCgOIAAhTQAAgNAEgKQADgKAGgGQAJgKAMgDQAIgCARAAIAUAAQAQAAAIACQAMADAJAKQAGAGAEAKQADAKAAANIAABTQAAAagNAOQgJAJgMADQgIACgQAAgAgXhDQgKACgEAGQgDAFAAAMIAABVQAAAMADAFQAEAGAKABIAKABIAcAAIAJgBQAKgBAEgGQADgGAAgLIAAhVQAAgOgEgFQgFgFgNgBIgEAAIgcAAg");
	this.shape_2.setTransform(414.5,14.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag9BgIAAg8QAAgMAEgJQAEgJAIgGQANgKANAAIAnAAQAEAAAEgCQADgCABgFIABgEIAAgfQgBgLgJgCIgDAAIhRAAIAAgcIBPAAQAYAAAMARQAHALAAALIAAAhQAAALgEAIQgFAIgIAGQgGAEgGACQgGABgGAAIgjAAQgJAAgEAFQgEAEAAAIIAAAiIBeAAIAAAcg");
	this.shape_3.setTransform(397.3,14.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAlBIIglg2IgjA2IgeAAIAzhJIgwhGIAdAAIAhAwIAhgwIAeAAIgxBGIA0BJg");
	this.shape_4.setTransform(374.3,17.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTBIQgJAAgHgDQgHgCgGgGQgLgKAAgRIAAg/QAAgqAtAAIAiAAQAKAAAGACQAHADAFAFQAFAFADAGQACAHAAAJIAAARIhcAqIAAAHQABAJACADQAEAEAJAAIBOAAIAAAYgAgfgqQgDAEAAAJIAAAdIBEggIAAgDQAAgMgPAAIglAAQgIAAgFAFg");
	this.shape_5.setTransform(360.3,17.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXBgQgGAAgHgEQgXgJAAgZIAAhFQAAgRAMgKQAEgEAIgDQAGgCAKAAIA3AAIAAgwIAYAAIAACWQAAAQgLAMQgKANgPAAgAgfgTQgDAEAAAIIAABAIAAABQABAHAEADQADAEAEAAIAqAAQAFAAAEgEQAGgEABgJIAAg/QgBgPgNAAIgoAAQgIAAgFAEg");
	this.shape_6.setTransform(345.1,14.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAjBIIAAhuQgCgJgOAAIglAAQgJAAgDAEQgEADAAAJIAABnIgZAAIAAhqQAAglApAAIAlAAQAUAAALAJQAJAJABATIAABqg");
	this.shape_7.setTransform(329.9,17.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgNBgIAAi/IAbAAIAAC/g");
	this.shape_8.setTransform(319.3,14.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAkBgIAAhmIgBgEQAAgFgDgDQgDgEgFgBIgqAAQgIAAgEAEQgEAEAAAIIAABnIgZAAIAAi/IAZAAIAAAwIA6AAQAUAAAKAQQAGAIAAAKIAABtg");
	this.shape_9.setTransform(300.9,14.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGBIQgMAAgJgFQgKgGgFgIQgFgHAAgLIAAhGQAAgJADgHQADgGAGgFQAKgJASAAIA2AAIAAAYIg2AAQgPAAAAAPIAAA+QAAAHAEAGQAFAFAHAAIA2AAIAAAYg");
	this.shape_10.setTransform(287.5,17.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUBIQgIAAgHgDQgHgCgFgGQgMgKAAgRIAAg/QAAgqAtAAIAjAAQAIAAAHACQAHADAFAFQAFAFADAGQADAHAAAJIAAARIheAqIAAAHQACAJADADQADAEAIAAIBPAAIAAAYgAgegqQgEAEgBAJIAAAdIBFggIAAgDQAAgMgOAAIgnAAQgHAAgEAFg");
	this.shape_11.setTransform(274,17.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBgIAAijIgqAAIAAgcIBvAAIAAAcIgqAAIAACjg");
	this.shape_12.setTransform(260.7,14.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag6BfIAAgYIBSAAQAFgBAEgEQACgDAAgHIAAgIIg6AAQgQAAgJgKQgGgFgBgGQgDgGAAgIIAAhrIAYAAIAABlQAAAIAEAFQAFAEAIAAIAkAAQAIAAAFgDQADgEAAgIIAAhnIAZAAIAACVQgBAJgCAHQgCAHgFAGQgKALgSAAg");
	this.shape_13.setTransform(239.7,19.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AghBIIAAhqIACgJQAHgcAeAAIAcAAIAAAYIgfAAQgFACgDAEQgDAEAAAHIAABmg");
	this.shape_14.setTransform(228.1,17.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAjBIIAAg6IhGAAIAAA6IgYAAIAAiPIAYAAIAAA+IBGAAIAAg+IAZAAIAACPg");
	this.shape_15.setTransform(215.5,17.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgSBIQgpAAAAglIAAhqIAZAAIAABtQABAJAPAAIApAAQAGAAADgEQADgEABgHIAAhnIAXAAIAACPg");
	this.shape_16.setTransform(200.4,17.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AA7BIIAAhpQAAgNgPAAIgVAAQgEABgDADQgCAEAAAHIAABnIgXAAIAAhpIAAgBQgDgNgNAAIgSAAIgDABQgGAAgCADQgDACAAAGIAABrIgZAAIAAhrQABgSAIgJQAJgJAQAAIAVAAIAHABQAHABAFADQAGADACAFQADgFAFgDQAGgDAIgBIAGgBIAWAAQAQAAAIAJQAIAJAAASIAABrg");
	this.shape_17.setTransform(182.9,17.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgSBeQgpAAAAglIAAhqIAZAAIAABtQABAJAPAAIApAAQAGAAADgEQAEgEAAgHIAAhnIAXAAIAACPgAgNg+QgFgCgGgFQgMgIAAgQIATAAQACARAQAAQARAAABgRIATAAQAAAIgCAGQgEAGgFAEQgMAJgOAAQgGAAgIgCg");
	this.shape_18.setTransform(165.4,15.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgTBIQgJAAgHgDQgHgCgGgGQgLgKAAgRIAAg/QAAgqAtAAIAiAAQAKAAAGACQAHADAFAFQAFAFACAGQADAHAAAJIAAARIhcAqIAAAHQABAJACADQAEAEAJAAIBOAAIAAAYgAgfgqQgDAEAAAJIAAAdIBEggIAAgDQAAgMgOAAIgmAAQgIAAgFAFg");
	this.shape_19.setTransform(150.6,17.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AhEBgIAAi/IBTAAQA2AAAAAuIAAAbQAAAMgEAJQgDAIgHAGQgHAGgJADQgKADgMAAIg5AAIAABHgAgogBIA5AAQALAAAGgEQAFgEACgLIAAgcIgBgDQgBgJgEgDQgEgDgJgBIgCAAIg8AAg");
	this.shape_20.setTransform(135.4,14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWBIQgKAAgIgDQgHgCgEgFQgJgJAAgRIAAhJQAAgPAIgIQAIgJARgCIADAAIAuAAIAGABQAhAEAAAdIAABJQgBAUgTALQgIAFgLAAgAgjgeIAAA7QAAATARAAIAmAAQAIAAAEgFQAEgEABgJIAAg8QgBgIgEgFQgEgEgIAAIgmAAQgRAAAAARg");
	this.shape_21.setTransform(111.5,17.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAjBIIAAg6IhGAAIAAA6IgXAAIAAiPIAXAAIAAA+IBGAAIAAg+IAZAAIAACPg");
	this.shape_22.setTransform(96.2,17.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgGBIQgMAAgJgFQgKgGgFgIQgFgHAAgLIAAhGQAAgJADgHQADgGAGgFQAKgJASAAIA2AAIAAAYIg2AAQgPAAAAAPIAAA+QAAAHAEAGQAFAFAHAAIA2AAIAAAYg");
	this.shape_23.setTransform(82.9,17.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgWBIQgLAAgJgIQgLgHgEgKQgCgGAAgIIAAgRQAAgTAJgLQAFgHAGgDQAIgEAJAAIA6AAIAAgJQAAgEgDgDQgDgDgDAAIhWAAIAAgYIBUAAQAPAAAIAHQAJAGACANIABAHIAABJQAAAKgFAIQgGAKgIAEQgHAFgJAAgAgfAAQgDAEAAAGIAAAYQAAAIAFAEQAFACAJAAIAfAAQAUAAAAgOIAAgYQAAgGgEgEQgFgDgHgBIgmAAQgIABgFADg");
	this.shape_24.setTransform(68.9,17.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAkBIIAAhuQgCgJgOAAIgWAAQgJAAgDAEQgEADAAAJIAABCQAAAlgpAAIAAgZQAJAAAEgDQAEgDAAgJIAAhCQAAglAoAAIAVAAQAVAAAKAJQAKAJAAATIAABqg");
	this.shape_25.setTransform(53.6,17.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AggBIIAAhqIABgJQAHgcAdAAIAcAAIAAAYIgeAAQgFACgDAEQgDAEAAAHIAABmg");
	this.shape_26.setTransform(42.1,17.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgWBIQgKAAgIgDQgHgCgEgFQgIgJAAgRIAAhJQgBgPAJgIQAHgJAQgCIAEAAIAuAAIAGABQAhAEgBAdIAABJQAAAUgTALQgIAFgLAAgAgjgeIAAA7QAAATARAAIAmAAQAIAAAEgFQAFgEAAgJIAAg8QAAgIgFgFQgEgEgIAAIgmAAQgRAAAAARg");
	this.shape_27.setTransform(29.4,17.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgGBIQgMAAgJgFQgKgGgFgIQgFgHAAgLIAAhGQAAgJADgHQADgGAGgFQAKgJASAAIA2AAIAAAYIg2AAQgPAAAAAPIAAA+QAAAHAEAGQAFAFAHAAIA2AAIAAAYg");
	this.shape_28.setTransform(16,17.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgLArIALgpIgfAeIgKgUIAogLIgpgLIALgVIAfAfIgLgqIAXAAIgKAqIAegeIALAUIgpAKIApAMIgLAVIgfgfIALApg");
	this.shape_29.setTransform(4.3,9.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(-3.2,1.7,463.3,32), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAmIAJgkIgbAaIgJgSIAkgKIgkgJIAJgSIAbAbIgJglIAUAAIgJAlIAagaIAJASIgjAIIAjAKIgJATIgbgcIAJAlg");
	this.shape.setTransform(315.7,8.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACBMIAAiBIgZAAIAAgWIAtAAIACAAIAACXg");
	this.shape_1.setTransform(307.7,17.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVA+IguhsIAAB5IgWAAIAAiBQAAgXASAAIAHABQAJACAFAMIAuBvIAAh9IAVAAIAACFQAAAIgFAGQgFAFgHABIgCABQgNAAgGgQgAAeANIAAgPIA8AAIAAAPgAA8gKQgTAAgHgOQgEgHAAgHIAAgJQAAgHACgFQACgFADgEQAFgFAGgBQAEgCAIAAIABAAQAHAAAEACQAGABAFAFQAHAIAAANIAAAJQAAANgHAIQgFAFgGABIgLABgAA2g8QgFAAgCAEQgCACAAAGIAAAKQAAAHACACQACADAFABIAEAAIAFAAIAEAAQAFgBACgDQABgDAAgGIAAgKQAAgHgCgDQgDgCgFgBIgCAAIgFAAg");
	this.shape_2.setTransform(292.4,17.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRA5QgIAAgJgGQgHgGgDgHQgCgFAAgGIAAgOQAAgOAGgKQAEgFAGgDQAFgCAIgBIAtAAIAAgHQAAgDgBgCQgCgCgEAAIhDAAIAAgUIBCAAQAMAAAGAFQAHAFACALIAAAFIAAA6QAAAIgDAGQgFAHgGAFQgGADgHAAgAgYAAQgDADAAAGIAAASQAAAHAFADQADABAIAAIAYAAQAPAAAAgLIAAgSQAAgGgDgDQgDgCgGgBIgeAAQgHABgDACg");
	this.shape_3.setTransform(270,19.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgKA1QgEgDgCgIIgdhNIAABbIgTAAIAAhbQgCgQAOgFQAJgCAGAEQAHAEAEAKIAaBLIAbhLQAEgKAHgEQAGgEAJACQAHADADAFQADAFgBAIIAABbIgTAAIAAhbIgcBNQgDAIgDADQgEAFgIAAQgGAAgEgFg");
	this.shape_4.setTransform(256,19.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgvBMIAAh6QAAgGACgGQACgFAEgEQAIgHAOAAIAjAAQAGgBAFACQAEABAEACQAFAFADAGQADAFAAAHIAAA2QAAAGgCAFQgCAGgDAEQgKALgMAAIguAAIAAAlgAgYg1QgDAEAAAFIAAAyIAAACQAAAHADABQAEADADAAIAjAAIABAAQAIgBACgIIAAgCIAAg3QgBgEgBgCQgCgBgEgBIgjAAQgHAAgDACg");
	this.shape_5.setTransform(242,21.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgRA5QgJAAgFgCQgGgCgDgEQgHgHAAgNIAAg6QAAgMAGgHQAHgGAMgCIADAAIAkAAIAFAAQAaAFAAAWIAAA6QAAAQgQAJQgGADgJAAgAgcgXIAAAuQAAAPAOAAIAdAAQAHAAADgDQAEgEAAgIIAAguQAAgHgEgDQgDgDgHAAIgdAAQgOAAAAANg");
	this.shape_6.setTransform(229.8,19.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHBgIAAg7QgFALgGAEQgFAEgIAAQgcAAAAg7QAAg4AdAAQAPAAAIARIAAg1IAPAAIAAA1QAIgRAPAAQAdAAAAA4QAAA7gcAAQgIAAgGgEQgFgEgFgLIAAA7gAAOglQgGAJAAADIAAAsQAGAOAEAEQAFAEAEAAQAIAAAEgJQADgJAAgZQAAgSgBgJQgCgIgEgDQgEgEgFAAQgGAAgGAHgAgmgkQgDAJAAAZQAAARABAJQACAJADAEQADAEAFAAQAFAAADgDQAEgDAEgHIAEgJIAAgsQgDgKgFgFQgGgEgEAAQgIgBgFAJg");
	this.shape_7.setTransform(217.3,19.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAvA5IAAhSQAAgLgMAAIgRAAQgDABgCACQgCAEAAAFIAABRIgSAAIAAhSIAAgCQgCgKgKABIgPAAIgCAAQgFAAgCACQgBACgBAFIAABUIgTAAIAAhUQAAgOAHgIQAGgHANAAIARAAIAFAAQAGACAEACQAFADABADQADgDAEgDQAEgCAGgCIAFAAIARAAQANAAAHAHQAGAIAAAOIAABUg");
	this.shape_8.setTransform(202.9,19.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRA5QgJAAgHgGQgIgGgEgHQgCgFAAgGIAAgOQAAgOAHgKQAEgFAGgDQAGgCAGgBIAvAAIAAgHQAAgDgDgCQgCgCgCAAIhFAAIAAgUIBDAAQAMAAAGAFQAHAFACALIABAFIAAA6QAAAIgFAGQgEAHgGAFQgGADgHAAgAgYAAQgDADAAAGIAAASQAAAHAFADQADABAHAAIAZAAQAQAAAAgLIAAgSQAAgGgEgDQgDgCgHgBIgdAAQgHABgDACg");
	this.shape_9.setTransform(189,19.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAdA5IAAhXQgCgGgMAAIgQAAQgIAAgCACQgDADAAAHIAAA0QAAAdghAAIAAgTQAIgBADgCQADgDAAgGIAAg0QAAgeAgAAIAQAAQAQAAAIAHQAJAIAAAPIAABTg");
	this.shape_10.setTransform(177,19.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAcA5IAAhXQgCgGgLAAIgdAAQgHAAgDACQgDADAAAHIAABRIgTAAIAAhTQAAgeAgAAIAdAAQAQAAAIAHQAIAIAAAPIAABTg");
	this.shape_11.setTransform(165,19.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAXA5IgugxQgFgFAAgDQAAgHAFgEIArgtIAbAAIg1A3IA3A6gAgwA5IAAhxIATAAIAABxg");
	this.shape_12.setTransform(147.7,19.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOA5QggAAAAgdIAAhUIATAAIAABWQACAIALAAIAgAAQAFgBACgDQADgDAAgFIAAhSIATAAIAABxg");
	this.shape_13.setTransform(135.5,19.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAvA5IAAhSQAAgLgMAAIgRAAQgDABgCACQgCAEAAAFIAABRIgSAAIAAhSIAAgCQgCgKgKABIgPAAIgCAAQgFAAgCACQgBACgBAFIAABUIgTAAIAAhUQAAgOAHgIQAGgHANAAIARAAIAFAAQAGACAEACQAFADABADQADgDAEgDQAEgCAGgCIAFAAIARAAQANAAAHAHQAGAIAAAOIAABUg");
	this.shape_14.setTransform(121.6,19.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRA5QgJAAgHgGQgJgGgCgHQgCgFgBgGIAAgOQABgOAGgKQAEgFAGgDQAFgCAIgBIAuAAIAAgHQAAgDgCgCQgCgCgEAAIhEAAIAAgUIBDAAQAMAAAGAFQAHAFACALIABAFIAAA6QAAAIgEAGQgFAHgGAFQgGADgHAAgAgYAAQgDADAAAGIAAASQAAAHAFADQADABAHAAIAZAAQAQAAAAgLIAAgSQgBgGgDgDQgDgCgHgBIgdAAQgGABgEACg");
	this.shape_15.setTransform(107.8,19.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgKA1QgEgDgCgIIgdhNIAABbIgTAAIAAhbQgCgQAOgFQAJgCAGAEQAHAEAEAKIAaBLIAbhLQAEgKAHgEQAGgEAJACQAHADADAFQADAFgBAIIAABbIgTAAIAAhbIgcBNQgDAIgDADQgEAFgIAAQgGAAgEgFg");
	this.shape_16.setTransform(93.8,19.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgKA1QgEgDgCgIIgdhNIAABbIgTAAIAAhbQgCgQAOgFQAJgCAGAEQAHAEAEAKIAaBLIAbhLQAEgKAHgEQAGgEAJACQAHADADAFQADAFgBAIIAABbIgTAAIAAhbIgcBNQgDAIgDADQgEAFgIAAQgGAAgEgFg");
	this.shape_17.setTransform(77.9,19.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRA5QgIAAgJgGQgHgGgDgHQgCgFAAgGIAAgOQAAgOAGgKQAEgFAGgDQAFgCAIgBIAtAAIAAgHQAAgDgBgCQgCgCgEAAIhDAAIAAgUIBCAAQAMAAAGAFQAHAFACALIAAAFIAAA6QAAAIgDAGQgFAHgGAFQgGADgHAAgAgYAAQgDADAAAGIAAASQAAAHAFADQADABAIAAIAYAAQAPAAAAgLIAAgSQAAgGgDgDQgDgCgGgBIgeAAQgHABgDACg");
	this.shape_18.setTransform(63.9,19.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgvBMIAAh6QAAgGACgGQACgFAEgEQAIgHAOAAIAjAAQAGgBAFACQAEABAEACQAFAFADAGQADAFAAAHIAAA2QAAAGgCAFQgCAGgDAEQgKALgMAAIguAAIAAAlgAgYg1QgDAEAAAFIAAAyIAAACQAAAHADABQAEADADAAIAjAAIABAAQAIgBACgIIAAgCIAAg3QgBgEgBgCQgCgBgEgBIgjAAQgHAAgDACg");
	this.shape_19.setTransform(51.7,21.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaA5IAAhUIABgHQAGgWAYAAIAVAAIAAATIgXAAQgFABgCAEQgCADAAAGIAABQg");
	this.shape_20.setTransform(42.6,19.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRA5QgJAAgFgCQgGgCgDgEQgHgHAAgNIAAg6QAAgMAGgHQAHgGAMgCIADAAIAkAAIAFAAQAaAFAAAWIAAA6QAAAQgQAJQgGADgJAAgAgcgXIAAAuQAAAPAOAAIAdAAQAHAAADgDQAEgEAAgIIAAguQAAgHgEgDQgDgDgHAAIgdAAQgOAAAAANg");
	this.shape_21.setTransform(32.5,19.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBMIAAh6QAAgGACgGQACgFAEgEQAIgHAOAAIAjAAQAGgBAFACQAEABAEACQAFAFADAGQADAFAAAHIAAA2QAAAGgCAFQgCAGgDAEQgKALgMAAIguAAIAAAlgAgYg1QgDAEAAAFIAAAyIAAACQAAAHADABQAEADADAAIAjAAIABAAQAIgBACgIIAAgCIAAg3QgBgEgBgCQgCgBgEgBIgjAAQgHAAgDACg");
	this.shape_22.setTransform(20.4,21.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAhBMIAAiAIhBAAIAACAIgWAAIAAiXIBtAAIAACXg");
	this.shape_23.setTransform(7.5,17.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ37, new cjs.Rectangle(-1.1,1.8,323.6,30.7), null);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBZQg3AAgCgpQgBgdAQgTQAQgSAagCQAPgBAUABQAMABAFgEQAFgEACgLQACgMgDgHQgFgGgNAAIgvgBQgPAAAAgBIABgLQACgIAEgDIAIAAIA2AAQATABALANQALAOgDARQgGApgKAtQgKArgsACgAgjAMQgHAGgCAJIgDASQgCAIAEAGQAFAHAIgBIAqAAQAIABAHgHQAGgGACgHIAIgoIg8AAQgJAAgHAGg");
	this.shape.setTransform(114,19.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdBZIAdieQABgJAEgFQAFgFAJAAIALAAIgeCkQgCANgNAAg");
	this.shape_1.setTransform(102.9,18.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsB7QgWAAgMgNQgLgNADgUIAQhRQAEgWARgNQARgOAXAAIAmAAQASAAAEgRIAGgkQAEgQANAAIAOAAIglDDQgFAYgRANQgRANgZAAgAgigVQgHAGgCAJIgPBSQgCAKAFAGQAGAGALAAIAfAAQAZAAAFgZIAIgpIAAAAIAJgtQABgGgDgEQgDgFgHAAIgtAAQgKAAgHAHg");
	this.shape_2.setTransform(91.9,15.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBZQgWAAgMgOQgMgNAEgVIAPhPQAEgVAQgOQAQgNAWgBQARgBAZABQASABAKAMQALAMgCARIgEAXQgFATgRAMQgQANgVAAIg6AAIgEATQgCAKAGAGQAFAGALAAIAtAAQAJAAAEACQAGACADAGQADAGgCAKgAgIg+QgIAAgHAGQgHAGgCAIIgHAnIA7AAQAJAAAHgGQAHgGACgIIAEgTQABgIgEgGQgFgHgIAAg");
	this.shape_3.setTransform(73.7,18.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABNByQgLABABgTIAZiVQAEgNAAgHQABgNgNgCQgxgHgHAeQgFAXgNBKIgKA+IgEANQgEAHgIgBQgLgBAAgJIADgOIAYiJIAAgJQAEgWgEgFQgDgEgWAAQgWAAgIAHQgIAHgEAVIgbCUQgEATgMgBQgJgBgBgHIABgOIAOhIQAIgrAEgdQAKhNBZAVQAHACAUgBIAdgCQASgCALABQAOACAKANQAJANgDAOQgQBigOBJQgDAMgLAAIAAAAg");
	this.shape_4.setTransform(52.3,16.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBZIAeieQACgTARAAIALAAIgeCkQgCANgNAAg");
	this.shape_5.setTransform(162.7,18.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag8BZIAYh/QAEgVARgOQAQgOAUAAIAogBQAAALgGAHQgGAIgIAAIgWAAQgXAAgFAYIgVBxQgCAIgDADQgEADgJAAg");
	this.shape_6.setTransform(212.6,18.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAqBZQgIAAgDgHQgDgGACgIIAUhlQADgRgFgGQgGgGgSAAIgUAAQgaAAgFAZIgWBvQgCAPgNAAIgPAAIAZh/QAEgVAQgOQAQgNAWgBIAjAAQAVABALANQALANgDATIgZCCg");
	this.shape_7.setTransform(148.6,18.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhMByIACgMQAEgOAPAAIA3AAQAZAAAFgYIAGgeQABgJgFgHQgFgFgKAAIggAAQgYAAgMgNQgMgNAEgXIAGgdQAEgVARgOQAQgNAVAAIBHAAIgCANQgCAMgPAAIg1AAQgaABgEAYIgGAcQgEAXAYABIAfAAQAYAAAMAMQALAOgDAVIgHAiQgEASgQANQgRANgSAAg");
	this.shape_8.setTransform(131.1,16.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AghBZQgWAAgMgOQgMgNAEgVIAPhPQAEgVAQgOQAQgNAXgBQAWgBATABQASABAKAMQALAMgCARQgBAKgDANQgFATgRAMQgQANgVAAIg6AAIgEATQgDAWAYABIAsgBQAJAAAFACQAFACADAGQADAGgCAKgAgXg4QgGAGgDAIIgHAnIA7AAQAJAAAHgGQAHgGACgIQADgMABgHQABgIgEgGQgFgGgIAAIgpAAQgIAAgHAGg");
	this.shape_9.setTransform(196,18.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhYB/IAnjLQAFgXARgNQARgOAXAAQAUgBARACQAUABALANQAKAMgDATIgQBTQgFAWgRAMQgRANgXAAIglAAQgSAAgEARIgJAvQgCANgMAAgAgVhNIgQBSQgCAMADAEQAEAEANAAQASABARgBQALAAAIgGQAHgGACgKQAKgtAGgmQACgKgGgFQgFgGgLAAIggAAQgZAAgEAYg");
	this.shape_10.setTransform(175.8,22.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMCdIAUhSQAfgDAUgYQATgYgDgeQgDgfgYgUQgYgUgeADQgfADgUAYQgUAYADAeIAAABIhMAkQgEgPgBgOQgGhAApgyQApgyBBgGQBAgHAyAqQAyApAGBBQAHBAgqAyQgpAyhBAGIgPABIgMAAg");
	this.shape_11.setTransform(15.7,15.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgCAMIgwgUIBlguIgaBtg");
	this.shape_12.setTransform(5.6,24.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAZQgLgJgBgNQgBgMAIgLQAJgKANgBQAMgBALAIQAKAJABANQACAMgJALQgIAKgOABIgDAAQgKAAgJgHg");
	this.shape_13.setTransform(15.7,15.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEAOQgFgCgCgFQgCgGACgEQADgGAFgDQAEgDAFACQAEACACAFQACAGgCAFQgCAFgFADQgDACgDAAIgDgBg");
	this.shape_14.setTransform(105.5,6.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAOQgFgCgCgFQgCgFACgFQACgGAFgDQAEgDAFACQAFACACAFQACAGgCAFQgCAFgFADQgDACgDAAIgDgBg");
	this.shape_15.setTransform(165.3,6.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ36, new cjs.Rectangle(0,0,218.7,35.4), null);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao9D9QhpABhLhLQhKhKAAhpQAAhoBKhLQBLhJBpgBIR7AAQBqABBJBJQBLBLAABoQAABphLBKQhJBLhqgBg");
	this.shape.setTransform(95.1,29.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ35, new cjs.Rectangle(12.4,4.1,165.6,50.7), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBSQhSBSh0AAIx9AAQh0AAhShSQhShSAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ34, new cjs.Rectangle(-1,-1,173,58), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AicBdQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAaiGQABgEAEAAIAJAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgBAEQAHgFAHgCQAJgDAIAAQAKAAAJAEQAIADAFAHQAFAHACAKQABAOgCAIQgFAQgDAHQgGAJgIAIQgIAHgJADQgKAEgKAAQgIAAgIgDQgGgCgFgFIgIArQAAADgFAAgAhqggQgIADgGAGIgLA1QAEAGAHADQAGADAIAAQAHAAAHgCQAGgDAGgFQAFgFAEgHQAEgIACgJQACgJgBgHQgBgIgEgFQgDgEgGgDQgFgCgHAAQgJAAgHADgAi7BLQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIADgQIhIAAIgEAQQgBAEgDAAIgJAAQgEAAABgEIAFgbQABgEADAAIAGAAQAJgKAGgKIANgUIAKgWIAIgWQABgEADAAIAtAAQABAAAAAAQABABAAAAQABABAAAAQAAABgBABIgQBUIAMAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgFAbQgBAEgEAAgAjdAEQgOAYgKAMIAtAAIAPhJIgVAAQgJAZgGAMgAHAA4IgKgDQgIgEgGgHQgFgHgBgKQgCgKACgMQADgMAFgKQAGgKAIgHQAIgHALgDQAKgEAMAAQAJAAAHACQAHACAFAEQAFAEACAGQACAFgBAHQgBAHgEAFQgFAGgHADQgHAEgLACQgMADgPAAIgVAAQgBAIACAGQACAGAEAEQADAEAGACQAGACAHAAQAIAAAHgBQAHgCAGgDQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAIABACIgBAJQAAADgEACQgGADgIABQgIACgJAAgAHQgiQgGACgFAEQgGAEgDAGQgEAGgDAIIARAAIAUgBQAIgBAGgCQAFgCADgDQADgDABgEQAAgEgBgDQgBgDgDgCQgGgDgMAAQgHAAgGABgAFUA4IgKgDQgJgEgFgHQgFgHgCgKQgBgKACgMQACgMAGgKQAFgKAJgHQAIgHAKgDQALgEALAAQAJAAAIACQAHACAFAEQAFAEACAGQACAFgCAHQgBAHgEAFQgEAGgHADQgIAEgLACQgLADgPAAIgVAAQgBAIACAGQABAGAEAEQAEAEAGACQAFACAHAAQAIAAAHgBQAIgCAGgDQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAAAIABACIAAAJQgBADgDACQgHADgIABQgIACgJAAgAFjgiQgGACgFAEQgFAEgEAGQgEAGgCAIIARAAIAUgBQAIgBAFgCQAGgCADgDQADgDAAgEQABgEgBgDQgCgDgDgCQgGgDgLAAQgHAAgHABgABvA4QgGgBgEgDQgEgCgDgDIgGgIQgDgGgCgPQAAgJADgSIAEgSQADgJAEgHQADgHAFgGQAFgHAGgFQAGgFAHgEQAIgEAJgDIAUgFIAXgDQAEgBAAAEIgBAIQgBADgDABQgRABgNADQgNAEgJAFQgKAFgGAIQgHAIgEALQAHgGAJgDQAIgCAJAAQAKAAAHADQAIADAEAHQAFAGABAKQACAJgDALQgCAMgFAKQgFAJgIAHQgHAGgJAEQgIADgKAAQgGAAgFgBgAB5gZQgKAEgIAIIgBAEQgCANAAAKQABAKADAGQADAHAFADQAGACAHAAQAGAAAGgCQAFgDAFgEQAEgFADgHQAEgGABgJQACgHgBgHQAAgGgDgFQgDgFgEgCQgFgDgGAAQgKAAgIAEgAgDA4IgJgDQgJgEgFgHQgFgIgBgJQgCgKACgMQADgLAFgKQAGgKAHgHQAIgHAJgEQAHgDAPgBQAIAAAMAEQAIAEAFAHQAGAHABAKQACAKgDALQgCAMgFAKQgGAJgIAIQgIAHgKAEQgKAEgLAAgAALghQgHADgEAFQgGAFgDAIQgEAHgCAIQgBAJABAHQABAIADAFQADAFAFADQAFACAIAAQAHAAAHgCQAHgDAFgFQAFgGAEgHQAEgHABgJQACgIgBgHQgBgIgDgFQgDgFgGgDQgFgCgIAAQgIAAgGACgAlbA4IgJgDQgJgEgFgHQgFgIgBgJQgCgKACgMQADgLAFgKQAGgKAHgHQAIgHAKgEQAHgDAPgBQAIAAAMAEQAIAEAFAHQAGAHABAKQACAKgDALQgCAMgFAKQgGAJgIAIQgIAHgKAEQgKAEgLAAgAlMghQgHADgFAFQgGAFgDAIQgEAHgCAIQgBAJABAHQABAIADAFQADAFAFADQAGACAIAAQAHAAAHgCQAHgDAFgFQAFgGAEgHQAEgHABgJQACgIgBgHQgBgIgDgFQgDgFgGgDQgFgCgIAAQgIAAgGACgAEJA3QgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAIgtIg3AAIgJAtQAAAEgEAAIgJAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAShfQABgEAEAAIAJAAQABAAABAAQABABAAAAQAAABAAAAQABABgBABIgHAkIA3AAIAHgkQABgEAEAAIAJAAQAEAAgBAEIgTBfQAAAEgEAAgAmoA3QAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAYh4IhJAAIgXB4IgCACIgDACIgKAAQAAAAgBAAQgBgBAAAAQAAgBgBAAQAAgBAAgBIAaiDQAAgEAFAAIBkAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgaCDIgCACIgDACg");
	this.shape.setTransform(51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(0,0,103.5,18.7), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao/D/QhqgBhKhKQhLhLAAhpQAAhpBLhKQBKhLBqAAIR/AAQBqAABKBLQBKBKABBpQgBBphKBLQhKBKhqABg");
	this.shape.setTransform(83.5,27.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0.5,1.8,166.1,50.9), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBSQhSBSh0AAIx9AAQh0AAhShSQhShSAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(-1,-1,173,58), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD0DeQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIAaiHQAAgEAEAAIAKAAQABAAAAAAQABAAAAABQAAAAABABQAAABAAABIgBAEQAGgFAIgCQAIgDAJAAQAKAAAIAEQAIADAFAHQAGAHABAKQABAOgCAJQgEAQgEAHQgFAJgIAIQgIAHgKADQgJAEgKAAQgJAAgHgDQgHgCgEgFIgJArQAAADgEAAgAEmBgQgIADgGAGIgKA2QAEAGAGADQAHADAIAAQAHAAAGgCQAHgDAFgFQAGgFADgHQAEgIACgJQACgKgBgHQgBgIgDgFQgEgEgFgDQgGgCgHAAQgIAAgIADgA0dDeQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIAaiHQAAgEAEAAIAKAAQABAAAAAAQABAAAAABQAAAAABABQAAABAAABIgBAEQAGgFAIgCQAIgDAJAAQAKAAAIAEQAIADAFAHQAGAHABAKQABAOgCAJQgEAQgEAHQgFAJgIAIQgIAHgKADQgJAEgKAAQgJAAgHgDQgHgCgEgFIgJArQAAADgEAAgAzrBgQgIADgGAGIgKA2QAEAGAGADQAHADAIAAQAHAAAGgCQAHgDAFgFQAGgFADgHQAEgIACgJQACgKgBgHQgBgIgDgFQgEgEgFgDQgGgCgHAAQgIAAgIADgARdC5IgJgDQgIgEgFgHQgFgIgCgJQgBgKACgMQACgMAGgKQAFgKAIgHQAIgHAKgEQAGgDAPgBQAIAAAMAEQAJAEAFAHQAFAHACAKQABAKgCAMQgCAMgGAKQgFAJgIAIQgIAHgKAEQgKAEgMAAgARsBfQgHADgFAFQgFAFgEAIQgDAHgCAJQgCAJABAHQABAIADAFQADAFAGADQAFACAIAAQAIAAAHgCQAGgDAGgFQAFgGADgHQAEgHACgJQABgJAAgHQgBgIgDgFQgEgFgFgDQgGgCgHAAQgIAAgHACgALfC6QgBgBgBAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIADgIQABgEADABIAHABQAFAAAEgCQAEgBAEgDQADgDACgFQACgFABgIIAMg9QABgEAEAAIA9AAQAEAAgBAEIgTBgQgBAEgDAAIgJAAQgEAAABgEIAQhVIgjAAIgLA3QgBAJgEAHQgEAHgFAEQgFAFgHACQgHACgJAAgAIEC5QgFgBgEgDQgFgCgDgDIgFgIQgDgGgCgPQgBgJADgTIAFgSQACgJAEgHQAEgHAEgGQAFgHAGgFQAGgFAIgEIAQgHIAUgFIAYgDQADgBAAAEIgBAIQAAADgEABQgRABgMADQgNAEgKAFQgJAFgHAIQgGAIgFALQAIgGAJgDQAIgCAIAAQAKAAAIADQAHADAFAHQAFAGABAKQABAJgCAMQgCAMgGAKQgFAJgHAHQgHAGgJAEQgJADgJAAQgHAAgFgBgAIOBnQgJAEgIAIIgBAEQgDAOABAKQAAAKADAGQADAHAGADQAFACAHAAQAHAAAFgCQAGgDAEgEQAFgFADgHQADgGACgJQABgIAAgHQgBgGgDgFQgCgFgFgCQgEgDgHAAQgJAAgJAEgAgPC2QgIgDgFgHQgGgIgBgJQgCgLACgMQACgJAGgOQAGgKAIgHQAIgHAIgDQAKgEAKAAQAJAAAHADQAHACAEAFIABgEQAAgEAEAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgTBgQAAAEgFAAIgJAAQgDAAAAgEIABgEQgGAFgIACQgIADgJAAQgJAAgIgEgAAIBfQgGADgFAEQgFAFgEAIQgEAHgCAKQgBAJABAIQABAHADAFQADAFAGADQAFACAGAAQAJAAAIgDQAHgDAGgGIALg2QgEgGgGgDQgHgDgIAAQgHAAgHACgAilC6QgBgBAAAAQgBAAAAgBQgBAAAAgBQAAgBABAAIACgIQABgEAEABIAGABQAGAAAEgCQAEgBADgDQADgDACgFQADgFABgIIAMg9QABgEAEAAIA9AAQAEAAgBAEIgTBgQgBAEgEAAIgJAAQgEAAABgEIARhVIgjAAIgLA3QgCAJgEAHQgDAHgGAEQgFAFgHACQgHACgIAAgAl/C5QgGgBgEgDQgEgCgDgDIgGgIQgDgGgCgPQAAgJADgTIAEgSQADgJAEgHQADgHAFgGQAFgHAGgFQAGgFAHgEQAIgEAJgDIAUgFIAXgDQAEgBAAAEIgBAIQgBADgDABQgRABgNADQgNAEgJAFQgKAFgGAIQgHAIgEALQAHgGAJgDQAIgCAJAAQAKAAAHADQAIADAEAHQAFAGABAKQACAJgDAMQgCAMgFAKQgFAJgIAHQgHAGgJAEQgIADgKAAQgGAAgFgBgAl1BnQgKAEgIAIIgBAEQgCAOAAAKQABAKADAGQADAHAFADQAGACAHAAQAGAAAGgCQAFgDAFgEQAEgFADgHQAEgGABgJQACgIgBgHQAAgGgDgFQgDgFgEgCQgFgDgGAAQgKAAgIAEgApFC2QgIgDgFgHQgGgIgBgJQgCgLACgMQACgJAGgOQAGgKAIgHQAIgHAJgDQAKgEAKAAQAJAAAHADQAHACAEAFIABgEQAAgEAEAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgTBgQAAAEgFAAIgJAAQgDAAAAgEIABgEQgGAFgIACQgIADgJAAQgKAAgIgEgAotBfQgGADgGAEQgFAFgEAIQgEAHgCAKQgBAJABAIQABAHADAFQADAFAGADQAFACAHAAQAJAAAIgDQAHgDAGgGIALg2QgEgGgGgDQgHgDgIAAQgHAAgHACgAtFC2QgIgDgFgHQgFgIgCgJQgCgLADgMQABgJAHgOQAFgKAIgHQAIgHAKgDQAJgEALAAQAIAAAHADQAHACAEAFIABgEQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgTBgQAAAEgEAAIgJAAQgEAAABgEIAAgEQgGAFgIACQgIADgJAAQgKAAgIgEgAssBfQgHADgFAEQgGAFgDAIQgEAHgCAKQgCAJABAIQABAHAEAFQADAFAFADQAGACAHAAQAIAAAIgDQAIgDAGgGIAKg2QgDgGgHgDQgGgDgJAAQgHAAgGACgAvaC6QgBgBgBAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIADgIQABgEADABIAHABQAFAAAEgCQAEgBAEgDQADgDACgFQACgFABgIIAMg9QABgEAEAAIA9AAQAEAAgBAEIgTBgQgBAEgDAAIgJAAQgEAAABgEIAQhVIgjAAIgLA3QgBAJgEAHQgEAHgFAEQgFAFgHACQgHACgJAAgAyCC5IgKgDQgJgEgFgHQgFgHgCgKQgBgKACgMQACgNAGgKQAFgKAJgHQAIgHAKgDQALgEALAAQAJAAAIACQAHACAFAEQAFAEACAGQACAFgCAHQgBAHgEAFQgEAGgHAEQgIAEgLACQgLADgPAAIgVAAQgBAIACAGQABAGAEAEQAEAEAGACQAFACAHAAQAIAAAHgBQAIgCAGgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAABIABACIAAAJQgBADgDACQgHADgIABQgIACgJAAgAxzBeQgGACgFAEQgFAEgEAGQgEAGgCAIIARAAIAUgBQAIgBAFgCQAGgCADgDQADgDAAgEQABgEgBgDQgCgDgDgCQgGgDgLAAQgHAAgHABgAUAC4QgEAAABgEIAPhMIhGBNQgDADgDAAIgMAAQgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgPBNIBGhOQACgDADAAIAMAAQAEAAgBAEIgSBgQgBAEgEAAgAQUC4QgEAAABgEIAIgtIg3AAIgJAtQAAAEgEAAIgJAAQgEAAABgEIAShgQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgHAkIA3AAIAHgkQABgEAEAAIAJAAQAEAAgBAEIgTBgQAAAEgEAAgANgC4QgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgHAhIAUAAQAMAAAJACQAKACAFAEQAGAEACAGQACAHgBAIQgCAJgFAGQgEAHgIAEQgHAEgKACQgJACgNAAgANwCpIAVAAIAQgBQAGgBAEgCQAFgCACgEQACgDABgGQABgFgBgDQgBgEgDgCQgDgCgHgCIgPgBIgUAAgAK/C4QgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgTBgQAAAEgEAAgAJWC4QgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgHAhIAUAAQAMAAAJACQAKACAFAEQAGAEACAGQACAHgBAIQgCAJgFAGQgEAHgIAEQgHAEgKACQgJACgNAAgAJmCpIAVAAIAQgBQAGgBAEgCQAFgCACgEQACgDABgGQABgFgBgDQgBgEgDgCQgDgCgHgCIgPgBIgUAAgAG8C4QgEAAABgEIAPhMIhGBNQgDADgDAAIgMAAQgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgPBNIBGhOQACgDADAAIAMAAQAEAAgBAEIgSBgQgBAEgEAAgADQC4QgEAAABgEIAQhVIgzAAIgRBVQAAAEgEAAIgJAAQgEAAABgEIAShgQABgEAEAAIBNAAQAEAAgBAEIgTBgQAAAEgEAAgAjEC4QgEAAABgEIAShgQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgTBgQAAAEgEAAgAktC4QgEAAABgEIAShgQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgGAhIATAAQANAAAJACQAJACAGAEQAFAEADAGQACAHgCAIQgCAJgEAGQgFAHgHAEQgHAEgKACQgKACgMAAgAkdCpIAUAAIAQgBQAGgBAFgCQAEgCACgEQADgDABgGQABgFgBgDQgBgEgEgCQgDgCgGgCIgPgBIgVAAgAqGC4QgDAAAAgEIAPhLIgqArQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAIgGAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAIgYgrIgPBLQAAAEgEAAIgKAAQgDAAAAgEIAThgQABgEADAAIALAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAcAyIAwgyIADgCIAMAAQABAAAAAAQABAAAAABQAAAAAAABQABABgBABIgSBgQgBAEgDAAgAvyC4QgDAAgDgDIgmgwIgJAvQAAAEgEAAIgJAAQgEAAABgEIAShgQABgEAEAAIAJAAQAEAAgBAEIgIAqIAzgrQADgDAEAAIANAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBABIg2AuIAoAyIABACQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABgBAAgATqA/QgFgBgDgEQgEgDgCgFQgCgFABgGQAAgEAEAAIAIAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABQAAAHAEADQADAEAHAAQAHAAAFgEQAGgEACgGQABgBAAgBQABAAAAgBQABAAAAAAQABAAAAAAIAIAAQAEAAgBAEQgCAGgEAFQgEAFgFADQgFAEgFABQgGACgGAAQgHAAgFgCgAmcgtIgBgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAFgEADgFQAEgFABgFQgFAAgDgEQgBgDABgFQABgGAEgDQADgDAGAAQAGAAACADQADAEgCAIIgDAKIgGAJIgHAJIgJAGIgBAAIgCAAgAqog1QgBAAAAAAQgBAAAAgBQAAAAAAgBQAAgBAAAAIADgRIhJAAIgDARQgBADgEAAIgJAAQgEAAABgDIAFgcQABgDAEAAIAGAAQAIgKAHgKIAMgVIAKgWIAIgXQABgDAEAAIAsAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgRBWIANAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIgGAcQgBADgDAAgArKh8QgOAZgJAMIAtAAIAOhLIgUAAQgJAagHAMgALzhKQgIgEgFgHQgGgHgBgKQgCgKACgNQACgIAGgOQAGgKAIgHQAIgHAJgEQAKgEAKAAQAJAAAHADQAHADAEAFIABgFQAAgDAEAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgTBgQAAAEgFAAIgJAAQgDAAAAgEIABgEQgGAFgIADQgIADgJAAQgKAAgIgEgAMLiiQgGADgGAFQgFAFgEAHQgEAIgCAJQgBAKABAHQABAIADAFQADAFAGACQAFADAHAAQAJAAAIgDQAHgEAGgGIALg1QgEgGgGgEQgHgDgIAAQgHAAgHACgAHyhKQgIgEgFgHQgGgHgBgKQgCgKACgNQACgIAGgOQAGgKAIgHQAIgHAJgEQAKgEAKAAQAJAAAHADQAHADAEAFIABgFQAAgDAEAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgTBgQAAAEgFAAIgJAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIABgEQgGAFgIADQgIADgJAAQgKAAgIgEgAIKiiQgGADgGAFQgFAFgEAHQgEAIgCAJQgBAKABAHQABAIADAFQADAFAGACQAFADAHAAQAJAAAIgDQAHgEAGgGIALg1QgEgGgGgEQgHgDgIAAQgHAAgHACgAA6hIQgGgBgEgCQgEgCgDgEIgGgIQgDgGgCgPQAAgIADgUIAEgSQADgIAEgHQADgIAFgGQAFgGAGgFQAGgFAHgEQAIgEAJgDIAUgFIAXgEQAEAAAAAEIgBAIQgBADgDAAQgRACgNADQgNADgJAFQgKAGgGAHQgHAIgEALQAHgGAJgCQAIgDAJAAQAKAAAHADQAIAEAEAGQAFAHABAJQACAKgDAMQgCAMgFAJQgFAKgIAGQgHAHgJADQgIAEgKAAQgGAAgFgCgABEiaQgKAEgIAIIgBAEQgCAOAAALQABAJADAHQADAGAFADQAGADAHAAQAGAAAGgDQAFgCAFgFQAEgFADgGQAEgHABgIQACgIgBgHQAAgHgDgEQgDgFgEgDQgFgCgGAAQgKAAgIADgAg4hHIgJgDQgJgEgFgIQgFgHgBgKQgCgKACgMQADgLAFgKQAGgKAHgHQAIgIAKgEQAHgCAPgCQAIAAAMAEQAHAEAFAIQAGAHABAKQACAKgDALQgCAMgFAKQgGAKgHAHQgIAIgKAEQgKAEgLAAgAgpihQgHADgFAFQgGAFgDAHQgEAIgCAIQgBAJABAIQABAHADAFQADAFAFADQAGADAIAAQAHAAAHgDQAHgDAFgFQAFgFAEgHQAEgIABgJQACgIgBgIQgBgHgDgFQgDgFgGgDQgFgDgIAAQgIAAgGADgApthKQgIgEgFgHQgFgHgCgKQgCgKADgNQABgIAHgOQAFgKAIgHQAIgHAKgEQAJgEALAAQAIAAAHADQAHADAEAFIABgFQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAIgJAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAgEQgGAFgIADQgIADgJAAQgKAAgIgEgApUiiQgHADgFAFQgGAFgDAHQgEAIgCAJQgCAKABAHQABAIAEAFQADAFAFACQAGADAHAAQAIAAAIgDQAIgEAGgGIAKg1QgDgGgHgEQgGgDgJAAQgHAAgGACgAtYhKQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIADgIQABgEADABQAIADATACIAOgBIAKgDQAEgCADgDQACgDABgDQABgEgCgEQgCgEgFgCQgEgDgIgBIgSgCQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIACgHQABgEADAAIARgBQAIgBAFgCQAGgCADgDQAEgDABgFQABgGgGgDIgIgCIgNgBQgTABgIADQgEABAAgEIABgJQAAgDAEgBQAJgCAUgBQALAAAIACQAIACAFADQAGADABAGQACAFgBAGQgBAFgDAFIgHAHIgKAFIgLADIAMAEQAEADADAEQADADABAEIAAAJQgBAIgFAGQgFAFgHAEQgHADgJACQgJACgKAAQgVgBgJgDgAunhHIgJgDQgJgEgFgIQgFgHgBgKQgCgKACgMQADgLAFgKQAGgKAHgHQAIgIAKgEQAHgCAPgCQAIAAAMAEQAIAEAFAIQAGAHABAKQACAKgDALQgCAMgFAKQgGAKgIAHQgIAIgKAEQgKAEgLAAgAuYihQgHADgFAFQgGAFgDAHQgEAIgCAIQgBAJABAIQABAHADAFQADAFAFADQAGADAIAAQAHAAAHgDQAHgDAFgFQAFgFAEgHQAEgIABgJQACgIgBgIQgBgHgDgFQgDgFgGgDQgFgDgIAAQgIAAgGADgAwQhKQgKgEgGgHQgGgHgCgKQgBgHACgQQABgIAHgOQAGgKAJgHQAIgHALgEQALgEALAAIAPABQAGABAFADQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABIgDAJQAAAAAAABQgBABAAAAQgBAAgBAAQAAAAgBAAQgFgDgGgBIgMgBQgIAAgIADQgHACgGAFQgGAFgEAIQgEAHgCAJQgCAKABAHQACAHAEAFQAEAFAGADQAHADAJAAIAMgBIAMgEQAFgDgBAFIgBAIQAAAEgDABQgGACgHABQgHACgHAAQgQgCgGgCgAJShJQgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgRBWIAgAAIAQhWQABgDAEAAIAJAAQAEAAgBADIgQBWIAfAAIARhWQABgDADAAIAJAAQAEAAgBADIgSBgQAAAEgFAAgAF3hJQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAShgQABgDAEAAIAbAAQAKAAAIABQAJACAFADQAFADACAFQACAFgBAHQgBAHgFAGQgGAGgJADIAJAEIAGAGQACADAAAEQABAEgBAFQgBAHgFAFQgEAGgHAEQgHADgJACQgJACgMAAgAGFhXIAQAAIAPgBIALgDQAEgCADgDQACgDABgEQABgEgBgDQgCgDgDgCIgKgEIgPgBIgPAAgAGOiGIAcAAIAJgDQAEgCACgCQADgDAAgEQABgEgBgCQgBgDgDgCIgJgCIgbgBgAD1hJQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAgACMhJQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgGAhIATAAQANAAAJACQAJACAGAEQAFAEADAHQACAGgCAJQgCAJgEAGQgFAGgHAEQgHAEgKACQgKACgMAAgACchXIAUAAIAQgBQAGgBAFgDQAEgCACgEQADgDABgFQABgFgBgEQgBgDgEgDQgDgCgGgBIgPgBIgVAAgAichJQgEAAABgEIARhVIgjAAQgDAAAAgEIACgHQABgDADAAIBWAAQAEAAgBADIgCAHQAAAEgEAAIgiAAIgRBVQgBAEgEAAgAjihJQgEAAABgEIAHgnQgGAEgIACQgHACgIAAQgJAAgHgDQgGgDgEgGQgEgGgBgJQgBgJACgMIAEgRQABgDADAAIAJAAQAEAAgBADIgDASQgCAIABAGQAAAGACAEQACAEAFACQAEACAGAAQAIAAAHgDQAHgCAGgFIAHgoQABgDAEAAIAJAAQAEAAgBADIgSBgQgBAEgEAAgAnFhJQgDAAAAgEIAJgtIg3AAIgJAtQAAAEgEAAIgKAAQgDAAAAgEIAThgQABgDADAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgHAlIA3AAIAHglQABgDADAAIAKAAQAEAAgBADIgTBgQAAAEgEAAg");
	this.shape.setTransform(106.6,29.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(-24.6,7.5,262.5,44.4), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHoBJQgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgLIAEgNIAGgKIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAHQgBAHgFAGQgFAHgIAEQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAH5gDQgFADgDAIIADAAQAOAAAGgCQAFgCABgEQABgDgCgCQgDgCgFAAQgHAAgFAEgAA5BGQgHgDgFgHQgEgHgCgKQgBgLACgMQADgNAFgJQAGgKAHgHQAHgHAJgEQAIgDAJAAQAJAAAGADQAHADACAFIABgFQABgEAEAAIArAAQAEAAgBAEIgTBfQgBAEgDAAIgrAAQgEAAABgEIAAgFQgEAFgHADQgIADgJAAQgJAAgHgEgABiAAQgEAGgDAOQgCAOABAGQACAFAGAAQAEAAADgCIAJgtQgCgCgEAAQgGAAgEAEgAkUBGIgJgEIgIgHQgEgDgCgEQgCgFgBgFIgBgKIABgMQABgIAIgOQAEgGALgLQAHgEAPgGQAIgDASgBQAJAAAPAEQAGABAEADIAIAGIAFAIIAEAJIABAKIgBAMIgEAMIgFAKQgKANgGAEQgNAJgIACQgRAEgJAAQgSgBgHgDgAj0AAQgEAGgDAOQgDANACAHQACAFAEAAQAFAAAEgFQAEgHACgNQADgOgCgGQgBgEgFAAQgFAAgDAEgAmYBGIgKgEIgIgHQgDgDgCgEQgDgFgBgFIgBgKIABgMQACgIAHgOQAEgGAMgLQAGgEAPgGQAIgDASgBQAKAAAPAEQAFABAEADIAIAGIAGAIIADAJIABAKIgBAMIgDAMIgGAKQgJANgGAEQgOAJgIACQgRAEgJAAQgRgBgHgDgAl5AAQgEAGgDAOQgCANACAHQABAFAFAAQAFAAADgFQAEgHADgNQADgOgCgGQgCgEgEAAQgFAAgEAEgAF+BIQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgJgtIgJAsQAAAEgEAAIgrAAQgEAAABgEIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgOBMIAVgiQADgDACAAIAvAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIggAoIAQAzQAAABABAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAgADzBIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAThfQAAgEAEAAIAsAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgTBfQAAAEgEAAgACtBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgbCKQAAAEgEAAgAhnBIQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgJgtIgJAsQAAAEgEAAIgrAAQgEAAABgEIAbiKQAAgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgOBMIAVgiQADgDACAAIAvAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIggAoIAQAzQAAABABAAQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBABQAAAAgBAAgAo1BIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAaiDQAAgEAFAAIAuAAQAAAAABAAQABAAAAABQAAAAABABQAAABAAABIgUBjIA7AAQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIgGAdQAAAEgEAAgAgeAVQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAFgYQABgEADAAIA1AAQAEAAgBAEIgFAYQAAADgEAAgAETgoQgFgBgDgCQgDgCgBgDQgBgDABgFIADgIQACgDAEgCIAJgDIAMgBIAMABQAFABADACQADACABADQABADgBAFQgBAFgCADQgCADgEACQgEACgFABIgMABg");
	this.shape.setTransform(56.9,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,113.8,14.9), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgGCzIAygzQgTgUAAgdQAAgfAWgWQAWgWAfAAQAfAAAWAWQAWAWAAAfQAAAfgWAWQgWAWgfAAQgdAAgUgTIgzAzgAA2AhQgTATAAAbQAAAbATATQATATAbAAQAbAAATgTQATgTAAgbQAAgbgTgTQgTgTgbAAQgbAAgTATgAhVCDIAVhIIAAgZIgGAAQgnABgbAbQgcAcAAAnIAAAPIgKAAIAAgPQAAgrAfgfQAegeArgBIgLgPQgXgbAAglIAAhGIAKAAIAABGQAAAhAVAaIARAUIAiAAIARgUQAUgaAAghIAAg8QgbgBgdgGQgZgFgPgJIgFgBIAFgJIAEABQAPAJAaAFQAcAGAcAAIAFAAIAABGQAAAlgXAbIgKAPQAPAAATAHIAEABIgDAKIgFgCQgPgGgPAAIgGAAIAAAZIAUBIIgtAtgAhJB/IAiAjIAigjIgSg/IggAAgAg2A2IAeAAIAAgUIgeAAgAAuBaIgBgLQAAgWAQgQQAQgRAXAAIAFAAIAAAKIgFAAQgTAAgNANQgNANAAATIACAOIgKACgAAjgtIAAgKIAFAAQAGAAAFgFQAEgEAAgGQAAgGgEgFQgFgEgGAAIgFAAIAAgoQAAgPgJgNQgJgLgPgFQgYgGgRAAQgRAAgZAGQgPAFgJALQgJANAAAPIAAAoIgFAAQgGAAgFAEQgEAFAAAGQAAAGAEAEQAFAFAGAAIAFAAIAAAKIgFAAQgLAAgGgHQgIgHAAgLQAAgJAFgHQAHgGAIgCIAAgfQAAgSALgQQAMgOARgFQAZgHAUAAQAUAAAYAHQARAFAMAOQALAQAAASIAAAfQAIACAHAGQAFAHAAAJQAAALgHAHQgIAHgKAAgAgdhBIAAgKIAdAAIAAAKgAhPhBIAAgKIAeAAIAAAKg");
	this.shape.setTransform(17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(0,0,35,37.2), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixBZQgEAAABgDIAaiGQABgEAEAAIArAAQAEAAgBAEIgBAFQAGgGAIgDQAHgCAIAAQAIAAAIADQAHAEAEAHQAFAHABAKQACAKgDANQgCALgGALQgFAKgHAHQgHAHgJADQgJAEgJAAQgHAAgGgCQgHgDgEgGIgIAsQgBADgEAAgAhsgXIgJAtQACACAFAAQAGAAAEgFQADgGADgNQADgOgCgGQgBgFgGAAQgFAAgDACgABtA0QgHgBgGgCIgKgFQgFgDgDgEQgDgDgCgFIgDgJQgCgKACgKIAEgNIAFgLIAIgJIAJgIQAGgEAQgGQAMgDAOAAQAMAAAJACQAJADAGAEQAGAFACAGQACAGgBAIQgCAHgEAGQgFAHgIADQgJAFgLACQgNADgQAAIgHAAQAAAEABADQACADADABQAFADAMAAIANgBIANgDQAFgCgBAFIgBASQgBADgDABQgIADgKABQgKABgKAAIgPgBgAB9gYQgEAEgDAIIADAAQANAAAHgCQAFgCABgFQAAgDgCgCQgCgCgFAAQgIAAgFAEgAkcAxQgHgDgFgHQgEgHgCgKQgBgLACgLQADgNAFgKQAGgKAHgHQAHgHAJgEQAIgDAJAAQAJAAAGADQAHADACAFIABgFQABgEAEAAIArAAQAEAAgBAEIgTBfQgBAEgDAAIgrAAQgEAAABgEIAAgFQgEAFgHADQgIADgJAAQgJAAgHgEgAjzgUQgEAGgDAOQgCANABAGQACAFAGAAQAEAAADgCIAJgtQgCgCgEAAQgGAAgEAFgAntA0QgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgKIAEgNIAGgLIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAIQgBAHgFAGQgFAHgIADQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAncgYQgFAEgDAIIADAAQAOAAAGgCQAFgCABgFQABgDgCgCQgDgCgFAAQgHAAgFAEgAI4AzQgEAAABgEIAThfQAAgEAEAAIBXAAQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIgFAVQAAAEgEAAIgnAAIgOBGQAAAEgEAAgAH0AzQgEAAABgEIAGgjIgRAAIgHAjQAAAEgEAAIgrAAQgEAAABgEIAShfQABgEAEAAIArAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgGAhIARAAIAGghQABgEAEAAIArAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgTBfQAAAEgEAAgAFxAzQgDAAAAgEIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThfQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBfQAAAEgEAAgADTAzQgDAAAAgEIAOhGIgXAAQgBAAgBgBQgBAAAAAAQAAgBAAAAQgBgBABgBIAEgVQAAgEAEAAIBhAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgEAVQAAAEgEAAIgXAAIgOBGQgBAEgEAAgAgjAzQgEAAABgEIAShfQABgEAEAAIBVAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgEAVQgBAEgEAAIgnAAIgOBGQAAAEgEAAgAmHAzQgDAAAAgEIAOhGIgXAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgVQABgEAEAAIBhAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgEAVQgBAEgEAAIgXAAIgOBGQAAAEgEAAgAqhAzQgEAAABgEIAZiDQABgEAEAAIA5AAQAPAAAMADIAKADIAIAGQAEADACADQADAEABAFQACAFAAAFIgCANIgDAMQgCAFgEAFQgDAFgEADIgJAHQgNAGgJACQgMADgPAAIgKAAIgHAlQAAAEgEAAgApjgWIALAAQAHAAAFgDQAFgFABgIQACgJgDgFQgDgDgIAAIgLAAg");
	this.shape.setTransform(67.7,8.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,135.5,17.9), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AiOCPQgsgsgBg+QABg+AsgsQAngnA5gFQA3gEAtAiIADADIgFAIIgFgDQgpgfgzADQg1AEglAlQgpApAAA6QAAA6ApApQApAqA7AAQA5AAApgqQAlglADg0QAFg0gggpIgCgEIAIgGIACAEQAiAsgFA4QgEA4gnAnQgtAtg8AAQg/AAgsgtgAh2B4QgjgkAAgvQAAgwAjgiQAegeAqgEQAqgEAiAYIAEADIgGAIIgEgDQgfgWgmAEQgnADgcAcQgeAfAAAsQAAAsAeAfQAgAgAtAAQArAAAfggQAcgbADgnQADgmgVgfIgDgEIAIgGIADAEQAYAigDAqQgFArgeAeQgjAiguAAQgyAAghgigAhfBgQgYgZAAgiQAAgjAYgXQAUgUAdgEQAcgEAXAOIAFADIgGAIIgEgCQgUgNgZAEQgZADgSASQgVAUAAAfQAAAeAVAWQAWAVAfAAQAeAAAVgVQARgSAEgZQACgYgMgWIgCgDIAJgFIACAEQAOAYgEAcQgDAcgVAUQgXAYgiAAQgkAAgYgYgAhHBIQgPgOAAgVQAAgVAPgPQAKgJANgDQAOgDANAEIAGACIgDAIIgGAAQgXgHgRAPQgMANAAAQQAAAQAMAMQAMALARAAQAQAAAMgLQAHgIACgLQADgLgEgKIgBgFIAKgDIABAFQAEANgDANQgEAOgIAKQgPAPgUAAQgVAAgPgPgAgrAlICIiIIgIgnIAwgxIAJAuIAuAJIgxAwIgngHIiHCHgABfiHIAHAiIAiAGIAfgfIghgHIgHghg");
	this.shape.setTransform(18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(0,0,37.5,37.6), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0DbQgFAAADgFIAQghIgWhjQgBgFAGAAIAqAAQADAAABADIADA4IAWg4QABgDADAAIArAAQAFAAgDAFIhFCGQgCADgDAAgAk9CzQgIgDgEgHQgFgHgBgKQgCgLADgMQACgNAGgKQAFgKAHgHQAIgHAIgEQAJgDAJAAQAJAAAGADQAGADADAFIABgFQABgEADAAIAsAAQAEAAgBAEIgTBgQgBAEgDAAIgsAAQgEAAABgEIABgFQgFAFgHADQgIADgIAAQgJAAgHgEgAkUBtQgEAGgDAOQgDAOACAGQABAFAHAAQAEAAADgCIAJguQgCgCgFAAQgGAAgDAFgAmzC2QgLgCgJgDQgBAAgBAAQAAgBAAAAQgBgBAAgBQAAAAABgBIAGgUQACgEAEABQAHAEAIABIARABIAJgBQAEgBAAgDQABgFgHgCQgHgCgTAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgTQABgEAEAAQASAAAIgCQAHgCABgEQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQgCgBgHAAQgVABgMADIgDgBIgBgDIACgSQABgEADAAQANgEAdgBQAPAAALACQAKACAGAFQAGAEACAGQACAGgBAHQgBAHgFAFQgGAGgHACQAIAEADAHQACAFgBAHQgCAIgFAGQgEAGgIAEQgIAFgMACQgLACgOAAQgMAAgLgBgAGTC1QgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThgQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgAELC1QgDAAgBgDIgJgqIgIApQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAWglQACgDADAAIAuAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABIggAsIARAwQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgACCC1QgBAAgBgBQgBAAAAAAQAAgBAAgBQgBAAABgBIAOhHIgSAAIgOBHQAAAEgEAAIgrAAQgEAAABgEIAShgQABgEAEAAIBvAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAgAiGC1QgBAAgBAAQAAgBgBAAQAAAAgBgBQAAgBAAAAIgJgqIgIApQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAWglQACgDADAAIAuAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBABIggAsIARAwQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQAAAAgBAAgABsgoQgEAAACgDIAaiHQABgEADAAIAsAAQAEAAgBAEIgBAFQAGgGAHgDQAHgCAIAAQAJAAAHADQAHAEAFAHQAFAHABAKQABAKgCANQgDAMgFALQgFAKgIAHQgHAHgIADQgJAEgJAAQgHAAgGgCQgHgDgEgGIgJAsQAAADgEAAgACyiZIgJAuQACACAEAAQAGAAAEgFQAEgGADgOQACgOgBgGQgCgFgGAAQgEAAgDACgAn4goQgFAAADgFIAQghIgVhjQgBgFAFAAIAqAAQAEAAAAADIADA4IAXg4QACgDADAAIArAAQAFAAgDAFIhHCGQgBADgEAAgAk+g6QgEAAABgEIADgQIgiAAIgDAQQgBAEgDAAIgqAAQgEAAABgEIAIgpQABgEAEAAIAIAAQAGgMAKgXQAGgRAFgTQABgEADAAIBXAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgOBHIAJAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgIApQgBAEgEAAgAlEiEQgFANgGAMIAOAAIAKgyIgFAAQgDAMgFANgAJhhNQgHgBgGgCIgKgFQgEgDgDgEQgEgDgCgFIgDgJQgCgKACgLIAEgNIAGgLIAHgJIAJgIQAHgEAQgGQAMgDAOAAQALAAAKACQAIADAGAEQAGAFACAGQADAGgCAIQgBAHgFAGQgFAHgIAEQgIAFgMACQgMADgRAAIgHAAQAAAEACADQABADADABQAGADAMAAIANgBIAMgDQAFgCAAAFIgCASQAAADgEABQgIADgJABQgKABgLAAIgPgBgAJyiaQgFAEgDAIIADAAQAOAAAGgCQAFgCABgFQABgDgCgCQgDgCgFAAQgHAAgFAEgAANhQIgKgEIgHgHQgDgDgCgEQgDgFgBgFIgBgKIABgMQACgIAHgPQAEgGALgLQAGgEAPgGQAIgDASgBQAKAAAPAEQAFABAEADIAIAGIAGAIIADAJIABALIgBAMIgDAMIgGAKQgJANgGAEQgOAJgIACQgRAEgJAAQgRgBgHgDgAAsiWQgEAGgDAOQgCANACAHQABAFAFAAQAFAAADgFQAEgHADgNQADgOgCgGQgCgFgEAAQgFAAgEAFgAHzhOQgEAAABgEIAThgQABgEADAAIArAAQAFAAgCAEIgSBgQgBAEgEAAgAGDhOQgEAAABgEIAShgQABgEAEAAIAnAAQAEAAgBAEIgFAbIAKAAQALAAAJACQAIACAGAFQAGAEACAHQACAHgCAJQgCAJgFAHQgEAHgIAFQgHAEgJADQgKACgLAAgAGzhpIAFAAQAFAAACgDQADgCABgEQABgFgCgDQgCgCgFAAIgEAAgAE+hOQgDAAAAgEIAHgjIgRAAIgHAjQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAhIASAAIAGghQAAgEAEAAIAsAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgAhnhOQgDAAAAgEIAOhHIgXAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAEgVQABgEAEAAIBhAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgEAVQgBAEgEAAIgXAAIgOBHQAAAEgEAAgAi4hOQgDAAAAgEIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThgQAAgEAEAAIAmAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQAAAAABAAQABABAAAAQAAABABAAQAAABAAABIgTBgQAAAEgEAAgApKhOQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIgBgUIgiAAIgJAUQgBAEgEAAIgvAAQgFAAACgFIBAiEQABgDAEAAIBFAAQABAAAAAAQABAAAAAAQABABAAAAQAAABABABIAMCEQAAAFgEAAgApOiKIgBgvIgTAvIAUAAg");
	this.shape.setTransform(68.9,21.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(0,0,137.9,43.9), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgtCXIAVhbIAAgaIgFAAQgoABgbAbQgcAcAAAnIAAAPIgKAAIAAgPQAAgrAfgfQAegeAsgBIgMgOQgXgdAAgkIAAhGIAKAAIAABGQAAAhAVAaIARAUIAiAAIAQgUQAVgZAAgiIAAg8QgcAAgcgHQgYgFgQgIIgFgCIAFgJIAEACQAPAIAZAFQAdAGAcAAIAFAAIAABGQAAAlgXAcIgLAOQArABAeAeQAfAfAAArIAAAPIgKAAIAAgPQAAgngcgcQgbgbgngBIgGAAIAAAYIAVBdIguAjgAghCTIAhAaIAigaIgShTIgeAAgAgOA2IAdAAIAAgUIgdAAgABLgtIAAgKIAFAAQAGAAAFgEQAEgEAAgHQAAgGgEgEQgFgFgGAAIgFAAIAAgoQAAgPgJgMQgJgMgPgEQgYgHgSAAQgQAAgZAHQgPAEgJAMQgJAMAAAPIAAAoIgFAAQgGAAgFAFQgEAEAAAGQAAAHAEAEQAFAEAGAAIAFAAIAAAKIgFAAQgKAAgHgHQgIgHAAgLQAAgJAGgHQAFgGAJgCIAAgfQAAgSALgPQAMgPARgFQAZgHATAAQAUAAAaAHQARAFALAPQALAPAAASIAAAfQAIACAHAGQAFAHAAAJQAAALgHAHQgIAHgKAAgAAKhBIAAgKIAeAAIAAAKgAgnhBIAAgKIAeAAIAAAKg");
	this.shape.setTransform(13.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(0,0,27,37.2), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("ABlC3IAAhOQAAgXgRgQQgHgHgJgFIAAA9IgvgWIgVAkIgUgkIgwAWIAAg9QgIAFgHAHQgRAQAAAXIAABOIgKAAIAAhOQAAgbAUgTQATgTAbAAIATAAIAAgOIgFgDQgSgOgKgTQgKgUAAgWIAAgoIAKAAIAAAoQAAAUAJASQAJAQAQANIAJAGIAAAdIgSAAIAhA6IAig6IgSAAIAAgdIAJgGQAQgNAIgQQAJgSAAgUIAAgYQgmgBgXgJQgZgKgbgYIAGgHQAcAXAWAJQAXAIAoABIAEAAIAAAiQAAAWgKAUQgKATgRAOIgFADIAAAOIATAAQAbAAAUATQATATAAAbIAABOgAAaBUIAgAPIAAgwQgGgCgHABgAg6AzIAAAwIAhgPIgTgiQgHgBgHACgABqAyQAQAAASgQQgXgQgOgWQgNgWAAgXIAAg1QAAgdgUgUQgUgVgdAAIg+AAIAAgKIA+AAQAhAAAXAYQAXAXAAAhIAAA1QAAAXAQAYQAOASAVAOIAFADIgEAEQgXAXgXAAgAiXAlIgEgEIAFgDQAXgPAOgWQAOgVAAgVIAAhCQAAgWARgPQARgOAWADIANACIgCAKIgMgCQgSgCgOALQgNAMAAARIAABCQAAAXgNAWQgOAWgXAQQASAQAQAAIAAAKQgXAAgXgXgAAQg4IAAgJIAVAAIAAAJgAgkg4IAAgJIAVAAIAAAJg");
	this.shape.setTransform(15.6,18.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(0,0,31.3,36.5), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHPQjAi/AAkQQAAkODAjAQDAjAEOAAQEQAAC/DAQDADAAAEOQAAEQjAC/Qi/DAkQAAQkOAAjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AniBcQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAIgsQgFAFgHADQgIADgIAAQgJAAgHgEQgIgDgEgHQgFgHgBgKQgCgLADgMQACgMAGgKQAFgKAHgHQAIgHAIgEQAJgDAJAAQAJAAAGADQAGADADAFIAJgwQABgDAEAAIArAAQAEAAgBADIgJAwQAEgFAIgDQAHgDAJAAQAJAAAHADQAHAEAFAHQAFAHABAKQABAKgCAMQgDAMgFALQgFAKgIAHQgHAHgJADQgIAEgJAAQgJAAgGgDQgGgDgDgFIgJAsQAAADgEAAgAmdgUIgJAtQACACAEAAQAGAAAEgFQAEgGADgOQACgOgBgFQgCgFgGAAQgFAAgCACgAnggRQgEAGgDANQgDAOACAGQABAFAHAAQAEAAADgCIAJgtQgCgCgFAAQgGAAgDAFgAqqBcQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAIgsQgFAFgHADQgIADgIAAQgJAAgHgEQgIgDgEgHQgFgHgBgKQgCgLADgMQACgMAGgKQAFgKAHgHQAIgHAIgEQAJgDAJAAQAJAAAGADQAGADADAFIAJgwQABgDAEAAIArAAQAEAAgBADIgJAwQAEgFAIgDQAHgDAJAAQAJAAAHADQAHAEAFAHQAFAHABAKQABAKgCAMQgDAMgFALQgFAKgIAHQgHAHgJADQgIAEgJAAQgJAAgGgDQgGgDgDgFIgJAsQAAADgEAAgAplgUIgJAtQACACAEAAQAGAAAEgFQAEgGADgOQACgOgBgFQgCgFgGAAQgFAAgCACgAqogRQgEAGgDANQgDAOACAGQABAFAHAAQAEAAADgCIAJgtQgCgCgFAAQgGAAgDAFgAJRA1IgLgFIgIgGQgEgDgDgFIgDgJIgCgLIACgMIADgLIAGgLIAHgJIAJgIQAGgFARgGQAJgCAUgBIAPABQAIABAFACQABAAABABQAAAAAAABQABAAAAABQAAABgBABIgFATQgCAFgEgCQgGgCgLAAQgFAAgFABQgFACgDADIgGAIIgEAKQgBAGABAFQAAAEADAEQACADAEACQAEABAGAAQAJAAAJgDQAFgBAAAEIgCAUQgBADgDABIgPAEIgPABQgUgBgIgCgAHKA0IgKgEIgIgHQgDgDgCgEQgDgFgBgFIgBgKIABgMQACgHAHgPQAEgGAMgLQAGgEAPgGQAIgDASgBQAKAAAPAEQAFABAEADIAIAGIAGAIIADAJIABALIgBALIgDAMIgGAKQgJANgGAEQgOAJgIACQgRAEgJAAQgRgBgHgDgAHpgRQgEAGgDANQgCANACAHQABAFAFAAQAFAAADgFQAEgHADgNQADgNgCgGQgCgFgEAAQgFAAgEAFgAkrA3QgHgBgGgCIgKgFQgFgDgDgEQgDgDgCgFIgDgJQgCgKACgLIAEgMIAFgLIAIgJIAJgIQAGgEAQgGQAMgDAOAAQAMAAAJACQAJADAGAEQAGAFACAGQACAGgBAIQgCAHgEAGQgFAGgIAEQgJAFgLACQgNADgQAAIgHAAQAAAEABADQACADADABQAFADAMAAIANgBIANgDQAFgCgBAFIgBASQgBADgDABQgIADgKABQgKABgKAAIgPgBgAkbgVQgEAEgDAIIADAAQANAAAHgCQAFgCABgFQAAgDgCgCQgCgCgFAAQgIAAgFAEgAtfA2QgNgCgHgEQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAIgbQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAFADAHABIAOACIAMgBQAFgBAFgDQAFgCAEgDIAHgIIg4AAQgEAAABgDIAGgdQABgDADAAIA4AAIgEgIQgCgEgEgCQgEgCgFgBIgLgBQgIAAgHABQgHACgGADQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIADgcQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBIAWgGQAMgCALAAQAJAAAIACQAJABAHACIAMAGIAKAIQAEAFADAGQADAFABAHQACAHAAAHQAAAIgCAJQgCAIgDAHQgCAHgEAHIgKANIgLAKQgGAFgHADIgPAGQgIADgJABIgSABQgLAAgLgCgAMIA2QgEAAABgEIAShfQABgEAEAAIAnAAQAEAAgBAEIgFAbIAKAAQALAAAJACQAIACAGAFQAGAEACAGQACAHgCAJQgCAJgFAHQgEAHgIAFQgHAEgJADQgKACgLAAgAM4AbIAFAAQAFAAACgDQADgCABgEQABgFgCgDQgCgCgFAAIgEAAgAKwA2QAAAAgBgBQgBAAAAAAQAAgBAAAAQgBgBAAgBIAOhGIgXAAQgDAAAAgEIAEgVQABgEAEAAIBhAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgEAVQgBAEgEAAIgXAAIgOBGQAAAEgEAAgAFoA2QgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAHgjIgRAAIgHAjQAAAEgEAAIgsAAQgEAAABgEIAThfQAAgEAEAAIAsAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgHAhIASAAIAGghQAAgEAEAAIAsAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgTBfQAAAEgEAAgACdA2QgEAAABgEIAShfQABgEAEAAIA3AAQAOAAAKACQALACAGAEQAHADADAGQADAGgCAIQgBAFgDAEQgEAFgGAEQAHACADAGQACAFgBAIQgCAIgFAGQgFAGgIAEQgJAEgMADQgLACgPAAgADPAbIAJAAQAFAAADgBQADgCABgEQAAgDgCgCQgCgCgFAAIgJAAgADWgKIAJAAQAFAAACgCQADgBABgDQABgEgDgBIgHgBIgIAAgABeA2QgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAHgkIgkAmIgDACIgkAAQgEAAABgEIAThfQAAgEAEAAIAmAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgHAkIAkgmIAEgCIAjAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgTBfQAAAEgEAAgAg/A2QgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAOhGIgXAAQgEAAABgEIAEgVQAAgEAEAAIBgAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIgEAVQAAAEgEAAIgWAAIgOBGQgBAEgEAAgAiTA2QgDAAgBgDIgJgqIgIApQAAAEgEAAIgsAAQgEAAABgEIAThfQAAgEAEAAIAsAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgHAkIAWglQACgDADAAIAuAAQABAAAAAAQABAAAAABQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQgBAAAAABQAAAAgBABIggArIARAwQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape.setTransform(88.6,9.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(0,0,177.2,18.5), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AkwFYIAAgSIB/AAIAAl7Ih/AAIAAgSICqAAQAlgPAVgTQAWgSAYgjIABgDQApgbAigoQAWgZAlg2IAMgRQAIgMAOgFQAOgEANAEQAQAGAIAOQAJAPgEAQIgtDbIBuAAQAVAAAMAPQAOAQgDAVIgrEgQgDARgNALQgMALgRAAIl3AAIAAAkgAifEiIF3AAQAKAAAIgGQAIgIABgKIAHgwIhCAAIAAgTIBFAAIALhIIhAAAIAAgSIBCAAIALhIIhCAAIAAgTIBFAAIAGgoQACgNgIgJQgGgJgOAAIiDAAIAxjxQAEgVgVgJQgSgGgLAQIgLARQgnA3gVAZQgkArgqAcQgZAlgYAUQgWATgoAQIgEABIgbAAgAknEiIAAgSIA3AAIAAASg");
	this.shape.setTransform(30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(0,0,61,68.9), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.oim();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(0,0,174,174), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(-284,65.6,1,1,0,0,0,284,65.6);

	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(284,65.6,1,1,0,0,0,284,65.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(-568,0,1136,131.3), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(1));

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(85.6,28,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5));

	// Слой 1
	this.instance_1 = new lib.Символ34();
	this.instance_1.parent = this;
	this.instance_1.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.13,scaleY:1.13},4,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.instance_2 = new lib.Символ35();
	this.instance_2.parent = this;
	this.instance_2.setTransform(85.6,27.6,1,1,0,0,0,95.2,29.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,172,57);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(81.3,28.5,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ31();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(84.5,27.5,1,1,0,0,0,86.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(-4.5,-0.5,172,57), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.5,-0.5,172,57);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(70.5,65,2.04,2.04,0,0,0,17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ24();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(73.6,58.6,1.97,1.97,0,0,0,18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ20();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(40.2,64.3,1.748,1.748,0,0,0,13.5,18.6);

	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(89.1,63,1.748,1.748,0,0,0,15.6,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ18();
	this.instance_2.parent = this;
	this.instance_2.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(64.6,63,1.05,1.05,0,0,0,30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,131,131), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции
	this.instance = new lib.Символ36();
	this.instance.parent = this;
	this.instance.setTransform(109.4,58.4,1.4,1.4,0,0,0,109.4,17.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(-43.8,33.6,306.2,49.6), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции - копия
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(458.9,84,0.529,0.529,0,0,0,284.1,65.7);
	this.instance.alpha = 0.309;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:284.2,regY:65.8,x:449.9},47).to({regX:284.1,regY:65.7,x:458.9},52).wait(1));

	// Режим изоляции
	this.instance_1 = new lib.Символ40();
	this.instance_1.parent = this;
	this.instance_1.setTransform(291,85.9,1,1,0,0,0,284,65.6);
	this.instance_1.alpha = 0.172;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:859.3},99).wait(1));

	// Слой 2
	this.instance_2 = new lib.back();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-15,51,0.601,0.601);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-561,20.3,1203.4,131.3);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.bg = new lib.Символ1();
	this.bg.parent = this;
	this.bg.setTransform(1321.7,348.5,1.94,1.94,0,0,0,120.2,199.9);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,2334.8,254.7), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_349 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_384 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(349).call(this.frame_349).wait(35).call(this.frame_384).wait(36));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKAkQgGgBgFgDQgFgEgBgFIgBgGIAAgJQAAgIADgHQADgDAEgCQADgBAFAAIAcAAIAAgFIgCgDQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgpAAIAAgLIAoAAQAHAAAEADQAEADACAGIAAAEIAAAkQABAEgDAFQgDAEgEADQgDACgFAAgAgPAAQgCACAAADIAAAMQAAAEADABQADACAEAAIAPAAQAKAAAAgHIAAgMQAAgDgCgCQgDgBgDAAIgSAAQgFAAgCABg");
	this.shape.setTransform(269.9,-67.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAhQgCgCgCgFIgSgvIAAA4IgMAAIAAg4QAAgKAIgDQAFgCAEADQAEACADAHIAQAuIARguQADgHAEgCQAEgDAFACQAEABACAEQACADAAAFIAAA4IgMAAIAAg4IgSAvIgEAHQgCADgFAAQgDAAgDgDg");
	this.shape_1.setTransform(261.1,-67.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgLAkQgEgBgGgDQgFgEgCgFIgBgGIAAgJQAAgIAFgHQACgDADgCQAEgBAEAAIAcAAIAAgFIgBgDQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBgBAAAAIgqAAIAAgLIAqAAQAGAAAEADQAEADACAGIABAEIAAAkQAAAEgDAFQgDAEgDADQgEACgFAAgAgPAAQgCACAAADIAAAMQAAAEADABQADACAEAAIAPAAQAJAAAAgHIAAgMQAAgDgCgCQgBgBgFAAIgSAAQgEAAgCABg");
	this.shape_2.setTransform(252.4,-67.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AARAkIAAg2QgBgEgGgBIgLAAQgEABgBABQgCACgBAEIAAAhQABARgVABIAAgNQAFAAACgBQACgCgBgEIAAggQABgSATAAIALAAQAJAAAFAEQAGAFAAAJIAAA0g");
	this.shape_3.setTransform(244.8,-67.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAOAkIgcgfQgDgDAAgCQAAgEADgDIAagbIARAAIghAiIAiAkgAgdAkIAAhGIALAAIAABGg");
	this.shape_4.setTransform(237.8,-67.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgJAkQgEgBgEgBQgDgBgEgDQgEgFAAgIIAAgfQAAgVAVABIARAAIAHAAIAHAEQACADABADIABAIIAAAIIgtAUIAAAEQABAEABACQACACAEAAIAmAAIAAAMgAgPgVQgCADAAAEIAAAOIAigQIAAAAQAAgHgIAAIgSAAQgEAAgCACg");
	this.shape_5.setTransform(230.5,-67.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdAvIAAhLIABgHQACgEACgCQAFgFAJAAIAVAAIAHABIAEACQAEACACAEQABADABAFIAAAhIgBAIQgBADgDADQgGAGgHAAIgdAAIAAAXgAgPggQgCACAAADIAAAfIABABQAAAEACABQAAABABAAQAAABABAAQAAAAABAAQAAAAAAAAIAWAAIABAAQAEgBACgFIAAgBIAAgiIgCgDIgEgCIgUAAQgEAAgDACg");
	this.shape_6.setTransform(222.9,-66);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(420));

	// Слой 3
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(-64.3,186.5,0.209,0.209,0,0,0,231.2,14.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(280).to({_off:false},0).to({y:164.5},9,cjs.Ease.get(1)).to({y:166.5},5,cjs.Ease.get(1)).wait(45).to({y:164.5},5).to({y:186.5,alpha:0},5,cjs.Ease.get(1)).to({alpha:1},1,cjs.Ease.get(1)).to({y:164.5},9,cjs.Ease.get(1)).to({y:166.5},5,cjs.Ease.get(1)).wait(45).to({y:164.5},5).to({y:186.5,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ37();
	this.instance_1.parent = this;
	this.instance_1.setTransform(71.1,57.3,1,1,0,0,0,154.3,16.4);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-10,alpha:1},5,cjs.Ease.get(1)).to({y:-6.9},4,cjs.Ease.get(1)).wait(271).to({regX:154.2,regY:16.5,scaleX:0.93,scaleY:0.93,x:77.5,y:53.2},0).to({regY:16.3,y:-13.7},9,cjs.Ease.get(1)).to({regY:16.4,y:-6.3},5,cjs.Ease.get(1)).wait(45).to({regY:16.3,y:-13.7},5).to({regY:16.5,y:56,alpha:0},5,cjs.Ease.get(1)).to({y:53.2,alpha:1},1,cjs.Ease.get(1)).to({regY:16.3,y:-13.7},9,cjs.Ease.get(1)).to({regY:16.4,y:-6.3},5,cjs.Ease.get(1)).wait(45).to({regY:16.3,y:-13.7},5).to({regY:16.5,y:56,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// logo
	this.instance_2 = new lib.Символ5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(38.4,-152.7,1,1,0,0,0,75,46);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-46.1},5,cjs.Ease.get(1)).to({y:-54.6},4,cjs.Ease.get(1)).wait(271).to({x:44.5,y:-129.4},0).to({x:46.1,y:-45.5},9,cjs.Ease.get(1)).to({regY:46.1,y:-53.9},5,cjs.Ease.get(1)).wait(45).to({regY:46,y:-45.5},5,cjs.Ease.get(1)).to({regY:46.1,x:44.5,y:-143,alpha:0},5,cjs.Ease.get(1)).wait(1).to({regY:46,y:-129.4,alpha:1},0).to({y:-50.1},9,cjs.Ease.get(1)).to({regY:46.1,y:-57},5,cjs.Ease.get(1)).wait(45).to({y:-49.1},5,cjs.Ease.get(1)).to({y:-143,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// text_5
	this.instance_3 = new lib.Символ27();
	this.instance_3.parent = this;
	this.instance_3.setTransform(55.3,240.8,1.261,1.261,0,0,0,86.2,35.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(280).to({_off:false},0).to({regY:35,y:51.7,alpha:1},9,cjs.Ease.get(1)).to({y:64.4},5,cjs.Ease.get(1)).wait(42).to({y:51.7},5,cjs.Ease.get(1)).to({y:127.4,alpha:0},5,cjs.Ease.get(1)).wait(4).to({regY:35.1,y:240.8},0).to({regY:35,y:51.7,alpha:1},9,cjs.Ease.get(1)).to({y:64.4},5,cjs.Ease.get(1)).wait(42).to({y:51.7},5,cjs.Ease.get(1)).to({y:127.4,alpha:0},5,cjs.Ease.get(1)).wait(4));

	// btn
	this.instance_4 = new lib.Символ28();
	this.instance_4.parent = this;
	this.instance_4.setTransform(73,269.4,0.983,0.983,0,0,0,85.6,28);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.Символ28(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(280).to({_off:false},0).to({y:121.9,alpha:1},9,cjs.Ease.get(1)).to({y:131.8},5,cjs.Ease.get(1)).wait(40).to({y:121.9},5,cjs.Ease.get(1)).to({regY:27.9,y:180.9,alpha:0},5,cjs.Ease.get(1)).wait(6).to({regY:28,y:269.4},0).to({y:121.9,alpha:1},9,cjs.Ease.get(1)).to({y:131.8},5,cjs.Ease.get(1)).wait(40).to({y:121.9},5,cjs.Ease.get(1)).to({regY:27.9,y:180.9,alpha:0},5,cjs.Ease.get(1)).wait(6));

	// text_4
	this.instance_5 = new lib.Символ26();
	this.instance_5.parent = this;
	this.instance_5.setTransform(129,222,1.453,1.453,0,0,0,56.8,7.4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(214).to({_off:false},0).to({y:76.8,alpha:1},10,cjs.Ease.get(1)).to({y:91.3},5,cjs.Ease.get(1)).wait(40).to({y:76.8},5,cjs.Ease.get(1)).to({y:483.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// pic_4
	this.instance_6 = new lib.Символ23();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-43.5,89.2,0.497,0.497,0,0,0,65.5,65.7);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(214).to({_off:false},0).to({rotation:360,y:84.2},10,cjs.Ease.get(1)).to({y:89.2},5,cjs.Ease.get(1)).wait(10).to({regX:65.4,regY:65.6,scaleX:0.44,scaleY:0.44},5,cjs.Ease.get(1)).to({regX:65.5,regY:65.7,scaleX:0.5,scaleY:0.5},5,cjs.Ease.get(1)).wait(20).to({y:84.2},5,cjs.Ease.get(1)).to({y:223.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// text_3
	this.instance_7 = new lib.Символ22();
	this.instance_7.parent = this;
	this.instance_7.setTransform(129.8,234.2,1.41,1.41,0,0,0,67.8,9);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(144).to({_off:false},0).to({regY:8.9,y:79.1,alpha:1},10,cjs.Ease.get(1)).to({regY:9.1,y:93.5},5,cjs.Ease.get(1)).wait(40).to({regY:8.9,y:79.1},5,cjs.Ease.get(1)).to({regY:9,y:473.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// pic_3
	this.instance_8 = new lib.Символ19();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-43.5,109.1,0.497,0.497,0,0,0,65.5,65.7);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(144).to({_off:false},0).to({rotation:360,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({y:89.2},5,cjs.Ease.get(1)).wait(11).to({regX:65.3,scaleX:0.45,scaleY:0.45},4,cjs.Ease.get(1)).to({regX:65.5,scaleX:0.5,scaleY:0.5},5,cjs.Ease.get(1)).wait(20).to({y:84.2},5,cjs.Ease.get(1)).to({y:223.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// text_2
	this.instance_9 = new lib.Символ16();
	this.instance_9.parent = this;
	this.instance_9.setTransform(129.1,309.2,1.278,1.278,0,0,0,69,22);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(74).to({_off:false},0).to({y:79.1},10,cjs.Ease.get(1)).to({regY:22.1,y:92},5,cjs.Ease.get(1)).wait(40).to({regY:22,y:79.1},5,cjs.Ease.get(1)).to({regY:21.9,y:449.7,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// pic_2
	this.instance_10 = new lib.Символ17();
	this.instance_10.parent = this;
	this.instance_10.setTransform(-43.5,104.1,0.497,0.497,0,0,0,65.5,65.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(74).to({_off:false},0).to({regY:65.7,rotation:360,y:84.2,alpha:1},10,cjs.Ease.get(1)).to({y:89.2},5,cjs.Ease.get(1)).wait(10).to({regX:65.3,scaleX:0.44,scaleY:0.44},5,cjs.Ease.get(1)).to({regX:65.5,scaleX:0.5,scaleY:0.5},5,cjs.Ease.get(1)).wait(20).to({y:84.2},5,cjs.Ease.get(1)).to({regY:65.5,y:228.4,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// text_1
	this.instance_11 = new lib.Символ12();
	this.instance_11.parent = this;
	this.instance_11.setTransform(129,202.2,1.237,1.237,0,0,0,88.5,9.2);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(5).to({_off:false},0).to({y:78.4},9,cjs.Ease.get(1)).to({y:90.8},5,cjs.Ease.get(1)).wait(40).to({y:78.4},5,cjs.Ease.get(1)).to({y:449.7,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pic_1
	this.instance_12 = new lib.Символ9();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-43.5,99.2,0.497,0.497,0,0,0,65.5,65.7);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(5).to({_off:false},0).to({rotation:360,y:84.2,alpha:1},9,cjs.Ease.get(1)).to({y:89.2},5,cjs.Ease.get(1)).wait(10).to({regX:65.4,regY:65.6,scaleX:0.43,scaleY:0.43},5,cjs.Ease.get(1)).to({regX:65.5,regY:65.7,scaleX:0.5,scaleY:0.5},5,cjs.Ease.get(1)).wait(20).to({y:84.2},5,cjs.Ease.get(1)).to({y:233.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pricel
	this.instance_13 = new lib.Символ8();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-43.5,99.2,0.524,0.524,0,0,0,86.9,87);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({rotation:360,y:83.5,alpha:1},9,cjs.Ease.get(1)).to({regY:87.2,y:88.8},5,cjs.Ease.get(1)).wait(15).to({regY:87.1,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).to({regY:87.2,scaleX:0.52,scaleY:0.52},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:83.5},5,cjs.Ease.get(1)).to({y:240.6,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:99.2},0).to({rotation:720,y:83.5,alpha:1},9,cjs.Ease.get(1)).to({regY:87.2,y:88.8},5,cjs.Ease.get(1)).wait(15).to({regY:87.1,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).to({regY:87.2,scaleX:0.52,scaleY:0.52},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:83.5},5,cjs.Ease.get(1)).to({y:240.6,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:99.2},0).to({rotation:1080,y:83.5,alpha:1},9,cjs.Ease.get(1)).to({regY:87.2,y:88.8},5,cjs.Ease.get(1)).wait(15).to({regY:87.1,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).to({regY:87.2,scaleX:0.52,scaleY:0.52},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:83.5},5,cjs.Ease.get(1)).to({y:240.6,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:99.2},0).to({rotation:1440,y:83.5,alpha:1},9,cjs.Ease.get(1)).to({regY:87.2,y:88.8},5,cjs.Ease.get(1)).wait(15).to({regY:87.1,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).to({regY:87.2,scaleX:0.52,scaleY:0.52},5,cjs.Ease.get(1)).wait(20).to({regY:87,y:83.5},5,cjs.Ease.get(1)).to({y:240.6,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89,-165.1,363.2,309.9);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		
		
		
		stage.canvas.addEventListener("mouseover", fl_MouseOverHandler_5);
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(350);
		}
		
		
		stage.canvas.addEventListener("mouseout", fl_MouseOutHandler_23);
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(404);
		}
		
		//setTimeout(function() {
		//         _this.an.gotoAndStop(364);
		//		 _this.bg.bg.gotoAndStop(0);
		//		 stage.canvas.removeEventListener("mouseover", fl_MouseOverHandler_5);
		//		 stage.canvas.removeEventListener("mouseout", fl_MouseOutHandler_23);
		//    }, 30000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// an
	this.an = new lib.Символ7();
	this.an.parent = this;
	this.an.setTransform(167.5,131.5,0.8,0.8,0,0,0,87,87);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// bg
	this.bg = new lib.Символ41();
	this.bg.parent = this;
	this.bg.setTransform(60.9,176.3,1.573,1.573,0,0,0,1167.3,174.1);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1615.4,2.4,3673,400.6);
// library properties:
lib.properties = {
	width: 320,
	height: 200,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/back.jpg?1490773571400", id:"back"},
		{src:"images/molecule.png?1490773571400", id:"molecule"},
		{src:"images/oim.png?1490773571400", id:"oim"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;