(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.hohlogo = function() {
	this.initialize(img.hohlogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,240,200);


(lib.mal = function() {
	this.initialize(img.mal);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,403,671);


(lib.man1 = function() {
	this.initialize(img.man1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,261,642);


(lib.man2 = function() {
	this.initialize(img.man2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,299,654);


(lib.say_03 = function() {
	this.initialize(img.say_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,183,159);


(lib.say_06 = function() {
	this.initialize(img.say_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,183,152);


(lib.sssi_03 = function() {
	this.initialize(img.sssi_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,149,130);


(lib.sssi_06 = function() {
	this.initialize(img.sssi_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,145,134);


(lib.sssi_11 = function() {
	this.initialize(img.sssi_11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,138,130);


(lib.treugolnik_grib = function() {
	this.initialize(img.treugolnik_grib);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,92);


(lib.treugolnik_slivki = function() {
	this.initialize(img.treugolnik_slivki);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,93,120);


(lib.treugolnik_zelen = function() {
	this.initialize(img.treugolnik_zelen);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,116);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AirBmIADgOIAAiBIgCgHQgCgDAAgCQAAgHAHgDQAEgDAIAAQAHAAAFACQAEADAAAEIAAACQAKgIAKgBQAKAAAGAFQAHAFAGAJQAIAQAAAaQAAAOgDAMQgCANgGALQgLAXgSAAQgEAAgFgDIgJgIIAAAYQAAADADAGQADAHAAACQAAAHgHAFQgIAFgIAAQgQAAAAgQgAiIgEQACAVACAIQADAPAGAAQAFAAAEgPQACgIABgVQAAgigMAAQgNAAAAAigACpBqQgEgCgCgFIgBgFQAAgCACgCIACgFIAGgdIghhfIgEgHQgCgEAAgDIAAgEQACgHAOgBQAIAAAFADQAGADABAJIABAQIAPAvIAYg6IACgLQABgFAEgCQACgCADAAQAHABAHAFQAGAEABAHQABAEgDAGIgFAJIgmBgQgDAMgBAJIAAAIQAAAFgCADQgDAFgIAAQgGAAgFgDgAFbBAQgBgCAAgFIABgRIgBgGIAAgEQACgEAIgBQAJAAAFADQAEACACAFIABAFIgBAPIAAAGQABAEgCADQgDAEgHAAQgLAAgHgIgAETBCQgHgDgFgIQgLgQgCgbIgBgLQAAgKACgLQADgJADgKQAJgYAUgCQAIAAAIAEQAJADAFAHQAEAIADAIQAEAHAAAIIAAAJQgBAEgEACQgFADgGAAQgGAAgDgDQgEgEAAgIIgCgPQgCgHgHAAQgDAAgCANQgCAMAAAPQAAATADAMQADAOAFAAQAGAAAFgJQAFgIAAgHQAAgLANABQAGAAAEACQAFADABAFIgFAMQgIATgKAIQgJAJgLAAQgKAAgIgEgAgtBAQgIgHgFgMQgIgTAAgXQAAgNACgMQADgKADgJQAGgMAJgFQAHgGAMAAQAHABAHAEQAHADAEAHQAEAGADAHIAFAQQAHAIgBAGQgBAJgPAAIgHAAIggACQABAoAMAAQAAAAAAAAQABAAAAgBQABAAAAgBQABgBAAgBQABgDAAgGIAAgCIgBgEQAAgFAHgEQAGgDAHgBQAIAAADADQADAEAAAGIgDAKQgFAQgGAHQgJAKgUAAQgJAAgHgFgAgfggQgDAEgCALIAWgCQgFgTgFAAQgFAAgCAGgAj7BAQgIgHgFgMQgIgTAAgXQAAgNACgMQADgKADgJQAGgMAJgFQAHgGAMAAQAHABAHAEQAGADAGAHQAEAGADAHIAFAQQAHAIgBAGQgCAJgOAAIgIAAIggACQAAAoANAAQAAAAAAAAQABAAAAgBQABAAAAgBQABgBAAgBQABgDAAgGIAAgCIgBgEQAAgFAGgEQAHgDAIgBQAHAAAEADQAEAEgBAGIgDAKQgEAQgIAHQgJAKgUAAQgJAAgHgFgAjuggQgCAEgBALIAVgCQgFgTgFAAQgFAAgDAGgAk6BAQgIgEABgDQAAgEADgEIAAhVIgaAEIAABRQADAIAAADQAAAIgNAAQgHABgIgFQgIgEABgDQAAgEADgEIAAheQgDgFAAgDQAAgLAPAAQAKAAAGAFIAngFQAGAAAHADQAIADAAAIQAAADgEAHIAABaQADAHAAADQAAAIgOAAQgGABgIgFgAAoBAQgHgEAAgDQAAgDADgGIAAheQgCgEgBgDQABgMAPAAQAIAAAGAFQAGAEAAAGQAAACgDAHIAAAkIAEAAIAfgyQADgKAIAAQAGAAAIAGQAHAFAAAGQAAADgDADQgCADgFABIgbAqQAKATAMAQIAGACQAEADAAAFQAAAFgFAFQgHAJgJgBQgEAAgDgBIgDgGIgCgEQgKgRgKgSIgJAAIAAAcQACAGAAAEQAAAJgNAAQgGAAgJgEgAFaADQgCgCAAgDIABgJQgCgdAAgeQAAgoADgEQADgDAIAAQAJAAAFACQAEACABAEIABAEIgDANIAABNIADARQAAAFgEACQgDACgGABQgLAAgHgJg");
	this.shape.setTransform(40.5,15.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(2.8,3.6,75.5,23.6), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrBWQgEgCgCgFIgBgFQAAgCACgDIADgFIAFgcIghhfIgEgHQgCgEAAgDIABgEQACgIANAAQAJAAAEADQAGADABAJIACAQIAPAwIAXg7IACgLQABgFADgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIglBgQgDALgBAKIAAAIQAAAFgCADQgDAEgIAAQgGAAgFgCgAkSAtIAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQAOgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAJIAAAHQAAAVgTATQgTASgXAAQgMAAgLgHgAjwgHQgIADgEADIAAAdQAEgBAEgCIALgJQAHgGADgGQAEgFAAgGQAAgFgFAAQgGAAgKAFgAjwg+QgKADgCACIAAAaQAPgJAIgJQAHgIAAgGQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQgFAAgJADgAA/AuQgIgEgFgHQgKgRgDgZIAAgMQAAgLACgKQACgKADgJQAKgYATgCQAIAAAJADQAIAEAFAHQAFAHADAIQADAIAAAIIAAAJQAAAEgFACQgFADgGAAQgGAAgDgDQgDgEgBgJIgCgOQgBgHgIAAQgDAAgCAMQgCANAAAQQAAASADAMQADAOAFAAQAGAAAFgJQAFgJAAgGQAAgKANAAQAGAAAFADQAEADABAEIgFAMQgIASgKAJQgJAJgLAAQgKAAgHgEgAirAsQgIgEAAgEQAAgDADgFIAAheQgCgFAAgDQAAgLAPAAQAIAAAGAFQAHAEAAAFQAAADgEAHIAAAkIAEAAIAfgyQAEgKAHAAQAHAAAHAFQAHAGAAAGQAAADgCADQgDADgFABIgaArQAJASAMAQIAHACQADADAAAFQAAAFgEAFQgIAIgJAAQgEAAgDgCIgCgFIgCgFQgLgQgKgTIgJAAIAAAdQADAGAAAEQAAAJgOAAQgGAAgIgEgADCgRQgEgGAAgFQAAgFACgDIAHgBIALgBIA/gLIAFABQADACACAEQACAEAAAGQAAAFgDADQgBAAAAABQgBAAAAAAQgBABAAAAQgBAAgBAAIgFgBIgGgBIgwAIIgIACIgGACQgGAAgEgFg");
	this.shape.setTransform(31.2,17.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(2.7,8.6,57.1,17.7), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHA3IgBgEIAAgFIAAgGIAAgDIAAgDQACgDAEAAQAEAAAEABQADACABADIABAEIgBAEIAAAEIAAAFIgBAEQgBACgEAAQgHAAgEgFgAgIARIgBgEIAAgDIAAgDQgBgRAAgUQAAgZACgCQACgCAFAAQAEAAADABQADABABADIAAACIgBAEIgBAFIAAAwIABAGIACAFQAAADgDABQgCACgDAAQgHAAgEgFg");
	this.shape.setTransform(148.8,97.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AADAqIgDAAQgGgBgFgDQgEgEgEgHQgHgMAAgRQAAgMAFgPQAGgNAGAAIACABIAEAAIADAAIAFgBIADABQAJADAFAKQAFAKAAAQQABASgIAOQgDAHgDADQgFADgDAAgAgHgRIgBAPQAAAHACAJQADANADAAQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAgBIADgKQACgKAAgGQgCgbgHAAQgEAAgDAMg");
	this.shape_1.setTransform(144.1,98.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUApIgEgCIgEgCIgCgCIACgGIAAgWIgBgHIAAgCIABgEIAAgYIgBgFQAAgGAJAAIAGAAIADACIAEADIABADIgDAHIAAARIASgCIAAgTIgBgGQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABAAIAFgBQAHAAAFACQADACAAAEIgCAHIAAAPIACAGIgBAEIgBACIAAAbIACAGQAAAFgJAAIgFgBIgEgBIgDgDIgCgCIACgGIAAgVIgSACIAAAXQACAEAAADQAAAFgIAAg");
	this.shape_2.setTransform(137.4,98.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAnIgGgGQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQABgJAJgBQADAAABADIAEADIADABQAEAAADgHQAFgGABgDQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEAAIgBACQgFAFgCAAQgFAAgEgDQgEgDAAgFQAAgCAEgCIAHgDQALgGADgJIgBgFQgCAAgDACQgEACgDAFQgFADgCAAQgFAAgEgEQgDgEAAgGQAAgDAEgBIAHgBIANgIQAHgEAHACQAGACADAEQAEAEAAAGQgBALgKAKQAGABADADQADACABADQAAAOgMANQgLANgJAAQgGAAgHgFg");
	this.shape_3.setTransform(130.7,98.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNAnQgFgEgDgIQgFgMAAgPQAAgIABgGQABgIADgGQAEgGAFgEQAFgEAHABQAEAAAEACQAEACAEAFIAEAIIAEAKQAEAGgBADQgBAGgJgBIgFAAIgTACQAAAZAHAAIACgCIABgGIgBgCIAAgCQAAgEAEgCQAEgCAFAAQAFAAACACQACACAAAEIgCAGQgDALgEAEQgGAGgMAAQgFAAgFgDgAgFgWQgBAEgBAGIAMgBQgCgNgDAAQgDAAgCAEg");
	this.shape_4.setTransform(124.7,98.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AATApIgFgBIgEgDQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIACgFIgIgoIgLApIABAEQAAADgDADQgDACgFAAIgHgBQgDgBgCgEIABgDQABgDAEgBIAQg4IAAgBIAAgBQAAgHAEgCQADgDAFAAQAFAAAEACQAEADAAAEQAAADgCADIAPA5IABAFQAAAGgHAAg");
	this.shape_5.setTransform(118.1,98.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AADAqIgEAAQgFgBgFgDQgEgEgEgHQgIgMAAgRQABgMAFgPQAGgNAFAAIADABIAEAAIADAAIAFgBIADABQAJADAFAKQAGAKgBAQQAAASgGAOQgEAHgDADQgFADgDAAgAgHgRIgBAPQAAAHADAJQACANADAAQABAAAAAAQABAAAAgBQAAAAABgBQAAAAABgBIADgKQACgKAAgGQgCgbgHAAQgEAAgDAMg");
	this.shape_6.setTransform(111.4,98.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKAnQgEgCAAgCIACgGIAAg1IgQADIAAAzIACAHQABAFgJAAQgEAAgGgDQgEgCAAgCIABgGIAAg7IgBgFQAAgGAKAAQAGAAAEADIAYgDQADgBAFACQAFADAAAEQAAADgDAEIAAA4IACAHQAAAFgJAAQgDAAgGgDg");
	this.shape_7.setTransform(105,98.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaAqQgEgDAAgCIACgFIgCg9IgBgFQAAgHAJAAQAFAAAFADQAEADAAADIgDAGIAAAkQALgbAJgSIAAgCQAAgDACgCQADgCAFAAQAFAAAEADQAEACAAAEIgCAGIAAA5IABAGQAAAGgIAAQgEAAgFgDQgFgCAAgCQAAgCACgEIAAgiIgTAsQgBAEgDABQgCACgEAAQgEABgEgDg");
	this.shape_8.setTransform(94.3,98.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgKANQgDgEAAgDIAFgFQAFgEABgEIABgEIABgDIACgBIAHACQAEACABACIAAACQAAADgDAEIgJAKQgDAGgCAAQgDAAgEgDg");
	this.shape_9.setTransform(85.2,103.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AADAqIgEAAQgFgBgFgDQgFgEgDgHQgIgMAAgRQAAgMAGgPQAGgNAFAAIAEABIADAAIADAAIAEgBIAEABQAJADAFAKQAGAKAAAQQgBASgGAOQgEAHgEADQgEADgEAAgAgGgRIgBAPQAAAHACAJQACANADAAQAAAAABAAQAAAAABgBQAAAAABgBQAAAAABgBIADgKQACgKAAgGQgCgbgHAAQgEAAgCAMg");
	this.shape_10.setTransform(81,98.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUApIgEgCIgEgCIgCgCIACgGIAAgWIgBgHIAAgCIABgEIAAgYIgBgFQAAgGAJAAIAGAAIADACIAEADIABADIgDAHIAAARIASgCIAAgTIgBgGQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABAAIAFgBQAHAAAFACQAEACAAAEIgDAHIAAAPIACAGIgBAEIgBACIAAAbIACAGQAAAFgIAAIgGgBIgEgBIgDgDIgCgCIACgGIAAgVIgSACIAAAXQACAEAAADQAAAFgIAAg");
	this.shape_11.setTransform(74.4,98.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLA7QgGgCgEgIQgDgEgEgMQgCgHAAgQIAAgPIACgOQACgGADgGQADgFAFgFIADgCIAGgFIAGgDIAFgEIAAgCIACgCIACgCIADgBIAFABIAFADIADAEIABAEIgBAEIgBADIgDACIgEABIgKAGIgJAFQgJAHAAAKIABABIACgBIACgCQADgEADAAIAHgBQAEAAAFADQAEACAEAEQADAFACAHQACAGAAALQAAANgCAFQgDAIgEAGQgEAGgGADQgFADgHAAQgFAAgGgEgAgFgCIgDADIgCAGIgBAIIABANIADAKIAEAHQABAAAAAAQABABAAAAQABAAAAAAQAAABAAAAQABAAAAgBQABAAABAAQAAAAABAAQAAgBABAAIADgGIACgJIABgLQAAgFgBgEIgDgHQgCgDgCgCQgBAAAAAAQgBgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_12.setTransform(67.2,96.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AADAqIgEAAQgFgBgFgDQgFgEgDgHQgIgMABgRQgBgMAGgPQAFgNAGAAIAEABIADAAIADAAIAEgBIAEABQAJADAFAKQAGAKAAAQQgBASgGAOQgEAHgEADQgDADgFAAgAgGgRIgBAPQAAAHACAJQACANADAAQACAAACgDIADgKQACgKAAgGQgCgbgHAAQgEAAgCAMg");
	this.shape_13.setTransform(60.4,98.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgcAyIgEgCIgEgCQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIACgGIAAgNIgCgFIABgDIADgCIADgBIADgBIAAAAIAHgUIAIgfIgCgFQAAgHAKAAIACAAIADABIAFACIAIABIAGAAIAEACQAAAAABABQAAAAAAABQAAAAAAABQAAABAAAAIgCAHIAEArIACAAIAFABIADACIACADIABACIgDAGIgBAOIACAGQAAABgBAAQAAABAAAAQAAABgBAAQAAABgBAAQgCABgDAAIgEAAIgEgCIgFgCIgCgCIACgGIABgJIgiADIAAAIIACAHQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBAAQgCACgDAAgAABgZIgEATIgGAUIAQgCIgDgtIgCAAg");
	this.shape_14.setTransform(53.1,99.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgLA2QgCgCgCgDIAAgDIABgDIABgDIAEgSIgVg8IgCgFIgCgEIABgCQABgFAIAAQAGAAADABQADADABAFIABAKIAKAeIAOglIABgHQABgDACgCIADAAQAEAAAFADQAEADABAEQAAADgCADIgDAGIgTAuIgFAPIgDANIAAAFIgBAFQgCADgEAAQgEAAgDgBg");
	this.shape_15.setTransform(45.5,100.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgaAqQgEgDAAgCIACgFIgCg9IgBgFQAAgHAJAAQAFAAAFADQAEADAAADIgDAGIAAAkQALgbAJgSIAAgCQAAgDACgCQADgCAFAAQAFAAAEADQAEACAAAEIgCAGIAAA5IABAGQAAAGgIAAQgEAAgFgDQgFgCAAgCQAAgCACgEIAAgiIgTAsQgBAEgDABQgCACgEAAQgEABgEgDg");
	this.shape_16.setTransform(34.8,98.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgKANQgDgEAAgDIAFgFQAFgEABgEIABgEIABgDIACgBIAHACQAEACABACIAAACQAAADgDAEIgJAKQgDAGgCAAQgDAAgEgDg");
	this.shape_17.setTransform(129.1,86.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AADAqIgDAAQgGgBgFgDQgEgEgEgHQgIgNABgQQgBgMAGgPQAFgNAHAAIADABIADAAIADAAIAEgBIAEABQAJADAFAKQAFAKABAQQAAASgHAOQgEAHgEADQgDADgFAAgAgGgRIgBAPQAAAHABAKQADAMADAAQACAAACgDIADgJQACgLAAgGQgCgbgHAAQgEAAgCAMg");
	this.shape_18.setTransform(124.9,81.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgUApIgEgCIgEgCIgCgCIADgGIAAgWIgCgHIABgCIABgEIAAgYIgCgFQAAgGAKAAIAEAAIAFACIADADIAAADIgCAHIAAARIASgCIAAgTIgBgGQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAABAAIAGgBQAGAAAFACQADACAAAEIgCAHIAAAPIABAGIAAAEIgBACIAAAbIABAGQABAFgJAAIgEgBIgFgBIgDgDIgBgCIABgGIAAgVIgSACIAAAXQACAEAAADQAAAFgJAAg");
	this.shape_19.setTransform(118.2,81.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgKApQgEgDgEgEQgGgLgCgQIAAgHIABgNIADgNQAHgPAMgBQAEAAAFACQAGACADAFIAFAJIACALIAAAFQAAADgDABQgDACgEAAQgEAAgCgCQgCgCgBgGIgBgJQgBgFgDAAQgCAAgCAIQgBAIAAAKQAAALABAIQADAJADAAQADAAADgGQADgFAAgEQAAgHAIAAQAEAAADACQADACAAADIgDAIQgFALgGAGQgGAFgHAAQgFAAgFgCg");
	this.shape_20.setTransform(111.9,81.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLA2QgCgCgCgDIAAgDIABgDIABgDIAEgSIgVg8IgCgFIgCgEIABgCQABgFAIAAQAGAAADABQADADABAFIABAKIAKAeIAOglIABgHQABgDACgCIADAAQAEAAAFADQAEADABAEQAAADgCADIgDAGIgTAuIgFAPIgDANIAAAFIgBAFQgCADgEAAQgEAAgDgBg");
	this.shape_21.setTransform(105.2,83);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AALApIgCgEIgBgDIgNgVIgFAAIAAASQACADAAADQAAAFgJAAQgEAAgFgCQgFgDAAgCQAAgCACgDIAAg7IgCgFQAAgHAKAAQAFAAAEADQAEACAAAEIgCAGIAAAXIADAAIASggQACgHAFABQAFAAAEADQAFADAAAFIgCADIgFADIgQAbQAGALAHAKIAEACQADABAAAEQAAADgDADQgFAFgGAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_22.setTransform(98.6,81.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgWAoIAAABQgHgFAAgBQAAgDACgDIAAg7IgCgFQAAgHAJAAIAGABIADAAIAGgBQAIgCAGAAQAHAAAFADQAEACACAEIACAGQAAAGgEAFQgDAFgGAFQAGAAADADQAEADABAFIAAAEQAAAOgMAMQgNAMgNAAQgIAAgGgFgAgBAGIgIAEIAAATIAGgCIAGgFQAEgEACgEQACgEAAgEQAAAAAAgBQAAgBgBAAQAAAAgBgBQAAAAgBAAQgDAAgGADgAgCgcIgHAEIAAARQAJgHAFgFQAEgFAAgEQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAgBAAIgJACg");
	this.shape_23.setTransform(91.7,81.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgaAqQgEgDAAgCIACgFIgCg9IgBgFQAAgHAJAAQAFAAAFADQAEADAAADIgDAGIAAAkQALgbAJgSIAAgCQAAgDACgCQADgCAFAAQAFAAAEADQAEACAAAEIgCAGIAAA5IABAGQAAAGgIAAQgEAAgFgDQgFgCAAgCQAAgCACgEIAAgiIgTAsQgBAEgDABQgCACgEAAQgEABgEgDg");
	this.shape_24.setTransform(81,81.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AADAqIgDAAQgGgBgFgDQgEgEgEgHQgIgNABgQQgBgMAGgPQAFgNAHAAIADABIADAAIADAAIAEgBIAEABQAJADAFAKQAFAKABAQQAAASgIAOQgDAHgEADQgDADgFAAgAgGgRIgBAPQAAAHABAKQADAMADAAQACAAACgDIADgJQACgLAAgGQgCgbgHAAQgEAAgCAMg");
	this.shape_25.setTransform(70.4,81.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAhArQgDgBgCgDIgCgIIgBgPIAAgHIABgHQAAgKgBAAQgBgBgEAJIgKAcIgBAGQAAAFgDABIgEABQgDAAgEgCQgEgDgBgEQgCgFABgMIAAgVQAAgHgBAAIgGALIgFANIgCAPQgBACABAFQABAEgCACQgCACgDAAQgEAAgDgCIgGgFQgCgDAAgbIAAghIgBgEIgBgEIAAgDQACgCAIAAQAJgBACAFIABACIgCAEIgBAEIAAAQIAMgXIABgEIADgDQABgBAEAAQAGAAAFADQAGACAAAEIgBAFIgCAEIAAAeIAJgYIAEgMIADgFQADgCAGAAQAGABADABQADABABAEIAAA7QAAAAAAAAQAAABAAAAQABABAAAAQABABAAAAQADADAAACIAAADIgDAEQgCABgEAAQgEAAgDgBg");
	this.shape_26.setTransform(62.2,81.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUAiIgFgDIgBgEIABgDIADgEIAEgDIAEgBQABAAAAABQABAAAAAAQABAAAAAAQAAABAAAAIACAEIAEADQABACADAAQADAAACgFQACgFABgKIgKABIgHACQgCAAgCgCQgDgCAAgDIABgDIACgEIADgEQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAAAIAGACIAKgBIABgDIAAgCQAAgHgCgDQgBgDgDgCQgDABgCABIgFAEQgBAFgDABQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAIgEgBIgEgDIgDgDIgBgDQAAgEAGgCQAFgHAGgDQAIgDAGAAQAFABAFACQAEABAEADQAFAHAAARIgBAQIgEAVQgEAJgGAEQgGAEgHAAQgLAAgIgJg");
	this.shape_27.setTransform(53.8,81.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgbAIQgCgDAAgEQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAABAAIAHgBIAegFIAFgBIADgBIAEABIADAEQABACAAAEQAAACgCACIgDABIgDAAIgEgBIgeAFIgEACIgFABQgDAAgDgEg");
	this.shape_28.setTransform(143.3,63.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AALAoIAAgGIgMgVIgJAPIAAAKQgCAEgFAAQgFAAgFgEQgFgDABgEQAAgEAEgDIARgbIgOgWQgDgBgCgCIgBgEQAAgEAGgCQAEgDAFAAQAGAAACADIABAEIAAAFIAGALIAIgPIABgFQACgDAGAAQAGAAACABQAFACAAADIgBADIgFAGIgPAZIARAcQAHAEgBADQABADgGADQgEACgFAAQgGAAgBgCg");
	this.shape_29.setTransform(132.7,64.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAKAmIAAgEIgBgEQgEAFgFADQgDADgIAAQgFAAgDgCQgEgCgEgFIgDgHIgBgHQAAgHAEgFQAEgFAHgEIAVgNIAAgDQAAgBAAgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgCgBgDAAQgCAAgJAIQgFAFgDACQgFAAgDgGQgDgFAAgEQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAAAIAIgEQANgIALgBQALABAFAGQAFAHAAANIAAAcQAAAEACAGIAGAEIAAADQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAABQgBACgDABQgFAEgGABQgFgBgBgEgAgEAGQgHAEgBAFQAAAEABACQADAEACAAQAGgBADgJQADgIAAgGQgFABgFAEg");
	this.shape_30.setTransform(125.7,64.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AALApIgCgEIgBgDIgNgVIgFAAIAAASQACADAAADQAAAFgJAAQgEAAgFgCQgFgDAAgCQAAgCACgDIAAg7IgCgFQAAgHAKAAQAFAAAEADQAEACAAAEIgCAGIAAAXIADAAIASggQACgHAFABQAFAAAEADQAFADAAAFIgCADIgFADIgQAbQAGALAHAKIAEACQADABAAAEQAAADgDADQgFAFgGAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_31.setTransform(118.9,64.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgaAqQgEgDAAgCIACgFIgCg9IgBgFQAAgHAJAAQAFAAAFADQAEADAAADIgDAGIAAAkQALgbAJgSIAAgCQAAgDACgCQADgCAFAAQAFAAAEADQAEACAAAEIgCAGIAAA5IABAGQAAAGgIAAQgEAAgFgDQgFgCAAgCQAAgCACgEIAAgiIgTAsQgBAEgDABQgCACgEAAQgEABgEgDg");
	this.shape_32.setTransform(111.7,64.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgUApIgFgCIgDgCIgBgCIACgGIAAgWIgCgHIABgCIABgEIAAgYIgCgFQAAgGAKAAIAEAAIAFACIACADIABADIgCAHIAAARIASgCIAAgTIgBgGQAAgBAAAAQAAgBAAgBQABAAAAgBQABAAAAAAIAGgBQAGAAAEACQAEACAAAEIgCAHIAAAPIABAGIAAAEIgBACIAAAbIABAGQAAAFgIAAIgEgBIgFgBIgEgDIAAgCIABgGIAAgVIgSACIAAAXQACAEAAADQAAAFgJAAg");
	this.shape_33.setTransform(104.5,64.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgPArIgGgDIgFgDIgCgDIABgFIAAg8IgBgGQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQADgDAFAAQAGAAAEADQADACAAAEIAAACIgBACIgBAEIAAARQALgGAKAAIAFABQADABADACIAEAGQABAEAAAEIgBAJIgCAIQgEAIgHAFQgGAFgHADQgFADgGAAIgGgBgAAAACIgIAFIAAAVIAHgDIAFgGIAFgIQACgEAAgDIAAgEIgDAAQgEAAgEACg");
	this.shape_34.setTransform(97.7,64.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AATApIgFgBIgEgDQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIACgFIgIgoIgLApIABAEQAAADgDADQgDACgFAAIgHgBQgDgBgCgEIABgEQABgCAEgBIAQg4IAAgBIAAgBQAAgHAEgCQADgDAFAAQAFAAAEACQAEADAAAEQAAADgCADIAPA5IABAFQAAAGgHAAg");
	this.shape_35.setTransform(90.8,64.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AADAqIgDAAQgGgBgFgDQgEgEgEgHQgHgNgBgQQABgMAFgPQAGgNAGAAIACABIAEAAIADAAIAFgBIADABQAJADAFAKQAFAKAAAQQABASgIAOQgDAHgDADQgFADgDAAgAgHgRIgBAPQAAAHACAKQADAMADAAQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAgBIADgJQACgLAAgGQgCgbgHAAQgEAAgDAMg");
	this.shape_36.setTransform(84.2,64.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgTArQgFgDABgCIACgGIgCg2QgDgBAAgDQACgNALAAIAEAAIAVgCIAFgDQAEAAACAEQADAFABADQAAAEgCACQgCACgDABIgGgCIgSACIABA4QACAEAAADQAAAAAAABQAAABgBAAQAAABAAAAQgBAAAAABQgCABgFAAQgEAAgFgCg");
	this.shape_37.setTransform(78.2,64.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgLA2QgCgCgCgDIAAgDIABgDIABgDIAEgSIgVg8IgCgFIgCgEIABgCQABgFAIAAQAGAAADABQADADABAFIABAKIAKAeIAOglIABgHQABgDACgCIADAAQAEAAAFADQAEADABAEQAAADgCADIgDAGIgTAuIgFAPIgDANIAAAFIgBAFQgCADgEAAQgEAAgDgBg");
	this.shape_38.setTransform(71.6,65.9);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgNAnQgFgEgDgIQgFgNAAgOQAAgIABgGQABgIADgGQAEgGAFgEQAFgEAHABQAEAAAEACQAEACAEAFIAEAIIAEAKQAEAGgBADQgBAGgJgBIgFAAIgTACQAAAZAHAAIACgCIABgGIgBgCIAAgCQAAgEAEgCQAEgCAFAAQAFAAACACQACACAAAEIgCAGQgDALgEAEQgGAGgMAAQgFAAgFgDgAgFgWQgBAEgBAGIAMgBQgCgNgDAAQgDAAgCAEg");
	this.shape_39.setTransform(65,64.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgcAxIABgFIABgEIAAhSIgBgEIgBgEQAAgEAEgCQADgCAFAAQAEAAADACQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIAAABQAGgFAGAAQAGAAAEADQAEADAEAGQAFAKAAAQQAAAKgCAIQgBAHgEAGQgHAPgMAAIgEgBIgGgGIAAAPIACAGIACAGQAAAEgFADQgEAEgGAAQgKAAAAgKgAgFgTQAAAOACAFQACAJADAAQADAAACgJQACgFAAgNQAAgWgHAAQgHAAAAAVg");
	this.shape_40.setTransform(58.5,66.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAhArQgDgBgCgDIgCgIIgBgPIAAgHIABgHQAAgKgBAAQgBgBgEAJIgKAcIgBAGQAAAFgDABIgEABQgDAAgEgCQgEgDgBgEQgCgFABgMIAAgVQAAgHgBABIgGAKIgFANIgCAPQgBACABAFQABAEgCACQgCACgDAAQgEAAgDgCIgGgFQgCgDAAgaIAAgiIgBgEIgBgEIAAgCQACgDAIAAQAJgBACAFIABACIgCAEIgBAEIAAAQIAMgXIABgEIADgDQABgBAEAAQAGAAAFADQAGACAAAEIgBAFIgCAEIAAAeIAJgYIAEgMIADgFQADgCAGAAQAGABADABQADABABAEIAAA7QAAAAAAAAQAAABAAAAQABABAAAAQABABAAAAQADADAAACIAAADIgDAEQgCABgEAAQgEAAgDgBg");
	this.shape_41.setTransform(50,64.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgXAoIABABQgHgFAAgBQAAgDACgDIAAg7IgCgFQAAgHAKAAIAFABIAEAAIAFgBQAIgCAGAAQAHAAAFADQAEACACAEIABAGQAAAGgDAFQgDAFgGAFQAGAAADADQADADABAFIABAEQAAAOgMAMQgMAMgOAAQgIAAgHgFgAgBAGIgHAEIAAATIAFgCIAFgFQAFgEACgEQACgEAAgEQAAAAAAgBQAAgBgBAAQAAAAgBgBQAAAAgBAAQgDAAgGADgAgBgcIgHAEIAAARQAIgHAEgFQAGgFAAgEQgBgBAAAAQAAAAAAAAQAAgBgBAAQAAAAgBAAIgIACg");
	this.shape_42.setTransform(37.8,64.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAJA3IgBgCIABgDIABgEQgEAFgEACQgCADgFAAQgMAAgGgOIgDgMIgBgPQAAgIACgHQACgGACgGQAIgOAKAAQAGAAAGAJIAAgSQAAgDgCgDIgCgGIABgDQADgGAJAAQAHAAACAFIABADIgBAFIgBAEIAABSIABAEIABAEIAAACQgDAEgIAAQgGAAgCgCgAgEgHIgCAGQgCAHABAJIgBAFIAAAGQAAAIACAEQACAEAEAAQAAAAAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIACgHQADgJAAgJQAAgHgDgIQgCgKgCAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABg");
	this.shape_43.setTransform(126.8,46.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgdAnIgCgGIAAgPIAAgvIAAgEIgBgDQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAABgBQACgDADAAQAEAAAFADQAEACABACIAAADIgBAEIgBAFIAAAUQAGgNAHgNQAIgLALABQADAAACADIAEAJQACAIAAARIAAAZIACAEIABADQAAAEgEACQgEACgFAAQgHAAgDgEQABgsgEgBQgDAAgNAnIAAAJQgBAFgCADQgDACgDAAQgFAAgGgGg");
	this.shape_44.setTransform(119.8,47.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgYAoQgEgEgCgHIgBgKQAAgGADgGQAEgGAHgEIAWgNIAAgFQAAgFgCAAIgDgBQgEAAgBACIgEAEIgFAFQgCADgCABQgEAAgDgDQgDgDAAgEIABgEQADgGAHgEQAFgDAGgCQAGgBAHAAQAFAAAEACQADACACAFQACAGABASIADAdIADAFQACADAAACIAAACQgCAHgJAAIgFgBQgCgBgBgFIgDgNQgBAIgIAIQgDAEgEACQgFACgEAAQgFAAgEgDgAgBABQgFADgDAEQgFAGAAAEQAAADACAEQABABAAAAQAAAAABABQAAAAABAAQAAAAAAAAQAEAAAFgIQACgGAEgQg");
	this.shape_45.setTransform(112.1,47.8);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgFA9QgDgBgBgCIgBgEIABgEIABgGIgBhdIAAgIQABgCADgBQAEgCADAAQAGAAACADQAAAAAAABQABAAAAABQAAAAAAABQAAABAAAAIgBAFIgBAHIAABWIABAGIABAFIAAADQgCADgDABQgCACgEAAQgDAAgCgCg");
	this.shape_46.setTransform(106.7,46);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgbA5QgCgDAAgoIABhCIgBgCIAAgDIABgDQACgDAFAAQAFAAAEACQADADAAAEIgCABIgBADIAAAvQAIgSAPgCQAJAAAFANQAFAMAAASQAAAOgDALIABAFQAAADgEACQgDACgEAAQgDAAgCgCQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIgBgDIACgEIABgEQACgIAAgOQAAgYgDgBIgEACIgFAGQgGANgDAHIgDANIgBALIgBACIACAEIABADIgBADQgEAGgEAAQgEAAgEgHg");
	this.shape_47.setTransform(101.6,45.9);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgLAoQgEgCgDgHQgEgFgBgHQgBgGAAgJQgBgRAIgNQAHgQALAAQAFAAAEADQAFACADAGQACAEABAFQABAFAAAGIAAAEQgBAFgIABQgFAAgDgEQgBgBgBgGIAAgFIAAgDQABgHgDAAQAAAAgBAAQAAAAAAABQAAAAAAABQAAABAAAAIgDALQgDANAAANQAAAPAFAAQAEAAADgKIACgFQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQACgCADABQAEAAADABQAFADAAAEQgBADgDADIgEAHQgFAHgFADQgFAEgDAAQgHAAgEgDg");
	this.shape_48.setTransform(94.8,47.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgLAoQgGgEgDgGIgFgMQgCgIAAgJQAAgGACgIQABgHACgGQADgGADgEQAEgDAEgCIAIgBQALAAAHAHQAFAFACAIQADAJAAAMQAAARgHAMQgEAIgFADQgGAEgGAAQgGAAgFgDgAgGgSQgDAIAAAKQAAAMABAGQACAKAGABQAAAAABAAQAAAAABAAQAAgBAAAAQABgBAAAAIAEgJIADgMIAAgMQAAgVgJgBIAAAAQgEAAgDAKg");
	this.shape_49.setTransform(88.3,47.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgWA+QgEgCgBgCIgBgCIABgDIAAgVIAAgSIgEgGQgCgEABgCIACgCIADgCIAAgvIgBgEQAAgEAEgCIAFgBQAGAAAEACQADABABADIABADQAAACgDAEQgCAEAAACIgBAjIASgEQgBgMACgdIgCgGQAAgFAGgDIADAAQAFAAAFACQAGADAAAFQAAACgDADQgDADAAACIABAkQACABACAEQADADAAACQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABIgEACIAAAhIABAEIABAEQAAADgFACIgDABQgEAAgGgDIgFgDIgBgEIABgFIADgGIAAgZIgTAEIAAAUIABANIABAFIAAAGQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAQgCACgEAAQgDAAgEgCg");
	this.shape_50.setTransform(81.1,45.9);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgcAxIABgFIABgEIAAhSIgBgEIgBgEQAAgEAEgCQADgCAFAAQAEAAADACQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIAAABQAGgFAGAAQAGAAAEADQAEADAEAGQAFAKAAAQQAAAKgCAIQgBAHgEAGQgHAPgMAAIgEgBIgGgGIAAAPIACAGIACAGQAAAEgFADQgEAEgGAAQgKAAAAgKgAgFgTQAAAOACAFQACAJADAAQADAAACgJQACgFAAgNQAAgWgHAAQgHAAAAAVg");
	this.shape_51.setTransform(70.3,49.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgcArIgHgDIgFgDIgDgDIACgFIAAg8IgBgGQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQADgDAFAAQAFAAAEADQAFACAAAEIgBACIAAACIgCAEIAAARQANgGAJAAIAFABQACABADACIAEAGQABAEABAEIgBAJIgEAIQgEAIgGAFQgFAFgGADQgIADgFAAIgFgBgAgOACIgIAFIAAAVIAGgDIAHgGIAGgIQACgEAAgDIgBgEIgDAAQgDAAgGACgAAaAnQgFgDgBgCIADgFIAAg7IgCgGQAAgGAJAAQAGAAADACQAFADAAADIgDAHIAAA5QACADAAADQAAAAAAABQAAABgBAAQAAABAAAAQgBAAAAABQgCABgEAAQgFAAgEgCg");
	this.shape_52.setTransform(62.2,47.7);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgKApQgEgDgEgEQgGgLgCgQIAAgHIABgNIADgNQAHgPAMgBQAEAAAFACQAGACADAFIAFAJIACALIAAAFQAAADgDABQgDACgEAAQgEAAgCgCQgCgCgBgGIgBgJQgBgFgDAAQgCAAgCAIQgBAIAAAKQAAALABAIQADAJADAAQADAAADgGQADgFAAgEQAAgHAIAAQAEAAADACQADACAAADIgDAIQgFALgGAGQgGAFgHAAQgFAAgFgCg");
	this.shape_53.setTransform(54.6,47.6);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgaA6QgEgDAAgCIACgFIgCg9IgBgFQAAgHAJAAQAFAAAFADQAEADAAADIgDAGIAAAkQALgbAJgSIAAgCQAAgDACgCQADgCAFAAQAFAAAEADQAEACAAAEIgCAGIAAA5IABAGQAAAGgIAAQgEAAgFgDQgFgCAAgCQAAgCACgEIAAgjIgTAtQgBAEgDABQgCACgEAAQgEABgEgDgAgXgyQAAgFADgDQADgBAGAAQAHABABADQAAADgBACIACAEQAAAAABABQAAAAABAAQAAAAAAAAQAAAAABAAQAHAAADgFQABgDACgCQACgBADgBQADABACABQACACAAADIgBAEQgEAHgGADQgGADgIABQgVgBgDgRg");
	this.shape_54.setTransform(121.6,28.8);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgcArIgHgDIgFgDIgDgDIADgFIAAg8IgCgGQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABAAQABgDAGAAQAFAAAEADQAFACAAAEIgBACIAAACIgCAEIAAARQANgGAJAAIAFABQADABACACIAEAGQABAEABAEIgBAJIgEAIQgEAIgGAFQgFAFgGADQgIADgFAAIgFgBgAgNACIgJAFIAAAVIAGgDIAHgGIAGgIQACgEAAgDIgBgEIgDAAQgDAAgFACgAAaAnQgFgDgBgCIADgFIAAg7IgCgGQAAgGAKAAQAEAAAFACQADADAAADIgCAHIAAA5QACADAAADQAAAAAAABQAAABgBAAQAAABAAAAQgBAAAAABQgCABgFAAQgEAAgEgCg");
	this.shape_55.setTransform(113.1,30.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgUApIgEgCIgEgCIgCgCIACgGIAAgWIgBgHIAAgCIABgEIAAgYIgBgFQAAgGAJAAIAGAAIADACIADADIACADIgDAHIAAARIASgCIAAgTIgBgGQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAAAIAFgBQAIAAADACQAFACAAAEIgDAHIAAAPIACAGIgBAEIgBACIAAAbIACAGQgBAFgHAAIgGgBIgEgBIgEgDIgBgCIACgGIAAgVIgSACIAAAXQACAEAAADQAAAFgIAAg");
	this.shape_56.setTransform(104.8,30.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAiApIgCgDIAAgDQgLgMgIgLIgFAAIAAATIACAGQAAABAAAAQAAABgBABQAAAAAAAAQAAABgBAAQgCACgEAAQgDAAgFgDQgFgCAAgCQAAgDACgDIAAgSIgFAAQgGAKgJANIgDAGQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQgEgBgFgEQgEgDAAgFQAAgCACgCIAFgCQALgMADgKIgQgaIgFgCIgBgFQgBgEAFgDQAEgDAFgBQAFAAACAHIAAAAIATAgIADAAIAAgaIgCgFQAAgHAJAAQAFAAAEACQAEAEAAACIgDAHIAAAXIADAAIAVggQACgGAFgBQAEABAFADQAEADAAAEQABAFgHACIgSAaQAGALAMALIADACQADACAAACQAAAEgDADIgFAEQgCACgDAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_57.setTransform(95.9,30.5);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AADAqIgDAAQgGgBgFgDQgFgEgDgHQgHgNAAgQQAAgMAFgPQAFgNAHAAIACABIAEAAIADAAIAEgBIAEABQAJADAFAKQAFAKABAQQAAASgIAOQgDAHgEADQgEADgDAAgAgHgRIAAAPQgBAHACAKQADAMADAAQACAAACgDIADgJQACgLAAgGQgCgbgHAAQgEAAgDAMg");
	this.shape_58.setTransform(87.3,30.5);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgcAxIABgFIABgEIAAhSIgBgEIgBgEQAAgEAEgCQADgCAFAAQAEAAADACQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIAAABQAGgFAGAAQAGAAAEADQAEADAEAGQAFAKAAAQQAAAKgCAIQgBAHgEAGQgHAPgMAAIgEgBIgGgGIAAAPIACAGIACAGQAAAEgFADQgEAEgGAAQgKAAAAgKgAgFgTQAAAOACAFQACAJADAAQADAAACgJQACgFAAgNQAAgWgHAAQgHAAAAAVg");
	this.shape_59.setTransform(80.7,32);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AADAqIgEAAQgFgBgFgDQgFgEgDgHQgIgNAAgQQAAgMAGgPQAGgNAFAAIAEABIADAAIADAAIAFgBIADABQAJADAFAKQAGAKgBAQQAAASgGAOQgEAHgDADQgEADgFAAgAgGgRIgCAPQABAHACAKQACAMADAAQABAAAAAAQAAAAABgBQAAAAABgBQAAAAABgBIADgJQACgLAAgGQgCgbgHAAQgEAAgCAMg");
	this.shape_60.setTransform(74.2,30.5);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgWAoIAAABQgHgFAAgBQAAgDACgDIAAg7IgCgFQAAgHAJAAIAGABIADAAIAGgBQAIgCAGAAQAHAAAFADQAEACACAEIABAGQAAAGgDAFQgDAFgGAFQAGAAADADQADADACAFIAAAEQAAAOgMAMQgMAMgOAAQgIAAgGgFgAgBAGIgIAEIAAATIAGgCIAGgFQAEgEACgEQACgEAAgEQAAAAAAgBQAAgBgBAAQAAAAgBgBQAAAAgBAAQgEAAgFADgAgCgcIgHAEIAAARQAJgHAFgFQAEgFAAgEQAAgBAAAAQAAAAAAAAQAAgBgBAAQAAAAgBAAIgJACg");
	this.shape_61.setTransform(67.8,30.5);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgHA+QgGgDAAgCQAAgDADgFIAAhVIgMACQgEAEgDAAQgHABgCgKIAAgDQAAgFACgCQADgDAEgBIAHAAIAqgGQAEgEADAAQADgBAEAFQAEAFAAAFQABAEgCACQgCADgCAAIgJgBIgPABIAABbQADAFAAADQAAABAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgHABQgEAAgGgCg");
	this.shape_62.setTransform(60.3,28.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой 1
	this.instance = new lib.say_03();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,183,159), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_zelen();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,104,116), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_slivki();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,93,120), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_grib();
	this.instance.parent = this;
	this.instance.setTransform(0,88.1,1,1,-47.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(0,0,149,150.6), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0054A5").s().p("AirGCQgEgCgCgFIgBgFQAAgCACgDIADgFIAFgcIghhgIgEgHQgCgEAAgDIABgEQACgIANAAQAJAAAEADQAGADABAJIACAQIAPAwIAXg7IACgLQABgFAEgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIgmBhQgDALgBAKIAAAIQAAAFgCADQgDAEgIAAQgGAAgFgCgACIFfIgKgFIgIgFQgEgDAAgBQAAgDADgGIAAheIgCgKQAAgEACgCQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBADIgDAKIAAAbQATgKAQAAIAIABQAFACADAEQAEAEADAFQACAGAAAJQAAAHgBAHQgCAHgDAFQgHAMgJAIQgKAJgKAEQgLAEgJAAIgJgBgACgEeIgNAIIAAAiQAEgBAGgEIAKgKQAFgGAEgGQADgGAAgFIgBgGQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQgGAAgIADgAmSFZIAAABQgKgHAAgDQAAgDADgFIAAhfQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQAOgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAJIAAAHQAAAWgTATQgTASgXAAQgMAAgLgHgAlwEkQgIADgEADIAAAeQAEgBAEgCIALgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgKAFgAlwDtQgKADgCACIAAAaQAPgJAIgJQAHgIAAgGQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQgFAAgJADgAGAFYQgBgCAAgFIAAgSIAAgFIAAgFQACgEAIAAQAIAAAFADQAFACACAFIABAFIgBAOIAAAHQABAEgCADQgDAEgHAAQgLAAgHgIgAERFbQgGgEAAgEQAAgDADgGIgChgQgDgGAAgDQAAgKAPAAQAJAAAGAEQAGAEAAAFQAAADgEAHIAAA6QARgrARgdIgBgDQAAgFAEgDQAEgDAHAAQAIAAAHAEQAHAEAAAGQAAADgEAHIAABbQACAGAAAEQAAAJgNAAQgHAAgHgEQgIgEAAgEQAAgDADgFIAAg4QgRAjgPAlQgBAFgEADQgEADgFAAQgIAAgGgEgAhAFaQgIgEgFgHQgKgRgDgaIAAgMQAAgLACgKQACgKADgJQAKgYATgCQAIAAAJADQAIAEAFAHQAFAHADAIQADAIAAAIIAAAJQAAAEgFACQgFADgGAAQgGAAgDgDQgDgEgBgJIgCgOQgBgHgIAAQgDAAgCAMQgCANAAAQQAAASADANQADAOAFAAQAGAAAFgJQAFgJAAgGQAAgLANAAQAGAAAFADQAEADABAFIgFAMQgIASgKAJQgJAJgLAAQgKAAgHgEgADfFYQgIgEAAgDQAAgDADgGIAAheQgCgFAAgDQAAgLAPAAQAIAAAGAEQAHAEAAAGQAAACgEAIIAABbQADAGAAAEQAAAEgEACQgDACgHAAQgHAAgHgEgAALFYIgFgEIgCgDQAAgEADgFIAAgjQgCgFAAgGIAAgFIACgGIAAglQgDgFAAgDQAAgLAPAAIAIABIAHADIAEAEQACADAAACQAAADgEAIIAAAcIAegEIAAgfIgCgIQAAgFADgCQADgCAGAAQALAAAGAEQAHADAAAGIgEALIAAAYQACAEAAAFIgBAGIgBAGIAAApIACAKQAAAIgNAAIgHgBIgHgDIgGgDQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgDADgFIAAgjIgeAEIAAAlQADAFAAAFQAAAIgNAAgAkrFYQgIgEAAgEQAAgDADgFIAAhfQgCgFAAgDQAAgLAPAAQAIAAAGAFQAHAEAAAFQAAADgEAHIAAAkIAEAAIAfgyQAEgKAHAAQAHAAAHAFQAHAGAAAGQAAADgCADQgDADgFABIgaArQAJATAMAQIAHACQADADAAAFQAAAFgEAFQgIAIgJAAQgEAAgDgCIgCgFIgCgFQgLgQgKgTIgJAAIAAAdQADAGAAAEQAAAJgOAAQgGAAgIgEgAF/EbQgCgDAAgDIABgJQgDgdAAgfQAAgoAEgEQACgCAJAAQAJAAAEACQAFACABAEIABADIgDAOIAABNIADASQAAAEgEADQgDACgGAAQgMAAgGgIgAEWCvQAAgIAFgEQAFgDAKAAQAKABABAGQABAFgCADQAAAEADADQADACAEAAQALAAAFgKQABgFADgCQADgDAGAAQAFABACACQACADAAAFQAAADgBADQgGALgJAFQgJAGgNAAQgkgBgEgbgAA7BxIADgOIAAiCIgCgGQgCgEAAgCQAAgGAHgEQAFgDAIAAQAGAAAFADQAEACAAAEIAAADQAKgJALAAQAJAAAHAEQAHAFAFAJQAIARAAAZQAAAOgCANQgDAMgFALQgMAYgSAAQgEAAgFgDIgJgJIAAAYQAAADADAGQADAHAAACQAAAHgHAFQgHAFgJAAQgQAAAAgPgABeAFQACAWACAJQAEAOAFAAQAFAAAEgOQACgJABgWQAAgggMAAQgNAAAAAggAhNBSQgEgCgEgFQgBgDgBgIIgBgvQAAgQgCgBQgBAAgGAOIgQAsIgBALQAAAHgFACQgDABgDAAQgHAAgGgEQgGgEgCgGQgCgJAAgSIABgjQgBgJgBAAIgJAQQgFAJgCAMQgDALgBAOQgBACABAJQABAHgDACQgDADgFAAQgGAAgFgEQgGgDgDgEQgDgFgBgqIAAg1IgDgNIABgEQADgEAMAAQAPAAADAHIABADIgCAGQgDAEAAADIAAAaIAVgrIAEgFQADgDAGAAQAJAAAJAFQAJAEABAGQAAAFgCADIgCAGIgBAwQAEgIAKgeIAGgSQADgGACgCQAFgEAKAAQAJAAAFADQAFADAAAFIAABdQAAACAFAEQAFADAAAEIgBAFQgCAEgDACQgEACgFAAQgHAAgFgCgAC6BRIgKgEIgIgGQgEgCAAgCQAAgDADgFIAAheIgCgKQAAgEACgBQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBACIgDALIAAAaQATgKAQAAIAIACQAFACADADQAEAEADAFQACAGAAAIQAAAIgBAGQgCAHgDAGQgHAMgJAIQgKAIgKAFQgLAEgJAAIgJgCgADSARIgNAHIAAAiQAEgBAGgEIAKgKQAFgFAEgHQADgGAAgFIgBgFQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQgGAAgIAEgAFDBNQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA5QARgqARgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgDQAAgEADgFIAAg2QgRAigPAkQgBAGgEACQgEADgFAAQgIAAgGgEgAgBBPQgJgBgHgGQgIgGgGgKQgLgUAAgcQAAgTAJgVQAJgWAJAAIAKABIANgBIAFABQAPAFAHAQQAJARAAAXQAAAfgLAVQgGAKgFAFQgGAFgHAAgAgKgPQgCALAAAMQAAAMADAQQAEAUAFAAQAEAAADgGQACgEADgKQADgRgBgKQgCgqgMAAQgHAAgDASgAkLBPQgJgBgHgGQgIgGgGgKQgLgUAAgcQAAgTAJgVQAJgWAJAAIAKABIAOgBIAFABQAPAFAHAQQAJARAAAXQAAAfgLAVQgGAKgFAFQgGAFgHAAgAkUgPQgCALAAAMQAAAMADAQQAEAUAGAAQAEAAADgGQACgEADgKQADgRgBgKQgCgqgMAAQgIAAgDASgAERBLQgIgEAAgEQAAgDADgFIAAheQgCgEAAgEQAAgKAPAAQAIAAAGAEQAHAEAAAFQAAADgEAHIAABbQADAFAAAEQAAAFgEACQgDACgHAAQgHAAgHgEgAmYBKQgIgEAAgDQAAgDADgGIAAhdQgCgFAAgDQAAgLAPAAQAIAAAGAEQAHAEAAAGQAAACgEAIIAAAjIAEAAIAfgxQAEgLAHAAQAHAAAHAGQAHAFAAAGQAAAEgCACQgDADgFACIgaAqQAJASAMAQIAHADQADADAAAEQAAAFgEAGQgIAIgJAAQgEAAgDgCIgCgFIgCgFQgLgQgKgTIgJAAIAAAdQADAFAAAFQAAAIgOAAQgGAAgIgEgAFIheQAAgHAFgEQAFgEAKAAQAKACABAGQABAEgCADQAAAFADACQADACAEAAQALAAAFgJQABgFADgDQADgCAGAAQAFAAACADQACACAAAFQAAAEgBADQgGAKgJAGQgJAFgNAAQgkgBgEgbgACtioQgGgFACgFIAHgIQAIgIABgGQACgCAAgEQAAgEACgBQAAgBABAAQAAAAABgBQAAAAABAAQABAAAAAAQAGAAAGADQAGADABAEIAAADQAAAEgFAGIgNASQgHAJgEAAIgBAAQgEAAgFgFgAimi8QgJgEAAgEQAAgEAEgHIAAiJIgSAEQgHAFgEABQgMACgCgRIAAgEQAAgIADgEQADgEAHgBIAMAAIBDgKQAHgGADgBQAGgBAHAJQAFAHABAIQABAGgDAEQgDAEgEABIgOgDIgXADIAACQQAEAHAAAGQAAAEgDACQgEACgHAAQgIAAgJgEgACSi7QgEgCgEgEQgBgDgBgJIgBgvQAAgQgCAAQgBgBgGAOIgQAsIgBALQAAAHgFACQgDACgDAAQgHAAgGgEQgGgFgCgGQgCgIAAgSIABgkQgBgJgBgBIgJARQgFAKgCALQgDAMgBANQgBADABAIQABAHgDACQgDADgFAAQgGAAgFgDQgGgDgDgEQgDgGgBgpIAAg3IgDgMIABgEQADgFAMAAQAPAAADAHIABAEIgCAGQgDAEAAACIAAAaIAVgrIAEgFQADgCAGAAQAJAAAJAEQAJAEABAGQAAAGgCADIgCAFIgBAyQAEgIAKgfIAGgSQADgHACgBQAFgEAKAAQAJAAAFADQAFACAAAGIAABdQAAADAFADQAFAEAAAEIgBAEQgCAFgDACQgEACgFAAQgHAAgFgDgAgri+QgJgBgHgGQgIgFgGgLQgLgUAAgbQAAgUAJgWQAJgWAJAAIAKACIAOgCIAFABQAPAGAHAPQAIARAAAZQAAAegKAWQgGAKgFAFQgGAFgHAAgAg0kcQgCALAAANQAAAMADAPQAEAUAGAAQAEAAADgFQACgFADgKQADgRgBgKQgCgqgMAAQgIAAgDASg");
	this.shape.setTransform(41.7,38.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(0,0,83.4,77.6), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.say_06();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(0,0,183,152), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmhH9IADgOIAAiDIgCgGQgCgEAAgCQABgGAGgEQAFgCAIAAQAHAAAEACQAEADABADIAAADQAKgJAKAAQAJAAAHAFQAHAFAFAIQAIARAAAaQABAPgDAMQgDAMgFAMQgLAXgTAAQgEAAgEgDIgJgIIAAAYQAAACACAHQADAGAAADQABAHgIAFQgHAEgIABQgQgBgBgPgAl+GSQACAVACAJQAEAPAFAAQAFAAAEgPQADgJABgVQAAgigNAAQgNAAAAAigAFuHcQgFgEgDgEQgCgDAAgFIAAgIIgBgLIAAgDQACgDAIAAQAGAAAFACQAFACACAEQACADAAAEIAAAIIADANIgCAEQgDAFgFABQgFAAgHgFgAhNHWQgIgGgFgNQgJgTAAgWQABgOACgMQACgLAEgJQAGgLAIgFQAIgGALAAQAIAAAHAEQAGADAGAIQAEAGADAGIAEAQQAIAJgCAGQgBAKgPAAIgIgBIgfACQAAAoAMAAQAAAAABAAQAAAAABAAQAAgBABAAQAAgBABgBQABgDAAgHIAAgBIgBgFQgBgFAHgEQAGgDAIAAQAIAAADADQAEADgBAGIgDAKQgEARgHAHQgKAKgTAAQgKAAgGgGgAhAF1QgDAFgBAKIAVgCQgFgSgFgBQgFABgCAFgAi0HXQgJgGgHgKQgFgIgGgSQgCgLgCgaIABgYQABgLACgLQADgKAEgJQAGgJAHgHIAhgWIABgDIACgEIAEgEQACgBADAAQADAAAEACIAHAFIAGAGQACADAAADIgBAHIgDADIgFAEIglAVQgPAKAAAPQAAAAABABQAAAAAAAAQAAAAABAAQAAAAABAAIACgBIADgDQAFgFAFgBIANgBQAHgBAGAEQAIADAFAIQAGAHADAMQADAMAAAOQgBAVgDAJQgEANgHAJQgGAJgJAFQgJAFgKAAQgKAAgJgFgAirF0IgEAGIgEAKIgBANQAAAKACAKIAEAQQAEAGADAEQADADADAAQADABADgEQAEgDACgGQADgGAAgIQACgIAAgKQAAgHgCgHIgEgMQgDgFgEgCQgEgEgEAAQgDAAgDADgAkjHWQgHgGgFgNQgIgTAAgWQAAgOABgMQADgLAEgJQAGgLAIgFQAIgGALAAQAIAAAGAEQAHADAFAIQAFAGACAGIAGAQQAHAJgCAGQgBAKgPAAIgHgBIghACQABAoAMAAQAAAAABAAQAAAAABAAQAAgBABAAQAAgBABgBQABgDAAgHIgBgBIAAgFQAAgFAGgEQAHgDAHAAQAIAAADADQAEADAAAGIgEAKQgEARgIAHQgJAKgTAAQgJAAgIgGgAkVF1QgDAFgBAKIAVgCQgFgSgFgBQgEABgDAFgAEdHUIAAgHIgCgFQgGAIgHAFQgHAFgMAAQgHAAgGgEQgGgDgFgIIgGgMQgCgFAAgGQABgKAGgIQAGgIAMgIIAigVIAAgFQAAgFgDgCQgDgCgFAAQgEAAgOAMQgHAKgFABQgHAAgGgIQgFgKAAgFQAAgDAEgDQAEgEAIgCQAUgNAUgBQARABAIAJQAJALAAAVIAAAuQgBAGADAJQAGADADAEIAAAFQAAADgBAEIgHAGQgIAGgJAAQgHgBgDgGgAEGGiQgLAHgCAGQgBAHADAEQAEAGADgBQAKAAAHgPIAFgWQgJACgJAGgAAJHXIgFgEIgCgDQAAgEADgFIAAgjQgCgFAAgGIAAgGIACgFIAAgmQgDgEAAgEQAAgKAPgBIAIABIAGAEIAFAEQACADAAACQAAADgFAIIAAAbIAfgDIAAgfIgCgJQAAgEADgDQADgCAGAAQALAAAGAFQAHADgBAGIgDALIAAAYQABAEAAAFIAAAFIgBAHIAAApIACAKQAAAIgNAAIgHgBIgIgDIgFgDIgCgEQAAgDADgGIAAgiIgfAEIAAAkQADAGABAEQAAAJgOAAgAB4HXQgIgFAAgDQAAgDADgFIAAhfQgCgFgBgDQABgLAPAAQAIAAAGAFQAGAEABAFQAAACgEAIIAAAkIAEAAIAfgyQAEgLAHAAQAHABAHAFQAHAGAAAFQAAAEgCADQgDADgFABIgbArQAKATAMAQIAGACQAEADAAAFQAAAEgFAGQgHAIgJAAQgEAAgDgCIgDgFIgBgFQgLgQgKgTIgJAAIAAAdQADAFAAAFQAAAIgOABQgHAAgHgEgAFjGjQgIgHAAgHQAAgFADgMQAFgLAKgRQASgkAAgKQAAgFgCAAQgFgBgFAHQgHAGgJANIgDAGQgCADgDACQgDABgEABQgGAAgFgFQgGgDABgHQAAgEADgEQADgCAFgCQAMgQAJgHQAHgGAGgCQAGgCAGgBQAKABAKAHQAGAFADAGQAEAFAAAIQAAANgOAYQgUAigCAHIgCAGIAAADIAAADIABAJQAAAEgDABQgCACgDAAQgHAAgHgFgAnMDoIgGgDIgGgEQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgEACgFIAAgUQgCgGAAgCQAAgDACgDIADgCIAJgDIABAAQAFgMAGgVIAMgyQgDgFAAgDQAAgLAPAAIAFAAIAFACIAIADIAWACQAEABACACQADACAAAFIgEAKIAHBGIACAAIAIABIAGADIACAEIABADIgEALIgBAWQACAFAAAEQAAAFgEACQgDACgGAAIgFgBIgPgHQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgEADgFIABgPIg3AHIAAALQADAGAAAEQAAAFgEACQgDACgHAAgAmcBvIgRBAIAcgDIgHhIIgDgBgAGiDNQgKAAgHgHQgIgFgFgKQgMgVAAgbQABgUAIgVQAJgXAJAAIAKACIAOgCIAGABQAOAGAIAQQAIAQAAAZQAAAegLAWQgGAKgFAFQgGAFgHAAgAGYBvQgCALAAANQAAAMADAPQAEAVAGAAQAEAAADgGQADgEACgLQADgQAAgLQgDgqgMAAQgHAAgEASgAEmDLQgIgEAAgEQAAgCAEgGIgDhXQgEgCAAgFQACgTARgCIAIABIAigEQAFgEAEAAQAFAAAFAGQAEAHAAAHQABAFgDAEQgEADgFAAQgDABgHgDIgdADIACBaQADAGAAAEQAAAFgDACQgEACgGAAQgIAAgHgEgAB6DNQgJAAgHgHQgIgFgFgKQgLgVAAgbQAAgUAJgVQAIgXAJAAIAKACIAOgCIAGABQAOAGAHAQQAJAQAAAZQAAAegLAWQgFAKgGAFQgGAFgHAAgABxBvQgCALAAANQAAAMADAPQAEAVAGAAQAEAAADgGQADgEACgLQADgQAAgLQgDgqgMAAQgIAAgDASgAjeDOIgHgDQgEgCgCgDQgCgDAAgDQABgFACgCQADgDAFgDIAUgZQgEAAgEgDIgJgGQgDgDgDgGQgCgEAAgFQgBgPAIgMQAHgKAKgHQAKgGALgEQALgDAIAAQAEAAAEABIAGAEIAGAFIABAGIgEAKIAABbQADAFAAAFQAAAFgDACQgEABgGAAIgHAAIgHgDIgGgEQgBAAAAgBQgBAAAAgBQAAgBAAAAQgBgBAAAAQAAgEADgEIAAgeIgXAnQgCAIgDACQgCACgEAAgAi7BpIgHAGIgGAGQgCAEAAAEQAAAEADADQAEACADAAIAFgDQADgCAEAAIAAgcgADLDJQgHgHgFgMQgIgTAAgXQAAgOACgLQACgMAEgIQAGgLAIgGQAIgGALAAQAIAAAHAFQAGADAFAIQAFAFACAHIAGAQQAHAIgCAGQgBALgPAAIgHgBIghACQABAoAMAAQAAAAABAAQAAAAABgBQAAAAABgBQAAgBABgBQABgDAAgGIAAgCIgBgEQAAgGAGgDQAHgDAHgBQAIAAADADQAEAEAAAGIgEAKQgEAQgIAHQgJALgTgBQgJAAgIgFgADZBoQgDAEgBALIAVgCQgEgTgGAAQgEAAgDAGgAAxDNIgHgDIgFgEQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAAAQAAgEAEgFIgGgtIgSAqIAAACQgBAHgDAEQgDADgKAAQgKAAgFgEQgDgDAAgHIAAgBIAAgBIgUgtIAAAxQADAGAAAEQAAAFgDACQgDACgHAAIgHgBIgIgDIgFgEIgCgDQAAgEADgFIAAhfQgDgEAAgDIABgGQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBABAAIAGgBIAWgCIAGADQADACAAADIAAAEIgCAFIAfBFIAdhFIgCgJQAAgEAGgCQAEgDAIAAIAJABIAIADIAFAEQACADAAADQAAAFgEAFIAFBbQADAGgBAEQAAAFgCACQgEACgGAAgAlPDMQgGgCgDgFIACgGQACgDAFgDIAahZIAAgEQABgKAFgEQAGgFAJAAQAIAAAGAEQAGAEABAHQAAAEgEAFIAXBaQADAGAAAEQAAAIgLAAIgJgBIgHgCIgGgEQgBAAAAgBQgBAAAAgBQAAgBAAAAQgBgBAAAAQAAgEAEgEIgNhBIgSBBIAAAHQABAGgFAEQgFADgHAAQgFAAgGgCgAjTg/QgJgBgHgGQgIgGgFgKQgMgUAAgcQABgTAIgWQAJgWAJAAIAKABIAOgBIAGABQAOAFAHAQQAJARAAAYQAAAfgLAVQgFAKgGAGQgGAEgHAAgAjcidQgCAKAAANQAAANADAPQAEAUAGAAQAEAAADgFQADgFACgKQADgRAAgKQgDgqgMAAQgHgBgEATgACshEQgIgGgFgMQgJgUAAgWQAAgPACgLQADgLAEgJQAGgLAIgGQAIgFAMAAQAHAAAGAEQAHAEAGAHQADAGAEAGIAEAQQAIAJgBAGQgCAKgPAAIgIgBIgfACQAAApAMAAQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAgBQACgDAAgHIgBgBIgBgFQAAgFAHgEQAHgDAHAAQAIAAAEADQADADgBAGIgCALQgFAPgHAIQgKAKgTAAQgKAAgGgGgAC5ilQgDAFgBALIAVgDQgEgSgGgBQgEABgDAFgAgWhEQgHgGgFgMQgJgUABgWQAAgPACgLQACgLAEgJQAGgLAIgGQAIgFALAAQAHAAAHAEQAGAEAFAHQAFAGACAGIAGAQQAHAJgCAGQgBAKgPAAIgHgBIggACQABApAMAAQAAAAAAgBQAAAAABAAQAAgBABAAQAAgBABgBQABgDAAgHIAAgBIgBgFQAAgFAGgEQAGgDAIAAQAIAAADADQAEADAAAGIgEALQgEAPgIAIQgJAKgSAAQgJAAgIgGgAgIilQgDAFgBALIAUgDQgEgSgFgBQgFABgCAFgABAhHQgHgEgCgEQgDgEgBgDQABgPAPgBQAEABAEAEIAFAFIAFABQAFAAAIgKQAIgLAAgEQABgFgDgBQgCgBgEACIgDACQgJAIgDAAQgHgBgHgEQgGgGAAgHQAAgFAGgDIALgEQATgKAFgNQABgEgBgEQgFAAgFADQgHADgGAHQgGAEgEAAQgIABgFgHQgGgFAAgJQAAgGAHgBIAJgCIAVgNQANgGALADQAJADAGAGQAGAHgBAKQgBARgOAPQAIADAEAEQAFAEACAFQAAAXgSAUQgTAVgQgBQgJAAgLgIgAiQhBQgGgCgDgFIACgFQACgEAFgCIAahZIAAgEQAAgKAGgFQAGgFAKAAQAHABAGAEQAHADAAAHQgBAFgDAEIAXBbQADAFAAAEQAAAJgMAAIgIgCIgHgCIgGgEQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAAAQABgEADgFIgNhBIgSBBIAAAIQABAFgFAEQgGAEgFgBQgGABgGgDgAEDhDIgFgEIgDgDQABgEADgFIAAgjQgCgFAAgGIAAgGIACgFIAAgmQgDgEAAgDQAAgMAPAAIAIABIAHAEIAEAEQACACAAADQAAADgEAHIAAAcIAegDIAAgfIgCgJQAAgEADgCQADgDAGAAQALAAAGAFQAGADAAAGIgDAKIAAAZQACAEAAAFIgBAFIgBAGIAAAqIACAKQAAAIgNAAIgHgBIgHgDIgGgDIgCgEQAAgDADgGIAAgiIgeADIAAAlQACAGAAAEQAAAJgMAAgAklhDQgHgEgBgEQAAgDADgFIAAhWIgZAFIAABRQADAJAAACQAAAJgNAAQgHAAgIgEQgHgEAAgEQAAgDACgFIAAhfQgCgEAAgDQAAgMAPAAQAKAAAGAGIAngGQAHAAAGAEQAIADAAAHQAAAEgEAGIAABbQACAHABADQgBAJgNAAQgGAAgIgEgACjkrIADgOIAAiCIgCgHQgCgDAAgCQAAgHAGgDQAGgDAIAAQAGAAAFACQAEADAAAEIAAACQAKgIALgBQAIAAAHAFQAHAFAGAJQAIAQAAAaQAAAPgDAMQgCANgFALQgMAXgTAAQgEAAgEgDIgJgIIAAAYQAAADADAGQADAHAAACQAAAHgIAFQgGAFgJAAQgQAAAAgQgADGmWQABAWADAIQAEAPAFAAQAFAAAEgPQACgIABgWQAAgigMAAQgNAAAAAigAH4knQgEgCgCgFIgBgFQAAgCACgCIACgGIAGgcIgihgIgDgHQgCgEAAgDIABgEQACgHANgBQAIAAAFADQAGADABAJIACAQIAOAwIAYg7IACgLQABgFAEgCQACgCADAAQAHABAHAFQAGAEABAHQABAEgDAGIgFAJIgmBhQgDAMgBAJIgBAIQABAFgCADQgDAFgIAAQgGAAgFgDgAjPlOQgFgEAAgEQAAgDACgGIgChgQgCgFAAgDQAAgLAOAAQAJAAAGAEQAHAEAAAGQgBACgEAHIAAA6QARgqARgeIAAgDQAAgFADgDQAEgDAHABQAIAAAHADQAHAEAAAGQAAADgEAIIAABbQADAFAAAFQAAAIgOAAQgGAAgIgEQgHgEAAgEQAAgDACgFIAAg4QgQAkgPAkQgCAFgEADQgDADgGAAQgHAAgHgEgAJilPQgHgDgFgIQgKgQgDgbIgBgLQABgLACgLQACgJADgKQAJgYAUgCQAIAAAIAEQAJADAFAHQAEAIAEAIQADAHAAAIIAAAJQAAAEgFACQgFADgGAAQgGAAgDgDQgDgEgBgIIgCgPQgBgHgIAAQgDAAgDANQgBAMAAAQQAAATACAMQADAOAGAAQAGAAAFgJQAEgIABgHQAAgLANABQAFAAAFACQAFADAAAFIgEAMQgIATgKAIQgKAJgLAAQgJAAgIgEgAkSlNQgKAAgHgHQgIgFgFgKQgMgVAAgbQABgUAIgVQAJgXAJAAIAKACIAOgCIAGABQAOAGAIAQQAIAQAAAZQAAAegLAWQgGAKgFAFQgGAFgHAAgAkcmrQgCALAAANQAAAMADAPQAEAVAGAAQAEAAADgGQADgFACgKQADgRAAgKQgDgqgMAAQgHAAgEASgAEhlRQgHgHgGgMQgIgTAAgXQAAgOACgMQACgKAEgJQAGgMAJgFQAIgGALAAQAIABAGAEQAGADAGAHQAEAGADAHIAFAQQAHAIgBAGQgCAKgPAAIgHAAIggACQAAAoAMAAQABAAAAAAQABAAAAgBQABAAAAgBQABgBAAgBQACgDAAgGIgBgCIgBgEQAAgFAGgEQAHgDAIgBQAHAAAEADQAEAEgBAGIgDAKQgEAQgIAHQgKAKgTAAQgJAAgHgFgAEumyQgCAEgBALIAVgCQgFgTgFAAQgFAAgDAGgABTlRQgHgHgGgMQgIgTAAgXQAAgOACgMQACgKAEgJQAGgMAJgFQAHgGAMAAQAIABAGAEQAHADAFAHQAEAGADAHIAFAQQAIAIgCAGQgCAKgPAAIgHAAIggACQAAAoAMAAQABAAAAAAQABAAAAgBQABAAAAgBQABgBAAgBQACgDAAgGIgBgCIgBgEQAAgFAGgEQAHgDAIgBQAHAAAEADQAEAEgBAGIgDAKQgFAQgHAHQgJAKgTAAQgKAAgHgFgABgmyQgCAEgBALIAUgCQgEgTgFAAQgFAAgDAGgAqSlQQgKgFAAgDQABgEAEgHIgDiRQgEgHAAgFQABgFAEgDQAEgDAJAAQAKABAIAFQAGAFABAFQgBADgGALIADBEIAGAAQAHgUAPgdQALgTAMgSIACgGQADgHAGAAQAHABAJAGQAKAIgBAJQgBAGgLAEIgrBLQANAWAbAZQAHABABACIACACQAEADAAAFQAAAFgGAGQgEAGgFADQgEADgGgBQgEAAgDgCQgBAAgCgHIgCgGQgRgQgUgfIgMAAIAAAqQAEAHAAAGQAAAEgEACQgCACgIAAQgIAAgJgEgAAUlRQgHgEAAgDQAAgEACgEIAAhWIgYAEIAABSQADAIAAADQAAAIgNAAQgHABgIgFQgHgEAAgDQAAgEACgEIAAhfQgCgFAAgDQAAgLAPAAQAKAAAGAFIAmgFQAHAAAGADQAIADAAAIQAAADgEAHIAABbQACAHABADQgBAIgNAAQgGABgIgFgAnUlTIAAgHIgCgGQgGAIgHAGQgHAEgMAAQgHAAgGgDQgHgEgEgHIgGgMQgCgGAAgGQABgKAGgHQAGgJAMgIIAigUIABgGQAAgEgEgDQgDgCgFAAQgEABgOAMQgHAJgFACQgIAAgEgJQgGgJAAgFQAAgDAEgDQAEgEAIgCQAUgNAUgBQAQAAAJAKQAIAKAAAVIAAAuQABAHACAJQAFACADAFIABAEQAAAEgCAEIgGAGQgIAFgIAAQgIgBgDgFgAnrmFQgLAGgCAHQgBAGAEAFQADAFADAAQAKgBAHgPIAFgWQgIACgKAHgAF3lRQgHgEAAgDQAAgDADgGIAAhfQgDgEAAgDQAAgMAPAAQAJAAAGAFQAHAEgBAGQAAACgEAHIAAAkIAFAAIAfgyQAEgKAHAAQAHAAAHAGQAHAFAAAGQAAADgDADQgCADgFABIgbArQAKATAMAQIAHACQADADAAAFQAAAFgFAFQgHAJgJgBQgEAAgDgBIgCgGIgDgEQgKgRgKgSIgKAAIAAAcQADAGAAAEQAAAJgNAAQgGAAgJgEgAmglRQgIgEAAgDQAAgDAEgGIAAhfQgDgEAAgDQAAgMAPAAQAIAAAHAFQAGAEAAAGQAAACgEAHIAAAkIAEAAIAggyQADgKAHAAQAHAAAIAGQAGAFAAAGQAAADgCADQgDADgFABIgaArQAKATAMAQIAGACQADADABAFQgBAFgEAFQgIAJgIgBQgFAAgCgBIgDgGIgCgEQgLgRgKgSIgJAAIAAAcQADAGAAAEQAAAJgNAAQgHAAgIgEgAjKn6QAAgHAGgEQAEgEAKAAQAKACABAFQACAFgDADQABAFACACQADACAEAAQALAAAFgJQABgFADgDQADgDAGABQAFAAACACQADADAAAFQAAADgCAEQgFAKgKAFQgJAGgNAAQgkgBgEgbg");
	this.shape.setTransform(67.1,52.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,134.1,104.9), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.hohlogo();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.563,0.563);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,135,112.5), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.man2();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(0,0,299,654), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.mal();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(0,0,403,671), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.say_03();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(0,0,183,159), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.man1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(0,0,261,642), null);


(lib.Анимация11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhzBoIADgPIAAiBIgCgHQgCgDAAgDQAAgGAGgDQAFgDAIAAQAHAAAEACQAFADAAAEIAAACQAKgIAKgBQAJAAAHAFQAHAFAFAJQAJAQAAAaQAAAOgDAMQgCANgGALQgLAXgTAAQgEAAgEgCIgJgJIAAAYQAAADADAGQADAHAAACQAAAHgIAFQgHAFgIAAQgQAAAAgPgAhQgDQABAVADAIQADAPAFAAQAGAAADgPQADgIABgVQAAghgNgBQgMABAAAhgAlPBgIgHgDIgGgEQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgEADgFIAAgUQgCgGAAgCQAAgDABgDIAEgCIAJgDIABAAQAFgMAFgVIANgxQgDgFAAgDQAAgLAPAAIAFAAIAFACIAIADIAWACQAEABACACQADACAAAFIgEAKIAHBFIACAAIAIABIAFADIADAEIABADIgEALIgCAWQADAFAAAEQAAAFgEACQgDACgGAAIgFgBIgPgHQAAAAgBgBQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgEAEgFIABgPIg3AHIAAALQADAGAAAEQAAAFgEACQgDACgHAAgAkggYIgQA/IAbgDIgGhHIgDgBgADZBIIgKgEIgJgGQgDgDAAgBQAAgDADgFIAAheIgCgKQAAgEACgBQADgFAJAAQAIAAAHAFQAGADAAAHIAAACIgDAKIAAAbQATgKAPAAIAJABQAEACAEAEQAEAEACAGQADAEAAAJQAAAIgCAGQgBAHgEAFQgGAMgKAJQgJAIgLAEQgLAEgJABIgIgCgADxAHIgOAIIAAAiQAEgBAGgEIALgKQAFgGADgGQAEgGAAgFIgBgFQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgGAAgHADgABkBDIAAAAQgLgHAAgCQAAgDADgGIAAheQgDgFAAgDQAAgLAQAAIAIABIAFABIAJgCQAOgCAKAAQALAAAHADQAHADADAHQACAFAAAGQAAAIgFAHQgFAJgJAHQAJABAFAFQAGAFABAHIABAIQAAAWgTASQgTASgXABQgNgBgKgGgACGANQgJAEgDADIAAAdQADgBAFgCIALgIQAGgHAEgGQADgGAAgGQAAgFgFAAQgFAAgKAFgACFgpQgKADgBACIAAAaQAPgJAHgJQAHgHAAgHQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgFAAgKADgAFiBEQgGgEAAgEQAAgDADgGIgDhfQgCgGAAgDQAAgKAPAAQAIAAAGAEQAHAEAAAGQAAACgEAIIAAA4QARgqAQgdIAAgDQAAgFAEgDQADgDAIABQAIAAAGADQAHAEAAAGQAAAEgEAGIAABbQADAFAAAFQAAAIgNAAQgHAAgIgEQgHgEAAgEQAAgDADgFIAAg3QgRAjgPAkQgCAFgDADQgEADgGAAQgHAAgGgEgAAdBFQgJAAgHgHQgIgFgFgKQgLgVAAgaQAAgUAJgVQAIgXAJAAIAKACIAOgCIAFABQAPAGAHAQQAJAQAAAZQAAAdgLAWQgGAKgFAFQgGAFgHAAgAAUgYQgCALAAANQAAALADAPQAEAVAGAAQAEAAADgGQACgEADgLQADgQgBgKQgCgqgMAAQgIAAgDASgAiwBFQgJAAgIgHQgHgFgGgKQgLgVAAgaQAAgUAJgVQAIgXAJAAIAKACIAOgCIAGABQAOAGAIAQQAIAQAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAi6gYQgCALAAANQAAALADAPQAEAVAHAAQADAAADgGQADgEACgLQADgQAAgKQgDgqgMAAQgHAAgEASgAmyA9QgGgDgDgFQgDgEAAgDQABgOAPgBQAEAAADAEIAFAFIAFABQAGAAAHgKQAIgKABgFQAAgEgCgCQgDAAgDABIgDADQgKAHgDAAQgHAAgGgFQgHgFAAgHQAAgFAHgCIAKgFQATgJAFgOQABgEgBgEQgFAAgFADQgGAEgHAGQgGAFgEAAQgIAAgFgGQgGgGAAgJQAAgGAHgBIAKgCIAVgMQAMgHALAEQAJADAGAGQAGAHAAAJQgCARgOAPQAIAEAFADQAFADABAGQAAAWgSAVQgTAUgQAAQgJAAgLgJgAEvBCQgHgEAAgEQAAgDADgFIAAheQgDgEAAgEQAAgLAPAAQAIAAAHAFQAGAEAAAFQAAADgEAHIAABaQADAGAAAEQAAAFgDACQgDABgHAAQgHAAgIgDgAFnhnQAAgHAFgEQAFgEAJAAQALACABAFQABAFgDADQABAFACACQADACAEAAQALAAAFgJQABgFADgDQAEgCAFAAQAFAAADACQACADAAAFQAAAEgCADQgFAKgKAFQgJAGgNAAQgjgBgEgbg");
	this.shape.setTransform(-41.6,0.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-86.3,-11.1,89.5,23.8);


(lib.Анимация9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjnBbIAAAAQgLgHAAgCQAAgDADgGIAAheQgDgFAAgDQAAgLAQAAIAIABIAFABIAJgCQAOgCAKAAQALAAAHADQAHADADAHQACAFAAAGQAAAIgFAHQgFAIgJAHQAJABAFAFQAGAFABAIIABAIQAAAWgTASQgTASgXABQgNgBgKgGgAjFAlQgJAEgDADIAAAdQADgBAFgCIALgIQAGgHAEgGQADgGAAgGQAAgFgFAAQgFAAgKAFgAjGgRQgKADgBACIAAAZQAPgJAHgIQAHgHAAgHQAAgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgFAAgKADgAD/BcQgGgEAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA4QARgqARgdIgBgDQAAgFAEgDQAEgDAHABQAIAAAHADQAHAEAAAGQAAAEgEAGIAABbQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgEQAAgDADgFIAAg4QgRAkgPAkQgBAFgEADQgEADgFAAQgIAAgGgEgACMBcQgGgEAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA4QARgqARgdIgBgDQAAgFAEgDQAEgDAHABQAIAAAHADQAHAEAAAGQAAAEgEAGIAABbQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgEQAAgDADgFIAAg4QgRAkgPAkQgBAFgEADQgEADgFAAQgIAAgGgEgAk/BaQgKgIgHgNQgMgYAAgvQAAgTADgQQACgQAFgNQAMgeAXAAQAKAAAHADQAIAEAFAJQAJANAEATIAFAOQAAAMgOAAQgJAAgIgDQgIgFAAgFIADgJQgBgMgCgEQgDgGgFAAQgGABgDAWQgEAeAAARQABAhADALQACALACAEQADAFADAAQAGAAAFgNQAEgMAAgIQAAgHAGgEQAFgDAHgBQAHAAAFADQAFAEAAAFQAAADgCAEIgEAGQgEARgKAOQgGAJgGAGQgHAEgGAAIgCABQgLAAgKgGgAhzBZQgIgHgFgMQgIgTAAgXQAAgOACgMQACgKAEgIQAGgLAIgGQAIgGAMAAQAHAAAHAFQAGADAGAHQAEAGADAHIAFAPQAHAIgBAGQgCALgPAAIgHgBIggACQAAAoAMAAQABAAAAAAQAAAAABgBQAAAAABgBQAAgBABgBQABgDAAgGIAAgCIgBgEQAAgGAGgDQAHgDAHAAQAIAAAEACQADAEAAAGIgDAKQgFAQgHAHQgKALgTgBQgJAAgHgFgAhmgHQgDAEgBAKIAVgCQgEgSgGAAQgEAAgDAGgAAdBaQgHgFAAgCQAAgEADgFIAAgbIgIAAQgJAPgOAUIgEAKQgDABgEAAQgHABgHgHQgHgFAAgIQAAgEAEgDIAGgCQASgUAGgPIgbgqQgFgBgCgDQgDgDAAgDQAAgGAHgFQAHgGAHAAQAIAAADAJIAAABIAeAxIAEAAIAAgoQgDgEAAgDQAAgMAPAAQAIAAAHAFQAGAEAAAFQAAADgEAHIAAAjIAEAAQAbglAGgMQADgKAIAAQAHAAAHAGQAHAFAAAGQAAAHgKADIgdAqQAKAQATATIAGACQAEADAAAFQAAAFgFAFQgEAFgEACQgEABgEAAQgFAAgCgBIgDgGIgCgEQgRgTgLgQIgIAAIAAAcQADAGAAAEQAAAFgDACQgEACgGAAQgHAAgIgEgAEEhPQAAgHAFgEQAFgEAKAAQAKACABAFQABAFgCADQAAAFADACQADACAEAAQALAAAFgJQABgFADgDQADgCAGAAQAFAAACACQACADAAAFQAAAEgBADQgGAKgJAFQgJAGgNAAQgkgBgEgbg");
	this.shape.setTransform(-32.5,-1.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.3,-11.3,69.8,19.5);


(lib.Анимация8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_03();
	this.instance.parent = this;
	this.instance.setTransform(-74.5,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-65,149,130);


(lib.Анимация7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_03();
	this.instance.parent = this;
	this.instance.setTransform(-74.5,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-65,149,130);


(lib.Анимация6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_06();
	this.instance.parent = this;
	this.instance.setTransform(-72.5,-67);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.5,-67,145,134);


(lib.Анимация5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_06();
	this.instance.parent = this;
	this.instance.setTransform(-72.5,-67);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.5,-67,145,134);


(lib.Анимация4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_11();
	this.instance.parent = this;
	this.instance.setTransform(-69,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69,-65,138,130);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_11();
	this.instance.parent = this;
	this.instance.setTransform(-69,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69,-65,138,130);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.parent = this;
	this.instance.setTransform(46.5,60,1,1,0,0,0,46.5,60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,93,120), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(91.5,79.5,1,1,0,0,0,91.5,79.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(0,0,183,159), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(91.2,75,0.814,0.814,0,0,0,67.1,52.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ12();
	this.instance_1.parent = this;
	this.instance_1.setTransform(91.5,79.5,1,1,0,0,0,91.5,79.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(0,0,183,159), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(90.6,63.2,1,1,0,0,0,41.6,38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(91.5,76,1,1,0,0,0,91.5,76);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(0,0,183,152), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ22();
	this.instance.parent = this;
	this.instance.setTransform(-172.6,224.4,2.203,2.203,0,0,0,40.4,14.3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({x:55.4},3).to({x:69.2},64).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ21();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-132.3,100.1,2.261,2.261,0,0,0,31.4,14.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(12).to({_off:false},0).to({x:50.1},3).to({x:66.2},64).wait(1));

	// Слой 1
	this.instance_2 = new lib.Анимация9("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(358.5,44.3,2.28,2.28,0,0,0,-0.1,-0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(12).to({_off:false},0).to({x:153.3},3,cjs.Ease.get(1)).to({x:139.5},64).wait(1));

	// здоровый перекус!
	this.instance_3 = new lib.Анимация11("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(385.9,162,2.149,2.149,0,0,0,0,-0.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({_off:false},0).to({x:157.9},3,cjs.Ease.get(1)).to({x:155.6},64).wait(1));

	// sssi_11.png
	this.instance_4 = new lib.Анимация3("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(74,-326);

	this.instance_5 = new lib.Анимация4("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(57.6,419.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).to({state:[{t:this.instance_4}]},8).to({state:[{t:this.instance_5}]},4).to({state:[{t:this.instance_5}]},67).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({startPosition:0},8).to({_off:true,x:57.6,y:419.8},4,cjs.Ease.get(-1)).wait(68));

	// sssi_06.png
	this.instance_6 = new lib.Анимация5("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(18.5,-287);

	this.instance_7 = new lib.Анимация6("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(-2.3,500.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6}]}).to({state:[{t:this.instance_6}]},4).to({state:[{t:this.instance_7}]},4).to({state:[{t:this.instance_7}]},71).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({startPosition:0},4).to({_off:true,x:-2.3,y:500.6},4,cjs.Ease.get(-1)).wait(72));

	// sssi_03.png
	this.instance_8 = new lib.Анимация7("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(132.5,-289);

	this.instance_9 = new lib.Анимация8("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(118.4,498.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_8}]}).to({state:[{t:this.instance_9}]},4).to({state:[{t:this.instance_9}]},75).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true,x:118.4,y:498.6},4,cjs.Ease.get(-1)).wait(76));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54,-391,261,171);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// treugolnik_zelen.png
	this.instance = new lib.Символ18();
	this.instance.parent = this;
	this.instance.setTransform(18,-59.3,1,1,0,0,0,52,58);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:6.2,y:-84.5},5).to({x:18,y:-59.3},5).wait(40));

	// treugolnik_slivki.png
	this.instance_1 = new lib.Символ19();
	this.instance_1.parent = this;
	this.instance_1.setTransform(94.5,-61.7,1,1,0,0,0,46.5,60);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({x:97.7,y:-92.7},5).to({x:94.5,y:-61.7},5).wait(35));

	// treugolnik_grib.png
	this.instance_2 = new lib.Символ16();
	this.instance_2.parent = this;
	this.instance_2.setTransform(144.5,-32.5,1,1,0,0,0,74.5,75.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({x:161.7,y:-59.8},5).to({x:144.5,y:-32.5},5).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34,-121.7,253,164.5);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(95.8,341.4,0.745,0.745,0,0,0,74.5,67);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,194.6,127.5), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ4();
	this.instance.parent = this;
	this.instance.setTransform(116.8,138.5,0.647,0.647,-5.7,0,0,126.8,84.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(0.3,5,173,110.5), null);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		setTimeout(function() {
		        _this.ban.gotoAndStop(230);
		   }, 30000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(285));

	// logo
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.setTransform(81.5,68.2,1,1,0,0,0,67.5,56.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(285));

	// Слой 8
	this.instance_1 = new lib.Символ9();
	this.instance_1.parent = this;
	this.instance_1.setTransform(87.2,29.9,1,1,0,0,0,97.2,170.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(204).to({_off:false},0).wait(76).to({alpha:0},4).wait(1));

	// Sir3ugla
	this.instance_2 = new lib.Символ5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(86.2,675.3,1,1,0,0,0,86.7,69.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).to({y:590.3},5).wait(125).to({y:690.3},5).to({_off:true},1).wait(80));

	// Слой 9
	this.instance_3 = new lib.Символ20();
	this.instance_3.parent = this;
	this.instance_3.setTransform(82.5,262.7,1,0.269,0,0,0,91.5,79.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(141).to({_off:false},0).to({scaleY:1,y:204.5,alpha:1},3).to({y:188.3},55).to({x:-17.5,alpha:0},5).to({_off:true},1).wait(80));

	// Слой 7
	this.instance_4 = new lib.Символ8();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-45,325,1,1,0,0,0,149.5,327);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(136).to({_off:false},0).to({x:67.5,alpha:1},3).wait(60).to({x:-32.5,alpha:0},5).to({_off:true},1).wait(80));

	// Слой 6
	this.instance_5 = new lib.Символ7();
	this.instance_5.parent = this;
	this.instance_5.setTransform(81.5,286.4,1,0.153,0,0,0,91.5,75.9);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(74).to({_off:false},0).to({regY:76,scaleY:1,y:222,alpha:1},5).to({y:205.8},55).to({x:169,alpha:0},7).to({_off:true},1).wait(143));

	// Слой 4
	this.instance_6 = new lib.Символ3();
	this.instance_6.parent = this;
	this.instance_6.setTransform(141,275.5,1,1,0,0,0,201.5,335.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(69).to({_off:false},0).to({x:53.5,alpha:1},5).wait(60).to({x:141,alpha:0},7).to({_off:true},1).wait(143));

	// Слой 3
	this.instance_7 = new lib.Символ11();
	this.instance_7.parent = this;
	this.instance_7.setTransform(83.5,267.1,1,0.214,0,0,0,91.5,79.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(4).to({_off:false},0).to({regY:79.5,scaleY:1,y:204.5,alpha:1},5).to({y:189.5},55).to({x:-4,alpha:0},8).to({_off:true},1).wait(212));

	// Слой 1
	this.instance_8 = new lib.Символ1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-4.5,316,1,1,0,0,0,130.5,321);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:70.5,alpha:1},4).wait(60).to({x:-17,alpha:0},8).to({_off:true},1).wait(212));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,295,284,642);
// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 24,
	color: "#0054A5",
	opacity: 1.00,
	manifest: [
		{src:"images/hohlogo.png?1479769685591", id:"hohlogo"},
		{src:"images/mal.jpg?1479769685591", id:"mal"},
		{src:"images/man1.jpg?1479769685591", id:"man1"},
		{src:"images/man2.jpg?1479769685591", id:"man2"},
		{src:"images/say_03.png?1479769685591", id:"say_03"},
		{src:"images/say_06.png?1479769685591", id:"say_06"},
		{src:"images/sssi_03.png?1479769685591", id:"sssi_03"},
		{src:"images/sssi_06.png?1479769685591", id:"sssi_06"},
		{src:"images/sssi_11.png?1479769685591", id:"sssi_11"},
		{src:"images/treugolnik_grib.png?1479769685591", id:"treugolnik_grib"},
		{src:"images/treugolnik_slivki.png?1479769685591", id:"treugolnik_slivki"},
		{src:"images/treugolnik_zelen.png?1479769685591", id:"treugolnik_zelen"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;