(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,0,703,305],[602,307,331,96],[0,307,600,168],[705,222,210,37],[719,405,109,109],[830,405,105,112],[705,0,298,220],[602,405,115,114]]}
];


// symbols:



(lib.bg = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.btn = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.eu1000 = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.logo = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.percent = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.slot = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.table = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.vip = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().rr(-109.5,-31.75,219,63.5,31.75);
	this.shape.setTransform(109.5,31.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(0,0,219,63.5), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AYBCcQgLgEgJgHQgJgGgIgIQgIgIgGgLQgGgKgEgMQgIgYAAggQAAgfAJgXQAFgMAGgLQAGgKAJgIIARgPQAJgGAMgEQALgFAKgCQAMgCAMAAQAQAAAMACIAWAFIAXAKIgKAdIgJgFIgfgJIgTgBQgTAAgQAGQgRAHgKANQgMANgFATQgHARABAXQgBAXAGASQAFASAKAOQALANAPAHQAQAHAVAAQAYAAAQgFIAXgJIAKAdIgKAEIgPAGIgzAGQgaAAgWgJgAgSCcQgLgEgJgHQgJgGgIgIQgIgIgGgLQgGgKgEgMQgIgYgBggQAAgfAKgXQAEgMAHgLQAGgKAJgIIARgPQAJgGALgEQAMgFAKgCQALgCAMAAQAQAAAMACIAWAFIAXAKIgKAdIgKgFIgegJIgTgBQgTAAgPAGQgRAHgKANQgMANgFATQgHARAAAXQAAAXAGASQAFASAKAOQALANAPAHQAPAHAVAAQAYAAAQgFIAXgJIAKAdIgKAEIgPAGIg0AGQgZAAgVgJgA5QCcQgLgEgJgHQgJgGgIgIQgIgIgGgLQgGgKgEgMQgJgYAAggQAAgfAKgXQAEgMAHgLQAHgKAHgIIASgPQAJgGAMgEQAKgFAMgCQAMgCAMAAQAPAAANACIAVAFIAXAKIgKAdIgJgFIgggJIgSgBQgUAAgQAGQgPAHgMANQgKANgHATQgFARAAAXQAAAXAEASQAGASALAOQAKANAQAHQAPAHAVAAQAYAAAQgFIAYgJIAJAdIgJAEIgRAGIgzAGQgZAAgWgJgEAhdACiIgRgDIgFgDIAHgdIAKADIAPACQALAAAIgCQAHgDAHgFQAGgFAGgHIAKgQIg4hjIgohUIApAAQALAfASAnIAqBPQAOggAOgnIAYhOIAmAAIgyCFIgfBGQgJAPgKAKQgLALgOAGQgQAGgVAAgAMnCiIgQgDIgFgDIAGgdIALADIAOACQALAAAIgCQAIgDAGgFQAHgFAFgHIAKgQIgegyIhBiFIAoAAQAMAfASAnIAqBPQAOggANgnIAYhOIAnAAIhDCsIgPAfQgIAPgLAKQgKALgPAGQgPAGgWAAgAoxCfIgEgDIAGgdIALADIANACQAMAAAHgCQAIgDAHgFQAGgFAFgHIAKgQIg4hjIgmhUIAnAAQAMAfATAnIApBPQAOggANgnIAZhOIAmAAIgyCFIggBGQgIAPgKAKQgLALgPAGQgOAGgXAAgAdvCbIAAjxIBEgGQAVAAATAEQATADAOAHQAOAIAHANQAJAMgBATQABAUgLAMQgJAOgRAGQAMADAIAFQAJAGAGAHQAOAOAAAZQgBATgGAOQgHAOgOAKQgOAJgVAFQgWAEgeAAgAeSCDIBAgBQAOgCAKgFQALgFAHgJQAFgJABgOQAAgMgFgIQgFgJgIgFQgKgFgMgCQgMgCgPAAIgtAAgAeSg9IAABMIA9gCQAMgCAIgEQAIgFAGgHQAEgHAAgMQAAgLgEgHQgGgHgJgFQgJgEgLgCQgMgDgOAAgEAnQACfIAAjCIgvA6IhaCIIgeAAIAAj4IAiAAIAAC3IBniNQATgYARgSIAcAAIAAD4gAbaCfIAAjaIhOAAIAAgeIC/AAIAAAeIhOAAIAADagAV+CfIgXg/IhxAAIgXA/IgkAAIBlj4IAfAAIAxBvIAzCJgAVdBDIgvh0IguB0IBdAAgAR3CfIAAhdIg0AGQgbAAgSgHQgRgGgKgMQgKgLgDgRQgEgRAAgTIAAhIIAiAAIAABIQABAPACAKQADAMAGAHQAHAHALAEQAMADARAAIAOAAIAigFIAAh9IAiAAIAAD4gAJuCfIAAjCIgWAbIhzCnIgdAAIAAj4IAiAAIAAC3IBmiNQATgYASgSIAbAAIAAD4gAEVCfIAAhhIgpAAIgQgCIgsBIIgNAbIgkAAIAdg6IAfgsIgSgIQgJgEgHgIQgIgJgFgMQgFgNAAgQQAAgTAIgPQAHgPAOgKQAPgKAUgFQAUgFAZAAIA0AEIAPACIAAD1gADYg7QgNACgKAGQgKAFgFAJQgGAKAAAOQAAANAEAIQAFAKAIAFQARAKAiAAIAlAAIAAhdIgjgBQgOAAgMACgAiuCfIAAjCIhIBeIhBBkIgdAAIAAj4IAjAAIAAC3IBliNQAUgYARgSIAbAAIAAD4gAsBCfIAAj1QAPgDASgBIAhgCQA1AAAcAUQAcAUABAoQgBAUgHAQQgJAPgOAKQgOAJgVAEQgVAFgbAAIgbAAIAABcgAreg8IAABhIAaAAQASAAAPgDQAOgCAKgFQAKgGAFgKQAGgJAAgPQAAgOgGgJQgFgKgKgFQgKgGgMgCQgNgCgOAAgAthCfIAAjCIhIBeIhBBkIgdAAIAAj4IAiAAIAAC3IBmiNQATgYARgSIAcAAIAAD4gAzhCfIAAj1QAOgDATgBIAggCQA1AAAcAUQAdAUAAAoQAAAUgIAQQgIAPgPAKQgOAJgVAEQgUAFgbAAIgbAAIAABcgAy+g8IAABhIAaAAQASAAAOgDQAOgCALgFQAJgGAGgKQAFgJAAgPQAAgOgFgJQgGgKgJgFQgKgGgNgCQgMgCgOAAgA14CfIAAjaIhNAAIAAgeIC/AAIAAAeIhPAAIAADagA7rCfIAAjCIgvA6IhaCIIgeAAIAAj4IAiAAIAAC3IBniNQATgYARgSIAcAAIAAD4gEghJACfIAAj4ICTAAIAAAeIhwAAIAADagEgkWACfIAAj4ICYAAIAAAeIh1AAIAABJIBpAAIAAAdIhpAAIAABWIB+AAIAAAegEgnxACfIAAj1QAPgDATgBIAggCQA1AAAcAUQAdAUAAAoQAAAUgIAQQgIAPgPAKQgOAJgVAEQgUAFgbAAIgbAAIAABcgEgnNgA8IAABhIAaAAQARAAAPgDQAOgCAKgFQAKgGAGgKQAFgJAAgPQAAgOgFgJQgGgKgKgFQgJgGgNgCQgMgCgOAAgEAl5gB0QgJgDgHgGQgOgLgDgVIAZgHQAEAMAGAHQAHAHAMAAQAMAAAHgHQAHgHADgMIAZAHQgCAKgEAIQgFAIgGAGQgHAGgJADQgKADgLAAQgMAAgJgDgAkDh0QgKgDgHgGQgOgLgDgVIAZgHQADAMAHAHQAHAHAMAAQAMAAAGgHQAIgHACgMIAZAHQgBAKgEAIQgEAIgIAGQgGAGgKADQgJADgLAAQgLAAgJgDg");
	this.shape.setTransform(254.6,7.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(0,-8.7,509.1,33), null);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABYBgIgJgCIgCgBIADgPIAGACIAHABQALAAAGgFQAHgFAFgLQgNgYgLgbQgIgRgLgkIAUAAIAVA+IAKAVQAHgVAFgUIALgqIAUAAQgIAdgIAaIgTAzQgEAJgFAGQgEAHgFAEQgGAEgGACQgHACgIAAgADWA5QgJgEgHgHQgGgHgDgKQgDgKAAgMQAAgLADgKQAEgKAGgHQAGgIAKgEQAJgEAMAAIANABIAOAEIgFAQIgJgDIgLgBQgIAAgHACQgGACgEAFQgIAKAAASQAAAIACAHQACAHAEAFQAEAFAGADQAHADAJAAQAIAAAFgCIAKgDIADAQIgFACIgPADIgIAAQgQgBgHgDgAh2A5QgIgDgHgIQgGgHgEgKQgEgKAAgMQAAgLAEgLQAEgKAGgHQAHgHAIgEQAKgEAKAAQALAAAJAEQAIAEAHAHQAGAHAEAKQAEALAAALQAAAMgEAKQgEAKgGAHQgHAIgIADQgJAEgLAAQgKAAgKgEgAh4gUQgEAFgCAHQgCAHAAAIQAAAJACAHQACAGAEAGQAEAFAGACQAFADAHAAQAHAAAFgDQAFgCAFgFQAHgLABgRQgBgRgHgKQgJgKgNAAQgNAAgJAKgAjvA4QgJgFgGgJQgFgJgDgMQgCgMAAgMQABgSACgPQACgPAHgLQAGgMAMgHQAGgEAIgCIARgEIAbgEIACAQIgHACIgTACQgUACgKAKQgGAFgDAIQgDAHgBALQAGgFAJgDQAHgDAIAAQAMAAAIAEQAIADAGAHQAMAOAAAXQAAALgDAJQgDAKgGAHQgGAIgJAEQgEACgFABIgMABQgOAAgKgFgAjpgXQgHAEgEAFIgBAOQABAIABAIQABAJAEAGQADAHAGADQAFAEAJAAQAHAAAGgDQAFgDAEgFQADgFABgHQACgGAAgIIgBgMQgBgGgEgFQgDgFgGgDQgGgDgIAAQgJAAgIADgAAqA7IAAguIgvAAIAAAuIgSAAIAAhnIASAAIAAAqIAvAAIAAgqIASAAIAABng");
	this.shape.setTransform(26.5,9.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ34, new cjs.Rectangle(0,0,52.9,19.3), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACbBLQgJgEgHgHQgGgHgEgKQgEgKAAgNQAAgMAEgKQAEgJAGgHQAHgIAJgDQAJgEAKAAQALAAAJAEQAJADAGAIQAHAHADAJQAEAKAAAMQAAANgEAKQgDAKgHAHQgGAHgJAEQgJAEgLAAQgKAAgJgEgACZgDQgEAFgCAGQgCAHAAAJQAAAJACAHQACAHAEAFQAEAFAFADQAFACAHAAQAHAAAFgCQAGgDAEgFQAIgKAAgSQAAgRgIgKQgIgKgOAAQgNAAgIAKgAk1BKQgJgGgFgJQgGgJgCgMQgCgMAAgNQAAgQACgPQADgPAGgMQAHgLAMgIQAFgDAIgDIARgEIAbgEIACARIgCAAIgYADQgTADgLAJQgFAFgEAIQgDAIgBAKQAGgFAJgCQAIgDAHAAQAMAAAIADQAJAEAFAHQAMAMAAAZQAAAKgDAKQgDAJgGAIQgGAHgJAEQgEADgFABIgMABQgOAAgKgFgAkugFQgIADgEAEIAAAOQAAAJABAJQABAIAEAHQADAGAGAEQAFADAJAAQAIAAAFgCQAFgDAEgFQADgFACgHQABgHAAgHIgBgOQgBgGgEgFQgDgEgGgDQgFgDgJAAQgIAAgIAEgAEJBNIgQgDIAAhkIAQgCIAVgBQAJAAAHABQAIABAGAEQAGADAEAGQAEAFAAAJQAAAGgEAGQgEAFgGADQAIADAFAGQAFAGAAALQAAAJgDAGQgEAGgHAEQgGAEgJACQgJABgKAAQgLAAgKgBgAELA+IADABIARAAIALgBQAGAAADgCQAEgCADgEQACgDAAgFQAAgFgCgDQgCgEgEgCIgIgDIghAAgAELAPIAegBIAHgCQAEgCACgDQACgDAAgEQAAgFgDgCQgCgDgEgCIgJgCIgbAAgAgBA/QAJgCAGgGQAGgFADgIQADgHABgIIADg2IBFAAIAABnIgSAAIAAhXIghAAIgBAcIgGAcQgCAHgEAFQgDAGgFAEQgFAFgGADQgGACgJABgAh4A/QAKgCAFgGQAGgFADgIQADgHACgIIADg2IBFAAIAABnIgTAAIAAhXIghAAIgBAcIgGAcQgCAHgDAFQgEAGgEAEQgFAFgHADQgGACgJABgAjCBNQgHgCgGgEQgFgEgDgGQgDgHAAgJQAAgIADgHQAEgGAGgEQAGgDAIgCQAIgCAJAAIAFAAIAOADIAAgGIgBgJQgBgDgDgEQgDgDgEgCQgFgCgHAAIgQABIgKADIgCgQIAMgDQAIgBAKAAQALAAAIADQAHACAFAGQAFAFACAHQACAHAAAIIAABBIgHACIgiACQgJAAgHgBgAi+AfQgEACgDADQgCAEAAAFQAAAFABADQACAEADACQAGAEALAAIAMAAIAJgCIAAgfIgHgBIgUAAQgEAAgEACg");
	this.shape.setTransform(33.4,7.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(0,0,66.9,15.8), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkpBLQgJgEgHgIQgGgHgDgKQgEgKAAgMQAAgMAEgKQADgJAHgHQAGgHAKgEQAJgEALAAIAOABIAOAEIgFAPIgJgDIgMgBQgIAAgGACQgGADgEAFQgIAJAAASQAAAJACAHQACAHAEAFQAEAFAGADQAHACAJAAQAHAAAGgBIAKgDIACAPIgEACIgPADIgJABQgPgCgHgCgAmNBOIgLgDQgKgFgGgHQgHgHgDgKQgDgKAAgMIABgMIADgMQAEgJAHgHQAGgHAJgDQAIgDAJAAQALAAAIADQAIADAGAHQALANAAAaIAAAGIhIAAQABAIACAHQADAGAEAEQAIAIARAAQAKAAAHgBIAKgEIADAQQgEACgIACQgJACgLAAgAmRgLQgFACgDAEQgEAEgCAFQgCAFAAAFIAzAAQABgMgHgHQgGgJgMAAQgGAAgFADgAoRBKQgJgGgGgJQgFgJgDgMQgCgMAAgNQAAgQADgPQACgPAHgMQAGgLAMgIQAGgDAHgDIARgEIAcgEIACARIgaADQgUADgKAJQgGAFgDAIQgDAIgBAKQAGgFAIgCQAIgDAIAAQALAAAJADQAIAEAGAHQALAMAAAZQAAAKgCAKQgDAJgGAIQgGAHgJAEQgFADgFABIgLABQgPAAgJgFgAoLgFQgHADgEAEIgBAOQAAAJACAJQABAIADAHQAEAGAFAEQAGADAJAAQAHAAAGgCQAFgDADgFQAEgFABgHQACgHAAgHIgBgOQgCgGgDgFQgDgEgGgDQgGgDgIAAQgJAAgIAEgAFTBNIgSgDIAAhlIASAAIAAAnIAKgCIANAAQAIAAAHACQAIABAFAFQAGAEADAGQAEAHAAAJQAAAJgEAHQgDAGgGAEQgFAFgJACQgIABgKAAgAFTAaIAAAkIAEABIAPAAIALgBIAIgDQAHgFAAgKQAAgFgCgEQgCgDgEgDIgIgDIgJgBgAAYBNQgHgCgGgEQgFgEgDgGQgDgHAAgJQAAgIADgHQAEgGAGgEQAGgDAIgCQAIgCAJAAIAFAAIAOADIAAgGIgBgJQgBgDgDgEQgDgDgEgCQgFgCgHAAIgQABIgKADIgCgQIAMgDQAIgBAKAAQALAAAIADQAHACAFAGQAFAFACAHQACAHAAAIIAABBIgHACIgiACQgJAAgHgBgAAcAfQgEACgDADQgCAEAAAFQAAAFABADQACAEADACQAGAEALAAIAMAAIAJgCIAAgfIgHgBIgUAAQgEAAgEACgAh9A/QAKgCAGgGQAGgFADgIQADgHABgIIADg2IBFAAIAABnIgSAAIAAhXIghAAIgBAcIgGAcQgCAHgEAFQgDAGgFAEQgFAFgGADQgGACgJABgAIWBMIgcgrIgbArIgUAAQAHgNAKgOIATgbIgigxIAVAAIAZAkIAZgkIAUAAIgiAvIAUAcQAKAOAHAOgAGmBMIAAhnIASAAIAABngAEOBMIAAguIgwAAIAAAuIgSAAIAAhnIASAAIAAAqIAwAAIAAgqIATAAIAABngACEBMIAAhXIgiAAIAAgQIBXAAIAAAQIgiAAIAABXgAiiBMIAAhXIguAAIAABXIgTAAIAAhnIBUAAIAABng");
	this.shape.setTransform(55.5,7.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(0,0,111,15.8), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FA1313").s().p("AE+BtQgKgEgHgIQgPgQAAgdQAAgdAPgQQAPgOAZAAQAZAAAPAOQAOAQAAAdQAAAdgOAQQgIAIgKAEQgKAEgMAAQgNAAgKgEgAFGAeQgFAGAAAQQAAAQAFAIQAGAGAJABQAIgBAGgGQAFgIAAgQQAAgQgFgGQgGgIgIABQgJgBgGAIgAABBoQgNgGgKgPQgKgPgGgUQgFgVAAgbQAAgbAGgUIAGgUQAEgIAFgHQAGgIAGgEQAGgGAGgEQAHgEAIgCQAIgCAJAAQASABAOAHQAOAHALAOQAKAPAFAVQAFAUAAAbQAAA2gUAdQgLAPgOAGQgOAIgSAAQgSAAgPgIgAAThDQgFAGgEAKQgEAJgBANIAAA6QABANAEAKQAEAJAFAGQAGAFAJAAQAIAAAGgFQAGgGAEgJQADgKACgNIAAg6QgCgNgDgJQgEgKgGgGQgGgEgIgBQgJABgGAEgAiuBoQgOgGgKgPQgKgPgGgUQgFgVAAgbQAAgbAGgUIAGgUQAEgIAFgHQAGgIAGgEQAGgGAHgEQAHgEAIgCQAIgCAJAAQASABAOAHQAOAHALAOQAKAPAFAVQAFAUAAAbQAAA2gUAdQgLAPgOAGQgOAIgSAAQgSAAgPgIgAichDQgFAGgEAKQgEAJgBANIAAA6QABANAEAKQAEAJAFAGQAGAFAJAAQAIAAAGgFQAGgGAEgJQADgKACgNIAAg6QgCgNgDgJQgEgKgGgGQgGgEgIgBQgJABgGAEgAC2BrIB5jVIArAAIh5DVgAmEBrIgBgPQAAgPAFgNQAFgNAIgKQAHgKAKgKIAtgrQAFgHADgFQACgHAAgGQAAgNgHgGQgIgGgMAAQgIAAgHADIgOAGIgQANIgXggQANgNASgIQAKgEAJgCQAKgCAKgBQATABAOAEQAOAEAIAJQAJAHAEALQAFAMAAAOQAAAMgFAKQgFALgHALQgIAJgJAJIgnAmIgJALIgEAIIBcAAIAAAmgAClAEQgKgEgIgGQgOgQAAgdQAAgeAOgPQAPgQAZAAQAaAAAOAQQAPAPAAAeQAAAdgPAQQgHAGgKAEQgKAEgNAAQgMAAgKgEgACthKQgFAHAAAQQAAAPAFAIQAGAHAIAAQAJAAAGgHQAFgIAAgPQAAgQgFgHQgGgHgJAAQgIAAgGAHg");
	this.shape.setTransform(39.5,11.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(0,0,79.1,22.5), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FA1313").s().p("AieBpQgOgHgLgPQgKgOgFgVQgFgVAAgbQAAgaAFgVIAHgTQAEgJAFgHQAFgHAGgFQAGgGAHgEQAIgDAIgCQAHgCAJAAQASAAAPAHQAOAHAKAPQALAOAFAVQAFAVAAAaQAAA2gVAdQgKAPgOAHQgPAHgSAAQgSAAgOgHgAiMhCQgGAFgDAKQgEAJgCAOIAAA5QACAOAEAJQADAKAGAFQAGAFAIAAQAJAAAGgFQAGgFADgKQAEgJABgOIAAg5QgBgOgEgJQgDgKgGgFQgGgFgJAAQgIAAgGAFgAlOBpQgOgHgLgPQgKgOgFgVQgFgVAAgbQAAgaAFgVIAHgTQAEgJAFgHQAFgHAGgFQAGgGAHgEQAIgDAIgCQAHgCAJAAQASAAAPAHQAOAHAKAPQALAOAFAVQAFAVAAAaQAAA2gVAdQgKAPgOAHQgPAHgSAAQgSAAgOgHgAk8hCQgGAFgDAKQgEAJgCAOIAAA5QACAOAEAJQADAKAGAFQAGAFAIAAQAJAAAGgFQAGgFADgKQAEgJABgOIAAg5QgBgOgEgJQgDgKgGgFQgGgFgJAAQgIAAgGAFgAF9BsIAAjTQAQgDASgBIAfgCQAwAAAZARQAaARAAAnQAAATgHAOQgGANgNAJQgaARgwAAIgQAAIAABIgAGthCIAAA+IAQAAQAMAAAKgCQAJgCAGgDQAHgEADgGQADgGAAgKQAAgJgDgGQgDgFgGgEQgGgEgJgBIgTgBgAEcBsIAAjWIAwAAIAADWgAB8BsIgZg4Ig9ieIA2AAIA4CdIA5idIAzAAIglBlIgxBxgAnnBsIAAiaQgJAGgMAFIgWAJIgOgjIAmgTIASgNIAPgNIAgAAIAADWg");
	this.shape.setTransform(54.5,11.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ30, new cjs.Rectangle(0,0,109.1,22.5), null);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FA1313").s().p("AE+BuQgLgBgJgEQgUgHgOgOQgIgHgFgJQgGgJgEgKQgFgLgCgMQgCgMAAgOQAAgaAJgVQAJgVAOgPQAPgOATgHIAUgFQAKgCALAAQAWAAAUAHQAKAEAIAFQAJAFAHAHQAOAPAJAVQAIAVAAAaQAAAOgCAMQgCAMgEALQgIAVgPAOQgOAOgTAHQgUAHgXAAQgLAAgKgCgAE7hAQgKAGgIAJQgHAJgEANQgEANAAAOQAAAQAEANQAEAMAHAKQAIAJAKAFQALAFANAAQAOAAAKgFQALgFAHgJQAIgKADgMQAEgNAAgQQAAgPgEgMQgDgNgIgKQgHgJgLgFQgKgFgOAAQgNAAgLAFgApzBTQgcgdAAg2QAAgaAJgUQAEgLAGgJQAFgJAIgHQAOgOAUgIQAUgHAYAAQAOAAALACIATAFIAWAJIgOAoQgKgGgNgEQgNgDgRAAQgLAAgKADQgLAEgIAIQgJAJgFANQgFANAAASQAAAOAEANQADANAHAJQAHAJAMAGQAMAFARAAIATgBIAPgDIAUgIIANAnQgKAGgSAFQgbAFgQAAQg1AAgbgdgAIKBtQgRgBgTgEIAAjPIBBgGQAVAAARADQARADANAHQAMAIAHALQAEAGABAHQACAHAAAJQAAANgGAKQgGAKgNAIQAVAHAHANQAIANAAARQAAAhgZASQgMAIgTAEQgSAEgYAAgAIVBGIAZABIAUgCQAJgBAGgDQAHgDADgGQAEgGAAgIQAAgPgLgHQgGgDgIgBIgxgCgAIVhFIAAAvIArgBQAIgCAFgCQAEgDADgFQACgFAAgGQAAgGgCgFQgDgFgFgCQgKgGgTAAgACQBsIAAhbIhSAAIAABbIgwAAIAAjWIAwAAIAABSIBSAAIAAhSIAwAAIAADWgAhSBsIAAiMQgbAggYAjQgfAwgOAZIgpAAIAAjWIAwAAIAAB+IAYgiIBJhcIAoAAIAADWgAk9BsIAAitIhQAAIAACtIgwAAIAAjWICxAAIAADWg");
	this.shape.setTransform(65.6,11.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ29, new cjs.Rectangle(0,0,131.2,22.5), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FA1313").s().p("AhaFRIhngUIgggMIAah2IA/AVQAoAKA3AAQAgAAAXgHQAYgHAQgNQAdgaAAgkQAAgbgMgWQgNgVgfgPQgdgPg1gHQgzgIhPAAIASi0IAKitIFnAAIAAB4IjvAAIgKB7QCMAJBCA5QBDA3AABkQAAAugQAnQgRAnggAdQggAdgyAQQhIARgrAAg");
	this.shape.setTransform(22.6,34);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ28, new cjs.Rectangle(0,0,45.2,68), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.vip();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(0,0,115,114), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.percent();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(0,0,109,109), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.slot();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(0,0,105,112), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FA1313").s().p("EApnAIUIAAixInPAAIAACxIiQAAIAAkwIBgAAQAkg9AUg9QAUg8AKg+QAKg+ADhCIACilIG4AAIAAIZIBxAAIAAEwgEAlTgBMIgOBrQgKA1gPAyQgQAzgYArIDuAAIAAmbIiYAAgAY4FrQgggGgegLQg9gWgtgsQgXgVgSgcQgSgbgMggQgNgggHgmQgGgmAAgrQAAhUAbhBQAahAAugtQAugsA8gWQAegLAfgFQAggGAhAAQBEAAA8AWQAfALAaARQAbAQAWAWQAtAtAaBAQAaBBAABUQAAArgGAmQgHAmgMAgQgaBBgsArQgsAsg9AWQg9AWhGAAQgiAAgggFgAYviyQggAQgXAdQgXAcgMAoQgMAoAAAuQAAAyAMAnQAMAnAXAdQAXAcAgAPQAhAQAqAAQApAAAigQQAggPAXgcQAXgdAMgnQAMgnAAgyQAAgvgMgoQgMgogXgdQgXgcgggPQgigPgpAAQgqAAghAPgEgi/AFqQgkgGgegMIAbh4QAvARAvAAQAeAAAbgNQAcgNAZgsIhMh/IhEh/IhtjiICmAAICfFbIA7isIA2ivICgAAIhgEEIhaDRQgcA/gfApQgfApggAXQghAXghAIQgiAJgiAAQghAAgjgGgEgwMADuQBFgIAlgcQATgNAOgVQAPgVAJgcQAQgvASiFQAHhKADiuIHGAAIAAKYIiVAAIAAoaIikAAIgHCCQgEA/gLA9QgLA8gVA1QgUA1gkAoQgTAUgWAQQgWAQgbAMQgbAMghAHQghAHgnABgEg3cAFrQgggGgegLQg9gWgtgsQgXgVgSgcQgSgbgMggQgNgggHgmQgGgmAAgrQAAhUAbhBQAahAAugtQAugsA8gWQAegLAfgFQAggGAhAAQBEAAA8AWQAfALAaARQAbAQAWAWQAtAtAaBAQAaBBAABUQAAArgGAmQgHAmgMAgQgaBBgsArQgsAsg9AWQg9AWhGAAQgiAAgggFgEg3lgCyQggAQgXAdQgXAcgMAoQgMAoAAAuQAAAyAMAnQAMAnAXAdQAXAcAgAPQAhAQAqAAQApAAAigQQAggPAXgcQAXgdAMgnQAMgnAAgyQAAgvgMgoQgMgogXgdQgXgcgggPQgigPgpAAQgqAAghAPgEBStAFjIAAmzQhUBihLBvQhgCWgrBMIh+AAIAAqYICVAAIAAGHIBKhrICdjPIBGhNIB6AAIAAKYgEBH9AFjIgwhHIg7hLIhChKQgjgjgjgbIAAEaIiVAAIAAqYICVAAIAAD5IDkj5ICyAAIiJCbIiRCWQA1AsBlBxQAyA9BdCNgEA4LAFjIAAqPQAwgJA3gEIBggEQCVAABQA0QBPA1AAB3QAAA8gUAqQgUArgoAbQhRA1iVAAIgwAAIAADfgEA6ggC7IAAC/IAwAAQAmAAAdgEQAegFAUgLQATgKAKgUQAKgUAAgdQAAgbgKgTQgLgSgSgLQgTgLgbgEIg7gEgEA0VAFjIgxiQIkEAAIgxCQIicAAICJlyICBkmICOAAIBBCNIBACZICJFygEAzAABcIhfj7IhfD7IC+AAgAQdFjIAAoaIj4AAIAAIaIiWAAIAAqYIIjAAIAAKYgAB8FjIAAmzQhVBihKBvQhgCWgrBMIh9AAIAAqYICUAAIAAGHIBKhrICdjPIBGhNIB6AAIAAKYgAohFjIgxiQIkEAAIgxCQIicAAICJlyICBkmICOAAIBBCNIBACZICJFygAp2BcIhfj7IhfD7IC+AAgA0PFjIAAjfIh6AIQg8AAgxgLQgygLgigdQgRgOgOgTQgNgTgKgXQgSgvAAhJIAAjLICVAAIAADEQAAAnAKAYQAJAZASAOQASANAZAGQAZAFAeAAIBngHIAAk7ICWAAIAAKYgEg/3AFjIAAoaIj4AAIAAIaIiWAAIAAqYIIjAAIAAKYgEhOYAFjIAAmzQhVBihLBvQhgCWgrBMIh9AAIAAqYICUAAIAAGHIBKhrICejPIBGhNIB6AAIAAKYgAg9l5QgcgJgXgSQgXgSgPgZQgPgagDggIBjgaQAIAkASAPQARAQAYAAQAYAAASgOQASgOAHgmIBiAaQgDAggPAaQgPAZgWARQgXASgcAJQgdAJgeAAQgfAAgcgJg");
	this.shape.setTransform(544.1,53.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(0,0,1088.3,106.5), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EAiHAIJIAAiyInlAAIAACyIhZAAIAAkBIBHAAQAYgcATgfQATgfANgiQARgtAVhhQAMhLADhRIADijIF4AAIAAJJIBUAAIAAEBgAdohwQgEBBgLBAQgKBBgVA/QgWA+gmA5IEwAAIAAn5IjAAAgEhVOAIJIAAiyInlAAIAACyIhYAAIAAkBIBGAAQAYgcATgfQATgfAOgiQARgtAVhhQAMhLADhRIADijIF4AAIAAJJIBUAAIAAEBgEhZtgBwQgDBBgLBAQgLBBgVA/QgVA+gmA5IEvAAIAAn5IjAAAgEBE/AFgIg7gMIgtgQIgegOIAchNIBFAcIAwALIA4AFQBTAAAtgbQAXgOALgXQALgXAAghQAAgmgPgZQgQgYgcgPQgagOglgFQgmgGgrAAIg8AAIAAhKIBzgFQAhgFAbgNQAagNARgWQASgWAAgiQAAgVgKgSQgIgRgTgPQglgbg+AAQg0AAgqAMQgrAMgUANIgdhMIAegPIAsgNIA2gJIA8gDQAxAAArAKQAqALAfAVQAeAWASAhQARAhAAAtQAAAugdApQgPAUgVAOQgWAPgcAJQAcAIAbANQAbAOATAVQAUAWALAdQAMAdAAAmQAAA1gTAmQgUAlgjAYQgjAZgxALQgzALg8AAgEA6vAFQQg6gWgrgsQgtgsgZhBQgZhBAAhWQAAhUAZhBQAZhCAtgsQArgrA6gWQA6gWBCAAQA/AAA6AWQAcALAZAQQAZARAWAVQArAsAaBCQAMAgAHAmQAGAlABAqQgBArgGAmQgHAlgMAhQgaBBgrAsQgWAWgZAQQgZARgcALQg6AWg/AAQhCAAg6gWgEA7MgDsQgoATgcAiQgdAjgPAxQgPAyAAA7QAAA8APAyQAPAxAdAjQAcAjAoASQAqATAyAAQAzAAApgTQAogSAcgjQAcgjAQgxQAQgyAAg8QAAg7gQgyQgQgxgcgjQgcgigogTQgpgTgzAAQgyAAgqATgEhK0AEQQBDgHAlgjQATgSAPgaQAPgaAMgkQAOgoAIgxQAJgvADg5QAIhygBiKIF6AAIAAKYIhdAAIAApIIjBAAIgKDKIgLBbQgIAugOArQgNArgTAmQgVAmgdAcQgdAdgoARQgoARg2ACgAAWFbQgugEgogJIAAqPIBcAAIAADyIBKgDQEnAAAADZIgEAyQgFAYgLAUQgTAogmAbQglAbg2AOQg2ANhDAAgAAcAAIAAEJIBXADQAkAAAigFQAhgGAagPQAZgQAQgZQAPgaAAgoQAAgogPgbQgOgbgbgQQgbgPglgGQglgFgsAAgApQFZIhZgNIAAqEICIgPIAqgBQA7AAAxAJQAzAIAlAVQAlAVAVAhQAWAiAAAxQgBA3gaAjQgZAjgsARQAdAJAXAMQAYAOASATQAhAlAABEQABAygTAmQgSAlglAaQgkAZg6AMQg7ANhQAAgApMELIA2AEIB1gFQAlgFAcgOQAbgNARgYQARgYAAglQAAgggNgXQgNgXgXgNQgXgNghgGQghgGgoAAIh3AAgApMj2IAADNIBiAAIBBgEQAegFAXgNQAWgMANgUQANgVAAgfQAAgcgNgUQgOgTgXgNQgYgLgggGQgfgGgkAAgEBZdAFXIAApHIjRAAIAAhRIIAAAIAABRIjRAAIAAJHgEBTPAFXIAAoGIh7CdIiGC+IhrCrIhOAAIAAqYIBbAAIAAHrIBLhzIBfiFIBmiDQA0hAAtgwIBKAAIAAKYgEA0DAFXIAApIIk/AAIAAJIIhdAAIAAqYIH6AAIAAKYgEAlDAFXIAAqYIGWAAIAABQIk5AAIAADGIEWAAIAABMIkWAAIAADnIFRAAIAABPgASvFXIAAoGIh7CdIiGC+IhrCrIhPAAIAAqYIBcAAIAAHrIBLhzIBfiFIBmiDQA0hAAsgwIBLAAIAAKYgAHzFXIAAqYIBdAAIAAKYgAzwFXIAAqPQAngJAwgDIBZgEQCMAABMA2QBLA1ABBpQgBA6gVApQgVAogmAZQgnAZg4AMQg4AMhGAAIhJAAIAAD2gAyTjzIAAEEIBGAAQAwAAAmgHQAmgGAbgOQAbgOAOgaQAPgaAAgpQgBgmgPgZQgOgZgagPQgagPghgFQgigGgmAAgA8UFXIAAqYIGWAAIAABQIk5AAIAADGIEWAAIAABMIkWAAIAADnIFRAAIAABPgEggXAFXIAApIIk/AAIAAJIIheAAIAAqYIH6AAIAAKYgEguRAFXIAAoGIh8CdIiFC+IhrCrIhOAAIAAqYIBbAAIAAHrIBLhzIBfiFIBmiDQA0hAAsgwIBKAAIAAKYgEg4LAFXIg9ipIktAAIg8CpIhiAAICKlsIBAibIBDiRIBVAAIBCCRICCFEIBIDDgEg5jABhIg8ihIg/iWIhACWIg8ChID3AAgEhSSAFXIAAqYIGWAAIAABQIk5AAIAADGIEWAAIAABMIkWAAIAADnIFSAAIAABPgAPKmJQgZgIgTgPQgmgfgIg2IBFgTQAHAfATATQASATAfAAQAgAAATgTQARgTAIgfIBDATQgDAbgMAVQgLAVgTAQQgTAPgYAIQgZAIgeAAQgeAAgYgIgEgx2gGJQgZgIgTgPQgmgfgHg2IBDgTQAIAfASATQATATAgAAQAfAAASgTQATgTAHgfIBEATQgFAbgLAVQgLAVgTAQQgSAPgZAIQgYAIgeAAQgfAAgYgIg");
	this.shape.setTransform(602.8,52.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(0,0,1205.6,104.2), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.eu1000();
	this.instance.parent = this;
	this.instance.setTransform(0,-10,0.43,0.43);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,-10,257.7,72.2), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AByBXIAAgjIhcAAIAAAjIgbAAIAAg8IASAAQAHgMAEgMQAEgLACgMQACgMAAgNIABghIBWAAIAABpIAXAAIAAA8gAA4gLQgBALgEAJQgDAKgEAIIAvAAIAAhQIgeAAgADPA2IgMgDQgMgFgJgIIgIgKQgDgFgDgHIgEgOIgBgOQAAgRAGgNQAFgNAJgIQAJgJAMgEIAMgEIAMgBQAOAAAMAFIALAFIAKAIQAIAIAGANQAFANAAARQAAAIgCAGQgBAIgCAGQgFANgJAJQgJAIgMAFQgMAEgOAAIgNgBgADOg0QgHADgEAGQgFAFgCAIQgCAIAAAKQAAAJACAHQACAIAFAFQAEAGAHADQAGADAIAAQAJAAAGgDQAHgDAEgGQAFgFACgIQACgHAAgJQAAgKgCgIQgCgIgFgFQgEgGgHgDQgGgDgJAAQgIAAgGADgAjrA2IgMgDQgMgFgJgIIgIgKQgEgFgCgHIgEgOIgBgOQAAgRAFgNQAFgNAJgIQAJgJAMgEIAMgEIANgBQANAAAMAFIALAFIAKAIQAJAIAFANQAFANAAARQAAAIgBAGQgBAIgDAGQgFANgJAJQgIAIgMAFQgMAEgOAAIgNgBgAjtg0QgGADgFAGQgEAFgCAIQgDAIAAAKQAAAJADAHQACAIAEAFQAFAGAGADQAHADAIAAQAIAAAHgDQAGgDAFgGQAEgFACgIQADgHAAgJQAAgKgDgIQgCgIgEgFQgFgGgGgDQgHgDgIAAQgIAAgHADgAGpA0IgCgpIgCgtIgfBGIgUAAIgehGIgFBWIgcAAIAKiCIAcAAIAkBOIAjhOIAbAAIALCCgAg1A0IAAg2IgyAAIAAA2IgdAAIAAiCIAdAAIAAAyIAyAAIAAgyIAdAAIAACCgAmJA0IAAgPQgQgBgLgFQgLgEgHgIQgHgHgEgKQgEgIAAgKQAAgKAEgJQAEgKAHgIQAHgHALgFQALgFAQgCIAAgOIAcAAIAAAOQAPACAMAFQALAFAHAHQAHAIAEAKQAEAJAAAKQAAAKgEAIQgEAKgHAHQgHAIgLAEQgMAFgPABIAAAPgAltAMQAIAAAGgDQAFgCAEgEQADgDACgFQACgGAAgGQAAgFgCgGQgBgFgEgEQgEgEgFgDQgGgCgIgBgAmXgsQgFADgEAEQgEAEgBAFQgCAGAAAFQAAAGACAGQACAFADADQAEAEAGACQAFADAIAAIAAg7QgIABgGACg");
	this.shape.setTransform(45.4,8.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,90.8,17.5), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABfBDIgMgDQgMgEgJgJIgIgKQgEgFgCgGIgEgOIgBgQQAAgQAFgMQAFgNAJgJQAJgJAMgEIAMgDIANgBQANAAAMAEIALAFIAKAIQAJAJAFANQAFAMAAAQQAAAJgBAHQgBAHgDAHQgFAMgJAJQgIAJgMAEQgMAEgOAAIgNgBgABdgmQgGADgFAFQgEAGgCAIQgDAIAAAIQAAAKADAIQACAHAEAGQAFAFAGADQAHADAIAAQAIAAAHgDQAGgDAFgFQAEgGACgHQADgIAAgKQAAgIgDgIQgCgIgEgGQgFgFgGgDQgHgDgIAAQgIAAgHADgAg4BBIgVgHIAJgXIAZAHIAKABQANAAAHgDQAIgEAAgJQAAgFgCgEQgDgDgEgCQgEgCgGAAIgegBIAAgXIAdgBIAIgDQADgCACgDQACgDAAgEQAAgHgFgDQgFgDgKAAQgKAAgIACQgIADgHAEIgJgYQAIgEAKgDQALgDAOAAQAKAAAJACQAJADAGAEQAHAFADAHQAEAHAAAKQAAAHgEAHQgEAHgIAFIAIAEIAHAHQADAEACAFQACAFAAAGQAAALgEAHQgEAIgHAFQgOAJgbAAgApyAzQgQgSAAghQAAgPAFgNIAGgMQADgFAFgEQAJgJAMgFQAMgEAPAAIAPABIAMADIANAGIgIAYQgGgEgIgCQgJgCgKAAQgHAAgGACQgHACgFAFQgFAFgDAIQgDAIAAALQAAAJACAHQACAIAFAGQAEAGAHADQAIADAKAAIALAAIAJgCIANgFIAIAYQgGADgMADQgQADgKAAQggAAgRgRgAFZBCIgVgDIAAh/IAeAAIAAArIAIAAQAPAAAMADQALACAIAGQAIAFAEAIQADAIAAAMQAAALgEAIQgEAIgIAGQgIAGgLADQgLACgOAAgAFiADIAAAnIAWAAQAFgBAEgDQAEgCACgEQACgDAAgGQAAgMgIgEIgLgDIgOgBIgDAAgADcBDQgLgBgMgCIAAh+IAogEQANAAAKACQALACAHAEQAIAFAEAHIADAHIABAKQAAAIgDAGQgEAGgIAFQANAEAEAIQAFAIAAAKQAAAVgPAKQgIAFgLADQgLACgPAAgADiAqIAHABIAUgBIAKgDQAEgBACgEQACgDAAgGQAAgJgHgEIgIgCIgegBgADigpIAAAcIAagBIAIgCIAEgFQACgDAAgEQAAgEgCgCQgBgDgDgCQgGgDgMAAgAJmBCIgBgqIgDgsIgeBFIgVAAIgehFIgEBWIgdAAIALiCIAcAAIAjBNIAkhNIAbAAIAKCCgAG4BCIAAiCIAdAAIAACCgAh+BCIAAhVQgQATgPAVIgbAtIgZAAIAAiCIAdAAIAABMIA8hMIAYAAIAACCgAlLBCIAAiAIAVgDIATgBQAdAAAQALQAPAKAAAXQAAAMgEAJQgEAHgHAFQgQALgeAAIgJAAIAAAsgAktgoIAAAmIAJAAIAOgBIAJgDQAEgCACgEQACgEAAgGQAAgFgCgEQgCgEgEgCQgDgCgGgBIgLgBgAmGBCIAAhpIgxAAIAABpIgeAAIAAiCIBsAAIAACCg");
	this.shape.setTransform(64.3,6.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,128.7,13.7), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAtQANgBAHgFQAEgDADgEQADgEACgGQADgJADgZQACgPAAgjIBaAAIAACCIgeAAIAAhpIggAAIgBAaIgDAYQgCAMgEAKQgFAKgHAIIgIAHIgJAGIgMADQgHACgHAAgAB5AtQANgBAHgFQAEgDADgEQADgEACgGQADgJADgZQACgPAAgjIBaAAIAACCIgeAAIAAhpIggAAIgBAaIgDAYQgCAMgEAKQgFAKgHAIIgIAHIgJAGIgMADQgHACgHAAgAAdBGIgMgDQgMgEgIgJIgIgKQgEgFgCgHIgEgOIgBgPQAAgQAFgNQAFgNAJgIQAIgJAMgEIAMgEIANgBQANABAMAEIALAFIAKAIQAJAIAFANQAFANAAAQQAAAJgBAGQgBAIgDAGQgFANgJAJQgIAJgMAEQgMAEgOAAIgNgBgAAbgkQgGAEgFAFQgEAFgCAJQgDAIAAAIQAAAJADAJQACAHAEAFQAFAGAGADQAHADAIAAQAIAAAHgDQAGgDAFgGQAEgFACgHQADgJAAgJQAAgIgDgIQgCgJgEgFQgFgFgGgEQgHgDgIAAQgIAAgHADgAHCBFIgUgDIAAiAIAdAAIAAAsIAIAAQAQAAALADQAMACAHAGQAIAFAEAIQAEAIAAALQAAALgEAJQgFAIgHAGQgIAGgLADQgMACgOAAgAHLAGIAAAnIAXgBQAFAAADgDQAEgCADgEQACgDAAgHQAAgLgJgEIgKgEIgPAAIgCAAgAIhBEIAAiCIAeAAIAACCgAiKBEIAAh/IAUgEIATAAQAdAAAQAKQAQAKAAAYQAAAMgEAHQgEAJgIAFQgQAKgdAAIgKAAIAAAsgAhtgmIAAAmIAKAAIANgBIAKgCQAEgCACgFQACgEAAgFQAAgGgDgEQgCgDgDgCQgEgCgFgBIgMgBgAjGBEIAAhVQgQATgPAWIgbAsIgZAAIAAiCIAdAAIAABNIA8hNIAYAAIAACCgAmTBEIAAh/IAVgEIATAAQAdAAAQAKQAPAKAAAYQAAAMgEAHQgEAJgHAFQgQAKgeAAIgJAAIAAAsgAl1gmIAAAmIAJAAIAOgBIAJgCQAEgCACgFQACgEAAgFQAAgGgCgEQgCgDgEgCQgDgCgGgBIgLgBgAoCBEIAAgPQgQgBgLgEQgLgFgHgIQgHgHgEgKQgEgJAAgJQAAgKAEgJQAEgJAHgJQAHgHALgFQALgFAQgCIAAgOIAcAAIAAAOQAPACAMAFQALAFAHAHQAHAJAEAJQAEAJAAAKQAAAJgEAJQgEAKgHAHQgHAIgLAFQgMAEgPABIAAAPgAnmAdQAIgBAGgDQAFgCAEgEQADgEACgFQACgFAAgGQAAgFgCgGQgBgEgEgFQgEgEgFgDQgGgCgIAAgAoQgcQgFADgEAEQgEAFgBAEQgCAGAAAFQAAAGACAFQACAFADAEQAEAEAGACQAFADAIABIAAg7QgIAAgGACg");
	this.shape.setTransform(57.5,7.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,115,14.2), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AvEB/IgQgDIgFgCIAGgeIALAEIAOACQALgBAIgCQAIgDAGgFQAHgFAFgGIAKgQIgegzIhBiFIAoAAQAMAfASAnIAqBQQAOggANgoIAYhOIAnAAIhDCsIgPAfQgIAPgLALQgKALgPAGQgPAFgWAAgASJB8IgXg/IhwAAIgYA/IgkAAIBlj4IAgAAIBJCvIAbBJgARoAgIguh0IguB0IBcAAgAOCB8IAAhzIh6AAIAABzIgjAAIAAj4IAjAAIAABoIB6AAIAAhoIAjAAIAAD4gAJEB8IhChqIhDBqIgnAAQAQgfAWghIAthDIhQh1IApAAIA+BdIA8hdIAoAAIhPB0IAvBEQAVAhARAfgAFnB8IgXg/IhwAAIgYA/IgkAAIBlj4IAgAAIBKCvIAaBJgAFHAgIgvh0IguB0IBdAAgAgZB8IAAj0QAPgEARgBIAhgCQA1ABAcATQAcAVAAAnQAAAWgIAPQgHAPgPAJQgPAKgUADQgVAFgaAAIgcAAIAABcgAAJhfIAABhIAaAAQASAAAOgCQAPgCAKgFQAKgGAFgJQAGgKgBgPQABgPgGgJQgFgKgKgFQgJgFgOgCQgMgDgOAAgAh5B8IAAjCIhIBeIhBBkIgdAAIAAj4IAiAAIAAC4IBmiOQAUgYARgSIAbAAIAAD4gAmAB8IAAhzIh6AAIAABzIgiAAIAAj4IAiAAIAABoIB6AAIAAhoIAkAAIAAD4gAr3B8IAAj0QAPgEASgBIAhgCQA1ABAcATQAcAVABAnQgBAWgHAPQgJAPgOAJQgOAKgVADQgVAFgbAAIgbAAIAABcgArUhfIAABhIAaAAQASAAAPgCQAOgCAKgFQAKgGAFgJQAGgKAAgPQAAgPgGgJQgFgKgKgFQgKgFgMgCQgNgDgOAAgAxgB8IAAjZIhOAAIAAgfIDAAAIAAAfIhPAAIAADZg");
	this.shape.setTransform(119.9,12.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(0,0,239.8,25.5), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhKB8IgQgDIAAjxIBDgGQAWAAARAEQAUACANAIQAOAIAIAMQAIANAAATQAAAUgKANQgKAOgQAGQALADAJAEQAIAGAHAGQANAOAAAaQAAASgHAOQgGAPgOAKQgOAJgWAEQgWAFgcAAgAg4BgIA/AAQAOgCALgFQAKgFAHgJQAGgJAAgOQAAgMgFgJQgEgIgJgFQgJgFgMgCQgNgCgOAAIgtAAgAg4hfIAABMIA8gBQAMgCAJgEQAIgGAFgHQAFgIAAgLQAAgLgFgHQgFgHgJgFQgJgEgMgDQgKgCgOAAg");
	this.shape.setTransform(9.1,12.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,18.2,25.4), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F9BE01").s().p("AlOBRQAagDAOgKQAHgFAGgIQAFgIAEgLQAGgRAGgyQADgbABhCICqAAIAAD5Ig4AAIAAjJIg9AAIgDAxQgBAYgEAVQgEAXgIAUQgIAUgNAPQgHAIgJAFQgIAGgKAFQgKAEgMADQgNADgOAAgAsSBgQggghAAg/QAAgeAKgYQAEgNAHgKQAHgKAIgIQARgRAXgJQAYgIAbAAQAQAAANACIAXAFIAZAMIgQAuQgLgHgQgFQgPgEgUAAQgMAAgNAEQgMAFgKAJQgJAKgGAPQgGAQAAAVQAAARAEAOQAEAPAIALQAIALAOAGQAOAGATABIAWgCIASgEIAXgJIAQAtQgMAHgWAHQgfAFgTAAQg9AAgfgigALzB+QgUgCgTgFIAAjzIA4AAIAABTIAOAAQAeAAAWAFQAWAGAPAKQAOAKAIAQQAHAPAAAXQAAAUgIAQQgIAQgPALQgPALgVAFQgWAFgaAAgAMEAGIAABLIAqgCQAKgCAHgEQAHgFAEgGQAFgIAAgKQAAgXgRgIQgIgEgMgBQgMgCgPAAgAzEB+QgUgCgTgFIAAjzICmAAIAAAwIhwAAIAAApIASAAQAcAAAWAEQAVAFAPAJQAIAFAFAGQAGAGAEAIQAEAIACAJQACAJAAALQAAAVgIAPQgHAQgPAKQgeAVg4gBgAy1BPIArgBQAKgBAIgEQAIgEAFgGQAEgGAAgMQAAgKgEgHQgFgHgHgDQgIgEgMgCIgqgCgASpB9IgYgqQgSgagKgLIgdAlIgYAqIhAAAQAQgdAVggIAwhAIhSh8IBEAAIAwBJIAxhJIBAAAIhRB5QAVAaAfAuQAVAiAMAWgAOnB9IAAj5IA5AAIAAD5gAJaB9IAAhqIheAAIAABqIg4AAIAAj5IA4AAIAABgIBeAAIAAhgIA4AAIAAD5gAEcB9IAAjJIhLAAIAAgwIDPAAIAAAwIhMAAIAADJgACKB9IgSg2IhiAAIgSA2Ig5AAIBKjEIAYg1IA2AAIBJCvIAbBKgABrAbIgkheIgkBeIBIAAgAmpB9IAAjJIhdAAIAADJIg4AAIAAj5IDNAAIAAD5gAwBB9IAAj5ICoAAIAAAvIhwAAIAAAyIBjAAIAAAtIhjAAIAAA8IB4AAIAAAvg");
	this.shape.setTransform(126,13);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,252,26), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F9BF03").s().p("ACLChIAAhDIitAAIAABDIg1AAIAAhyIAjAAQAOgXAHgXQAIgWAEgXQAEgYAAgYIABg+IClAAIAADJIAqAAIAABygAAegaQgDAUgGASQgGASgJARIBZAAIAAiaIg5AAgAP0BdIgngOIARgsIAvAPIAUABQAYAAAPgGQAOgHAAgRQAAgLgEgGQgGgGgIgDQgHgDgMgCIg5gBIAAguIA4gBQAIgCAHgDQAFgEAFgGQADgGAAgIQAAgNgKgGQgJgGgSAAQgUAAgPAFQgPAEgNAIIgSgsQAPgJAUgGQAVgGAZAAQAVAAAQAFQASAEAMAJQANAJAHANQAHAOAAASQAAAOgHANQgHAOgQAJIAQAKQAHAGAGAHQAFAIADAJQAEAJAAAMQAAAUgHAPQgHAOgPAJQgcASgyAAgAMeBhQgMgCgLgEQgYgIgQgRQgJgIgGgKQgHgKgEgMQgGgMgCgOQgDgOAAgQQAAggALgYQAJgYASgRQARgQAWgJQAMgEAMgCQALgCAMAAQAaAAAXAIQAMAEAJAHQAKAGAIAIQASARAJAYQAKAYAAAgQAAAQgCAOQgDAOgEAMQgKAYgRAQQgQARgXAIQgXAIgbAAQgMAAgMgCgAMahpQgMAGgIALQgIAKgFAPQgEAPAAASQAAATAEANQAFAPAIALQAIALAMAFQANAGAPAAQAQAAAMgGQANgFAJgLQAIgLAEgPQAFgNAAgTQAAgSgFgPQgEgPgIgLQgJgKgNgGQgMgGgQAAQgPAAgNAGgAlgBdIgngOIAQgsIAwAPIAUABQAXAAAPgGQAOgHAAgRQABgLgFgGQgFgGgIgDQgIgDgLgCIg6gBIAAguIA4gBQAIgCAHgDQAGgEAEgGQAEgGgBgIQAAgNgKgGQgJgGgSAAQgUAAgPAFQgOAEgOAIIgSgsQAPgJAUgGQAVgGAZAAQAVAAARAFQARAEANAJQAMAJAIANQAGAOABASQgBAOgGANQgIAOgPAJIAPAKQAIAGAGAHQAFAIADAJQADAJABAMQAAAUgIAPQgGAOgPAJQgcASgzAAgA0BBbQgQgJgNgQQgLgRgGgYQgGgYAAgfQAAgfAGgYIAHgXIALgSQAGgIAHgHQAIgGAHgEQAJgFAJgCQAJgCALAAQAVAAAQAIQARAJAMARQAMAQAGAZQAGAYAAAfQAAA+gYAiQgMAQgRAJQgQAIgVAAQgVAAgRgIgAzshsQgHAGgEALQgEAMgCAPIAABDQACAQAEALQAEALAHAGQAHAGAKAAQAKAAAGgGQAHgGAFgLQAEgLABgQIAAhDQgBgPgEgMQgFgLgHgGQgGgGgKAAQgKAAgHAGgA3NBbQgRgJgLgQQgMgRgGgYQgGgYAAgfQAAgfAGgYIAHgXIALgSQAGgIAHgHQAHgGAJgEQAIgFAKgCQAIgCALAAQAUAAARAIQARAJALARQANAQAGAZQAGAYAAAfQAAA+gZAiQgLAQgRAJQgRAIgUAAQgWAAgQgIgA24hsQgGAGgFALQgEAMgCAPIAABDQACAQAEALQAFALAGAGQAHAGAKAAQAKAAAHgGQAGgGAEgLQAEgLACgQIAAhDQgCgPgEgMQgEgLgGgGQgHgGgKAAQgKAAgHAGgA6ZBbQgRgJgLgQQgMgRgGgYQgGgYAAgfQAAgfAGgYIAIgXIAKgSQAGgIAHgHQAIgGAHgEQAJgFAJgCQAKgCAKAAQAUAAARAIQARAJAMARQAMAQAGAZQAGAYAAAfQAAA+gYAiQgMAQgRAJQgRAIgUAAQgWAAgQgIgA6EhsQgHAGgEALQgEAMgCAPIAABDQACAQAEALQAEALAHAGQAGAGALAAQAKAAAGgGQAIgGADgLQAFgLABgQIAAhDQgBgPgFgMQgDgLgIgGQgGgGgKAAQgLAAgGAGgAwPBeQgRgGgMgLQgXgWgIgnIgaAAIAAgjIAWAAIAAgXIgWAAIAAgkIAcAAQAEgUAJgPQAJgQANgKQANgKARgFQARgFAUAAQAQAAAMACIAXAHIgLAqIgRgFQgJgCgOAAQgWAAgMAJQgGAFgEAHQgFAHgCAJIBQAAIgHAkIhOAAIAAAXIBJAAIgGAjIg+AAQADALAEAHQAFAIAGAEQAGAEAIACQAIACAJAAQAMAAAMgCQAMgCAMgFIALApQgKAFgPAEQgPAEgVAAQgWAAgSgFgAsQBfQgTgCgUgFIAAjyICmAAIAAAvIhwAAIAAApIASAAQAcAAAWAFQAWAEAPAKQAHAFAFAGQAHAGADAIQAFAIABAJQACAJAAALQAAAUgIAQQgGAPgQAKQgeAVg4AAgAsBAwIAJABIAigCQALgBAHgEQAIgDAFgHQAEgGAAgLQAAgLgEgGQgFgGgHgEQgIgEgMgCIgqgBgAdRBeIgSg2IhiAAIgSA2Ig6AAIAahKIBJiuIA2AAIBJCuIAbBKgAcxgDIgkhfIgjBfIBHAAgAYDBeIAAjIIhMAAIAAgwIDPAAIAAAwIhMAAIAADIgAVcBeIAAiiQggAlgcApQgkA4gQAcIgvAAIAAj4IA4AAIAACTIBwiTIAuAAIAAD4gAJUBeIAAjJIhdAAIAADJIg4AAIAAj4IDNAAIAAD4gADlBeIAAj4ICoAAIAAAvIhwAAIAAAxIBkAAIAAAuIhkAAIAAA7IB5AAIAAAvgApNBeIAAj4ICoAAIAAAvIhwAAIAAAxIBkAAIAAAuIhkAAIAAA7IB5AAIAAAvgA9KBeIAAiyQgLAHgNAGIgaAKIgRgpIAtgWIAUgPIASgPIAlAAIAAD4g");
	this.shape.setTransform(193.4,16.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(0,0,386.7,32.2), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.btn();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(0,0,331,96), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.table();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(0,0,298,220), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(0,0,210,37), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(0,0,703,305), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(99.5,28.9,0.601,0.601,0,0,0,165.5,48);
	this.instance.alpha = 0.238;
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:99.6,alpha:0.121},7,cjs.Ease.get(-1)).to({x:99.5,alpha:0},7,cjs.Ease.get(1)).to({x:99.6,alpha:0.109},7,cjs.Ease.get(-1)).to({x:99.5,alpha:0.238},8,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(99.5,28.9,0.601,0.601,0,0,0,165.5,48);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,199,57.7);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ41();
	this.instance.parent = this;
	this.instance.setTransform(99.5,29,1,1,0,0,0,109.5,31.8);
	this.instance.alpha = 0.309;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({_off:true},1).wait(2));

	// Слой 1
	this.instance_1 = new lib.Символ40();
	this.instance_1.parent = this;
	this.instance_1.setTransform(99.5,28.9,1,1,0,0,0,99.5,28.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regY:28.8,scaleX:1.1,scaleY:1.1},0).wait(1).to({regY:28.9,scaleX:1,scaleY:1},0).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,199,57.7);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 34
	this.instance = new lib.Символ34();
	this.instance.parent = this;
	this.instance.setTransform(79.5,112.9,1,1,0,0,0,26.4,9.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({x:74.5},5).to({x:79.5},5).wait(16));

	// Символ 31
	this.instance_1 = new lib.Символ31();
	this.instance_1.parent = this;
	this.instance_1.setTransform(51.6,82.8,1.304,1.304,0,0,0,39.6,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(14).to({regX:39.5,regY:11.3,scaleX:1.52,scaleY:1.52,x:51.5,y:83.4},5).to({regX:39.6,regY:11.2,scaleX:1.3,scaleY:1.3,x:51.6,y:82.8},5).wait(16));

	// Символ 26
	this.instance_2 = new lib.Символ26();
	this.instance_2.parent = this;
	this.instance_2.setTransform(48.4,29.9,0.548,0.548,0,0,0,54.5,54.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({regX:54.6,scaleX:0.72,scaleY:0.72,y:24.4},5).to({regX:54.5,scaleX:0.55,scaleY:0.55,y:29.9},5).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,106,122.6);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 33
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(103.1,111.6,1,1,0,0,0,33.4,7.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({x:112.6},5).to({x:103.1},5).wait(16));

	// Символ 30
	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(68,85.5,1.247,1.247,0,0,0,54.5,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(14).to({scaleX:1.45,scaleY:1.45,x:68.1},5).to({scaleX:1.25,scaleY:1.25,x:68},5).wait(16));

	// Символ 27
	this.instance_2 = new lib.Символ27();
	this.instance_2.parent = this;
	this.instance_2.setTransform(59.9,31.3,0.548,0.548,0,0,0,57.6,57);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(14).to({regX:57.8,regY:56.8,scaleX:0.66,scaleY:0.66,x:60,y:25.2},5).to({regX:57.6,regY:57,scaleX:0.55,scaleY:0.55,x:59.9,y:31.3},5).wait(16));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,136.5,119.5);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ28();
	this.instance.parent = this;
	this.instance.setTransform(13.6,77.9,0.602,0.602,0,0,0,22.5,34);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({regX:22.4,scaleX:0.82,scaleY:0.82,x:13.5},5).to({regX:22.5,scaleX:0.6,scaleY:0.6,x:13.6},5).wait(21));

	// Слой 3
	this.instance_1 = new lib.Символ29();
	this.instance_1.parent = this;
	this.instance_1.setTransform(102.3,85.9,1,1,0,0,0,65.5,11.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({x:107.8},5).to({x:102.3},5).wait(21));

	// Слой 4
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(112.7,112.1,1,1,0,0,0,55.5,7.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({x:117.2},5).to({x:112.7},5).wait(21));

	// Слой 1
	this.instance_3 = new lib.Символ25();
	this.instance_3.parent = this;
	this.instance_3.setTransform(67.5,30.8,0.548,0.548,0,0,0,52.5,56.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({regX:52.6,regY:56,scaleX:0.66,scaleY:0.66,x:73.2,y:24.8},5).to({regX:52.5,regY:56.1,scaleX:0.55,scaleY:0.55,x:67.5,y:30.8},5).wait(21));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,168.1,119.9);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(89.9,9.4,0.714,0.714,0,0,0,125.9,13.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,179.8,18.6), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(99.5,28.9,1,1,0,0,0,99.5,28.9);
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.Символ39(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-2.8,219,63.5);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ22();
	this.instance.parent = this;
	this.instance.setTransform(128.5,9.2,1,1,0,0,0,89.9,9.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.96,scaleY:0.96,y:9.3},7,cjs.Ease.get(-1)).to({regY:9.3,scaleX:0.91,scaleY:0.91},7,cjs.Ease.get(1)).to({scaleX:0.95,scaleY:0.95},7,cjs.Ease.get(-1)).to({regY:9.2,scaleX:1,scaleY:1,y:9.2},8,cjs.Ease.get(1)).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ8();
	this.instance_1.parent = this;
	this.instance_1.setTransform(544.6,11.9,0.666,0.666,0,0,0,193.2,16.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regY:16.2,scaleX:0.69,scaleY:0.69,y:12},7,cjs.Ease.get(-1)).to({regY:16.1,scaleX:0.71,scaleY:0.71},7,cjs.Ease.get(1)).to({regX:193.3,regY:16.2,scaleX:0.69,scaleY:0.69,x:544.7},7,cjs.Ease.get(-1)).to({regX:193.2,regY:16.1,scaleX:0.67,scaleY:0.67,x:544.6,y:11.9},8,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ14();
	this.instance_2.parent = this;
	this.instance_2.setTransform(309.9,9.6,0.714,0.714,0,0,0,120,12.8);

	this.instance_3 = new lib.Символ13();
	this.instance_3.parent = this;
	this.instance_3.setTransform(21.5,9.5,0.714,0.714,0,0,0,9.1,12.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2}]}).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(15,0,658.4,22.6);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(254.6,16.4,1,1,0,0,0,254.6,16.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.08,scaleY:1.08,x:254.7,y:16.5},7,cjs.Ease.get(-1)).to({scaleX:1.16,scaleY:1.16,y:16.4},7,cjs.Ease.get(1)).to({scaleX:1.07,scaleY:1.07,y:16.5},8,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:254.6,y:16.4},7,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-8.7,509.1,33);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ35();
	this.instance.parent = this;
	this.instance.setTransform(33.2,308.2,1,1,0,0,0,84,60);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(89).to({_off:false},0).to({y:231.1},4,cjs.Ease.get(-1)).to({y:141.2},5,cjs.Ease.get(1)).wait(59).to({y:135.2},2).to({y:319.3},4).wait(63));

	// Слой 4
	this.instance_1 = new lib.Символ36();
	this.instance_1.parent = this;
	this.instance_1.setTransform(247.9,307.4,1,1,0,0,0,68.2,59.7);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(93).to({_off:false},0).to({y:230.3},4,cjs.Ease.get(-1)).to({y:140.4},5,cjs.Ease.get(1)).wait(57).to({y:134.4},2).to({y:318.4},4).wait(61));

	// Слой 10
	this.instance_2 = new lib.Символ37();
	this.instance_2.parent = this;
	this.instance_2.setTransform(457.3,310.3,1,1,0,0,0,53,61.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(97).to({_off:false},0).to({y:233.2},4,cjs.Ease.get(-1)).to({y:143.3},5,cjs.Ease.get(1)).wait(55).to({y:137.3},2).to({y:321.3},4).wait(59));

	// Слой 2
	this.instance_3 = new lib.Символ24();
	this.instance_3.parent = this;
	this.instance_3.setTransform(863.2,102.8,0.433,0.433,0,0,0,544.3,53.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(56).to({_off:false},0).to({x:223.1,alpha:1},9).to({x:233.1},3).to({regX:544.1,scaleX:0.47,scaleY:0.47,x:233,y:104.4},3,cjs.Ease.get(-1)).to({regX:544.3,regY:53.7,scaleX:0.51,scaleY:0.51,x:233.1,y:106.7},4,cjs.Ease.get(1)).to({regY:53.8,scaleX:0.47,scaleY:0.47,x:233.2,y:104.7},4,cjs.Ease.get(-1)).to({regY:53.6,scaleX:0.43,scaleY:0.43,x:233.1,y:102.8},4,cjs.Ease.get(1)).to({regY:53.5,scaleX:0.32,scaleY:0.32,x:233,y:38},4).to({scaleX:0.3,scaleY:0.3},8,cjs.Ease.get(-1)).to({regX:544.4,regY:53.6,scaleX:0.26,scaleY:0.26},9,cjs.Ease.get(1)).to({regX:544.5,regY:53.7,scaleX:0.29,scaleY:0.29},9,cjs.Ease.get(-1)).to({regX:544.3,regY:53.5,scaleX:0.32,scaleY:0.32},9,cjs.Ease.get(1)).to({scaleX:0.3,scaleY:0.3},8,cjs.Ease.get(-1)).to({regX:544.4,regY:53.6,scaleX:0.26,scaleY:0.26},9,cjs.Ease.get(1)).to({regX:544.5,regY:53.7,scaleX:0.29,scaleY:0.29},9,cjs.Ease.get(-1)).to({regX:544.3,regY:53.5,scaleX:0.32,scaleY:0.32},9,cjs.Ease.get(1)).to({regX:544.6,regY:53.6,scaleX:0.19,scaleY:0.19,alpha:0},6).wait(63));

	// Слой 9
	this.instance_4 = new lib.Символ23();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-322,48.2,0.317,0.317,0,0,0,603.1,51.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(56).to({_off:false},0).to({x:243.1,y:51.8,alpha:1},9).to({x:233.1},3).to({regY:51.7,scaleX:0.34,scaleY:0.34,y:49.7},3,cjs.Ease.get(-1)).to({regX:603.2,regY:51.6,scaleX:0.37,scaleY:0.37,y:46.8},4,cjs.Ease.get(1)).to({regX:603.3,scaleX:0.35,scaleY:0.35,x:233.2,y:49.4},4,cjs.Ease.get(-1)).to({regX:603.1,scaleX:0.32,scaleY:0.32,x:233.1,y:51.8},4,cjs.Ease.get(1)).to({regX:602.9,regY:51.8,scaleX:0.24,scaleY:0.24,x:233,y:0.3},4).to({regX:603.1,scaleX:0.26,scaleY:0.26,x:233.1},8,cjs.Ease.get(-1)).to({regY:51.6,scaleX:0.29,scaleY:0.29,x:233},9,cjs.Ease.get(1)).to({regX:603.3,regY:51.7,scaleX:0.26,scaleY:0.26,x:233.1},9,cjs.Ease.get(-1)).to({regX:602.9,regY:51.8,scaleX:0.24,scaleY:0.24,x:233},9,cjs.Ease.get(1)).to({regX:603.1,scaleX:0.26,scaleY:0.26,x:233.1},8,cjs.Ease.get(-1)).to({regY:51.6,scaleX:0.29,scaleY:0.29,x:233},9,cjs.Ease.get(1)).to({regX:603.3,regY:51.7,scaleX:0.26,scaleY:0.26,x:233.1},9,cjs.Ease.get(-1)).to({regX:602.9,regY:51.8,scaleX:0.24,scaleY:0.24,x:233},9,cjs.Ease.get(1)).to({regX:603.1,regY:51.5,scaleX:0.37,scaleY:0.37,x:233.1,y:0.2,alpha:0},6).wait(63));

	// Символ 20
	this.instance_5 = new lib.Символ20();
	this.instance_5.parent = this;
	this.instance_5.setTransform(312.9,36.1,1,1,0,0,0,128.8,36.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(38).to({alpha:0},7).wait(124).to({regX:128.9,regY:36,scaleX:1.42,scaleY:1.42,x:251,y:36},0).to({regX:128.8,regY:36.1,scaleX:0.92,scaleY:0.92,x:250.9,y:36.1,alpha:1},6).to({scaleX:1,scaleY:1},2).wait(7).to({x:270.9},0).to({x:312.9},2).wait(40));

	// Символ 19
	this.instance_6 = new lib.Символ19();
	this.instance_6.parent = this;
	this.instance_6.setTransform(123.5,47.9,1,1,0,0,0,45.4,8.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(34).to({x:133.5},3).to({x:-181,alpha:0},4).wait(142).to({x:-166.5,alpha:1},0).to({x:-50.5},2,cjs.Ease.get(-1)).to({x:123.5},3,cjs.Ease.get(1)).wait(38));

	// Символ 18
	this.instance_7 = new lib.Символ18();
	this.instance_7.parent = this;
	this.instance_7.setTransform(104.5,25,1,1,0,0,0,64.3,6.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(32).to({x:114.5},3).to({x:-200,alpha:0},4).wait(142).to({x:-185.5,alpha:1},0).to({x:-69.5},2,cjs.Ease.get(-1)).to({x:104.5},3,cjs.Ease.get(1)).wait(40));

	// Символ 17
	this.instance_8 = new lib.Символ17();
	this.instance_8.parent = this;
	this.instance_8.setTransform(111,3.1,1,1,0,0,0,57.5,7.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(30).to({x:121},3).to({x:-193.1,alpha:0},4).wait(142).to({x:-179,alpha:1},0).to({x:-63},2,cjs.Ease.get(-1)).to({x:111},3,cjs.Ease.get(1)).wait(42));

	// Символ 15
	this.instance_9 = new lib.Символ15();
	this.instance_9.parent = this;
	this.instance_9.setTransform(235.4,128.4,0.814,0.814,0,0,0,345.8,11.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(43).to({y:123.9},3).to({y:322.8},4).wait(138).to({x:855.5,y:128.4},0).to({x:225.4},10).to({x:235.4},2).wait(26));

	// Символ 12
	this.instance_10 = new lib.Символ12();
	this.instance_10.parent = this;
	this.instance_10.setTransform(237.9,91.3,0.581,0.581,0,0,0,254.7,16.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(46).to({y:86.7},3).to({y:285.6},4).wait(135).to({x:-270.2,y:91.3},0).to({x:247.9},10).to({x:237.9},2).wait(26));

	// Символ 6
	this.instance_11 = new lib.Символ21();
	this.instance_11.parent = this;
	this.instance_11.setTransform(237.8,185.8,1,1,0,0,0,99.5,28.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(40).to({scaleX:1.19,scaleY:1.19},3).to({regY:28.8,scaleX:0.39,scaleY:0.39,y:245.8,alpha:0},4).wait(149).to({regY:28.9,scaleX:1.87,scaleY:1.87,y:185.9},0).to({scaleX:1.13,scaleY:1,y:185.8,alpha:1},5).to({scaleX:1},2).wait(23));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34,-10,536.1,224.6);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ16();
	this.instance.parent = this;
	this.instance.setTransform(320.1,181.3,1,1,0,0,0,237.8,107.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(320.1,32.6,0.621,0.621,0,0,0,105.1,18.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(828.2,398.6,1,1,0,0,0,149,110);
	this.instance_2.alpha = 0.52;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(320,152.5,1,1,0,0,0,351.5,152.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(288.5,152.5,1008.7,508.6);
// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.png?1488528555474", id:"index_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;