(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1486650837518", id:"bg"},
		{src:"images/bgg.png?1486650837518", id:"bgg"},
		{src:"images/kursor.png?1486650837518", id:"kursor"},
		{src:"images/lev_rukapngкопия.png?1486650837518", id:"lev_rukapngкопия"},
		{src:"images/prav_rukapngкопия.png?1486650837518", id:"prav_rukapngкопия"},
		{src:"images/telkapngкопия.png?1486650837518", id:"telkapngкопия"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,700,400);


(lib.bgg = function() {
	this.initialize(img.bgg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.kursor = function() {
	this.initialize(img.kursor);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,70,76);


(lib.lev_rukapngкопия = function() {
	this.initialize(img.lev_rukapngкопия);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,76,207);


(lib.prav_rukapngкопия = function() {
	this.initialize(img.prav_rukapngкопия);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,123,148);


(lib.telkapngкопия = function() {
	this.initialize(img.telkapngкопия);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,236,246);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bgg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.kursor();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.569,0.569);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,39.8,43.2);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#965A00","#A28200"],[0,1],-6,61.8,140.1,-84.3).s().p("A03FjQhkAAAAhjIAAn/QAAhjBkAAMApvAAAQBkAAAABjIAAH/QAABjhkAAg");
	this.shape.setTransform(143.7,36.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,1.3,287.4,71.2);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF9900","#FFCC00"],[0,1],-6,61.8,140.1,-84.3).s().p("A03FjQhkAAAAhjIAAn/QAAhjBkgBMApvAAAQBkABAABjIAAH/QAABjhkAAg");
	this.shape.setTransform(143.7,35.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,287.4,71.2);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AL/CsIg7ipIAAgDIAxirIAqAAIgwCrIA+CsgAKUCsIAAlXIAvAAIAAFXgAJACsIAAh/Ig0AAIAAB/IgvAAIAAkcQAAg7A4AAIAiAAQAcAAANAPQAOAPAAAdIAAEcgAIMhtIAABxIA0AAIAAhxQAAgUgUAAIgMAAQgVAAABAUgAGTCsIg6ipIAAgDIAwirIArAAIgxCrIA+CsgAEoCsIAAlXIAvAAIAAFXgAA0CsIAAlXIAuAAIAAB9IAnAAQAbAAAOAOQAOAPAAAcIAABmQAAA7g4AAgABiCCIAbAAQAKAAAGgFQAEgFABgKIAAhgQAAgSgSAAIgeAAgAg5CsIAAktIgsAAIAAgqICEAAIAAAqIgqAAIAAEtgAiuCsIAAh/Ig0AAIAAB/IgvAAIAAkcQAAg7A3AAIAjAAQAbAAAOAPQAOAPAAAdIAAEcgAjihtIAABxIA0AAIAAhxQAAgUgUAAIgNAAQgTAAAAAUgAllCsIAAidIg5AAIAACdIguAAIAAlXIAuAAIAACSIA5AAIAAiSIAuAAIAAFXgApICsQgcAAgNgPQgOgPgBgdIAAgWIAuAAIAAATQABAKAEAFQAFAFAJAAIAKAAQALAAAFgFQAFgFAAgKIAAhHQAAgXgbAAIgMAAIAAglIAGAAQAOAAAGgFQAIgGgBgLIAAhBQAAgLgFgFQgFgFgKAAIgHAAQgJAAgEAFQgFAFAAALIAAAiIguAAIAAgmQAAg7A3AAIAbAAQAcAAAOAPQAOAPgBAdIAABFQABAQgJAKQgHAKgPAEQAkAHAAAiIAABLQAAAdgOAPQgOAPgbAAgAr0CsQgbAAgOgPQgOgPAAgdIAAgWIAuAAIAAATQAAAKAFAFQAEAFAJAAIALAAQATAAAAgUIAAhSIgxABQgXAAgLgRQgMgOAAghIAAiIIAuAAIAACJQABAXAKAAIATAAQARAAACgTIAAiNIAwAAIAAEcQgBAdgPAPQgNAPgdAAg");
	this.shape.setTransform(81.3,17.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,162.6,34.5);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF9901","#FAB900"],[0,1],-0.9,8.9,-0.9,-18).s().p("AgVCsIAAktIgsAAIAAgqICEAAIAAAqIgsAAIAAEtg");
	this.shape.setTransform(271.5,17.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FF9901","#FAB900"],[0,1],0.6,10.5,0.6,-16.4).s().p("Ag4CsIAAlXIBxAAIAAAqIhCAAIAABoIA6AAIAAAoIg6AAIAABzIBCAAIAAAqg");
	this.shape_1.setTransform(256.4,17.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.2,9.4,-1.2,-17.5).s().p("AAaCsIAAh/IgzAAIAAB/IguAAIAAkcQAAg7A3AAIAhAAQAcAAAOAPQANAPAAAdIAAEcgAgZhtIAABxIAzAAIAAhxQAAgUgUAAIgKAAQgVAAAAAUg");
	this.shape_2.setTransform(239.6,17.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#FF9901","#FAB900"],[0,1],0.9,10.5,0.9,-16.4).s().p("AhHCsIAAlXIBNAAQAeAAAQAQQAPAPAAAgIAABCQAAAdggAHIAAADQASADAKAKQAJAKAAAOIAABWQAAAagNANQgNANgaAAgAgZCCIAhAAQASAAAAgPIAAhMQAAgZgaAAIgZAAgAgZgZIAWAAQALAAAHgHQAGgGAAgMIAAg2QAAgNgFgGQgFgGgLAAIgZAAg");
	this.shape_3.setTransform(221.3,17.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.8,10.5,-1.8,-17).s().p("AgWCsIAAlXIAsAAIAAFXg");
	this.shape_4.setTransform(208.4,17.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#FF9901","#FAB900"],[0,1],-1,6.3,-1,-16.5).s().p("AhECsIAAlXIAuAAIAAB9IAkAAQAcAAAOAOQANAPAAAcIAABmQAAA7g3AAgAgWCCIAZAAQAKAAAFgFQAFgFAAgKIAAhgQAAgSgSAAIgbAAg");
	this.shape_5.setTransform(196.8,17.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#FF9901","#FAB900"],[0,1],-0.9,8.1,-0.9,-18.8).s().p("AgWCsIAAktIgsAAIAAgqICEAAIAAAqIgsAAIAAEtg");
	this.shape_6.setTransform(181,17.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.2,5.8,-1.2,-17).s().p("AAaCsIAAh/IgzAAIAAB/IguAAIAAkcQAAg7A3AAIAhAAQAcAAAOAPQANAPAAAdIAAEcgAgZhtIAABxIAzAAIAAhxQAAgUgUAAIgLAAQgTAAgBAUg");
	this.shape_7.setTransform(164.4,17.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#FF9901","#FAB900"],[0,1],-1,7.4,-1,-17.5).s().p("AhECsIAAlXICGAAIAAAqIhYAAIAABTIAkAAQAcAAAOAOQANAPAAAcIAABmQAAA7g4AAgAgWCCIAZAAQAKAAAFgFQAFgFAAgKIAAhgQAAgSgSAAIgbAAg");
	this.shape_8.setTransform(146.3,17.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.2,5.8,-1.2,-17).s().p("AAaCsIAAh/IgzAAIAAB/IguAAIAAkcQAAg7A3AAIAhAAQAcAAAOAPQANAPAAAdIAAEcgAgZhtIAABxIAzAAIAAhxQAAgUgUAAIgLAAQgTAAgBAUg");
	this.shape_9.setTransform(128.3,17.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#FF9901","#FAB900"],[0,1],-1,9.4,-1,-17.5).s().p("AhECsIAAlXIBRAAQA4AAAAA7IAABmQABAcgOAOQgOAPgcAAIgkAAIAAB9gAgWAFIAbAAQASAAAAgSIAAhgQAAgKgFgFQgFgFgKAAIgZAAg");
	this.shape_10.setTransform(110.2,17.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.2,5.8,-1.2,-17).s().p("AAaCsIAAh/IgzAAIAAB/IguAAIAAkcQAAg7A3AAIAhAAQAbAAAOAPQAOAPAAAdIAAEcgAgZhtIAABxIAzAAIAAhxQAAgUgUAAIgLAAQgTAAgBAUg");
	this.shape_11.setTransform(92.2,17.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#FF9901","#FAB900"],[0,1],0,10.9,0,-15.9).s().p("AgNCsQgcAAgOgPQgOgPABgdIAAgWIAtAAIAAATQABAKAEAFQAFAFAJAAIAIAAQALAAAFgFQAFgFAAgKIAAhHQAAgXgZAAIgMAAIAAglIAHAAQALAAAGgFQAIgGAAgLIAAhBQgBgLgFgFQgFgFgJAAIgFAAQgKAAgFAFQgDAFAAALIAAAiIgvAAIAAgmQAAg7A3AAIAZAAQAcAAANAPQAOAPAAAdIAABFQABAQgJAKQgHAKgPAEQAkAHAAAiIAABLQAAAdgOAPQgOAPgbAAg");
	this.shape_12.setTransform(74,17.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#FF9901","#FAB900"],[0,1],-1.1,6.9,-1.1,-14.6).s().p("AgOCsQgbAAgOgPQgOgPAAgdIAAgWIAuAAIAAATQAAAKAFAFQAEAFAJAAIAJAAQATAAAAgUIAAhSIgvABQgXAAgLgRQgMgOAAghIAAiIIAuAAIAACJQABAXAKAAIARAAQARAAACgTIAAiNIAwAAIAAEcQgBAdgPAPQgNAPgdAAg");
	this.shape_13.setTransform(7.1,17.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#FF9901","#FAB900"],[0,1],1.1,7.3,1.1,-17.1).s().p("AgzCsIA9isIguirIAoAAIAwCrIAAADIg4Cpg");
	this.shape_14.setTransform(21.8,17.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#FF9901","#FAB900"],[0,1],-0.9,2.9,-0.9,-16.6).s().p("AgVCsIAAlXIAsAAIAAFXg");
	this.shape_15.setTransform(29.6,17.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#FF9901","#FAB900"],[0,1],3,3.4,3,-14).s().p("AAFCsIg3ipIAAgDIAwirIAoAAIgvCrIA8Csg");
	this.shape_16.setTransform(37.3,17.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#FF9901","#FAB900"],[0,1],0.3,5.3,0.3,-11.1).s().p("Ag4CsIAAlXIBxAAIAAAqIhCAAIAABoIA6AAIAAAoIg6AAIAABzIBCAAIAAAqg");
	this.shape_17.setTransform(50.6,17.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой 2
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#4D3D00").s().p("AUUCsIAAktIgsAAIAAgqICGAAIAAAqIgsAAIAAEtgARbCsIAAlXIBzAAIAAAqIhEAAIAABoIA8AAIAAAoIg8AAIAABzIBEAAIAAAqgAQHCsIAAh/Ig0AAIAAB/IgvAAIAAkcQAAg7A4AAIAiAAQAcAAAOAPQANAPAAAdIAAEcgAPThtIAABxIA0AAIAAhxQAAgUgUAAIgMAAQgUAAAAAUgALtCsIAAlXIBPAAQAfAAAPAQQAQAPAAAgIAABCQAAAdghAHIAAADQATADAJAKQAJAKAAAOIAABWQAAAagNANQgNANgaAAgAMcCCIAiAAQASAAAAgPIAAhMQAAgZgbAAIgZAAgAMcgZIAVAAQANAAAHgHQAGgGAAgMIAAg2QAAgNgFgGQgFgGgKAAIgbAAgAKeCsIAAlXIAuAAIAAFXgAH7CsIAAlXIAuAAIAAB9IAmAAQAcAAAOAOQANAPAAAcIAABmQAAA7g3AAgAIpCCIAbAAQAKAAAFgFQAFgFAAgKIAAhgQAAgSgSAAIgdAAgAGLCsIAAktIgsAAIAAgqICGAAIAAAqIgsAAIAAEtgAEXCsIAAh/Ig1AAIAAB/IguAAIAAkcQAAg7A3AAIAjAAQAbAAAOAPQAOAPAAAdIAAEcgADihtIAABxIA1AAIAAhxQAAgUgUAAIgNAAQgUAAAAAUgAACCsIAAlXICJAAIAAAqIhbAAIAABTIAmAAQAcAAAOAOQAOAPAAAcIAABmQAAA7g4AAgAAwCCIAbAAQAKAAAFgFQAFgFAAgKIAAhgQAAgSgSAAIgdAAgAhQCsIAAh/Ig1AAIAAB/IguAAIAAkcQAAg7A3AAIAjAAQAbAAAOAPQAOAPAAAdIAAEcgAiFhtIAABxIA1AAIAAhxQAAgUgUAAIgNAAQgUAAAAAUgAllCsIAAlXIBUAAQA4AAAAA7IAABmQAAAcgOAOQgOAPgcAAIgmAAIAAB9gAk3AFIAdAAQASAAAAgSIAAhgQAAgKgFgFQgFgFgKAAIgbAAgAm5CsIAAh/Ig1AAIAAB/IguAAIAAkcQAAg7A3AAIAjAAQAbAAAOAPQAOAPAAAdIAAEcgAnuhtIAABxIA1AAIAAhxQAAgUgUAAIgNAAQgUAAAAAUgAqYCsQgcAAgOgPQgOgPAAgdIAAgWIAuAAIAAATQAAAKAFAFQAFAFAJAAIAKAAQALAAAFgFQAFgFAAgKIAAhHQAAgXgbAAIgMAAIAAglIAGAAQAOAAAGgFQAHgGAAgLIAAhBQAAgLgFgFQgFgFgLAAIgGAAQgJAAgFAFQgEAFAAALIAAAiIguAAIAAgmQAAg7A3AAIAbAAQAcAAANAPQAOAPAAAdIAABFQAAAQgIAKQgHAKgPAEQAkAHAAAiIAABLQAAAdgOAPQgOAPgbAAgAutCsIAAlXIBzAAIAAAqIhEAAIAABoIA8AAIAAAoIg8AAIAABzIBEAAIAAAqgAvyCsIg6ipIAAgDIAwirIAqAAIgwCrIA+CsgAxcCsIgBlXIAuAAIAAFXgAzICsIA/isIgwirIAqAAIAwCrIAAADIg6CpgA02CsQgbAAgOgPQgOgPAAgdIAAgWIAuAAIAAATQAAAKAFAFQAEAFAJAAIAMAAQASAAAAgUIAAhSIgwABQgXAAgMgRQgLgOAAghIAAiIIAuAAIAACJQAAAXALAAIASAAQASAAABgTIAAiNIAwAAIAAEcQgBAdgOAPQgOAPgcAAg");
	this.shape_18.setTransform(140.5,16.9);

	this.timeline.addTween(cjs.Tween.get(this.shape_18).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-0.3,279.6,34.8);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AG5C/IAAiJQAAgHAGAAIAXAAQAFAAAGACQAFADAEAEQAEAEACAFQADAGAAAGIAAAsQAAAGgDAGQgCAFgEAEQgEAEgFACQgGADgFAAIgQAAIAAAoQAAAHgHAAQgGAAAAgHgAHGCJIAQAAQAGAAAFgFQAEgEAAgHIAAgsQAAgHgEgEQgFgFgGAAIgQAAgAFcC/QAAgHAGAAQAGAAAEgDQAEgDABgGIAIgbIgahcQAAgHAHAAQAFAAABAFIAUBGIAVhGQACgFAEAAQAHAAAAAHIgBACIgjB5IgEAJQgDAEgDADQgIAGgKAAQgGAAAAgHgAANC/IAAiJQAAgHAHAAIAWAAQAGAAAFACQAFADAEAEQAEAEADAFQACAGAAAGIAAAsQAAAGgCAGQgDAFgEAEIgJAGQgFADgGAAIgQAAIAAAoQAAAHgGAAQgHAAAAgHgAAaCJIAQAAQAGAAAFgFQAEgEAAgHIAAgsQAAgHgEgEQgFgFgGAAIgQAAgAEYCZQgHAAAAgHIAAhZIAAgDQAAgHAHAAIAmAAQAHAAAAAHQAAAHgHAAIgfAAIAAAQIAPAAQAGAAAFACQAGACADAEQAFAFACAFQACAGAAAGIAAAQQAAAGgCAFQgCAGgFAEQgDAEgGACQgFADgGAAgAEfCLIAPAAQAGAAAFgFQAFgFAAgGIAAgQQAAgHgFgFQgFgFgGAAIgPAAgAIaCVQgFgBgDgFQgEgDgCgGQgDgFAAgFQAAgIADgGQADgGAGgEIAVgPQAFgEAAgGQAAgGgDgFQgEgEgGAAQgFAAgFAFQgEAFgDAAQgHAAAAgGQAAgEADgDQACgDAEgDQAHgFAIAAQAFAAAFACQAFACAEAEIAGAJQABAFAAAGQAAAHgCAFQgDAGgGAEIgUAPQgGAFAAAIQAAAGAEAEQAFAEAEAAQAGAAAFgFQAFgGADAAQAHAAAAAHQAAADgDAEQgCADgEADQgIAFgIAAQgFAAgGgDgADmCRIAAgwIghAAIAAAwQAAAHgGAAQgHAAAAgHIAAhcQAAgHAHAAQAGAAAAAHIAAAdIAhAAIAAgdQAAgHAHAAQAGAAAAAHIAABcQAAAHgGAAQgHAAAAgHgAgzCVQgIgDgFgIQgFgHAAgJIAAguQAAgGACgGQACgFAEgEIAJgGQAGgDAGAAQAFAAAGADQAFACAEAEIAGAJQACAGAAAGIAAAXQAAAHgGAAIgmAAIAAAQQAAAGAEAFQAFAFAHAAQADAAAFgDQAFgEACAAQAHAAAAAHQAAAGgIAEQgHAEgHAAQgGAAgFgDgAgzBBQgFAEAAAHIAAAQIAfAAIAAgQQAAgHgEgEQgFgFgGAAQgHAAgEAFgAhuCRIAAhEQAAgHgEgEQgFgFgGAAIgQAAIAABUQAAAHgGAAQgHAAAAgHIAAhUIgfAAIAABUQAAAHgHAAQgGAAAAgHIAAhbQAAgHAGAAIBDAAQAGAAAFACQAFADAEAEQAEAEACAFQACAGAAAGIAABEQAAAHgGAAQgHAAAAgHgAk+CUIgZgwIgLAMIAAAhQAAAHgHAAQgHAAAAgHIAAhcQAAgHAHAAQAHAAAAAHIAAAmIAlgqQACgDADAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQADACAAADQAAAAAAABQAAABgBAAQAAABAAAAQgBABAAAAIgbAgIAcA0IABAEQAAAHgIAAQgDAAgCgEgAnyCVQgCgCAAgEQAAgEACgDQADgDAEAAQAEAAACADQAEADAAAEQAAAEgEACQgCADgEAAQgEAAgDgDgAowCVQgFgBgDgFQgEgDgCgGQgDgFAAgFQAAgIAEgGQACgGAGgEIAVgPQAFgEAAgGQAAgGgDgFQgEgEgFAAQgGAAgFAFQgEAFgDAAQgHAAAAgGQAAgEADgDQACgDAEgDQAHgFAIAAQAFAAAFACQAFACAEAEQAEAEACAFQACAFAAAGQAAAHgDAFQgDAGgFAEIgVAPQgGAFAAAIQAAAGAEAEQAFAEAFAAQAFAAAFgFQAGgGACAAQAHAAAAAHQAAADgDAEQgCADgEADQgIAFgIAAQgFAAgGgDgAnACXQgHAAAAgHIAAiDQAAgIAHAAIAtAAQAHAAAAAIQAAAHgHAAIgmAAIAAAxIAhAAQAHAAAAAHQAAAHgHAAIghAAIAAA2IAmAAQAHAAAAAHQAAAHgHAAgAB+CXQgGAAgFgDIgJgGQgEgEgCgFQgDgGAAgGIAAhEQAAgHAHAAQAHAAAAAHIAABEQAAAHAEAEQAFAFAGAAIAQAAIAAhUQAAgHAHAAQAGAAAAAHIAABbQAAAHgGAAgAkBCXQgFAAgGgDQgFgCgEgEIgGgJQgCgGAAgGQAAgGACgGIAGgJQAEgFAFgCQAGgCAFAAIAQAAIAAgQQAAgGgEgEQgFgFgGAAQgEAAgEADQgGAEgCAAQAAAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgCgDAAgCQAAgGAIgEQAHgEAHAAQAGAAAGADQAEACAEAEQAEAEACAFQACAGAAAFIAABFQAAAHgGAAgAkMBuQgEAEAAAHQAAAHAEAEQAFAFAGAAIAQAAIAAggIgQAAQgGAAgFAFgAgpgWQAAgFAEgCQAEgBAAgEIAAgFIAAAAQgIAAAAgHQAAgIAIAAIAHAAQAIAAAAAIIAAAMQAAAGgEAHQgFAHgGAAQgIAAAAgIgACKgkQgHgDgFgFQgFgGgDgHQgDgHAAgIIAAhWQAAgIACgHQADgHAGgFQAFgGAHgCQAHgEAIAAQAKAAAJAFQAKAGAFAJIABAEQAAADgDACQgCADgDAAQgFAAgDgEQgDgFgFgEQgFgCgGAAQgJAAgHAGQgGAHAAAJIAAAdQAFgDAFgCQAGgCAGAAQAIAAAHADQAHADAGAGQAFAFADAHQADAHAAAIIAAAZQAAAIgDAHQgDAHgFAGQgGAFgHADQgHADgIAAQgIAAgHgDgACJhxQgGAHAAAJIAAAZQAAAKAGAGQAHAHAJAAQAKAAAGgHQAHgGAAgKIAAgZQAAgJgHgHQgGgHgKAAQgJAAgHAHgAn/gpIAAhEIgsAAIAABEQAAAIgIAAQgJAAAAgIIAAiTQAAgJAJAAQAIAAAAAJIAAA+IAsAAIAAg+QAAgJAJAAQAIAAAAAJIAACTQAAAIgIAAQgJAAAAgIgAh/gjQgHgDAEgHIgBAAIANgYQgFgCgDgEQgFgFgCgGQgDgGAAgGIAAgSQAAgHADgGQACgGAFgFQAEgEAGgDQAGgCAHAAIAZAAQAIAAAAAHIAABlQAAAHgIAAQgHAAAAgHIAAgYIgTAAIgMAYIgBACQgCAFgEAAIgEgBgAh0iBQgFAFAAAIIAAASQAAAHAFAFQAGAFAHAAIASAAIAAg1IgSAAQgHAAgGAFgAIygpIAAhLQAAgIgFgFQgFgFgHAAIgSAAIAABdQAAAHgIAAQgHAAAAgHIAAhdIgkAAIAABdQAAAHgIAAQgHAAAAgHIAAhlQAAgHAHAAIBNAAQAGAAAGACQAGADAFAEQAEAFADAGQADAGAAAHIAABLQAAAHgIAAQgIAAAAgHgAGBgkQgKgEgFgIQgGgJAAgKIAAgyQAAgHADgGQADgGAEgFQAFgEAGgDQAGgCAGAAQAHAAAGACQAGADAFAEQAEAFADAGQACAGAAAHIAAAZQAAAIgHAAIgrAAIAAARQAAAHAEAGQAGAFAHAAQAEAAAGgDQAGgEACAAQAIAAAAAHQAAAHgKAEQgIAEgIAAQgHAAgFgCgAGBiCQgFAFAAAIIAAARIAjAAIAAgRQAAgIgFgFQgFgFgIAAQgHAAgFAFgAi5gpIAAhLQAAgIgGgFQgFgFgHAAIgSAAIAABdQAAAHgIAAQgHAAAAgHIAAhdIgkAAIAABdQAAAHgHAAQgIAAAAgHIAAhlQAAgHAIAAIBMAAQAGAAAGACQAHADAEAEQAFAFACAGQADAGAAAHIAABLQAAAHgIAAQgHAAAAgHgAlhgkQgJgEgGgIQgFgJAAgKIAAgyQAAgHACgGQADgGAEgEQAFgFAGgDQAGgCAHAAQAIAAAIADQAJAFAAAHQAAAHgIAAQgCAAgGgEQgFgDgEAAQgIAAgFAFQgFAFAAAIIAAAyQAAAHAFAGQAFAFAIAAQAEAAAGgDQAFgEACAAQAIAAAAAHQAAAHgJAEQgJAEgHAAQgHAAgGgCgAAQgiQgIAAAAgIIABgEIA1hlQADgFAAgGQAAgJgHgHQgHgGgJAAQgFAAgEACIgGAFQgIAIgDAAIgEgBQgEgDAAgEIABgEQAFgJAJgGQAIgFAMAAQAHAAAHAEQAHACAGAFQAFAGADAHQADAHAAAIQAAAKgEAIIgvBaIArAAQAIAAAAAIQAAAIgIAAgAFCgoIgXhNIgXBNQgCAFgGAAQgDAAgCgCQgCgCAAgDIAfhoQABgFAGAAQAGAAABAFIAfBoQAAAHgHAAQgGAAgCgFgAm0gjQgHAAgGgCQgGgDgFgEQgEgFgDgGQgCgGAAgHQAAgGACgHQADgGAEgEQAFgFAGgCQAGgDAHAAIARAAIAAgRQAAgHgFgFQgFgFgHAAQgEAAgGADQgFAEgDAAQgDAAgCgCQgCgDAAgCQAAgHAJgFQAIgDAIAAQAHAAAGACQAGADAEAFQAFAEACAGQADAGAAAGIAABMQAAAHgIAAgAnBhQQgFAFAAAHQAAAIAFAFQAFAFAIAAIARAAIAAgkIgRAAQgIAAgFAGg");
	this.shape.setTransform(57.8,19.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,115.7,39.7);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","#333333"],[0,1],-65.7,-17.8,65.8,-17.8).s().p("ABEA5Iq2AAQgeAAAAgeIAAmaQAAgeAeAAITlAAQAeAAAAAeIAAGaQAAAegeAAIndAAICpFlg");
	this.shape.setTransform(65.8,41.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131.5,82.9);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjHAeQgUgGgBgLQAAgLATgHQATgIAcgCQAcgBAUAGQAVAHAAAJQABALgUAIQgTAJgcACIgJAAQgWAAgRgGgABqAKQgUgGAAgJQgBgLATgJQAUgIAcgCQAcgBAUAGQAUAHABALQAAALgTAGQgTAJgcACIgKAAQgWAAgRgGg");
	this.shape.setTransform(22.1,3.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,44.3,7.4);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.prav_rukapngкопия();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.072,1.072);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131.9,158.7);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.lev_rukapngкопия();
	this.instance.parent = this;
	this.instance.setTransform(0,0,1.072,1.072);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,81.5,221.9);


(lib.Символ5_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AGTDJIAAgoQgPgCgKgLQgLgMAAgQIAAg6IAdAAIAAA6QAAAMAPAAIAJAAQAPAAAAgMIAAgiQAAgOgMgZIgshhQgMgYAAgRIAAgYQAAgQALgMQAKgMAPgCIAAgoIAZAAIAAAoQAPACALAMQAKAMAAAQIAAAqIgdAAIAAgqQAAgNgPAAIgJAAQgPAAAAANIAAAaQAAAHALAZIAuBjQALAZAAAPIAAAmQAAAPgLANQgKALgPACIAAAogAjgDIIADhmQACgzAFgmQAGgqALgoQAMgqAUgqIAAgDIhkAAIAAglICJAAIAAAsQgUAqgMAqQgLAngGApQgFAlgCAzIgCBlgAnNDFIAAg3QAAgUAFgTQAEgSAJgSIA/iBQAGgOAAgaIAAgrQAAgHgGgFQgFgFgHAAIgRAAQgHAAgFAFQgFAFAAAHIAAArIglAAIAAguQAAgVAPgQQAQgPAUAAIAXAAQAWAAAPAQQAPAPAAAVIAAAuQAAAjgJATIg/CCQgOAmAAAWIAAASIBTAAIAAAlg");
	this.shape.setTransform(55.4,30.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(8.9,10.5,92.9,40.3);


(lib.Анимация97 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iDQAGgOAAgZIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJASIg9CFQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAGAHAAIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGgBQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAQAAAVIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgQAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAQQgPAPgWAAgAgbqEQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAlgCAyIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiOQAAgRAJgLQAIgKANgEQgLgEgIgKQgIgJAAgNIAAhLQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABLQAAANgJALQgIAJgKADQAdAQAAAaIAACOQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAARARABIAQAAQAPgBAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAHIAABJQAAARASAAIAKAAQAPAAAAgRIAAhJQAAgRgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgQQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация96 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgrQAAgHgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgPQgPgQAAgVIAAg+IAmAAIAAA7QAAARARAAIARAAQARAAAAgRIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMAMAAAWIAACaQAAAVgPAQQgPAPgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARgBAAgRIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHALAAAWIgmAAIAAjiIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHAAIgSAAQgHAAgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAVIAACXQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAWIAABxQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHABQgSAAgKAOgAglw/IADhmQACgzAFgmQAGgsALgnQAKgrAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGArQgFAmgCAyIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiOQAAgQAJgMQAIgJANgGQgLgEgIgIQgIgLAAgNIAAhKQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABKQAAAPgJAKQgIAJgKACQAdARAAAaIAACOQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgRgPgBIgQAAQgRABAAARgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgRgPAAIgKAAQgHAAgFAGgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAFAHABIARAAQAHgBAGgFQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB9QAAAHAFAFQAGAEAHAAQASAAAJgOQAIgNAAgWIAAhcQAAgHgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация95 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgsQAAgGgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAlAAAWIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgOAAgWIAAg+IAmAAIAAA7QAAARARABIARAAQARgBAAgRIAAiSQAAgIgGgFQgFgGgGAAQgLAAgHAGQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAXIAACZQAAAWgPAOQgPAQgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgPAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGAAQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAQAAAVIAACXQAAAWgPAPQgQAPgVAAgAgUm7QgWAAgPgQQgPgPAAgVIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHAAIgSAAQgHAAgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgbqEQgHAMAAAVIAABxQAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgIgFgFQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgKAAgMIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAAOgJAKQgIAIgKAEQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgSgPABIgKAAQgHgBgFAGgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHAAQASgBAJgPQAIgMAAgWIAAhdQAAgGgFgFQgGgFgHgBIgRAAQgHABgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация94 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgsQAAgGgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAARARABIARAAQARgBAAgRIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMAOAAAVIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHAKAAAXIgmAAIAAjiIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHAAIgSAAQgHAAgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAXIAABwQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHAAQgSAAgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGArQgFAlgCAzIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiOQAAgQAJgMQAIgJANgGQgLgEgIgIQgIgLAAgNIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAPgJAKQgIAJgKACQAdARAAAaIAACOQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgQgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAGAHAAIARAAQAHAAAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB8QAAAHAFAGQAGAEAHAAQASAAAJgOQAIgNAAgVIAAhdQAAgHgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация93 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgrQAAgHgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAlAAAWIAAASIBSAAIAAAmgAgUXPQgWAAgPgPQgPgPAAgWIAAg/IAmAAIAAA8QAAARARABIARAAQARgBAAgRIAAiSQAAgIgGgFQgFgFgGgBQgLABgHAFQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMAMAAAXIAACZQAAAWgPAPQgPAPgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgPAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGAAQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAQAAAVIAACXQAAAWgPAPQgQAPgVAAgAgUm7QgWAAgPgQQgPgPAAgVIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHAAIgSAAQgHAAgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgbqEQgHAMAAAVIAABxQAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgIgFgFQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgKAAgMIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAAOgJAKQgIAIgKAEQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgSgPABIgKAAQgHgBgFAGgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHAAQASgBAJgPQAIgMAAgWIAAhdQAAgGgFgFQgGgFgHgBIgRAAQgHABgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация92 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlFIgpAAIAAglIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iCQAGgOAAgaIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJATIg9CFQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMAOAAAVIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAFAHABIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGAAQgSAAgIANQgHAKAAAXIgmAAIAAjiIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgPAAgWIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAWgPAPQgPAPgWAAgAgbqFQgHAMAAAXIAABwQAAAHAFAFQAFAGAHgBIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgFgHAAQgSAAgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgpAUgrIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAkgCAzIgBBlgAgU7DQgVAAgQgPQgPgQAAgVIAAiOQAAgRAJgLQAIgKANgFQgLgEgIgIQgIgKAAgOIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAOgJALQgIAJgKACQAdARAAAaIAACOQAAAVgPAQQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgQgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgQQgPgOAAgWIAAg/IAlAAIAAA8QAAAHAFAFQAGAGAHAAIARAAQAHAAAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAWgPAOQgQAQgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgPQAIgNAAgVIAAheQAAgGgFgFQgGgGgHABIgRAAQgHgBgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация91 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAgmIAnAAIAAlEIgpAAIAAglIBMAAIAAFpIAnAAIAAAmgEgBFAhTIAAg3QAAgVAEgSQAEgSAKgTIA8iCQAGgOAAgaIAAgrQAAgHgFgGQgFgEgFAAIgRAAQgHgBgFAGQgFAFAAAHIAAArIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJASIg9CFQgPAlAAAXIAAASIBSAAIAAAlgAgUXPQgWAAgPgPQgPgPAAgWIAAg+IAmAAIAAA7QAAARARAAIARAAQARAAAAgRIAAiSQAAgIgGgFQgFgGgGABQgLgBgHAGQgHAEgGALIgggNIBMiWIhVAAIAAglIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMAOQAMANAAAWIAACZQAAAWgPAPQgPAPgWAAgAAINLIAAhQIhTAAIAAgjIBFkcIA0AAIAAEcIAhAAIAAAjIghAAIAABQgAglLYIAtAAIAAhpIAHiEgAgUDHQgVAAgQgPQgPgQAAgVIAAg+IAmAAIAAA7QAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiQQAAgHgGgFQgHgHgGABQgSAAgIANQgHALAAAWIgmAAIAAjiIB3AAIAAAlIhRAAIAAB1QAOgMAVAAQAWAAAQAPQARAPAAAWIAACXQAAAVgPAQQgQAPgVAAgAgUm7QgWAAgPgQQgPgOAAgWIAAknQAAgWAPgPQAPgPAWAAIAXAAQAWAAAPAPQAPAPAAAWIAAAuIglAAIAAgsQAAgGgFgFQgFgGgHABIgSAAQgHgBgFAGQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAVIAACXQAAAWgPAOQgPAQgWAAgAgbqFQgHAMAAAWIAABxQAAAHAFAFQAFAGAHAAIASAAQARgBAAgRIAAiQQAAgIgFgFQgFgFgHABQgSAAgKAOgAglw/IADhmQACgzAFgmQAGgsALgnQAKgqAUgrIAAgDIhiAAIAAglICHAAIAAAsQgUAqgMAqQgLAngGArQgFAmgCAyIgBBlgAgU7DQgVAAgQgPQgPgPAAgWIAAiPQAAgPAJgMQAIgJANgGQgLgDgIgJQgIgLAAgNIAAhKQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABKQAAAOgJALQgIAIgKADQAdARAAAZIAACPQAAAWgPAPQgPAPgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgRgPAAIgQAAQgRAAAAARgEgAaggnQgGAFAAAGIAABKQAAARASAAIAKAAQAPAAAAgRIAAhKQAAgRgPAAIgKAAQgHAAgFAGgEgAUglHQgWAAgPgQQgPgPAAgVIAAg/IAlAAIAAA8QAAAHAFAFQAGAFAHABIARAAQAHgBAGgFQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAVgPAPQgQAQgVAAgEgAegqrQgFAFAAAHIAAB9QAAAHAFAEQAGAFAHABQASAAAJgPQAIgNAAgWIAAhcQAAgHgFgFQgGgFgHAAIgRAAQgHAAgGAFg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGArXIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAhTIAAg4QAAgTAEgTQAEgSAKgTIA8iDQAGgOAAgZIAAgsQAAgGgFgFQgFgFgFgBIgRAAQgHAAgFAGQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAjgJATIg9CEQgPAmAAAVIAAASIBSAAIAAAmgAgUXPQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgHgGgHQgFgEgGAAQgLAAgHAEQgHAFgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAINLIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglLZIAtAAIAAhqIAHiEgAgUDHQgVAAgQgQQgPgPAAgVIAAg/IAmAAIAAA8QAAAHAFAFQAFAGAHAAIASAAQARAAAAgSIAAiQQAAgHgGgGQgHgFgGgBQgSAAgIAOQgHAKAAAYIgmAAIAAjjIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAQAAAVIAACXQAAAVgPAPQgQAQgVAAgAgUm7QgWAAgPgPQgPgQAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgsQAAgGgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAGIAABpQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAQQgPAPgWAAgAgbqEQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglw/IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgCIhiAAIAAgmICHAAIAAAsQgUAqgMAqQgLAngGAsQgFAlgCAyIgBBlgAgU7DQgVAAgQgQQgPgPAAgVIAAiOQAAgRAJgLQAIgKANgEQgLgEgIgKQgIgJAAgNIAAhLQAAgVAPgQQAPgPAWAAIAQAAQATAAAPAPQAQAQAAAVIAABLQAAANgJALQgIAJgKADQAdAQAAAaIAACOQAAAVgPAPQgPAQgVAAgAgi+KIAACQQAAARARAAIAQAAQAPAAAAgRIAAiQQAAgSgPAAIgQAAQgRAAAAASgEgAaggnQgGAFAAAHIAABJQAAARASAAIAKAAQAPAAAAgRIAAhJQAAgRgPgBIgKAAQgHABgFAFgEgAUglHQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgUIAAiDQAAgVAPgQQAPgPAWAAIAXAAQAVAAAQAPQAPAQAAAVIAAEnQAAAWgPAPQgQAPgVAAgEgAegqrQgFAFAAAGIAAB9QAAAHAFAGQAGAEAHAAQASABAJgQQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.9,-277.5,15.9,555.1);


(lib.Анимация88 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("Ag3DHIAAglIAnAAIAAlCIgpAAIAAgmIBMAAIAAFoIAnAAIAAAlg");
	this.shape.setTransform(-1.6,287.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("Ag7DHIAAg4QAAgTAEgTQAEgSAKgSIA8iCQAGgOAAgZIAAgsQAAgGgFgFQgFgGgHAAIgPAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CCQgPAmAAAVIAAASIBSAAIAAAmg");
	this.shape_1.setTransform(-1.1,223.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCCCCC").s().p("AgLDHQgVAAgQgQQgPgPABgVIAAg/IAlAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiQQAAgIgGgGQgFgEgHgBQgKABgHAEQgHAFgGAJIgfgMIBLiUIhUAAIAAgmIB4AAIAAAxIg3BlQAGgFAJAAQAWAAAMANQAMANAAAWIAACYQgBAVgPAPQgPAQgWAAg");
	this.shape_2.setTransform(-1,159);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCCCCC").s().p("AAHDHIAAhQIhTAAIAAgiIBFkbIAzAAIAAEbIAhAAIAAAiIghAAIAABQgAgmBVIAtAAIAAhoIAHiEg");
	this.shape_3.setTransform(0.1,94.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCCCCC").s().p("AgLDHQgWAAgQgQQgPgOABgWIAAg+IAlAAIAAA7QAAAHAFAFQAFAGAIAAIARAAQARgBAAgRIAAiQQAAgHgGgGQgHgFgIgBQgQAAgHAOQgIAKAAAYIglAAIAAjjIB2AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQASAPgBAWIAACXQAAAWgPAOQgPAQgWAAg");
	this.shape_4.setTransform(-0.9,30.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CCCCCC").s().p("AgMDHQgVAAgPgQQgPgPAAgVIAAklQAAgVAPgQQAPgPAVAAIAYAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgrQAAgHgFgFQgGgFgGgBIgTAAQgHABgFAFQgEAFgBAHIAABoQARgOATAAQAXAAAQAPQAPAPAAAWIAACUQAAAVgPAPQgPAQgWAAgAgSAAQgIAKAAAWIAABwQABAHAEAFQAFAFAHAAIATAAQARAAAAgRIAAiQQAAgFgFgGQgFgEgHgBQgTABgJAPg");
	this.shape_5.setTransform(-0.9,-34.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#CCCCCC").s().p("AgaDHIAChmQADgzAEgmQAHgqAKgoQAKgqAVgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAqQgFAkgCAzIgDBlg");
	this.shape_6.setTransform(-1.1,-98.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CCCCCC").s().p("AgJDHQgVAAgQgQQgPgPAAgVIAAiPQAAgNAJgMQAIgKANgEQgLgFgIgJQgJgJABgNIAAhLQAAgWAPgPQAPgPAWAAIANAAQAWAAAPAPQAQAPAAAWIAABLQAAANgJALQgIAJgKADQAdAQAAAXIAACPQAAAVgPAPQgPAQgWAAgAgYAAIAACQQABASARAAIANAAQARAAABgSIAAiQQgBgQgRAAIgNAAQgRAAgBAQgAgQibQgFAFAAAHIAABJQAAASASAAIAIAAQARAAAAgSIAAhJQAAgRgRAAIgIAAQgHAAgGAFg");
	this.shape_7.setTransform(-1.1,-163);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CCCCCC").s().p("AgMDHQgVAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAGgBIASAAQAHABAGgGQAEgFAAgHIAAh9QgQAPgTAAQgVAAgRgPQgQgQAAgTIAAiCQAAgWAPgPQAPgPAVAAIAYAAQAVAAAQAPQAPAPAAAWIAAElQAAAWgPAPQgQAPgVAAgAgVibQgFAFAAAGIAAB9QAAAIAFAEQAGAGAGgBQASAAAKgPQAIgMgBgVIAAheQAAgGgEgFQgGgGgHAAIgSAAQgGAAgGAGg");
	this.shape_8.setTransform(-0.9,-227.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CCCCCC").s().p("Ag3DHIAAglIAnAAIAAlCIgpAAIAAgmIBMAAIAAFoIAnAAIAAAlg");
	this.shape_9.setTransform(-1.6,-291.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-11.7,-324,23.5,648);


(lib.Анимация87 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("EgBGAwZIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlgEgBFAmVIAAg4QAAgTAEgTQAEgSAKgSIA8iEQAGgOAAgZIAAgsQAAgGgFgFQgFgGgFAAIgRAAQgHABgFAFQgFAFAAAGIAAAsIgmAAIAAguQAAgVAQgQQAPgPAVAAIAVAAQAVAAAQAQQAPAPAAAVIAAAuQAAAigJAUIg9CEQgPAmAAAVIAAASIBSAAIAAAmgAgUcRQgWAAgPgQQgPgPAAgVIAAg/IAmAAIAAA8QAAASARAAIARAAQARAAAAgSIAAiSQAAgIgGgFQgFgFgGgBQgLABgHAFQgHAEgGALIgggOIBMiUIhVAAIAAgmIB5AAIAAAxIg1BlQAEgFAJAAQAVAAAMANQAMANAAAWIAACaQAAAVgPAPQgPAQgWAAgAAISNIAAhQIhTAAIAAgiIBFkdIA0AAIAAEdIAhAAIAAAiIghAAIAABQgAglQbIAtAAIAAhqIAHiEgAgUIJQgVAAgQgQQgPgOAAgWIAAg+IAmAAIAAA7QAAAHAFAFQAFAGAHAAIASAAQARgBAAgRIAAiQQAAgJgGgGQgHgFgGgBQgSAAgIAOQgHAMAAAYIgmAAIAAjlIB3AAIAAAmIhRAAIAAB1QAOgNAVAAQAWAAAQAPQARAPAAAWIAACZQAAAWgPAOQgQAQgVAAgAgUh5QgWAAgPgQQgPgPAAgVIAAknQAAgVAPgQQAPgPAWAAIAXAAQAWAAAPAPQAPAQAAAVIAAAuIglAAIAAgrQAAgHgFgFQgFgFgHgBIgSAAQgHABgFAFQgFAFAAAHIAABoQAQgOATAAQAXAAAQAPQAPAPAAAWIAACWQAAAVgPAPQgPAQgWAAgAgblCQgHAMAAAWIAABwQAAAHAFAFQAFAFAHAAIASAAQARAAAAgRIAAiRQAAgGgFgGQgFgEgHgBQgSABgKAPgAglr9IADhmQACgzAFgmQAGgsALgoQAKgqAUgqIAAgDIhiAAIAAglICHAAIAAAsQgUArgMApQgLAngGAsQgFAkgCAzIgBBlgAgU2BQgVAAgQgQQgPgPAAgVIAAiPQAAgPAJgMQAIgKANgEQgLgFgIgJQgIgJAAgNIAAhLQAAgWAPgPQAPgPAWAAIAQAAQATAAAPAPQAQAPAAAWIAABLQAAANgJALQgIAJgKADQAdAQAAAZIAACPQAAAVgPAPQgPAQgVAAgAgi5IIAACQQAAASARAAIAQAAQAPAAAAgSIAAiQQAAgSgPAAIgQAAQgRAAAAASgAga7lQgGAFAAAHIAABJQAAASASAAIAKAAQAPAAAAgSIAAhJQAAgRgPAAIgKAAQgHAAgFAFgEgAUggFQgWAAgPgPQgPgPAAgWIAAg+IAlAAIAAA7QAAAHAFAFQAGAGAHgBIARAAQAHABAGgGQAFgFAAgHIAAh9QgRAPgSAAQgWAAgQgPQgRgQAAgVIAAiCQAAgWAPgPQAPgPAWAAIAXAAQAVAAAQAPQAPAPAAAWIAAEnQAAAWgPAPQgQAPgVAAgEgAeglpQgFAFAAAGIAAB9QAAAIAFAEQAGAGAHgBQASAAAJgPQAIgMAAgVIAAheQAAgGgFgFQgGgGgHAAIgRAAQgHAAgGAGgEgBGgqJIAAglIAnAAIAAlEIgpAAIAAgmIBMAAIAAFqIAnAAIAAAlg");
	this.shape.setTransform(-0.1,-2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8,-311.7,15.9,619.5);


(lib.Анимация9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#333333","#000000"],[0,1],-65.5,0,65.5,0).s().p("AprD0QgiABgBgkIAAmhQABgkAiABITXAAQAigBABAkIAAGhQgBAkgigBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.5,-24.5,131,49);


(lib.Анимация1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-304.5,-174,0.87,0.87);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-304.5,-174,609.1,348.1);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ44();
	this.instance.parent = this;
	this.instance.setTransform(1500,150,1,1,0,0,0,300,150);

	this.instance_1 = new lib.Символ44();
	this.instance_1.parent = this;
	this.instance_1.setTransform(900,150,1,1,0,0,180,300,150);

	this.instance_2 = new lib.Символ44();
	this.instance_2.parent = this;
	this.instance_2.setTransform(300,150,1,1,0,0,0,300,150);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1800,300);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4
	this.instance = new lib.Символ18();
	this.instance.parent = this;
	this.instance.setTransform(242.9,66.6,1,1,0,0,0,19.9,21.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:21.7,scaleX:0.95,scaleY:0.95,x:243.1,y:67.4},4,cjs.Ease.get(-1)).to({scaleX:0.9,scaleY:0.9,x:243.4,y:68.2},5,cjs.Ease.get(1)).wait(5).to({regY:21.6,scaleX:1,scaleY:1,x:242.9,y:66.6},5,cjs.Ease.get(1)).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ15();
	this.instance_1.parent = this;
	this.instance_1.setTransform(141.5,36.5,1,1,0,0,0,81.3,17.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:37.6},4,cjs.Ease.get(-1)).to({y:39},5,cjs.Ease.get(1)).wait(5).to({y:36.5},5,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ16();
	this.instance_2.parent = this;
	this.instance_2.setTransform(143.7,35.6,1,1,0,0,0,143.7,35.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:36.7},4,cjs.Ease.get(-1)).to({y:38.1},5,cjs.Ease.get(1)).wait(5).to({y:35.6},5,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ17();
	this.instance_3.parent = this;
	this.instance_3.setTransform(143.5,39.4,1,1,0,0,0,143.7,35.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(20));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.2,0,287.6,88.2);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ12();
	this.instance.parent = this;
	this.instance.setTransform(72.5,30.3,1,1,0,0,0,57.8,19.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(72.6,30.6,1,1,0,0,0,65.8,23.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(6.8,7,131.5,82.9);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ8();
	this.instance.parent = this;
	this.instance.setTransform(136.2,60.4,1,1,0,0,0,22.1,3.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(28).to({alpha:1},1).to({alpha:0},1).wait(18).to({alpha:1},1).to({alpha:0},1).wait(51));

	// Слой 1
	this.instance_1 = new lib.telkapngкопия();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0,1.072,1.072);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(101));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,253,263.7);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(304.6,174);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,609.1,348.1);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ3();
	this.instance.parent = this;
	this.instance.setTransform(305.6,174,1,1,0,180,0,304.6,174);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},49).to({alpha:1},51).to({alpha:0},50).to({alpha:1},50).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(304.6,174,1,1,0,0,0,304.6,174);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(201));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,610.1,348.1);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// lev_ruka.png - копия
	this.instance = new lib.Символ4();
	this.instance.parent = this;
	this.instance.setTransform(223.7,245,1,1,0,0,0,63.7,215);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:-1.3,x:223.8},9,cjs.Ease.get(-1)).to({regX:63.8,rotation:-3},10,cjs.Ease.get(1)).to({regY:215.1,rotation:-1.3,x:223.9,y:245.2},10,cjs.Ease.get(-1)).to({regX:63.7,regY:215,rotation:0,x:223.7,y:245},10,cjs.Ease.get(1)).wait(1));

	// prav_ruka.png - копия
	this.instance_1 = new lib.Символ5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(19.9,247.3,1,1,0,0,0,45.9,150.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:1.5,x:20,y:247.4},9,cjs.Ease.get(-1)).to({rotation:3.5,y:247.3},10,cjs.Ease.get(1)).to({regY:150.4,rotation:1.6,x:20.1,y:247.4},10,cjs.Ease.get(-1)).to({regY:150.3,rotation:0,x:19.9,y:247.3},10,cjs.Ease.get(1)).wait(1));

	// telka.png - копия
	this.instance_2 = new lib.Символ6();
	this.instance_2.parent = this;
	this.instance_2.setTransform(106.5,119.8,1,1,0,0,0,126.5,131.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26,-12,267.5,267.7);


(lib.Символ4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_79 = function() {
		this.parent.second.play();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(79).call(this.frame_79).wait(11));

	// Слой 4
	this.instance_1 = new lib.Анимация87("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(108.8,-257.4);

	this.instance_2 = new lib.Анимация88("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(108.8,322.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},9).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_1}]},10).to({state:[{t:this.instance_2}]},10).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-191.8},9).to({y:-128.4},10).to({y:-64.1},10).to({y:0.7},10).to({y:65},10).to({y:129.7},10).to({y:193.8},10).to({y:258.4},10).to({_off:true,y:322.9},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100.8,-569.1,15.8,619.5);


(lib.Анимация89 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Анимация87("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.2,-30.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.8,-342.3,15.9,619.5);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay();
	}
	this.frame_299 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_305 = function() {
		this.gotoAndPlay();
	}
	this.frame_400 = function() {
		this.gotoAndPlay(306);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(299).call(this.frame_299).wait(6).call(this.frame_305).wait(95).call(this.frame_400).wait(1));

	// Слой 3
	this.grafik = new lib.Символ45();
	this.grafik.parent = this;
	this.grafik.setTransform(905.8,175.7,1,1,0,0,0,900,150);

	this.timeline.addTween(cjs.Tween.get(this.grafik).to({x:-294.2},299).wait(6).to({x:905.8},0).to({x:-294.2},95).wait(1));

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(304.6,174.1,1,1,0,0,0,304.6,174);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(401));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,1805.7,348.1);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(144,135,1,1,0,0,0,118,123);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:133.9},9,cjs.Ease.get(-1)).to({y:132.6},10,cjs.Ease.get(1)).wait(15).to({y:135},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,267.5,267.7);


(lib.Символ4копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_9 = function() {
		this.stop();
	}
	this.frame_19 = function() {
		this.stop();
	}
	this.frame_29 = function() {
		this.stop();
	}
	this.frame_39 = function() {
		this.stop();
	}
	this.frame_49 = function() {
		this.stop();
	}
	this.frame_59 = function() {
		this.stop();
	}
	this.frame_69 = function() {
		this.stop();
	}
	this.frame_79 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(9).call(this.frame_9).wait(10).call(this.frame_19).wait(10).call(this.frame_29).wait(10).call(this.frame_39).wait(10).call(this.frame_49).wait(10).call(this.frame_59).wait(10).call(this.frame_69).wait(10).call(this.frame_79).wait(1));

	// Слой 3
	this.instance = new lib.Анимация89("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(101.1,-226.3);

	this.instance_1 = new lib.Анимация90("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(101.1,-162.3);
	this.instance_1._off = true;

	this.instance_2 = new lib.Анимация91("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(101.1,-97.5);
	this.instance_2._off = true;

	this.instance_3 = new lib.Анимация92("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(101.1,-33.5);
	this.instance_3._off = true;

	this.instance_4 = new lib.Анимация93("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(101.1,30.6);
	this.instance_4._off = true;

	this.instance_5 = new lib.Анимация94("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(101.1,95.3);
	this.instance_5._off = true;

	this.instance_6 = new lib.Анимация95("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(101.1,159.7);
	this.instance_6._off = true;

	this.instance_7 = new lib.Анимация96("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(101.1,224.1);
	this.instance_7._off = true;

	this.instance_8 = new lib.Анимация97("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(101.1,288.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},9).to({state:[{t:this.instance_2}]},10).to({state:[{t:this.instance_3}]},10).to({state:[{t:this.instance_4}]},10).to({state:[{t:this.instance_5}]},10).to({state:[{t:this.instance_6}]},10).to({state:[{t:this.instance_7}]},10).to({state:[{t:this.instance_8}]},10).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true,y:-162.3},9).wait(71));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:false},9).to({_off:true,y:-97.5},10).wait(61));
	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},10).to({_off:true,y:-33.5},10).wait(51));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(19).to({_off:false},10).to({_off:true,y:30.6},10).wait(41));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(29).to({_off:false},10).to({_off:true,y:95.3},10).wait(31));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},10).to({_off:true,y:159.7},10).wait(21));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(49).to({_off:false},10).to({_off:true,y:224.1},10).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(59).to({_off:false},10).to({_off:true,y:288.2},10).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(93.3,-568.6,15.8,619.5);


(lib.Символ2_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ApqD0QgkAAAAgiIAAmiQAAgkAkAAITWAAQAiAAABAkIAAGiQgBAigiAAg");
	mask.setTransform(65.5,24.5);

	// Слой 5
	this.instance_2 = new lib.Символ5_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(50.3,26.1,1,1,0,0,0,40.1,33.6);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 2 - копия
	this.second = new lib.Символ4копия();
	this.second.parent = this;
	this.second.setTransform(22.7,25.9,1,1,0,0,0,57.1,33.6);

	this.second.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.second).wait(1));

	// Слой 2
	this.instance_3 = new lib.Символ4_1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(34.2,26.2,1,1,0,0,0,57.1,33.6);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Слой 1
	this.instance_4 = new lib.Анимация9("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(65.5,23.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-1.2,131,49);


// stage content:
(lib.nastya26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.bg.gotoAndPlay(306);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.bg.gotoAndPlay(1);
		}
		
		//stage.canvas.addEventListener("mouseover", fl_Clickover.bind(this));
		
		//function fl_Clickover()
		{
		    _this.bg.grafik.gotoAndPlay(306);
		  
		}
		
		//stage.canvas.addEventListener("mouseout", fl_Clickout.bind(this));
		
		//function fl_Clickout()
		{
		    _this.bg.grafik.gotoAndPlay(1);
		    
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// btn
	this.instance = new lib.Символ14();
	this.instance.parent = this;
	this.instance.setTransform(438.4,247.9,0.76,0.76,0,0,0,143.7,35.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// schet
	this.instance_1 = new lib.Символ2_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(438.4,135.7,1.668,1.668,0,0,0,65.7,24.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// text2
	this.instance_2 = new lib.Символ13();
	this.instance_2.parent = this;
	this.instance_2.setTransform(439.3,38.7,1.026,1.026,0,0,0,139.1,17.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// text
	this.instance_3 = new lib.Символ11();
	this.instance_3.parent = this;
	this.instance_3.setTransform(65.8,22.7,1,1,0,0,0,65.8,23.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// telka
	this.instance_4 = new lib.Символ7();
	this.instance_4.parent = this;
	this.instance_4.setTransform(154.5,175.8,1,1,0,0,0,133.7,133.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// bg
	this.bg = new lib.Символ9();
	this.bg.parent = this;
	this.bg.setTransform(301.1,146.1,1,1,0,0,0,305.1,174.1);

	this.timeline.addTween(cjs.Tween.get(this.bg).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(296,-717,1805.7,1187.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;