(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,220,36);


(lib.tovar = function() {
	this.initialize(img.tovar);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,240,240);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AMkCDIgQgGQgJgEgGgGQgFgFgGgIQgGgLgIgdQgEgRgBgqQAAgVAFgkQADgQALgYQAGgIAFgGQAGgFAJgFQAHgEAJgBIATgDIASADQAKABAGAEQAIAFAGAFQAHAGAFAIQAMAYACAQQAFAkAAAVQgCAqgDARQgIAdgGALQgFAIgHAFQgGAGgIAEQgGADgKADIgSABgAMthMQgFAEgDAIQgDAKAAAPIAABVQABAQACAJQADAJAFADQADADAHAAQAFAAAFgDQAEgDADgJIADgZIAAhVIgDgZQgDgIgEgEQgFgCgFAAQgHAAgDACgAJwCDIgQgGQgHgEgGgGQgHgFgFgIQgHgLgIgdQgEgRgBgqQAAgVAFgkQADgQAMgYQAFgIAHgGQAGgFAHgFQAIgEAIgBIATgDIASADQAJABAIAEQAHAFAGAFQAHAGAFAIQAMAYACAQQAGAkAAAVQgCAqgEARQgIAdgGALQgFAIgHAFQgGAGgHAEQgIADgJADIgSABgAJ5hMQgEAEgDAIQgEAKAAAPIAABVQABAQADAJQADAJAEADQAEADAGAAQAFAAAFgDQAEgDADgJQACgJABgQIAAhVQgBgPgCgKQgDgIgEgEQgFgCgFAAQgGAAgEACgADbB9QgGgCAAgHIADgeQABgKAJAEQAPAIARgBQAJABAHgCQAGgDAFgFQAEgEADgIQADgIgBgKQABgKgDgHQgCgHgFgEQgEgGgHgCQgIgCgIAAQgRgBgLAFQgKADAAgJIAAh5QAAgIAGAAIB1AAQAHAAgBAIIAAAdQABAIgHAAIhBAAIAAAvIAOgBQAOAAAMAFQALAEAIAKQAJALAFANQAEAPAAAUQAAATgFAQQgGAQgLALQgKALgQAGQgQAGgWgBQgkgCgOgFgAmFB/QgOgHgLgLQgKgNgFgSQgGgSAAgZQAAgXAGgRQAFgTAKgMQALgMAOgGQAOgGATABQAUgBAOAGQAPAGAKAMQAKAMAFATQAGARAAAXQAAAZgGASQgFASgKANQgKALgPAHQgOAFgUAAQgTAAgOgFgAl0gJQgDAHgBAKIAAA4QABAKADAIQAFALALAAQAMAAAFgLQADgIACgKIAAg4QgCgKgDgHQgFgLgMgBQgLABgFALgAGOCBQgIAAABgIIAAgYQAAgIAFgHIAYgeIAZggQALgUAGgOQAIgTAAgNQAAgQgIgIQgIgIgPAAQgSAAgPAHQgDAAgDgBQgCgBgBgEIgCgeQAAgGAFgBQAMgGANgCQAMgDAPgBQASAAAQAGQAOAGAKAJQAKAKAFANQAFAPAAASQAAASgGATQgFARgKARQgJAQgNARIgaAcIA+AAQAHAAgBAGIAAAgQABAIgHAAgAAKB5IAAjqQAAgIAGAAIBbACQALACAKAEQAJAEAIAGQAIAFAFAIQAHAIAEAJIAIAWQAHAiAAAUQgDAogEAQQgDALgFAKQgEAKgHAHQgFAIgIAHQgIAFgJAEIgVAGIhbACQgGAAAAgIgABDBTIAPAAQALAAAJgEQAHgFAFgIQAGgJACgQQACgPAAgXQAAgVgCgPQgCgQgGgJQgFgJgHgEQgJgEgLAAIgPAAgAiZCBQgHAAAAgIIAAhnQAAgXgFgIQgEgHgJgBQgMAAgGAJIAACFQAAAIgHAAIgsAAQgIAAAAgIIAAiqQAAgHAIAAIAsAAQAHAAAAAHIAAAGQAGgIALgFQAKgDAMAAQAOAAAKADQAJAFAHAJQAHAJAFAOQACAOAAATIAABrQABAIgHAAgAnzCBQgFAAgDgGIghhVIAABTQABAIgHAAIgsAAQgHAAAAgIIAAj3QAAgFAHAAIAsAAQAHAAgBAFIAACMIAehAQACgFAHgBIAtAAQAKABgFAJIgmBIIArBeQAEAIgKABgAqoCBQgHAAAAgIIAAiqQAAgHAHAAIAsAAQAHAAAAAHIAACqQAAAIgHAAgAsSCBQgHAAgCgHIgyiXIAACWQAAAIgHAAIgqAAQgHAAAAgIIAAjqQAAgIAHAAIA4AAQAHAAACAHIAzCXIAAiWQgBgIAHAAIAqAAQAHAAgBAIIAADqQABAIgHAAgAqqhTQgIgGAAgOQAAgPAIgGQAHgIAQABQARgBAIAIQAJAGAAAPQAAAOgJAGQgIAHgRAAQgQAAgHgHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ47, new cjs.Rectangle(-90.2,-13.2,180.4,26.5), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AAXCxQgJAAAAgJIAAlKQAAgIAJgBIA9AAQAJABAAAIIAAAIQAIgKAMgGQAMgGAQAAQATAAAQAIQAPAIALAQQAKARAGAZQAGAZAAAiQAAAhgGAYQgGAYgKASQgLAQgPAIQgQAJgTgBQgPABgNgHQgMgFgIgLIAABmQAAAJgJAAgABdhvIAACGQALALAJAAQAJAAAGgEQAGgFAEgJQAFgMADgvIgCgmQgCgPgEgIQgEgJgGgFQgGgEgJAAQgLAAgJALgAItBPQgXgIgPgRQgPgRgIgZQgIgYAAghQAAgfAHgZQAHgYAOgRQANgRATgIQATgJAXAAQAaAAATAJQATAJANARQANARAGAZQAHAZAAAhIgBAPQAAAJgLAAIh1AAQABAPADAJQAEAKAHAGQAGAGAKACQAIADAOAAQAYAAAUgJQALgEABALIACAiQABAIgHADQgMAGgQADQgPACgSAAQgdAAgWgJgAJphFQAAgegHgMQgGgLgOAAQgNAAgGALQgHAMAAAeIA1AAIAAAAgAiWBPQgWgIgQgRQgPgRgIgZQgHgYAAghQAAgfAHgZQAHgYANgRQANgRATgIQATgJAXAAQAaAAATAJQAUAJANARQAMARAHAZQAGAZAAAhIAAAPQgBAJgLAAIh1AAQABAPAEAJQAEAKAGAGQAGAGAKACQAJADANAAQAZAAATgJQALgEABALIADAiQAAAIgGADQgMAGgQADQgPACgSAAQgdAAgXgJgAhZhFQAAgegHgMQgGgLgOAAQgOAAgGALQgHAMAAAeIA2AAIAAAAgAMBBTQgJAAAAgKIAAi+IgwAAQgJAAAAgKIAAgjQAAgIAJgBICvAAQAJABAAAIIAAAjQAAAKgJAAIgvAAIAAC+QAAAKgKAAgAGGBTQgJAAAAgKIAAhgIgyAAIAABgQAAAKgJAAIg7AAQgJAAAAgKIAAjrQAAgIAJgBIA7AAQAJABAAAIIAABVIAyAAIAAhVQAAgIAJgBIA7AAQAJABAAAIIAADrQAAAKgJAAgAllBTQgJAAAAgKIAAi+IgwAAQgJAAAAgKIAAgjQAAgIAJgBICuAAQAKABAAAIIAAAjQAAAKgKAAIgvAAIAAC+QAAAKgJAAgAoCBTQgJAAAAgKIAAhgIgyAAIAABgQAAAKgJAAIg7AAQgJAAAAgKIAAjrQAAgIAJgBIA7AAQAJABAAAIIAABVIAyAAIAAhVQAAgIAJgBIA7AAQAJABAAAIIAADrQAAAKgJAAgAryBTQgJAAAAgKIAAhyIg6B0QgEAIgIAAIg1AAQgJAAAAgKIAAjrQAAgIAJgBIA2AAQAJABAAAIIAAB0IA6h1QAEgIAJAAIA0AAQAJABAAAIIAADrQAAAKgJAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(-89.6,-17.7,179.3,35.4), null);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AjQChQgKAAADgKIAQhEIhAjjQgDgLAKAAIA4AAQAIAAABAHIAbCKIAciKQACgHAGAAIA5AAQAKAAgCALIhQEpQgBAIgKAAgAp0BJQgSgIgNgPQgNgPgHgWQgGgXAAgeQAAgeAGgWQAHgXANgQQANgOASgIQASgHAYAAQAXAAASAHQATAIAMAOQANAQAHAXQAHAWAAAeQAAAegHAXQgHAWgNAPQgMAPgTAIQgSAHgXAAQgYAAgSgHgApfhgQgEAIgBAOIAABFQABANAEAIQAHAPAOAAQAOAAAGgPQAEgIACgNIAAhFQgCgOgEgIQgGgPgOAAQgOAAgHAPgALSBLQgIAAAAgJIAAjVQAAgIAIAAIBKAAQAXAAARAEQASAEALAIQAMAHAFAMQAGANAAAQQAAAOgGALQgGAMgMAHQAQAGAIAOQAJAOAAARQAAARgGANQgGAOgMAJQgMAJgSAEQgSAFgZAAgAMQAfIAKAAQAQAAAGgGQAGgGAAgPQAAgOgGgGQgHgGgPAAIgKAAgAMQhAIAIAAQANAAAGgEQAGgGAAgNQAAgOgGgGQgFgEgOAAIgIAAgAIJBLQgJAAAAgJIAAhnIg0BpQgEAHgIAAIgwAAQgIAAAAgJIAAjVQAAgIAIAAIAxAAQAIAAAAAIIAABpIA1hqQAEgHAIAAIAvAAQAJAAAAAIIAADVQAAAJgJAAgAEuBLQgGAAgEgGIgphhIAABeQAAAJgIAAIg3AAQgJAAAAgJIAAjVQAAgIAJAAIA3AAQAIAAAAAIIAABZIAlhbQADgGAHAAIA5AAQANAAgFAMIguBkIAzBqQACAFgCADQgCAEgGAAgABQBLQgIAAAAgJIAAitIgrAAIAACtQAAAJgHAAIg1AAQgJAAAAgJIAAjVQAAgIAJAAIClAAQAIAAAAAIIAADVQAAAJgIAAgAlRBLQgGAAgEgGIgphhIAABeQAAAJgIAAIg3AAQgJAAAAgJIAAjVQAAgIAJAAIA3AAQAIAAAAAIIAABZIAlhbQADgGAHAAIA5AAQANAAgFAMIguBkIAzBqQACAFgCADQgCAEgGAAgAsGBLQgJAAAAgJIAAitIgqAAIAACtQAAAJgIAAIg2AAQgJAAAAgJIAAjVQAAgIAJAAICmAAQAIAAAAAIIAADVQAAAJgIAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ39, new cjs.Rectangle(-89.7,-16.1,179.4,32.3), null);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AEhBQQgOgFgKgLQgKgLgFgRQgFgQAAgUQAAgUAFgQQAEgQAJgLQAIgLANgFQAMgGAPAAQAQAAANAGQAMAGAJALQAIALAEAQQAEAQAAAUIAAAKQAAAGgIAAIhLAAQABAKACAGQACAGAFAFQADADAHACIAOABQAQAAANgFQAHgDAAAHIACAWQAAAGgEABQgIAEgKACQgKACgLAAQgTAAgPgGgAFIgQQAAgTgEgIQgEgHgJAAQgJAAgEAHQgEAIAAATIAiAAIAAAAgACkBQQgPgFgLgLQgKgLgFgRQgFgQAAgUQAAgUAFgQQAFgPAKgLQALgLAPgGQAPgGATAAQAQAAAOAEQAFACAAAFIgDAXQAAAHgHgDQgJgDgJAAQgIAAgHAEQgGACgFAGQgFAHgCAJQgDAKAAAMQAAAOADAJQADAKAEAGQAFAGAIADQAGACAJAAQAJAAAJgCQAHgDAAAIIACAWQAAAFgFACQgMAEgSAAQgTAAgQgGgAl0BPQgFgCABgEIACgXQAAgHAIADQAQAGAPAAQAMAAAHgEQAGgEAAgIQAAgKgJgGQgFgCgHgCIgUgCQgGAAAAgGIAAgUQAAgGAGAAQAWgBAJgEQAIgFAAgJQAAgHgFgDQgFgEgLAAQgRAAgOAEQgHADgBgHIgCgWQAAgEAFgCQAOgEAegCQARAAAMADQANAEAIAGQAIAFAEAJQAEAIAAAMQAAAMgHAKQgHAKgLAEQANAFAHAKQAGALAAANQAAALgEAJQgEAJgJAHQgIAGgNADQgNAEgRAAQghgCgNgFgAjbBSQgIgDgGgHQgGgGgEgKQgDgKAAgMQAAgOAEgLQADgJAIgHQAIgHAMgDQAKgEAQAAIAQAAIAAgKQAAgLgFgEQgFgEgMAAQgWACgMAFQgHADAAgHIgDgVQAAgFAEgCQALgFAMgCQAMgDANAAQATAAANAEQALAFAIAIQAHAIACANQADALAAARIAABfQAAAGgFAAIgnAAQgFAAAAgGIAAgFQgGAHgIAEQgIADgKAAQgKAAgIgDgAjDAPQgEAFAAAMQAAAKAEAEQAEAEAHAAQAJAAAGgGIAAgjIgMAAQgKAAgEAGgAgSBSQgGAAAAgGIAAiXQAAgGAGAAIA0AAQAQAAAMADQAMADAIAFQAJAGAEAIQAEAJAAALQAAAKgEAJQgFAIgIAFQALAEAGAJQAGAKAAANQAAAMgEAJQgEAKgJAGQgJAGgMAEQgNADgSAAgAAZAyIAHAAQALAAAEgDQAFgEAAgLQAAgLgFgEQgEgEgLAAIgHAAgAAZgQIAGAAQAJAAAEgEQAEgDAAgKQAAgKgEgDQgDgEgKAAIgGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ38, new cjs.Rectangle(-37.7,-8.6,75.5,17.2), null);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AlXByQgHAAABgGIAAjUQgBgGAHAAIAnAAQAGAAAAAGIAAAFQAFgHAIgDQAIgEAKAAQAMAAAKAFQAKAFAHALQAHALADAQQAEAQAAAVQAAAWgEAPQgDAQgHALQgHAKgKAGQgKAFgMAAQgKAAgIgEQgIgDgFgHIAABBQAAAGgGAAgAkqhHIAABWQAHAHAGAAQAGAAADgCQAFgEABgFQAEgIACgfIgBgXQgBgKgEgGQgBgGgFgCQgDgDgGAAQgHAAgGAHgAAoBVQgGAAAAgGIAAgaIgtAAIAAAaQAAAGgGAAIgoAAQgFAAgBgGIAAg2QABgGAFAAIAHAAQAHgTAJgpQADgVAEgqQAAgGAFAAIBWAAQAGAAgBAGIAAB7IAKAAQAHAAAAAGIAAA2QAAAGgHAAgAAKgdQgFAZgGAXIAYAAIAAhgIgHAAQgCAXgEAZgACMAzQgQgFgKgLQgKgLgGgQQgEgPAAgVQAAgUAEgQQAGgQAKgLQALgLAOgGQAQgFATAAQARAAAMADQAGACgBAGIgCAWQAAAHgHgCQgKgDgIAAQgJAAgGADQgGADgFAGQgFAGgCAKQgDAJAAANQAAAOADAKQACAIAFAHQAFAFAHADQAHADAJAAQAJAAAJgDQAGgCABAHIACAWQAAAGgGACQgLADgSAAQgTAAgQgGgAidAzQgPgFgKgLQgJgLgFgQQgFgPAAgVQAAgVAFgQQAEgPAIgLQAJgLAMgGQANgFAOAAQASAAAMAGQAMAFAJAMQAHAKAFAQQAEARAAAVIAAAKQAAAGgIAAIhMAAQABAJADAGQACAGAEAEQAEAEAHACIANABQAQAAANgGQAHgCABAHIABAWQABAFgEACQgIADgLACQgJACgLAAQgTAAgPgGgAh2gsQAAgTgEgIQgFgHgIAAQgJAAgEAHQgFAIAAATIAjAAIAAAAgAm1AzQgPgFgLgLQgKgLgGgQQgFgPAAgVQAAgUAFgQQAGgQAKgLQALgLAPgGQAPgFATAAQAQAAAOADQAFACgBAGIgCAWQAAAHgHgCQgJgDgJAAQgIAAgGADQgIADgEAGQgFAGgCAKQgDAJAAANQAAAOADAKQACAIAGAHQAEAFAIADQAGADAJAAQAJAAAIgDQAIgCgBAHIADAWQgBAGgFACQgLADgSAAQgUAAgPgGgAFqA1QgHAAAAgGIAAiXQAAgGAHAAIA0AAQAQAAANADQAMADAIAGQAIAFAEAIQAEAJAAAMQAAAKgEAIQgFAIgIAFQALAEAGAKQAGAKAAAMQAAANgEAJQgEAJgJAHQgJAGgNADQgMADgRAAgAGUAWIAIAAQALAAAFgEQAFgEAAgLQAAgKgFgEQgFgEgLAAIgIAAgAGUgtIAGAAQAKAAAFgDQAEgEAAgJQAAgKgEgEQgFgDgKAAIgGAAgAECA1QgFAAAAgGIAAh6IggAAQgFAAAAgGIAAgXQAAgGAFAAIByAAQAFAAAAAGIAAAXQAAAGgFAAIgfAAIAAB6QAAAGgGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ37, new cjs.Rectangle(-48.5,-11.4,97,22.9), null);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AAVBiQgFAAgBgFIAAi2QABgFAFAAIAiAAQAEAAAAAFIAAAEQAFgGAGgDQAIgDAIAAQAKAAAJAEQAJAFAGAJQAGAIADAPQADAOAAASQAAASgDAOQgDANgGAKQgGAJgJAEQgJAFgKAAQgIAAgIgEQgGgCgFgHIAAA5QAAAFgEAAgAA7g+IAABLQAHAGAEAAQAGAAACgCQAEgDACgFQAEgHAAgaIgBgUQAAgJgDgFQgCgFgEgCQgCgCgGAAQgGAAgFAFgAjkArQgEgBABgEIABgTQABgHAGADQANAFAOAAQALAAAEgEQAGgDAAgHQAAgHgIgFIgKgEIgSgCQgEAAAAgFIAAgSQAAgFAEAAQAUgBAHgEQAJgDAAgIQAAgHgGgDQgEgCgKAAQgOAAgMADQgHACAAgFIgBgTQgBgEAEgBQANgEAagBQAOAAALACQALADAGAFQAHAFADAIQAFAHAAAJQgBALgGAJQgGAHgJAFQALAFAGAJQAFAIAAALQAAAKgDAHQgEAJgIAFQgGAFgMADQgLADgPAAQgcgBgLgFgAlFAsQgLgFgIgIQgIgKgEgNQgEgOAAgSQAAgSAEgOQAEgOAIgJQAIgJALgFQAMgEANAAQAPAAALAEQALAFAHAJQAJAJADAOQAFAOAAASQAAASgFAOQgDANgJAKQgHAIgLAFQgLAFgPAAQgNAAgMgFgAk4g6QgCAFgCAIIAAAqQACAHACAFQAEAKAIAAQAIAAAFgKQACgFACgHIAAgqQgCgIgCgFQgFgJgIAAQgIAAgEAJgAGOAuQgHgDgFgGQgGgFgDgIQgCgJAAgLQAAgKADgKQAEgJAGgGQAHgFAJgEQAKgDAOAAIANAAIAAgIQAAgKgEgDQgEgEgKAAQgUACgKAEQgGADgBgGIgCgSQAAgFAEgBQAKgEAKgDQAKgBALAAQARAAAKADQAKAEAHAHQAGAHACAKQADAKAAAPIAABSQAAAFgFAAIghAAQgFAAAAgFIAAgFQgFAHgHADQgGADgJAAQgIAAgIgDgAGjgLQgEAFAAAJQAAAIADAEQAEAEAGAAQAJAAAEgGIAAgdIgLAAQgHAAgEAFgAClAuQgHgDgGgGQgFgFgDgIQgCgJgBgLQABgKACgKQAEgJAGgGQAHgFAKgEQAKgDANAAIAOAAIAAgIQgBgKgEgDQgEgEgJAAQgVACgJAEQgHADAAgGIgCgSQgBgFAFgBQAJgEAKgDIAWgBQAQAAALADQAKAEAHAHQAFAHADAKQACAKAAAPIAABSQAAAFgFAAIghAAQgEAAAAgFIAAgFQgFAHgHADQgHADgIAAQgIAAgIgDgAC5gLQgDAFAAAJQAAAIADAEQADAEAHAAQAIAAAFgGIAAgdIgLAAQgIAAgEAFgAErAuQgFAAAAgFIAAhqIgbAAQgFAAAAgFIAAgTQAAgFAFAAIBhAAQAGAAAAAFIAAATQAAAFgGAAIgaAAIAABqQAAAFgGAAgAhrAuQgFAAAAgFIAAiCQAAgFAFAAIAtAAQANAAALACQALADAHAEQAHAFAEAHQADAIAAAKQAAAJgDAGQgEAIgIAEQAKADAFAJQAGAIgBALQABAKgEAIQgEAIgHAFQgIAGgKADQgLADgPAAgAhFATIAFAAQALAAADgEQAEgDAAgJQAAgJgEgEQgEgDgKAAIgFAAgAhFgmIAEAAQAJAAAEgDQADgEAAgIQAAgJgDgDQgEgCgJAAIgEAAgAneAuQgFAAAAgFIAAiCQAAgFAFAAIAtAAQAOAAALACQAKADAIAEQAGAFAEAHQAEAIAAAKQAAAJgEAGQgEAIgHAEQAKADAFAJQAFAIAAALQAAAKgDAIQgEAIgHAFQgIAGgLADQgLADgPAAgAm4ATIAGAAQAKAAAEgEQADgDAAgJQAAgJgDgEQgEgDgKAAIgGAAgAm4gmIAFAAQAIAAADgDQAFgEAAgIQAAgJgFgDQgDgCgIAAIgFAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ36, new cjs.Rectangle(-48.4,-9.8,96.8,19.7), null);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AhsB7QgFAAAAgFIAAi2QAAgFAFAAIAiAAQAFAAAAAFIAAAEQAEgGAHgDQAHgDAIAAQAMAAAIAEQAIAFAGAJQAGAIADAPQADAOAAARQAAASgDAPQgDANgGAKQgGAJgIAEQgIAFgMAAQgHAAgIgEQgHgCgEgHIAAA5QAAAFgFAAgAhFglIAABLQAGAGAFAAQAFAAADgCQAEgDACgFQADgHABgbIAAgTQgCgJgCgFQgCgFgEgCQgDgCgFAAQgGAAgFAFgAE/BFQgNgFgKgJQgIgJgFgOQgEgOAAgSQAAgQAEgOQAFgOAIgJQAJgKAOgEQANgFAQAAQAOAAALADQAFACgBAEIgBATQAAAGgGgCQgJgCgHAAQgHAAgGACQgGADgDAFQgFAGgCAHQgCAJAAAKQAAAMACAIQADAIAEAGQAEAFAGACQAGADAHAAQAJAAAGgDQAGgCABAHIABASQABAFgFACQgKADgPAAQgRAAgNgFgAjMBFQgNgFgJgJQgIgJgEgOQgFgOAAgSQAAgRAFgOQADgNAIgKQAHgJALgEQAKgFANAAQAOAAALAFQALAEAHAKQAHAKAEANQADAOAAARIAAAJQAAAFgHAAIhAAAQAAAIACAGQACAFAEAEQADADAGABQAFACAHAAQAOAAAKgFQAHgCAAAGIACASQAAAFgEACQgGADgJABQgJACgKAAQgQAAgMgFgAirgNQAAgQgEgIQgDgFgIAAQgHAAgEAFQgDAIAAAQIAdAAIAAAAgAk4BIIgRgFQgIgDgHgFIgMgLIgJgOQgFgJgCgJIgGgnIACgXIAEgTQACgJAFgIQADgHAGgHQAFgGAHgFQAGgFAIgDQAIgEAJgBQAJgCAKAAQAPAAAVAFQAFADAAAEIgCAZQgBAIgGgEQgMgFgOAAQgKAAgIAFQgIAEgGAHQgGAIgDAMQgDALAAAQQAAAPADALQADALAGAIQAGAHAIAFQAIADALAAQAOAAAMgEQAHgDAAAHIABAYQABAFgFACQgHADgKACIgSABQgKAAgKgCgADjBHQgFAAAAgFIAAhAIggBBQgCAEgGAAIgdAAQgFAAAAgFIAAiCQAAgFAFAAIAeAAQAFAAAAAFIAABAIAhhBQACgEAFAAIAcAAQAGAAAAAFIAACCQAAAFgGAAgAAZBHQgFAAAAgFIAAiCQAAgFAFAAIAtAAQAOAAAKACQALADAHAEQAHAFADAHQAFAIAAAKQAAAJgFAGQgDAIgIAEQAKADAGAIQAFAIAAAMQAAAKgEAIQgEAIgIAFQgGAGgMADQgLADgPAAgAA+AsIAHAAQAJAAAEgEQAEgDAAgJQAAgKgEgEQgEgDgJAAIgHAAgAA+gNIAFAAQAJAAADgDQAEgEAAgIQAAgJgEgDQgDgCgJAAIgFAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ35, new cjs.Rectangle(-37.8,-12.3,75.7,24.7), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AJECsQgKAAAAgKIAAlEQAAgIAKgBIA8AAQAJABAAAIIAAByIAZAAQAXAAATAIQATAHANAOQANAOAGAUQAHAUAAAaQAAAagHAUQgGAVgNAOQgNAPgTAHQgTAIgXAAgAKJBtIATAAQAOAAAIgNQAIgLAAgYQAAgXgIgMQgIgLgOgBIgTAAgAGOCsQgKAAAAgKIAAkLIg9AAQgKgBABgIIAAgwQgBgIAKgBIDNAAQAJABAAAIIAAAwQAAAIgJABIg9AAIAAELQAAAKgKAAgADdCsQgJAAAAgKIAAjPIhFDQQgCAJgKAAIhNAAQgKAAAAgKIAAlEQAAgIAKgBIA6AAQAJABAAAIIAADQIBFjQQADgJAJAAIBNAAQAKABAAAIIAAFEQAAAKgKAAgAhSCsQgIAAgBgKIAAkLIhKAAIAAELQAAAKgJAAIhAAAQgJAAAAgKIAAlEQAAgIAJgBIDcAAQAKABgBAIIAAFEQABAKgKAAgAnHCsQgOAAAFgNIAZhRIhUjsQgDgNAMAAIA9AAQAIABACAHIAmCFIAqiFQACgIAJAAIA+AAQANAAgEANIhmFCQgCAIgIAAgApgCsQgIgBgCgHIhIiiIAACgQAAAKgKAAIg/AAQgKAAAAgKIAAlEQAAgIAKgBIA/AAQAKABAAAIIAACKIA9iLQAEgIAHAAIBCAAQAGABACAEQADAEgDAFIhICSIBXCpQACAFgCAEQgDAEgGABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(-77.4,-17.1,154.8,34.3), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJECsQgKAAAAgKIAAlEQAAgIAKgBIA8AAQAJABAAAIIAAByIAZAAQAXAAATAIQATAHANAOQANAOAGAUQAHAUAAAaQAAAagHAUQgGAVgNAOQgNAPgTAHQgTAIgXAAgAKJBtIATAAQAOAAAIgNQAIgLAAgYQAAgXgIgMQgIgLgOgBIgTAAgAGOCsQgKAAAAgKIAAkLIg9AAQgKgBABgIIAAgwQgBgIAKgBIDNAAQAJABAAAIIAAAwQAAAIgJABIg9AAIAAELQAAAKgKAAgADdCsQgJAAAAgKIAAjPIhFDQQgCAJgKAAIhNAAQgKAAAAgKIAAlEQAAgIAKgBIA6AAQAJABAAAIIAADQIBFjQQADgJAJAAIBNAAQAKABAAAIIAAFEQAAAKgKAAgAhSCsQgIAAgBgKIAAkLIhKAAIAAELQAAAKgJAAIhAAAQgJAAAAgKIAAlEQAAgIAJgBIDcAAQAKABgBAIIAAFEQABAKgKAAgAnHCsQgOAAAFgNIAZhRIhUjsQgDgNAMAAIA9AAQAIABACAHIAmCFIAqiFQACgIAJAAIA+AAQANAAgEANIhmFCQgCAIgIAAgApgCsQgIgBgCgHIhIiiIAACgQAAAKgKAAIg/AAQgKAAAAgKIAAlEQAAgIAKgBIA/AAQAKABAAAIIAACKIA9iLQAEgIAHAAIBCAAQAGABACAEQADAEgDAFIhICSIBXCpQACAFgCAEQgDAEgGABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.4,-17.1,154.8,34.3);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AtwEfQg7ABAAg8IAAnHQAAg8A7ABIbhAAQA7gBAAA8IAAHHQAAA8g7gBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(-94,-28.7,188.1,57.5), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#7FFFED","#00CCFF"],[0,1],0,28.2,0,-28.1).s().p("AtwEfQg7ABAAg8IAAnHQAAg8A7ABIbhAAQA7gBAAA8IAAHHQAAA8g7gBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(-94,-28.7,188.1,57.5), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ay5fTMAAAg+lMAlzAAAMAAAA+lg");
	this.shape.setTransform(1,-5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(-120,-205.3,242.1,400.6), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AHTCrQgHAAAAgHIAAj+QAAgGAHAAIAvAAQAHAAAAAGIAAAGQAGgIAJgEQAKgFAMAAQAPAAAMAHQAMAFAIANQAIANAEAUQAFATAAAZQAAAZgFAUQgEASgIANQgIANgMAGQgMAHgPAAQgMAAgKgFQgJgEgGgIIAABOQAAAHgHAAgAIJgyIAABmQAIAJAIAAQAGAAAFgDQAEgDADgIQAFgJACglIgCgcQgBgLgEgIQgDgHgEgDQgFgDgGAAQgJAAgHAJgABqBlIgSgGQgIgEgHgGQgGgGgGgIQgHgLgKgdQgEgQgCgoQAAgbAHgoQAEgOAFgLQAFgLAGgJQAGgIAIgGQAIgHAJgEQAMgFAegDQAQAAAeAHQAGADAAAFIgCAiQAAAEgEABQgDACgDgBQgPgIgRABQgUABgHAIQgGAGgEAMQgFAMgBASQAIgGAKgDQAJgDALAAQAPAAAMAGQAMAGAIAKQAJAMAEAQQAEASAAAVQAAAVgFARQgFARgKAMQgKALgPAHQgPAGgTAAgABlgVQABAmADAPQACALAFAGQAFAGAIABQAJAAAFgLQAGgLAAgWQAAgWgGgKQgFgKgLAAQgNAAgJAJgALuBiQgHABAAgIIAAhLIgnAAIAABLQAAAIgGgBIguAAQgHABAAgIIAAi1QAAgGAHAAIAuAAQAGAAAAAGIAABCIAnAAIAAhCQAAgGAHAAIAtAAQAHAAAAAGIAAC1QAAAIgHgBgAFCBiQgHABAAgIIAAi1QAAgGAHAAIByAAQAGAAAAAGIAAAbQAAAIgGgBIg8AAIAACTQAAAIgIgBgAg5BiQgIABAAgIIAAgqIhUAAQgHAAAAgHIAAggQAAgLAFgKIBJiUQACgGAHAAIA7AAQAHAAAAAHIAACeIANAAQAHAAAAAGIAAAkQAAAHgHAAIgNAAIAAAqQAAAIgHgBgAhrAAIAqAAIAAhXgAk1BiQgKAAADgJIBBjMIhRAAQgHAAAAgHIAAgkQAAgHAHAAICNAAQAHAAAAAHIAAAjQAAAIgCAHIhADIQgCAGgHAAgAoiBiQgHABAAgIIAAi5IgaAYQgGAEgEgGIgVgcQgDgFAEgEIA6gzQAFgFAIAAIApAAQAHAAAAAHIAAD5QAAAIgHgBgArgBiQgHABAAgIIAAi5IgaAYQgGAEgEgGIgVgcQgDgFAEgEIA5gzQAGgFAIAAIApAAQAHAAAAAHIAAD5QAAAIgHgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(-80.2,-17.1,160.5,34.2), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(5.4,1,1).p("AvJBoIeTjP");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(-99.6,-13,199.4,26.1), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F5307B").ss(5.4,1,1).p("AvJBoIeTjP");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(-99.6,-13,199.4,26.1), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7D7C97").s().p("AHPCrQgGAAgBgFIAAgCIAAj+QAAgHAHABIAvAAQAHgBAAAHIAAAGQAGgIAJgEQAKgFAMAAQAPAAAMAGQAMAHAIAMQAIANAEATQAFATAAAZQAAAZgFAVQgEASgIANQgIANgMAGQgMAGgPABQgMAAgKgGQgJgDgGgIIAABOIAAACQgBAFgGAAgAIFgzIAABnQAIAIAHAAQAHAAAFgCQAEgEADgHQAFgJACgmIgCgcQgCgLgDgHQgDgHgEgDQgFgEgHABQgIAAgHAIgAA8BfQgGgCAAgFIADgiQAAgDADgCQADgCADACQAPAHARAAQAIAAAHgDQAHgCAFgFQAHgHADgKQAFgNABgSQgIAGgKADQgKADgKAAQgPAAgMgGQgMgFgIgLQgJgLgEgRQgFgRAAgVQAAgWAGgSQAFgQAKgMQAKgMAPgGQAPgGATAAIAUADQAJABAJAEQAIAEAHAGQAHAGAFAIQANAYAEARQAFAjAAAWQgCAugEATQgDAOgFALQgFALgHAIQgGAJgIAHQgIAFgJAEQgJAEgLADIgWACQgggDgOgFgABphwQgGAKAAAXQAAAXAGAKQAFAJALAAQANAAAJgJQAAgUgEghQgCgLgFgHQgFgFgIAAQgJgBgFALgAiBBfQgGgCAAgFIADgiQAAgDADgCQADgCADACQAPAHARAAQAIAAAHgDQAHgCAFgFQAGgHAEgKQAFgNABgSQgIAGgKADQgKADgKAAQgPAAgMgGQgMgFgIgLQgJgLgEgRQgFgRAAgVQAAgWAGgSQAFgQAKgMQAKgMAPgGQAPgGATAAIAUADQAJABAJAEQAIAEAHAGQAHAGAFAIQAMAYAEARQAFAjAAAWQgCAugEATQgEAOgFALQgEALgGAIQgGAJgIAHQgIAFgJAEQgJAEgLADIgWACQgggDgOgFgAhUhwQgGAKAAAXQAAAXAGAKQAFAJALAAQANAAAJgJQAAgUgEghQgCgLgFgHQgFgFgIAAQgJgBgFALgAo+BkQgPgCgMgGQgGgDABgGIACgiQABgEADgBQAEgCADACQAJAGALACQAKAEALAAQARAAAIgJQAHgIAAgQQAAgKgFgIQgEgGgJgFQgIgEgLgDIgTgDQgHAAAAgGIAAggQAAgGAHgBQANgBALgDQAKgBAHgGQAHgDADgHQADgFAAgIQAAgNgHgHQgHgHgPAAQgKgBgLADIgSAHQgKADAAgJIgCghQgBgFAFgCQANgFAPgDQAOgDASAAQATAAAPAEQAQAFAKAJQAKAJAFANQAFAMAAAQQAAAMgCALQgDAJgFAJQgFAHgIAGQgHAFgLAFQALADAIAGQAIAHAFAIQAGAIADAKQADAJAAAMQAAATgHAOQgFAPgMAKQgLAJgQAFQgQAGgUAAQgRgBgPgCgALqBiQgHAAAAgHIAAhLIgnAAIAABLQAAAHgGAAIguAAQgHAAAAgHIAAi1QAAgHAHABIAuAAQAGgBAAAHIAABCIAnAAIAAhCQAAgHAHABIAtAAQAHgBAAAHIAAC1QAAAHgHAAgAE+BiQgIAAAAgHIAAi1QAAgHAIABIBxAAQAHgBAAAHIAAAbQAAAHgHAAIg7AAIAACTQAAAHgIAAgAjzBiQgIAAAAgHIAAgqIhUAAQgHAAAAgHIAAghQAAgKAFgKIBIiVQADgFAHgBIA7AAQAHAAAAAIIAACdIAOAAQAHABAAAFIAAAlQAAAHgHAAIgOAAIAAAqQAAAHgHAAgAklgBIAqAAIAAhXgArcBiQgHAAAAgHIAAi5IgaAXQgGAFgEgGIgVgcQgDgFAEgFIA5gyQAGgGAIAAIApAAQAHAAAAAIIAAD5QAAAHgHAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(-79.8,-17.1,159.6,34.2), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("ALNBoQgEAAAAgEIAAibQAAgDAEAAIAdAAQAEAAAAADIAAAFQAEgGAFgCQAGgDAIAAQAJAAAHADQAHAEAFAIQAFAIADALQADAMAAAPQAAAQgDAMQgDALgFAIQgFAIgHADQgHAEgJAAQgHAAgHgDQgFgCgEgFIAAAwQAAAEgEAAgALugfIAAA+QAFAGAFAAQAEAAACgCQADgCACgEQADgGABgXIgBgQQgBgHgCgFQgCgEgDgBQgCgDgEAAQgGAAgEAFgAu0BTQgEAAAAgFIAAgSIghAAIAAASQAAAFgFAAIgdAAQgEAAAAgFIAAgnQAAgFAEAAIAFAAQAFgOAHgdQADgPACgfQAAgDAEAAIA/AAQAEAAAAADIAABZIAHAAQAFAAAAAFIAAAnQAAAFgFAAgAvKAAQgDARgFARIATAAIAAhEIgGAAQgBAQgEASgAPAA6QgFgFAAgKQAAgJAFgFQAFgFALAAQAKAAAFAFQAFAFAAAJQAAAKgFAFQgFAEgKAAQgLAAgFgEgAHeA9QgJgCgHgDQgEgCAAgEIACgUQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAQAAABABAAQAFADAGACQAHACAHgBQAKAAAFgEQAEgFAAgKQAAgGgDgFQgDgEgFgDIgLgDIgMgDQgEAAAAgDIAAgTQAAgFAEAAQAIAAAHgCIAKgEQAEgDACgDQACgEAAgFQAAgIgEgEQgFgEgJgBQgGAAgHACIgLAEQgGACAAgFIgBgUQgBgEADAAQAIgEAJgCQAJgBALAAQAMAAAJACQAJADAHAGQAGAFADAIQADAIAAAJQAAAIgCAFQgBAHgEAFQgDAEgEAEQgFADgGADQAGACAFAEQAFADAEAFQADAGACAFQABAHAAAGQAAAMgDAIQgEAJgHAGQgHAGgKADQgJADgMAAQgLAAgJgBgAFcA6QgDgCAAgEIACgUQAAgGAGADQAKAFALgBIAKgBQAEgBADgDQADgEACgEQABgGAAgHQAAgFgBgEQgCgEgDgEQgDgDgEgBQgFgCgFAAQgLAAgHADQgHACAAgGIAAhPQAAgEAEgBIBLAAQAFABAAAEIAAAUQAAAEgFAAIgpAAIAAAfIAJgBQAJAAAHADQAHADAGAGQAFAHADAJQADAKAAALQAAANgDALQgEAKgHAHQgHAHgKAEQgKADgOAAQgXgBgKgDgAgfA8QgGgDgFgEQgEgFgDgHQgCgHAAgJQAAgLACgHQADgHAGgEQAGgFAIgEQAIgCAMAAIAKAAIAAgHQAAgIgEgDQgCgDgIAAQgRABgIAEQgGADAAgGIgCgPQAAgEADgCIARgEQAJgCAJAAQANAAAJADQAIADAGAGQAFAFACAKQACAJAAAMIAABFQAAAEgEAAIgcAAQgEAAAAgEIAAgEQgEAFgFADQgGACgHAAQgHAAgGgCgAgOALQgDAEAAAIQAAAIADADQADADAFAAQAGAAAEgFIAAgZIgIAAQgHAAgDAEgAkhA6QgKgEgHgHQgHgJgEgMQgEgLAAgPQAAgOAEgMQADgLAGgJQAGgHAJgEQAJgEALAAQAMAAAJAEQAJAEAGAIQAGAIADAMQADAMAAAOIAAAHQAAAFgFAAIg3AAIACALQACAFADADQADADAEABIALABQALAAAJgEQAGgCAAAFIABAQQAAAEgDABQgFADgIABQgHABgIAAQgOAAgLgEgAkEgLQAAgOgDgGQgDgFgHAAQgGAAgDAFQgDAGAAAOIAZAAIAAAAgAm5A9QgEgBAAgEIACgQQAAgFAEABIAGABQAGAAADgFQADgEAAgOIAAhFQAAgDAEAAIBOAAQAEAAAAADIAABvQAAAEgEAAIgcAAQgEAAAAgEIAAhZIgOAAIAAAzQAAAMgDAJQgCAIgFAFQgFAFgHADQgIACgKAAQgKAAgGgBgApvA6QgKgEgIgHQgHgJgEgMQgDgLAAgPQAAgOADgMQAEgLAGgJQAGgHAJgEQAJgEALAAQAMAAAJAEQAJAEAGAIQAGAIADAMQADAMAAAOIAAAHQAAAFgGAAIg3AAQABAGACAFQABAFADADQADADAFABIAKABQAMAAAJgEQAFgCABAFIABAQQAAAEgDABQgGADgHABQgHABgJAAQgNAAgLgEgApSgLQAAgOgEgGQgDgFgGAAQgGAAgDAFQgEAGAAAOIAaAAIAAAAgAttA6QgKgEgHgHQgHgJgEgMQgEgLAAgPQAAgOAEgMQADgLAGgJQAGgHAJgEQAJgEALAAQAMAAAJAEQAJAEAGAIQAGAIADAMQADAMAAAOIAAAHQAAAFgFAAIg3AAIACALQACAFADADQADADAEABIALABQALAAAJgEQAGgCAAAFIABAQQAAAEgDABQgFADgIABQgHABgIAAQgOAAgLgEgAtQgLQAAgOgDgGQgDgFgHAAQgGAAgDAFQgDAGAAAOIAZAAIAAAAgAN6A8QgFAAAAgEIAAguIgXAAIAAAuQAAAEgEAAIgcAAQgEAAAAgEIAAhvQAAgDAEAAIAcAAQAEAAAAADIAAApIAXAAIAAgpQAAgDAFAAIAbAAQAFAAAAADIAABvQAAAEgFAAgAJ1A8QgFAAAAgEIAAhvQAAgDAFAAIBFAAQAEAAAAADIAAARQAAAFgEAAIgkAAIAABZQAAAEgFAAgADzA8QgGAAACgFIAoh9IgxAAQgFAAAAgEIAAgWQAAgEAFgBIBVAAQAFABAAAEIAAAVQAAAGgCADIgmB6QgCAEgEAAgACWA8QgFAAAAgEIAAhxIgPAOQgEADgCgDIgNgRQgCgEADgDIAjgeQADgEAFAAIAZAAQAEABAAAEIAACYQAAAEgEAAgAhgA8QgEAAAAgEIAAguIgYAAIAAAuQAAAEgEAAIgcAAQgEAAAAgEIAAhvQAAgDAEAAIAcAAQAEAAAAADIAAApIAYAAIAAgpQAAgDAEAAIAbAAQAFAAAAADIAABvQAAAEgFAAgAodA8QgFAAAAgEIAAhvQAAgDAFAAIAmAAQAMAAAJABQAJACAGAFQAGADADAHQADAGAAAJQAAAHgDAFQgEAHgGADQAIADAFAGQAEAIAAAJQAAAJgDAHQgDAHgGAEQgGAFgKADQgJACgNAAgAn9AlIAFAAQAIAAADgDQAEgDAAgIQAAgIgEgCQgDgDgIAAIgFAAgAn9gMIAEAAQAHAAADgBQADgEAAgGQAAgIgDgCQgDgDgHAAIgEAAgAsbA8QgEAAAAgEIAAhvQAAgDAEAAIAbAAQAEAAAAADIAABZIAMAAIAAhZQAAgDAFAAIAaAAQAEAAAAADIAABZIANAAIAAhZQAAgDAEAAIAaAAQAFAAAAADIAABvQAAAEgFAAgAPBAMQgEAAAAgFIAAgEQAAgMAEgKQAEgKAKgJQAFgFACgGQACgEAAgGQAAgHgEgDQgEgEgIAAIgMABIgLAFQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIgCgVQAAgDADgBQAHgEAJgCQAJgBAJAAQAMAAAJADQAKACAGAGQAHAFADAJQADAHAAALIgCALIgEALQgFAKgLALQgEAEgCAFQgCAFAAAHIAAADQAAAFgEAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(-102.3,-10.4,204.8,20.9), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AIGBVIgKgFIgJgFQgEgEgDgFQgFgHgFgTQgCgLgBgbQAAgNADgXQACgLAIgPQADgGAEgDQAEgEAFgDQAFgCAFgBIAMgCIAMACQAGABAFACQAFADAEAEIAHAJQAIAPACALQADAXAAANQgBAbgCALQgGATgEAHQgDAFgEAEIgJAFIgLAFIgMABgAIMgxQgDADgCAGQgCAFAAALIAAA2IACAQQACAGADABQACADAEAAQAEAAADgDQACgBACgGIADgQIAAg2IgDgQQgCgGgCgDQgDgBgEAAQgEAAgCABgAGSBVIgKgFIgJgFQgEgEgDgFQgEgHgGgTQgCgLgBgbQAAgNADgXQACgLAIgPIAHgJQAEgEAFgDQAFgCAFgBIAMgCIAMACQAGABAFACQAFADAEAEIAHAJQAIAPACALQADAXAAANQgBAbgCALQgGATgEAHQgDAFgEAEIgJAFIgLAFIgMABgAGYgxQgDADgBAGQgDAFAAALIAAA2QABAKACAGQABAGADABQADADADAAQAEAAADgDQADgBABgGQACgGABgKIAAg2QgBgLgCgFQgBgGgDgDQgDgBgEAAQgDAAgDABgACNBQQgEgBABgEIABgUQABgGAFADQAKAEAMABIAKgBIAHgGQADgCABgGQACgFAAgGQAAgGgCgFQgBgEgDgDQgDgEgEgCQgFgBgGAAQgKAAgIADQgGACAAgGIAAhOQAAgFAEABIBLAAQAEgBAAAFIAAATQAAAFgEAAIgqAAIAAAeIAJAAQAJAAAIADQAHADAFAHQAGAGADAIQADAKAAANQAAANgDAJQgEALgHAHQgHAHgKAEQgLADgNABQgYgCgJgEgAj6BSQgKgFgGgHQgHgIgEgMQgDgMAAgPQAAgQADgKQAEgMAHgIQAGgHAKgEQAJgEAMAAQAMAAAKAEQAJAEAHAHQAGAIAEAMQADAKAAAQQAAAPgDAMQgEAMgGAIQgHAHgJAFQgKADgMABQgMgBgJgDgAjwgFIgCAKIAAAkIACALQAEAIAHAAQAHAAAEgIQACgEABgHIAAgkQgBgGgCgEQgEgIgHAAQgHAAgEAIgAEABTQgEAAAAgFIAAgQQAAgFADgEIAQgTIAQgVQAHgNAEgJQAFgMAAgIQAAgLgFgFQgFgFgKAAQgMAAgJAEIgEAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIgBgTQAAgFADgBQAIgDAIgBQAIgCAJgBQAMAAAKAEQAJAEAHAGQAGAGADAJQAEAJAAAMQAAAMgEAMQgDAKgHALQgGAKgIALIgRASIAoAAQAEABAAAEIAAAUQAAAFgEAAgAAGBOIAAiXQAAgFAEABIA7ABIANADIALAGIAJAJIAHALIAFAPQAEAVAAANQgBAagDAKIgFANQgDAHgEAFIgJAJIgLAGIgNAEIg7ABQgEAAAAgFgAArA1IAKAAQAHAAAFgCQAFgDAEgGQADgFACgLQABgJAAgPQAAgOgBgJQgCgKgDgGQgEgFgFgEQgFgCgHAAIgKAAgAhiBTQgFAAAAgFIAAhCQAAgPgDgFQgCgFgHAAQgHAAgEAGIAABVQAAAFgFAAIgcAAQgFAAAAgFIAAhtQAAgEAFgBIAcAAQAFABAAAEIAAADQAEgEAHgEQAGgCAIAAQAJAAAGACQAHADAEAGQAFAGACAJQACAJAAAMIAABFQAAAFgEAAgAlBBTQgEAAgBgEIgWg3IAAA2QAAAFgEAAIgcAAQgFAAAAgFIAAifQAAgEAFAAIAcAAQAEAAAAAEIAABbIATgqQACgEAEAAIAdAAQAHAAgDAHIgZAuIAcA8QACAGgGAAgAm2BTQgFAAAAgFIAAhtQAAgEAFgBIAcAAQAFABAAAEIAABtQAAAFgFAAgAn7BTQgEAAgBgEIghhiIAABhQAAAFgEAAIgbAAQgFAAAAgFIAAiXQAAgFAFABIAkAAQAEAAACADIAgBiIAAhhQAAgFAEABIAcAAQAEgBAAAFIAACXQAAAFgEAAgAm4g1QgFgEAAgKQAAgJAFgEQAFgEALgBQAKABAGAEQAFAEAAAJQAAAKgFAEQgGAEgKAAQgLAAgFgEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(-58.2,-8.5,116.4,17.1), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F5307B").s().p("AsCB0QgJgBgJgEQgIgEgHgGQgHgGgFgHQgGgHgEgKIgHgUQgDgOgCglQAAgSAFggIAHgUQAEgJAGgIQAFgHAHgFQAHgHAIgDQAJgEAJgCQAKgCAKAAQAMAAAJACQAKACAIAEQAIADAHAHQAGAFAGAHIAKARIAGAUQAGAgAAASQgCAlgEAOIgHAUQgDAKgGAHIgMANQgHAGgIAEQgJAEgJABQgJACgMAAQgKAAgKgCgAr7hGQgGADgEAJQgEAIgCAPQgDAPAAAUQAAAVADAQQACAOAEAJQAEAJAGADQAGAEAHAAQAIAAAHgEQAFgDAEgJQAFgJACgOQACgPAAgWQAAgUgCgPQgCgPgFgIQgEgJgFgDQgHgEgIAAQgHAAgGAEgAN+BzQgHAAAAgHIAAjWQAAgHAHAAIAoAAQAGAAAAAHIAABLIARAAQAPAAAMAEQAMAFAJAKQAJAKAEANQAFANAAARQAAARgFANQgEAOgJAKQgJAKgMAFQgMAFgPAAgAOsBIIAMAAQAKAAAFgIQAFgHAAgQQAAgQgFgHQgFgIgKAAIgMAAgAMEBzQgGAAAAgHIAAiyIgpAAQgGAAAAgFIAAgfQAAgHAGAAICIAAQAGAAAAAHIAAAfQAAAFgGAAIgoAAIAACyQAAAHgHAAgAKPBzQgGAAAAgHIAAiJIgtCKQgCAGgHAAIgzAAQgGAAAAgHIAAjWQAAgHAGAAIAnAAQAFAAAAAHIAACJIAuiKQACgGAHAAIAzAAQAGAAAAAHIAADWQAAAHgGAAgAHFBzQgFAAAAgHIAAiyIgyAAIAACyQAAAHgGAAIgrAAQgGAAAAgHIAAjWQAAgHAGAAICTAAQAGAAAAAHIAADWQAAAHgGAAgADMBzQgIAAADgJIARg2Ig4idQgCgIAIAAIApAAQAFAAACAGIAYBYIAdhZQABgFAGAAIApAAQAIAAgDAIIhDDXQgBAFgGAAgAgzBzQgHAAAAgHIAAjWQAAgHAHAAIAoAAQAGAAAAAHIAABLIAQAAQAPAAAMAEQANAFAIAKQAJAKAEANQAFANAAARQAAARgFANQgEAOgJAKQgIAKgNAFQgMAFgPAAgAgFBIIALAAQAKAAAFgIQAFgHAAgQQAAgQgFgHQgFgIgKAAIgLAAgAkeBzQgGAAAAgHIAAjWQAAgHAGAAIAnAAQAGAAAAAHIAACxIAWAAIAAixQAAgHAHAAIAnAAQAGAAAAAHIAACxIAWAAIAAixQAAgHAGAAIAoAAQAGAAAAAHIAADWQAAAHgGAAgAm+BzQgGAAAAgHIAAjWQAAgHAGAAIB2AAQAHAAAAAHIAAAdQAAAGgHAAIhFAAIAAAxIBAAAQAGAAAAAHIAAAcQAAAGgGAAIhAAAIAAA2IBIAAQAGAAAAAGIAAAdQAAAHgGAAgAoYBzQgHAAAAgHIAAhGQgFAGgLAEQgKAEgMAAQgOAAgKgEQgKgFgHgJQgHgJgEgOQgEgNAAgUIAAhUQAAgHAGAAIArAAQAGAAAAAHIAABOQAAAUAFAIQAEAIALAAQAOAAAFgIIAAhqQAAgHAHAAIAqAAQAHAAAAAHIAADWQAAAHgHAAgAuGBzQgFAAgCgFIgbg8IgdA8QgBAFgGAAIgsAAQgJAAAEgKIAyhpIgxhoQgFgJAKAAIAsAAQAFAAACAFIAcA7IAbg7QACgFAFAAIAsAAQAJAAgEAJIgxBoIAyBpQAFAKgLAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(-102.3,-11.8,204.6,23.7), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo();
	this.instance.parent = this;
	this.instance.setTransform(-110,-18);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(-110,-18,220,36), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// tovar.jpg - копия
	this.instance = new lib.tovar();
	this.instance.parent = this;
	this.instance.setTransform(-110,-106,0.866,0.866);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(-110,-106,207.9,207.9), null);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ4, new cjs.Rectangle(-120,-200,240,400), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#F5307B").ss(2,1,1).p("Ayv/PMAlfAAAMAAAA+fMglfAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(-121,-201,242,402), null);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ47();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.08,scaleY:1.08},8,cjs.Ease.get(-1)).to({scaleX:1.18,scaleY:1.18},9,cjs.Ease.get(1)).to({scaleX:1.09,scaleY:1.09},8,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},9,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.2,-13.2,180.4,26.5);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_69 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(69).call(this.frame_69).wait(9));

	// Символ 40
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(-89.8,-180.9);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(16).to({y:-215.4},0).to({scaleY:0.93,y:-179.6,alpha:1},7).to({scaleY:1,y:-180.9},2).wait(44).to({scaleX:0.74,x:-90,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:145.7,alpha:0},3,cjs.Ease.get(1)).wait(1));

	// Символ 39
	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-89.9,-220.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(13).to({y:-254.7},0).to({scaleY:0.93,y:-216,alpha:1},7).to({scaleY:1,y:-220.2},2).wait(47).to({scaleX:0.74,x:-90,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:-325.9,alpha:0},3,cjs.Ease.get(1)).wait(1));

	// Символ 38
	this.instance_2 = new lib.Символ38();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-37.9,-263.8);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({y:-298.3},0).to({scaleY:0.93,y:-256.5,alpha:1},7).to({scaleY:1,y:-263.8},2).wait(50).to({scaleX:0.74,x:-51.6,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:93.8,alpha:0},3,cjs.Ease.get(1)).wait(1));

	// Символ 37
	this.instance_3 = new lib.Символ37();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-132.1,-261);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(7).to({y:-295.5},0).to({scaleY:0.93,y:-253.8,alpha:1},7).to({scaleY:1,y:-261},2).wait(53).to({scaleX:0.74,x:-121.2,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:-280.6,alpha:0},3,cjs.Ease.get(1)).wait(1));

	// Символ 36
	this.instance_4 = new lib.Символ36();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-48.6,-298.4);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({y:-332.9},0).to({scaleY:0.93,y:-288.5,alpha:1},7).to({scaleY:1,y:-298.4},2).wait(56).to({scaleX:0.74,x:-59.5,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:104.4,alpha:0},3,cjs.Ease.get(1)).wait(1));

	// Символ 35
	this.instance_5 = new lib.Символ35();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-142.5,-300.9);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({y:-335.4},0).to({regY:-0.1,scaleY:0.93,y:-290.9,alpha:1},7).to({regY:0,scaleY:1,y:-300.9},2).wait(59).to({scaleX:0.74,x:-128.9,alpha:0.48},5,cjs.Ease.get(1)).to({scaleX:1,x:-272,alpha:0},3,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180.6,-313.2,180.4,150.1);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.parent = this;
	this.instance.setTransform(-1,5);
	this.instance.alpha = 0.922;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ33, new cjs.Rectangle(-121,-200.3,242.1,400.6), null);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ30();
	this.instance.parent = this;
	new cjs.ButtonHelper(this.instance, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ32();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,1.8);
	this.instance_1.alpha = 0.551;
	this.instance_1.filters = [new cjs.BlurFilter(2, 2, 1)];
	this.instance_1.cache(-79,-19,159,38);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ26, new cjs.Rectangle(-78.4,-17.1,160,39.8), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ24();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ25();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,3.5);
	this.instance_1.alpha = 0.488;
	this.instance_1.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance_1.cache(-96,-31,192,62);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(-96,-28.7,196,66.5), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ17();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,0.5);
	this.instance_1.filters = [new cjs.BlurFilter(2, 2, 1)];
	this.instance_1.cache(-102,-15,203,30);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(-100.6,-13.5,204,31), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 16
	this.instance = new lib.Символ16();
	this.instance.parent = this;
	this.instance.setTransform(1.1,-2.7);
	this.instance.alpha = 0.621;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 15
	this.instance_1 = new lib.Символ15();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(-99.5,-17.1,204,34.2), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.15,scaleY:1.15},10,cjs.Ease.get(-1)).to({scaleX:1.32,scaleY:1.32},11,cjs.Ease.get(1)).to({scaleX:1.17,scaleY:1.17},11,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},12,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.2,-17.1,160.5,34.2);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 14
	this.instance = new lib.Символ14();
	this.instance.parent = this;
	this.instance.setTransform(-0.3,-23.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 13
	this.instance_1 = new lib.Символ13();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,18.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(-99.9,-40.3,204,75.8), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_101 = function() {
		this.gotoAndPlay(13);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(101).call(this.frame_101).wait(19));

	// Символ 11
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(0,46.5,1,1,0,0,0,0,-10.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(7).to({y:31.9,alpha:1},5,cjs.Ease.get(1)).wait(13).to({y:39.2},7,cjs.Ease.get(1)).to({y:31.9},8,cjs.Ease.get(1)).to({scaleX:1.33,scaleY:1.33},8,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},8,cjs.Ease.get(1)).wait(14).to({y:39.2},7,cjs.Ease.get(1)).to({y:31.9},8,cjs.Ease.get(1)).to({scaleX:1.33,scaleY:1.33},8,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},8,cjs.Ease.get(1)).to({y:46.5,alpha:0},18,cjs.Ease.get(1)).wait(1));

	// Символ 10
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.8,23.9,1.75,1.75,0,0,0,0.1,0.1);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({y:9.3,alpha:1},8,cjs.Ease.get(1)).wait(13).to({scaleX:2.3,scaleY:2.3,x:0.9,y:9.4},7,cjs.Ease.get(1)).to({scaleX:1.75,scaleY:1.75,x:0.8,y:9.3},8,cjs.Ease.get(1)).wait(30).to({scaleX:2.3,scaleY:2.3,x:0.9,y:9.4},7,cjs.Ease.get(1)).to({scaleX:1.75,scaleY:1.75,x:0.8,y:9.3},8,cjs.Ease.get(1)).wait(16).to({y:23.9,alpha:0},18,cjs.Ease.get(1)).wait(1));

	// Символ 9
	this.instance_2 = new lib.Символ9();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-0.1,-0.6,1,1,0,0,0,-0.1,11.8);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-15.2,alpha:1},12,cjs.Ease.get(1)).to({scaleX:1.2,scaleY:1.2},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).to({y:-22.5},7,cjs.Ease.get(1)).to({y:-15.2},8,cjs.Ease.get(1)).wait(17).to({scaleX:1.2,scaleY:1.2},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).to({y:-22.5},7,cjs.Ease.get(1)).to({y:-15.2},8,cjs.Ease.get(1)).wait(16).to({y:-0.6,alpha:0},18,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-102.4,-24.3,204.8,91.8);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_103 = function() {
		this.gotoAndPlay(15);
	}
	this.frame_114 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(103).call(this.frame_103).wait(11).call(this.frame_114).wait(1));

	// Слой 1
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.7,scaleY:0.7,x:-264.6,y:70.3},0).to({scaleX:1,scaleY:1,x:0,y:0,alpha:1},13,cjs.Ease.get(1)).to({scaleX:0.93,scaleY:0.93},10,cjs.Ease.get(-1)).to({scaleX:0.86,scaleY:0.86},11,cjs.Ease.get(1)).to({scaleX:0.93,scaleY:0.93},12,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},11,cjs.Ease.get(1)).to({scaleX:0.93,scaleY:0.93},10,cjs.Ease.get(-1)).to({scaleX:0.86,scaleY:0.86},11,cjs.Ease.get(1)).to({scaleX:0.93,scaleY:0.93},12,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},12,cjs.Ease.get(1)).to({scaleX:0.7,scaleY:0.7,x:-264.6,y:70.3,alpha:0},11,cjs.Ease.get(-1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110,-106,207.9,207.9);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.238},24,cjs.Ease.get(1)).to({alpha:1},25,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-121,-201,242,402);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.parent = this;
	this.instance.setTransform(0,18,1,1,0,0,0,0,18);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.84,scaleY:0.84},16,cjs.Ease.get(-1)).to({scaleX:0.66,scaleY:0.66,y:18.1},18,cjs.Ease.get(1)).to({scaleX:0.82,scaleY:0.82},17,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,y:18},18,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110,-18,220,36);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_15 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(15).call(this.frame_15).wait(15));

	// Слой 1
	this.instance = new lib.Символ45();
	this.instance.parent = this;
	this.instance.setTransform(0,26.5,0.789,0.789);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,y:-10,alpha:1},11).to({y:0},3).wait(1).to({y:-10},3).to({scaleX:0.79,scaleY:0.79,y:26.5,alpha:0},11).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71.2,16.1,142.4,20.9);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.parent = this;
	this.instance.setTransform(0,-17.7,0.82,0.82);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-20},3).to({x:247.1,alpha:0},6).wait(1).to({x:-20,alpha:1},6).to({x:0},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.9,-37.6,168,75.2);


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 1
	this.instance = new lib.Символ12();
	this.instance.parent = this;
	this.instance.setTransform(-0.6,2.1,0.827,0.827);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-13},3).to({y:101.1,alpha:0},6).wait(1).to({y:-13,alpha:1},6).to({y:2.1},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.3,-31.3,170,62.6);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.764,0.764);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.9,scaleY:0.9,y:26},9,cjs.Ease.get(1)).wait(1).to({scaleX:0.76,scaleY:0.76,y:0},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-13.7,168,27.5);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.txt1 = new lib.Символ34();
	this.txt1.parent = this;
	this.txt1.setTransform(90.4,238.3);

	this.timeline.addTween(cjs.Tween.get(this.txt1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(-90.2,-75,180.4,150.1), null);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.parent = this;
	this.instance.setTransform(-0.2,-1.6,0.65,0.65,0,0,0,0,0.1);

	this.instance_1 = new lib.Символ23();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-1.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(-96,-30.5,196,66.5), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.04,scaleY:1.04},16,cjs.Ease.get(-1)).to({scaleX:1.09,scaleY:1.09},18,cjs.Ease.get(1)).to({scaleX:1.04,scaleY:1.04},18,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},17,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96,-30.5,196,66.5);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.07,scaleY:1.07},0).wait(1).to({scaleX:0.92,scaleY:0.92},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96,-30.5,196,66.5);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(-2.4,149.5);
	new cjs.ButtonHelper(this.instance, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ33();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.9,-5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(-122,-205.3,242.1,400.6), null);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(10).call(this.frame_10).wait(10));

	// Слой 1
	this.instance = new lib.Символ20();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9).wait(1).to({alpha:0},9).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122,-205.3,242.1,400.6);


// stage content:
(lib.new240x400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.vtoroy.gotoAndPlay(1);
			_this.txt.txt1.gotoAndPlay(1);
			_this.logo.gotoAndPlay(1);
			_this.photo.gotoAndPlay(104);
			_this.price.gotoAndPlay(1);
			_this.hochesh.gotoAndPlay(1);
			_this.nikontxt.gotoAndPlay(1);
		}
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.vtoroy.gotoAndPlay(10);
			_this.txt.txt1.gotoAndPlay(70);
			_this.logo.gotoAndPlay(10);
			_this.photo.gotoAndPlay(1);
			_this.price.gotoAndPlay(10);
			_this.hochesh.gotoAndPlay(10);
			_this.nikontxt.gotoAndPlay(16);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 1
	this.logo = new lib.Символ42();
	this.logo.parent = this;
	this.logo.setTransform(120,23.8);

	this.timeline.addTween(cjs.Tween.get(this.logo).wait(1));

	// Слой 2
	this.instance = new lib.Символ2();
	this.instance.parent = this;
	this.instance.setTransform(120.1,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 9
	this.txt = new lib.Символ41();
	this.txt.parent = this;
	this.txt.setTransform(120.2,254.5,1,1,0,0,0,0.1,81.6);

	this.timeline.addTween(cjs.Tween.get(this.txt).wait(1));

	// Слой 10
	this.nikontxt = new lib.Символ46();
	this.nikontxt.parent = this;
	this.nikontxt.setTransform(120.1,288.5);

	this.timeline.addTween(cjs.Tween.get(this.nikontxt).wait(1));

	// Слой 8
	this.vtoroy = new lib.Символ21();
	this.vtoroy.parent = this;
	this.vtoroy.setTransform(121.1,205.1);

	this.timeline.addTween(cjs.Tween.get(this.vtoroy).wait(1));

	// Слой 7
	this.price = new lib.Символ43();
	this.price.parent = this;
	this.price.setTransform(120.7,355.1);

	this.timeline.addTween(cjs.Tween.get(this.price).wait(1));

	// Слой 6
	this.hochesh = new lib.Символ44();
	this.hochesh.parent = this;
	this.hochesh.setTransform(120,102.7);

	this.timeline.addTween(cjs.Tween.get(this.hochesh).wait(1));

	// Слой 4
	this.photo = new lib.Символ5();
	this.photo.parent = this;
	this.photo.setTransform(120,230,0.968,0.968);

	this.timeline.addTween(cjs.Tween.get(this.photo).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(119.1,199,242.1,402);
// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/logo.png?1485774169467", id:"logo"},
		{src:"images/tovar.jpg?1485774169467", id:"tovar"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;