(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.ball = function() {
	this.initialize(img.ball);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,210);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.dama_03 = function() {
	this.initialize(img.dama_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,70,78);


(lib.dama_062 = function() {
	this.initialize(img.dama_062);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,29,113);


(lib.dama_09 = function() {
	this.initialize(img.dama_09);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,71,65);


(lib.dama_121 = function() {
	this.initialize(img.dama_121);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,103,327);


(lib.dama_181 = function() {
	this.initialize(img.dama_181);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,44,104);


(lib.dama_21 = function() {
	this.initialize(img.dama_21);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,180);


(lib.dym = function() {
	this.initialize(img.dym);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,272,500);


(lib.lightn = function() {
	this.initialize(img.lightn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,48);


(lib.log = function() {
	this.initialize(img.log);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,150,108);


(lib.mech = function() {
	this.initialize(img.mech);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,280,254);


(lib.mous = function() {
	this.initialize(img.mous);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,64,64);


(lib.qwe = function() {
	this.initialize(img.qwe);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,30,32);


(lib.wer = function() {
	this.initialize(img.wer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,66,61);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ110 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.mous();
	this.instance.parent = this;
	this.instance.setTransform(-32,-32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ110, new cjs.Rectangle(-32,-32,64,64), null);


(lib.Символ93 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.wer();
	this.instance.parent = this;
	this.instance.setTransform(-33,-31);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ93, new cjs.Rectangle(-33,-31,66,61), null);


(lib.Символ92 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.qwe();
	this.instance.parent = this;
	this.instance.setTransform(-15,-16);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ92, new cjs.Rectangle(-15,-16,30,32), null);


(lib.Символ66 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkOB7QAAgFAEgIQADgJAAgLIgBgGIgDgFIgJgEIhwgCQgLAAgGACIgKAFQgDADgBAEIgBAIIAAAcQAAAHgHAAQgFAAgEgIQgEgHgCgMIgDgzIAUAAIBoiaQAGgIAAgDQAAgEgKgBIgkgCIgEgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgFAFAAIANABIB3AAIAEAAIACABIABADQAAAEgGAAIgPABQgDABgBADQgFAHgCAbQgDAaAAAtIAAA+IAagBIgFAgIgIAZQgDAKgGAGQgFAGgFAAQgGAAAAgHgAmHAkIgKARIBfAAIAFgkQACgYAAglIgBg3gAuYBJIgHgLIgIgjIgrAdIgbANQgNAEgNAAQgLAAgIgDQgIgDgGgGQgFgGgDgHQgCgHAAgIQAAgNAIgIQAHgIARgIIBdgvIgGgWQgDgKgFgHQgFgGgGgEQgHgDgKAAQgIAAgIADIgNAIIgJAIIgDAHQAAABAAABQAAAAgBABQAAAAgBAAQgBAAgBAAQgFAAgFgEQgFgEABgFIABgFIAVgLIA4gUQAOgDALAAQARAAAJAFQAJAEAFAJQAEAJABAMIAFBBQACASAEAOQAEAPAGAJQAHAJAIAAIAKgCIATgIIAFgDQAEAAAAADIgBAEIgFAEIhBAiIgMADQgFAAgEgFgAvrgLQgJAGgGAFQgEAGAAAIQAAAMAHAJQAGAJAPAAQAHAAAJgDIAPgHIAMgHIAMgLQACgCgBgEIgIgwgAo3BHQgQgFgMgKQgMgLgIgPQgHgQAAgVQAAgSADgNQACgNAEgKIAJgRIAKgMQAGgHAKgHIATgMQALgFAMgDQALgDANAAQAWAAALAHQANAIAAAMQgBALgEAIQgEAIgLAHQgLAIgSAIIg+AbQABANAFALQAFAMAKAJQAJAJANAFQAOAFAQAAQAOAAAMgDIATgHIAOgHIAEgDIAEABIABADIgOAOIgWAQQgMAJgQAGQgRAGgSAAQgQAAgQgFgAoohoQgGADgFAJQgGAIgEAPQgEAOAAAUIAwgUIAKgHQAHgFAAgMIgCgLIgFgJIgJgHQgFgCgHAAQgFAAgHAEgAP/BIIjxADIgDgCIgBgDQgBgDAIAAQAQAAADgFQADgGADgbQADgbAAgtIgDhEQgBgFgFgCQgGgCgLAAQgGAAgBgEQAAgEAGAAIBZAAIADABIABADQABAEgIAAIgGABQgDABgCADQgDAFgBAcQgCAbgBAtIABA7IAlADIAhgDIAGhcIgDhEIgBgEIgBgDIgEgBIgJgBQgGAAgBgEQAAgEAGAAIBRAAIADABIABADQAAAEgGAAIgHABQgDABgCADQgDAFgCAcQgBAbAAAtIAAA7IAvACIAXgCIAGhcIgChEIgDgHIgEgBIgJgBQgHAAAAgEQAAgEAGAAIAsACIAXgBIAWgBIADABIABADQAAAEgGAAQgRAAgDAFQgDAFgCAcQgCAbAAAtIAAAwQAAARABADQABAFAFABQAFACAMAAQAHAAAAAEQAAAFgGAAgARsBIQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgEAEAAQALAAAFgDQAHgDABgIIADgVIAEh9IgDgQQgCgGgDgBIgIgCIgDAAIgCABQgDgCgBgCQABgFADAAIADAAIACAAIADAAIBEABIAHAAIACAAIACAAQAFAAAAAFQAAACgEACIgDgBIgBAAQgKAAgEAHQAAgBAAAAQAAAAAAAAQAAAAAAABQAAAAgBABIgFA5IAAAOIA6ABQASACAQAEQAQAFALAJQALAJgBAPQAAATgJANQgJANgPAIQgPAJgSADQgTAEgTAAgAS1gWIAAA3QABANAIAIQAJAIASAAQAYAAAIgKQAKgKAAgYQAAgMgEgHQgFgJgHgFQgHgFgKgCIgVgCgAKcBKIgEgBIgBgDQAAgEAHAAQAQAAADgEQADgGADgbQADgbAAgtIAAgwQAAgRgBgEQgBgEgFgCQgGgCgLAAQgHAAAAgEQAAgEAGAAIAzACIAYgBIAVgBIAEABIACADQgBAEgGAAQgRAAgCAEQgEAGgDAbQgDAcAAAtIAAAvQAAARABADQABAFAFACQAGACALAAQAHAAAAAEQAAAEgGAAgAG+BIQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgEAFAAQALAAAGgDQAGgDACgIIACgVIAEh5IgDgQQgBgHgDgDQgFgDgGAAQgHAAAAgEQAAgEAFAAIASABIBIgBIAEACIABADQABADgIAAIgMABQgFABgCACIgDAMIgEBAIA7ABQARACARAEQAPAFALAJQALAJAAAPQAAASgJAOQgJANgPAIQgPAJgTADQgSAEgUAAgAIHgWIAAA+QADAKAIAGQAKAGAOAAQAYAAAKgKQAIgKABgYQgBgMgEgHQgEgJgIgFQgHgFgKgCIgUgCgAEBBKIgBgEIhNikIgECNQAAAMAEAEQAFAEAJAAQAEAAgBAEQAAAAAAABQAAABAAAAQgBAAAAABQgBAAgBAAIg+gBQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAQAIAAAGgDQAFgDABgGIAQiFIABgXQAAgSgJAAIgFAAIgEABQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgEIAGgCIA7gBIAIABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIgBACIgCABIgDABIgBADQAAAGAFAMIAsBcIAMAVIAHAJIBGh7IAEgMQAAgEgDgBIgHgCIgGgBQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIABgDQAAAAABAAQAAgBABAAQAAAAABAAQABAAABAAIBUAAQABAAABAAQABAAAAAAQABAAAAABQABAAAAAAIABADIAAADIgFABIgMACQgEABgDAHQgEAKgBAVIgCBwIACAUQABAHADACQACACAFAAIAKAAIADABIABACIAAAEIgCACIhaAAQgEAAABgEIABgDIACgCQAHAAAGgDQAHgDAAgKIAEh8IgCgEIgCAAIgFAIIhOCIIgHAHQgEACgFAAIgDAAgAhJBKIgDgBIgBgDQAAgEAGAAQAQAAAEgEQACgGADgbQAEgcAAgtIgBgqIhnCXQgDAFgHABIhBADIgEgBIgBgDQAAgEAHAAQAQAAADgEQAEgGADgbQACgbAAgtIgBhFQAAgEgGgCQgFgCgLAAQgIAAABgEQAAgEAFAAIBhAAIAEABIABADQAAAEgHAAQgQAAgDAEQgEAGgDAbQgCAcAAAtIAAAxIBrifQADgFAFgBIA+gCIADABIACADQAAAEgHAAQgQAAgDAEQgDAGgDAbQgCAcgBAtIABBDQABAFAFACQAFACAMAAQAGAAABAEQAAAEgGAAgAtXBIQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgEAEAAQALAAAGgDQAGgDABgIIAEgVIACiDQgCgMgEgDQgDgEgHAAIgCAAIgCABQgDgCgBgCQABgFADAAIADAAIACAAIADAAIB5AAQAZAAAOAHQAOAHAAARQAAALgFAKQgFAJgIAIQgKAHgKAGIgYALIAeACQAPACALAFQAMAEAGAIQAIAIgBALQAAASgKAOQgKANgQAIQgRAJgUADQgUAEgTAAgAsCgXIgLACIAAA2IAAAHQACAKAJAGQAKAGAOAAQAYAAANgKQANgKAAgYQAAgMgEgHQgFgJgIgFQgIgFgMgBIgZgDgAsChwQgHACgBAFIgCBEIACABIALAAQAPAAAKgDQAKgCAHgGQAOgLAAgYQAAgPgKgIQgLgJgTAAQgMAAgHACgAylBKIgDgBIgBgDQgBgEAIAAQAQAAADgEQACgFADgWQADgWABgiIhdgBIgHABIAABOQABAFAFACQAGACALAAQAHAAAAAEQAAAEgGAAIhgAAIgEgBIgCgDQAAgEAIAAQAQAAADgEQADgGADgbQADgbAAgtIgBhFQgBgEgFgCQgGgCgLAAQgHAAAAgEQAAgEAGAAIAVABIBMgBIADABIABADQAAAEgGAAQgRAAgCAEQgDAFgDATQgCATgBAgIBkgCIAAhFQgCgEgFgCQgGgCgLAAQgHAAAAgEQAAgEAGAAIAVABIBMgBIADABIABADQABAEgIAAQgQAAgDAEQgDAGgDAbQgDAcAAAtIABBDQABAFAFACQAGACALAAQAHAAAAAEQAAAEgGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ66, new cjs.Rectangle(-133.6,-13,267.3,26), null);


(lib.Символ64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ah2CAIADgcQAAgFgCgEQgCgDgHgCQgIgCgPAAIhcAAQgRABgIAEQgJAFgCAJQgBAJAAAQQAAAGgGAAQgFAAgEgHQgDgFgBgLIgDgxIAWACIB4izQgXAAgQgBIgdgFIgCgDIgBgEQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBIArAHIBWABIAPgCIAEABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAXAAIAugBIAPgBIADABIACADQAAAEgGABIgTABIAvBiIAbhNIACgMIAAgGQgBgEgCAAIgJgBQgFAAgCgDIgBgDIABgCIACAAIAzABIAJAAIAGAAIAEgBIADABQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAAAAAIADgCIBOACIAPgCIAEABQABAAAAAAQAAABAAAAQABAAAAABQAAAAAAABQAAAFgHAAIgQACIgDABQgBAAgCAIIgFBHIBDACIAOAAIAXgCIgBhBQAAgKgCgDQgDgDgGAAIgTgBIgDAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABAAIADgCIBOACIAPgCIAEABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAFgHAAIgQACIgEABQgBAAgBALIgEA5IgCAgIACBMQABAKABABIAEACIARADIAIAAIAEAAIABADQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAIgFABIgPgBIgPAAIhKABIgCgBIgBgDIABgDIAEgBQAMAAAHgBQAHgCACgCQADgGADgWQACgPABgsIgJgBIheAAIABBNQABAKABABIAFACIAQADIAIAAIAEAAIACADQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgEABIhoAAIgDgBIgBgDIABgDIAEgBQAMAAAHgBQAIgCABgCIAEgQIAGheIgBg/QAAgKgCgDQgCgDgHAAIgSgBIgEAAIAAgBIgBABIgFACIgKABIhnDCQgGAMgCAAIgGgCIgHgFIgHgHIgLgUIgGgIIgLgLIAAgBIABgDIAEgBQACAAADACIAGAGIAKANIAKgCIALgFQAFgEAFgGQAGgGAGgJIhHh7QgGgIgDgCIgIgDIgNgCQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgLABIgCABQgCABgBAKIgFA4IgBAhIABBPIAPgBIALgCIgHArQgDAMgGAJQgFAJgHAAQgFAAAAgGgAj9BAIBlAAQADgMACgZQACgaAAgoIAAg+gAO4BbIgMgKIgDgDIACgFIANgLIAEgCIAEACIALAKIADAEIgDAEIgLALIgEACgAMGBWIgUgFQgTgHgPgMQgHgGgGgIQgGgIgEgJQgJgSAAgWIgxAAIACBHQABAJABABIAEACIARADIAIAAIAEAAIABADQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAIgFABIhnAAIgDgBIgBgDIABgDIAEgBQAMAAAHgBQAIgCABgCIAEgQIADgcIACiBQAAgKgCgDQgDgDgGAAIgSgBIgEAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIADgCIA0ADIApgDIAEABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAFgHAAIgQACIgEABQgBAAgBAJIgGBMIAyABQADgXALgSQALgSAQgNQAQgOATgGQAJgEAKgCIAUgBQAWAAAUAGIASAIIAQAKQAPAMAIATQAFAIACALQACAKAAAMQAAAVgJAVQgIAWgQARQgPARgVALQgWAKgZAAgAMDhvQgNAHgJAMQgJANgEARQgFASAAAUQAAAZAGATQAGATAKANIALALQAGAEAHADQANAHAOAAQAIAAAHgDQAHgBAGgEQAMgIAIgOQAJgNAEgSQAEgQAAgTQAAgPgGgaQgFgTgKgNQgJgNgNgGQgNgHgNAAQgQAAgNAHgAq3BRQgUgHgPgNQgOgNgJgTQgEgJgCgLQgCgJAAgMQAAgbAKgVQAKgVAQgPQAIgIAKgGQAJgGAKgEQALgEALgCQAKgCAMAAQAVAAAUAGQAJADAJAFIAQAKQAPAMAJATQAEAIADALQACAKAAAMQAAAVgJAVQgJAWgPARQgQARgVALQgVAKgaAAQgXAAgTgGgAqmhvQgNAHgIAMQgJANgFARQgEASAAAUQAAAZAGATQAGATAKANIALALQAGAEAGADQANAHAOAAQAIAAAHgDQAHgBAHgEQAMgIAIgOQAIgNAEgSQAEgQAAgTQAAgPgFgaQgGgTgJgNQgKgNgMgGQgNgHgOAAQgQAAgNAHgAF1BTQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIABgCIACgCIAFABQAHAAAEgEQAEgEADgLQABgKABgSIgBh9IgDgJIgEgIQgCgDgEAAIgPAAIgDgBQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAAAQAAgBABAAIADgBIBbAAIAEAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABQAAAFgHABIgFAAIgLABIgEABIgCAFIgGAfIgBAxIAYgGQAMgCAMAAQANAAAVAFQAPAFAJAIQAKAIAFALQAEAKAAAMQAAALgFAMQgFALgJAJQgKAJgNAFQgOAGgSAAgAHDgYQgKACgLAEIACBMQAAAGAFAEQAEADAGACIAMADIAMAAQALAAAIgEQAIgFAFgHQAGgHADgJQACgJAAgIQAAgLgCgJQgDgIgGgIQgGgHgJgFQgKgEgOAAgAmdBVIgDgBIgBgDIABgDIADgBIAOAAIAIgBIAEgCIACgDIAEgJIADgTIAEiQIhtCnIgBAEQAAAEAFABIAPACQAHAAAAAFQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAIgEAAIg3gBIgPABIgDAAIgDgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAUgBIAFgDIB/i8QgXAAgQgBIgdgFIgCgDIgBgEQAAgDADgCIArAHIBkgBIAEABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAAFgHAAIgRACIgDABQgBABgBAKIgFA4IgBAhIACBMQABAKABABIAEACIAHACIAWABIABACQAAAEgCABIgEABgAvVBSIABgDQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAOAAQAIAAAEgEQAEgDACgJIADgWIADiLQAAgLgEgDQgEgDgJAAIgLAAQgEAAAAgEIABgCIADgCIBdgBIABACIgBAEQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQgMAAgGADQgGADgCALIgEBWIAHgCIALgEIAcgSIAmgjQAIgJAEgJQAFgJAAgIQAAgKgLAAIgFAAIgCABIgBgEIABgCIABgCIArABIAQgBIANAAIACABIAAACQAAABAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgIAAgKAIIg4A1QgRAPgRAMIBEBSQAJAJAIAGQAGAFAGACQAFACAGAAIABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIABADQAAABgGABIgMACIgjABIgIgEIhRhdIgBAAIgDABIgPAHIAAA7QABAKADAEQACAEAFACIAMABQABAAAAAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAEIgDACIhdABQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBgAO5AvIgKigIAGgDIAagEIAHgBIgLB5IgGAdQgCANgDAFQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgBAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ64, new cjs.Rectangle(-98.2,-13.4,196.5,26.8), null);


(lib.Символ63 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlnCDIgGgFIgIgHIgLgVIgGgIIgKgKIAAgCIABgDIADgBQACAAADADIAHAGIAJANIALgDIAKgFQAGgDAFgGIANgQIhIh6QgHgJgCgBIgJgDIgNgCQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIABgDIACgBIADgBIACAAIAcABIAtgBIARgCIACABIACADQAAAEgFACIgVABIAwBgIAchLIABgNIAAgGQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIgKAAQgEgBgDgCIgBgEIABgBIACgBIA0ACIAIAAIAHgBIADAAQABAAABAAQAAAAABAAQAAAAABABQAAAAAAAAIABgBIACgBICAACIAQgDIAIgCIAEgEIADgEQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIgPA0IgEAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIABgJQAAgDgFgBIgNgDIhBgCIgDAIIgDBBIAYgGQALgCAMAAQAOAAAVAGQAPAFAJAIQAKAJAEALQAEALABAKQAAAMgGALQgFAMgIAIQgKAJgOAGQgNAGgSAAQgPAAgPgDQgPgDgPgGQgDADgHADIgNAFIgZAFQgEAAAAgEIACgDIACgBIAEAAQAIAAAEgFQAEgFACgMQACgLAAgTIABhzQAAgKgDgHQgDgGgEgDQgDgEgEgCIgJgBIgCAAIgBABIgFACIgKABIhnDBQgHAMgCAAgAiRARQgJACgLAEIACBNQAAAFAFAEQADADAHACIALADIANAAQAKAAAJgEQAIgEAFgIQAFgHADgIQADgJAAgJQAAgKgDgJQgCgKgGgHQgGgIgKgEQgJgFgOAAgAA0B9Ig3AEQAAAAgBAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgDACgBIAGAAQAFAAABgCIAAhrQAAglgCgVQgCgVgDgDQgCgCgDgBIgUgBQgBAAAAAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIgCgDQAAgFAEAAICOgBIAzAFQABAAACgFIAJgXQACgGAEAAIAHADQABABAAAAQABABgBAAQAAABAAAAQgBABgBABQgHAFgEAJQgFAJgDANIgEALIgDAPQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgEAAgBgEIgEgIQgFgEgGgEQgHgEgJgDQgKgCgMgBIg6gBIgDBPIA4AAIAjgEIANgDQAFgBADgCQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAIAEABIgJAcIgBAOQAAABAAAAQgBAAAAABQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQgBgFgFgCQgEgDgHgBIhUgCIACBVIA9gDIAlgGQAGgCADgCIAEgHIABgIIACgBIACAAIADABIgCAZIAAAJIAAAMIgCAEgAFGB/IgDgCIgBgCIABgDIAEgBIAVgCIAEgBIACgDIAEgJIADgUIAEiFIhsCpIgCADIgFABIhEADIgDgCIgBgCIABgDIAEgBIAOgBIAHgBIAFgBIABgDQADgFACgNIAEgeIABh9QAAgKgCgDQgDgCgFgBIgTAAIgEgBQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIABgEIADgBIAPABIBOgBIAEAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAEgGABIgMAAQgFABgBADQgFAGgDAYQgDAYABAqIACBCIBhifIAIgKQAEgEAHAAIA2gCIAEAAQAAAAABABQAAAAAAABQAAAAAAABQABAAAAABQgBAEgGABIgRACIgCABQgCAAgCALIgDA4IgCAfIACBOQABAJABACIAEACIAHABIAJABIAJAAIAEABIABACQAAADgCABIgFACgAE2hcIgLgIIgQgPIAVgPIAJAJIAIAGQAFACAEAAIAHgCIAIgEIALgMIAIAHIgBAAIgHAKIgKALIgLAKQgHAEgGAAQgGAAgGgDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ63, new cjs.Rectangle(-43.6,-13.2,87.2,26.5), null);


(lib.Символ62 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIIBnIgDgDIgBgDQAAAAAAAAQAAgBABAAQAAAAABgBQABAAAAAAQAJgBALgGIAqgYIAKgIQACgCACgNIAGhJIgBhIIAsAAIgBAdQACAEAJAFQALADAQAAQAPAAAMgFQAMgGAKgKIADgFQAFgGADgJIAeAAIgLAPIgIAIQgSAOgVAIIgWAGIgVACIgQgBIgLgCIABBIQABALACAEQABAAAAABQABAAAAAAQABABAAAAQABAAABAAIAHABIAPgBIACABIAAADIAAADIgCABIggAFIgkAOIhDAlQgLAGgDAAgA2qA0QAAAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgEADgGQAEgGAGgFQAGgEAKgEQAKgDAOAAIACABIgCgRQAAgGADgNQAEgOAIgPQAIgPAOgPIAOgLIADgCQAKgHALgEIAAgCIA1AAIAyBaIANATQAHAIAEACIAiAFIADABIABADIgCADQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgugEIgyAEIgCgBIgBgCIADgFIgBgCIg3hvIgGADIgIAGQgHAHgGALQgGALgEAPQgDAPAAATQAAAIAEAHQAFAHANAAIAAABIgBAGQAAACgHAAIgHAAIg/AAQgJACgEADQgFADgDAEQgCAFAAAGIgBADIgHABgAV/AiIgPgMIgDgEQgBgCADgDIAQgNIAEgCIAFACIAMALIAEAEIgDAFIgNANIgFADgAoUAaIhCAEQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAgBAAgBQAAgDADgCIAIAAQAFAAABgDIABh6ICtAAIgEAPIAAAAIgCAQQAAABAAAAQAAABgBAAQAAAAgBAAQgBABgBgBQgCgBgBgDQgCgFgFgDQgFgDgJgCIgSgCIhPAAIADBhIBegFIATgEQAHgCAEgDIAEgHIACgKIACgBIADgBIADACIgDAdIAAAKIAAANIgCAEgANwAXQgWgIgRgPQgRgOgKgWQgFgKgDgNQgCgMAAgOIAAgEIABgPIAxAAIAAAGIABAJQABAYAFATQAHAWAMAOIANAMQAHAFAHAEQAPAHARAAQAJAAAIgDQAJgCAGgEQAOgJAKgPQAKgPAFgVQAEgSAAgUIAAgEIgBgLIA0AAIgCAPQgDAQgFAPQgLAZgSATQgRAUgZAMQgZAMgdAAQgbAAgXgHgAxCAXQgWgIgRgPQgRgOgKgWQgFgKgDgNQgBgMAAgOIAAgEIAAgPIAxAAIAAAGIABAJQAAAYAHATQAGAWAMAOIANAMQAHAFAHAEQAPAHARAAQAJAAAIgDQAJgCAGgEQAOgJAKgPQAKgPAFgVQAEgSAAgUIAAgEIAAgLIAzAAIgCAPQgDAQgFAPQgLAZgSATQgRAUgZAMQgZAMgdAAQgbAAgXgHgAGBAbIAAgEIAAgDIABgCIAYgBQAJgCABgDQADgFACgSIAEhdIAtAAIgCBYIACAXQABAGAJACQAJADAPAAIADAAIABAFQAAABAAAAQAAABAAABQAAAAAAABQgBAAAAAAIgEACIh3AAQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBgBAAgAl6AdQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgGAIgBIASgCIAFgBIACgGIAGhyIAsAAIgEBsIAJACIAJACIBAAAQAMAAAFgCIADhuIAvAAIgEBuIASACIAMABIAkAAIALgBIAMgBIAFgsIACgeIAAglIAqAAIgEBgIAAAIQABAKACAEQAEAEAGAAIAWAAIADABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBAAIgDACIgGgBIgLAAIgSgBIgVgBIlKADgATPAaIgCgDIACgDIAEgCQAOAAAIgBQAIgCACgCQAEgHADgZQADgRACg0IgLgCIhuAAIABBaQACALACACIAEACIATADIAKAAIAFABIABADQAAABAAABQAAAAAAABQgBAAAAABQgBAAAAAAIgGACIh4AAIgCgCIgCgDIACgDIADgCQAPAAAIgBQAJgCABgCIAEgSIAEhjIDKAAIAAAPIABBZQABALACACIAFACIATADIAKAAIAFABIABADQAAABgBABQAAAAAAABQAAAAgBABQAAAAgBAAIgFACIgSgBIgRgBIhVACgAr5AaIgCgDIACgDIADgCQAPAAAIgBQAIgCACgCQAEgHADgWQADgWAAgsIgSAOIgTAJIgTAFIgRACQgMAAgIgCQgKgCgGgEQgOgIgJgOIgDgHIgFgPIAqAAQADAHAFAGIACACQAFAGAIADQAJAEAMAAQAFAAAKgDQAJgCAJgGIADgCQAHgFAFgHIADgDIAsAAIgBAPIACBZQABALACACIAEACIAUADIAKAAIAEABIABADQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgGACIh4AAgAAjAaQgDAAgBgFIACgDIACgCIAGABQAIAAAFgEQAFgGACgKQACgNABgUIABhEICPAAQAJAFAHAGIAFAEQAHAIAFAKQAFANAAANQAAAOgGANQgGANgLAKQgKAKgQAGQgQAHgVAAgAB9hiQgLACgMAFIACBYQAAAGAFAEQAEAEAIACIAOAEIAOAAQAMAAAKgFQAKgFAFgHQAHgIADgLQADgKAAgKQAAgMgDgLQgDgLgHgIIgIgIIgKgGQgLgFgQAAgAVxgZIgIgHQgDgDAAgGQABgEAEgHIAtg0IAVAAIgTARQgJAIgHAIQgFAJgBAKQABADACADIAFAGIAGAEIAHABQAAAAAAAAQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAAAAAAAIgNAHIgHADIgGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ62, new cjs.Rectangle(-145.2,-10.4,290.5,21), null);


(lib.Символ61 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AVuBJIABgBQAIgKAFgMQAEgLAAgMQAAgJgCgGQgCgHgFgDQgJgGgOAAQgHAAgHADQgHABgGAFQgFAEgDAFQgEAFACAEQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDAAQgFgDgCgEQgDgFAAgEQAAgDAEgEIAYgRIAhgPQAIgCAHgBQALABAKACQAKADAIAEQAOALAAAXQAAAMgGAKQgHALgJAJIgVASgAQzBJIAChUQAAgLgDgDQgCgDgHgCIgWAAIgEAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgBIBaACIARgCIAFAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAGgIAAIgSACIgFABQgBABgBAIIgGBSIBNADIAQgBIAbgCIgBhLQAAgLgDgDQgDgDgHgCIgWAAIgDAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBIADgBIA8ACIAwgCIAEAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAGgIAAIgTACIgEABQgCABgBAMIgFBBIgBAWgAPMBJQgBgPgEgWQgHgVgLgPQgLgPgOgHQgPgIgQAAQgTAAgPAIQgOAIgLAOQgKAPgFATQgFASgBAVIgxAAQACgTAIgRQAMgZATgRQAJgIALgIQALgGAMgFQAMgFANgDQAMgBANAAQAZgBAXAIQALADAKAGQAKAFAJAHQARANAKAVQAFAKADAMQACAMAAANIAAAFgAK7BJIADgIQAFgRAAgVQAAgQgEgNQgGgNgIgIQgIgJgLgGQgLgFgNAAIgOADIgNADIgJAGIgEAFIgDBjIgsAAIgBhOQgBgOgCgGQgCgFgDgBIgQABIgDgBIAAgEQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAAAgBIAHAAIA3ABIAEgBIAmgMQALgCALAAQAqAAAYASQAYARAAAfQAAANgDAMQgCAMgFAKIgIANgAGEBJIADhUIgzACIgTAEQgHABgDADIgIAHIgGAJIgCgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAGgLIAPgwIABgBIAEAAQAAAAABAAQABAAAAAAQAAAAABAAQAAABAAAAIgBAIQAAACAIABICWACQATgBALgDQAKgCADgCIAFgGQAAgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABABIgFALIgMAvIgFACQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIACgJQAAgDgGgCIgQgDIg0gDIgDAKIgCBLgAAXBJIAAhDIgBgKIgDgLIgFgJQgDgDgEgBIgQAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAIAEgBIBoAAIAFAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABQAAAGgHABIgHAAIgMABIgEACIgDAFIgHAjIgBA5QAOgEAOgDQAOgDANAAQAQABAYAFIALAFgAhmBJIAAggIgBggIgBgWIgDgKIgIgEIgPgCIgFgBIgBgCQAAgBAAgBQAAgBABAAQAAgBAAAAQABgBAAAAIAGgBIAMABIAPAAIBEgBIAFgBIADACIABAEIgBADIgEABIgLAAIgHACIgDACIgCADQgCADgCAOIgDBOgAjwBJIAChWIgDgKIgFgCIgIgCIgVgCIgEgBIgBgCQAAgDACgCIAGgBIBpAAIAFgBIADACIABAEIgBADIgEABIgLAAIgHACIgDACIgCADQgDAGgCAQIgCBJgAl+BJIgBhUIgCgMIgGgCIgdgEIgEgBIgBgCQAAgDACgCIAFgBIBpAAIAGgBIADACIABAEIgCADIgDABIgMAAIgGACIgDACIgCADQgDAGgCAQIgCBJgApvBJQAAgsgCgYQgDgYgDgDQgCgDgEgBIgSgCIgGABQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBIgBgDQAAgFAEgBIDJABIAYAEQACAAABgGIALgbQADgGAFAAIAIAEQACACgFADQgIAGgFAKQgFALgEAOIgEANIgDARQAAABAAAAQgBABAAAAQgBAAAAAAQgBABgBAAQgEgBgBgFIgGgIIgNgKQgHgEgLgDQgLgCgNgBIhFgBIgEBbIAkABIBHgGIAPgDQAGgCADgDQAAAAAAgBQABAAAAAAQABgBAAAAQABAAABAAIADACIgFATgAr3BJQAEgHAAgJIAAgxIgBgTQAAgLgDgDQgDgDgGgCIgWAAIgEAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgBIBaACIARgCIAFAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAGgIAAIgSACIgFABQgBABgCAMIgFBBIAAAWgAuABJIgDgLQgDgRAAgUIAAgkQAAgLgCgDQgDgDgIgCIgVAAIgEAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgBIA7ACIAtgCIAEAAQABABAAAAQABAAAAABQAAAAABABQAAAAAAABQAAAGgIAAIgNACIgIACIgFBDQAAATAFANgAvlBJQgCgPgEgWQgHgVgLgPQgLgPgOgHQgPgIgQAAQgTAAgPAIQgOAIgLAOQgKAPgFATQgFASgBAVIgxAAQADgTAHgRQAMgZATgRQAJgIALgIQALgGAMgFQAMgFANgDQAMgBANAAQAZgBAXAIQALADAKAGQAKAFAJAHQARANAKAVQAFAKADAMQACAMAAANIAAAFgA1VBJIgshLIgRgWIgKgDIgIAAIgHgCQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIABgDIADgCIADgBIACAAIAgABQAkAAARgBIATgCIAEABIABAEQAAADgDACIgHABIgUABIApBUQALgFAJgIQAJgHAHgIQAHgJADgMQAFgKAAgNQAAgGgFgCIgIgDIgKgBQgEgBAAgDQAAgFADgBIAzABIAZgCQAGABAAAFIgDABIgBAAIgBABIgBAAQgHAGgJAMIgUAbQgLAPgPAOQgVASgMAGIAEAGg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ61, new cjs.Rectangle(-145.4,-7.3,290.9,14.6), null);


(lib.Символ58 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AmJCnIgEgDIgBgDQAAgBAAAAQABAAAAgBQABAAAAAAQABgBABAAQAIgBAMgFIApgYIALgJQABgCACgNIAHhKIgCiVQgBgPgCgFQgCgGgDAAIgRABIgDgBIAAgEQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAIAHAAIA3ABIAEgBIAmgMQAKgCALAAQAqAAAZASQAXARAAAgQAAANgCALQgDAMgFALQgKAVgRAOQgSAPgVAHIgWAFIgVACIgPAAIgMgDIACBKQABALACADQAAABAAAAQABABAAAAQABAAAAAAQABABABAAIAHAAIAQgBIABACIAAADIAAACIgBABIghAGIgkANIhDAmQgKAFgEAAgAjxibIgMAEIgJAGIgEAFIgFCAQACAFAKAEQAKADAQAAQAPAAANgEQAMgGAJgLQAJgLAFgRQAFgQAAgVQAAgRgFgNQgFgNgIgJQgJgJgLgFQgKgFgOAAgAHsBhIgPgMIgDgDQAAgCADgEIAPgNIAEgDIAFADIANALIADAFIgDAFIgNANIgFADgAghBWQgXgIgRgPQgRgPgKgVQgFgLgCgNQgDgLAAgOQAAgeAMgZQALgZATgRQAKgJALgHQAKgGAMgGQANgEAMgDQAMgCANAAQAZAAAWAHQALAEALAFQAJAGAJAHQARANALAWQAEAKADAMQADALAAAOQAAAZgKAYQgLAagSATQgRAUgZANQgZAMgdAAQgaAAgWgIgAgNiIQgPAIgKAOQgKAPgGAUQgFAUAAAYQAAAeAHAVQAHAWAMAPIAMAMQAHAGAIADQAOAIAQAAQAJAAAIgDQAJgCAHgFQAOgJAJgQQAKgPAFgUQAEgTAAgWQAAgSgGgeQgGgWgLgPQgLgPgPgHQgPgIgQAAQgSAAgOAIgAoQBaIgBgDIABgDIABgCIAXgCQAJgBABgDQADgGACgSIAHixIgzACIgSAEQgIABgDADIgHAIIgGAJIgDgBQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAAAAAgBIAGgLIAPgwIACgBIADgBQABAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIgBAHQAAADAIABICWACQAUgCAKgCQAKgCAEgDIAEgGQAAAAABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABIgEALIgNAwIgFABQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIACgKQAAgDgGgCIgPgDIg0gDIgDAKIgFCjIACAYQACAGAIACQAJACAPAAIAEABIABAEQAAABAAABQAAABgBAAQAAABAAAAQAAAAgBABIgEABIh3ABQAAAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBgAE8BaIgBgDIABgDIAEgCQAOAAAIgCQAJgBACgDQADgGAEgaQADgRABg0IgLgBIhtAAIABBZQABAMACABIAFADIATADIAKAAIAEAAIACAEQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgFABIh5ABIgCgCIgCgDIACgDIADgCQAPAAAIgCQAJgBABgDIAFgSIADghIADiWQAAgLgDgDQgDgEgHgBIgVAAIgFAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAIAEgBIBaACIASgCIAEAAQABAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAGgHAAIgTACIgEABQgBABgCAIIgGBTIBOADIAQgBIAagDIAAhLQgBgLgCgDQgDgEgHgBIgWAAIgEAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAgBAAAAQAAgBAAgBQAAgBABAAQAAgBAAAAQABgBAAAAIAEgBIA7ACIAwgCIAFAAQAAAAABABQAAAAABABQAAAAAAABQAAAAAAABQAAAGgIAAIgTACIgDABQgCABgCAMIgEBCIgCAlIACBYQABAMACABIAEADIAUADIAJAAIAFAAIABAEQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgFABIgRgBIgSAAIhVACgAHfAlIgIgGQgDgEAAgFQAAgFAEgGIAtg0QAIgKAFgMQAFgLAAgMQAAgJgDgHQgCgGgFgDQgJgHgNAAQgHAAgHADQgIACgFAFQgGAEgDAFQgDAFABAEQAAABAAAAQAAABAAAAQAAABAAAAQAAAAAAABIgDAAQgFgDgDgFQgDgEAAgFQAAgCAEgEIAZgSIAhgPQAIgDAGAAQAMAAAKADQAJACAIAFQAPAKAAAYQgBAMgGALQgGAKgJAJIgoAjQgJAIgGAJQgGAHAAAKQAAADACAEIAFAFIAHAEIAGABQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgMAGIgIADIgGABg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ58, new cjs.Rectangle(-58,-16.8,116.2,33.7), null);


(lib.Символ57 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtOCXQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgFADgFQADgGAGgFQAGgFALgDQAJgDAOgBIACABIgBgQQAAgIADgNQADgNAIgQQAIgPAPgOQAHgHAKgHQAJgGAMgEIgshNIgSgWIgJgDIgJAAIgGgCQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIABgDIADgCIADgBIADAAIAgACQAkAAARgCIATgDIADACIACAEQAAADgDACIgIABIgTABIApBVQAKgFAKgHQAJgIAGgIQAHgKAEgLQAEgLAAgNQAAgFgEgDIgJgDIgJgBQgEgBAAgDQAAgGADAAIAzACIAYgDQAHAAAAAGIgDABIgCAAIgBABIgBAAQgHAGgIAMIgUAcQgMAPgOAOQgVASgMAGIA1BfIAOATQAGAIAFADIAiAFIACABIABACIgCAEQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgugEIgxAEIgDgBIAAgCIACgFIAAgCIg4hwQgGACgIAHQgHAGgGALQgGAMgDAOQgEAPAAAUQAAAIAFAIQAFAGAMAAIAAABIAAAGQgBADgGAAIgHgBIhAABQgIACgFADQgFADgDAEQgCAFAAAGIgBACIgGACgABGB8IhBAFQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQABgDADgCIAIAAQAFgBAAgCIABh6QAAgrgDgZQgCgZgDgEQgDgCgEgBIgQgBIgGAAQgBAAAAAAQgBAAgBAAQAAgBAAAAQgBAAAAgBIgCgDQAAgGAFAAIDHACIAYADQACAAACgGIAKgbQADgGAFAAIAIADQADADgFADQgIAGgFAKQgFAKgEAPIgEANIgDASQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQgEAAgBgGIgGgJIgNgKQgIgDgLgEQgKgDgOgBIhEAAIgEBbIAkABIBGgEIAPgEQAHgCACgDQAAgBABAAQAAAAABAAQAAgBABAAQABAAAAABIAEABIgKAgIgBAQQAAABgBABQAAABgBAAQAAAAgBAAQAAAAgBAAQgDgBgBgDQgCgGgFgDQgFgDgIgBIgTgCIhPAAIADBiIBegFIATgFQAIgDADgCIAFgHIACgKIABgBIADgBIADACIgDAdIAAAKIAAAOIgCAEgAnmB5QgXgHgRgQQgRgPgKgVQgFgKgCgNQgCgMAAgOQAAgeALgYQALgaATgRQAKgIALgIQAKgGANgGQAMgEAMgDQANgCANAAQAZAAAWAIQAMADAKAGQAJAFAJAHQASAOAKAVQAEAKADAMQADAMAAANQAAAZgKAZQgKAZgTATQgRAVgZAMQgZAMgdAAQgbAAgWgIgAnShlQgPAIgKAPQgKAOgGAVQgFAUAAAXQAAAeAHAVQAHAXAMAOIAMANQAHAFAIAEQAPAHAQAAQAJAAAIgDQAJgCAHgFQAOgJAKgPQAJgPAFgVQAFgUAAgWQAAgRgHgeQgGgVgLgPQgLgQgPgHQgPgIgQAAQgSAAgPAIgADhCAQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAgBQAAgFAHgBIATgCIAEgBIACgGIAGhVIAAhyIgDgNIgFgBIgdgEIgFgBIgBgDQAAgCADgCIAFgBIBpAAIAFgBIADACIABAEIgBADIgEABIgLAAIgGACIgEACIgBACQgDAHgDAQIgFC2IAIACIAKABIBAABQALAAAGgDIACgUIADiwIgDgLIgFgBIgJgCIgUgCIgFgBIgBgDQAAgCADgCIAFgBIBpAAIAFgBIADACIABAEIgBADIgEABIgLAAIgGACIgEACIgBACQgDAHgDAQIgFC4IARACIANAAIAjAAIALAAIANgCIAEgsIACgeIAAhEIgBggIgCgYIgCgKIgJgDIgPgCIgEgBIgBgDQAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAIAFgBIANABIAOABIBEgCIAGgBIADACIAAAEIgBADIgEABIgLAAIgGACIgDACIgCACQgCAEgCAOIgIBtIAABAIABAJQAAALADAEQADADAHABIAWAAIADABQABAAAAAAQABABAAAAQAAABAAAAQAAABAAABQAAABAAAAQAAABAAABQAAAAgBAAQAAABgBAAIgDACIgFgBIgNAAIgSgBIgVgBIlKADgAieB9IgCgDIACgDIADgCQAPAAAIgCQAIgBACgCQAEgHADgXQAEgXAAgrIgTAOIgTAJIgTAFIgRACQgLAAgJgDQgJgBgHgEQgOgIgIgOQgIgOgDgRQgDgSAAgTIAAgmQAAgKgDgEQgDgEgHgBIgWAAIgEAAQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAEgBIA8ACIAsgCIAFAAQAAABABAAQAAAAABABQAAAAAAABQAAAAAAABQAAAGgIAAIgMACIgJACIgFBEQAAAdANAOQAGAIAJAEQAJADAMABQAGgBAJgCQAJgCAJgGQAJgGAHgHQAHgJAAgKIAAgwIgBgVQgBgKgCgEQgDgEgHgBIgVAAIgFAAQAAAAAAgBQgBAAAAAAQAAgBAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAEgBIBaACIASgCIAEAAQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAGgHAAIgTADIgEABQgCAAgBAMIgFBCIgBAkIABBZQABAMACACIAFACIATADIAKAAIAEABIACADQAAABAAAAQgBABAAABQAAAAgBAAQAAABgBAAIgFACIh4AAgAJ+B8QgDAAAAgEIABgDIACgCIAGABQAJAAAEgEQAFgGADgMQACgMAAgVIABiFIgBgLIgEgLIgFgJQgDgEgEAAIgRAAIgEgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAgBAAAAQAAgBABAAIAEgBIBpAAIAFAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAABQAAAGgIABIgGAAIgMACIgFABIgCAFIgHAkIgBA5QAOgEANgDQAOgCAOAAQAPAAAZAFQARAHALAIQALAJAFANQAFANAAANQAAAOgGANQgFANgLAKQgLAKgQAHQgQAGgUABgALYAAQgLACgMAEIACBZQAAAHAFAEQAFAEAHACIAOADIAOABQAMAAAKgFQAKgFAGgJQAGgHADgLQADgKAAgKQAAgMgDgLQgDgLgGgJQgIgIgLgFQgLgFgQAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ57, new cjs.Rectangle(-84.9,-15.2,169.9,30.4), null);


(lib.Символ54 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.qwe();
	this.instance.parent = this;
	this.instance.setTransform(-11.2,-11.9,0.746,0.746);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ54, new cjs.Rectangle(-11.2,-11.9,22.4,23.9), null);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.wer();
	this.instance.parent = this;
	this.instance.setTransform(-24.6,-22.7,0.746,0.746);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ53, new cjs.Rectangle(-24.6,-22.7,49.3,45.5), null);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.mech();
	this.instance.parent = this;
	this.instance.setTransform(-140,-127);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ50, new cjs.Rectangle(-140,-127,280,254), null);


(lib.Символ48 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A6ybgMAAAg2/MA1lAAAMAAAA2/g");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A7ObPMAAAg2dMA2dAAAMAAAA2dg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgxiAY7MAAAgx1MBjFAAAMAAAAx1g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ46, new cjs.Rectangle(-317,-159.5,634.2,319.1), null);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dym();
	this.instance.parent = this;
	this.instance.setTransform(-102.9,-189.2,0.757,0.757);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ40, new cjs.Rectangle(-102.9,-189.2,205.9,378.5), null);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#66FF33").s().p("Ah8AVQgFgDADgGQAMgXAgADQAFAAAFgBQAjgGABAbQABAJgIAEQgUAJgSAAQgXAAgUgNgAA/ADQgFgDACgGIAFgLQAEgKAKgEQAbgFASAJQAFACgBAFQABASgcAJQgLADgIAAQgMAAgHgHg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ah/AXQgFgEADgHQANgfAjAEQAGABAGgCQAmgIACAkQABAMgJAFQgWAMgVAAQgYAAgXgSgAA7AIQgGgGADgGIAGgPQAEgNALgFQAegHAUAMQAFACAAAHQABAXggAMQgLAEgKAAQgNAAgIgIg");
	this.shape_1.setTransform(-0.2,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ31, new cjs.Rectangle(-13.3,-4.1,26.3,8.1), null);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_03();
	this.instance.parent = this;
	this.instance.setTransform(-35,-39);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ30, new cjs.Rectangle(-35,-39,70,78), null);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_062();
	this.instance.parent = this;
	this.instance.setTransform(-14.3,-55.8,0.988,0.988);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ25, new cjs.Rectangle(-14.3,-55.8,28.7,111.6), null);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-300,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ24, new cjs.Rectangle(-300,-150,600,300), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.ball();
	this.instance.parent = this;
	this.instance.setTransform(-19.1,-20.1,0.191,0.191);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(-19.1,-20.1,38.3,40.2), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_09();
	this.instance.parent = this;
	this.instance.setTransform(-35.5,-32.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(-35.5,-32.5,71,65), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_121();
	this.instance.parent = this;
	this.instance.setTransform(-51.5,-163.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(-51.5,-163.5,103,327), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_21();
	this.instance.parent = this;
	this.instance.setTransform(-51,-90);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(-51,-90,102,180), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.lightn();
	this.instance.parent = this;
	this.instance.setTransform(52.4,8.4,0.349,0.349,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(-52.3,-8.3,104.7,16.8), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgyZAa4MAAAg1vMBkzAAAMAAAA1vg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(-322.6,-172,645.2,344.1), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.log();
	this.instance.parent = this;
	this.instance.setTransform(-40.2,-29,0.537,0.537);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(-40.2,-29,80.6,58), null);


(lib.Символ111 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ110();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ111, new cjs.Rectangle(-32,-32,64,64), null);


(lib.Символ95 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 93
	this.instance = new lib.Символ93();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:-0.5,rotation:5.6,x:0.1,y:-0.5},0).wait(1).to({rotation:11.3},0).wait(1).to({rotation:16.9,x:0.2},0).wait(1).to({rotation:22.5,y:-0.4},0).wait(1).to({rotation:28.1,x:0.3},0).wait(1).to({rotation:33.8},0).wait(1).to({rotation:39.4},0).wait(1).to({rotation:45,x:0.4,y:-0.3},0).wait(1).to({rotation:50.6},0).wait(1).to({rotation:56.3},0).wait(1).to({rotation:61.9,x:0.5,y:-0.2},0).wait(1).to({rotation:67.5},0).wait(1).to({rotation:73.1,y:-0.1},0).wait(1).to({rotation:78.8},0).wait(1).to({rotation:84.4,y:0},0).wait(1).to({rotation:90},0).wait(1).to({rotation:95.6,y:0.1},0).wait(1).to({rotation:101.3},0).wait(1).to({rotation:106.9,y:0.2},0).wait(1).to({rotation:112.5},0).wait(1).to({rotation:118.1,y:0.3},0).wait(1).to({rotation:123.8,x:0.4},0).wait(1).to({rotation:129.4},0).wait(1).to({rotation:135,y:0.4},0).wait(1).to({rotation:140.6,x:0.3},0).wait(1).to({rotation:146.3},0).wait(1).to({rotation:151.9,y:0.5},0).wait(1).to({rotation:157.5,x:0.2},0).wait(1).to({rotation:163.1},0).wait(1).to({rotation:168.8,x:0.1},0).wait(1).to({rotation:174.4},0).wait(1).to({rotation:180,x:0},0).wait(1).to({rotation:185.6},0).wait(1).to({rotation:191.3,x:-0.1},0).wait(1).to({rotation:196.9},0).wait(1).to({rotation:202.5,x:-0.2},0).wait(1).to({rotation:208.1},0).wait(1).to({rotation:213.8,x:-0.3,y:0.4},0).wait(1).to({rotation:219.4},0).wait(1).to({rotation:225},0).wait(1).to({rotation:230.6,x:-0.4,y:0.3},0).wait(1).to({rotation:236.3},0).wait(1).to({rotation:241.9},0).wait(1).to({rotation:247.5,y:0.2},0).wait(1).to({rotation:253.1,x:-0.5},0).wait(1).to({rotation:258.8,y:0.1},0).wait(1).to({rotation:264.4},0).wait(1).to({rotation:270,y:0},0).wait(1).to({rotation:275.6},0).wait(1).to({rotation:281.3,y:-0.1},0).wait(1).to({rotation:286.9},0).wait(1).to({rotation:292.5,x:-0.4,y:-0.2},0).wait(1).to({rotation:298.1},0).wait(1).to({rotation:303.8,y:-0.3},0).wait(1).to({rotation:309.4},0).wait(1).to({rotation:315,x:-0.3},0).wait(1).to({rotation:320.6,y:-0.4},0).wait(1).to({rotation:326.3},0).wait(1).to({rotation:331.9,x:-0.2},0).wait(1).to({rotation:337.5},0).wait(1).to({rotation:343.1,x:-0.1,y:-0.5},0).wait(1).to({rotation:348.8},0).wait(1).to({rotation:354.4,x:0},0).wait(1).to({rotation:360},0).wait(1));

	// Символ 92
	this.instance_1 = new lib.Символ92();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({rotation:-11.2},0).wait(1).to({rotation:-22.5},0).wait(1).to({rotation:-33.7},0).wait(1).to({rotation:-45},0).wait(1).to({rotation:-56.2},0).wait(1).to({rotation:-67.5},0).wait(1).to({rotation:-78.7},0).wait(1).to({rotation:-90},0).wait(1).to({rotation:-101.2},0).wait(1).to({rotation:-112.5},0).wait(1).to({rotation:-123.7},0).wait(1).to({rotation:-135},0).wait(1).to({rotation:-146.2},0).wait(1).to({rotation:-157.5},0).wait(1).to({rotation:-168.7},0).wait(1).to({rotation:-180},0).wait(1).to({rotation:-191.2},0).wait(1).to({rotation:-202.5},0).wait(1).to({rotation:-213.7},0).wait(1).to({rotation:-225},0).wait(1).to({rotation:-236.2},0).wait(1).to({rotation:-247.5},0).wait(1).to({rotation:-258.7},0).wait(1).to({rotation:-270},0).wait(1).to({rotation:-281.2},0).wait(1).to({rotation:-292.5},0).wait(1).to({rotation:-303.7},0).wait(1).to({rotation:-315},0).wait(1).to({rotation:-326.2},0).wait(1).to({rotation:-337.5},0).wait(1).to({rotation:-348.7},0).wait(1).to({rotation:-360},0).wait(1).to({rotation:-371.2},0).wait(1).to({rotation:-382.5},0).wait(1).to({rotation:-393.7},0).wait(1).to({rotation:-405},0).wait(1).to({rotation:-416.2},0).wait(1).to({rotation:-427.5},0).wait(1).to({rotation:-438.7},0).wait(1).to({rotation:-450},0).wait(1).to({rotation:-461.2},0).wait(1).to({rotation:-472.5},0).wait(1).to({rotation:-483.7},0).wait(1).to({rotation:-495},0).wait(1).to({rotation:-506.2},0).wait(1).to({rotation:-517.5},0).wait(1).to({rotation:-528.7},0).wait(1).to({rotation:-540},0).wait(1).to({rotation:-551.2},0).wait(1).to({rotation:-562.5},0).wait(1).to({rotation:-573.7},0).wait(1).to({rotation:-585},0).wait(1).to({rotation:-596.2},0).wait(1).to({rotation:-607.5},0).wait(1).to({rotation:-618.7},0).wait(1).to({rotation:-630},0).wait(1).to({rotation:-641.2},0).wait(1).to({rotation:-652.5},0).wait(1).to({rotation:-663.7},0).wait(1).to({rotation:-675},0).wait(1).to({rotation:-686.2},0).wait(1).to({rotation:-697.5},0).wait(1).to({rotation:-708.7},0).wait(1).to({rotation:-720},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33,-31,66,61);


(lib.Символ59 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 64
	this.instance = new lib.Символ64();
	this.instance.parent = this;
	this.instance.setTransform(49,-22.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(79).to({_off:false},0).to({y:-0.1,alpha:1},7,cjs.Ease.get(1)).wait(31).to({y:-6.5},2).to({y:15.9,alpha:0},6).wait(1));

	// Символ 63
	this.instance_1 = new lib.Символ63();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-99.6,-26.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(76).to({_off:false},0).to({y:-4.3,alpha:1},7,cjs.Ease.get(1)).wait(31).to({y:-10.7},2).to({y:11.7,alpha:0},6).to({_off:true},1).wait(3));

	// Слой 5
	this.instance_2 = new lib.Символ62();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-2.1,7.3);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(65).to({_off:false},0).to({y:8},3,cjs.Ease.get(1)).to({scaleY:1.07,skewX:-20.9,x:1.8},4,cjs.Ease.get(1)).to({x:-56.9,alpha:0},4,cjs.Ease.get(1)).to({_off:true},1).wait(49));

	// Символ 58
	this.instance_3 = new lib.Символ61();
	this.instance_3.parent = this;
	this.instance_3.setTransform(2,-10.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(65).to({_off:false},0).to({y:-11.5},3,cjs.Ease.get(1)).to({scaleY:1.28,skewX:38.8,x:7.8},4,cjs.Ease.get(1)).to({x:-50.9,alpha:0},4,cjs.Ease.get(1)).to({_off:true},1).wait(49));

	// Символ 58
	this.instance_4 = new lib.Символ58();
	this.instance_4.parent = this;
	this.instance_4.setTransform(89.3,0.9);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(6).to({y:-109.1},0).to({y:10.9,alpha:1},5).to({y:0.9},2).wait(51).to({_off:true},1).wait(61));

	// Символ 57
	this.instance_5 = new lib.Символ57();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-62.4,-2.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({y:-112.6},0).to({y:7.4,alpha:1},5).to({y:-2.6},2).wait(56).to({_off:true},1).wait(61));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-147.4,-17.8,294.8,35.6);


(lib.Символ56 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ59();
	this.instance.parent = this;
	this.instance.setTransform(60,10);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ56, new cjs.Rectangle(-87.4,-7.8,294.8,35.6), null);


(lib.Символ52 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// wer
	this.instance = new lib.Символ53();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:3},0).wait(1).to({rotation:6.1},0).wait(1).to({rotation:9.1},0).wait(1).to({rotation:12.1},0).wait(1).to({rotation:15.1},0).wait(1).to({rotation:18.2},0).wait(1).to({rotation:21.2},0).wait(1).to({rotation:24.2},0).wait(1).to({rotation:27.2},0).wait(1).to({rotation:30.3},0).wait(1).to({rotation:33.3},0).wait(1).to({rotation:36.3},0).wait(1).to({rotation:39.3},0).wait(1).to({rotation:42.4},0).wait(1).to({rotation:45.4},0).wait(1).to({rotation:48.4},0).wait(1).to({rotation:51.4},0).wait(1).to({rotation:54.5},0).wait(1).to({rotation:57.5},0).wait(1).to({rotation:60.5},0).wait(1).to({rotation:63.5},0).wait(1).to({rotation:66.6},0).wait(1).to({rotation:69.6},0).wait(1).to({rotation:72.6},0).wait(1).to({rotation:75.6},0).wait(1).to({rotation:78.7},0).wait(1).to({rotation:81.7},0).wait(1).to({rotation:84.7},0).wait(1).to({rotation:87.7},0).wait(1).to({rotation:90.8},0).wait(1).to({rotation:93.8},0).wait(1).to({rotation:96.8},0).wait(1).to({rotation:99.8},0).wait(1).to({rotation:102.9},0).wait(1).to({rotation:105.9},0).wait(1).to({rotation:108.9},0).wait(1).to({rotation:111.9},0).wait(1).to({rotation:115},0).wait(1).to({rotation:118},0).wait(1).to({rotation:121},0).wait(1).to({rotation:124},0).wait(1).to({rotation:127.1},0).wait(1).to({rotation:130.1},0).wait(1).to({rotation:133.1},0).wait(1).to({rotation:136.1},0).wait(1).to({rotation:139.2},0).wait(1).to({rotation:142.2},0).wait(1).to({rotation:145.2},0).wait(1).to({rotation:148.2},0).wait(1).to({rotation:151.3},0).wait(1).to({rotation:154.3},0).wait(1).to({rotation:157.3},0).wait(1).to({rotation:160.3},0).wait(1).to({rotation:163.4},0).wait(1).to({rotation:166.4},0).wait(1).to({rotation:169.4},0).wait(1).to({rotation:172.4},0).wait(1).to({rotation:175.5},0).wait(1).to({rotation:178.5},0).wait(1).to({rotation:181.5},0).wait(1).to({rotation:184.5},0).wait(1).to({rotation:187.6},0).wait(1).to({rotation:190.6},0).wait(1).to({rotation:193.6},0).wait(1).to({rotation:196.6},0).wait(1).to({rotation:199.7},0).wait(1).to({rotation:202.7},0).wait(1).to({rotation:205.7},0).wait(1).to({rotation:208.7},0).wait(1).to({rotation:211.8},0).wait(1).to({rotation:214.8},0).wait(1).to({rotation:217.8},0).wait(1).to({rotation:220.8},0).wait(1).to({rotation:223.9},0).wait(1).to({rotation:226.9},0).wait(1).to({rotation:229.9},0).wait(1).to({rotation:232.9},0).wait(1).to({rotation:236},0).wait(1).to({rotation:239},0).wait(1).to({rotation:242},0).wait(1).to({rotation:245},0).wait(1).to({rotation:248.1},0).wait(1).to({rotation:251.1},0).wait(1).to({rotation:254.1},0).wait(1).to({rotation:257.1},0).wait(1).to({rotation:260.2},0).wait(1).to({rotation:263.2},0).wait(1).to({rotation:266.2},0).wait(1).to({rotation:269.2},0).wait(1).to({rotation:272.3},0).wait(1).to({rotation:275.3},0).wait(1).to({rotation:278.3},0).wait(1).to({rotation:281.3},0).wait(1).to({rotation:284.4},0).wait(1).to({rotation:287.4},0).wait(1).to({rotation:290.4},0).wait(1).to({rotation:293.4},0).wait(1).to({rotation:296.5},0).wait(1).to({rotation:299.5},0).wait(1).to({rotation:302.5},0).wait(1).to({rotation:305.5},0).wait(1).to({rotation:308.6},0).wait(1).to({rotation:311.6},0).wait(1).to({rotation:314.6},0).wait(1).to({rotation:317.6},0).wait(1).to({rotation:320.7},0).wait(1).to({rotation:323.7},0).wait(1).to({rotation:326.7},0).wait(1).to({rotation:329.7},0).wait(1).to({rotation:332.8},0).wait(1).to({rotation:335.8},0).wait(1).to({rotation:338.8},0).wait(1).to({rotation:341.8},0).wait(1).to({rotation:344.9},0).wait(1).to({rotation:347.9},0).wait(1).to({rotation:350.9},0).wait(1).to({rotation:353.9},0).wait(1).to({rotation:357},0).wait(1).to({rotation:360},0).wait(1));

	// qwe
	this.instance_1 = new lib.Символ54();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.6,-0.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({rotation:-6.1},0).wait(1).to({rotation:-12.1},0).wait(1).to({rotation:-18.2},0).wait(1).to({rotation:-24.2},0).wait(1).to({rotation:-30.3},0).wait(1).to({rotation:-36.3},0).wait(1).to({rotation:-42.4},0).wait(1).to({rotation:-48.4},0).wait(1).to({rotation:-54.5},0).wait(1).to({rotation:-60.5},0).wait(1).to({rotation:-66.6},0).wait(1).to({rotation:-72.6},0).wait(1).to({rotation:-78.7},0).wait(1).to({rotation:-84.7},0).wait(1).to({rotation:-90.8,y:-0.9},0).wait(1).to({rotation:-96.8},0).wait(1).to({rotation:-102.9},0).wait(1).to({rotation:-108.9},0).wait(1).to({rotation:-115},0).wait(1).to({rotation:-121},0).wait(1).to({rotation:-127.1},0).wait(1).to({rotation:-133.1},0).wait(1).to({rotation:-139.2},0).wait(1).to({rotation:-145.2},0).wait(1).to({rotation:-151.3},0).wait(1).to({rotation:-157.3},0).wait(1).to({rotation:-163.4},0).wait(1).to({rotation:-169.4},0).wait(1).to({rotation:-175.5},0).wait(1).to({rotation:-181.5},0).wait(1).to({rotation:-187.6},0).wait(1).to({rotation:-193.6},0).wait(1).to({rotation:-199.7},0).wait(1).to({rotation:-205.7},0).wait(1).to({rotation:-211.8},0).wait(1).to({rotation:-217.8},0).wait(1).to({rotation:-223.9},0).wait(1).to({rotation:-229.9},0).wait(1).to({rotation:-236},0).wait(1).to({rotation:-242},0).wait(1).to({rotation:-248.1},0).wait(1).to({rotation:-254.1},0).wait(1).to({rotation:-260.2},0).wait(1).to({rotation:-266.2},0).wait(1).to({rotation:-272.3,y:-0.8},0).wait(1).to({rotation:-278.3},0).wait(1).to({rotation:-284.4},0).wait(1).to({rotation:-290.4},0).wait(1).to({rotation:-296.5},0).wait(1).to({rotation:-302.5},0).wait(1).to({rotation:-308.6},0).wait(1).to({rotation:-314.6},0).wait(1).to({rotation:-320.7},0).wait(1).to({rotation:-326.7},0).wait(1).to({rotation:-332.8},0).wait(1).to({rotation:-338.8},0).wait(1).to({rotation:-344.9},0).wait(1).to({rotation:-350.9},0).wait(1).to({rotation:-357},0).wait(1).to({rotation:-363},0).wait(1).to({rotation:-369.1},0).wait(1).to({rotation:-375.1},0).wait(1).to({rotation:-381.2},0).wait(1).to({rotation:-387.2},0).wait(1).to({rotation:-393.3},0).wait(1).to({rotation:-399.3},0).wait(1).to({rotation:-405.4},0).wait(1).to({rotation:-411.4},0).wait(1).to({rotation:-417.5},0).wait(1).to({rotation:-423.5},0).wait(1).to({rotation:-429.6},0).wait(1).to({rotation:-435.6},0).wait(1).to({rotation:-441.7},0).wait(1).to({rotation:-447.7},0).wait(1).to({rotation:-453.8,y:-0.9},0).wait(1).to({rotation:-459.8},0).wait(1).to({rotation:-465.9},0).wait(1).to({rotation:-471.9},0).wait(1).to({rotation:-478},0).wait(1).to({rotation:-484},0).wait(1).to({rotation:-490.1},0).wait(1).to({rotation:-496.1},0).wait(1).to({rotation:-502.2},0).wait(1).to({rotation:-508.2},0).wait(1).to({rotation:-514.3},0).wait(1).to({rotation:-520.3},0).wait(1).to({rotation:-526.4},0).wait(1).to({rotation:-532.4},0).wait(1).to({rotation:-538.5},0).wait(1).to({rotation:-544.5},0).wait(1).to({rotation:-550.6},0).wait(1).to({rotation:-556.6},0).wait(1).to({rotation:-562.7},0).wait(1).to({rotation:-568.7},0).wait(1).to({rotation:-574.8},0).wait(1).to({rotation:-580.8},0).wait(1).to({rotation:-586.9},0).wait(1).to({rotation:-592.9},0).wait(1).to({rotation:-599},0).wait(1).to({rotation:-605},0).wait(1).to({rotation:-611.1},0).wait(1).to({rotation:-617.1},0).wait(1).to({rotation:-623.2},0).wait(1).to({rotation:-629.2},0).wait(1).to({rotation:-635.3,y:-0.8},0).wait(1).to({rotation:-641.3},0).wait(1).to({rotation:-647.4},0).wait(1).to({rotation:-653.4},0).wait(1).to({rotation:-659.5},0).wait(1).to({rotation:-665.5},0).wait(1).to({rotation:-671.6},0).wait(1).to({rotation:-677.6},0).wait(1).to({rotation:-683.7},0).wait(1).to({rotation:-689.7},0).wait(1).to({rotation:-695.8},0).wait(1).to({rotation:-701.8},0).wait(1).to({rotation:-707.9},0).wait(1).to({rotation:-713.9},0).wait(1).to({rotation:-720},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.6,-22.7,49.3,45.5);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ50();
	this.instance.parent = this;
	this.instance.setTransform(35,121,1,1,0,0,0,40,126);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1,scaleY:1,rotation:-10.8,x:20.6,y:130.7},14,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:-22.7,x:5.1,y:141},15,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-11.3,x:20,y:131.1},15,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,rotation:0,x:35,y:121},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-145,-132,280,254);


(lib.Символ41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(0,-24.1,0.665,0.665);
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ41, new cjs.Rectangle(-68.5,-150,137,251.8), null);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ31();
	this.instance.parent = this;
	this.instance.filters = [new cjs.BlurFilter(4, 4, 1)];
	this.instance.cache(-15,-6,30,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ32, new cjs.Rectangle(-15.3,-6.1,34,16), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ23();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:4},0).wait(1).to({rotation:8.1},0).wait(1).to({rotation:12.1},0).wait(1).to({rotation:16.2},0).wait(1).to({rotation:20.2},0).wait(1).to({rotation:24.3},0).wait(1).to({rotation:28.3},0).wait(1).to({rotation:32.4},0).wait(1).to({rotation:36.4},0).wait(1).to({rotation:40.4},0).wait(1).to({rotation:44.5},0).wait(1).to({rotation:48.5},0).wait(1).to({rotation:52.6},0).wait(1).to({rotation:56.6},0).wait(1).to({rotation:60.7},0).wait(1).to({rotation:64.7},0).wait(1).to({rotation:68.8},0).wait(1).to({rotation:72.8},0).wait(1).to({rotation:76.9},0).wait(1).to({rotation:80.9},0).wait(1).to({rotation:84.9},0).wait(1).to({rotation:89},0).wait(1).to({rotation:93},0).wait(1).to({rotation:97.1},0).wait(1).to({rotation:101.1},0).wait(1).to({rotation:105.2},0).wait(1).to({rotation:109.2},0).wait(1).to({rotation:113.3},0).wait(1).to({rotation:117.3},0).wait(1).to({rotation:121.3},0).wait(1).to({rotation:125.4},0).wait(1).to({rotation:129.4},0).wait(1).to({rotation:133.5},0).wait(1).to({rotation:137.5},0).wait(1).to({rotation:141.6},0).wait(1).to({rotation:145.6},0).wait(1).to({rotation:149.7},0).wait(1).to({rotation:153.7},0).wait(1).to({rotation:157.8},0).wait(1).to({rotation:161.8},0).wait(1).to({rotation:165.8},0).wait(1).to({rotation:169.9},0).wait(1).to({rotation:173.9},0).wait(1).to({rotation:178},0).wait(1).to({rotation:182},0).wait(1).to({rotation:186.1},0).wait(1).to({rotation:190.1},0).wait(1).to({rotation:194.2},0).wait(1).to({rotation:198.2},0).wait(1).to({rotation:202.2},0).wait(1).to({rotation:206.3},0).wait(1).to({rotation:210.3},0).wait(1).to({rotation:214.4},0).wait(1).to({rotation:218.4},0).wait(1).to({rotation:222.5},0).wait(1).to({rotation:226.5},0).wait(1).to({rotation:230.6},0).wait(1).to({rotation:234.6},0).wait(1).to({rotation:238.7},0).wait(1).to({rotation:242.7},0).wait(1).to({rotation:246.7},0).wait(1).to({rotation:250.8},0).wait(1).to({rotation:254.8},0).wait(1).to({rotation:258.9},0).wait(1).to({rotation:262.9},0).wait(1).to({rotation:267},0).wait(1).to({rotation:271},0).wait(1).to({rotation:275.1},0).wait(1).to({rotation:279.1},0).wait(1).to({rotation:283.1},0).wait(1).to({rotation:287.2},0).wait(1).to({rotation:291.2},0).wait(1).to({rotation:295.3},0).wait(1).to({rotation:299.3},0).wait(1).to({rotation:303.4},0).wait(1).to({rotation:307.4},0).wait(1).to({rotation:311.5},0).wait(1).to({rotation:315.5},0).wait(1).to({rotation:319.6},0).wait(1).to({rotation:323.6},0).wait(1).to({rotation:327.6},0).wait(1).to({rotation:331.7},0).wait(1).to({rotation:335.7},0).wait(1).to({rotation:339.8},0).wait(1).to({rotation:343.8},0).wait(1).to({rotation:347.9},0).wait(1).to({rotation:351.9},0).wait(1).to({rotation:356},0).wait(1).to({rotation:360},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.1,-20.1,38.3,40.2);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.parent = this;
	this.instance.setTransform(-13.8,17.1,0.269,0.269);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(21).to({alpha:0.602},0).to({regY:0.4,scaleX:1.49,scaleY:1.49,rotation:65.2,x:-13.9,y:17.5,alpha:1},23).to({scaleX:21.58,scaleY:21.58,x:-13.7,y:-99.5},4).to({regX:0.5,regY:0.7,scaleX:36.69,scaleY:36.69,x:-14.4,y:-186.8,alpha:0},3).wait(29));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19,11.7,10.3,10.8);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.parent = this;
	this.instance.setTransform(-25.5,19.2,1,1,0,0,0,-24.8,19.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.03,scaleY:1.03,rotation:-1,x:-26.1,y:20.4},9,cjs.Ease.get(-1)).to({scaleX:1.05,scaleY:1.05,rotation:-2.2,x:-26.5,y:21.5},10,cjs.Ease.get(1)).to({regX:-24.9,scaleX:1.03,scaleY:1.03,rotation:-1,x:-26.1,y:20.4},10,cjs.Ease.get(-1)).to({regX:-24.8,scaleX:1,scaleY:1,rotation:0,x:-25.5,y:19.2},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.2,-32.5,71,65);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ15();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(-51.5,-163.5,103,327), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(-51,-90,102,180), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.setTransform(-14.4,0,1.276,1.006,0,180,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(1).to({_off:false,regX:0.1,regY:-0.1,scaleX:0.9,scaleY:1.19,skewX:220.2,skewY:7.7,x:10.6,y:6.7},0).to({_off:true},1).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false,scaleY:1.17,skewX:-39,skewY:-8,x:5},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.2,-8.4,133.6,16.9);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ5();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0.007},0).wait(1).to({alpha:0.015},0).wait(1).to({alpha:0.026},0).wait(1).to({alpha:0.04},0).wait(1).to({alpha:0.058},0).wait(1).to({alpha:0.08},0).wait(1).to({alpha:0.108},0).wait(1).to({alpha:0.142},0).wait(1).to({alpha:0.182},0).wait(1).to({alpha:0.225},0).wait(1).to({alpha:0.263},0).wait(1).to({alpha:0.294},0).wait(1).to({alpha:0.317},0).wait(1).to({alpha:0.335},0).wait(1).to({alpha:0.348},0).wait(1).to({alpha:0.357},0).wait(1).to({alpha:0.364},0).wait(1).to({alpha:0.369},0).wait(1).to({alpha:0.371},0).wait(1).to({alpha:0.365},0).wait(1).to({alpha:0.357},0).wait(1).to({alpha:0.347},0).wait(1).to({alpha:0.334},0).wait(1).to({alpha:0.318},0).wait(1).to({alpha:0.299},0).wait(1).to({alpha:0.274},0).wait(1).to({alpha:0.244},0).wait(1).to({alpha:0.207},0).wait(1).to({alpha:0.167},0).wait(1).to({alpha:0.129},0).wait(1).to({alpha:0.095},0).wait(1).to({alpha:0.068},0).wait(1).to({alpha:0.048},0).wait(1).to({alpha:0.032},0).wait(1).to({alpha:0.021},0).wait(1).to({alpha:0.012},0).wait(1).to({alpha:0.006},0).wait(1).to({alpha:0.002},0).wait(1).to({alpha:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-322.6,-172,645.2,344.1);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ3();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.14,scaleY:1.14},4,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},5,cjs.Ease.get(1)).to({scaleX:1.14,scaleY:1.14},4,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},6,cjs.Ease.get(1)).wait(41));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.2,-29,80.6,58);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ24();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:29.2},36,cjs.Ease.get(-1)).to({x:60},38,cjs.Ease.get(1)).to({x:29.6},38,cjs.Ease.get(-1)).to({x:0},37,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-300,-150,600,300);


(lib.Символ112 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ111();
	this.instance.parent = this;
	this.instance.setTransform(0,11.1,0.689,0.689);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:-0.1,scaleY:0.55,y:-2.9},6,cjs.Ease.get(1)).to({regY:0,scaleY:0.69,y:11.1},5,cjs.Ease.get(1)).wait(1).to({regY:-0.1,scaleY:0.55,y:-2.9},6,cjs.Ease.get(1)).to({regY:0,scaleY:0.69,y:11.1},5,cjs.Ease.get(1)).wait(32));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-22,-10.9,44.1,44.1);


(lib.Символ96 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ95();
	this.instance.parent = this;
	this.instance.setTransform(-278.7,-83);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-882.9},69,cjs.Ease.get(1)).to({x:-278.7},70,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-311.7,-114,66,61);


(lib.Символ65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ66();
	this.instance.parent = this;
	this.instance.setTransform(102.1,0,0.611,0.611);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ112();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-8,0.722,0.722);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ65, new cjs.Rectangle(-15.9,-15.9,199.7,31.9), null);


(lib.Символ55 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ52();
	this.instance.parent = this;
	this.instance.setTransform(-22.8,-14.2,1,1,0,0,0,-22.8,-14.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:0,regY:0,rotation:4.6,x:-1.2,y:1.8},0).wait(1).to({rotation:9.1,x:-2.5,y:3.4},0).wait(1).to({rotation:13.7,x:-4,y:5},0).wait(1).to({rotation:18.2,x:-5.6,y:6.4},0).wait(1).to({rotation:22.8,x:-7.3,y:7.7},0).wait(1).to({rotation:27.3,x:-9.1,y:8.9},0).wait(1).to({rotation:31.9,x:-11,y:9.9},0).wait(1).to({rotation:36.5,x:-12.9,y:10.7},0).wait(1).to({rotation:41,x:-14.9,y:11.4},0).wait(1).to({rotation:45.6,x:-17,y:12},0).wait(1).to({rotation:50.1,x:-19.1,y:12.3},0).wait(1).to({rotation:54.7,x:-21.2,y:12.6},0).wait(1).to({rotation:59.2,x:-23.4},0).wait(1).to({rotation:63.8,x:-25.5,y:12.5},0).wait(1).to({rotation:68.4,x:-27.6,y:12.2},0).wait(1).to({rotation:72.9,x:-29.7,y:11.7},0).wait(1).to({rotation:77.5,x:-31.7,y:11},0).wait(1).to({rotation:82,x:-33.7,y:10.3},0).wait(1).to({rotation:86.6,x:-35.6,y:9.3},0).wait(1).to({rotation:91.1,x:-37.4,y:8.2},0).wait(1).to({rotation:95.7,x:-39.2,y:7},0).wait(1).to({rotation:100.3,x:-40.8,y:5.6},0).wait(1).to({rotation:104.8,x:-42.3,y:4.1},0).wait(1).to({rotation:109.4,x:-43.7,y:2.5},0).wait(1).to({rotation:113.9,x:-45,y:0.8},0).wait(1).to({rotation:118.5,x:-46.1,y:-1},0).wait(1).to({rotation:123,x:-47.1,y:-2.9},0).wait(1).to({rotation:127.6,x:-47.9,y:-4.9},0).wait(1).to({rotation:132.2,x:-48.6,y:-6.9},0).wait(1).to({rotation:136.7,x:-49.1,y:-9},0).wait(1).to({rotation:141.3,x:-49.4,y:-11.1},0).wait(1).to({rotation:145.8,x:-49.6,y:-13.3},0).wait(1).to({rotation:150.4,y:-15.4},0).wait(1).to({rotation:154.9,x:-49.4,y:-17.5},0).wait(1).to({rotation:159.5,x:-49.1,y:-19.6},0).wait(1).to({rotation:164.1,x:-48.5,y:-21.7},0).wait(1).to({rotation:168.6,x:-47.9,y:-23.7},0).wait(1).to({rotation:173.2,x:-47,y:-25.7},0).wait(1).to({rotation:177.7,x:-46,y:-27.6},0).wait(1).to({rotation:182.3,x:-44.9,y:-29.4},0).wait(1).to({rotation:186.8,x:-43.6,y:-31.1},0).wait(1).to({rotation:191.4,x:-42.2,y:-32.7},0).wait(1).to({rotation:195.9,x:-40.7,y:-34.2},0).wait(1).to({rotation:200.5,x:-39.1,y:-35.6},0).wait(1).to({rotation:205.1,x:-37.3,y:-36.8},0).wait(1).to({rotation:209.6,x:-35.5,y:-37.9},0).wait(1).to({rotation:214.2,x:-33.6,y:-38.8},0).wait(1).to({rotation:218.7,x:-31.6,y:-39.6},0).wait(1).to({rotation:223.3,x:-29.5,y:-40.2},0).wait(1).to({rotation:227.8,x:-27.5,y:-40.7},0).wait(1).to({rotation:232.4,x:-25.3,y:-41},0).wait(1).to({rotation:237,x:-23.2,y:-41.1},0).wait(1).to({rotation:241.5,x:-21.1,y:-41},0).wait(1).to({rotation:246.1,x:-19,y:-40.8},0).wait(1).to({rotation:250.6,x:-16.9,y:-40.4},0).wait(1).to({rotation:255.2,x:-14.8,y:-39.9},0).wait(1).to({rotation:259.7,x:-12.8,y:-39.2},0).wait(1).to({rotation:264.3,x:-10.8,y:-38.3},0).wait(1).to({rotation:268.9,x:-9,y:-37.3},0).wait(1).to({rotation:273.4,x:-7.2,y:-36.1},0).wait(1).to({rotation:278,x:-5.5,y:-34.8},0).wait(1).to({rotation:282.5,x:-3.9,y:-33.4},0).wait(1).to({rotation:287.1,x:-2.4,y:-31.8},0).wait(1).to({rotation:291.6,x:-1.1,y:-30.1},0).wait(1).to({rotation:296.2,x:0.1,y:-28.4},0).wait(1).to({rotation:300.8,x:1.1,y:-26.5},0).wait(1).to({rotation:305.3,x:2,y:-24.6},0).wait(1).to({rotation:309.9,x:2.8,y:-22.6},0).wait(1).to({rotation:314.4,x:3.4,y:-20.5},0).wait(1).to({rotation:319,x:3.8,y:-18.4},0).wait(1).to({rotation:323.5,x:4,y:-16.3},0).wait(1).to({rotation:328.1,x:4.1,y:-14.2},0).wait(1).to({rotation:332.7,x:4,y:-12},0).wait(1).to({rotation:337.2,x:3.7,y:-9.9},0).wait(1).to({rotation:341.8,x:3.3,y:-7.8},0).wait(1).to({rotation:346.3,x:2.7,y:-5.8},0).wait(1).to({rotation:350.9,x:2,y:-3.8},0).wait(1).to({rotation:355.4,x:1.1,y:-1.9},0).wait(1).to({rotation:360,x:0,y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.6,-22.7,49.3,45.5);


(lib.Символ51 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ55();
	this.instance.parent = this;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ43 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ41();
	this.instance.parent = this;
	this.instance.setTransform(-7.5,44.3,1.577,1.155,0,0,180);
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.69,scaleY:1.24},29,cjs.Ease.get(-1)).to({scaleX:1.82,scaleY:1.33},30,cjs.Ease.get(1)).to({scaleX:1.7,scaleY:1.24,x:-7.6},30,cjs.Ease.get(-1)).to({scaleX:1.58,scaleY:1.16,x:-7.5},30,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.6,-129,216.1,290.9);


(lib.Символ42 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance = new lib.Символ41();
	this.instance.parent = this;
	this.instance.setTransform(-15.8,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ42, new cjs.Rectangle(-84.3,-117.6,137,251.8), null);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.parent = this;
	this.instance.alpha = 0.32;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14,cjs.Ease.get(1)).to({alpha:0.32},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15.3,-6.1,34,16);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(4,-55.8,1,1,0,0,0,4,-55.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:15},9,cjs.Ease.get(1)).to({rotation:0},10,cjs.Ease.get(1)).wait(1).to({rotation:15},9,cjs.Ease.get(1)).to({rotation:0},10,cjs.Ease.get(1)).to({rotation:34.5,x:4.1},5).wait(1).to({regY:-55.9,rotation:31.8,x:4.2,y:-55.9},0).wait(1).to({regY:-55.8,rotation:34.5,x:4.1,y:-55.8},0).wait(1).to({regY:-55.9,rotation:31.8,x:4.2,y:-55.9},0).wait(1).to({regY:-55.8,rotation:34.5,x:4.1,y:-55.8},0).wait(1).to({regY:-55.9,rotation:31.8,x:4.2,y:-55.9},0).wait(1).to({regY:-55.8,rotation:34.5,x:4.1,y:-55.8},0).wait(1).to({regY:-55.9,rotation:31.8,x:4.2,y:-55.9},0).to({regY:-55.8,rotation:0,x:4,y:-55.8},28).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ9();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-23,34.4,0.586,1,0,0,0,-0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:-0.2,regY:0.1,scaleX:0.26,rotation:15,x:-28.5,y:27.8},9,cjs.Ease.get(1)).to({regX:-0.1,scaleX:0.37,x:-24.2,y:23.5},10,cjs.Ease.get(1)).wait(1).to({regX:-0.2,scaleX:0.26,x:-28.5,y:27.8},9).to({regX:-0.1,scaleX:0.37,x:-24.2,y:23.5},10,cjs.Ease.get(1)).to({regX:0.1,regY:0.2,scaleX:0.08,x:-47.3,y:17.3},5).wait(7).to({regX:-0.1,regY:0,scaleX:0.59,rotation:0,x:-23,y:34.4},28).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70.5,-55.8,84.9,111.6);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(-11.6,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(-35,-39,70,78), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.dama_181();
	this.instance.parent = this;
	this.instance.setTransform(-34,-103.8,1,1,-23.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ26();
	this.instance_1.parent = this;
	this.instance_1.setTransform(28.2,-21.9,1,0.878,38,0,0,3,-56.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(-83.1,-121.5,131.3,183.9), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(-3.4,-0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-30,0,1.15,1.15);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(-375,-172.9,694.2,345.5), null);


(lib.Символ97 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ96();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:252.6},37,cjs.Ease.get(1)).to({y:0},25,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-311.7,-114,66,61);


(lib.Символ91 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 93
	this.instance = new lib.Символ97();
	this.instance.parent = this;
	this.instance.setTransform(-80,-40,0.746,0.746);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ91, new cjs.Rectangle(-312.4,-125,49.2,45.5), null);


(lib.Символ44 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия: 2
	this.instance = new lib.Символ42();
	this.instance.parent = this;
	this.instance.setTransform(17.8,-28);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:1.18,scaleY:1.18,y:-59.4,alpha:0.809},56).to({scaleX:0.79,scaleY:1.21,y:-66.6,alpha:0},31).wait(1));

	// Слой 1 - копия
	this.instance_1 = new lib.Символ42();
	this.instance_1.parent = this;
	this.instance_1.setTransform(17.8,-66.6,0.788,1.206);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.18,scaleY:1.18,y:-59.4,alpha:0.809},32).to({scaleX:1,scaleY:1,y:58.4,alpha:0},55).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.6,-208.5,137,314.6);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ19();
	this.instance.parent = this;
	this.instance.setTransform(31.4,36.4,1,1,0,0,0,31.4,36.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:1.8,x:31.5,y:36.5},14,cjs.Ease.get(-1)).to({rotation:3.7,y:36.4},15,cjs.Ease.get(1)).to({regY:36.3,rotation:1.8,x:31.4,y:36.5},15,cjs.Ease.get(-1)).to({regY:36.4,rotation:0,y:36.4},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35,-39,70,78);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(-4.1,-98.1,1,1,0,0,0,-4.1,-98.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:-98.2,rotation:2.5,x:-4,y:-98.2},14,cjs.Ease.get(-1)).to({regY:-98.1,rotation:5.2,y:-98.1},15,cjs.Ease.get(1)).to({rotation:2.5},15,cjs.Ease.get(-1)).to({rotation:0,x:-4.1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.1,-121.5,131.3,183.9);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(49.7,8.7,2.602,2.602,0,0,0,-13.8,17);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 18
	this.instance_1 = new lib.Символ18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(37.9,-60.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 14
	this.instance_2 = new lib.Символ14();
	this.instance_2.parent = this;
	this.instance_2.setTransform(98.1,-101,1,1,0,0,0,-8.5,-101.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Символ 14
	this.instance_3 = new lib.Символ14();
	this.instance_3.parent = this;
	this.instance_3.setTransform(9.7,-104.2,1,1,0,5.8,-174.2,-8.4,-101.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Символ 20
	this.instance_4 = new lib.Символ20();
	this.instance_4.parent = this;
	this.instance_4.setTransform(63.1,-140);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// Символ 12
	this.instance_5 = new lib.Символ12();
	this.instance_5.parent = this;
	this.instance_5.setTransform(53.4,-35.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ27, new cjs.Rectangle(-55.8,-179,210.5,241.9), null);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();
	this.instance.parent = this;
	this.instance.setTransform(69.1,4.1,1,1,0,0,0,69.1,4.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:69,rotation:-1.5,x:69,y:4.2},14,cjs.Ease.get(-1)).to({regX:69.1,rotation:-3.5,x:69.1,y:4.1},15,cjs.Ease.get(1)).to({regX:69,regY:4.2,rotation:-1.6,y:4.2},15,cjs.Ease.get(-1)).to({regX:69.1,regY:4.1,rotation:0,y:4.1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.8,-179,210.5,241.9);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 8
	this.instance = new lib.Символ44();
	this.instance.parent = this;
	this.instance.setTransform(0.1,348.9,1.938,1.533,0,0,0,0,0.1);
	this.instance.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// dama_09.png
	this.instance_1 = new lib.Символ28();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-28.1,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// dama_12.png
	this.instance_2 = new lib.Символ16();
	this.instance_2.parent = this;
	this.instance_2.setTransform(17.5,226.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Слой 9
	this.instance_3 = new lib.Символ43();
	this.instance_3.parent = this;
	this.instance_3.setTransform(13.7,218.5,1.237,1.237);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(-129.2,-113.5,267.2,624.8), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.dama1 = new lib.Символ7();
	this.dama1.parent = this;
	this.dama1.setTransform(113.9,-45.9,0.726,0.726);

	this.timeline.addTween(cjs.Tween.get(this.dama1).to({regX:0.1,regY:-0.1,rotation:-1.3,y:-41.8},21,cjs.Ease.get(-1)).to({rotation:-2.7,y:-37},23,cjs.Ease.get(1)).to({regX:0.2,rotation:-1.3,y:-41.4},22,cjs.Ease.get(-1)).to({regX:0,regY:0,rotation:0,y:-45.9},23,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(20,-128.4,194.1,453.9);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_198 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_214 = function() {
		this.stop();
	}
	this.frame_230 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(198).call(this.frame_198).wait(16).call(this.frame_214).wait(16).call(this.frame_230).wait(1));

	// Слой 1
	this.dama = new lib.Символ8();
	this.dama.parent = this;
	this.dama.setTransform(-93.4,-54.4);

	this.timeline.addTween(cjs.Tween.get(this.dama).to({x:-119.6},22,cjs.Ease.get(-1)).to({rotation:-9.7,x:-218.3,y:-11.2},26).to({rotation:-2.5,x:-313.2,y:-42.6},24,cjs.Ease.get(1)).to({rotation:0,x:-348.4,y:-54.4},26).to({x:-316.5},25,cjs.Ease.get(-1)).to({rotation:9,x:-220.9},25).to({rotation:0,x:-93.4},50,cjs.Ease.get(1)).wait(1).to({x:-307.2},15,cjs.Ease.get(1)).wait(1).to({x:-93.4},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.4,-182.7,194.1,453.9);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_8 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(8));

	// Слой 2
	this.instance = new lib.Символ65();
	this.instance.parent = this;
	this.instance.setTransform(-270.4,39.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-481.5,alpha:0},7,cjs.Ease.get(1)).wait(1).to({x:-270.4,alpha:1},7).wait(1));

	// Слой 11
	this.instance_1 = new lib.Символ56();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-16.9,-204.8,1.256,1.256);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1,x:4.1,y:-206.8,alpha:0},7).wait(1).to({scaleX:1.26,scaleY:1.26,x:-16.9,y:-204.8,alpha:1},7).wait(1));

	// Слой 7
	this.instance_2 = new lib.Символ4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-234.1,-190.2,1.298,1.298);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(16));

	// Слой 6
	this.instance_3 = new lib.Символ91();
	this.instance_3.parent = this;
	this.instance_3.setTransform(551.8,-87.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:631.8,alpha:0},7).wait(1).to({x:551.8,alpha:1},7).wait(1));

	// Слой 10
	this.instance_4 = new lib.Символ49();
	this.instance_4.parent = this;
	this.instance_4.setTransform(545.1,178);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({x:207,y:-53,alpha:1},7,cjs.Ease.get(1)).wait(1).to({x:545.1,y:178,alpha:0},7,cjs.Ease.get(1)).wait(1));

	// Символ 29
	this.dama_main = new lib.Символ29();
	this.dama_main.parent = this;
	this.dama_main.setTransform(96.9,4.4,0.834,0.834);

	this.timeline.addTween(cjs.Tween.get(this.dama_main).to({scaleX:1.45,scaleY:1.45,x:112.7,y:44.5},5).to({scaleX:1.35,scaleY:1.35,x:104.6,y:25},2).wait(1).to({scaleX:1.45,scaleY:1.45,x:112.7,y:44.5},2).to({scaleX:0.83,scaleY:0.83,x:96.9,y:4.4},5).wait(1));

	// Слой 6
	this.instance_5 = new lib.Символ46();
	this.instance_5.parent = this;
	this.instance_5.setTransform(3.6,-84.9);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:0.602},7).wait(1).to({alpha:0},7).wait(1));

	// Слой 8
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],-3.5,-214,-3.5,90.1).s().p("EgxrAY7MAAAgx1MBjXAAAMAAAAx1g");
	this.shape.setTransform(4.6,-85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(16));

	// Символ 2
	this.instance_6 = new lib.Символ2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(3.5,-82.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:1.45,scaleY:1.45,x:5,y:-75.1},5).to({scaleX:1.35,scaleY:1.35,x:4.7,y:-65.3},2).wait(1).to({scaleX:1.45,scaleY:1.45,x:5,y:-75.1},2).to({scaleX:1.36,scaleY:1.36,x:4.7,y:-76.6},1).to({scaleX:1,scaleY:1,x:3.5,y:-82.5},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-371.5,-255.5,1051.6,555.5);


// stage content:
(lib.throne600300 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
			_this.priz.gotoAndStop(1);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(9);
			_this.main.dama_main.gotoAndPlay(0);
			_this.priz.gotoAndStop(0);
		}
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.btn_vpravo.addEventListener("mouseover", fl_MouseOverHandler_22);
		
		function fl_MouseOverHandler_22()
		{
			_this.main.dama_main.gotoAndPlay(216);
		}
		
		
		var frequency = 30;
		stage.enableMouseOver(frequency);
		this.btn_vlevo.addEventListener("mouseover", fl_MouseOverHandler_29);
		
		function fl_MouseOverHandler_29()
		{
			_this.main.dama_main.gotoAndPlay(200);
		}
		
		
		stage.canvas.style.cursor = "none";
		this.priz.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.priz.x = stage.mouseX/window.devicePixelRatio;
			this.priz.y = stage.mouseY/window.devicePixelRatio;
		}
		
		this.btn_vlevo.cursor = "none";
		this.btn_vpravo.cursor = "none";
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 5
	this.priz = new lib.Символ51();
	this.priz.parent = this;
	this.priz.setTransform(560.6,44.8);

	this.timeline.addTween(cjs.Tween.get(this.priz).wait(1));

	// Слой 4
	this.btn_vlevo = new lib.Символ48();
	this.btn_vlevo.parent = this;
	this.btn_vlevo.setTransform(471.6,154.1);
	new cjs.ButtonHelper(this.btn_vlevo, 0, 1, 2, false, new lib.Символ48(), 3);

	this.btn_vpravo = new lib.Символ47();
	this.btn_vpravo.parent = this;
	this.btn_vpravo.setTransform(125.3,154.8);
	new cjs.ButtonHelper(this.btn_vpravo, 0, 1, 2, false, new lib.Символ47(), 3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.btn_vpravo},{t:this.btn_vlevo}]}).wait(1));

	// Слой 3
	this.main = new lib.Символ45();
	this.main.parent = this;
	this.main.setTransform(296.6,233.6);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(225,128.1,1051.6,555.5);
// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/ball.png?1496755516935", id:"ball"},
		{src:"images/bg.jpg?1496755516935", id:"bg"},
		{src:"images/dama_03.png?1496755516935", id:"dama_03"},
		{src:"images/dama_062.png?1496755516935", id:"dama_062"},
		{src:"images/dama_09.png?1496755516935", id:"dama_09"},
		{src:"images/dama_121.png?1496755516936", id:"dama_121"},
		{src:"images/dama_181.png?1496755516936", id:"dama_181"},
		{src:"images/dama_21.png?1496755516936", id:"dama_21"},
		{src:"images/dym.png?1496755516936", id:"dym"},
		{src:"images/lightn.png?1496755516936", id:"lightn"},
		{src:"images/log.png?1496755516936", id:"log"},
		{src:"images/mech.png?1496755516936", id:"mech"},
		{src:"images/mous.png?1496755516936", id:"mous"},
		{src:"images/qwe.png?1496755516936", id:"qwe"},
		{src:"images/wer.png?1496755516936", id:"wer"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;