(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.cheese_clock = function() {
	this.initialize(img.cheese_clock);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,324,312);


(lib.cheese_clock1 = function() {
	this.initialize(img.cheese_clock1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,179,171);


(lib.cheese_clock2 = function() {
	this.initialize(img.cheese_clock2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,324,312);


(lib.girl2 = function() {
	this.initialize(img.girl2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,240,400);


(lib.girlq1 = function() {
	this.initialize(img.girlq1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,240,400);


(lib.hohlogo = function() {
	this.initialize(img.hohlogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,240,200);


(lib.say1 = function() {
	this.initialize(img.say1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,284,216);


(lib.say2 = function() {
	this.initialize(img.say2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,295,183);


(lib.sssi_03 = function() {
	this.initialize(img.sssi_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,149,130);


(lib.sssi_06 = function() {
	this.initialize(img.sssi_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,145,134);


(lib.sssi_11 = function() {
	this.initialize(img.sssi_11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,138,130);


(lib.treugolnik_grib = function() {
	this.initialize(img.treugolnik_grib);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,92);


(lib.treugolnik_slivki = function() {
	this.initialize(img.treugolnik_slivki);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,93,120);


(lib.treugolnik_zelen = function() {
	this.initialize(img.treugolnik_zelen);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,116);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlLBzQgEgDgCgFIgBgEQAAgDACgCIADgFIAFgdIghheIgEgIQgCgEAAgDIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAPIAPAvIAXg6IACgKQABgGAEgCQACgBADAAQAHAAAHAFQAGAFABAGQABAFgDAFIgFAKIgmBgQgDALgBAKIAAAIQAAAFgCACQgDAFgIAAQgGAAgFgCgAo1BRQgEgDgEgEQgNgHAAgDQAAgEAFgHIgFiPQgEgHAAgEQAAgFAEgDQAFgDAIAAQAIAAAFABIAHACIAKgEQAKgDANAAQAOAAAJAEQAIAEAEAJQACAHAAAGQAAAcgeAYIAMgBQATAAACAbQAAAKgHAPQgHAOgPARQgdAjgQABQgGgBgFgCgAoZgHQgIAEgIAIIADArIAWgTQAPgOACgQQAAgLgLAAQgIAAgHAFgAodhVQgHACgIAGIADAzQAmgiAAgQQAAgLgMAAQgHAAgHACgAC6BQQgFgCgDgFQgCgDgBgIIAAgvQAAgPgCgBQgCAAgGANIgQAsIAAALQgBAHgEACQgDABgEAAQgGAAgHgEQgGgEgBgGQgDgJABgSIAAgjQAAgJgBAAIgKAQQgEAJgDAMQgDALAAAOQgCACABAJQABAHgDACQgDADgFAAQgFAAgGgEQgGgDgCgEQgEgFAAgqIAAg1IgEgNIACgEQACgEANAAQAPAAADAHIAAADIgCAGQgCAEAAADIAAAaIAVgrIAEgFQACgDAGAAQAJAAAKAFQAJAEAAAGQAAAFgCADIgCAGIAAAwQAEgIAJgeIAHgSQADgGACgCQAFgEAKAAQAJAAAFADQAEADABAFIAABdQAAACAEAEQAFADAAAEIgBAFQgBAEgEACQgDACgFAAQgHAAgFgCgAIxBIQgCgCAAgFIABgRIgBgFIAAgFQACgEAJAAQAIAAAFACQAFACACAFIABAGIgCAOIABAHQAAAEgCACQgCAEgHAAQgMAAgGgIgADlBLQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA5QARgqARgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgDQAAgEADgFIAAg2QgRAigPAkQgBAGgEACQgEADgFAAQgIAAgGgEgAgiBNIgHgDQgDgCgCgDQgCgDAAgDQAAgEADgDQACgDAGgDIAUgZQgEAAgFgDIgIgGQgEgDgCgFQgDgFAAgEQAAgPAIgLQAHgLAKgHQAKgGAKgEQALgDAHAAQAFAAAEACIAGADIAFAFIACAGIgEAKIAABaQADAGAAAEQAAAFgEACQgDACgGAAIgIgBIgHgDIgFgEQgBAAAAgBQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgDADgFIAAgeIgXAnQgBAIgDACQgCACgFAAgAABgXIgGAGIgGAHQgCADAAAEQAAADADADQADADAEAAIADgEQADgCAFAAIAAgbgAjgBLQgIgEgFgIQgKgQgDgaIAAgMQAAgKACgKQACgKADgKQAKgYATgBQAIgBAJAEQAIADAFAHQAFAIADAIQADAHAAAJIAAAIQAAADgFADQgFACgGAAQgGAAgDgCQgDgDgBgJIgCgPQgBgHgIAAQgDAAgCANQgCAMAAAPQAAATADAMQADAOAFAAQAGAAAFgJQAFgIAAgGQAAgLANAAQAGAAAFADQAEADABAFIgFAMQgIASgKAJQgJAIgLAAQgKAAgHgDgAIBBGIgBgHIgCgGQgGAJgHAFQgHAFgMAAQgHAAgGgEQgGgEgFgHIgGgMQgCgGAAgGQABgJAGgIQAGgJAMgHIAigUIABgFQAAgFgDgCQgDgCgGAAQgEAAgOAMQgGAJgGACQgHAAgFgJQgGgJAAgFQAAgDAEgDQAEgEAIgCQAUgNAUgBQARAAAIAKQAJALAAAVIAAAtQAAAGACAJQAGADADAEIABAEQAAAEgCAEIgGAGQgJAGgIAAQgIgBgCgGgAHpAUQgLAGgBAHQgBAHADAEQADAFAEAAQAJgBAHgOIAFgWQgIABgKAHgAFZBJIgGgEIgCgEQAAgDADgFIAAgjQgCgGAAgFIABgGIABgFIAAglQgCgFAAgDQAAgLAPAAIAIABIAGAEIAFAEQACACAAADQAAADgFAHIAAAcIAfgEIAAgeIgCgJQAAgFADgCQADgCAGAAQALAAAGAEQAGAEAAAGIgEAKIAAAYQACAFAAAEIAAAFIgCAGIAAAqIADAJQAAAJgNAAIgIgBIgHgDIgFgEIgCgDQAAgEADgFIAAgiIgfADIAAAlQADAGAAAEQAAAJgNAAgAiUBJIgFgEIgCgEQAAgDADgFIAAgjQgCgGAAgFIAAgGIACgFIAAglQgDgFAAgDQAAgLAPAAIAIABIAHAEIAEAEQACACAAADQAAADgEAHIAAAcIAegEIAAgeIgCgJQAAgFADgCQADgCAGAAQALAAAGAEQAHAEAAAGIgEAKIAAAYQACAFAAAEIgBAFIgBAGIAAAqIACAJQAAAJgNAAIgHgBIgHgDIgGgEIgCgDQAAgEADgFIAAgiIgeADIAAAlQADAGAAAEQAAAJgNAAgAnLBIQgIgEAAgDQAAgDADgGIAAhdQgCgFAAgDQAAgLAPAAQAIAAAGAEQAHAEAAAGQAAACgEAIIAAAjIAEAAIAfgxQAEgLAHAAQAHAAAHAGQAHAFAAAGQAAAEgCACQgDADgFACIgaAqQAJASAMAQIAHADQADADAAAEQAAAFgEAGQgIAIgJAAQgEAAgDgCIgCgFIgCgFQgLgQgKgTIgJAAIAAAdQADAFAAAFQAAAIgOAAQgGAAgIgEgAIvAMQgCgDAAgEIABgIQgCgdAAgeQAAgoADgEQADgDAJAAQAIAAAFACQAFACABAEIAAAEIgDAOIAABMIADARQAAAFgDACQgEADgFAAQgMAAgHgIg");
	this.shape.setTransform(59.1,11.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(0,0,118.2,23.4), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_zelen();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(0,0,104,116), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_slivki();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(0,0,93,120), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.treugolnik_grib();
	this.instance.parent = this;
	this.instance.setTransform(0,88.1,1,1,-47.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(0,0,149,150.6), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cheese_clock();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.728,0.728);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(0,0,236,227.3), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cheese_clock2();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.728,0.728);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(0,0,236,227.3), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cheese_clock1();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.728,0.728);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(0,0,130.4,124.6), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACrBsIADgOIAAiCIgCgGQgBgDAAgDQAAgGAGgDQAFgDAIAAQAGAAAFACQAEADABAEIAAACQAKgJAKAAQAJAAAHAFQAHAFAFAJQAIAQAAAZQABAPgDAMQgCANgGALQgLAXgTAAQgEAAgEgDIgJgIIAAAYQAAADACAGQADAGAAADQABAHgIAFQgHAFgIAAQgQAAgBgQgADPABQABAVACAJQAEAPAFAAQAGAAADgPQADgJABgVQAAghgNAAQgMAAAAAhgAjWBlIgHgDIgFgEQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBAAAAgBQABgDADgFIAAgVQgDgFAAgDQAAgDACgCIADgDIAJgCIABAAQAFgMAFgVIANgxQgDgFAAgDQAAgLAPAAIAFAAIAFACIAIADIAWACQAEAAACADQADACAAAFIgEAKIAHBFIACAAIAIABIAGADIACAEIABADIgEALIgCAVQADAGAAAEQAAAFgEACQgDACgGAAIgFgBIgPgHQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgDAEgFIABgPIg3AGIAAAMQADAGAAAEQAAAFgEACQgDACgGAAgAingTIgQA/IAcgDIgGhHIgEgBgAO7BMQgFgEgDgFQgCgDAAgEIAAgJIgBgKIABgEQABgDAIAAQAHAAAEACQAFACADAEQABADAAAFIAAAHIACANIgBAFQgDAFgFAAQgGAAgGgEgAAWBLIgGgDQgEgCgCgDQgBgDAAgEQgBgEADgDQADgDAFgCIAUgZQgEgBgFgCIgIgGQgEgEgCgFQgDgEAAgEQAAgQAIgLQAHgLAKgGQAKgHALgDQALgDAIAAQAEAAAEABIAGAEIAGAFIABAFIgEALIAABaQADAFAAAFQAAAEgEACQgDACgGAAIgHgBIgHgDIgGgDQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgEACgFIAAgeIgXAoQgCAHgDACQgBADgGAAgAA6gaIgHAGIgGAHQgCAEAAAEQAAADADACQADADAEAAIAEgDQAEgCAEAAIAAgbgAtZBKQgJgBgHgGQgIgFgGgLQgLgUAAgbQAAgTAJgWQAIgWAKAAIAJACIAPgCIAFABQAPAGAHAPQAJARAAAYQAAAegMAWQgFAKgGAFQgFAFgHAAgAtigTQgDALAAAMQAAAMAEAPQAEAUAGAAQAEAAADgFQACgFACgKQADgRAAgKQgCgpgMAAQgIAAgDASgAH/BFQgIgGgFgMQgJgUAAgWQAAgNADgMQACgLAEgJQAGgLAIgFQAIgGALAAQAIAAAHAEQAGAEAGAHQADAGAEAHIAEAQQAIAIgBAGQgCAJgPAAIgIgBIgfADQAAAoAMAAQAAAAABAAQAAgBABAAQAAgBABAAQAAgBAAgBQACgDAAgGIAAgCIgCgEQAAgGAHgDQAHgEAHAAQAIAAAEADQADADgBAHIgCAKQgFAQgHAHQgKAKgTAAQgKAAgGgGgAIMgbQgDAFgBALIAVgCQgFgTgFAAQgEAAgDAFgAGYBGQgJgFgHgLQgEgHgHgTQgDgLgBgZIABgYQABgLACgLQADgKAEgJQAFgJAIgHIAZgRIAIgEIABgEIACgEIAEgDQACgCADAAQADAAAEACIAHAFIAGAGQACAEAAADIgBAGIgEADIgEAEIglAVQgPAKAAAPQAAABABAAQAAAAAAAAQAAABABAAQAAAAAAAAIADgCIADgDQAGgFAEgBIANgBQAHAAAGADQAIAEAFAHQAFAIAEALQADAMAAAOQgBAUgDAJQgEANgHAJQgGAJgJAFQgJAFgKAAQgKAAgJgFgAGhgcIgEAHIgEAKIgBALQAAALACAJIAFAQQACAGAEAEQADAEADAAQADAAADgEQAEgDACgGQACgGABgHQACgJAAgJQAAgHgCgHIgEgMQgDgFgEgCQgEgDgEAAQgDAAgDACgAEqBFQgIgGgFgMQgJgUABgWQAAgNACgMQACgLAEgJQAGgLAIgFQAIgGALAAQAIAAAHAEQAGAEAFAHQAFAGACAHIAGAQQAHAIgCAGQgBAJgPAAIgHgBIghADQABAoAMAAQAAAAABAAQAAgBABAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgCIgBgEQAAgGAGgDQAGgEAIAAQAIAAADADQAEADAAAHIgEAKQgEAQgHAHQgKAKgTAAQgJAAgHgGgAE3gbQgDAFgBALIAVgCQgEgTgGAAQgFAAgCAFgAnaBFQgIgGgEgMQgJgUAAgWQAAgNACgMQACgLAFgJQAFgLAIgFQAJgGALAAQAIAAAGAEQAGAEAGAHQAEAGADAHIAFAQQAIAIgCAGQgBAJgPAAIgIgBIggADQABAoAMAAQAAAAAAAAQABgBAAAAQABgBAAAAQAAgBABgBQACgDgBgGIAAgCIgBgEQAAgGAHgDQAGgEAHAAQAJAAADADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgKAAgHgGgAnMgbQgEAFgBALIAWgCQgFgTgGAAQgEAAgCAFgAqcBFQgHgGgGgMQgIgUAAgWQAAgNACgMQACgLAEgJQAGgLAJgFQAIgGALAAQAIAAAGAEQAGAEAGAHQAEAGADAHIAFAQQAHAIgBAGQgCAJgPAAIgHgBIggADQAAAoAMAAQABAAAAAAQABgBAAAAQABgBAAAAQABgBAAgBQACgDAAgGIgBgCIgBgEQAAgGAGgDQAHgEAIAAQAHAAAEADQAEADgBAHIgDAKQgEAQgIAHQgKAKgTAAQgJAAgHgGgAqPgbQgCAFgBALIAVgCQgFgTgFAAQgFAAgDAFgAhZBIQgGgCgDgEIACgGQACgDAFgDIAbhYIAAgEQAAgKAFgFQAFgEAKAAQAIAAAHAEQAFAEAAAGQAAAFgDAFIAXBZQACAGAAAEQAAAIgKAAIgIgBIgIgDIgGgDQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgEACgFIgMhAIgSBBIAAAHQAAAGgEADQgFAEgHAAQgFAAgGgDgApGBCQgGgEgDgEQgDgEAAgDQABgOAPgCQAEABADAEIAFAFIAGABQAFAAAIgKQAIgLAAgEQAAgFgCgBQgCgBgEACIgDACQgJAIgEAAQgHAAgGgFQgGgFgBgIQABgFAGgDIAKgDQATgJAGgOQAAgEgBgEQgFAAgFADQgGADgHAHQgFAFgFAAQgIAAgFgGQgFgGAAgJQAAgGAGgBIAKgCIAVgMQAMgHAMADQAIADAGAHQAGAGAAAKQgCARgOAPQAIADAFADQAFAEABAGQAAAWgSAUQgSAVgRAAQgIAAgMgJgAsXBIQgFgCgDgEIABgGQACgDAGgDIAahYIAAgEQAAgKAGgFQAFgEAKAAQAHAAAHAEQAGAEAAAGQAAAFgEAFIAYBZQADAGgBAEQAAAIgLAAIgIgBIgIgDIgGgDQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQAAgEADgFIgNhAIgRBBIAAAHQAAAGgEADQgGAEgGAAQgGAAgGgDgANqBEIAAgIIgCgFQgGAIgHAFQgHAFgMAAQgHAAgGgEQgGgDgFgHIgGgMQgCgGAAgGQABgKAGgIQAGgIALgIIAjgUIAAgFQAAgEgCgDQgDgCgGAAQgEAAgOAMQgHAKgFABQgHAAgGgIQgFgJAAgFQAAgEAEgDQAEgDAHgDQAVgMAUgBQARAAAIAKQAJAKAAAVIAAAtQAAAHACAIQAGADADAEIABAFQgBAEgBADIgHAGQgIAGgJAAQgHgBgDgFgANSARQgKAHgCAHQgBAGADAFQAEAFADAAQAKgBAHgPIAFgWQgJACgKAGgAJWBGIgFgEIgCgDQAAgEADgFIAAgjQgCgFAAgGIAAgFIACgFIAAglQgDgFAAgDQAAgLAPAAIAIABIAHADIAEAEQACADAAACQAAADgFAIIAAAcIAfgEIAAgfIgCgIQAAgFADgCQADgCAGAAQALAAAGAEQAGADAAAGIgDALIAAAYQABAEABAFIgBAFIgBAGIAAApIACAKQAAAIgNAAIgHgBIgHgDIgGgDIgCgEQAAgDADgFIAAgjIgfAEIAAAlQADAFAAAFQAAAIgMAAgAmCBGIgGgEIgCgDQAAgEADgFIAAgjQgCgFAAgGIAAgFIACgFIAAglQgCgFgBgDQABgLAPAAIAIABIAGADIAFAEQABADAAACQAAADgEAIIAAAcIAegEIAAgfIgBgIQAAgFACgCQAEgCAFAAQAMAAAFAEQAHADAAAGIgEALIAAAYQACAEAAAFIgBAFIgBAGIAAApIADAKQAAAIgOAAIgHgBIgHgDIgFgDIgCgEQAAgDACgFIAAgjIgeAEIAAAlQADAFAAAFQAAAIgNAAgAusBGQgHgEAAgEQAAgDADgFIAAhUIgaAEIAABQQADAJAAADQAAAIgNAAQgHAAgIgEQgHgEAAgEQAAgDADgFIAAhdQgCgFAAgDQAAgLAOAAQAKAAAHAFIAmgFQAHAAAHADQAHADABAHQAAAEgFAHIAABaQADAGAAAEQAAAIgNAAQgHAAgIgEgALFBGQgIgEAAgEQAAgDADgFIAAheQgDgFABgDQgBgLAQAAQAIAAAGAFQAGAEABAFQAAADgFAHIAAAjIAFAAIAfgxQAEgKAHAAQAHAAAHAFQAHAGAAAGQAAADgCADQgDADgFABIgaAqQAJATAMAQIAHACQADADAAAFQAAAFgEAFQgIAIgJAAQgEAAgDgCIgDgFIgBgFQgLgQgLgTIgJAAIAAAdQAEAGAAAEQAAAJgOAAQgHAAgHgEgAOwASQgIgGAAgHQgBgFAEgLQAFgMAKgRQASgkABgJQAAgGgDAAQgFAAgFAGQgHAHgJAMIgDAGQgCAEgDABQgCACgFAAQgGAAgFgEQgFgEAAgGQAAgFADgDQADgDAFgCQANgQAIgHQAGgFAHgDQAGgCAGAAQAKAAAKAHQAHAFADAGQADAGAAAHQAAANgOAYQgUAjgCAGIgCAGIAAACIAAADIABAJQAAAEgDACQgCACgDAAQgHAAgHgGg");
	this.shape.setTransform(100.3,12.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(0,0,200.6,24.8), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACjBpIADgOIAAiCIgCgGQgCgEAAgCQAAgGAGgEQAGgDAIAAQAGAAAFADQAEACAAAEIAAADQAKgJALAAQAIAAAHAEQAHAFAGAJQAIARAAAaQAAANgDANQgCAMgFALQgMAYgTAAQgEAAgEgDIgJgJIAAAYQAAADADAGQADAHAAACQAAAHgIAFQgGAFgJAAQgQAAAAgPgADGgCQABAVADAJQAEAOAFAAQAFAAAEgOQACgJABgVQAAghgMAAQgNAAAAAhgAH4BtQgEgDgCgFIgBgEQAAgDACgCIACgFIAGgdIgiheIgDgIQgCgEAAgDIABgDQACgIANAAQAIAAAFACQAGAEABAJIACAPIAOAvIAYg6IACgKQABgGAEgCQACgBADAAQAHAAAHAFQAGAFABAGQABAFgDAFIgFAKIgmBgQgDALgBAKIgBAIQABAFgCACQgDAFgIAAQgGAAgFgCgAjPBFQgFgDAAgFQAAgDACgFIgChgQgCgFAAgDQAAgLAOAAQAJAAAGAEQAHAEAAAGQgBACgEAIIAAA5QARgqARgdIAAgDQAAgGADgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQADAFAAAFQAAAIgOAAQgGAAgIgEQgHgEAAgDQAAgEACgFIAAg2QgQAigPAkQgCAGgEACQgDADgGAAQgHAAgHgEgAJiBFQgHgEgFgIQgKgQgDgaIgBgMQABgKACgKQACgKADgKQAJgYAUgBQAIgBAIAEQAJADAFAHQAEAIAEAIQADAHAAAJIAAAIQAAAEgFADQgFACgGAAQgGAAgDgCQgDgEgBgJIgCgPQgBgHgIAAQgDAAgDANQgBAMAAAPQAAATACAMQADAOAGAAQAGAAAFgJQAEgIABgGQAAgLANAAQAFAAAFADQAFADAAAFIgEAMQgIASgKAJQgKAIgLAAQgJAAgIgDgAkSBHQgKgBgHgGQgIgGgFgKQgMgUAAgcQABgTAIgVQAJgWAJAAIAKABIAOgBIAGABQAOAFAIAQQAIARAAAXQAAAfgLAVQgGAKgFAFQgGAFgHAAgAkcgXQgCALAAAMQAAAMADAQQAEAUAGAAQAEAAADgGQADgEACgKQADgRAAgKQgDgqgMAAQgHAAgEASgAEhBCQgHgGgGgNQgIgTAAgXQAAgNACgLQACgLAEgJQAGgLAJgGQAIgFALAAQAIAAAGAEQAGADAGAIQAEAFADAHIAFAQQAHAJgBAFQgCAKgPAAIgHgBIggACQAAAoAMAAQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAgBQACgDAAgHIgBgCIgBgEQAAgFAGgEQAHgDAIAAQAHAAAEADQAEADgBAGIgDAKQgEAQgIAIQgKAKgTAAQgJAAgHgGgAEugeQgCAFgBAKIAVgCQgFgTgFAAQgFAAgDAGgABTBCQgHgGgGgNQgIgTAAgXQAAgNACgLQACgLAEgJQAGgLAJgGQAHgFAMAAQAIAAAGAEQAHADAFAIQAEAFADAHIAFAQQAIAJgCAFQgCAKgPAAIgHgBIggACQAAAoAMAAQABAAAAAAQABAAAAgBQABAAAAgBQABAAAAgBQACgDAAgHIgBgCIgBgEQAAgFAGgEQAHgDAIAAQAHAAAEADQAEADgBAGIgDAKQgFAQgHAIQgJAKgTAAQgKAAgHgGgABggeQgCAFgBAKIAUgCQgEgTgFAAQgFAAgDAGgAqSBDQgKgEAAgEQABgEAEgHIgDiQQgEgHAAgEQABgGAEgCQAEgDAJAAQAKAAAIAFQAGAFABAFQgBADgGALIADBEIAGAAQAHgUAPgdQALgTAMgRIACgHQADgGAGAAQAHAAAJAGQAKAIgBAJQgBAGgLAEIgrBMQANAUAbAZQAHABABACIACACQAEADAAAFQAAAFgGAHQgEAFgFADQgEADgGAAQgEAAgDgCQgBgBgCgGIgCgHQgRgQgUgfIgMAAIAAAqQAEAHAAAGQAAAEgEACQgCACgIAAQgIAAgJgEgAAUBCQgHgEAAgDQAAgDACgFIAAhVIgYAEIAABRQADAIAAADQAAAJgNAAQgHAAgIgFQgHgEAAgDQAAgDACgFIAAheQgCgFAAgDQAAgLAPAAQAKAAAGAGIAmgGQAHAAAGADQAIAEAAAHQAAAEgEAGIAABaQACAHABADQgBAJgNAAQgGAAgIgFgAnUBAIAAgHIgCgGQgGAJgHAFQgHAFgMAAQgHAAgGgEQgHgEgEgHIgGgMQgCgGAAgGQABgJAGgIQAGgJAMgGIAigVIABgFQAAgFgEgCQgDgCgFAAQgEAAgOAMQgHAJgFACQgIAAgEgJQgGgJAAgFQAAgDAEgDQAEgEAIgCQAUgNAUgBQAQAAAJAKQAIALAAAVIAAAtQABAGACAJQAFADADAEIABAEQAAAEgCAEIgGAGQgIAGgIAAQgIgBgDgGgAnrAOQgLAGgCAHQgBAHAEAEQADAFADAAQAKgBAHgOIAFgWQgIABgKAHgAF3BCQgHgEAAgDQAAgDADgGIAAhdQgDgFAAgDQAAgLAPAAQAJAAAGAEQAHAEgBAGQAAACgEAIIAAAkIAFAAIAfgyQAEgLAHAAQAHAAAHAGQAHAFAAAGQAAAEgDACQgCADgFACIgbAqQAKASAMAQIAHADQADADAAAEQAAAFgFAGQgHAIgJAAQgEAAgDgCIgCgFIgDgFQgKgQgKgTIgKAAIAAAdQADAFAAAFQAAAIgNAAQgGAAgJgEgAmgBCQgIgEAAgDQAAgDAEgGIAAhdQgDgFAAgDQAAgLAPAAQAIAAAHAEQAGAEAAAGQAAACgEAIIAAAkIAEAAIAggyQADgLAHAAQAHAAAIAGQAGAFAAAGQAAAEgCACQgDADgFACIgaAqQAKASAMAQIAGADQADADABAEQgBAFgEAGQgIAIgIAAQgFAAgCgCIgDgFIgCgFQgLgQgKgTIgJAAIAAAdQADAFAAAFQAAAIgNAAQgHAAgIgEgAjKhmQAAgHAGgEQAEgEAKAAQAKACABAGQACAEgDADQABAFACACQADACAEAAQALAAAFgJQABgFADgDQADgCAGAAQAFAAACADQADACAAAFQAAAEgCADQgFAKgKAGQgJAFgNAAQgkgBgEgbg");
	this.shape.setTransform(67.1,12);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(0,0,134.1,24.1), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0A54A5").s().p("AASA/QgBgBAAgJIgSggIgOAXIgBAQQgDAFgIAAQgIAAgIgEQgHgFAAgHQAAgGAHgGIAbgqIgWgiQgGgDgBgDQgCgDAAgDQAAgGAIgEQAHgFAIABQAJgBADAGIABAGIAAAHIALATIANgYQAAgGABgDQADgFALABQAHgBAGADQAGADAAAFIgBAEIgHAJIgZAoIAcAtQAJAGAAAFQAAAFgHAEQgHAEgJAAQgJgBgBgDg");
	this.shape.setTransform(252.1,117.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0A54A5").s().p("AAQA8IgBgHIgCgGQgGAJgHAFQgGAFgMAAQgHAAgGgEQgGgEgFgHIgGgMQgCgGAAgGQABgJAGgIQAGgJAMgGIAhgVIABgFQAAgFgDgCQgDgCgFAAQgEAAgOAMQgGAJgGACQgHAAgFgJQgGgJAAgFQAAgDAEgDQAEgEAIgCQAUgNATgBQARAAAIAKQAJALAAAVIAAAtQAAAGACAJQAGADADAEIABAEQAAAEgCAEIgGAGQgJAGgIAAQgIgBgCgGgAgHAKQgLAGgBAHQgBAHADAEQADAFAEAAQAJgBAGgOIAFgWQgIABgJAHg");
	this.shape_1.setTransform(241.2,117.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0A54A5").s().p("AgqA/QgHgEAAgEQAAgDADgFIAAhdQgCgGAAgCQAAgLAOAAQAJgBAGAFQAHAEAAAFQgBADgEAHIAAAkIAFAAIAegxQADgLAIAAQAGAAAIAFQAHAGAAAGQAAADgDADQgCADgFACIgaApQAJATAMAQIAHADQADADAAAEQAAAFgEAGQgIAHgJAAQgEAAgDgCIgCgEIgDgGQgKgPgKgUIgJAAIAAAdQADAGAAAFQAAAIgNAAQgGAAgJgEg");
	this.shape_2.setTransform(230.5,117.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0A54A5").s().p("AgqBCQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgDQAAgEADgFIAAg2QgRAigOAkQgBAGgEACQgEADgFAAQgIAAgGgEg");
	this.shape_3.setTransform(219,117.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0A54A5").s().p("AggBBIgHgCIgGgEIgCgEQAAgDADgFIAAgjQgCgGAAgFIAAgFIACgFIAAgmQgCgFgBgDQABgLAPAAIAIABIAGAEIAFAEQABACABADQgBADgEAHIAAAcIAegEIAAgeIgCgJQAAgFADgCQADgCAFAAQALAAAHAEQAGAEAAAGIgEAKIAAAYQACAFAAAFIgBAFIgBAFIAAAqIACAJQAAAJgMAAIgIgBIgHgDIgFgEIgCgDQAAgEADgFIAAgiIgeADIAAAlQADAGAAAEQAAAJgNAAg");
	this.shape_4.setTransform(207.7,117.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0A54A5").s().p("AgXBDIgKgEIgJgGQgDgCgBgBQAAgDAEgGIAAheIgDgKQAAgEADgBQADgEAJAAQAIAAAHAEQAGAEAAAGIgBACIgBAFIgBAGIAAAaQARgKAQAAIAJACQAEACAEAEQAEAEACAFQADAGAAAHQAAAIgCAGQgBAHgEAGQgHAMgJAIQgJAIgLAFQgKAEgJAAIgIgCgAAAADIgNAHIAAAjQAEgBAGgFIAJgKQAFgFAEgGQADgHAAgEIgBgGQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQgGAAgHADg");
	this.shape_5.setTransform(197,117.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0A54A5").s().p("AgoBAQgFgCgDgFIABgGQACgDAGgCIAahYIAAgCIAAgDQAAgJAFgFQAGgFAJAAQAHAAAHAFQAGAEAAAGQAAAFgEAFIAXBZQADAGAAADQAAAJgLAAIgIgBIgIgDIgGgEQAAAAgBgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgEADgFIgNhAIgRBBIABAHQAAAFgFAEQgFADgGAAQgGABgGgDg");
	this.shape_6.setTransform(186.3,117.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0A54A5").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_7.setTransform(175.8,117.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0A54A5").s().p("AgeBDQgIgEAAgDQAAgDADgGIgChWQgEgCgBgFQADgTARgCIAIABIAggEQAGgEAEAAQAFAAAEAHQAFAHAAAGQABAFgEAEQgDADgFABQgDAAgHgDIgdAEIACBZQAEAFAAAFQAAAEgEACQgDACgHAAQgHAAgHgEg");
	this.shape_8.setTransform(166.3,117.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0A54A5").s().p("AgSBVQgEgCgCgGIgBgEQAAgDACgCIADgFIAFgcIghhfIgEgIQgCgDAAgEIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAQIAPAwIAWg8IACgKQABgGAEgCQACgBADAAQAHAAAHAFQAGAFABAHQABAEgDAFIgFAKIgeBJIgIAXQgDALgBAKIAAAIQAAAFgCADQgDAEgHAAQgGAAgFgCg");
	this.shape_9.setTransform(155.9,119.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0A54A5").s().p("AgVA9QgIgGgFgNQgIgTAAgWQAAgNACgMQACgLAEgJQAGgLAIgFQAIgGAMAAQAGAAAHAEQAGADAGAIQAEAGADAGIAFAQQAHAJgBAGQgCAJgPAAIgHgBIgfADQAAAnAMAAQAAAAAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgHIAAgBIgBgFQAAgFAGgEQAHgDAHAAQAIAAAEADQADADAAAGIgDAKQgFARgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgCQgEgSgFgBQgEABgDAFg");
	this.shape_10.setTransform(145.6,117.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0A54A5").s().p("AgsBNIABgHIACgHIAAiCIgCgGQgCgEAAgCQAAgGAHgEQAFgDAHAAQAHABAFACQAEADAAADIAAADQAKgJAJAAQAKAAAGAFQAIAFAEAIQAJARAAAaQAAAPgDAMQgCALgGAMQgLAXgSAAQgEAAgEgDIgJgJIAAAZQAAACADAHQADAGAAADQAAAHgHAEQgIAFgIABQgQgBAAgPgAgJgdQACAVACAIQADAPAFAAQAFAAAEgPQACgIABgVQAAgigMAAQgMAAAAAig");
	this.shape_11.setTransform(135.3,120);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0A54A5").s().p("AAzBEQgEgCgEgFQgBgDgBgIIgBgYIAAgMIAAgLQABgQgCAAQgCgBgGAOIgQArIgBALQAAAIgEABQgDACgEAAQgGAAgGgEQgGgFgBgGQgDgIAAgSIABgjQgBgJgBAAIgJARQgFAIgCALQgDAMAAANQgCADABAIQABAIgDABQgDADgFABQgFAAgGgEQgGgDgCgEQgEgGgBgpIAAg2IgCgGIgBgGIABgEQADgFANABQAOgBAEAIIAAADIgCAGQgCAEgBACIAAAaIATglIADgGIADgEQADgDAGAAQAJAAAJAEQAJAEAAAGQAAAGgCADIgCAGIAAAwQAEgIAJgeIAHgSQACgGACgCQAGgEAKAAQAIAAAGADQAEADAAAFIAABcQABADAEAEQAFADAAAEIgBAEQgCAFgDACQgDACgFAAQgHAAgGgCg");
	this.shape_12.setTransform(122,117.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0A54A5").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_13.setTransform(102.5,117.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0A54A5").s().p("AAOBXIgBgDIABgGIACgFQgGAHgGAFQgFADgHAAQgUAAgIgVQgDgJgCgKQgCgLAAgNQAAgMACgMQADgKAFgKQAMgWARAAQAIAAAKAPIAAgdQAAgEgDgGQgDgFAAgDIACgFQAEgLAOAAQALAAAEAJIABAFIgCAHIgCAHIAACCIACAHIACAFIgBAEQgDAHgOgBQgJAAgDgDgAgGgMQgDAEgBAGQgDALAAAPIAAAIIAAAIQAAANADAHQADAGAGAAQABAAACgEIAGgLQADgOAAgNQAAgLgEgOQgFgPgDAAQgDAAgCAEg");
	this.shape_14.setTransform(233.9,88.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0A54A5").s().p("AgvA9QgBgBgBgJIgBgVIABhNIgBgGIAAgFQAAgEABgDQAEgEAFAAQAHAAAHADQAGAEABAEIACAEIgDAHIgBAHIAAAfQAJgUAMgUQANgRARABQAEAAAEAFQAEAEABAJQAEANAAAbIAAAoIADAGQABACAAAEQAAAFgGADQgGAEgIAAQgLAAgFgHQAChGgFgBQgHgBgUA/IAAAOQgBAIgEAEQgFADgEAAQgJAAgJgJg");
	this.shape_15.setTransform(222.9,91.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0A54A5").s().p("AgmA/QgGgGgDgLQgCgIAAgIQgBgKAGgKQAGgJAKgGIAjgVIABgIQAAgHgDgBIgGgBQgFAAgEADIgFAGQgDABgEAHQgEAFgEABQgGABgEgFQgGgFAAgHQAAgDACgDQAGgJAKgGQAIgFAKgDQAKgCALAAQAIAAAGAEQAFADADAIQADAJACAcQABAVAEAaQAAADAEAEQADAFABADIgBAEQgEALgNAAQgFAAgCgCQgEgCgCgIQgCgNgDgHQgBAMgNANQgFAHgHADQgHADgGAAQgJAAgFgFgAgCACQgIAEgFAGQgJAJAAAHQABAGAEAGQACADADAAQAFAAAIgOQADgJAIgZg");
	this.shape_16.setTransform(210.8,91);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0A54A5").s().p("AgJBhQgEgCgCgFQgCgBAAgEIACgHIACgJIgBiUIAAgMQAAgDAGgCQAGgBAFgBQAKABACADQADADAAAEIgCAIIgCAKIAACJIACAJIACAIIgBAFQgDAEgEACQgEACgGABQgFAAgEgCg");
	this.shape_17.setTransform(202.2,88.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0A54A5").s().p("AgrBbQgDgHgBg+IABhoIAAgEIAAgEIABgFQADgFAIABQAHAAAHADQAGAEgCAFIgCAEQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABIAABJQAOgdAYgCQAOgBAIAWQAIATAAAcQgBAXgFARIACAHQAAAGgFACQgGAEgHAAQgEAAgEgDQgDgBgBgEIgBgFQAAgDACgDQADgEAAgCQADgMAAgXQAAgngGAAQgCAAgEADIgIAJQgKAUgEAMIgGAUQgBAJAAAJIAAACIABAGIACAGQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBABQgFAJgHAAQgGAAgGgKg");
	this.shape_18.setTransform(194.2,88);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0A54A5").s().p("AgSA/QgHgEgFgJQgFgJgCgKQgCgLAAgNQAAgcALgWQAMgYATABQAHAAAGADQAHAFAEAIQAEAHACAIQACAHAAAJIgBAIQgBAIgLAAQgJAAgGgFQgCgDAAgJIABgHIAAgGQgBgLgDAAQgCAAgCAGIgDARQgFAWAAAUQAAAWAHAAQAIAAAEgOQACgCABgGQAAgFACgCQADgCAFAAQAHAAAFADQAGADAAAGQAAAFgFAFIgIALQgHALgHAGQgIAFgHABQgJgBgHgEg");
	this.shape_19.setTransform(183.5,90.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0A54A5").s().p("AgTA/QgIgFgFgKQgGgJgCgMQgDgLAAgOQAAgLACgLQACgLAEgKQAEgKAGgGQAFgGAGgCIAOgCQARAAALAMQAIAHAEAOQAEANAAASQAAAcgLAUQgGAMgJAFQgIAGgKAAQgKAAgJgFgAgKgeQgFANAAAPQAAAVACAJQADAQAKACQACAAADgEQADgFADgJIAEgTIABgSQAAgigOgBIgBAAQgGAAgFAOg");
	this.shape_20.setTransform(173.2,90.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0A54A5").s().p("AgkBiQgGgDgBgDIgCgEIABgFIAAggIAAgdIgFgKQgEgFABgFQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABgBIAFgDIAAhKQgCgEAAgDQAAgFAHgDQADgCAGAAQAJAAAFADQAFACACAFIABAEQAAADgEAGQgEAGAAAFQgBAkABASIAdgGQgCgSACgvIgCgKQAAgHAIgEIAGgBQAIAAAHAEQAJAEAAAHQABAEgFAFQgEAEAAAEIAAA4QAEADAEAFQAEAFAAAEQAAAEgEABIgIAEIABA1IACAGIABAGQAAAFgIADIgEABQgHAAgJgEQgFgDgDgDQgCgDAAgDIACgIIAEgJIAAgoIgdAHIAAAfIAAAVIACAJIABAIQAAAFgDACQgDADgFAAQgGAAgGgDg");
	this.shape_21.setTransform(161.9,88);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0A54A5").s().p("AgsBNIACgHIABgHIAAiCIgCgGQgCgDAAgDQAAgGAGgDQAFgDAJAAQAGAAAFACQAEADAAAEIAAACQAKgJAKAAQAIAAAHAEQAHAGAGAJQAIAQAAAaQAAAOgDANQgCALgGALQgLAYgTAAQgDAAgEgDIgJgIIAAAXQAAADADAGQADAHAAACQAAAHgHAGQgIAEgIAAQgQAAAAgPgAgJgeQABAWADAIQAEAOAEAAQAFAAAEgOQACgIABgWQAAghgMAAQgMAAAAAhg");
	this.shape_22.setTransform(144.9,93);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0A54A5").s().p("AguBEIgKgFIgIgFQgEgDAAgCQAAgDADgFIAAhdIgCgKQAAgFACgBQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBADIgBAEIgCAGIAAAbQATgKAQAAIAHABQAFACADADQAEAEADAGQACAGAAAHQAAAIgBAHQgCAGgDAGQgHAMgJAIQgJAIgKAFQgLAEgJAAIgJgBgAgWADIgNAIIAAAhQAEgBAGgDIAKgKQAFgGAEgHQADgGAAgFIgBgFQAAAAgBgBQAAAAgBAAQAAAAgBAAQgBAAAAAAQgGAAgIADgAAoA9QgIgEAAgEQAAgDADgFIAAhdQgCgFAAgEQAAgKAPAAQAIAAAGAEQAHAEAAAFQAAADgEAHIAABbQADAGAAAEQAAAEgEACQgDACgHAAQgHAAgHgEg");
	this.shape_23.setTransform(132.1,90.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0A54A5").s().p("AgSA/QgHgEgFgJQgEgJgDgKQgCgLAAgNQAAgcALgWQAMgYASABQAJAAAFADQAGAFAFAIQAEAHACAIQACAHAAAJIAAAIQgDAIgKAAQgKAAgFgFQgCgDAAgJIABgHIAAgGQAAgLgFAAQgBAAgBAGIgFARQgEAWAAAUQAAAWAHAAQAIAAAEgOQACgCAAgGQAAgFADgCQADgCAFAAQAHAAAFADQAGADAAAGQgBAFgEAFIgIALQgHALgHAGQgIAFgGABQgKgBgHgEg");
	this.shape_24.setTransform(120.3,90.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0A54A5").s().p("AgqBbQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAFQAGAEAAAFQAAADgEAHIAAA5QARgqAQgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHAEAAAFQAAAEgEAHIAABaQACAGAAAEQAAAJgNAAQgHAAgHgFQgIgEAAgDQAAgDADgGIAAg3QgRAjgOAkQgBAGgEACQgEADgFAAQgIAAgGgEgAglhPQAAgIAFgEQAFgDAKgBQAKACABAGQABAFgCADQAAAEADADQADACADAAQALAAAFgKQABgFADgCQADgDAGAAQAFAAACADQACADAAAFQAAADgBADQgGAKgJAGQgJAFgNAAQgjAAgEgbg");
	this.shape_25.setTransform(226,61.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0A54A5").s().p("AguBDIgKgEIgIgGQgEgCAAgBQAAgDADgGIAAheIgCgKQAAgEACgBQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBACIgBAFIgCAGIAAAaQATgKAQAAIAHACQAFACADAEQAEADADAGQACAGAAAIQAAAHgBAGQgCAIgDAFQgHAMgJAIQgJAIgKAFQgLAEgJAAIgJgCgAgWADIgNAHIAAAjQAEgBAGgFIAKgKQAFgFAEgGQADgHAAgEIgBgGQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgGAAgIADgAAoA9QgIgEAAgDQAAgDADgGIAAheQgCgEAAgDQAAgLAPAAQAIAAAGAEQAHAEAAAGQAAACgEAHIAABbQADAFAAAEQAAAFgEACQgDACgHAAQgHAAgHgEg");
	this.shape_26.setTransform(212.7,63.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0A54A5").s().p("AggBBIgIgCIgFgEIgCgEQAAgDADgFIAAgjQgCgGAAgFIABgFIABgFIAAgmQgDgFAAgDQAAgLAPAAIAIABIAHAEIAEAEQACACAAADQABADgFAHIAAAcIAdgEIAAgeIgCgJQAAgFADgCQAEgCAFAAQAMAAAFAEQAHAEAAAGIgEAKIAAAYQACAFAAAFIAAAFIgCAFIAAAqIADAJQgBAJgNAAIgHgBIgHgDIgGgEIgCgDQAAgEADgFIAAgiIgdADIAAAlQADAGAAAEQAAAJgNAAg");
	this.shape_27.setTransform(199.6,63.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0A54A5").s().p("AgKA+QgIgDAAgEQAAgDADgFIAAgcIgIAAQgJAQgOATIgFAKQgDADgEAAQgHgBgHgGQgHgFAAgHQAAgFAEgCIAGgDQASgTAGgPIgagqQgFgCgDgDQgDgDAAgDQAAgGAIgGQAHgFAGAAQAIAAADAJIABABIAfAyIADAAIAAgoQgCgFAAgEQAAgLAPABQAHAAAGADQAHAFAAAFQAAACgEAJIAAAjIADAAQAbgmAHgMQADgKAIAAQAGAAAHAFQAIAGAAAGQAAAHgKAEIgdAqQAJAQATASIAHADQADADAAAEQAAAFgEAFQgEAFgEABQgEADgFAAQgEAAgDgDIgDgFIgBgFQgRgRgMgSIgHAAIAAAeQACAFAAAEQAAAFgDABQgDADgHAAQgGAAgHgFg");
	this.shape_28.setTransform(185.5,63.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0A54A5").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_29.setTransform(171.9,63.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#0A54A5").s().p("AgsBNIACgIIABgGIAAiCIgCgGQgCgEAAgCQAAgGAGgEQAGgDAIAAQAGABAFACQAEADAAADIAAADQAKgJAKAAQAIAAAHAFQAHAFAGAIQAIARAAAaQAAAPgDAMQgCAMgFALQgMAXgTAAQgEAAgDgDIgJgJIAAAZQAAACADAHQADAGAAADQAAAGgIAFQgGAFgJABQgQAAAAgQgAgJgdQABAVADAIQAEAPAEAAQAFAAAEgPQACgIABgVQAAgigMAAQgMAAAAAig");
	this.shape_30.setTransform(161.7,66.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0A54A5").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_31.setTransform(151.3,63.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#0A54A5").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_32.setTransform(141.2,63.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#0A54A5").s().p("AgMBhQgJgEAAgEQAAgEAEgHIAAiHIgSADQgGAGgFABQgLABgDgQIAAgFQAAgHADgEQAEgEAHgCIALAAIBCgJQAIgHADAAQAGgBAGAIQAGAIABAHQABAGgEAEQgDAFgEAAIgOgDIgWADIAACPQAEAIAAAGQAAAEgEABQgDADgHAAQgHAAgKgFg");
	this.shape_33.setTransform(129.4,60.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Слой 1
	this.instance = new lib.say1();
	this.instance.parent = this;
	this.instance.setTransform(31,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(31,0,284,216), null);


(lib.Анимация12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMBXQgBgCAAgFIABgIIAAgJIgBgGIAAgEQACgFAIAAQAIAAAEADQAGACABAFIABAFIAAAIIgBAHIAAAGQABAEgCADQgDAEgHAAQgKAAgHgIgAgNAbQgCgDAAgEIABgEIAAgFQgDgcAAgeQAAgoAEgEQADgDAIAAQAIAAAFACQAEACABAEIABAEIgCAGIgBAHIAABMIABAKIACAIQAAAFgDACQgEACgFABQgLgBgHgHg");
	this.shape.setTransform(84.1,-1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQBAQgIgEgFgHQgKgRgCgaIgBgLQAAgLACgKQACgKADgJQAKgYAUgCQAGAAAJADQAJAEAEAHQAFAHADAIQADAIAAAIIAAAJQAAAEgEACQgGADgGAAQgFAAgEgDQgDgEgBgJIgBgOQgCgHgGAAQgDAAgDAMQgCANAAAQQAAARADANQADAOAFAAQAGAAAEgJQAFgJAAgGQAAgLANAAQAGAAAFADQAEADABAFIgEAMQgJASgJAJQgKAJgLAAQgIAAgIgEg");
	this.shape_1.setTransform(77.3,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBVQgEgDgCgEIgBgFQAAgCACgDIADgFIAFgdIghheIgEgHQgCgFAAgDIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAPIAPAwIAWg6IACgLQABgFAEgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIgeBJIgIAXQgDALgBAKIAAAIQAAAFgCADQgDAEgHAAQgGAAgFgCg");
	this.shape_2.setTransform(66.8,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpA/QgIgEAAgDQAAgDADgGIAAheQgCgEgBgEQABgKAPgBQAIABAGAEQAGAEAAAGQAAACgDAIIAAAkIAEAAIAegzQADgKAIAAQAGAAAIAGQAHAFAAAGQAAAEgCACQgDADgFABIgbArQAKASAMAQIAGACQAEADAAAFQAAAFgFAFQgHAJgJAAQgEgBgDgBIgDgGIgCgEQgKgRgJgSIgJAAIAAAcQACAGAAAEQAAAJgNAAQgHAAgHgEg");
	this.shape_3.setTransform(56.4,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_4.setTransform(45.7,1.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsBNIABgHIACgHIAAiCIgCgGQgCgDAAgDQAAgGAHgDQAFgDAHAAQAHAAAFACQAEADAAAEIAAACQAKgJAJAAQAKAAAGAEQAIAGAEAJQAJAQAAAaQAAAOgDANQgCALgGALQgLAYgSAAQgEAAgEgDIgJgIIAAAXQAAADADAGQADAHAAACQAAAIgHAFQgIAEgIAAQgQAAAAgPgAgJgeQACAWACAIQADAOAFAAQAFAAAEgOQACgIABgWQAAghgMAAQgMAAAAAhg");
	this.shape_5.setTransform(35.4,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_6.setTransform(25.1,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AARA+QgIgEAAgDQAAgDADgFIAAhVIgYAEIAABRQADAIAAADQAAAJgNAAQgHAAgIgFQgIgEAAgDQAAgDADgFIAAheQgCgFAAgDQAAgLAPAAQAKAAAGAGIAmgGQAGAAAHADQAIAEAAAHQAAAEgEAGIAABaQACAHAAADQAAAJgNAAQgHAAgHgFg");
	this.shape_7.setTransform(14.9,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqBbQgGgDAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGADQAGAFAAAFQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgFAEgDQAEgDAHAAQAIAAAHAEQAHADAAAHQAAADgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgDQgIgEAAgEQAAgEADgEIAAg4QgRAjgOAlQgBAFgEADQgEADgFAAQgIAAgGgFgAglhQQAAgHAFgEQAFgEAKABQAKABABAGQABAEgCADQAAAFADACQADACADAAQALAAAFgJQABgFADgDQADgCAGAAQAFABACACQACACAAAFQAAAEgBADQgGAKgJAGQgJAGgNgBQgjgBgEgbg");
	this.shape_8.setTransform(-1.9,-1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AguBEIgKgFIgIgFQgEgDAAgCQAAgDADgFIAAhdIgCgKQAAgFACgBQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBADIgBAEIgCAGIAAAbQATgKAQAAIAHABQAFACADADQAEAEADAGQACAGAAAHQAAAIgBAHQgCAGgDAGQgHAMgJAIQgJAIgKAFQgLAEgJAAIgJgBgAgWADIgNAIIAAAhQAEgBAGgDIAKgKQAFgGAEgHQADgGAAgFIgBgFQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgGAAgIADgAAoA9QgIgEAAgEQAAgDADgFIAAhdQgCgFAAgEQAAgKAPAAQAIAAAGAEQAHAEAAAFQAAADgEAHIAABbQADAGAAAEQAAAEgEACQgDACgHAAQgHAAgHgEg");
	this.shape_9.setTransform(-15.2,1.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_10.setTransform(-27.9,1.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_11.setTransform(-38.4,1.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgsBNIACgHIABgHIAAiCIgCgGQgCgDAAgDQAAgGAGgDQAFgDAIAAQAHAAAFACQAEADAAAEIAAACQAKgJAJAAQAKAAAGAEQAHAGAGAJQAIAQAAAaQAAAOgDANQgCALgGALQgLAYgTAAQgDAAgEgDIgJgIIAAAXQAAADADAGQADAHAAACQAAAIgHAFQgIAEgIAAQgQAAAAgPgAgJgeQACAWACAIQADAOAFAAQAFAAAEgOQACgIABgWQAAghgMAAQgMAAAAAhg");
	this.shape_12.setTransform(-48.7,3.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_13.setTransform(-59.1,1.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgtBQIgHgEIgGgDQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAgDADgGIAAgUQgCgFAAgDQAAgDABgCIAEgDIAFgCIAEgBIABAAQAFgMAFgUIANgxQgDgFAAgEQAAgLAPABIAFAAIAEABIAIADIAMABIAKACQAEAAACADQADABAAAGIgEAKIAHBFIACAAIAIABIAFADIADADIABAEIgEAKIgCAWQADAFAAAFQAAAEgEACQgDACgGAAIgFgBIgIgDIgHgDQAAgBgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgDAEgGIABgOIg2AGIAAAMQADAGAAAEQAAAFgEABQgDADgHAAgAABgpIgGAhIgJAeIAagCIgGhHIgDgBg");
	this.shape_14.setTransform(-70.6,2.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeA9QgGgEgCgEQgDgEgBgEQABgOAPgBQAEAAAEAFIAFAEIAFACQAFgBAHgKQAIgKAAgEQABgFgDgCQgCAAgEABIgDADQgIAHgDAAQgIAAgGgEQgGgGAAgHQAAgEAGgDIALgEQASgKAFgOQABgEgCgDQgEAAgFADQgGADgGAHQgGAEgEAAQgIAAgGgGQgFgFAAgKQAAgFAGgCIAKgCIAVgMQAMgGALADQAJADAGAGQAGAHgBAJQgBARgPAQQAJADAEAEQAFADABAFQABAWgTAVQgSAUgPAAQgJAAgMgIg");
	this.shape_15.setTransform(-82,0.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88.5,-14.5,177,29);


(lib.Анимация11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMBXQgBgCAAgFIABgIIAAgJIgBgGIAAgEQACgFAIAAQAIAAAEADQAGACABAFIABAFIAAAIIgBAHIAAAGQABAEgCADQgDAEgHAAQgKAAgHgIgAgNAbQgCgDAAgEIABgEIAAgFQgDgcAAgeQAAgoAEgEQADgDAIAAQAIAAAFACQAEACABAEIABAEIgCAGIgBAHIAABMIABAKIACAIQAAAFgDACQgEACgFABQgLgBgHgHg");
	this.shape.setTransform(84.1,-1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQBAQgIgEgFgHQgKgRgCgaIgBgLQAAgLACgKQACgKADgJQAKgYAUgCQAGAAAJADQAJAEAEAHQAFAHADAIQADAIAAAIIAAAJQAAAEgEACQgGADgGAAQgFAAgEgDQgDgEgBgJIgBgOQgCgHgGAAQgDAAgDAMQgCANAAAQQAAARADANQADAOAFAAQAGAAAEgJQAFgJAAgGQAAgLANAAQAGAAAFADQAEADABAFIgEAMQgJASgJAJQgKAJgLAAQgIAAgIgEg");
	this.shape_1.setTransform(77.3,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBVQgEgDgCgEIgBgFQAAgCACgDIADgFIAFgdIghheIgEgHQgCgFAAgDIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAPIAPAwIAWg6IACgLQABgFAEgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIgeBJIgIAXQgDALgBAKIAAAIQAAAFgCADQgDAEgHAAQgGAAgFgCg");
	this.shape_2.setTransform(66.8,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgpA/QgIgEAAgDQAAgDADgGIAAheQgCgEgBgEQABgKAPgBQAIABAGAEQAGAEAAAGQAAACgDAIIAAAkIAEAAIAegzQADgKAIAAQAGAAAIAGQAHAFAAAGQAAAEgCACQgDADgFABIgbArQAKASAMAQIAGACQAEADAAAFQAAAFgFAFQgHAJgJAAQgEgBgDgBIgDgGIgCgEQgKgRgJgSIgJAAIAAAcQACAGAAAEQAAAJgNAAQgHAAgHgEg");
	this.shape_3.setTransform(56.4,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_4.setTransform(45.7,1.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsBNIABgHIACgHIAAiCIgCgGQgCgDAAgDQAAgGAHgDQAFgDAHAAQAHAAAFACQAEADAAAEIAAACQAKgJAJAAQAKAAAGAEQAIAGAEAJQAJAQAAAaQAAAOgDANQgCALgGALQgLAYgSAAQgEAAgEgDIgJgIIAAAXQAAADADAGQADAHAAACQAAAIgHAFQgIAEgIAAQgQAAAAgPgAgJgeQACAWACAIQADAOAFAAQAFAAAEgOQACgIABgWQAAghgMAAQgMAAAAAhg");
	this.shape_5.setTransform(35.4,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_6.setTransform(25.1,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AARA+QgIgEAAgDQAAgDADgFIAAhVIgYAEIAABRQADAIAAADQAAAJgNAAQgHAAgIgFQgIgEAAgDQAAgDADgFIAAheQgCgFAAgDQAAgLAPAAQAKAAAGAGIAmgGQAGAAAHADQAIAEAAAHQAAAEgEAGIAABaQACAHAAADQAAAJgNAAQgHAAgHgFg");
	this.shape_7.setTransform(14.9,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqBbQgGgDAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGADQAGAFAAAFQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgFAEgDQAEgDAHAAQAIAAAHAEQAHADAAAHQAAADgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgDQgIgEAAgEQAAgEADgEIAAg4QgRAjgOAlQgBAFgEADQgEADgFAAQgIAAgGgFgAglhQQAAgHAFgEQAFgEAKABQAKABABAGQABAEgCADQAAAFADACQADACADAAQALAAAFgJQABgFADgDQADgCAGAAQAFABACACQACACAAAFQAAAEgBADQgGAKgJAGQgJAGgNgBQgjgBgEgbg");
	this.shape_8.setTransform(-1.9,-1.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AguBEIgKgFIgIgFQgEgDAAgCQAAgDADgFIAAhdIgCgKQAAgFACgBQAEgEAIAAQAJAAAGAEQAHAEAAAGIgBADIgBAEIgCAGIAAAbQATgKAQAAIAHABQAFACADADQAEAEADAGQACAGAAAHQAAAIgBAHQgCAGgDAGQgHAMgJAIQgJAIgKAFQgLAEgJAAIgJgBgAgWADIgNAIIAAAhQAEgBAGgDIAKgKQAFgGAEgHQADgGAAgFIgBgFQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgGAAgIADgAAoA9QgIgEAAgEQAAgDADgFIAAhdQgCgFAAgEQAAgKAPAAQAIAAAGAEQAHAEAAAFQAAADgEAHIAABbQADAGAAAEQAAAEgEACQgDACgHAAQgHAAgHgEg");
	this.shape_9.setTransform(-15.2,1.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_10.setTransform(-27.9,1.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_11.setTransform(-38.4,1.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgsBNIACgHIABgHIAAiCIgCgGQgCgDAAgDQAAgGAGgDQAFgDAIAAQAHAAAFACQAEADAAAEIAAACQAKgJAJAAQAKAAAGAEQAHAGAGAJQAIAQAAAaQAAAOgDANQgCALgGALQgLAYgTAAQgDAAgEgDIgJgIIAAAXQAAADADAGQADAHAAACQAAAIgHAFQgIAEgIAAQgQAAAAgPgAgJgeQACAWACAIQADAOAFAAQAFAAAEgOQACgIABgWQAAghgMAAQgMAAAAAhg");
	this.shape_12.setTransform(-48.7,3.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAEBDIgFgBQgJgBgIgGQgHgFgGgLQgLgUAAgaQAAgUAJgWQAIgWAJAAIAFABIAFABIAGgBIAHgBIAGABQAOAGAIAPQAIARAAAZQAAAdgLAWQgFAKgGAFQgGAFgGAAgAgLgbQgCALAAANQAAALADAPQAEAUAGAAQADAAADgFQADgFACgKQADgRAAgJQgDgqgLAAQgHAAgEASg");
	this.shape_13.setTransform(-59.1,1.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgtBQIgHgEIgGgDQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAgDADgGIAAgUQgCgFAAgDQAAgDABgCIAEgDIAFgCIAEgBIABAAQAFgMAFgUIANgxQgDgFAAgEQAAgLAPABIAFAAIAEABIAIADIAMABIAKACQAEAAACADQADABAAAGIgEAKIAHBFIACAAIAIABIAFADIADADIABAEIgEAKIgCAWQADAFAAAFQAAAEgEACQgDACgGAAIgFgBIgIgDIgHgDQAAgBgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgDAEgGIABgOIg2AGIAAAMQADAGAAAEQAAAFgEABQgDADgHAAgAABgpIgGAhIgJAeIAagCIgGhHIgDgBg");
	this.shape_14.setTransform(-70.6,2.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeA9QgGgEgCgEQgDgEgBgEQABgOAPgBQAEAAAEAFIAFAEIAFACQAFgBAHgKQAIgKAAgEQABgFgDgCQgCAAgEABIgDADQgIAHgDAAQgIAAgGgEQgGgGAAgHQAAgEAGgDIALgEQASgKAFgOQABgEgCgDQgEAAgFADQgGADgGAHQgGAEgEAAQgIAAgGgGQgFgFAAgKQAAgFAGgCIAKgCIAVgMQAMgGALADQAJADAGAGQAGAHgBAJQgBARgPAQQAJADAEAEQAFADABAFQABAWgTAVQgSAUgPAAQgJAAgMgIg");
	this.shape_15.setTransform(-82,0.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88.5,-14.5,177,29);


(lib.Анимация10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrANQgEgGAAgFQAAgEADgDIAHgBIALgBIAwgIIAHgCIAHgBIAEABQAEACACAEQACAEAAAGQAAAEgEADQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFgBIgHgBIgvAIIgHACIgHACQgGABgEgGg");
	this.shape.setTransform(61.8,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQBAQgHgEgGgHQgKgRgCgaIgBgLQAAgLACgKQACgKAEgJQAJgYAUgCQAGAAAJADQAIAEAFAHQAFAHADAIQADAIAAAIIAAAJQAAAEgEACQgFADgGAAQgHAAgCgDQgEgEgBgJIgCgOQgBgHgGAAQgDAAgDAMQgCANAAAQQAAARADANQADAOAFAAQAFAAAGgJQAEgJAAgGQAAgLAOAAQAFAAAFADQAFADAAAFIgEAMQgJASgJAJQgKAJgLAAQgJAAgHgEg");
	this.shape_1.setTransform(46,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBVQgEgDgCgEIgBgFQAAgCACgDIADgFIAFgdIghheIgEgHQgCgFAAgDIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAPIAPAwIAWg6IACgLQABgFAEgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIgeBJIgIAXQgDALgBAKIAAAIQAAAFgCADQgDAEgHAAQgGAAgFgCg");
	this.shape_2.setTransform(35.5,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqA/QgHgEAAgDQAAgDADgGIAAheQgDgEAAgEQAAgKAQgBQAIABAGAEQAHAEgBAGQAAACgDAIIAAAkIAEAAIAegzQAEgKAHAAQAHAAAHAGQAHAFAAAGQAAAEgDACQgCADgFABIgbArQAKASAMAQIAGACQAEADAAAFQAAAFgFAFQgHAJgJAAQgEgBgDgBIgDgGIgCgEQgKgRgJgSIgJAAIAAAcQACAGAAAEQAAAJgNAAQgGAAgJgEg");
	this.shape_3.setTransform(25.1,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_4.setTransform(14.2,1.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgqBbQgGgDAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGADQAGAFAAAFQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgFAEgDQAEgDAHAAQAIAAAHAEQAHADAAAHQAAADgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgDQgIgEAAgEQAAgEADgEIAAg4QgRAjgOAlQgBAFgEADQgEADgFAAQgIAAgGgFgAglhQQAAgHAFgEQAFgEAKABQAKABABAGQABAEgCADQAAAFADACQADACADAAQALAAAFgJQABgFADgDQADgCAGAAQAFABACACQACACAAAFQAAAEgBADQgGAKgJAGQgJAGgNgBQgjgBgEgbg");
	this.shape_5.setTransform(-2.7,-1.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqBCQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgDQAAgEADgFIAAg2QgRAigOAkQgBAGgEACQgEADgFAAQgIAAgGgEg");
	this.shape_6.setTransform(-14.2,1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKA/QgIgFAAgCQAAgEADgFIAAgbIgIAAQgJAPgOAUIgFAKQgDABgEAAQgHABgHgHQgHgFAAgIQAAgEAEgDIAGgCQASgUAGgPIgagqQgFgBgDgDQgDgDAAgDQAAgGAIgFQAHgGAGAAQAIAAADAJIABABIAfAyIADAAIAAgpQgCgEAAgDQAAgMAPAAQAHAAAGAFQAHAEAAAFQAAADgEAHIAAAkIADAAQAbgmAHgMQADgKAIAAQAGAAAHAGQAIAFAAAGQAAAHgKADIgdAqQAJAQATATIAHACQADADAAAFQAAAFgEAFQgEAFgEACQgEABgFAAQgEAAgDgBIgDgGIgBgEQgRgTgMgQIgHAAIAAAcQACAGAAAEQAAAFgDACQgDACgHAAQgGAAgHgEg");
	this.shape_7.setTransform(-28.4,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_8.setTransform(-41.9,1.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_9.setTransform(-52,1.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSBaQgKgHgIgNQgLgYAAgvQAAgTACgQQADgQAFgNQAMgeAXgBQAIAAAIAEQAHAEAFAIQAKAOADATIAFAOQAAAMgOAAQgJAAgHgEQgIgEAAgFIACgKQgBgLgCgFQgDgFgDAAQgHAAgDAXQgEAeAAARQABAhADALQACAKACAFQADAFAEAAQAEgBAFgNQAEgLABgIQgBgHAGgEQAFgEAHAAQAHAAAFADQAGAEgBAFQAAADgCAEIgDAGQgFARgKAOQgFAJgHAFQgHAFgGAAIgCABQgKAAgJgHg");
	this.shape_10.setTransform(-62.5,-1.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.8,-14.5,139.6,29);


(lib.Анимация9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrANQgEgGAAgFQAAgEADgDIAHgBIALgBIAwgIIAHgCIAHgBIAEABQAEACACAEQACAEAAAGQAAAEgEADQAAAAgBABQAAAAgBABQAAAAgBAAQAAAAgBAAIgFgBIgHgBIgvAIIgHACIgHACQgGABgEgGg");
	this.shape.setTransform(61.8,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQBAQgHgEgGgHQgKgRgCgaIgBgLQAAgLACgKQACgKAEgJQAJgYAUgCQAGAAAJADQAIAEAFAHQAFAHADAIQADAIAAAIIAAAJQAAAEgEACQgFADgGAAQgHAAgCgDQgEgEgBgJIgCgOQgBgHgGAAQgDAAgDAMQgCANAAAQQAAARADANQADAOAFAAQAFAAAGgJQAEgJAAgGQAAgLAOAAQAFAAAFADQAFADAAAFIgEAMQgJASgJAJQgKAJgLAAQgJAAgHgEg");
	this.shape_1.setTransform(46,1.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBVQgEgDgCgEIgBgFQAAgCACgDIADgFIAFgdIghheIgEgHQgCgFAAgDIABgDQACgIANAAQAJAAAEACQAGAEABAJIACAPIAPAwIAWg6IACgLQABgFAEgCQACgCADAAQAHAAAHAFQAGAFABAHQABAEgDAGIgFAJIgeBJIgIAXQgDALgBAKIAAAIQAAAFgCADQgDAEgHAAQgGAAgFgCg");
	this.shape_2.setTransform(35.5,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqA/QgHgEAAgDQAAgDADgGIAAheQgDgEAAgEQAAgKAQgBQAIABAGAEQAHAEgBAGQAAACgDAIIAAAkIAEAAIAegzQAEgKAHAAQAHAAAHAGQAHAFAAAGQAAAEgDACQgCADgFABIgbArQAKASAMAQIAGACQAEADAAAFQAAAFgFAFQgHAJgJAAQgEgBgDgBIgDgGIgCgEQgKgRgJgSIgJAAIAAAcQACAGAAAEQAAAJgNAAQgGAAgJgEg");
	this.shape_3.setTransform(25.1,1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_4.setTransform(14.2,1.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgqBbQgGgDAAgEQAAgDADgGIgChfQgDgGAAgDQAAgKAPAAQAJAAAGADQAGAFAAAFQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgFAEgDQAEgDAHAAQAIAAAHAEQAHADAAAHQAAADgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgDQgIgEAAgEQAAgEADgEIAAg4QgRAjgOAlQgBAFgEADQgEADgFAAQgIAAgGgFgAglhQQAAgHAFgEQAFgEAKABQAKABABAGQABAEgCADQAAAFADACQADACADAAQALAAAFgJQABgFADgDQADgCAGAAQAFABACACQACACAAAFQAAAEgBADQgGAKgJAGQgJAGgNgBQgjgBgEgbg");
	this.shape_5.setTransform(-2.7,-1.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgqBCQgGgDAAgFQAAgDADgFIgChgQgDgFAAgDQAAgLAPAAQAJAAAGAEQAGAEAAAGQAAACgEAIIAAA5QARgqAQgdIgBgDQAAgGAEgDQAEgCAHAAQAIAAAHAEQAHADAAAGQAAAEgEAHIAABaQACAFAAAFQAAAIgNAAQgHAAgHgEQgIgEAAgDQAAgEADgFIAAg2QgRAigOAkQgBAGgEACQgEADgFAAQgIAAgGgEg");
	this.shape_6.setTransform(-14.2,1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKA/QgIgFAAgCQAAgEADgFIAAgbIgIAAQgJAPgOAUIgFAKQgDABgEAAQgHABgHgHQgHgFAAgIQAAgEAEgDIAGgCQASgUAGgPIgagqQgFgBgDgDQgDgDAAgDQAAgGAIgFQAHgGAGAAQAIAAADAJIABABIAfAyIADAAIAAgpQgCgEAAgDQAAgMAPAAQAHAAAGAFQAHAEAAAFQAAADgEAHIAAAkIADAAQAbgmAHgMQADgKAIAAQAGAAAHAGQAIAFAAAGQAAAHgKADIgdAqQAJAQATATIAHACQADADAAAFQAAAFgEAFQgEAFgEACQgEABgFAAQgEAAgDgBIgDgGIgBgEQgRgTgMgQIgHAAIAAAcQACAGAAAEQAAAFgDACQgDACgHAAQgGAAgHgEg");
	this.shape_7.setTransform(-28.4,1.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVA9QgIgGgFgMQgIgUAAgXQAAgNACgLQACgLAEgJQAGgLAIgGQAIgFAMAAQAGAAAHAEQAGADAGAIQAEAFADAIIAFAQQAHAIgBAFQgCAKgPAAIgHgBIgfADQAAAoAMAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAgBABgBQABgDAAgGIAAgDIgBgDQAAgGAGgDQAHgEAHAAQAIAAAEADQADADAAAHIgDAKQgFAQgHAHQgKAKgSAAQgJAAgHgGgAgIgjQgDAFgBAKIAUgBQgEgUgFABQgEgBgDAGg");
	this.shape_8.setTransform(-41.9,1.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkA/IAAABQgKgHAAgDQAAgDADgFIAAheQgDgFAAgDQAAgLAPAAIAIABIAGABIAJgCQANgCAKAAQALAAAHADQAHADADAHQACAFAAAFQAAAJgFAHQgFAIgKAIQAJABAGAEQAFAFACAIIAAAHQAAAWgTATQgTASgWAAQgMAAgLgHgAgCAKQgIADgEADIAAAeQAEgBAEgCIAKgJQAHgGADgGQAEgGAAgGQAAgFgFAAQgGAAgJAFgAgCgsQgKADgCACIAAAaQAOgJAIgJQAHgIAAgGQAAgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgFAAgIADg");
	this.shape_9.setTransform(-52,1.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSBaQgKgHgIgNQgLgYAAgvQAAgTACgQQADgQAFgNQAMgeAXgBQAIAAAIAEQAHAEAFAIQAKAOADATIAFAOQAAAMgOAAQgJAAgHgEQgIgEAAgFIACgKQgBgLgCgFQgDgFgDAAQgHAAgDAXQgEAeAAARQABAhADALQACAKACAFQADAFAEAAQAEgBAFgNQAEgLABgIQgBgHAGgEQAFgEAHAAQAHAAAFADQAGAEgBAFQAAADgCAEIgDAGQgFARgKAOQgFAJgHAFQgHAFgGAAIgCABQgKAAgJgHg");
	this.shape_10.setTransform(-62.5,-1.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.8,-14.5,139.6,29);


(lib.Анимация8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_03();
	this.instance.parent = this;
	this.instance.setTransform(-74.5,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-65,149,130);


(lib.Анимация7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_03();
	this.instance.parent = this;
	this.instance.setTransform(-74.5,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.5,-65,149,130);


(lib.Анимация6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_06();
	this.instance.parent = this;
	this.instance.setTransform(-72.5,-67);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.5,-67,145,134);


(lib.Анимация5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_06();
	this.instance.parent = this;
	this.instance.setTransform(-72.5,-67);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-72.5,-67,145,134);


(lib.Анимация4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_11();
	this.instance.parent = this;
	this.instance.setTransform(-69,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69,-65,138,130);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.sssi_11();
	this.instance.parent = this;
	this.instance.setTransform(-69,-65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69,-65,138,130);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.girlq1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.Анимация1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.girlq1();
	this.instance.parent = this;
	this.instance.setTransform(-120,-200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ22();
	this.instance.parent = this;
	this.instance.setTransform(148.8,96.8,1.355,1.355,0,0,0,59.1,11.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.say2();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(0,0,295,183), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(73.2,71.2,0.659,0.659,0,0,0,142.1,108);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ20, new cjs.Rectangle(0,0,187.1,142.4), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ17();
	this.instance.parent = this;
	this.instance.setTransform(46.5,60,1,1,0,0,0,46.5,60);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(0,0,93,120), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(53.2,80.2,1,1,0,0,0,53.2,80.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},59).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,130.4,124.6);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 11
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(130.2,94.2,1,1,0,0,0,65.2,62.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Символ 12
	this.instance_1 = new lib.Символ12();
	this.instance_1.parent = this;
	this.instance_1.setTransform(118,113.6,1,1,0,0,0,118,113.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Символ 13
	this.instance_2 = new lib.Символ13();
	this.instance_2.parent = this;
	this.instance_2.setTransform(118,113.6,1,1,0,0,0,118,113.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(0,0,236,227.3), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.parent = this;
	this.instance.setTransform(100.3,12.3,1,1,0,0,0,100.3,12.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(0,0,200.6,24.8), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ7();
	this.instance.parent = this;
	this.instance.setTransform(67,12,1,1,0,0,0,67,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(0,0,134.1,24.1), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Анимация9("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-148.2,-93.4);
	this.instance._off = true;

	this.instance_1 = new lib.Анимация10("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(51.8,-93.4);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(12).to({_off:false},0).to({_off:true,x:51.8},4,cjs.Ease.get(1)).wait(64));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(12).to({_off:false},4,cjs.Ease.get(1)).to({x:80.8},58).to({x:290.8},5,cjs.Ease.get(1)).wait(1));

	// здоровый перекус!
	this.instance_2 = new lib.Анимация11("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(311.5,-61.4);
	this.instance_2._off = true;

	this.instance_3 = new lib.Анимация12("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(91.5,-61.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(12).to({_off:false},0).to({_off:true,x:91.5},4,cjs.Ease.get(1)).wait(64));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({_off:false},4,cjs.Ease.get(1)).to({x:79.5},58).to({x:-160.5},5,cjs.Ease.get(1)).wait(1));

	// sssi_11.png
	this.instance_4 = new lib.Анимация3("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(74,-326);

	this.instance_5 = new lib.Анимация4("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(76,55);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({startPosition:0},8).to({_off:true,x:76,y:55},4,cjs.Ease.get(-1)).wait(68));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(8).to({_off:false},4,cjs.Ease.get(-1)).wait(2).to({startPosition:0},0).wait(2).to({startPosition:0},0).wait(58).to({startPosition:0},0).wait(5).to({startPosition:0},0).wait(1));

	// sssi_06.png
	this.instance_6 = new lib.Анимация5("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(18.5,-287);

	this.instance_7 = new lib.Анимация6("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(20.5,113);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({startPosition:0},4).to({_off:true,x:20.5,y:113},4,cjs.Ease.get(-1)).wait(72));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(4).to({_off:false},4,cjs.Ease.get(-1)).wait(6).to({startPosition:0},0).wait(2).to({startPosition:0},0).wait(58).to({startPosition:0},0).wait(5).to({startPosition:0},0).wait(1));

	// sssi_03.png
	this.instance_8 = new lib.Анимация7("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(132.5,-289);

	this.instance_9 = new lib.Анимация8("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(134.5,111);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true,x:134.5,y:111},4,cjs.Ease.get(-1)).wait(76));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:false},4,cjs.Ease.get(-1)).wait(10).to({startPosition:0},0).wait(2).to({startPosition:0},0).wait(58).to({startPosition:0},0).wait(5).to({startPosition:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54,-391,261,171);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// treugolnik_zelen.png
	this.instance = new lib.Символ18();
	this.instance.parent = this;
	this.instance.setTransform(18,-59.3,1,1,0,0,0,52,58);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:6.2,y:-84.5},5).to({x:18,y:-59.3},5).wait(40));

	// treugolnik_slivki.png
	this.instance_1 = new lib.Символ19();
	this.instance_1.parent = this;
	this.instance_1.setTransform(94.5,-61.7,1,1,0,0,0,46.5,60);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(5).to({x:97.7,y:-92.7},5).to({x:94.5,y:-61.7},5).wait(35));

	// treugolnik_grib.png
	this.instance_2 = new lib.Символ16();
	this.instance_2.parent = this;
	this.instance_2.setTransform(144.5,-32.5,1,1,0,0,0,74.5,75.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({x:161.7,y:-59.8},5).to({x:144.5,y:-32.5},5).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34,-121.7,253,164.5);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 1
	this.instance = new lib.Символ20();
	this.instance.parent = this;
	this.instance.setTransform(378.6,201.1,0.381,0.381,-125.2,0,0,127.5,127.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({scaleX:1,scaleY:1,rotation:0,x:378.5,alpha:1},5).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:1.03,scaleY:1.03},5).to({scaleX:1,scaleY:1},5).wait(1));

	// girlq1.jpg
	this.instance_1 = new lib.Анимация1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(386,200);

	this.instance_2 = new lib.Анимация2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(386,200);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[{t:this.instance_1}]},9).to({state:[{t:this.instance_2}]},5).to({state:[{t:this.instance_2}]},65).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({startPosition:0},9).to({_off:true},5).wait(66));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(266,0,240,400);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 7
	this.instance = new lib.Символ9();
	this.instance.parent = this;
	this.instance.setTransform(-90,15.2,1,1,0,0,0,67,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:110},9).to({x:123},60).to({x:323},10,cjs.Ease.get(1)).wait(1));

	// Символ 8
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(363.1,44.9,1,1,0,0,0,100.3,12.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:127.1},9).to({x:121.1},60).to({x:-118.9},10,cjs.Ease.get(1)).wait(1));

	// cheese_clock1.png
	this.instance_2 = new lib.Символ14();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-122,173.6,1,1,0,0,0,118,113.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:-15.3},4,cjs.Ease.get(-1)).to({x:118},5,cjs.Ease.get(1)).wait(60).to({x:378},10,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-240,3.2,703.4,284.1);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(94.6,58.7,0.641,0.641,0,0,0,147.5,91.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(0,0,189.1,117.3), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// say2.png
	this.instance = new lib.Символ23();
	this.instance.parent = this;
	this.instance.setTransform(124.5,223.6,0.471,0.471,99.5,0,0,138.7,8.6);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({regX:138.6,regY:8.7,scaleX:1,scaleY:1,rotation:0,x:124.6,alpha:1},5).to({scaleX:0.94,scaleY:0.94},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:0.94,scaleY:0.94},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:0.94,scaleY:0.94},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:0.94,scaleY:0.94},5).to({scaleX:1,scaleY:1},5).wait(1).to({scaleX:0.94,scaleY:0.94},5).to({scaleX:1,scaleY:1},6).wait(1));

	// Слой 1
	this.instance_1 = new lib.girl2();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(70));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,240,400);


// stage content:
(lib.index = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		setTimeout(function() {
		        _this.ban.gotoAndStop(230);
		   }, 30000);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(320));

	// Слой 1
	this.instance = new lib.hohlogo();
	this.instance.parent = this;
	this.instance.setTransform(65,5,0.47,0.47);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(320));

	// Слой 8
	this.instance_1 = new lib.Символ2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(119,247.6,1,1,0,0,0,118,143.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(79).to({_off:true},1).wait(240));

	// treugolnik_zelen.png
	this.instance_2 = new lib.Символ4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(152.8,553.1,0.647,0.647,-5.7,0,0,126.8,84.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(74).to({_off:false},0).to({y:463.1},5).wait(155).to({y:543.1},5).to({_off:true},1).wait(80));

	// say1.png
	this.instance_3 = new lib.Символ3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-264,198,1,1,0,0,0,253,200);
	this.instance_3.alpha = 0.148;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(74).to({_off:false},0).to({x:-12,y:200,alpha:1},5).wait(78).to({x:-10,alpha:0},2).to({_off:true},1).wait(160));

	// Слой 16
	this.instance_4 = new lib.Символ5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(397.5,198,1,1,0,0,0,147.5,200);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(159).to({_off:false},0).to({x:148.5,y:201},2).wait(68).to({x:-111.5,alpha:0},10).to({_off:true},1).wait(80));

	// Слой 17
	this.instance_5 = new lib.Символ6();
	this.instance_5.parent = this;
	this.instance_5.setTransform(115.5,292,1,1,0,0,0,74.5,67);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(239).to({_off:false},0).wait(81));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-119,205,703.4,386.3);
// library properties:
lib.properties = {
	width: 240,
	height: 400,
	fps: 24,
	color: "#0054A5",
	opacity: 1.00,
	manifest: [
		{src:"images/cheese_clock.png?1479763620680", id:"cheese_clock"},
		{src:"images/cheese_clock1.png?1479763620680", id:"cheese_clock1"},
		{src:"images/cheese_clock2.png?1479763620680", id:"cheese_clock2"},
		{src:"images/girl2.jpg?1479763620680", id:"girl2"},
		{src:"images/girlq1.jpg?1479763620680", id:"girlq1"},
		{src:"images/hohlogo.png?1479763620680", id:"hohlogo"},
		{src:"images/say1.png?1479763620680", id:"say1"},
		{src:"images/say2.png?1479763620680", id:"say2"},
		{src:"images/sssi_03.png?1479763620680", id:"sssi_03"},
		{src:"images/sssi_06.png?1479763620680", id:"sssi_06"},
		{src:"images/sssi_11.png?1479763620680", id:"sssi_11"},
		{src:"images/treugolnik_grib.png?1479763620680", id:"treugolnik_grib"},
		{src:"images/treugolnik_slivki.png?1479763620680", id:"treugolnik_slivki"},
		{src:"images/treugolnik_zelen.png?1479763620680", id:"treugolnik_zelen"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;