(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1140,
	height: 100,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/back.jpg?1477404243047", id:"back"},
		{src:"images/molecule.png?1477404243047", id:"molecule"},
		{src:"images/oim.png?1477404243047", id:"oim"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.back = function() {
	this.initialize(img.back);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1094,117);


(lib.molecule = function() {
	this.initialize(img.molecule);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,122,122);


(lib.oim = function() {
	this.initialize(img.oim);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,174,174);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.molecule();
	this.instance.parent = this;
	this.instance.setTransform(568,100.7,0.418,0.418,180);

	this.instance_1 = new lib.molecule();
	this.instance_1.parent = this;
	this.instance_1.setTransform(335,37.1,0.598,0.598,69);

	this.instance_2 = new lib.molecule();
	this.instance_2.parent = this;
	this.instance_2.setTransform(365.9,44.2,0.418,0.418,150);

	this.instance_3 = new lib.molecule();
	this.instance_3.parent = this;
	this.instance_3.setTransform(273,58.7,0.418,0.418,180);

	this.instance_4 = new lib.molecule();
	this.instance_4.parent = this;
	this.instance_4.setTransform(475.1,42.5,0.598,0.598,114);

	this.instance_5 = new lib.molecule();
	this.instance_5.parent = this;
	this.instance_5.setTransform(124,23.7,0.598,0.598);

	this.instance_6 = new lib.molecule();
	this.instance_6.parent = this;
	this.instance_6.setTransform(115,48.7,0.418,0.418,90);

	this.instance_7 = new lib.molecule();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,27.7,0.598,0.598);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,568,131.3);


(lib.Символ38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVBTQgGABgFgCQgGgCgEgCQgRgMAAgUIAAhaQAAgiAfgEIAHAAIBRAAIAAAXIhQAAQgMAAgDANIAAADIAAAUIA3AAQASABALAJQAFAFADAHQADAFAAAIIAAAiQAAAIgDAIQgEAHgHAGQgGAEgFACQgGACgFAAgAgVAAQgOACAAALIAAAfQAAAGAFAFQAGAEAGAAIAoAAIAFgBQAGgCACgJIABgBIAAggQAAgHgDgDQgDgCgIgCIgBAAIgpAAIgBAAg");
	this.shape.setTransform(453.1,11.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AABBUIAAiOIgaAAIAAgZIAwAAIAAABIADAAIAACmg");
	this.shape_1.setTransform(436.6,11.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIBTQgQAAgMgFQgLgGgGgMIgEgMQgCgFAAgGIAAhIQAAgLADgJQADgJAGgGQAIgIAKgCQAHgCAOAAIARAAQAOAAAHACQAKACAIAIQAGAGADAJQADAJAAALIAABIQAAAWgMAMQgIAIgKADQgHACgOgBgAgTg6QgKABgDAGQgDAEAAALIAABJQAAALADAEQADAGAKAAIAIABIAYAAIAIgBQAJAAADgGQACgEAAgLIAAhJQAAgMgEgFQgEgEgLgBIgDgBIgYAAg");
	this.shape_2.setTransform(422.9,11.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1BTIAAg0QABgKADgJQAEgHAGgFQALgIAMABIAhAAQADgBAEgCQADgCABgEIABgEIAAgaQgBgKgJgCIgCgBIhGAAIAAgXIBEAAQAWAAAJAOQAIAKgBAKIAAAdQAAAJgDAHQgFAGgHAFQgFAEgGABQgFACgFAAIgeAAQgHAAgEAEQgDADAAAHIAAAeIBQAAIAAAYg");
	this.shape_3.setTransform(407.8,11.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AguA+IAAgUIA/AAQADgBACgCQADgCAAgIIAAgKQAAgFgDgEQgDgDgGAAIgaAAQgVAAgIgLQgDgGAAgHIAAgQQAAgHACgFQABgFAEgEQAHgIAOAAIBAAAIAAAWIg+AAQgJgBAAAKIAAAJQAAAEADADQADADAFAAIAdAAIAGABQALACAHAIQADACACAEQABAFAAAGIAAATQAAAHgCAFQgDAFgGAFQgJAGgGgBg");
	this.shape_4.setTransform(387.8,13.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTBTQgGAAgHgCQgTgJAAgVIAAg8QAAgPAKgJQAEgDAGgDQAHgCAIAAIAuAAIAAgpIAWAAIAACCQAAANgJALQgJAMgOgBgAgagQQgEAEAAAGIAAA3IABACQABAFACAEQADADAFAAIAjAAQAFAAADgDQAFgFAAgIIAAg1QAAgNgLAAIgjAAQgHAAgDADg");
	this.shape_5.setTransform(375.4,11.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA+IAAhaIAAgIQACgMAGgGQAGgFAKgCIAGgBIALAAIAAAWIgKAAQgLAAAAANIAABZg");
	this.shape_6.setTransform(366.3,13.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTA+QgJAAgJgGQgJgHgDgIQgCgGAAgHIAAgOQAAgPAHgLQAFgFAGgDQAGgDAIgBIAyAAIAAgIQAAgDgDgDQgCgCgDAAIhKAAIAAgWIBJAAQAMAAAHAHQAIAFADAMIAAAFIAABAQAAAIgFAHQgFAIgGAFQgHADgIAAgAgaAAQgEADAAAFIAAAVQAAAIAGADQADACAIAAIAbAAQARAAAAgNIAAgVQAAgGgEgCQgDgCgIAAIgfAAQgIAAgDACg");
	this.shape_7.setTransform(356,13.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdA9QgFgDgCgHIgWhXIgVBXQgDAKgIADIgHABQgOAAgDgMIgbhyIAUAAIAZBiIAYhaQABgFAEgDQAEgDAFAAQAEAAAGADQAEADABAFIAZBaIAYhiIAVAAIgcByQgCAGgEADQgEADgHAAQgHAAgEgEg");
	this.shape_8.setTransform(340.6,13.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAxBUIgNgjIhHAAIgNAjIgaAAIA4iWQADgIAFgFQAFgFAFAAQAGAAAFAFQAFAFADAIIA4CWgAAbAZIgbhLIgaBLIA1AAg");
	this.shape_9.setTransform(324.6,11.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAgA+IggguIgfAuIgZAAIAtg+Igrg+IAaAAIAcArIAcgrIAaAAIgqA+IAtA+g");
	this.shape_10.setTransform(304.7,13.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgRA+QgHAAgGgCQgGgCgFgFQgKgJAAgOIAAg3QAAglAnAAIAdAAQAIAAAGACQAHADADAEQAFAEADAGQABAGAAAIIAAAOIhQAlIAAAFQACAJACACQADADAIABIBDAAIAAAUgAgaglQgEAFAAAHIAAAZIA8gbIAAgCQAAgLgNAAIggAAQgIAAgDADg");
	this.shape_11.setTransform(292.5,13.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTBTQgGAAgHgCQgTgJAAgVIAAg8QAAgPAKgJQAEgDAGgDQAHgCAIAAIAuAAIAAgpIAWAAIAACCQAAANgJALQgJAMgOgBgAgagQQgEAEAAAGIAAA3IABACQABAFACAEQADADAFAAIAjAAQAFAAADgDQAFgFAAgIIAAg1QAAgNgLAAIgjAAQgHAAgDADg");
	this.shape_12.setTransform(279.1,11.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAeA+IAAheQgBgIgNAAIgfAAQgIAAgDADQgEADAAAHIAABZIgVAAIAAhbQAAggAkgBIAfAAQASABAJAHQAJAJAAAQIAABbg");
	this.shape_13.setTransform(265.8,13.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgJBTIAAh8IATAAIAAB8gAgJg6QgEgEAAgGQAAgGAEgFQAFgDAEAAQAFgBAFAFQAEAFAAAFQAAAHgEADQgEAFgGAAQgEAAgFgFg");
	this.shape_14.setTransform(256.6,11.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTBTQgGAAgHgCQgTgJAAgVIAAg8QAAgPAKgJQAEgDAGgDQAHgCAIAAIAuAAIAAgpIAWAAIAACCQAAANgJALQgJAMgOgBgAgagQQgEAEAAAGIAAA3IABACQABAFACAEQADADAFAAIAjAAQAFAAADgDQAFgFAAgIIAAg1QAAgNgLAAIgjAAQgHAAgDADg");
	this.shape_15.setTransform(247.5,11.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAxBUIgNgjIhHAAIgNAjIgaAAIA4iWQADgIAFgFQAFgFAFAAQAGAAAFAFQAFAFADAIIA4CWgAAbAZIgbhLIgaBLIA1AAg");
	this.shape_16.setTransform(233.6,11.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgzBTIAAgVIBHAAQAFgBADgDQACgDAAgHIAAgGIgyAAQgNAAgJgJQgEgEgCgFQgDgHAAgGIAAhdIAVAAIAABYQAAAHAEAEQAEAEAHAAIAfAAQAHAAAEgEQADgDAAgGIAAhaIAWAAIAACBQAAAJgDAGQgCAGgEAFQgJAKgQAAg");
	this.shape_17.setTransform(212.9,15.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgcA+IAAhbIABgIQAHgYAYAAIAZAAIAAAVIgbAAQgDABgDAEQgDADAAAGIAABYg");
	this.shape_18.setTransform(202.7,13.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAeA+IAAgyIg8AAIAAAyIgVAAIAAh8IAVAAIAAA2IA8AAIAAg2IAWAAIAAB8g");
	this.shape_19.setTransform(191.7,13.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgPA+QgkABAAghIAAhcIAVAAIAABfQACAIANAAIAiAAQAGgBADgDQACgDAAgHIAAhZIAWAAIAAB8g");
	this.shape_20.setTransform(178.4,13.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAzA+IAAhaQAAgMgNAAIgSAAQgEABgCADQgDAEAAAFIAABZIgSAAIAAhaIgBgBQgCgLgLAAIgQAAIgDAAQgFAAgCADQgCACgBAFIAABcIgVAAIAAhbQAAgQAIgJQAHgHAOgBIATAAIAGABQAGABAFADQAFACABAEQACgEAFgCQAFgDAHgBIAFgBIATAAQAOABAIAHQAHAJAAAQIAABbg");
	this.shape_21.setTransform(163.1,13.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgPBSQgkAAAAghIAAhbIAVAAIAABeQACAIANAAIAiAAQAGAAADgEQACgDAAgGIAAhZIAWAAIAAB8gAgKg2QgGgCgFgDQgKgIAAgNIARgBQABAPANAAQAPAAABgPIARABQAAAGgDAGQgCAFgFAEQgKAHgNAAQgFAAgFgCg");
	this.shape_22.setTransform(147.8,11.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgQA+QgIAAgGgCQgHgCgEgFQgKgJAAgOIAAg3QAAglAnAAIAeAAQAHAAAGACQAGADAEAEQAFAEACAGQACAGAAAIIAAAOIhQAlIAAAFQACAJACACQADADAIABIBDAAIAAAUgAgaglQgEAFAAAHIAAAZIA7gbIAAgCQAAgLgMAAIggAAQgIAAgDADg");
	this.shape_23.setTransform(134.8,13.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag7BTIAAilIBHAAQAwAAAAAnIAAAZQAAAKgDAIQgDAFgGAGQgHAFgIADQgIADgKAAIgxAAIAAA9gAgiAAIAxAAQAJAAAFgEQAFgDABgJIAAgZIAAgDQgBgHgEgDQgDgDgIgBIgCgBIgzAAg");
	this.shape_24.setTransform(121.5,11.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTA+QgIAAgHgCQgHgCgDgEQgHgJAAgNIAAhAQgBgNAIgHQAGgIAPgBIACgBIAoAAIAFABQAdAEAAAZIAABAQAAARgRAKQgIADgJAAgAgegaIAAAzQAAARAPAAIAgAAQAHAAAEgFQAEgDgBgJIAAgzQABgHgEgEQgEgDgHAAIggAAQgPAAAAAOg");
	this.shape_25.setTransform(100.5,13.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAeA+IAAgyIg8AAIAAAyIgVAAIAAh8IAVAAIAAA2IA8AAIAAg2IAWAAIAAB8g");
	this.shape_26.setTransform(87.2,13.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgFA+QgKABgIgFQgJgEgEgIQgEgHAAgIIAAg9QAAgHACgHQADgFAFgFQAJgIAQAAIAuAAIAAAWIguAAQgOAAAAANIAAA1QAAAHAEAEQAEAEAGABIAuAAIAAAUg");
	this.shape_27.setTransform(75.5,13.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgTA+QgJAAgJgGQgJgHgDgIQgCgGAAgHIAAgOQAAgPAHgLQAFgFAGgDQAGgDAIgBIAyAAIAAgIQAAgDgDgDQgCgCgDAAIhKAAIAAgWIBJAAQAMAAAHAHQAIAFADAMIAAAFIAABAQAAAIgFAHQgFAIgGAFQgHADgIAAgAgaAAQgEADAAAFIAAAVQAAAIAGADQADACAIAAIAbAAQARAAAAgNIAAgVQAAgGgEgCQgDgCgIAAIgfAAQgIAAgDACg");
	this.shape_28.setTransform(63.2,13.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAfA+IAAheQgCgIgNAAIgRAAQgIAAgDADQgEADAAAHIAAA5QABAhgkgBIAAgVQAIAAAEgDQACgCAAgJIAAg4QAAggAkgBIARAAQASABAJAHQAJAJAAAQIAABbg");
	this.shape_29.setTransform(49.8,13.7);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgcA+IAAhbIABgIQAHgYAYAAIAZAAIAAAVIgbAAQgDABgDAEQgDADAAAGIAABYg");
	this.shape_30.setTransform(39.7,13.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgTA+QgJAAgGgCQgHgCgDgEQgIgJAAgNIAAhAQABgNAGgHQAIgIANgBIAEgBIAnAAIAFABQAdAEgBAZIAABAQAAARgRAKQgGADgKAAgAgegaIAAAzQAAARAPAAIAgAAQAHAAAEgFQADgDABgJIAAgzQgBgHgDgEQgEgDgHAAIggAAQgPAAAAAOg");
	this.shape_31.setTransform(28.6,13.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgFA+QgKABgIgFQgJgEgEgIQgEgHAAgIIAAg9QAAgHACgHQADgFAFgFQAJgIAQAAIAuAAIAAAWIguAAQgOAAAAANIAAA1QAAAHAEAEQAEAEAGABIAuAAIAAAUg");
	this.shape_32.setTransform(16.8,13.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgJAlIAJgkIgaAbIgKgSIAkgKIgkgIIAKgSIAaAaIgJgkIATAAIgJAkIAagaIAKASIgkAIIAkAKIgKASIgbgbIAKAkg");
	this.shape_33.setTransform(6.6,7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,462.8,28);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAlIAJgkIgaAbIgKgSIAkgKIgkgIIAKgSIAaAaIgJgkIATAAIgJAkIAagaIAKASIgkAIIAkAKIgKASIgbgbIAKAkg");
	this.shape.setTransform(315.7,8.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AACBiIAAimIgfAAIAAgdIA5AAIACAAIAADDg");
	this.shape_1.setTransform(304.4,13.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcBQIg7iMIAACdIgcAAIAAinQAAgdAXAAIAJABQALACAHAQIA8CPIAAihIAaAAIAACsQAAAKgGAHQgHAIgIABIgDAAQgQAAgJgUgAAmAQIAAgSIBPAAIAAASgABNgMQgYAAgKgTQgEgIAAgKIAAgMQAAgJACgGQACgHAFgFQAGgGAIgCQAGgCAJAAIABAAQAJAAAGACQAIACAHAGQAIAKABARIAAAMQgBASgIAJQgHAGgIACQgFACgKAAgAA8hJQgCADAAAIIAAAOQAAAHACAEQADAEAGABIAFABIAIAAIAEgBQAHgBACgEQACgEAAgHIAAgOQAAgJgDgDQgEgEgGAAIgCAAIgIAAIgFAAQgGABgDAEg");
	this.shape_2.setTransform(284.6,13.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA8BJIAAhqQAAgOgPAAIgWAAQgFABgCAEQgDAEAAAGIAABpIgWAAIAAhqIAAgCQgDgMgNAAIgTAAIgDAAQgGAAgCADQgDADAAAGIAABsIgZAAIAAhsQAAgTAIgJQAJgJARAAIAWAAIAGAAQAIABAGADQAFADACAGQADgGAFgDQAGgDAIgBIAGAAIAWAAQARAAAJAJQAIAJAAATIAABsg");
	this.shape_3.setTransform(253.1,16);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYBJIAAhqIABgJQACgOAGgHQAHgHAMgCIAHAAIAOAAIAAAYIgMAAQgNAAAAAPIAABqg");
	this.shape_4.setTransform(240,16);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVBJQgPAAgJgGQgJgHgEgOQgDgIABgBIAAhLQAAgPAIgJQAIgIARgCIADAAIAvAAIAFAAQAiAFAAAdIAABLQAAAUgUAMQgIAEgLAAgAgjgeIAAA7QAAAUARAAIAmAAQAJAAAEgFQAEgFAAgJIAAg8QAAgJgEgEQgEgFgJAAIgmAAQgRAAAAASg");
	this.shape_5.setTransform(227.9,16);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYBiIAAidIACgJQAHgdAeAAIAKAAIAAAZIgOAAQgFABgEAFQgCAEAAAHIAAAHIAZAAIAAAZIgZAAIAAB5g");
	this.shape_6.setTransform(217.4,13.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXBiIAAjDIAXAAIAAAxIAYAAIAAAZIgYAAIAAB5g");
	this.shape_7.setTransform(210.9,13.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWBJQgLAAgKgHQgLgIgEgKQgCgGAAgIIAAgSQAAgSAJgMQAFgHAHgEQAHgDAKAAIA6AAIAAgKQAAgEgCgDQgDgDgEAAIhXAAIAAgYIBVAAQAPAAAJAGQAIAHAEAOIAAAHIAABKQAAAKgFAIQgGAKgIAFQgIAEgJAAgAgfAAQgEADAAAHIAAAYQAAAJAGADQAEADAKAAIAfAAQAUAAAAgPIAAgYQAAgHgEgDQgEgDgJAAIglAAQgJABgEACg");
	this.shape_8.setTransform(198.9,16);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLBiIAAjDIAXAAIAADDg");
	this.shape_9.setTransform(188.1,13.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag8BhIAAicQAAgJADgHQACgHAFgFQAKgJATAAIAsAAQAIAAAGABQAGACAEADQAHAFAEAIQADAHAAAJIAABFQAAAJgCAGQgDAHgEAGQgMANgQAAIg8AAIAAAwgAgfhEQgFAEAAAHIAABAIAAADQABAIAEADQAFAEAEAAIAtAAIABAAQAKgDADgJIAAgDIAAhGQgBgGgCgCQgCgDgGgBIgsAAQgJAAgEAEg");
	this.shape_10.setTransform(177.3,18.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGBJQgMAAgKgFQgKgFgFgJQgEgIAAgKIAAhHQAAgJACgIQADgHAGgEQALgJASAAIA3AAIAAAYIg3AAQgPAAAAAQIAAA+QgBAIAFAFQAEAGAJAAIA2AAIAAAYg");
	this.shape_11.setTransform(155.6,16);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLBiIAAiSIAXAAIAACSgAgLhEQgEgEAAgIQAAgHAEgFQAFgFAGAAQAGAAAFAFQAFAGAAAHQAAAHgFAFQgEAEgHAAQgGAAgFgFg");
	this.shape_12.setTransform(146,13.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYBiIAAjDIAYAAIAAAxIAZAAIAAAZIgZAAIAAB5g");
	this.shape_13.setTransform(140.9,13.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgWBJQgLAAgKgHQgLgIgEgKQgCgGAAgIIAAgSQAAgSAJgMQAFgHAHgEQAHgDAKAAIA6AAIAAgKQAAgEgCgDQgDgDgEAAIhXAAIAAgYIBVAAQAPAAAJAGQAIAHAEAOIAAAHIAABKQAAAKgFAIQgGAKgIAFQgIAEgJAAgAgfAAQgEADAAAHIAAAYQAAAJAGADQAEADAKAAIAfAAQAUAAAAgPIAAgYQAAgHgEgDQgEgDgJAAIglAAQgJABgEACg");
	this.shape_14.setTransform(128.8,16);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AA8BJIAAhqQAAgOgPAAIgWAAQgFABgCAEQgDAEAAAGIAABpIgWAAIAAhqIAAgCQgDgMgNAAIgTAAIgDAAQgGAAgCADQgDADAAAGIAABsIgZAAIAAhsQAAgTAIgJQAJgJARAAIAWAAIAGAAQAIABAGADQAFADACAGQADgGAFgDQAGgDAIgBIAGAAIAWAAQARAAAJAJQAIAJAAATIAABsg");
	this.shape_15.setTransform(110.8,16);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA8BJIAAhqQAAgOgPAAIgWAAQgFABgCAEQgDAEAAAGIAABpIgWAAIAAhqIAAgCQgDgMgNAAIgTAAIgDAAQgGAAgCADQgDADAAAGIAABsIgZAAIAAhsQAAgTAIgJQAJgJARAAIAWAAIAGAAQAIABAGADQAFADACAGQADgGAFgDQAGgDAIgBIAGAAIAWAAQARAAAJAJQAIAJAAATIAABsg");
	this.shape_16.setTransform(90.5,16);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgWBJQgLAAgKgHQgLgIgEgKQgCgGAAgIIAAgSQAAgSAJgMQAFgHAHgEQAHgDAKAAIA6AAIAAgKQAAgEgCgDQgDgDgEAAIhXAAIAAgYIBVAAQAPAAAJAGQAIAHAEAOIAAAHIAABKQAAAKgFAIQgGAKgIAFQgIAEgJAAgAgfAAQgEADAAAHIAAAYQAAAJAGADQAEADAKAAIAfAAQAUAAAAgPIAAgYQAAgHgEgDQgEgDgJAAIglAAQgJABgEACg");
	this.shape_17.setTransform(72.5,16);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYBJIAAhqIABgJQACgOAGgHQAHgHAMgCIAHAAIAOAAIAAAYIgMAAQgNAAAAAPIAABqg");
	this.shape_18.setTransform(61.7,16);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag8BhIAAgYIBOAAQATAAAAgSIAAgGIg6AAQgQAAgLgMQgFgFgDgIQgCgHgBgIIAAhEQABgaAVgJQAIgCAFAAIAyAAQAeAAAEAdIABAGIAAB6QAAASgNAKQgFAEgHACQgIACgJAAgAgfhCQgEAEABAHIAABAQABAIADAEQAFAEAGAAIApAAQAHAAADgEQAEgEAAgHIAAhBQAAgRgOAAIgrAAQgGACgEAEg");
	this.shape_19.setTransform(49.7,18.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgVBJQgPAAgJgGQgJgHgEgOQgDgIABgBIAAhLQAAgPAIgJQAIgIARgCIADAAIAvAAIAFAAQAiAFAAAdIAABLQAAAUgUAMQgIAEgLAAgAgjgeIAAA7QAAAUARAAIAmAAQAJAAAEgFQAEgFAAgJIAAg8QAAgJgEgEQgEgFgJAAIgmAAQgRAAAAASg");
	this.shape_20.setTransform(33.8,16);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgYBJIAAhqIABgJQACgOAGgHQAHgHAMgCIAHAAIAOAAIAAAYIgMAAQgNAAAAAPIAABqg");
	this.shape_21.setTransform(23.1,16);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhFBiIAAjDIBTAAQA4AAAAAvIAAAcQAAAMgDAJQgEAHgHAHQgHAGgKADQgJAEgNAAIg5AAIAABIgAgogBIA5AAQAMAAAFgDQAGgEACgMIAAgcIgBgEQgBgIgFgFQgDgCgJgBIgDAAIg8AAg");
	this.shape_22.setTransform(11.1,13.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,322.5,32.8);


(lib.Символ36 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBYQg2AAgCgoQgBgeAQgSQAPgSAagBQAOgCAVACQALAAAFgDQAFgEACgLQADgNgEgGQgEgGgOgBIgtgBQgPAAgBAAIABgLQACgJAFgCIAIgBIA0AAQATABALANQALAOgCASQgGAogKAsQgKArgtACgAgiAMQgHAFgCAJIgEASQgBAJAEAGQAEAGAJAAIAoAAQAIAAAHgGQAGgGADgIIAHgnIg6AAQgJgBgHAHg");
	this.shape.setTransform(114,19.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdBYIAdicQABgKAEgEQAFgFAJAAIALAAIgeCjQgCAMgNAAg");
	this.shape_1.setTransform(102.9,18.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsB7QgVAAgMgOQgMgNAEgUIAPhPQAEgWARgOQARgNAYAAIAlAAQASAAADgRIAHgkQADgRAOAAIANAAIglDCQgEAYgRAOQgRANgZAAgAgigVQgGAGgCAKIgQBQQgCAKAGAHQAFAGALAAIAfAAQAZAAAFgZIAIgpIgBAAIAJgsQABgHgDgEQgDgEgGAAIgsAAQgKAAgIAGg");
	this.shape_2.setTransform(91.9,15.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggBYQgXAAgMgNQgLgOADgUIAPhPQAEgVAQgNQAQgOAXgBQAQgBAYACQASABALAMQAKAMgCARIgEAWQgFAUgQAKQgRANgVAAIg5AAIgEATQgBALAFAGQAGAGALAAIArAAQAKAAAEABQAFACADAGQADAGgBAKgAgIg+QgIAAgHAGQgGAGgCAIIgIAoIA7AAQAIAAAHgGQAHgGADgJIADgSQABgJgEgGQgEgGgJAAg");
	this.shape_3.setTransform(73.7,18.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("ABMByQgLAAACgTIAZiTQAEgOAAgHQAAgMgMgCQgygIgGAfQgGAXgMBJIgKA+IgEAMQgEAHgHAAQgLgCAAgIIACgPIAYiIIAAgJQAEgWgEgEQgCgFgWAAQgWABgIAHQgJAGgEAWIgaCTQgEATgMgBQgKgCgBgHIACgOIANhIQAIgpAEgdQALhNBYAVQAHACAUgBIAdgDQARgBAMABQAOABAJANQAJANgCAPQgRBggOBJQgDANgKAAIgBAAg");
	this.shape_4.setTransform(52.3,16.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgdBYIAdicQACgTAQAAIAMAAIgeCjQgCAMgNAAg");
	this.shape_5.setTransform(162.7,18.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag8BYIAZh+QADgUARgPQAPgOAUAAIApAAQgBAKgGAIQgGAHgIAAIgVAAQgWAAgFAYIgWBwQgBAJgEACQgDADgKAAg");
	this.shape_6.setTransform(212.6,18.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AApBYQgHAAgDgGQgDgGABgJIAUhkQAEgQgGgGQgGgHgRAAIgVAAQgYAAgGAaIgVBtQgDAPgNAAIgOAAIAYh+QAEgVAQgNQAQgOAVgBIAkAAQAVACALANQALAMgEAUIgZCAg");
	this.shape_7.setTransform(148.6,18.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhLBxIACgMQADgNAQAAIA2AAQAZAAAEgYIAGgeQACgKgFgGQgGgGgKAAIgfAAQgYAAgMgMQgLgNADgWIAGgeQAEgVARgNQAQgNAVgBIBHAAIgDANQgCAMgPABIg0AAQgZAAgFAZIgGAcQgEAWAZABIAdAAQAYAAAMAMQAMANgEAWIgHAhQgDATgRANQgRAMgSAAg");
	this.shape_8.setTransform(131.1,16.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggBYQgXAAgMgNQgLgOADgUIAPhPQAEgVAQgNQAQgOAXgBQAWgBATACQASABAKAMQAKAMgCARQAAAKgEAMQgFAUgQAKQgRANgUAAIg6AAIgDAUQgDAWAXAAIArAAQAKAAAEABQAFACADAGQADAGgBAKgAgWg4QgHAGgCAIIgIAoIA7AAQAJAAAHgGQAHgGACgJQADgLAAgHQABgJgEgGQgEgGgJAAIgoAAQgIAAgGAGg");
	this.shape_9.setTransform(196,18.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhXB+IAnjKQAEgWARgOQASgNAWAAQAUgBARABQAUABAKANQALANgDASIgQBTQgFAVgRANQgRANgYAAIgkAAQgSAAgDARIgJAuQgDANgLAAgAgVhNIgQBRQgCAMAEAEQAEAEAMAAQASABAQgBQALAAAIgFQAIgGACgKQAKgtAGglQABgKgFgGQgFgFgLAAIghAAQgXAAgFAXg");
	this.shape_10.setTransform(175.8,22.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLCcIAShRQAfgDAUgYQAUgZgDgdQgDgfgYgUQgZgUgdADQgfADgUAYQgUAZADAdIAAAAIhLAkQgEgPgCgNQgGg/AqgyQApgzBBgGQA+gGAzApQAyAqAGBAQAGA/gpAyQgqAzhAAGIgPABIgLgBg");
	this.shape_11.setTransform(15.7,15.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgBAMIgxgTIBlguIgaBrg");
	this.shape_12.setTransform(5.6,24.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAYQgKgIgCgNQgBgMAJgKQAIgLAOgBQALgBAKAJQALAIABANQABAMgIAKQgJALgNABIgDAAQgKAAgJgIg");
	this.shape_13.setTransform(15.7,15.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgEAOQgFgCgCgGQgCgFADgEQACgGAFgDQADgCAFACQAFACACAFQACAFgCAEQgCAGgGADQgDABgBAAIgEAAg");
	this.shape_14.setTransform(105.5,6.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgEAOQgFgCgCgGQgCgFADgEQACgGAFgDQADgCAFACQAFABACAGQACAFgCAEQgDAGgFADQgDABgBAAIgEAAg");
	this.shape_15.setTransform(165.3,6.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,218.7,35.4);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao9D9QhpAAhKhKQhKhKAAhpQAAhnBKhLQBKhKBpAAIR7AAQBpAABKBKQBKBLAABnQAABphKBKQhKBKhpAAg");
	this.shape.setTransform(95.1,29.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(12.4,4.1,165.6,50.7);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBRQhSBTh0AAIx9AAQh0AAhShTQhShRAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,173,58);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AicBdQAAAAgBAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIAaiFQAAgDAEAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgBAFQAGgFAIgDQAIgDAJAAQAKAAAIAEQAIAEAFAHQAGAHABAKQABAOgCAGQgEAQgEAHQgFAKgIAHQgIAHgKAEQgJAEgKAAQgJAAgHgDQgHgDgEgFIgJArQAAAEgEAAgAhqggQgIAEgGAGIgKAzQAEAGAGAEQAHADAIAAQAHAAAGgDQAHgCAFgFQAGgFADgHQAEgIACgKQACgHgBgIQgBgHgDgFQgEgFgFgDQgGgCgHAAQgIAAgIADgAi7BKQAAAAgBAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIADgRIhJAAIgDARQgBADgEAAIgJAAQgEAAABgDIAFgcQABgDAEAAIAGAAQAIgKAHgKIAMgUIAKgVIAIgXQABgDAEAAIAsAAQABAAABAAQABAAAAABQAAAAAAABQAAAAAAABIgRBUIANAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgGAcQgBADgDAAgAjdADQgOAZgJAMIAtAAIAOhJIgUAAQgJAagHAKgAHAA4IgKgDQgJgEgFgHQgFgHgCgKQgBgKACgNQACgKAGgKQAFgKAJgHQAIgHAKgEQALgEALAAQAJAAAIACQAHADAFAEQAFAEACAFQACAGgCAGQgBAHgEAFQgEAGgHACQgIAFgLACQgLACgPAAIgVAAQgBAIACAHQABAGAEAEQAEAEAGACQAFACAHAAQAIAAAHgCQAIgBAGgEQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAIABADIAAAIQgBAEgDABQgHADgIACQgIACgJAAgAHPghQgGACgFAEQgFAEgEAGQgEAGgCAIIARAAIAUgBQAIgBAFgCQAGgCADgEQADgDAAgEQABgDgBgDQgCgDgDgCQgGgEgLAAQgHAAgHACgAFTA4IgKgDQgIgEgGgHQgFgHgBgKQgCgKACgNQADgKAFgKQAGgKAIgHQAIgHALgEQAKgEAMAAQAJAAAHACQAHADAFAEQAFAEACAFQACAGgBAGQgBAHgEAFQgFAGgHACQgHAFgLACQgMACgPAAIgVAAQgBAIACAHQACAGAEAEQADAEAGACQAGACAHAAQAIAAAHgCQAHgBAGgEQABAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAIABADIgBAIQAAAEgEABQgGADgIACQgIACgJAAgAFjghQgGACgFAEQgGAEgDAGQgEAGgDAIIARAAIAUgBQAIgBAGgCQAFgCADgEQADgDABgEQAAgDgBgDQgBgDgDgCQgGgEgMAAQgHAAgGACgABuA3QgFgBgEgCQgFgCgDgEIgFgIQgDgGgCgPQgBgIADgSIAFgSQACgIAEgHQAEgIAEgGQAFgGAGgFQAGgFAIgEQAHgEAJgDIAUgFIAYgEQADAAAAAEIgBAIQAAADgEAAQgRACgMADQgNADgKAFQgJAGgHAHQgGAIgFALQAIgGAJgCQAIgDAIAAQAKAAAIADQAHAEAFAGQAFAHABAJQABAKgCAKQgCAMgGAJQgFAKgHAGQgHAHgJADQgJAEgJAAQgHAAgFgCgAB4gZQgJAEgIAIIgBAEQgDAMABALQAAAJADAHQADAGAGADQAFADAHAAQAHAAAFgDQAGgCAEgFQAFgFADgGQADgHACgIQABgGAAgHQgBgHgDgEQgCgFgFgDQgEgCgHAAQgJAAgJADgAgDA4IgJgDQgIgEgFgIQgFgHgCgKQgBgKACgMQACgJAGgKQAFgKAIgHQAIgIAIgEQAGgCAPgCQAIAAAMAEQAJAEAFAIQAFAHACAKQABAKgCAJQgCAMgGAKQgFAKgIAHQgIAIgKAEQgKAEgMAAgAAKggQgHADgDAFQgFAFgEAHQgDAIgCAGQgCAJABAIQABAHADAFQADAFAGADQADADAIAAQAIAAAHgDQAGgDAGgFQAFgFADgHQAEgIACgJQABgGAAgIQgBgHgDgFQgEgFgFgDQgGgDgHAAQgIAAgHADgAlbA4IgJgDQgIgEgFgIQgFgHgCgKQgBgKACgMQACgJAGgKQAFgKAIgHQAIgIAKgEQAGgCAPgCQAIAAAMAEQAJAEAFAIQAFAHACAKQABAKgCAJQgCAMgGAKQgFAKgIAHQgIAIgKAEQgKAEgMAAgAlMggQgHADgFAFQgFAFgEAHQgDAIgCAGQgCAJABAIQABAHADAFQADAFAGADQAFADAIAAQAIAAAHgDQAGgDAGgFQAFgFADgHQAEgIACgJQABgGAAgIQgBgHgDgFQgEgFgFgDQgGgDgHAAQgIAAgHADgAEIA2QAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAgBIAJgtIg3AAIgJAtQAAAEgEAAIgKAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAgBAAgBIATheQABgDADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgHAlIA3AAIAHglQABgDADAAIAKAAQAEAAgBADIgTBeQAAAEgEAAgAmnA2QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAXh2IhIAAIgYB2IgBADIgDABIgKAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAZiCQABgEAEAAIBkAAQABAAABABQAAAAABAAQAAABAAABQAAAAAAABIgaCCIgBADIgDABg");
	this.shape.setTransform(51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,103.5,18.7);


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990F17").s().p("Ao+D+QhqAAhKhKQhLhLAAhpQAAhoBLhKQBKhLBqAAIR+AAQBpAABLBLQBKBKAABoQAABphKBLQhLBKhpAAg");
	this.shape.setTransform(83.5,27.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.5,1.8,166.1,50.9);


(lib.Символ31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("Ao+kXIR9AAQB0AABSBSQBSBSAABzQAAB0hSBRQhSBTh0AAIx9AAQh0AAhShTQhShRAAh0QAAhzBShSQBShSB0AAg");
	this.shape.setTransform(85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-1,173,58);


(lib.Символ27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AD0DeQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAaiHQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgBAFQAHgFAHgDQAJgDAIAAQAKAAAJAEQAIAEAFAHQAFAHACAKQABAOgCAIQgFAQgDAHQgGAKgIAHQgIAHgJAEQgKAEgKAAQgIAAgIgDQgGgDgFgFIgIArQAAAEgFAAgAEmBfQgIAEgGAGIgLA1QAEAGAHAEQAGADAIAAQAHAAAHgDQAGgCAGgFQAFgFAEgHQAEgIACgKQACgJgBgIQgBgHgEgFQgDgFgGgDQgFgCgHAAQgJAAgHADgA0cDeQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAaiHQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgBAFQAHgFAHgDQAJgDAIAAQAKAAAJAEQAIAEAFAHQAFAHACAKQABAOgCAIQgFAQgDAHQgGAKgIAHQgIAHgJAEQgKAEgKAAQgIAAgIgDQgGgDgFgFIgIArQAAAEgFAAgAzqBfQgIAEgGAGIgLA1QAEAGAHAEQAGADAIAAQAHAAAHgDQAGgCAGgFQAFgFAEgHQAEgIACgKQACgJgBgIQgBgHgEgFQgDgFgGgDQgFgCgHAAQgJAAgHADgARdC5IgJgDQgJgEgFgIQgFgHgBgKQgCgKACgMQADgLAFgKQAGgKAHgHQAIgIAKgEQAHgCAPgCQAIAAAMAEQAIAEAFAIQAGAHABAKQACAKgDALQgCAMgFAKQgGAKgIAHQgIAIgKAEQgKAEgLAAgARsBfQgHADgFAFQgGAFgDAHQgEAIgCAIQgBAJABAIQABAHADAFQADAFAFADQAGADAIAAQAHAAAHgDQAHgDAFgFQAFgFAEgHQAEgIABgJQACgIgBgIQgBgHgDgFQgDgFgGgDQgFgDgIAAQgIAAgGADgALeC5QgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBABgBIACgHQABgEAEABIAGAAQAGAAAEgBQAEgBADgDQADgDACgFQADgFABgIIAMg+QABgDAEAAIA9AAQAEAAgBADIgTBgQgBAEgEAAIgJAAQgEAAABgEIARhVIgjAAIgLA3QgCAJgEAHQgDAHgGAFQgFAEgHACQgHADgIAAgAIEC4QgGgBgEgCQgEgCgDgEIgGgIQgDgGgCgPQAAgIADgUIAEgSQADgIAEgHQADgIAFgGQAFgGAGgFQAGgFAHgEIARgHIAUgFIAXgEQAEAAAAAEIgBAIQgBADgDAAQgRACgNADQgNADgJAFQgKAGgGAHQgHAIgEALQAHgGAJgCQAIgDAJAAQAKAAAHADQAIAEAEAGQAFAHABAJQACAKgDAMQgCAMgFAJQgFAKgIAGQgHAHgJADQgIAEgKAAQgGAAgFgCgAIOBmQgKAEgIAIIgBAEQgCAOAAALQABAJADAHQADAGAFADQAGADAHAAQAGAAAGgDQAFgCAFgFQAEgFADgGQAEgHABgIQACgIgBgHQAAgHgDgEQgDgFgEgDQgFgCgGAAQgKAAgIADgAgPC2QgIgEgFgHQgFgHgCgKQgCgKADgNQABgIAHgOQAFgKAIgHQAIgHAIgEQAJgEALAAQAIAAAHADQAHADAEAFIABgFQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAIgJAAQgEAAABgEIAAgEQgGAFgIADQgIADgJAAQgIAAgIgEgAAIBeQgHADgDAFQgGAFgDAHQgEAIgCAJQgCAKABAHQABAIAEAFQADAFAFACQAFADAGAAQAIAAAIgDQAIgEAGgGIAKg1QgDgGgHgEQgGgDgJAAQgHAAgGACgAikC5QgBAAgBAAQgBgBAAAAQAAgBAAAAQAAgBAAgBIADgHQABgEADABIAHAAQAFAAAEgBQAEgBAEgDQADgDACgFQACgFABgIIAMg+QABgDAEAAIA9AAQAEAAgBADIgTBgQgBAEgDAAIgJAAQgEAAABgEIAQhVIgjAAIgLA3QgBAJgEAHQgEAHgFAFQgFAEgHACQgHADgJAAgAl/C4QgFgBgEgCQgFgCgDgEIgFgIQgDgGgCgPQgBgIADgUIAFgSQACgIAEgHQAEgIAEgGQAFgGAGgFQAGgFAIgEQAHgEAJgDIAUgFIAYgEQADAAAAAEIgBAIQAAADgEAAQgRACgMADQgNADgKAFQgJAGgHAHQgGAIgFALQAIgGAJgCQAIgDAIAAQAKAAAIADQAHAEAFAGQAFAHABAJQABAKgCAMQgCAMgGAJQgFAKgHAGQgHAHgJADQgJAEgJAAQgHAAgFgCgAl1BmQgJAEgIAIIgBAEQgDAOABALQAAAJADAHQADAGAGADQAFADAHAAQAHAAAFgDQAGgCAEgFQAFgFADgGQADgHACgIQABgIAAgHQgBgHgDgEQgCgFgFgDQgEgCgHAAQgJAAgJADgApFC2QgIgEgFgHQgFgHgCgKQgCgKADgNQABgIAHgOQAFgKAIgHQAIgHAKgEQAJgEALAAQAIAAAHADQAHADAEAFIABgFQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAIgJAAQgEAAABgEIAAgEQgGAFgIADQgIADgJAAQgKAAgIgEgAosBeQgHADgFAFQgGAFgDAHQgEAIgCAJQgCAKABAHQABAIAEAFQADAFAFACQAGADAHAAQAIAAAIgDQAIgEAGgGIAKg1QgDgGgHgEQgGgDgJAAQgHAAgGACgAtEC2QgIgEgFgHQgGgHgBgKQgCgKACgNQACgIAGgOQAGgKAIgHQAIgHAJgEQAKgEAKAAQAJAAAHADQAHADAEAFIABgFQAAgDAEAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgTBgQAAAEgFAAIgJAAQgDAAAAgEIABgEQgGAFgIADQgIADgJAAQgKAAgIgEgAssBeQgGADgGAFQgFAFgEAHQgEAIgCAJQgBAKABAHQABAIADAFQADAFAGACQAFADAHAAQAJAAAIgDQAHgEAGgGIALg1QgEgGgGgEQgHgDgIAAQgHAAgHACgAvaC5QgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBABgBIACgHQABgEAEABIAGAAQAGAAAEgBQAEgBADgDQADgDACgFQADgFABgIIAMg+QABgDAEAAIA9AAQAEAAgBADIgTBgQgBAEgEAAIgJAAQgEAAABgEIARhVIgjAAIgLA3QgCAJgEAHQgDAHgGAFQgFAEgHACQgHADgIAAgAyCC5IgKgDQgIgEgGgHQgFgHgBgKQgCgKACgNQADgMAFgKQAGgKAIgHQAIgHALgEQAKgEAMAAQAJAAAHACQAHADAFAEQAFAEACAFQACAGgBAGQgBAHgEAFQgFAGgHAEQgHAFgLACQgMACgPAAIgVAAQgBAIACAHQACAGAEAEQADAEAGACQAGACAHAAQAIAAAHgCQAHgBAGgEQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIABADIgBAIQAAAEgEABQgGADgIACQgIACgJAAgAxyBeQgGACgFAEQgGAEgDAGQgEAGgDAIIARAAIAUgBQAIgBAGgCQAFgCADgEQADgDABgEQAAgDgBgDQgBgDgDgCQgGgEgMAAQgHAAgGACgAT/C3QgDAAAAgEIAPhMIhGBOQgCACgDAAIgMAAQgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgPBNIBGhOQACgCADAAIANAAQAEAAgBADIgTBgQAAAEgEAAgAQTC3QgDAAAAgEIAJgtIg3AAIgJAtQAAAEgEAAIgKAAQgDAAAAgEIAThgQABgDADAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgHAlIA3AAIAHglQABgDADAAIAKAAQAEAAgBADIgTBgQAAAEgEAAgANgC3QgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgGAhIATAAQANAAAJACQAJACAGAEQAFAEADAHQACAGgCAJQgCAJgEAGQgFAGgHAEQgHAEgKACQgKACgMAAgANwCpIAUAAIAQgBQAGgBAFgDQAEgCACgEQADgDABgFQABgFgBgEQgBgDgEgDQgDgCgGgBIgPgBIgVAAgAK/C3QgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAgAJWC3QgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgGAhIATAAQANAAAJACQAJACAGAEQAFAEADAHQACAGgCAJQgCAJgEAGQgFAGgHAEQgHAEgKACQgKACgMAAgAJmCpIAUAAIAQgBQAGgBAFgDQAEgCACgEQADgDABgFQABgFgBgEQgBgDgEgDQgDgCgGgBIgPgBIgVAAgAG7C3QgDAAAAgEIAPhMIhGBOQgCACgDAAIgMAAQgEAAABgEIAShgQABgDAEAAIAJAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgPBNIBGhOQACgCADAAIANAAQAEAAgBADIgTBgQAAAEgEAAgADPC3QgDAAAAgEIARhVIgzAAIgRBVQAAAEgEAAIgKAAQgDAAAAgEIAThgQABgDADAAIBOAAQAEAAgBADIgTBgQAAAEgEAAgAjEC3QgDAAAAgEIAThgQABgDADAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgTBgQAAAEgEAAgAktC3QgDAAAAgEIAThgQABgDADAAIAKAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgHAhIAUAAQAMAAAJACQAKACAFAEQAGAEACAHQACAGgBAJQgCAJgFAGQgEAGgIAEQgHAEgKACQgJACgNAAgAkdCpIAVAAIAQgBQAGgBAEgDQAFgCACgEQACgDABgFQABgFgBgEQgBgDgDgDQgDgCgHgBIgPgBIgUAAgAqGC3QgDAAAAgEIAPhLIgpArQAAAAgBABQAAAAAAAAQgBAAAAAAQgBABAAAAIgHAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgYgrIgPBLQAAAEgEAAIgJAAQgEAAABgEIAShgQABgDAEAAIALAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIAcAzIAwgzIADgBIALAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAABIgTBgQAAAEgEAAgAvxC3QgEAAgCgDIgmgvIgJAuQAAAEgEAAIgKAAQgDAAAAgEIAThgQABgDADAAIAKAAQAEAAgBADIgJArIAzgrQAEgDAEAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAIg3AuIApAyIAAADQAAAAAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAgATqA/QgFgCgEgDQgEgEgBgEQgCgFAAgHQABgEAEAAIAHAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABQAAAHAEAEQAEAEAHAAQAGAAAGgEQAFgEADgHQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAIAHAAQAFAAgCAEQgCAHgEAFQgDAEgFAEQgFADgGACQgGACgGAAQgGAAgFgCgAmbgtIgBgDQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAEgDAEgFQADgGACgFQgGAAgCgEQgCgDABgEQABgHAEgDQADgCAGAAQAHAAACADQACADgBAIIgEAKIgFAKIgIAIIgIAHIgCAAIgBgBgAqng0QgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIADgQIhIAAIgEAQQgBAEgDAAIgJAAQgEAAABgEIAFgbQABgEADAAIAGAAQAJgKAGgKIANgVIAKgWIAIgWQABgEADAAIAtAAQABAAAAAAQABAAAAABQAAAAAAABQABABgBABIgQBVIAMAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgFAbQgBAEgEAAgArJh7QgOAYgKAMIAtAAIAPhKIgVAAQgJAZgGANgALyhKQgIgDgFgHQgFgIgCgJQgCgLADgMQABgJAHgOQAFgKAIgHQAIgHAKgDQAJgEALAAQAIAAAHADQAHACAEAFIABgEQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgTBgQAAAEgEAAIgJAAQgEAAABgEIAAgEQgGAFgIACQgIADgJAAQgKAAgIgEgAMLihQgHADgFAEQgGAFgDAIQgEAHgCAKQgCAJABAIQABAHAEAFQADAFAFADQAGACAHAAQAIAAAIgDQAIgDAGgGIAKg2QgDgGgHgDQgGgDgJAAQgHAAgGACgAHxhKQgIgDgFgHQgFgIgCgJQgCgLADgMQABgJAHgOQAFgKAIgHQAIgHAKgDQAJgEALAAQAIAAAHADQAHACAEAFIABgEQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgTBgQAAAEgEAAIgJAAQgBAAgBgBQAAAAgBAAQAAgBAAgBQAAAAAAgBIAAgEQgGAFgIACQgIADgJAAQgKAAgIgEgAIKihQgHADgFAEQgGAFgDAIQgEAHgCAKQgCAJABAIQABAHAEAFQADAFAFADQAGACAHAAQAIAAAIgDQAIgDAGgGIAKg2QgDgGgHgDQgGgDgJAAQgHAAgGACgAA5hHQgFgBgEgDQgFgCgDgDIgFgIQgDgGgCgPQgBgJADgTIAFgSQACgJAEgHQAEgHAEgGQAFgHAGgFQAGgFAIgEQAHgEAJgDIAUgFIAYgDQADgBAAAEIgBAIQAAADgEABQgRABgMADQgNAEgKAFQgJAFgHAIQgGAIgFALQAIgGAJgDQAIgCAIAAQAKAAAIADQAHADAFAHQAFAGABAKQABAJgCAMQgCAMgGAKQgFAJgHAHQgHAGgJAEQgJADgJAAQgHAAgFgBgABDiZQgJAEgIAIIgBAEQgDAOABAKQAAAKADAGQADAHAGADQAFACAHAAQAHAAAFgCQAGgDAEgEQAFgFADgHQADgGACgJQABgIAAgHQgBgGgDgFQgCgFgFgCQgEgDgHAAQgJAAgJAEgAg4hHIgJgDQgIgEgFgHQgFgIgCgJQgBgKACgMQACgMAGgKQAFgKAIgHQAIgHAKgEQAGgDAPgBQAIAAAMAEQAHAEAFAHQAFAHACAKQABAKgCAMQgCAMgGAKQgFAJgGAIQgIAHgKAEQgKAEgMAAgAgpihQgHADgFAFQgFAFgEAIQgDAHgCAJQgCAJABAHQABAIADAFQADAFAGADQAFACAIAAQAIAAAHgCQAGgDAGgFQAFgGADgHQAEgHACgJQABgJAAgHQgBgIgDgFQgEgFgFgDQgGgCgHAAQgIAAgHACgApshKQgIgDgFgHQgGgIgBgJQgCgLACgMQACgJAGgOQAGgKAIgHQAIgHAJgDQAKgEAKAAQAJAAAHADQAHACAEAFIABgEQAAgEAEAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgTBgQAAAEgFAAIgJAAQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIABgEQgGAFgIACQgIADgJAAQgKAAgIgEgApUihQgGADgGAEQgFAFgEAIQgEAHgCAKQgBAJABAIQABAHADAFQADAFAGADQAFACAHAAQAJAAAIgDQAHgDAGgGIALg2QgEgGgGgDQgHgDgIAAQgHAAgHACgAtXhKQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBIACgIQACgFADACQAIADATABIANgBIALgDQAEgCACgDQADgCAAgDQABgFgCgEQgCgDgEgDQgFgCgHgCIgSgCQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIABgHQABgEADAAIARgBQAIgBAGgCQAGgDADgDQAEgDAAgEQACgGgGgDIgIgDIgNAAQgTABgIACQgFABABgDIABgJQAAgDAEgBQAIgCAVgBQALAAAIABQAIACAFAEQAFADACAFQACAFgBAHQgBAFgDAEIgHAIIgKAFIgLADIALAEQAFACADAEQACAEABAEIABAJQgCAHgFAGQgEAFgIAEQgHAEgJABQgIACgKAAQgWgBgIgDgAunhHIgJgDQgIgEgFgHQgFgIgCgJQgBgKACgMQACgMAGgKQAFgKAIgHQAIgHAKgEQAGgDAPgBQAIAAAMAEQAJAEAFAHQAFAHACAKQABAKgCAMQgCAMgGAKQgFAJgIAIQgIAHgKAEQgKAEgMAAgAuYihQgHADgFAFQgFAFgEAIQgDAHgCAJQgCAJABAHQABAIADAFQADAFAGADQAFACAIAAQAIAAAHgCQAGgDAGgFQAFgGADgHQAEgHACgJQABgJAAgHQgBgIgDgFQgEgFgFgDQgGgCgHAAQgIAAgHACgAwQhKQgJgEgGgHQgGgHgCgKQgBgGABgQQACgIAHgOQAGgKAIgIQAJgHAKgDQALgEAMAAIAOABQAHABAEACQABAAABABQAAAAAAABQABAAAAABQAAABgBABIgCAIQAAABgBAAQAAABgBAAQAAABgBgBQgBAAgBAAQgFgCgFgBIgMgBQgJAAgHACQgIADgGAFQgGAFgEAHQgEAIgCAJQgBAJABAHQABAIAEAFQAEAFAHADQAGACAJAAIANgBIALgEQAFgCAAAEIgBAJQAAADgEABQgGADgHABQgGABgIAAQgPgBgHgDgAJRhIQgDAAAAgEIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgRBVIAfAAIARhVQABgEAEAAIAJAAQAEAAgBAEIgRBVIAgAAIAQhVQABgEAEAAIAJAAQAEAAgBAEIgTBgQAAAEgEAAgAF2hIQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIAThgQABgEADAAIAbAAQALAAAIACQAIABAFADQAFAEADAFQACAFgBAGQgCAIgEAFQgGAGgKAEIAJAEIAGAFQACAEABAEQABAEgBAEQgCAHgEAGQgEAFgHAEQgHAEgJACQgKACgLAAgAGFhXIAPAAIAQgBIALgDQAEgCACgDQADgDABgEQAAgEgBgDQgBgDgEgCIgJgDIgPgBIgQAAgAGOiFIAbgBIAKgCQAEgCACgDQACgDABgDQABgEgCgDQgBgDgDgBIgJgDIgbAAgAD0hIQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgTBgQAAAEgEAAgACLhIQgBAAAAgBQgBAAAAAAQgBgBAAgBQAAAAAAgBIAThgQABgEADAAIAKAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIgHAhIAUAAQAMAAAJACQAKACAFAEQAGAEACAGQACAHgBAIQgCAJgFAGQgEAHgIAEQgHAEgKACQgJACgNAAgACbhXIAVAAIAQgBQAGgBAEgCQAFgCACgEQACgDABgGQABgFgBgDQgBgEgDgCQgDgCgHgCIgPgBIgUAAgAibhIQgEAAABgEIAQhVIgiAAQgEAAABgEIABgHQABgEAEAAIBVAAQAEAAgBAEIgBAHQgBAEgEAAIgiAAIgRBVQgBAEgDAAgAjihIQgEAAABgEIAIgnQgHADgHACQgIACgHAAQgJAAgHgDQgHgDgEgGQgEgGgBgJQAAgJACgLIADgRQABgEAEAAIAJAAQAEAAgBAEIgDARQgCAJAAAGQABAGACAEQACAEAEACQAEABAHAAQAHAAAIgCQAHgDAFgEIAIgoQABgEAEAAIAJAAQAEAAgBAEIgTBgQgBAEgDAAgAnEhIQgEAAABgEIAIgtIg3AAIgJAtQAAAEgEAAIgJAAQgEAAABgEIAShgQABgEAEAAIAJAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIgHAkIA3AAIAHgkQABgEAEAAIAJAAQAEAAgBAEIgTBgQAAAEgEAAg");
	this.shape.setTransform(106.6,29.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24.6,7.5,262.5,44.4);


(lib.Символ26 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHoBJQgHgBgGgDIgKgFQgFgCgDgEQgDgEgCgEIgDgJQgCgKACgMIAEgNIAFgJIAIgJIAJgHQAGgFAQgFQAMgEAOAAQAMAAAJADQAJACAGAFQAGAEACAGQACAHgBAGQgCAHgEAGQgFAGgIAFQgJAEgLADQgNACgQAAIgHAAQAAAEABADQACADADACQAFADAMAAIANgBIANgEQAFgCgBAFIgBASQgBAEgDABQgIACgKABQgKACgKAAIgPgBgAH4gDQgEADgDAIIADAAQANAAAHgDQAFgCABgDQAAgDgCgCQgCgCgFAAQgIAAgFAEgAA5BGQgIgEgEgHQgFgHgBgKQgCgKADgNQACgMAGgIQAFgKAHgHQAIgHAIgEQAJgEAJAAQAJAAAGADQAGADADAFIABgFQABgDADAAIAsAAQAEAAgBADIgTBeQgBAEgDAAIgsAAQgEAAABgEIABgEQgFAFgHACQgIAEgIAAQgJAAgHgEgABiAAQgEAFgDAOQgDAPACAFQABAGAHAAQAEAAADgDIAJgrQgCgDgFAAQgGAAgDAEgAkTBGIgKgFIgIgGQgDgEgCgEQgDgEgBgFIgBgLIABgMQACgIAHgMQAEgHAMgKQAGgFAPgGQAIgCASgCQAKAAAPAEQAFACAEADIAIAGIAGAIIADAJIABAJIgBALIgDAMIgGALQgJAMgGAFQgOAIgIADQgRAEgJAAQgRgCgHgCgAj0AAQgEAGgDANQgCAOACAGQABAGAFAAQAFAAADgGQAEgGADgOQADgNgCgGQgCgEgEAAQgFAAgEAEgAmYBGIgJgFIgIgGQgEgEgCgEQgCgEgBgFIgBgLIABgMQABgIAIgMQAEgHALgKQAHgFAPgGQAIgCASgCQAJAAAPAEQAGACAEADIAIAGIAFAIIAEAJIABAJIgBALIgEAMIgFALQgKAMgGAFQgNAIgIADQgRAEgJAAQgSgCgHgCgAl4AAQgEAGgDANQgDAOACAGQACAGAEAAQAFAAAEgGQAEgGACgOQADgNgCgGQgBgEgFAAQgFAAgDAEgAF9BHQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgIgsIgJArQAAAEgEAAIgsAAQgEAAABgEIAbiIQABgEAEAAIArAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgPBKIAWghQACgCADAAIAuAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgfAnIAQA0QAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAgADzBHQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIASheQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBeQAAAEgEAAgACsBHQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAbiIQAAgEAFAAIArAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgbCIQAAAEgEAAgAhnBHQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAgBIgIgsIgJArQAAAEgEAAIgsAAQgEAAABgEIAbiIQABgEAEAAIArAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgPBKIAWghQACgCADAAIAuAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgfAnIAQA0QAAAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAgAo0BHQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAZiCQABgEAEAAIAuAAQABAAABABQAAAAAAAAQABABAAABQAAAAAAABIgUBiIA8AAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABIgGAcQAAAEgEAAgAgdAVQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAFgXQABgDADAAIA0AAQAEAAgBADIgFAXQAAAEgEAAgAESgnQgFgBgDgCQgDgCgBgEQgBgDABgFIADgHQADgEADgCIAJgDIANgBIAMABQAFABACACQAEACAAAEQACADgBAEQgBAFgDADQgCAEgEACQgDACgGABIgMABg");
	this.shape.setTransform(56.9,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,113.8,14.9);


(lib.Символ25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgFCzIAwgzQgTgVAAgdQAAgfAXgVQAVgXAgAAQAfAAAVAXQAXAVAAAfQAAAggXAVQgVAXgfAAQgdAAgVgTIgyAygAA1AgQgTAUAAAaQAAAbATAUQAUATAbAAQAaAAAUgTQASgUABgbQgBgagSgUQgUgSgagBQgbABgUASgAhUCCIAUhIIAAgZIgFAAQgnABgcAcQgcAcAAAnIAAAPIgKAAIAAgPQABgrAegfQAfgfArgBIgMgOQgWgbAAglIAAhFIAKAAIAABFQAAAiAUAYIARAUIAjAAIARgUQASgYAAgiIAAg7QgagBgcgHQgZgFgQgIIgEgCIAEgJIAFACQAPAIAZAGQAdAFAbABIAEAAIAABFQAAAlgWAbIgKAOQAOAAATAHIAFABIgEAKIgEgCQgQgGgOAAIgFAAIAAAZIASBIIgsAtgAhJB/IAiAjIAjgjIgSg/IghAAgAg2A2IAfAAIAAgVIgfAAgAAuBaIgCgMQAAgWAQgQQAQgRAYAAIAEAAIAAAKIgEAAQgTAAgOAOQgMANAAASIACAOIgKACgAAigsIAAgLIAGAAQAGABAEgFQAFgEAAgGQAAgHgFgEQgEgEgGgBIgGAAIAAgnQAAgQgJgMQgIgMgPgEQgXgGgSgBQgRABgZAGQgPAEgIAMQgJAMAAAQIAAAnIgGAAQgGABgEAEQgFAEAAAHQAAAGAFAEQAEAFAGgBIAGAAIAAALIgGAAQgKgBgHgGQgIgIAAgKQAAgJAGgIQAGgGAJgCIAAgeQAAgTALgPQALgPARgEQAagIATAAQAUAAAYAIQARAEALAPQALAPAAATIAAAeQAJACAGAGQAGAIAAAJQgBAKgGAIQgIAGgKABgAgdhBIAAgKIAdAAIAAAKgAhOhBIAAgKIAeAAIAAAKg");
	this.shape.setTransform(17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,35,37.2);


(lib.Символ24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHOQi/i/gBkPQABkOC/jAQDAi/EOgBQEPABC/C/QDADAABEOQgBEPjAC/Qi/DAkPABQkOgBjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AixBZQgEAAACgEIAaiFQABgDADAAIAsAAQAEAAgBADIgBAFQAGgFAHgDQAHgDAIAAQAJAAAHAEQAHAEAFAHQAFAHABAKQABAKgCAMQgDALgFAKQgFAKgIAHQgHAHgIAEQgJAEgJAAQgHAAgGgDQgHgCgEgGIgJArQAAAEgEAAgAhrgWIgJArQACADAEAAQAGAAAEgFQAEgGADgNQACgOgBgGQgCgFgGAAQgEAAgDADgABsA0QgHgBgGgDIgKgFQgEgCgDgEQgEgEgCgEIgDgJQgCgKACgKIAEgNIAGgLIAHgJIAJgHQAHgFAQgFQAMgEAOAAQALAAAKADQAIACAGAFQAGAEACAGQADAHgCAHQgBAIgFAGQgFAGgIADQgIAEgMADQgMACgRAAIgHAAQAAAEACADQABADADACQAGADAMAAIANgBIAMgEQAFgCAAAFIgCASQAAAEgEABQgIACgJABQgKACgLAAIgPgBgAB9gYQgFAEgDAJIADAAQAOAAAGgDQAFgCABgEQABgEgCgCQgDgCgFAAQgHAAgFAEgAkbAxQgIgEgEgHQgFgHgBgKQgCgKADgLQACgMAGgKQAFgKAHgHQAIgHAIgEQAJgEAJAAQAJAAAGADQAGADADAFIABgFQABgDADAAIAsAAQAEAAgBADIgTBeQgBAEgDAAIgsAAQgEAAABgEIABgEQgFAFgHACQgIAEgIAAQgJAAgHgEgAjygUQgEAGgDAOQgDANACAFQABAGAHAAQAEAAADgDIAJgrQgCgDgFAAQgGAAgDAFgAnsA0QgHgBgGgDIgKgFQgFgCgDgEQgDgEgCgEIgDgJQgCgKACgKIAEgNIAFgLIAIgJIAJgHQAGgFAQgFQAMgEAOAAQAMAAAJADQAJACAGAFQAGAEACAGQACAHgBAHQgCAIgEAGQgFAGgIADQgJAEgLADQgNACgQAAIgHAAQAAAEABADQACADADACQAFADAMAAIANgBIANgEQAFgCgBAFIgBASQgBAEgDABQgIACgKABQgKACgKAAIgPgBgAncgYQgEAEgDAJIADAAQANAAAHgDQAFgCABgEQAAgEgCgCQgCgCgFAAQgIAAgFAEgAI4AyQgEAAABgEIASheQABgDAEAAIBWAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgEAVQgBAEgEAAIgnAAIgOBFQAAAEgEAAgAHzAyQgDAAAAgEIAHgiIgRAAIgHAiQAAAEgEAAIgsAAQgEAAABgEIATheQAAgDAEAAIAsAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIgHAhIASAAIAGghQAAgDAEAAIAsAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIgTBeQAAAEgEAAgAFxAyQgEAAABgEIAHgkIgkAmIgEACIgjAAQgEAAABgEIASheQABgDAEAAIAlAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAkIAlgmIADgBIAjAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBeQAAAEgEAAgADSAyQgDAAAAgEIAOhFIgXAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAEgVQABgDAEAAIBhAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIgEAVQgBAEgEAAIgXAAIgOBFQAAAEgEAAgAgjAyQgEAAABgEIATheQAAgDAEAAIBVAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIgFAVQAAAEgEAAIgnAAIgOBFQAAAEgEAAgAmGAyQgDAAAAgEIAOhFIgXAAQgBAAgBAAQgBAAAAgBQAAAAAAgBQgBgBABgBIAEgVQAAgDAEAAIBhAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgEAVQAAAEgEAAIgXAAIgOBFQgBAEgEAAgAqhAyQgDAAAAgEIAaiCQAAgEAFAAIA5AAQAPAAALADIALAEIAIAFQAEADACAEQADAEABAEQABAFAAAGIgBAMIgEAMQgCAGgDAEQgDAFgEAEIgJAHQgOAFgIACQgNADgPAAIgJAAIgHAkQgBAEgEAAgApjgVIAMAAQAHAAAEgEQAFgEACgJQACgJgEgEQgDgEgHAAIgLAAg");
	this.shape.setTransform(67.7,8.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,135.5,17.9);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AiOCPQgsgsAAg/QAAg8AsgsQAngoA5gEQA2gEAtAhIAEADIgGAIIgEgDQgpgfgzAEQg1AEglAlQgoApAAA4QAAA7AoApQApApA7AAQA4AAApgpQAmglADg1QAEgygfgqIgDgEIAIgGIADAEQAiAtgFA2QgEA4goAoQgsAsg8AAQg/AAgsgsgAh2B3QgjgjAAgwQAAguAjgjQAegeAqgDQAqgEAiAYIADACIgGAJIgEgDQgdgWgnADQgnAEgbAbQgfAgAAAqQAAAtAfAfQAfAfAtAAQAqAAAggfQAbgcADgmQAEgngWgeIgCgEIAIgFIADAEQAYAhgEAqQgEAqgeAeQgjAiguAAQgxAAgigigAheBfQgZgYAAgjQAAgiAZgXQAUgUAcgEQAcgDAXAOIAEACIgFAJIgEgDQgUgMgZADQgZAEgRARQgWAUAAAeQAAAfAWAVQAWAWAeAAQAeAAAUgWQASgRADgZQADgZgNgVIgCgDIAJgFIACAFQAPAWgFAcQgDAcgUAUQgWAZgjAAQgjAAgYgZgAhHBHQgOgNAAgWQAAgVAOgOQALgIANgDQANgEAOAFIAFABIgDAIIgFAAQgXgHgSAPQgLAMAAAQQAAARALALQANAMAQAAQAQAAAMgMQAHgIACgKQACgLgDgLIgBgFIAJgDIACAFQADAOgCANQgEAOgIAJQgOAPgVAAQgVAAgPgPgAgqAkICHiGIgIgoIAvgwIAJAtIAuAKIgwAwIgogIIiGCGgABfiHIAHAiIAiAHIAfgfIgigHIgHgig");
	this.shape.setTransform(18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,37.5,37.6);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHOQi/i/gBkPQABkOC/jAQDAi/EOgBQEPABC/C/QDADAABEOQgBEPjAC/Qi/DAkPABQkOgBjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHOQi/i/gBkPQABkOC/jAQDAi/EOgBQEPABC/C/QDADAABEOQgBEPjAC/Qi/DAkPABQkOgBjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0DbQgFAAADgFIAQgiIgVhiQgBgFAFAAIAqAAQAEAAAAADIADA3IAVg3QACgDADAAIArAAQAFAAgDAFIhFCGQgBADgEAAgAk9CzQgHgEgFgHQgEgHgCgKQgBgKACgNQADgMAFgKQAGgKAHgHQAHgHAJgEQAIgEAJAAQAJAAAGADQAHADACAFIABgFQABgDAEAAIArAAQAEAAgBADIgTBgQgBAEgDAAIgrAAQgEAAABgEIAAgEQgEAFgHACQgIAEgJAAQgJAAgHgEgAkUBsQgEAGgDAOQgCAPABAFQACAGAGAAQAEAAADgDIAJgtQgCgDgEAAQgGAAgEAFgAmzC1QgLgBgJgDQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAgBIAHgTQABgFAEACQAIADAIACIAQABIAKgBQADgCABgCQAAgFgGgCQgHgCgTgBQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIADgTQABgDAEAAQASgBAIgCQAIgBAAgEQAAgBAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQgDgCgHAAQgUABgMADIgDAAIgBgDIACgTQAAgEAEAAQANgDAcgCQAQAAAKADQALACAGAEQAGAEACAHQACAFgCAIQgBAGgFAGQgFAGgIACQAIAEADAGQACAGgBAHQgBAHgFAGQgFAHgIAEQgIAEgLACQgMADgOAAQgMAAgLgCgAGTC0QgBAAgBAAQgBAAAAgBQAAAAAAgBQgBgBABgBIAHgkIgkAmIgEACIgjAAQgEAAABgEIAShgQABgDAEAAIAlAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAkIAlgmIADgBIAjAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBgQAAAEgEAAgAELC0QgEAAAAgDIgKgqIgIApQAAAEgEAAIgrAAQgEAAABgEIAShgQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAlIAXgmQABgCADAAIAuAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIghAsIARAxQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAgACBC0QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAOhHIgRAAIgOBHQAAAEgEAAIgsAAQgEAAABgEIAThgQAAgDAEAAIBwAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIgTBgQAAAEgEAAgAiFC0QgBAAgBAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIgKgqIgIApQAAAEgEAAIgrAAQgEAAABgEIAShgQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAlIAXgmQABgCADAAIAuAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAIghAsIARAxQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAgABsgnQgEAAABgEIAaiHQABgDAEAAIArAAQAEAAgBADIgBAFQAGgFAIgDQAHgDAIAAQAIAAAIAEQAHAEAEAHQAFAHABAKQACAKgDAMQgCANgGAKQgFAKgHAHQgHAHgJAEQgJAEgJAAQgHAAgGgDQgHgCgEgGIgIArQgBAEgEAAgACxiYIgJAtQACADAFAAQAGAAAEgFQADgGADgPQADgOgCgGQgBgFgGAAQgFAAgDADgAn3gnQgFAAADgFIAQgiIgWhiQgBgFAGAAIAqAAQADAAABADIADA3IAXg3QABgDADAAIArAAQAFAAgDAFIhGCGQgCADgDAAgAk+g6QgEAAABgEIAEgQIgiAAIgDAQQgBAEgEAAIgpAAQgEAAABgEIAIgpQABgDADAAIAIAAQAHgMAJgYQAHgRAEgTQABgDAEAAIBXAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIgOBIIAIAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgIApQgBAEgDAAgAlEiEQgFAOgGAMIAOAAIAKgyIgFAAQgDAMgFAMgAJhhMQgHgBgGgDIgKgFQgFgCgDgEQgDgEgCgEIgDgJQgCgKACgMIAEgNIAFgLIAIgJIAJgHQAGgFAQgFQAMgEAOAAQAMAAAJADQAJACAGAFQAGAEACAGQACAHgBAHQgCAIgEAGQgFAGgIAFQgJAEgLADQgNACgQAAIgHAAQAAAEABADQACADADACQAFADAMAAIANgBIANgEQAFgCgBAFIgBASQgBAEgDABQgIACgKABQgKACgKAAIgPgBgAJxiaQgEAEgDAJIADAAQANAAAHgDQAFgCABgEQAAgEgCgCQgCgCgFAAQgIAAgFAEgAAMhPIgJgFIgGgGQgEgEgCgEQgCgEgBgFIgBgLIABgMQABgIAIgOQADgHAKgKQAHgFAPgGQAIgCASgCQAJAAAPAEQAGACAEADIAIAGIAFAIIAEAJIABALIgBALIgEAMIgFALQgKAMgGAFQgNAIgIADQgRAEgJAAQgSgCgHgCgAAsiWQgEAHgDANQgDAOACAGQACAGAEAAQAFAAAEgGQAEgGACgOQADgNgCgHQgBgFgFAAQgFAAgDAFgAHzhOQgFAAACgEIAShgQABgDAEAAIArAAQAEAAgBADIgTBgQgBAEgDAAgAGChOQgEAAABgEIAThgQAAgDAEAAIAoAAQAEAAgBADIgGAbIALAAQALAAAIADQAJACAFAEQAGAFACAHQACAHgBAJQgCAJgFAHQgFAHgHAEQgIAFgJACQgJACgLAAgAGyhpIAFAAQAFAAADgCQADgCAAgFQABgFgBgCQgCgDgFAAIgFAAgAE+hOQgEAAABgEIAGgiIgRAAIgHAiQAAAEgEAAIgrAAQgEAAABgEIAShgQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgGAhIARAAIAGghQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBgQAAAEgEAAgAhmhOQgDAAAAgEIAOhHIgXAAQgBAAgBAAQgBAAAAgBQAAAAAAgBQgBgBABgBIAEgVQAAgDAEAAIBhAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgEAVQAAAEgEAAIgXAAIgOBHQgBAEgEAAgAi3hOQgEAAABgEIAHgkIgkAmIgEACIgjAAQgEAAABgEIAShgQABgDAEAAIAlAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAkIAlgmIADgBIAjAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBgQAAAEgEAAgApJhOQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgVIgjAAIgIAVQgCADgDAAIgwAAQgEAAACgFIBAiEQABgDADAAIBGAAQAAAAABAAQAAABABAAQAAAAABABQAAAAAAABIANCEQAAAFgEAAgApOiKIAAguIgTAuIATAAg");
	this.shape.setTransform(68.9,21.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,137.9,43.9);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AgsCXIAUhbIAAgaIgEAAQgoAAgcAcQgcAcAAAnIAAAPIgKAAIAAgPQAAgrAfgfQAfgfAsAAIgNgPQgWgbAAgkIAAhGIAKAAIAABGQAAAhAUAYIARAVIAiAAIAQgVQAVgYgBghIAAg8QgcgBgagGQgYgGgRgIIgEgCIAEgJIAFACQAPAIAXAGQAdAGAdAAIAEAAIAABGQAAAlgWAaIgMAPQAsAAAeAfQAeAfABArIAAAPIgKAAIAAgPQgBgngbgcQgcgcgnAAIgFAAIAAAXIAUBeIgtAigAghCTIAhAaIAigaIgShTIgeAAgAgOA2IAdAAIAAgUIgdAAgABKgsIAAgKIAGAAQAGAAAEgFQAFgEAAgGQAAgGgFgFQgEgEgGAAIgGAAIAAgoQAAgQgJgMQgIgMgPgEQgZgGgRAAQgQAAgZAGQgPAEgIAMQgJAMAAAQIAAAoIgGAAQgFAAgFAEQgFAFAAAGQAAAGAFAEQAFAFAFAAIAGAAIAAAKIgGAAQgKAAgHgHQgIgIAAgKQABgJAFgHQAGgHAJgCIAAgeQAAgTALgPQALgOARgFQAagHASAAQATAAAaAHQARAFALAOQALAPAAATIAAAeQAJACAGAHQAGAHAAAJQgBAKgGAIQgIAHgKAAgAAJhAIAAgKIAeAAIAAAKgAgmhAIAAgKIAeAAIAAAKg");
	this.shape.setTransform(13.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27,37.2);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("ABkC2IAAhNQAAgXgQgRQgIgHgIgEIAAA9IgwgXIgUAkIgTgkIgwAXIAAg9QgJAEgHAHQgQARAAAXIAABNIgKAAIAAhNQAAgbATgUQATgTAbAAIATAAIAAgNIgFgEQgRgOgKgRQgKgUAAgWIAAgpIAKAAIAAApQAAAUAJARQAJAQAPAMIAJAGIAAAdIgRAAIAgA7IAhg7IgRAAIAAgdIAIgGQAQgMAJgQQAJgRAAgUIAAgZQgngBgWgJQgYgJgcgZIAHgHQAbAYAWAIQAXAJAnAAIAFAAIAAAjQAAAWgKAUQgKARgSAOIgEAEIAAANIATAAQAbAAATATQATAUAAAbIAABNgAAZBTIAhAQIAAgxQgGgBgHAAgAg5AyIAAAxIAhgQIgUgiQgHAAgGABgABpAxQARAAASgPQgYgRgNgVQgNgWAAgXIAAg1QAAgdgVgTQgUgVgdAAIg9AAIAAgKIA9AAQAhAAAYAXQAXAXAAAhIAAA1QAAAYAQAXQANARAVAOIAGADIgFAFQgXAWgXAAgAiWAlIgFgFIAFgDQAYgPAOgUQANgWAAgVIAAhBQAAgXARgOQASgPAWAEIAMACIgBAKIgNgCQgRgDgOAMQgOAMAAARIAABBQAAAXgNAWQgNAVgYARQASAPARAAIAAAKQgXAAgXgWgAAQg3IAAgKIAUAAIAAAKgAgjg3IAAgKIAUAAIAAAKg");
	this.shape.setTransform(15.6,18.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,31.3,36.5);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnOHOQi/i/gBkPQABkOC/jAQDAi/EOgBQEPABC/C/QDADAABEOQgBEPjAC/Qi/DAkPABQkOgBjAjAg");
	this.shape.setTransform(65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AniBcQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAIgrQgEAFgHACQgIAEgJAAQgJAAgHgEQgHgEgFgHQgEgHgCgKQgBgKACgNQADgKAFgKQAGgKAHgHQAHgHAJgEQAIgEAJAAQAJAAAGADQAHADACAFIAJgvQABgEAEAAIArAAQAEAAgBAEIgJAvQAFgFAHgDQAIgDAIAAQAJAAAIAEQAHAEAEAHQAFAHABAKQACAKgDAKQgCANgGAKQgFAKgHAHQgIAHgIAEQgJAEgJAAQgIAAgHgEQgGgCgDgFIgIArQgBAEgEAAgAmdgTIgJArQACADAFAAQAGAAADgGQAEgFADgPQADgMgCgGQgBgFgGAAQgFAAgDADgAnggRQgEAGgDAMQgCAPABAFQACAGAGAAQAEAAADgDIAJgrQgCgDgEAAQgGAAgEAFgAqqBcQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIAIgrQgEAFgHACQgIAEgJAAQgJAAgHgEQgHgEgFgHQgEgHgCgKQgBgKACgNQADgKAFgKQAGgKAHgHQAHgHAJgEQAIgEAJAAQAJAAAGADQAHADACAFIAJgvQABgEAEAAIArAAQAEAAgBAEIgJAvQAFgFAHgDQAIgDAIAAQAJAAAIAEQAHAEAEAHQAFAHABAKQACAKgDAKQgCANgGAKQgFAKgHAHQgIAHgIAEQgJAEgJAAQgIAAgHgEQgGgCgDgFIgIArQgBAEgEAAgAplgTIgJArQACADAFAAQAGAAADgGQAEgFADgPQADgMgCgGQgBgFgGAAQgFAAgDADgAqogRQgEAGgDAMQgCAPABAFQACAGAGAAQAEAAADgDIAJgrQgCgDgEAAQgGAAgEAFgAJQA0IgKgEIgJgGQgEgEgCgEIgEgJIgBgLIABgNIAEgKIAFgLIAHgJIAJgIQAHgEAQgGQAJgDAVgBIAOABQAIABAGADQABAAAAAAQABABAAAAQAAABAAABQAAAAAAABIgGAUQgBAEgEgBQgHgDgKAAQgGAAgEACQgFABgEAEIgGAIIgEAIQgBAGABAFQABAFACADQADADAEACQAEACAFAAQAKAAAJgDQAFgCgBAFIgCATQAAAEgEABIgPAEIgPABQgUgCgIgCgAHJA0IgJgFIgIgGQgEgEgCgEQgCgEgBgFIgBgLIABgMQABgGAIgOQAEgHALgKQAHgFAPgGQAIgCASgCQAJAAAPAEQAGACAEADIAIAGIAFAIIAEAJIABALIgBAJIgEAMIgFALQgKAMgGAFQgNAIgIADQgRAEgJAAQgSgCgHgCgAHpgRQgEAHgDALQgDAOACAGQACAGAEAAQAFAAAEgGQAEgGACgOQADgLgCgHQgBgFgFAAQgFAAgDAFgAkrA3QgHgBgGgDIgKgFQgEgCgDgEQgEgEgCgEIgDgJQgCgKACgMIAEgLIAGgLIAHgJIAJgHQAHgFAQgFQAMgEAOAAQALAAAKADQAIACAGAFQAGAEACAGQADAHgCAHQgBAIgFAGQgFAEgIAFQgIAEgMADQgMACgRAAIgHAAQAAAEACADQABADADACQAGADAMAAIANgBIAMgEQAFgCAAAFIgCASQAAAEgEABQgIACgJABQgKACgLAAIgPgBgAkagVQgFAEgDAJIADAAQAOAAAGgDQAFgCABgEQABgEgCgCQgDgCgFAAQgHAAgFAEgAtfA2QgMgDgIgDQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBIAIgcQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABABQAAAAAAAAQAGADAGACIAOABIAMgBQAGgBAFgCQAEgCAEgEIAHgIIg3AAQgEAAABgBIAFgdQABgEAEAAIA4AAIgEgIQgDgDgDgCQgEgDgFgBIgMgBQgHAAgHACQgHABgHADQAAAAgBABQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAQAAgBAAAAQAAAAgBgBQAAAAAAgBIADgcQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAIAWgGQAMgCALAAQAKAAAIABQAIABAHADIANAGIAKAIQAEAEADAGQADAGABAGQABAHAAAIQAAAIgCAIQgBAJgDAGQgDAHgEAHIgJAMIgLAKQgHAFgHAEIgPAGQgIACgIABIgSACQgMAAgLgCgAMHA1QgEAAABgEIATheQAAgDAEAAIAoAAQAEAAgBADIgGAbIALAAQALAAAIADQAJACAFAEQAGAFACAFQACAHgBAJQgCAJgFAHQgFAHgHAEQgIAFgJACQgJACgLAAgAM3AaIAFAAQAFAAADgCQADgCAAgFQABgFgBgCQgCgDgFAAIgFAAgAKwA1QgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAOhFIgXAAQgEAAABgEIAEgVQAAgDAEAAIBhAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgEAVQAAAEgEAAIgXAAIgOBFQgBAEgEAAgAFoA1QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAGgiIgRAAIgHAiQAAAEgEAAIgrAAQgEAAABgEIASheQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgGAhIARAAIAGghQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBeQAAAEgEAAgACcA1QgEAAABgEIATheQAAgDAEAAIA4AAQANAAALABQAKACAHAEQAHAEACAGQADAFgBAIQgBAFgDAFQgEAFgGADQAHACADAGQACAFgBAHQgCAIgFAGQgFAHgJAEQgIAEgMACQgMACgOAAgADOAbIAKAAQAFAAADgCQACgCABgDQABgEgCgBQgDgCgFAAIgJAAgADWgKIAIAAQAFAAADgBQADgCABgDQAAgDgCgCIgHgBIgJAAgABeA1QgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAHgkIgkAmIgEACIgjAAQgEAAABgEIASheQABgDAEAAIAlAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAkIAlgmIADgBIAjAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgTBeQAAAEgEAAgAg/A1QAAAAgBAAQgBAAAAgBQAAAAAAgBQgBgBAAgBIAOhFIgXAAQgDAAAAgEIAEgVQABgDAEAAIBfAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIgEAVQgBAEgEAAIgVAAIgOBFQAAAEgEAAgAiSA1QgEAAAAgDIgKgqIgIApQAAAEgEAAIgrAAQgEAAABgEIASheQABgDAEAAIArAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIgHAlIAXgmQABgCADAAIAuAAQABAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIghArIARAwQABAAAAABQAAAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAQgBAAAAAAg");
	this.shape.setTransform(88.6,9.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,177.2,18.5);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EA232D").s().p("AkvFYIAAgSIB+AAIAAl6Ih+AAIAAgTICqAAQAlgPAVgSQAVgSAYgjIACgDQAngbAjgoQAWgZAlg3IALgRQAJgMANgEQAPgFAMAFQARAFAIAPQAJAOgFAQIgsDbIBtAAQAVAAANAQQANAPgCAVIgsEgQgCARgNALQgNALgQAAIl2AAIAAAkgAieEhIF2AAQAKAAAHgGQAIgHABgKIAHgxIhCAAIAAgSIBFAAIALhIIg/AAIAAgTIBCAAIALhIIhCAAIAAgSIBEAAIAHgoQABgMgIgJQgGgJgOAAIiDAAIAxjxQAFgWgVgIQgSgGgLAPIgMARQgnA3gVAaQgkAqgoAcQgaAlgXAUQgXATgoARIgDABIgbAAgAkmEhIAAgSIA2AAIAAASg");
	this.shape.setTransform(30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,61,68.9);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.oim();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,174,174);


(lib.Символ40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ39();
	this.instance.parent = this;
	this.instance.setTransform(-284,65.6,1,1,0,0,0,284,65.6);

	this.instance_1 = new lib.Символ39();
	this.instance_1.parent = this;
	this.instance_1.setTransform(284,65.6,1,1,0,0,0,284,65.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-568,0,1136,131.3);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_4 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(4).call(this.frame_4).wait(1));

	// Слой 2
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(85.6,28,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(5));

	// Слой 1
	this.instance_1 = new lib.Символ34();
	this.instance_1.parent = this;
	this.instance_1.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.13,scaleY:1.13},4,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.instance_2 = new lib.Символ35();
	this.instance_2.parent = this;
	this.instance_2.setTransform(85.6,27.6,1,1,0,0,0,95.2,29.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(5));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.5,-0.5,172,57);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ33();
	this.instance.parent = this;
	this.instance.setTransform(81.3,28.5,1,1,0,0,0,51.8,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ31();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ32();
	this.instance_2.parent = this;
	this.instance_2.setTransform(84.5,27.5,1,1,0,0,0,86.5,26.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.5,-0.5,172,57);


(lib.Символ28 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ29();
	this.instance.parent = this;
	this.instance.setTransform(85.5,28,1,1,0,0,0,85.5,28);

	this.instance_1 = new lib.Символ30();
	this.instance_1.parent = this;
	this.instance_1.setTransform(81.5,28,1,1,0,0,0,85.5,28);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.5,-0.5,172,57);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ25();
	this.instance.parent = this;
	this.instance.setTransform(70.5,65,2.04,2.04,0,0,0,17.5,18.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ24();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ21();
	this.instance.parent = this;
	this.instance.setTransform(73.6,58.6,1.97,1.97,0,0,0,18.8,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ20();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ15();
	this.instance.parent = this;
	this.instance.setTransform(40.2,64.3,1.748,1.748,0,0,0,13.5,18.6);

	this.instance_1 = new lib.Символ14();
	this.instance_1.parent = this;
	this.instance_1.setTransform(89.1,63,1.748,1.748,0,0,0,15.6,18.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ18();
	this.instance_2.parent = this;
	this.instance_2.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ13();
	this.instance.parent = this;
	this.instance.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Символ11();
	this.instance.parent = this;
	this.instance.setTransform(64.6,63,1.05,1.05,0,0,0,30.5,34.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ10();
	this.instance_1.parent = this;
	this.instance_1.setTransform(65.5,65.5,1,1,0,0,0,65.5,65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,131,131);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции
	this.instance = new lib.Символ36();
	this.instance.parent = this;
	this.instance.setTransform(109.4,58.4,1.4,1.4,0,0,0,109.4,17.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.8,33.6,306.2,49.6);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Режим изоляции - копия
	this.instance = new lib.Символ40();
	this.instance.parent = this;
	this.instance.setTransform(458.9,84,0.529,0.529,0,0,0,284.1,65.7);
	this.instance.alpha = 0.309;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:284.2,regY:65.8,x:449.9},47).to({regX:284.1,regY:65.7,x:458.9},52).wait(1));

	// Режим изоляции
	this.instance_1 = new lib.Символ40();
	this.instance_1.parent = this;
	this.instance_1.setTransform(291,85.9,1,1,0,0,0,284,65.6);
	this.instance_1.alpha = 0.172;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:859.3},99).wait(1));

	// Слой 2
	this.instance_2 = new lib.back();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-15,51,0.601,0.601);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-561,20.3,1203.4,131.3);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_349 = function() {
		this.gotoAndPlay(0);
	}
	this.frame_384 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(349).call(this.frame_349).wait(35).call(this.frame_384).wait(36));

	// Слой 3
	this.instance = new lib.Символ38();
	this.instance.parent = this;
	this.instance.setTransform(73.2,89.5,0.654,0.654,0,0,0,231.2,14.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:23.8},9,cjs.Ease.get(1)).to({y:23.6},5,cjs.Ease.get(1)).wait(266).to({x:-30.2,y:86.4},0).to({y:17.6},9,cjs.Ease.get(1)).to({y:23.8},5,cjs.Ease.get(1)).wait(45).to({y:17.6},5).to({y:86.4,alpha:0},5,cjs.Ease.get(1)).to({alpha:1},1,cjs.Ease.get(1)).to({y:17.6},9,cjs.Ease.get(1)).to({y:23.8},5,cjs.Ease.get(1)).wait(45).to({y:17.6},5).to({y:86.4,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ37();
	this.instance_1.parent = this;
	this.instance_1.setTransform(71.1,64.9,1,1,0,0,0,154.3,16.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:-2.4},5,cjs.Ease.get(1)).to({y:0.7},4,cjs.Ease.get(1)).wait(271).to({x:-34,y:64.9},0).to({y:-7.2},9,cjs.Ease.get(1)).to({y:0.7},5,cjs.Ease.get(1)).wait(45).to({y:-7.2},5).to({y:68,alpha:0},5,cjs.Ease.get(1)).to({y:64.9,alpha:1},1,cjs.Ease.get(1)).to({y:-7.2},9,cjs.Ease.get(1)).to({y:0.7},5,cjs.Ease.get(1)).wait(45).to({y:-7.2},5).to({y:68,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// logo
	this.instance_2 = new lib.Символ5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(38.4,-160.5,1,1,0,0,0,75,46);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-53.9},5,cjs.Ease.get(1)).to({y:-62.3},4,cjs.Ease.get(1)).wait(271).to({x:-66.7,y:-137.2},0).to({x:-65.2,y:-53.2},9,cjs.Ease.get(1)).to({regY:46.1,y:-61.6},5,cjs.Ease.get(1)).wait(45).to({regY:46,y:-53.2},5,cjs.Ease.get(1)).to({regY:46.1,x:-66.7,y:-150.7,alpha:0},5,cjs.Ease.get(1)).wait(1).to({regY:46,y:-137.2,alpha:1},0).to({y:-57.9},9,cjs.Ease.get(1)).to({regY:46.1,y:-64.7},5,cjs.Ease.get(1)).wait(45).to({y:-56.8},5,cjs.Ease.get(1)).to({y:-150.7,alpha:0},5,cjs.Ease.get(1)).wait(1));

	// text_5
	this.instance_3 = new lib.Символ27();
	this.instance_3.parent = this;
	this.instance_3.setTransform(458.7,229.2,1.737,1.737,0,0,0,86.2,35.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(280).to({_off:false},0).to({regY:35,y:-31.4,alpha:1},9,cjs.Ease.get(1)).to({y:-14},5,cjs.Ease.get(1)).wait(42).to({y:-31.4},5,cjs.Ease.get(1)).to({y:72.8,alpha:0},5,cjs.Ease.get(1)).wait(4).to({regY:35.1,y:229.2},0).to({regY:35,y:-31.4,alpha:1},9,cjs.Ease.get(1)).to({y:-14},5,cjs.Ease.get(1)).wait(42).to({y:-31.4},5,cjs.Ease.get(1)).to({y:72.8,alpha:0},5,cjs.Ease.get(1)).wait(4));

	// btn
	this.instance_4 = new lib.Символ28();
	this.instance_4.parent = this;
	this.instance_4.setTransform(985.1,161.5,1.319,1.319,0,0,0,85.5,28);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;
	new cjs.ButtonHelper(this.instance_4, 0, 1, 2, false, new lib.Символ28(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(280).to({_off:false},0).to({y:-36.4,alpha:1},9,cjs.Ease.get(1)).to({y:-23.2},5,cjs.Ease.get(1)).wait(40).to({y:-36.4},5,cjs.Ease.get(1)).to({regY:27.9,y:42.6,alpha:0},5,cjs.Ease.get(1)).wait(6).to({regY:28,y:161.5},0).to({y:-36.4,alpha:1},9,cjs.Ease.get(1)).to({y:-23.2},5,cjs.Ease.get(1)).wait(40).to({y:-36.4},5,cjs.Ease.get(1)).to({regY:27.9,y:42.6,alpha:0},5,cjs.Ease.get(1)).wait(6));

	// text_4
	this.instance_5 = new lib.Символ26();
	this.instance_5.parent = this;
	this.instance_5.setTransform(823.9,156.9,2.016,2.016,0,0,0,56.9,7.4);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(214).to({_off:false},0).to({y:-44.6,alpha:1},10,cjs.Ease.get(1)).to({y:-24.5},5,cjs.Ease.get(1)).wait(40).to({y:-44.6},5,cjs.Ease.get(1)).to({y:519.8,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// pic_4
	this.instance_6 = new lib.Символ23();
	this.instance_6.parent = this;
	this.instance_6.setTransform(468.2,-20.4,0.562,0.562,0,0,0,65.5,65.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(214).to({_off:false},0).to({regY:65.5,rotation:360,y:-26},10,cjs.Ease.get(1)).to({regY:65.6,y:-20.4},5,cjs.Ease.get(1)).wait(10).to({regY:65.5,scaleX:0.5,scaleY:0.5},5,cjs.Ease.get(1)).to({regY:65.6,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:-26},5,cjs.Ease.get(1)).to({regY:65.6,y:131.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

	// text_3
	this.instance_7 = new lib.Символ22();
	this.instance_7.parent = this;
	this.instance_7.setTransform(824.9,173.8,1.956,1.956,0,0,0,67.8,9);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(144).to({_off:false},0).to({regY:8.9,y:-41.4,alpha:1},10,cjs.Ease.get(1)).to({regY:9,y:-21.7},5,cjs.Ease.get(1)).wait(40).to({regY:8.9,y:-41.4},5,cjs.Ease.get(1)).to({regY:9,y:506.5,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// pic_3
	this.instance_8 = new lib.Символ19();
	this.instance_8.parent = this;
	this.instance_8.setTransform(468.2,2.1,0.562,0.562,0,0,0,65.5,65.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(144).to({_off:false},0).to({regY:65.5,rotation:360,y:-26,alpha:1},10,cjs.Ease.get(1)).to({regY:65.6,y:-20.4},5,cjs.Ease.get(1)).wait(11).to({regY:65.5,scaleX:0.51,scaleY:0.51},4,cjs.Ease.get(1)).to({regY:65.6,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:-26},5,cjs.Ease.get(1)).to({regY:65.6,y:131.3,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(210));

	// text_2
	this.instance_9 = new lib.Символ16();
	this.instance_9.parent = this;
	this.instance_9.setTransform(823.9,277.8,1.774,1.774,0,0,0,69,21.9);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(74).to({_off:false},0).to({y:-41.5},10,cjs.Ease.get(1)).to({regY:22,y:-23.6},5,cjs.Ease.get(1)).wait(40).to({regY:21.9,y:-41.5},5,cjs.Ease.get(1)).to({y:472.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// pic_2
	this.instance_10 = new lib.Символ17();
	this.instance_10.parent = this;
	this.instance_10.setTransform(468.2,-3.5,0.562,0.562,0,0,0,65.5,65.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(74).to({_off:false},0).to({rotation:360,y:-26,alpha:1},10,cjs.Ease.get(1)).to({regY:65.6,y:-20.4},5,cjs.Ease.get(1)).wait(10).to({regX:65.4,regY:65.5,scaleX:0.49,scaleY:0.49},5,cjs.Ease.get(1)).to({regX:65.5,regY:65.6,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:-26},5,cjs.Ease.get(1)).to({y:136.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(280));

	// text_1
	this.instance_11 = new lib.Символ12();
	this.instance_11.parent = this;
	this.instance_11.setTransform(823.9,129.3,1.717,1.717,0,0,0,88.6,9.1);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(5).to({_off:false},0).to({regY:9.2,y:-42.3},9,cjs.Ease.get(1)).to({y:-25.1},5,cjs.Ease.get(1)).wait(40).to({y:-42.3},5,cjs.Ease.get(1)).to({y:472.9,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pic_1
	this.instance_12 = new lib.Символ9();
	this.instance_12.parent = this;
	this.instance_12.setTransform(468.2,-9.1,0.562,0.562,0,0,0,65.5,65.6);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(5).to({_off:false},0).to({regY:65.5,rotation:360,y:-26,alpha:1},9,cjs.Ease.get(1)).to({regY:65.6,y:-20.4},5,cjs.Ease.get(1)).wait(10).to({regY:65.5,scaleX:0.49,scaleY:0.49},5,cjs.Ease.get(1)).to({regY:65.6,scaleX:0.56,scaleY:0.56},5,cjs.Ease.get(1)).wait(20).to({regY:65.5,y:-26},5,cjs.Ease.get(1)).to({regY:65.6,y:142.6,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(350));

	// pricel
	this.instance_13 = new lib.Символ8();
	this.instance_13.parent = this;
	this.instance_13.setTransform(468.2,-9,0.591,0.591,0,0,0,87,87);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({rotation:360,y:-26.8,alpha:1},9,cjs.Ease.get(1)).to({y:-20.9},5,cjs.Ease.get(1)).wait(15).to({scaleX:0.63,scaleY:0.63,y:-20.8},5,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,y:-20.9},5,cjs.Ease.get(1)).wait(20).to({y:-26.8},5,cjs.Ease.get(1)).to({y:150.7,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:-9},0).to({rotation:720,y:-26.8,alpha:1},9,cjs.Ease.get(1)).to({y:-20.9},5,cjs.Ease.get(1)).wait(15).to({scaleX:0.63,scaleY:0.63,y:-20.8},5,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,y:-20.9},5,cjs.Ease.get(1)).wait(20).to({y:-26.8},5,cjs.Ease.get(1)).to({y:150.7,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:-9},0).to({rotation:1080,y:-26.8,alpha:1},9,cjs.Ease.get(1)).to({y:-20.9},5,cjs.Ease.get(1)).wait(15).to({scaleX:0.63,scaleY:0.63,y:-20.8},5,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,y:-20.9},5,cjs.Ease.get(1)).wait(20).to({y:-26.8},5,cjs.Ease.get(1)).to({y:150.7,alpha:0},5,cjs.Ease.get(1)).wait(1).to({y:-9},0).to({rotation:1440,y:-26.8,alpha:1},9,cjs.Ease.get(1)).to({y:-20.9},5,cjs.Ease.get(1)).wait(15).to({scaleX:0.63,scaleY:0.63,y:-20.8},5,cjs.Ease.get(1)).to({scaleX:0.59,scaleY:0.59,y:-20.9},5,cjs.Ease.get(1)).wait(20).to({y:-26.8},5,cjs.Ease.get(1)).to({y:150.7,alpha:0},5,cjs.Ease.get(1)).to({_off:true},1).wait(140));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.2,-172.9,602.8,271.4);


// stage content:



(lib._1440x1001 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
		
		var _this = this;
		
		
		
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		  function fl_MouseOverHandler_5()
		{
		    _this.an.gotoAndPlay(350);
			
		
		    
		}
		
		
		stage.canvas.onmouseout = fl_MouseOutHandler_23;
		
		  function fl_MouseOutHandler_23()
		{
		    _this.an.gotoAndPlay(404);
		
			
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// an
	this.an = new lib.Символ7();
	this.an.parent = this;
	this.an.setTransform(287.5,137.5,0.8,0.8,0,0,0,87,87);

	this.timeline.addTween(cjs.Tween.get(this.an).wait(1));

	// bg
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(215.3,278.3,1.94,1.94,0,0,0,120.2,199.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-536.3,-20.3,2334.8,254.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;