(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,610,310);


(lib.btn = function() {
	this.initialize(img.btn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,230,73);


(lib.inter1 = function() {
	this.initialize(img.inter1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.inter2 = function() {
	this.initialize(img.inter2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.inter3 = function() {
	this.initialize(img.inter3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,600,300);


(lib.logo2 = function() {
	this.initialize(img.logo2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,200,137);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Символ91 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E40034").s().p("ABSDZQgTgIgOgOQgbgcAAg2IAAjiQAAg2AbgcQAOgOATgGQAUgIAYABQAzAAAbAbQAOAPAFAUQAIAUAAAbIAADiQAAAbgIAUQgFAVgOAOQgOAOgSAIQgUAGgaAAQgYAAgUgGgABliXQgJAKAAAXIAADsQAAAYAJAJQAJAKAQAAQARAAAJgKQALgJAAgYIAAjsQAAgXgLgKQgJgJgRAAQgQAAgJAJgAOuDbIAAizIgYAAQgYAAgKAMQgLAOAAAeIgBBqIgGARIhFAAIAGgZIAChgQAAgiAJgYQAJgYAbgKQgWgKgMgXQgLgWAAgiIAAgjQAAgyAYgZQAMgMAUgHQATgGAbAAIBoAAIAAG1gANziRQgKALAAAXIAAAsQAAAaANAKQAJAKAUAAIAbAAIAAiGIghAAQgSAAgIAKgAK5DbIAAk8IhWE8IhFAAIAAm1IA+AAIAAEEIBFkEIBWAAIAAG1gAGmDbIAAi8IhOAAIAAC8IhGAAIAAm1IBGAAIAAC8IBOAAIAAi8IBGAAIAAG1gAhVDbIAAk5IgwE5IhBAAIgzk1IAAE1Ig8AAIAAm1IBgAAIAyE3IAwk3IBfAAIAAG1gAofDbIAAm1IBlAAQAzAAAbAbQAZAdAAA0IAAA4QAAA1gZAbQgOAOgTAIQgTAFgaAAIghAAIAACmgAnbgGIAhAAQAQgBAJgJQAJgJAAgXIAAhCQAAgYgJgJQgJgIgQAAIghAAgAqEDbIgMhQIhVAAIgLBQIg/AAIBHm1IBkAAIBGG1gAqaBQIghjdIghDdIBCAAgAvyDbIAAm1IC3AAIAAA/IhxAAIAAF2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ91, new cjs.Rectangle(-101,-22.3,202.1,44.7), null);


(lib.Символ53 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.btn();
	this.instance.parent = this;
	this.instance.setTransform(-115,-36.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115,-36.5,230,73);


(lib.Символ50 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AdLFvIAAgfIhxAAIAAAfIgtAAIAAhIIAPABQALAAAHgFQAIgFAAgRIAAjVICLAAIAADvIAXAAIAABIgAcCEKQAAARgEAMIA3AAIAAjIIgzAAgAPZFvIAAgfIhwAAIAAAfIgsAAIAAhIIAOABQALAAAHgFQAIgFAAgRIAAjVICLAAIAADvIAWAAIAABIgAOREKQAAARgDAMIA2AAIAAjIIgzAAgA0jFvIAAgfIhwAAIAAAfIgsAAIAAhIIAPABQAKAAAIgFQAHgFAAgRIAAjVICLAAIAADvIAWAAIAABIgA1rEKQAAARgDAMIA2AAIAAjIIgzAAgALRFOQgMgEgJgKQgRgRAAgjIAAiSQAAghARgTQAJgIAMgFQANgFAQAAQAgAAARASQAJAKAEANQAFANgBAQIAACSQABASgFANQgEAMgJAJQgIAKgNAEQgMAEgQAAQgQAAgNgEgALdBiQgGAHAAAPIAACXQAAAQAGAGQAHAGAKAAQALAAAGgGQAFgGAAgQIAAiXQAAgPgFgHQgGgFgLAAQgKAAgHAFgAg7FOQgMgEgJgKQgRgRAAgjIAAiSQAAghARgTQAJgIAMgFQAMgFAQAAQAgAAARASQAJAKAEANQAEANAAAQIAACSQAAASgEANQgEAMgJAJQgJAKgLAEQgMAEgRAAQgQAAgMgEgAgwBiQgFAHgBAPIAACXQABAQAFAGQAHAGAKAAQALAAAGgGQAGgGAAgQIAAiXQAAgPgGgHQgGgFgLAAQgKAAgHAFgAnCFOQgLgEgKgKQgQgRgBgjIAAiSQABghAQgTQAKgIALgFQANgFARAAQAgAAAQASQAJAKAFANQAEANAAAQIAACSQAAASgEANQgFAMgJAJQgIAKgMAEQgNAEgPAAQgRAAgNgEgAm1BiQgHAHAAAPIAACXQAAAQAHAGQAGAGALAAQAJAAAGgGQAHgGAAgQIAAiXQAAgPgHgHQgGgFgJAAQgLAAgGAFgApfFOQgNgEgIgKQgSgRABgjIAAiSQgBghASgTQAIgIANgFQAMgFAQAAQAgAAASASQAIAKAEANQAFANAAAQIAACSQAAASgFANQgEAMgIAJQgJAKgMAEQgNAEgQAAQgQAAgMgEgApUBiQgFAHAAAPIAACXQAAAQAFAGQAHAGAKAAQAKAAAHgGQAGgGAAgQIAAiXQAAgPgGgHQgHgFgKAAQgKAAgHAFgAtJFOQgLgEgJgKQgQgRAAgjIAAgHIApAAIAAAKQAAAQAGAGQAGAGALAAQALAAAGgHQAHgIAAgUIAAgzQgFAMgLAHQgKAGgPAAQgMAAgJgFQgJgDgGgJQgGgIgEgLQgCgNAAgPIAAg0QgBghASgTQAIgIANgFQAMgFAQAAQAhAAARASQAIAKAFANQAEANAAAQIAACQQAAARgEAOQgEAOgIAJQgRASgiAAQgRAAgMgEgAs9BjQgFAFAAAQIAAAyQAAAQAFAGQAHAGAKAAQALAAAGgGQAGgGAAgQIAAgyQAAgQgGgFQgGgGgLAAQgKAAgHAGgAzCFOQgMgEgIgKQgRgRAAgjIAAiSQAAghARgTQAIgIAMgFQANgFAQAAQAgAAASASQAJAKADANQAFANAAAQIAACSQAAASgFANQgDAMgJAJQgJAKgMAEQgNAEgQAAQgQAAgNgEgAy2BiQgFAHAAAPIAACXQAAAQAFAGQAHAGAKAAQALAAAGgGQAGgGAAgQIAAiXQAAgPgGgHQgGgFgLAAQgKAAgHAFgA5pFOQgMgEgJgKQgRgRAAgjIAAiSQAAghARgTQAJgIAMgFQAMgFARAAQAgAAARASQAJAKAEANQAFANAAAQIAACSQAAASgFANQgEAMgJAJQgIAKgNAEQgMAEgQAAQgRAAgMgEgA5dBiQgGAHAAAPIAACXQAAAQAGAGQAGAGALAAQAKAAAGgGQAGgGABgQIAAiXQgBgPgGgHQgGgFgKAAQgLAAgGAFgA8HFOQgMgEgJgKQgRgRAAgjIAAiSQAAghARgTQAJgIAMgFQANgFAQAAQAgAAARASQAJAKAEANQAEANAAAQIAACSQAAASgEANQgEAMgJAJQgIAKgMAEQgNAEgQAAQgQAAgNgEgA77BiQgGAHAAAPIAACXQAAAQAGAGQAGAGALAAQAKAAAGgGQAGgGAAgQIAAiXQAAgPgGgHQgGgFgKAAQgLAAgGAFgA/vFOQgMgEgJgKQgRgRAAgjIAAiSQAAghARgTQAJgIAMgFQAMgFARAAQAgAAARASQAJAKAEANQAFANgBAQIAACSQABASgFANQgEAMgJAJQgJAKgMAEQgMAEgQAAQgRAAgMgEgA/jBiQgGAHAAAPIAACXQAAAQAGAGQAHAGAKAAQAKAAAGgGQAHgGgBgQIAAiXQABgPgHgHQgGgFgKAAQgKAAgHAFgEglnAFOQgMgEgJgKQgQgRAAgjIAAiSQAAghAQgTQAJgIAMgFQAMgFAQAAQAhAAAQASQAJAKAEANQADANAAAQIAAAcIgpAAIAAgeQAAgPgGgHQgGgFgLAAQgKAAgHAFQgFAHAAAPIAACXQAAAQAFAGQAHAFAKABQALgBAGgFQAGgGAAgQIAAgoIApAAIAAAlQAAASgDANQgEAMgJAJQgIAKgNAEQgMAEgQAAQgQAAgMgEgEAlkAFQIAAjKIgfDKIgpAAIghjGIAADGIgmAAIAAkYIA8AAIAhDHIAejHIA9AAIAAEYgEAiJAFQIAAhzIgPAAQgQAAgHAIQgGAJAAATIgBBEIgDALIgtAAIAEgQIABg+QAAgVAGgQQAGgQARgGQgOgHgIgPQgGgOAAgVIAAgWQAAggAOgRQAJgIAMgEQAMgDASAAIBBAAIAAEYgEAhiABnQgFAGAAAPIAAAcQAAARAHAGQAHAHAMAAIASAAIAAhXIgVAAQgMAAgGAIgAfnFQIAAh5IgxAAIAAB5IgsAAIAAkYIAsAAIAAB3IAxAAIAAh3IAtAAIAAEYgAY2FQIAAjKIgeDKIgqAAIggjGIAADGIgnAAIAAkYIA9AAIAhDHIAejHIA9AAIAAEYgAVbFQIAAkYIAsAAIAAEYgATDFQIAAkYIAsAAIAABoIAVAAQAhAAARASQAPASAAAiIAAAkQAAAjgPARQgJAIgMAFQgNAEgQABgATvEnIAVAAQAKABAGgGQAGgFAAgQIAAgqQAAgPgGgGQgGgGgKABIgVAAgAR2FQIAAh5IgxAAIAAB5IgtAAIAAkYIAtAAIAAB3IAxAAIAAh3IAtAAIAAEYgAJqFQIgkhvIgkBvIgpAAIAxiQIguiIIAuAAIAhBmIAihmIApAAIguCIIAxCQgAG3FQIAAkYIAsAAIAAEYgAEfFQIAAkYIAsAAIAABoIAVAAQAhAAAQASQAQASABAiIAAAkQgBAjgQARQgIAIgMAFQgNAEgQABgAFLEnIAVAAQAKABAGgGQAFgFAAgQIAAgqQAAgPgFgGQgGgGgKABIgVAAgAB9FQIAAkYIBDAAQARAAAMADQAMAEAIAIQAIAJAEAMQADAMAAAQIAAAKQAAAWgGAOQgHAOgPAGQAJAEAHAFQAGAGAEAIQAHAPAAAWIAAAXQAAAhgRARQgIAIgNAEQgMAEgRABgACpEnIAZAAQALAAAGgFQAGgHAAgPIAAgYQAAgUgGgHQgHgHgQAAIgTAAgACpCpIARAAQANABAGgHQAIgGgBgRIAAgQQAAgPgFgGQgFgIgLAAIgWAAgAiqFQIAAjxIgyAAIAADxIgsAAIAAkYICLAAIAAEYgArMFQIAAgrIArAAIAAArgAvLFQIAAjWIgiAAIAAgfQANAAAIgDQAIgDAGgFQAFgEADgHIAFgNIAeAAIAAEYgA90FQIAAgrIArAAIAAArgEghzAFQIAAjWIgiAAIAAgfQAOAAAIgDQAIgDAFgFQAFgEADgHIAGgNIAeAAIAAEYgArMC3IAAgqIArAAIAAAqgA90C3IAAgqIArAAIAAAqgAaRgzIAAghIhwAAIAAAhIgsAAIAAhIIAPAAQAKAAAIgFQAHgGAAgQIAAjWICLAAIAADxIAWAAIAABIgAZJiZQAAARgDANIA2AAIAAjJIgzAAgAxqgzIAAghIhxAAIAAAhIgsAAIAAhIIAPAAQAKAAAIgFQAHgGABgQIAAjWICKAAIAADxIAXAAIAABIgAyyiZQgBARgDANIA2AAIAAjJIgyAAgAMshVQgMgEgJgKQgRgSgBghIAAiTQABghARgSQAJgKAMgEQAMgFAQABQAhgBARATQAIAIAFANQAEANAAARIAACTQAAAQgEANQgFAOgIAIQgJAKgMAEQgMAFgRgBQgQABgMgFgAM3lAQgFAGgBAPIAACXQABAQAFAFQAHAHAKAAQALAAAGgHQAGgFAAgQIAAiXQAAgPgGgGQgGgHgLAAQgKAAgHAHgAB8hVQgMgEgJgKQgRgSAAghIAAiTQAAghARgSQAJgKAMgEQANgFAPABQAhgBASATQAIAIAEANQAEANABARIAACTQgBAQgEANQgEAOgIAIQgKAKgLAEQgNAFgRgBQgPABgNgFgACIlAQgGAGAAAPIAACXQAAAQAGAFQAHAHAJAAQAMAAAFgHQAHgFgBgQIAAiXQABgPgHgGQgFgHgMAAQgJAAgHAHgAkJhVQgMgEgJgKQgRgSAAghIAAiTQAAghARgSQAJgKAMgEQAMgFARABQAggBARATQAJAIAEANQAFANAAARIAACTQAAAQgFANQgEAOgJAIQgJAKgMAEQgMAFgQgBQgRABgMgFgAj9lAQgGAGAAAPIAACXQAAAQAGAFQAGAHALAAQAKAAAGgHQAHgFAAgQIAAiXQAAgPgHgGQgGgHgKAAQgLAAgGAHgAmnhVQgMgEgJgKQgRgSAAghIAAiTQAAghARgSQAJgKAMgEQANgFAQABQAggBARATQAJAIAEANQAEANAAARIAACTQAAAQgEANQgEAOgJAIQgIAKgMAEQgNAFgQgBQgQABgNgFgAmblAQgGAGAAAPIAACXQAAAQAGAFQAHAHAKAAQAKAAAGgHQAGgFAAgQIAAiXQAAgPgGgGQgGgHgKAAQgKAAgHAHgAwJhVQgMgEgJgKQgRgSAAghIAAiTQAAghARgSQAJgKAMgEQANgFAQABQAggBARATQAJAIAEANQAFANgBARIAACTQABAQgFANQgEAOgJAIQgIAKgNAEQgMAFgQgBQgQABgNgFgAv9lAQgGAGAAAPIAACXQAAAQAGAFQAHAHAKAAQAKAAAHgHQAFgFAAgQIAAiXQAAgPgFgGQgHgHgKAAQgKAAgHAHgA2whVQgMgEgKgKQgRgSAAghIAAiTQAAghARgSQAKgKAMgEQAMgFARABQAfgBARATQAJAIAFANQAEANAAARIAACTQAAAQgEANQgFAOgJAIQgIAKgMAEQgMAFgQgBQgRABgMgFgA2klAQgHAGAAAPIAACXQAAAQAHAFQAGAHALAAQAKAAAGgHQAGgFAAgQIAAiXQAAgPgGgGQgGgHgKAAQgLAAgGAHgA5PhVQgMgEgIgKQgSgSABghIAAiTQgBghASgSQAIgKAMgEQANgFAQABQAggBASATQAIAIAEANQAFANAAARIAACTQAAAQgFANQgEAOgIAIQgJAKgMAEQgNAFgQgBQgQABgNgFgA5DlAQgFAGAAAPIAACXQAAAQAFAFQAHAHAKAAQALAAAFgHQAHgFAAgQIAAiXQAAgPgHgGQgFgHgLAAQgKAAgHAHgA84hVQgMgEgIgKQgRgSAAghIAAgIIAqAAIAAAKQAAAQAGAFQAGAHALAAQAMAAAFgIQAHgGAAgVIAAgzQgGANgKAGQgKAGgPAAQgMAAgJgEQgJgFgGgIQgGgIgEgMQgCgMAAgPIAAg0QAAghARgSQAIgKANgEQAMgFAQABQAhgBARATQAIAIAFANQAEANAAARIAACQQAAARgEAOQgEAOgIAJQgRASgiAAQgQABgNgFgA8slAQgFAGAAAPIAAAzQAAAOAFAHQAHAGAKAAQALAAAGgGQAGgHAAgOIAAgzQAAgPgGgGQgGgGgLgBQgKABgHAGgA/UhVQgMgEgKgKQgRgSAAghIAAiTQAAghARgSQAKgKAMgEQAMgFARABQAfgBARATQAJAIAFANQAEANAAARIAACTQAAAQgEANQgFAOgJAIQgIAKgMAEQgMAFgQgBQgRABgMgFgA/JlAQgFAGgBAPIAACXQABAQAFAFQAHAHALAAQAJAAAHgHQAGgFAAgQIAAiXQAAgPgGgGQgHgHgJAAQgLAAgHAHgEgivgBVQgMgEgJgKQgQgSAAghIAAiTQAAghAQgSQAJgKAMgEQAMgFARABQAggBAQATQAJAIAEANQAEANAAARIAAAcIgqAAIAAgeQAAgPgFgGQgHgHgKAAQgKAAgHAHQgGAGAAAPIAACXQAAAQAGAFQAHAHAKgBQAKABAHgHQAFgFAAgQIAAgoIAqAAIAAAmQAAAQgEANQgEAOgJAIQgIAKgMAEQgMAFgQgBQgRABgMgFgEAiqgBUIAAjIIgeDIIgqAAIggjGIAADGIgnAAIAAkYIA+AAIAgDHIAejHIA+AAIAAEYgAfQhUIAAhyIgQAAQgPABgGAHQgHAIAAAUIgBBEIgEAKIgsAAIAEgQIABg8QAAgXAGgPQAGgPARgHQgPgHgGgOQgIgOABgWIAAgWQAAghAPgPQAIgIAMgFQAMgEARAAIBDAAIAAEYgAepk9QgFAHAAAQIAAAbQAAAQAIAHQAGAGANAAIARAAIAAhWIgWAAQgLABgGAGgAcvhUIAAh3IgzAAIAAB3IgsAAIAAkYIAsAAIAAB4IAzAAIAAh4IAtAAIAAEYgAV9hUIAAjIIgfDIIgpAAIggjGIAADGIgnAAIAAkYIA9AAIAgDHIAejHIA+AAIAAEYgASnhUIAAjKIg3DKIgtAAIAAkYIAnAAIAACoIAtioIA3AAIAAEYgAP2hUIAAhrIgLACIgMABQgRAAgMgFQgMgEgJgJQgQgSAAgiIAAhqIAsAAIAABsQAAAQAHAFQAFAHALAAQAKAAAGgGQAFgFABgNIAAhwIAsAAIAAEYgAJuhUIAAkYIB0AAIAAAoIhJAAIAABCIAWAAQAhgBAQATQAQARAAAiIAAAkQAAAigQASQgJAIgMAFQgMAEgQAAgAKZh7IAWAAQAKAAAGgGQAFgGAAgPIAAgqQAAgPgFgGQgGgFgKgBIgWAAgAIthUIgHgzIg2AAIgIAzIgpAAIAtkYIBBAAIAsEYgAIgitIgWiNIgVCNIArAAgAE2hUIAAkYIBAAAQAiAAAQASQAQASAAAiIAAAkQAAAigQARQgJAKgMAEQgMAEgRAAIgUAAIAABpgAFijlIAUAAQAKABAHgHQAFgFAAgPIAAgqQAAgPgFgGQgHgGgKAAIgUAAgAAOhUIAAjwIgyAAIAADwIgrAAIAAkYICJAAIAAEYgAoUhUIAAgqIArAAIAAAqgAqxhUIAAgiQAAgVAGgPQAGgPAKgOIAqgwQAKgNAHgPQAFgQAAgTQAAgUgFgGQgHgGgKgBQgKAAgHAHQgGAGAAAPIAAAeIgpAAIAAgcQAAghAQgSQAJgKAMgEQAMgFAQABQAhgBAQATQAJAIAEANQAEANAAARQAAAXgHATQgIATgJAPQgLAPgMANIgWAYQgJAKgGAMQgFALACANIBTAAIAAAngAtQhUIAAgiQABgVAGgPQAGgPAKgOIAqgwQAKgNAGgPQAHgQAAgTQAAgUgHgGQgFgGgLgBQgLAAgFAHQgHAGAAAPIAAAeIgqAAIAAgcQAAghARgSQAIgKAMgEQANgFAQABQAggBARATQAJAIADANQAFANAAARQAAAXgIATQgHATgKAPQgKAPgMANIgWAYQgKAKgFAMQgFALABANIBTAAIAAAngA67hUIAAgqIArAAIAAAqgAoUjsIAAgqIArAAIAAAqgA67jsIAAgqIArAAIAAAqg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ50, new cjs.Rectangle(-244.5,-36.7,489.1,73.5), null);


(lib.Символ49 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AffCeIAAghIhwAAIAAAhIgtAAIAAhIIAPAAQALAAAHgFQAIgFAAgRIAAjVICLAAIAADwIAWAAIAABIgAeXA4QAAASgEAMIA3AAIAAjHIgzAAgAn1CeIAAghIhxAAIAAAhIgsAAIAAhIIAPAAQAKAAAIgFQAHgFAAgRIAAjVICLAAIAADwIAXAAIAABIgAo+A4QAAASgDAMIA2AAIAAjHIgzAAgAbXB8QgMgFgJgIQgRgTAAgiIAAiQQAAgjARgSQAJgJAMgEQAMgEAQgBQAhABARARQAJAJAEANQAEAOAAARIAACQQAAARgEANQgEANgJAKQgJAIgMAFQgMAEgRABQgQgBgMgEgAbjhvQgGAHAAAPIAACWQAAAPAGAHQAGAGAKAAQALAAAGgGQAGgHAAgPIAAiWQAAgPgGgHQgGgFgLgBQgKABgGAFgAywB8QgMgFgIgIQgSgTAAgiIAAiQQAAgjASgSQAIgJAMgEQANgEAQgBQAgABASARQAIAJAEANQAFAOAAARIAACQQAAARgFANQgEANgIAKQgJAIgMAFQgNAEgQABQgQgBgNgEgAykhvQgGAHAAAPIAACWQAAAPAGAHQAHAGAKAAQALAAAGgGQAGgHAAgPIAAiWQAAgPgGgHQgGgFgLgBQgKABgHAFgEghCAB8QgMgFgIgIQgRgTAAgiIAAiQQAAgjARgSQAIgJAMgEQANgEAQgBQAgABARARQAIAJAEANQAEAOAAARIAAAbIgpAAIAAgeQAAgPgGgHQgGgFgLgBQgKABgHAFQgGAHAAAPIAACWQAAAPAGAHQAHAFAKAAQALAAAGgFQAGgHAAgPIAAgoIApAAIAAAlQAAARgEANQgEANgIAKQgIAIgNAFQgMAEgQABQgQgBgNgEgEAl+AB9IgrhvIgNAZIAABWIgsAAIAAhWIgOgZIgrBvIgtAAIA9iaIg9h9IAsAAIA6B6IAAh6IAsAAIAAB6IA6h6IArAAIg9B9IA9CagEAiAAB9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIAsEXgEAhyAAlIgViNIgVCNIAqAAgAYfB9IAAkXIBBAAQAhAAAQASQAQASAAAiIAAAkQAAAigQARQgIAIgMAFQgNAEgQAAIgVAAIAABpgAZLgTIAVAAQAKAAAGgFQAFgGAAgPIAAgqQAAgPgFgGQgGgGgKABIgVAAgAXSB9IAAjuIgyAAIAADuIgsAAIAAkXICLAAIAAEXgAT2B9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIAsEXgAToAlIgViNIgVCNIAqAAgAQmB9IAAjuIguAAIAAgpICIAAIAAApIguAAIAADugAO4B9IAAh4IgyAAIAAB4IgsAAIAAkXIAsAAIAAB5IAyAAIAAh5IAtAAIAAEXgALIB9IAAkXIB4AAIAAApIhMAAIAABNIA8AAIAAAoIg8AAIAABSIBMAAIAAAngAJ+B9IAAjIIgeDIIgqAAIggjFIAADFIgnAAIAAkXIA9AAIAhDGIAejGIA9AAIAAEXgAGvB9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIAsEXgAGhAlIgViNIgVCNIAqAAgADfB9IAAjuIguAAIAAgpICIAAIAAApIguAAIAADugAAnB9IAAkXIBBAAQAhAAARASQAQASAAAiIAAAkQAAAigQARQgJAIgMAFQgMAEgRAAIgVAAIAABpgABTgTIAVAAQAKAAAGgFQAGgGAAgPIAAgqQAAgPgGgGQgGgGgKABIgVAAgAgYB9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIArEXgAgmAlIgViNIgVCNIAqAAgAjGB9IAAjuIgyAAIAADuIgsAAIAAkXICLAAIAAEXgAm2B9IAAkXIB4AAIAAApIhMAAIAABNIA8AAIAAAoIg8AAIAABSIBMAAIAAAngAsMB9IAAkXIAsAAIAAEXgAukB9IAAkXIAsAAIAABpIAVAAQAhABAQARQAQASAAAhIAAAlQAAAhgQASQgIAJgMAEQgNAFgQgBgAt4BWIAVAAQAKgBAGgFQAFgGAAgPIAAgqQAAgPgFgFQgGgGgKAAIgVAAgAwSB9IAAjuIguAAIAAgpICIAAIAAApIguAAIAADugA1uB9IAAkXIB1AAIAAApIhJAAIAABAIAVAAQAhABARARQAQASAAAhIAAAlQAAAhgQASQgJAJgMAEQgMAFgRgBgA1CBWIAVAAQAKgBAGgFQAGgGAAgPIAAgqQAAgPgGgFQgGgGgKAAIgVAAgA2uB9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIAsEXgA28AlIgViNIgVCNIAqAAgA6mB9IAAkXIBBAAQAhAAARASQAQASAAAiIAAAkQAAAigQARQgJAIgMAFQgMAEgRAAIgVAAIAABpgA56gTIAVAAQAKAAAGgFQAGgGAAgPIAAgqQAAgPgGgGQgGgGgKABIgVAAgA8wB9IAAkXIAsAAIAAEXgA/IB9IAAkXIAsAAIAABpIAVAAQAhABARARQAQASAAAhIAAAlQAAAhgQASQgJAJgMAEQgMAFgRgBgA+cBWIAVAAQAKgBAGgFQAGgGAAgPIAAgqQAAgPgGgFQgGgGgKAAIgVAAgEgijAB9IgIgyIg2AAIgHAyIgpAAIAtkXIBBAAIAsEXgEgixAAlIgViNIgVCNIAqAAgEglRAB9IAAhrIgLADIgNAAQgQAAgMgFQgMgEgJgJQgQgRAAgjIAAhpIAsAAIAABsQAAAPAGAHQAGAGALAAQAKAAAGgFQAFgGABgNIAAhwIAsAAIAAEXg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ49, new cjs.Rectangle(-247.5,-15.7,495.1,31.5), null);


(lib.Символ47 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E40034").ss(2,1,1).p("EguFgWpMBcLAAAMAAAAtTMhcLAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ47, new cjs.Rectangle(-296,-146,592,292), null);


(lib.Символ22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgyPAaaMAAAg0zMBkfAAAMAAAA0zg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ22, new cjs.Rectangle(-321.6,-169,643.2,338.1), null);


(lib.Символ19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AL5DTIAAgRIhAAAIAAiaIAYAAIAACEIAcAAIAAiEIAZAAIAACEIAMAAIAAAngAO0DBQgHgDgEgFQgKgKAAgSIAAgdIgOAAIAABCIgZAAIAAiaIAZAAIAABCIAOAAIAAgdQAAgTAKgJQAEgFAHgDQAHgDAJABQASgBAJALQAFAFACAGQACAIAAAJIAABQQAAAJgCAIQgCAGgFAFQgFAFgGADQgHADgJgBQgJABgHgDgAO7BAQgEADAAAJIAABSQAAAJAEADQADAEAGAAQAFAAAEgEQADgDAAgJIAAhSQAAgJgDgDQgEgDgFgBQgGABgDADgAIdDBQgGgDgFgFQgJgKAAgSIAAgTIAXAAIAAAUQAAAJADADQAEAEAFAAQAGAAADgEQAEgDAAgKIAAgNQAAgKgEgFQgEgFgIAAIgEAAIAAgVIAGAAQAGAAAEgEQAEgDAAgKIAAgIQAAgLgEgDQgDgDgGgBQgFABgEADQgDADAAAJIAAAQIgXAAIAAgPQAAgTAJgJQAFgFAGgDQAHgDAJABQASgBAJALQAFAFACAGQACAIAAAJIAAAEQAAAZgRAHQAJAEAEAHQAEAJAAAMIAAAMQAAAJgCAIQgCAGgFAFQgFAFgGADQgHADgJgBQgJABgHgDgAghDBQgGgDgFgFQgJgKAAgSIAAgdIgPAAIAABCIgYAAIAAiaIAYAAIAABCIAPAAIAAgdQAAgTAJgJQAFgFAGgDQAHgDAJABQARgBAJALQAFAFACAGQADAIAAAJIAABQQAAAJgDAIQgCAGgFAFQgEAFgGADQgHADgJgBQgJABgHgDgAgaBAQgDADAAAJIAABSQAAAJADADQAEAEAFAAQAGAAADgEQAEgDAAgJIAAhSQAAgJgEgDQgDgDgGgBQgFABgEADgAlfDBQgGgDgFgFQgJgKAAgSIAAhQQAAgTAJgJQAFgFAGgDQAHgDAJABQASgBAJALQAEAFACAGQADAIAAAJIAAAPIgXAAIAAgQQAAgJgDgDQgEgDgGgBQgFABgEADQgDADAAAJIAABSQAAAJADADQAEAEAFAAQAGAAAEgEQADgDAAgJIAAgVIAXAAIAAAUQAAAJgDAIQgCAGgEAFQgFAFgHADQgGADgJgBQgJABgHgDgAqtDBQgGgDgFgFQgJgKAAgSIAAhQQAAgTAJgJQAFgFAGgDQAHgDAJABQASgBAJALQAFAFACAGQADAIAAAJIAABQQAAAJgDAIQgCAGgFAFQgEAFgHADQgHADgJgBQgJABgHgDgAqmBAQgDADAAAJIAABSQAAAJADADQAEAEAFAAQAGAAADgEQAEgDAAgJIAAhSQAAgJgEgDQgDgDgGgBQgFABgEADgAE5DCIAAgWIAIAAQAGAAAEgDQAEgCAAgJIAAh2IBNAAIAACaIgZAAIAAiEIgcAAIAABeQAAALgDAIQgCAHgFAEQgFAFgGACQgHABgGAAgANRDCIAAhvIgeBvIgZAAIAAiaIAWAAIAABcIAZhcIAeAAIAACagAKWDCIgEgcIgeAAIgEAcIgWAAIAYiaIAkAAIAYCagAKOCRIgLhNIgMBNIAXAAgAHkDCIAAhvIgeBvIgZAAIAAiaIAWAAIAABcIAYhcIAfAAIAACagAEcDCIgEgcIgeAAIgEAcIgWAAIAZiaIAjAAIAZCagAEVCRIgMhNIgMBNIAYAAgACXDCIAAiaIBBAAIAAAWIgpAAIAAArIAhAAIAAAWIghAAIAAAtIApAAIAAAWgABEDCIAAiaIAkAAQASAAAJAKQAJAJAAATIAAAUQAAASgJALQgFAFgGACQgHACgJAAIgMAAIAAA6gABcByIAMAAQAFABAEgEQADgDAAgIIAAgXQAAgJgDgDQgEgDgFAAIgMAAgAi7DCIAAgWIAOAAIAFgDQACgCAAgDIABgIIgjh0IAYAAIAbBaIAWhaIAYAAIgfByQgFAQgEAHQgEAJgFAEQgFAEgFAAgAjlDCIgXg+IgIAPIAAAvIgYAAIAAiaIAYAAIAABDIAghDIAYAAIgiBFIAiBVgAnBDCIAAiaIBCAAIAAAWIgqAAIAAArIAhAAIAAAWIghAAIAAAtIAqAAIAAAWgAnrDCIAAg7IgNACQgJAAgHgDQgGgCgFgFQgJgLAAgSIAAg6IAYAAIAAA8QAAAHAEAEQADAEAGgBQAFAAAEgCQADgEAAgGIAAg+IAYAAIAACagAppDCIAAiaIAkAAQASAAAJAKQAJAJAAATIAAAUQAAASgJALQgFAFgGACQgHACgJAAIgMAAIAAA6gApRByIAMAAQAFABAEgEQADgDAAgIIAAgXQAAgJgDgDQgEgDgFAAIgMAAgAsYDCIAAiaIAkAAQAKAAAHACQAGACAEAFQAFAFACAGQACAGAAAKIAAAFQAAAMgEAIQgDAHgJAEQAFACAEADQADADACAEQAEAIAAANIAAANQAAARgJAJQgEAFgHADQgHACgJAAgAsACsIAOAAQAGAAADgEQADgCAAgJIAAgOQAAgKgDgEQgEgFgIAAIgLAAgAsABnIAJAAQAHAAAEgEQAEgDAAgKIAAgIQAAgIgDgEQgDgEgGAAIgMAAgAtVDCIAAiEIgZAAIAAgWIBLAAIAAAWIgZAAIAACEgAuwDCIAAhvIgfBvIgYAAIAAiaIAVAAIAABcIAZhcIAeAAIAACagAuRgmIAAgRIg+AAIAAARIgYAAIAAgnIAIAAQAGAAAEgCQAEgEAAgJIAAh1IBMAAIAACEIANAAIAAAngAu5heQAAALgCAGIAeAAIAAhuIgcAAgAi+g4QgHgDgFgFQgJgJAAgTIAAhQQAAgTAJgKQAFgEAHgDQAHgCAIgBQASAAAJAKQAFAFACAHQACAIAAAJIAAAPIgWAAIAAgRQAAgIgEgDQgDgEgGAAQgGAAgDAEQgDADAAAIIAABTQAAAJADAEQADACAGAAQAGAAADgCQAEgEAAgJIAAgVIAWAAIAAAUQAAAJgCAHQgCAIgFAEQgEAFgHADQgHACgJAAQgIAAgHgCgAnBg4QgHgDgEgFQgJgJAAgTIAAgUIAWAAIAAAVQAAAJAEAEQADADAGAAQAGAAADgDQADgFAAgKIAAgMQAAgLgDgEQgEgFgIABIgEAAIAAgWIAFAAQAHAAAEgEQADgDAAgKIAAgIQAAgKgDgEQgDgEgGAAQgGAAgDAEQgEADAAAIIAAARIgWAAIAAgPQAAgTAJgKQAEgEAHgDQAHgCAJgBQARAAAJAKQAFAFACAHQADAIAAAJIAAAEQAAAZgRAGQAJAFAEAIQAEAIAAAMIAAAMQAAAJgDAHQgCAIgFAEQgEAFgHADQgGACgJAAQgJAAgHgCgAt1g3IAAgWIAIAAQAGAAAEgCQAEgEAAgJIAAh1IBMAAIAACaIgYAAIAAiEIgcAAIAABdQAAAMgDAHQgCAIgFAEQgFAFgGABQgHACgHAAgAhGg3IgEgcIgeAAIgEAcIgWAAIAZiaIAjAAIAZCagAhNhoIgMhOIgMBOIAYAAgAkhg3IAAiaIBCAAIAAAWIgpAAIAAArIAhAAIAAAWIghAAIAAAtIApAAIAAAWgAlKg3IAAhCIgcAAIAABCIgYAAIAAiaIAYAAIAABCIAcAAIAAhCIAYAAIAACagAn6g3IAAhvIgfBvIgYAAIAAiaIAVAAIAABcIAZhcIAeAAIAACagAqHg3IAAiaIBAAAIAAAWIgoAAIAAAkIAMAAQASAAAJAKQAJAJAAATIAAAUQAAASgJAKQgFAFgGACQgHADgJAAgApvhNIAMAAQAFAAAEgDQADgDAAgJIAAgWQAAgJgDgDQgEgDgFAAIgMAAgArSg3IAAg/IgJAAQgIAAgEAFQgEAEAAALIAAAlIgCAGIgYAAIACgJIAAghQAAgNAEgIQADgIAJgEQgIgEgEgIQgDgHAAgNIAAgMQAAgSAIgIQAEgEAHgDQAHgCAJAAIAlAAIAACagArni3QgEADAAAJIAAAPQAAAJAFAEQADADAHABIAKAAIAAgwIgMAAQgGAAgDAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ19, new cjs.Rectangle(-100,-21.1,200.1,42.3), null);


(lib.Символ18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E40034").s().p("AIQCKQgMgEgIgKQgRgSAAghIAAiRQAAghARgSQAIgKAMgEQANgFAQABQAggBARATQAIAIAEANQAEANAAARIAAAbIgqAAIAAgeQABgPgHgFQgFgHgLAAQgKAAgGAHQgHAFAAAPIAACXQAAAPAHAFQAGAHAKAAQALAAAFgHQAHgFgBgPIAAgpIAqAAIAAAmQAAARgEANQgEANgIAIQgIAKgMAEQgMAFgRgBQgQABgNgFgAF0CKQgMgEgIgKQgSgSABghIAAiRQgBghASgSQAIgKAMgEQAMgFARABQAggBASATQAIAIAEANQAEANAAARIAACRQAAARgEANQgEANgIAIQgKAKgLAEQgNAFgQgBQgRABgMgFgAGAhfQgGAFAAAPIAACXQAAAPAGAFQAHAIAKgBQAKABAGgIQAHgFAAgPIAAiXQAAgPgHgFQgGgHgKAAQgKAAgHAHgAjQCKQgMgEgIgKQgSgSAAghIAAiRQAAghASgSQAIgKAMgEQANgFAPABQAhgBARATQAJAIAEANQAEANABARIAACRQgBARgEANQgEANgJAIQgJAKgMAEQgNAFgQgBQgPABgNgFgAjEhfQgFAFgBAPIAACXQABAPAFAFQAGAIAKgBQALABAGgIQAHgFAAgPIAAiXQAAgPgHgFQgGgHgLAAQgKAAgGAHgApECKQgMgEgHgKQgRgSAAghIAAgjIApAAIAAAmQAAAPAGAFQAGAIAKgBQALABAGgIQAGgGAAgTIAAgWQAAgTgGgIQgHgIgPAAIgHAAIAAgnIAJAAQANgBAGgFQAHgGAAgSIAAgPQAAgTgGgGQgGgHgLAAQgKAAgGAHQgGAFAAAPIAAAeIgpAAIAAgbQAAghARgSQAHgKAMgEQANgFAPABQAhgBARATQAIAIAEANQAEANAAARIAAAHQAAAugeAMQAQAHAIAOQAGAPAAAVIAAAXQAAARgEANQgEANgIAIQgJAKgMAEQgMAFgRgBQgPABgNgFgArgCKQgMgEgIgKQgRgSgBghIAAiRQABghARgSQAIgKAMgEQAMgFARABQAggBASATQAIAIAEANQAFANgBARIAACRQABARgFANQgEANgIAIQgJAKgNAEQgLAFgRgBQgRABgMgFgArUhfQgFAFgBAPIAACXQABAPAFAFQAHAIAKgBQALABAGgIQAFgFAAgPIAAiXQAAgPgFgFQgGgHgLAAQgKAAgHAHgAN+CMIAAjJIg3DJIgtAAIAAkXIAnAAIAACnIAtinIA2AAIAAEXgAKrCMIAAjvIgtAAIAAgoICHAAIAAAoIgtAAIAADvgAEGCMIAAh4IgyAAIAAB4IgsAAIAAkXIAsAAIAAB4IAyAAIAAh4IAtAAIAAEXgABnCMIgqhwIgNAZIAABXIgsAAIAAhXIgNgZIgqBwIguAAIA8iaIg8h9IArAAIA6B5IAAh5IAsAAIAAB5IA5h5IAsAAIg+B9IA+CagAk8CMIAAjIIgeDIIgpAAIghjFIAADFIgmAAIAAkXIA9AAIAhDGIAdjGIA9AAIAAEXgAujCMIAAkXIBCAAQARAAANAEQAMAEAIAJQAHAHAEAMQAEAMABAQIAAAKQAAAXgIANQgGANgQAIQAJAEAGAEQAHAFADAIQAJAPAAAWIAAAYQAAAggSAQQgHAJgNAFQgMAEgRAAgAt3BkIAZAAQALAAAGgGQAFgGAAgPIAAgZQAAgUgGgGQgHgIgPAAIgTAAgAt3gZIARAAQAMgBAIgFQAGgGAAgSIAAgPQAAgPgGgHQgEgHgMAAIgVAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ18, new cjs.Rectangle(-93.2,-14.2,186.5,28.5), null);


(lib.Символ17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("ACbDvQgIgDgGgGQgLgMAAgWIAAhhQAAgWALgMQAGgGAIgDQAIgDALAAQAVAAALAMQAGAGADAJQADAIAAALIAABhQAAALgDAIQgDAJgGAGQgFAGgIADQgIADgLAAQgLAAgIgDgACjBUQgEADAAALIAABjQAAAKAEAEQAEAFAHAAQAHAAAEgFQAEgEAAgKIAAhjQAAgLgEgDQgEgEgHAAQgHAAgEAEgAjxDvQgIgDgGgGQgLgMAAgWIAAhhQAAgWALgMQAGgGAIgDQAIgDALAAQAVAAALAMQAGAGADAJQADAIAAALIAABhQAAALgDAIQgDAJgGAGQgFAGgIADQgJADgKAAQgLAAgIgDgAjpBUQgEADAAALIAABjQAAAKAEAEQAEAFAHAAQAHAAAEgFQAEgEAAgKIAAhjQAAgLgEgDQgEgEgHAAQgHAAgEAEgApgDvQgIgDgGgGQgLgMAAgWIAAhhQAAgWALgMQAGgGAIgDQAJgDAKAAQAVAAAMAMQAGAGACAJQADAIAAALIAABhQAAALgDAIQgCAJgGAGQgGAGgIADQgIADgLAAQgKAAgJgDgApYBUQgEADAAALIAABjQAAAKAEAEQAFAFAGAAQAHAAAEgFQAEgEAAgKIAAhjQAAgLgEgDQgEgEgHAAQgGAAgFAEgAsxDvQgJgDgFgGQgLgMAAgWIAAhhQAAgWALgMQAFgGAJgDQAIgDALAAQAVAAAKAMQAGAGADAJQACAIAAALIAAASIgbAAIAAgTQAAgLgEgDQgDgEgIAAQgHAAgEAEQgEADAAALIAABjQAAAKAEAEQAEAEAHAAQAIAAADgEQAEgEAAgKIAAgaIAbAAIAAAZQAAALgCAIQgDAJgGAGQgEAGgJADQgIADgKAAQgLAAgIgDgAFlDwIAAieIgeAAIAAgbIBaAAIAAAbIgfAAIAACegADtDwIAAi5IAqAAQAWAAAKAMQALAMAAAWIAAAYQAAAWgLAMQgFAGgIADQgIACgLAAIgOAAIAABGgAEJCQIAOAAQAGAAAFgEQADgDAAgKIAAgcQAAgKgDgEQgFgDgGAAIgOAAgAAgDwIAAghIgNAAQgLAAgIgDQgHgDgGgFQgKgMAAgWIAAgyQAAgXAKgMQAGgGAHgCQAIgDALAAIANAAIAAgLIAdAAIAAALIAOAAQAWAAAKALQAMAMAAAXIAAAyQAAAWgMAMQgFAFgIADQgIADgLAAIgOAAIAAAhgAA9C1IAOAAQAHAAAEgEQADgEAAgJIAAg2QAAgLgDgDQgEgEgHAAIgOAAgAAIBgQgDADgBALIAAA2QABAJADAEQADAEAIAAIANAAIAAhZIgNAAQgIAAgDAEgAhCDwIAAiFIgTCFIgcAAIgWiDIAACDIgZAAIAAi5IAoAAIAWCDIAUiDIAoAAIAAC5gAkzDwIgchKIgJARIAAA5IgdAAIAAi5IAdAAIAABRIAnhRIAdAAIgpBSIApBngAnNDwIAAiGIgkCGIgdAAIAAi5IAaAAIAABvIAdhvIAkAAIAAC5gArhDwIAAi5IAsAAQALAAAIADQAJACAEAGQAFAFAEAIQABAIAAALIAAAGQAAAOgDAKQgGAJgJAEQAGADAEADQAFAEACAFQAEAKAAAPIAAAPQAAAVgLALQgFAGgIADQgJADgKAAgArEDVIARAAQAHAAAEgEQADgEAAgKIAAgQQAAgNgDgEQgGgFgJAAIgNAAgArECCIALAAQAJAAAEgEQAEgEABgLIAAgKQgBgLgDgEQgEgEgHAAIgOAAgAoAAtIAAgWIBAAAIAAAWgAhvgcIAIgaIgLAAIAAgcIAcAAIAAAZIgNAdgAGQghIAAgVIhNAAIAAi5IAdAAIAACeIAhAAIAAieIAeAAIAACeIAOAAIAAAwgArjghIAAgVIhKAAIAAAVIgdAAIAAgwIAKABQAHAAAFgEQAFgDAAgLIAAiNIBbAAIAACeIAQAAIAAAwgAsShkQAAALgCAIIAkAAIAAiDIgiAAgADJg3QgJgDgFgGQgMgMAAgWIAAhhQAAgWAMgMQAFgGAJgDQAIgDALAAQAVAAAMAMQAFAGACAJQAEAIAAALIAABhQAAALgEAIQgCAJgFAGQgGAGgIADQgJADgKAAQgLAAgIgDgADRjSQgFADAAALIAABjQAAAKAFAEQAEAFAHAAQAGAAAEgFQAEgEABgKIAAhjQgBgLgEgDQgEgEgGAAQgHAAgEAEgArBg2IAAgbIAKABQAHAAAFgEQAFgDAAgLIAAiNIBbAAIAAC5IgdAAIAAieIghAAIAABwQAAAOgDAJQgEAJgGAFQgGAFgHACQgIACgIAAgAMQg2IAAieIgfAAIAAgbIBaAAIAAAbIgeAAIAACegALKg2IAAiGIgkCGIgeAAIAAi5IAaAAIAABvIAehvIAkAAIAAC5gAJWg2IAAhPIgiAAIAABPIgdAAIAAi5IAdAAIAABPIAiAAIAAhPIAdAAIAAC5gAG3g2IAAi5IBPAAIAAAbIgxAAIAAAzIAnAAIAAAaIgnAAIAAA2IAxAAIAAAbgABqg2IAAieIgeAAIAAgbIBZAAIAAAbIgeAAIAACegAAog2IgchKIgIARIAAA5IgcAAIAAi5IAcAAIAABRIAmhRIAcAAIgoBSIAoBngAifg2IgYhJIgYBJIgcAAIAhhfIgehaIAeAAIAWBEIAWhEIAbAAIgeBaIAgBfgAlEg2IAAi5IBPAAIAAAbIgyAAIAAAzIAoAAIAAAaIgoAAIAAA2IAyAAIAAAbgAmNg2IAAieIgeAAIAAgbIBaAAIAAAbIgeAAIAACegAn9g2IAAhLIgKAAQgLAAgEAFQgFAFABANIgBAsIgDAIIgdAAIADgLIAAgoQAAgPAFgKQAEgKAKgEQgJgFgEgJQgFgKAAgOIAAgOQAAgWAKgKQAFgGAIgCQAJgDALAAIArAAIAAC5gAoXjQQgDAEAAALIAAASQAAALAEAEQAFAEAIAAIAMAAIAAg4IgPAAQgHAAgEAEg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ17, new cjs.Rectangle(-84.3,-24.1,168.6,48.3), null);


(lib.Символ16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E40034").s().p("AJLGPQgNgGgKgKQgTgUAAgmIAAikQAAgmATgUQAKgKANgGQAOgEASAAQAlgBAUAVQAJAKAFAPQAFAOAAATIAACkQAAATgFAOQgFAPgJAKQgLAKgNAGQgOAEgTAAQgSAAgOgEgAJZCGQgHAHAAARIAACqQAAARAHAHQAHAHALAAQANAAAGgHQAHgHAAgRIAAiqQAAgRgHgHQgGgHgNABQgLgBgHAHgANAGQIAAiHIg5AAIAACHIgxAAIAAk6IAxAAIAACGIA5AAIAAiGIAyAAIAAE6gAHVGQIAAjjIg+DjIgyAAIAAk6IAsAAIAAC8IAyi8IA+AAIAAE6gAEcGQIgIg5Ig9AAIgIA5IguAAIAzk6IBIAAIAyE6gAENEsIgYifIgYCfIAwAAgAAGGQIAAk6IBJAAQAlAAATATQASAVAAAmIAAAoQAAAngSATQgKAKgNAFQgOAEgTABIgXAAIAAB2gAA4DuIAXAAQALAAAHgIQAGgFAAgRIAAgwQAAgQgGgHQgHgGgLAAIgXAAgAF9BEIAAglIBtAAIAAAlgAoSABIAAgjIh/AAIAAAjIgyAAIAAhPIARAAQAMAAAIgGQAJgGAAgTIAAjvICcAAIAAEOIAZAAIAABPgApkhwQAAAUgEAOIA9AAIAAjhIg5AAgAh/giIAAgsIARAAQALAAAJgGQAIgGAAgTIAAjvICbAAIAAE6IgxAAIAAkNIg4AAIAAC/QAAAYgGAPQgGAPgKAJQgKAJgNADQgNAFgOAAgANGgiIAAjjIg+DjIgzAAIAAk6IAtAAIAAC8IAyi8IA+AAIAAE6gAKAgiIAAk6IAxAAIAAE6gAHVgiIAAk6IAyAAIAAB2IAXAAQAlgBATAVQASAUAAAlIAAApQAAAngSATQgKAKgNAFQgOAFgTAAgAIHhOIAXAAQAMAAAGgHQAGgGAAgSIAAgvQAAgRgGgGQgGgGgMAAIgXAAgAF/giIAAiGIg4AAIAACGIgxAAIAAk6IAxAAIAACHIA4AAIAAiHIAzAAIAAE6gABtgiIAAk6IAyAAIAAB2IAXAAQAlgBATAVQASAUAAAlIAAApQAAAngSATQgKAKgNAFQgOAFgTAAgACfhOIAXAAQAMAAAGgHQAHgGAAgSIAAgvQAAgRgHgGQgGgGgMAAIgXAAgAi6giIgJg5Ig8AAIgJA5IgtAAIAyk6IBJAAIAyE6gAjJiGIgYieIgYCeIAwAAgAnMgiIAAk6ICHAAIAAAtIhVAAIAABXIBEAAIAAAtIhEAAIAABdIBVAAIAAAsgAsBgiIAAjjIg+DjIgyAAIAAk6IAsAAIAAC8IAzi8IA9AAIAAE6gALultIAAglIBtAAIAAAlg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ16, new cjs.Rectangle(-88.2,-40.3,176.5,80.7), null);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AD6D2QgKgDgGgHQgNgOAAgaIAAhwQAAgaANgOQAGgHAKgDQAKgEAMAAQAYAAANAOQAHAHADAKQADAKAAANIAAAVIggAAIAAgXQAAgMgEgFQgFgEgJAAQgHAAgFAEQgFAFAAAMIAAB0QAAAMAFAFQAFAEAHAAQAJAAAFgEQAEgFAAgMIAAgfIAgAAIAAAdQAAANgDAKQgDAKgHAHQgGAHgKADQgIAEgNAAQgMAAgKgEgAldD2QgJgDgHgHQgMgOAAgaIAAhwQAAgaAMgOQAHgHAJgDQAJgEANAAQAZAAANAOQAGAHADAKQADAKAAANIAAAVIggAAIAAgXQAAgMgEgFQgFgEgJAAQgHAAgFAEQgFAFABAMIAAB0QgBAMAFAFQAFAEAHAAQAJAAAFgEQAEgFAAgMIAAgfIAgAAIAAAdQAAANgDAKQgDAKgGAHQgGAHgKADQgKAEgMAAQgNAAgJgEgAnVD2QgKgDgGgHQgOgOAAgaIAAhwQAAgaAOgOQAGgHAKgDQAKgEAMAAQAZAAANAOQAGAHADAKQAEAKAAANIAABwQAAANgEAKQgDAKgGAHQgHAHgJADQgKAEgMAAQgMAAgKgEgAnMBBQgEAFgBAMIAAB0QABAMAEAFQAFAEAIAAQAIAAAFgEQAEgFAAgMIAAh0QAAgMgEgFQgFgEgIAAQgIAAgFAEgAKND3IgFgmIgqAAIgFAmIggAAIAjjXIAxAAIAiDXgAKDCzIgRhsIgQBsIAhAAgAHGD3IAAjXIAzAAQANABAJADQAKADAGAGQAGAGADAJQADAKAAAMIAAAIQAAAQgFALQgGALgLAFQAHADAFAEQAFAEACAGQAHAMAAARIAAASQgBAZgNANQgGAGgJADQgKAEgNgBgAHoDZIATAAQAJAAAEgFQAEgFAAgLIAAgTQAAgPgEgGQgGgFgLAAIgPAAgAHoB4IANAAQAJAAAGgFQAFgEAAgNIAAgNQAAgLgEgGQgEgFgIAAIgRAAgAFyD3IAAi4IgkAAIAAgfIBpAAIAAAfIgjAAIAAC4gACmD3IAAhcIgnAAIAABcIgiAAIAAjXIAiAAIAABdIAnAAIAAhdIAiAAIAADXgAAsD3IgGgmIgoAAIgGAmIgfAAIAijXIAxAAIAjDXgAAiCzIgQhsIgRBsIAhAAgAiRD3IAAjXIAyAAQAaAAAMAOQANAOAAAaIAAAbQAAAagNAOQgHAHgIAEQgKACgNAAIgQAAIAABRgAhvCIIAQAAQAHAAAGgFQAEgDAAgMIAAghQAAgLgEgFQgGgEgHAAIgQAAgAjmD3IAAi4IgjAAIAAgfIBpAAIAAAfIgjAAIAAC4gApiD3IAAjXIAxAAQAaAAANAOQAMAOAAAaIAAAbQAAAagMAOQgHAHgJAEQgKACgNAAIgPAAIAABRgApACIIAPAAQAIAAAFgFQAEgDAAgMIAAghQAAgLgEgFQgFgEgIAAIgPAAgAqdD3IAAi4IgnAAIAAC4IgiAAIAAjXIBrAAIAADXgAjegHIAAgZIhVAAIAAAZIgjAAIAAg3IAMAAQAIAAAGgEQAFgEAAgMIAAilIBrAAIAAC5IARAAIAAA3gAkVhVQAAAOgCAJIApAAIAAiaIgnAAgAmoghQgJgDgHgHQgOgOAAgaIAAhwQAAgaAOgOQAHgHAJgEQAJgDANAAQAZAAANAOQAGAHADAKQAEAKAAANIAABwQAAANgEAKQgDAKgGAHQgHAHgJADQgKAEgMAAQgNAAgJgEgAmfjWQgFAFAAAMIAAB0QAAAMAFAFQAFAEAIAAQAIAAAEgEQAFgFAAgMIAAh0QAAgMgFgFQgEgEgIAAQgIAAgFAEgAogghQgKgDgGgHQgNgOAAgaIAAhwQAAgaANgOQAGgHAKgEQAJgDANAAQAZAAANAOQAGAHADAKQADAKAAANIAAAVIggAAIAAgXQAAgMgFgFQgEgEgIAAQgIAAgFAEQgEAFAAAMIAAB0QAAAMAEAFQAFAEAIAAQAIAAAEgEQAFgFAAgMIAAgfIAgAAIAAAdQAAANgDAKQgDAKgGAHQgHAHgKADQgJAEgMAAQgNAAgJgEgALIggIAAibIgqCbIgjAAIAAjXIAfAAIAACBIAjiBIApAAIAADXgAJEggIAAibIgpCbIgjAAIAAjXIAeAAIAACBIAiiBIArAAIAADXgAG9ggIAAhcIgmAAIAABcIgiAAIAAjXIAiAAIAABdIAmAAIAAhdIAiAAIAADXgAFEggIgHgmIgpAAIgFAmIggAAIAjjXIAyAAIAiDXgAE5hkIgQhsIgQBsIAgAAgADHggIghhVIgLATIAABCIghAAIAAhCIgLgTIggBVIgjAAIAvh3IgvhgIAhAAIAtBeIAAheIAhAAIAABeIAtheIAiAAIgvBgIAvB3gAg9ggIAAjXIAyAAQAYAAANAOQAMAOAAAaIAAAbQAAAagMAOQgGAHgJAEQgLACgLAAIgQAAIAABRgAgbiPIAQAAQAIAAAEgFQADgDAAgMIAAghQAAgLgDgFQgEgEgIAAIgQAAgAitggIAAjXIBcAAIAAAfIg6AAIAAA8IAuAAIAAAfIguAAIAAA/IA6AAIAAAegArmggIAAjXIAzAAQAOAAAKAEQAJADAFAGQAHAGADAJQADAKAAAMIAAAIQgBAQgFALQgFALgMAFQAIADAEAEQAGAEACAGQAGAMAAARIAAASQAAAYgNAOQgGAGgKADQgJAEgOgBgArEg+IATAAQAJAAAFgFQAEgFAAgMIAAgSQAAgPgFgGQgFgFgLgBIgQAAgArEifIAOAAQAJAAAFgFQAGgEAAgNIAAgNQAAgLgFgGQgDgFgJAAIgRAAg");
	this.shape.setTransform(74.1,-0.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ15, new cjs.Rectangle(-0.1,-25.6,148.5,50), null);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgorAIIIAAwPMBRXAAAIAAQPg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ14, new cjs.Rectangle(-260.4,-52,520.8,104), null);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E40034").s().p("AgJG6IAAtzIATAAIAANzg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ13, new cjs.Rectangle(-1,-44.2,2,88.4), null);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgnCATiMAAAgnDMBOFAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ10, new cjs.Rectangle(-249.9,-124.9,499.8,250), null);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.inter3();
	this.instance.parent = this;
	this.instance.setTransform(-300,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ9, new cjs.Rectangle(-300,-150,600,300), null);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.inter2();
	this.instance.parent = this;
	this.instance.setTransform(-300,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ8, new cjs.Rectangle(-300,-150,600,300), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.inter1();
	this.instance.parent = this;
	this.instance.setTransform(-300,-150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(-300,-150,600,300), null);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.logo2();
	this.instance.parent = this;
	this.instance.setTransform(-100,-68.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(-100,-68.5,200,137), null);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgnCATiMAAAgnDMBOFAAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ5, new cjs.Rectangle(-249.9,-125,499.8,250), null);


(lib.Символ1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(301.3,153.1,0.987,0.987,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ1, new cjs.Rectangle(-301,-153,602.3,306.1), null);


(lib.Символ45 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ47();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ45, new cjs.Rectangle(-297,-147,598,298), null);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ50();
	this.instance.parent = this;
	this.instance.setTransform(0.1,23.3,0.62,0.62);

	this.instance_1 = new lib.Символ49();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.1,-30.2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E40034").ss(2,1,1).p("EgpVAAAMBSrAAA");
	this.shape.setTransform(0,-9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ23, new cjs.Rectangle(-265.5,-46,531.2,92), null);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ14();
	this.instance.parent = this;
	this.instance.alpha = 0.738;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ12, new cjs.Rectangle(-260.4,-52,520.8,104), null);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ10();
	this.instance.parent = this;
	this.instance.filters = [new cjs.BlurFilter(22, 22, 1)];
	this.instance.cache(-252,-127,504,254);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ11, new cjs.Rectangle(-260.9,-135.9,524,275), null);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 2
	this.instance = new lib.Символ6();
	this.instance.parent = this;
	this.instance.setTransform(0,-0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 1
	this.instance_1 = new lib.Символ5();
	this.instance_1.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ4, new cjs.Rectangle(-249.9,-125,499.8,250), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgnDATiMAAAgnDMBOHAAAMAAAAnDg");

	// Слой 10
	this.instance = new lib.Символ19();
	this.instance.parent = this;
	this.instance.setTransform(106.6,0.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(299).to({_off:false},0).to({x:131.6,alpha:1},15,cjs.Ease.get(1)).wait(45).to({x:106.6,alpha:0},15).to({_off:true},1).wait(30));

	// Слой 6
	this.instance_1 = new lib.Символ18();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-94.2,0.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(299).to({_off:false},0).to({x:-123.7,alpha:1},15,cjs.Ease.get(1)).wait(45).to({x:-94.2,alpha:0},15,cjs.Ease.get(1)).to({_off:true},1).wait(30));

	// Слой 5
	this.instance_2 = new lib.Символ17();
	this.instance_2.parent = this;
	this.instance_2.setTransform(84.3,1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(184).to({_off:false},0).to({x:125.5,alpha:1},15,cjs.Ease.get(1)).wait(45).to({x:84.3,alpha:0},15).to({_off:true},1).wait(145));

	// Слой 4
	this.instance_3 = new lib.Символ16();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-90.5,-0.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(184).to({_off:false},0).to({x:-130.5,alpha:1},15,cjs.Ease.get(1)).wait(45).to({x:-90.5,alpha:0},15,cjs.Ease.get(1)).to({_off:true},1).wait(145));

	// Слой 3
	this.instance_4 = new lib.Символ15();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,0.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(69).to({_off:false},0).to({x:50,alpha:1},14,cjs.Ease.get(1)).wait(47).to({x:0,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(260));

	// Слой 9
	this.instance_5 = new lib.Символ91();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-76,1.2,0.731,0.731);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(69).to({_off:false},0).to({x:-128,alpha:1},14,cjs.Ease.get(1)).wait(47).to({x:-76,alpha:0},14,cjs.Ease.get(1)).to({_off:true},1).wait(260));

	// Слой 8
	this.instance_6 = new lib.Символ13();
	this.instance_6.parent = this;
	this.instance_6.setTransform(0,0,1,0.104);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(69).to({_off:false},0).to({scaleY:1,alpha:1},7,cjs.Ease.get(0.98)).wait(61).to({scaleY:0.1,alpha:0},7,cjs.Ease.get(1)).wait(40).to({scaleY:1,alpha:1},7,cjs.Ease.get(1)).wait(61).to({scaleY:0.1,alpha:0},7,cjs.Ease.get(1)).wait(40).to({scaleY:1,alpha:1},7,cjs.Ease.get(1)).wait(61).to({scaleY:0.1,alpha:0},7,cjs.Ease.get(1)).wait(31));

	// Слой 7
	this.instance_7 = new lib.Символ12();
	this.instance_7.parent = this;
	this.instance_7.setTransform(249.2,0,1,1,180);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(59).to({_off:false},0).to({x:1.2,alpha:1},10,cjs.Ease.get(1)).wait(75).to({x:249.2,alpha:0},10,cjs.Ease.get(1)).wait(20).to({x:1.2,alpha:1},10,cjs.Ease.get(1)).wait(75).to({x:249.2,alpha:0},10,cjs.Ease.get(1)).wait(20).to({x:1.2,alpha:1},10,cjs.Ease.get(1)).wait(75).to({x:249.2,alpha:0},10,cjs.Ease.get(1)).to({_off:true},1).wait(20));

	// inter1.jpg
	this.instance_8 = new lib.Символ7();
	this.instance_8.parent = this;
	this.instance_8.setTransform(-501.5,0,0.833,0.833);
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(269).to({_off:false},0).wait(1).to({x:-441},0).wait(1).to({x:-384.6},0).wait(1).to({x:-333.1},0).wait(1).to({x:-286.7},0).wait(1).to({x:-245.4},0).wait(1).to({x:-209.2},0).wait(1).to({x:-177.6},0).wait(1).to({x:-150.5},0).wait(1).to({x:-127.4},0).wait(1).to({x:-108.2},0).wait(1).to({x:-92.6},0).wait(1).to({x:-79.9},0).wait(1).to({x:-69},0).wait(1).to({x:-59.3},0).wait(1).to({x:-50.1},0).wait(1).to({x:-40.9},0).wait(1).to({x:-31.4},0).wait(1).to({x:-21.4},0).wait(1).to({x:-11},0).wait(1).to({x:0},0).wait(96).to({y:27.2},0).wait(1).to({y:53.3},0).wait(1).to({y:77.9},0).wait(1).to({y:100.6},0).wait(1).to({y:121.2},0).wait(1).to({y:139.6},0).wait(1).to({y:155.9},0).wait(1).to({y:170.1},0).wait(1).to({y:182.5},0).wait(1).to({y:192.9},0).wait(1).to({y:201.5},0).wait(1).to({y:208.9},0).wait(1).to({y:215.2},0).wait(1).to({y:220.8},0).wait(1).to({y:225.8},0).wait(1).to({y:230.6},0).wait(1).to({y:235.4},0).wait(1).to({y:240.3},0).wait(1).to({y:245.5},0).wait(1).to({y:251.2},0).wait(1));

	// inter2.jpg
	this.instance_9 = new lib.Символ8();
	this.instance_9.parent = this;
	this.instance_9.setTransform(501.3,0,0.833,0.833);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(154).to({_off:false},0).wait(1).to({x:427.5},0).wait(1).to({x:366.1},0).wait(1).to({x:315.2},0).wait(1).to({x:272.8},0).wait(1).to({x:236.9},0).wait(1).to({x:205.7},0).wait(1).to({x:177.9},0).wait(1).to({x:152.3},0).wait(1).to({x:129.1},0).wait(1).to({x:108.6},0).wait(1).to({x:90.8},0).wait(1).to({x:75.4},0).wait(1).to({x:62},0).wait(1).to({x:50.4},0).wait(1).to({x:40},0).wait(1).to({x:30.8},0).wait(1).to({x:22.3},0).wait(1).to({x:14.4},0).wait(1).to({x:7},0).wait(1).to({x:0},0).wait(96).to({x:60.5},0).wait(1).to({x:116.9},0).wait(1).to({x:168.4},0).wait(1).to({x:214.8},0).wait(1).to({x:256.1},0).wait(1).to({x:292.4},0).wait(1).to({x:323.9},0).wait(1).to({x:351.1},0).wait(1).to({x:374.2},0).wait(1).to({x:393.4},0).wait(1).to({x:408.9},0).wait(1).to({x:421.7},0).wait(1).to({x:432.5},0).wait(1).to({x:442.2},0).wait(1).to({x:451.5},0).wait(1).to({x:460.7},0).wait(1).to({x:470.2},0).wait(1).to({x:480.1},0).wait(1).to({x:490.6},0).wait(1).to({x:501.6},0).to({_off:true},1).wait(115));

	// inter3.jpg
	this.instance_10 = new lib.Символ9();
	this.instance_10.parent = this;
	this.instance_10.setTransform(0,250.5,0.833,0.833);

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(40).to({y:216.2},0).wait(1).to({y:183.7},0).wait(1).to({y:154.1},0).wait(1).to({y:128.1},0).wait(1).to({y:106},0).wait(1).to({y:87.6},0).wait(1).to({y:72.6},0).wait(1).to({y:60.4},0).wait(1).to({y:50},0).wait(1).to({y:41},0).wait(1).to({y:33.4},0).wait(1).to({y:27},0).wait(1).to({y:21.6},0).wait(1).to({y:17.1},0).wait(1).to({y:13.2},0).wait(1).to({y:9.9},0).wait(1).to({y:7},0).wait(1).to({y:4.5},0).wait(1).to({y:2.1},0).wait(1).to({y:0},0).wait(96).to({x:-73.7},0).wait(1).to({x:-135.2},0).wait(1).to({x:-186.1},0).wait(1).to({x:-228.4},0).wait(1).to({x:-264.4},0).wait(1).to({x:-295.5},0).wait(1).to({x:-323.4},0).wait(1).to({x:-349},0).wait(1).to({x:-372.2},0).wait(1).to({x:-392.6},0).wait(1).to({x:-410.4},0).wait(1).to({x:-425.9},0).wait(1).to({x:-439.2},0).wait(1).to({x:-450.9},0).wait(1).to({x:-461.2},0).wait(1).to({x:-470.5},0).wait(1).to({x:-479},0).wait(1).to({x:-486.8},0).wait(1).to({x:-494.2},0).wait(1).to({x:-501.2},0).to({_off:true},1).wait(230));

	// Слой 2
	this.instance_11 = new lib.Символ4();
	this.instance_11.parent = this;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(40).to({y:-34.2},0).wait(1).to({y:-66.7},0).wait(1).to({y:-96.4},0).wait(1).to({y:-122.3},0).wait(1).to({y:-144.5},0).wait(1).to({y:-162.9},0).wait(1).to({y:-177.8},0).wait(1).to({y:-190},0).wait(1).to({y:-200.5},0).wait(1).to({y:-209.5},0).wait(1).to({y:-217},0).wait(1).to({y:-223.4},0).wait(1).to({y:-228.8},0).wait(1).to({y:-233.3},0).wait(1).to({y:-237.2},0).wait(1).to({y:-240.5},0).wait(1).to({y:-243.4},0).wait(1).to({y:-246},0).wait(1).to({y:-248.3},0).wait(1).to({y:-250.5},0).wait(326).to({y:-223.4},0).wait(1).to({y:-197.4},0).wait(1).to({y:-172.9},0).wait(1).to({y:-150.2},0).wait(1).to({y:-129.6},0).wait(1).to({y:-111.3},0).wait(1).to({y:-95.1},0).wait(1).to({y:-80.9},0).wait(1).to({y:-68.5},0).wait(1).to({y:-58.2},0).wait(1).to({y:-49.5},0).wait(1).to({y:-42.2},0).wait(1).to({y:-35.9},0).wait(1).to({y:-30.3},0).wait(1).to({y:-25.3},0).wait(1).to({y:-20.5},0).wait(1).to({y:-15.8},0).wait(1).to({y:-10.9},0).wait(1).to({y:-5.7},0).wait(1).to({y:0},0).wait(1));

	// Слой 12
	this.instance_12 = new lib.Символ11();
	this.instance_12.parent = this;
	this.instance_12.setTransform(0.6,10.6,1.026,1);
	this.instance_12.alpha = 0.789;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(405));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-266.9,-125.3,538,275);


(lib.Символ6_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance_1 = new lib.Символ53();
	this.instance_1.parent = this;
	new cjs.ButtonHelper(this.instance_1, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6_1, new cjs.Rectangle(-115,-36.5,230,73), null);


(lib.Символ46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ45();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.711},14,cjs.Ease.get(1)).to({alpha:1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-297,-147,598,298);


(lib.Символ21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 3
	this.instance = new lib.Символ23();
	this.instance.parent = this;
	this.instance.setTransform(4.8,-24.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Слой 2
	this.instance_1 = new lib.Символ46();
	this.instance_1.parent = this;
	this.instance_1.setTransform(4.5,5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ22();
	this.instance_2.parent = this;
	this.instance_2.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ21, new cjs.Rectangle(-321.6,-169,643.2,338.1), null);


(lib.Символ7_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1 - копия
	this.instance_1 = new lib.Символ6_1();
	this.instance_1.parent = this;
	this.instance_1.alpha = 0;
	this.instance_1.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1.06,scaleY:1.06,alpha:0.07},14,cjs.Ease.get(-1)).to({scaleX:1.13,scaleY:1.13,alpha:0.148},15,cjs.Ease.get(1)).to({scaleX:1.07,scaleY:1.07,alpha:0.07},15,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,alpha:0},15,cjs.Ease.get(1)).wait(1));

	// Слой 1
	this.instance_2 = new lib.Символ6_1();
	this.instance_2.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1.06,scaleY:1.06},14,cjs.Ease.get(-1)).to({scaleX:1.13,scaleY:1.13},15,cjs.Ease.get(1)).to({scaleX:1.07,scaleY:1.07},15,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},15,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115,-36.5,230,73);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_13 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(13).call(this.frame_13).wait(13));

	// Слой 1
	this.instance = new lib.Символ7_1();
	this.instance.parent = this;
	this.instance.setTransform(0,215.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(6).to({_off:false},0).to({scaleX:1.09,scaleY:1.09,y:79.1},6,cjs.Ease.get(1)).wait(1).to({scaleX:1,scaleY:1,y:215.1},6,cjs.Ease.get(1)).to({_off:true},1).wait(6));

	// Слой 3
	this.instance_1 = new lib.Символ21();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,754.4,1,1,57.1,0,0,4.5,759.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({rotation:-5.7,x:0.2,y:754.3},8).to({rotation:0,x:0.1},4).wait(1).to({rotation:-5.7,x:0.2},4).to({rotation:57.1,x:0,y:754.4},8).wait(1));

	// Слой 1
	this.main1 = new lib.Символ2();
	this.main1.parent = this;
	this.main1.setTransform(0,754.2,1,1,0,0,0,0,754.1);

	this.timeline.addTween(cjs.Tween.get(this.main1).to({regX:0.1,regY:754.2,rotation:5.2,y:754.3},4).to({regX:0,regY:754.1,rotation:-60,y:754.2},8).wait(1).to({regX:0.1,regY:754.2,rotation:5.2,y:754.3},8).to({regX:0,regY:754.1,rotation:0,y:754.2},4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-266.9,-125.3,1218.2,824.7);


// stage content:
(lib.zilart600300_v2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		document.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
		window.open(clickTAG, "_blank");
		}
		
		var _this = this;
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		  function fl_MouseOverHandler_5()
		{
		    _this.main.gotoAndPlay(1);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		  function fl_MouseOutHandler_2()
		{
		    _this.main.gotoAndPlay(15);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Слой 2
	this.main = new lib.Символ20();
	this.main.parent = this;
	this.main.setTransform(300,150);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

	// Слой 1
	this.instance = new lib.Символ1();
	this.instance.parent = this;
	this.instance.setTransform(300,150);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(299,147,1252.3,852.4);
// library properties:
lib.properties = {
	width: 600,
	height: 300,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1496051968949", id:"bg"},
		{src:"images/btn.png?1496051968949", id:"btn"},
		{src:"images/inter1.jpg?1496051968949", id:"inter1"},
		{src:"images/inter2.jpg?1496051968949", id:"inter2"},
		{src:"images/inter3.jpg?1496051968949", id:"inter3"},
		{src:"images/logo2.png?1496051968949", id:"logo2"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;